CREATE PROCEDURE OW_LAO.PROC_D2C_AR_ONE_VIEW_TABLE AS
BEGIN 
--D2C_AR_ONE_VIEW_TABLE
	
--Truncate Table OW_LAO.TF_D2C_AR_ONE_VIEW_TABLE_01
TRUNCATE TABLE OW_LAO.TF_D2C_AR_ONE_VIEW_TABLE_01;
	
	
INSERT INTO OW_LAO.TF_D2C_AR_ONE_VIEW_TABLE_01
--DROP TABLE OW_LAO.TF_D2C_AR_ONE_VIEW_TABLE_01
--CREATE TABLE OW_LAO.TF_D2C_AR_ONE_VIEW_TABLE_01 AS ( 
SELECT	DISTINCT
	
	--,OW_LAO.AFFILIATE_ID_ADJUSTED(OVSBSDESS.ID_STORE, RVSBSSOL.AFFILIATE_ID, RVSBSSOL.SALES_CHANNEL) AS AFFILIATE_ID_ADJUSTED
	--,DAC.AFFILIATE_CHANNEL
	 MAC.CUSTOMER_NAME_SUMMARY AS AFFILIATE_CHANNEL
	,MAC.CUSTOMER_NAME_DETAIL AS AFFILIATE_SUB_CHANNEL
	,ONFNCLIDOI.CUSTOMER
	,ONFNCLIDOI.DOCUMENT_TYPE
	,ONFNCLIDOI.POSTING_KEY
	,ONFNCLIDOI.PAYMENT_TERMS 
	,ONFNCLIDOI.REFERENCE
	,ONFNCLIDOI.DOCUMENT_DATE
	,ONFNCLIDOI.AMOUNT_IN_LOCAL_CURRENCY
	,ONFNCLIDOI.NET_DUE_DATE
	,ONFNCLIDOI.ARREARS_BY_NET_DUE_DATE
	,ONFNCLIDOI.DOCUMENT_NUMBER
	,IFNULL(MAAA."ASSIGNMENT",ONFNCLIDOI."ASSIGNMENT") AS "ASSIGNMENT"
	--,ONFNCLIDOI."ASSIGNMENT"
	,ONFNCLIDOI."TEXT" 
	,ONFNCLIDOI.REASON_CODE 
	,ONFNCLIDOI.ENTRY_DATE 
	,ONFNCLIDOI."G/L_ACCOUNT" 
	,ONFNCLIDOI.BILLING_DOCUMENT 
	,ONFNCLIDOI.INVOICE_REFERENCE 	
	,ONFNCLIDOI.POSTING_DATE 
	,ONFNCLIDOI."YEAR/MONTH" 
	,ONFNCLIDOI.USER_NAME 
	
	--,IFNULL(RVSBSSOL."SEQUENCE", MAAA."SEQUENCE") AS "SEQUENCE"
	,RVSBSSOL."SEQUENCE"
	
	,RVSBSSOL.ORDER_ID
	
	--,DAC.AFFILIATE_SUB_CHANNEL
	,RVSBSSOL.STATUS_DESCRIPTION AS VTEX_STATUS
	,(RVSBSSOL.VALUE/100) AS VTEX_AMOUNT
	,IFNULL(URVSBSSOL.SELLING_PRICE,0) AS VTEX_SC_PLUS-- Vtex( SC+)
	,IFNULL(URVSBSSOL2.SELLING_PRICE,0) AS VTEX_INSTAL-- Vtex( INSTAL)
	,(RVSBSSOL.TOTAL_SHIPPING/100) AS VTEX_FREIGHT
	
	
	,OPMO.STATUS AS MKP_STATUS
	,OPMO.SUBTOTAL AS MKP_AMT
	
	,ONZASOT.SALES_DOCUMENT
	,ONZASOT.REJECT_REASON_1
	,(CASE WHEN DRVSBSSOP.VOUCHER_NO IS NULL 
		THEN 'N'
		ELSE 'Y'
	END) AS "VOUCHER (Y/N)"
	,DRVSBSSOP.VOUCHER_NO
	
	--Pegar dados do NERP 
	,COUNT(DISTINCT ONZASOT.DELIVERY) OVER (PARTITION BY ONZASOT.CUSTOMER_PO) AS "DO Count"
	
	,ONZOT.DELIVERY_NO AS DO_NERP
	
	,ONZOT.EPOD AS DO_IOD_NERP --Era EPOD_DATE
	,ONZOT.AR_AMOUNT AS DO_AMT_NERP
	,FUTCA."DO No." AS DO_CELLO
	,FUTCA.DO_STATUS AS DO_STATUS_CELLO
	--Pegar dados do NERP (VER COMO CRIAR O RELACIONAMENTO)
	,ONZDDTIR.RETURN_DO_NO AS RDO_NERP
	,RONZOT.EPOD AS RDO_IOD_NERP -- EPOD_DATE
	,RONZOT.AR_AMOUNT AS RDO_AMT_NERP
	
	,RDAASDC.ID
    ,RDAASDC.COURIER_COLLECT
    ,RDAASDC.TOTAL_AMOUNT
    ,RDAASDC.STATUS_DESCRIPTION
    ,UONZCF.CLAIM_AMT
	,UONZCF.CREDIT_MEMO_NO
	
	,VUTCRT.RDO AS RDO_CELLO
	,VUTCRT.STATUS_NM AS RDO_STATUS_CELLO
	,VUTCRT.IOD_DT AS DO_IOD_CELLO
	,VUTCRT.RDO_RETURN_IOD_DATE AS RDO_IOD_CELLO
	,VUTCRT.RDO_AMT AS RDO_AMT_CELLO
	,VUTCRT.GR_DATE AS RDO_GR_DATE_CELLO
	--,FUTCA.DO_AMT
	,(CASE WHEN ONFNCLIDOI.ARREARS_BY_NET_DUE_DATE > 0
			THEN 'Over'
			ELSE 'In'
		END) AS "In/Over"	
	,(CASE WHEN ONFNCLIDOI.ARREARS_BY_NET_DUE_DATE<=-46
			THEN '* Indue'
		 WHEN ONFNCLIDOI.ARREARS_BY_NET_DUE_DATE BETWEEN -45 AND -38
			THEN '0~7 Indue'
		WHEN ONFNCLIDOI.ARREARS_BY_NET_DUE_DATE BETWEEN -37 AND -30
			THEN '8~15 Indue'
		WHEN ONFNCLIDOI.ARREARS_BY_NET_DUE_DATE BETWEEN -29 AND -15
			THEN '16~30 Indue'
		WHEN ONFNCLIDOI.ARREARS_BY_NET_DUE_DATE BETWEEN -14 AND 0
			THEN '31~45 Indue'
		WHEN ONFNCLIDOI.ARREARS_BY_NET_DUE_DATE BETWEEN 1 AND 7
			THEN '1 ~ 7 days'
		WHEN ONFNCLIDOI.ARREARS_BY_NET_DUE_DATE BETWEEN 8 AND 14
			THEN '8 ~ 14 days'
		WHEN ONFNCLIDOI.ARREARS_BY_NET_DUE_DATE BETWEEN 15 AND 31
			THEN '15 ~ 31 days'	
		WHEN ONFNCLIDOI.ARREARS_BY_NET_DUE_DATE BETWEEN 32 AND 60
			THEN '32 ~ 60 days'
		WHEN ONFNCLIDOI.ARREARS_BY_NET_DUE_DATE BETWEEN 61 AND 90
			THEN '61 ~ 90 days'
		WHEN ONFNCLIDOI.ARREARS_BY_NET_DUE_DATE BETWEEN 91 AND 180
			THEN '91~180 days'
		WHEN ONFNCLIDOI.ARREARS_BY_NET_DUE_DATE BETWEEN 181 AND 360
			THEN '181~360 days'
			ELSE 'Over 360'
	END) AS "Range"
	,(CASE WHEN MTFASC."KEY" IS NULL 
		THEN 'Process Delay'
		ELSE MTFASC."TYPE"
	END) AS "TYPE"
	,(CASE WHEN MTFASC."KEY" IS NULL
		THEN 'Others (In analysis)'
		ELSE MTFASC."1_CATE"
	END) AS "1_CATE"
	,(CASE WHEN MTFASC."KEY" IS NULL
		THEN 'In analysis (1st and 2nd analysis)'
		ELSE MTFASC."2_CATE"
	END) AS "2_CATE"
	,MTFASC."3_CATE"
	,(CASE WHEN MTFASC."KEY" IS NULL
		THEN 'OST'
		ELSE MTFASC.PIC
	END) AS PIC
	,(CASE WHEN MTFASC."KEY" IS NULL
		THEN 'New Open Item'
		ELSE 'Mapped'
	END) AS "NEW_OPEN_ITEM"
	,ONFNCLIDOI.LINE_ITEM
	,IFNULL(ONFNCLIDOI.CUSTOMER,'') || IFNULL(ONFNCLIDOI."ASSIGNMENT",'') || IFNULL(ONFNCLIDOI.DOCUMENT_NUMBER,'') || IFNULL(REPLACE(ONFNCLIDOI.AMOUNT_IN_LOCAL_CURRENCY,'.',','),'') || IFNULL(ONFNCLIDOI.LINE_ITEM,'')  AS "Key"
	,IFNULL(ONFNCLIDOI.CUSTOMER,'') || IFNULL(ONFNCLIDOI."ASSIGNMENT",'') || IFNULL(ONFNCLIDOI.DOCUMENT_NUMBER,'') || IFNULL(REPLACE(ONFNCLIDOI.AMOUNT_IN_LOCAL_CURRENCY,'.',','),'')  AS "Key2"
	--,REPLACE(REPLACE(JSON_VALUE('[' || RVSBSSOL.INVOICE_DATA || ']', '$.userPaymentInfo.paymentMethods'),'[',''),']','') AS VTEX_PAYMENT_METHOD
	,VVP.ACQUIRER
	,VVP.PAYMENT_SYSTEM_NAME_ORIGIN  AS PAYMENT_SYSTEM
	,VVP.PAYMENT_SYSTEM_NAME AS PAYMENT_SYSTEM_NAME
	,NULL AS "ASSIGNMENT_KEY_DISTINTIC"
	,NULL AS "AMOUNT_IN_LOCAL_CURRENCY_KEY_DISTINCT"
	,NOW() AS LAST_UPDATE 
	,NOW() AS LOAD_DATE
FROM OW_SEDA_S.ODS_NERP_FBL5N_CUSTOMER_LINE_ITEM_DISPLAY_OPEN_ITEMS_HIST/*ODS_NERP_FBL5N_CUSTOMER_LINE_ITEM_DISPLAY_OPEN_ITEMS*/ ONFNCLIDOI
LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER RVSBSSOL
	ON (ONFNCLIDOI."ASSIGNMENT" = RVSBSSOL."SEQUENCE"
		OR ONFNCLIDOI."ASSIGNMENT" = RVSBSSOL.ORDER_ID
		OR ONFNCLIDOI.REFERENCE = RVSBSSOL."SEQUENCE")
LEFT JOIN OW_LAO.VIEW_VTEX_PAYMENTS VVP 
	ON (ONFNCLIDOI."ASSIGNMENT" = VVP."SEQUENCE"
		OR ONFNCLIDOI."ASSIGNMENT" = VVP.ORDER_ID)
LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SALES_ORDER RVSBSO  	
	ON (RVSBSSOL.MARKETPLACE_ORDER_ID = RVSBSO.ORDER_ID)
LEFT JOIN U_PRJ_ECOM.ODS_VTEX_SSG_BR_SHOP_DATA_ENTITIES_STORES_SDS OVSBSDESS 
	ON ((CASE WHEN (CASE
				-- CD_STORE_INFORMATION
	       			WHEN RVSBSSOL.CD_STORE_INFORMATION IS NOT NULL 
					THEN RVSBSSOL.CD_STORE_INFORMATION
					ELSE RVSBSO.CD_STORE_INFORMATION
			  END) IS NOT NULL 
				THEN(CASE
					 -- CD_STORE_INFORMATION 
					 WHEN RVSBSSOL.CD_STORE_INFORMATION IS NOT NULL 
					 	THEN RVSBSSOL.CD_STORE_INFORMATION
						ELSE RVSBSO.CD_STORE_INFORMATION
				     END)
				ELSE(CASE
					  -- UTM_SOURCE
					  WHEN RVSBSSOL.UTM_SOURCE IS NOT NULL 
					  	THEN RVSBSSOL.UTM_SOURCE
						ELSE RVSBSO.UTM_SOURCE
				    END)
		END) = OVSBSDESS.ID_STORE)
LEFT JOIN (SELECT DISTINCT RVSBSSOP.ORDER_ID
				,STRING_AGG(RVSBSSOP.GIFT_CARD_ID, ', ') AS GIFT_CARD_ID
				,STRING_AGG(RVSBSSOP.REDEMPTION_CODE, ', ') AS VOUCHER_NO
				,STRING_AGG(RVSBSSOP.TID, ', ') AS TID
			FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_PAYMENT RVSBSSOP
			WHERE	RVSBSSOP.GIFT_CARD_ID IS NOT NULL
				AND RVSBSSOP.REDEMPTION_CODE IS NOT NULL
				AND RVSBSSOP.TID IS NOT NULL
			GROUP BY  RVSBSSOP.ORDER_ID) DRVSBSSOP
	ON (RVSBSSOL.ORDER_ID = DRVSBSSOP.ORDER_ID)	
--Dados de Samsung Care +
LEFT JOIN (SELECT RVSBSSOL.ORDER_ID
				,RVSBSSOL."SEQUENCE"
			    ,STRING_AGG(RVSBSSOI.NAME, ', ') AS NAME
				,STRING_AGG(RVSBSSOI.REF_ID, ', ') AS REF_ID
				,SUM(RVSBSSOI.QUANTITY) AS QUANTITY
			    ,SUM(RVSBSSOI.QUANTITY*(RVSBSSOI.SELLING_PRICE/100)) AS SELLING_PRICE
			FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER RVSBSSOL
			LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_ITEM RVSBSSOI 
				ON (RVSBSSOL.ORDER_ID = RVSBSSOI.ORDER_ID)
			WHERE UPPER(RVSBSSOI.REF_ID) LIKE '%BRASIL%' OR (RVSBSSOI.NAME LIKE '%Samsung Care+%' AND RVSBSSOI.REF_ID IS NULL)
			GROUP BY RVSBSSOL.ORDER_ID, RVSBSSOL."SEQUENCE") URVSBSSOL
	ON (ONFNCLIDOI."ASSIGNMENT" = URVSBSSOL."SEQUENCE" OR ONFNCLIDOI."ASSIGNMENT" = URVSBSSOL.ORDER_ID)
--Dados de Instalação
LEFT JOIN (SELECT RVSBSSOL.ORDER_ID
				,RVSBSSOL."SEQUENCE"
				,STRING_AGG(RVSBSSOI.NAME, ', ') AS NAME
				,STRING_AGG(RVSBSSOI.REF_ID, ', ') AS REF_ID
				,SUM(RVSBSSOI.QUANTITY) AS QUANTITY
				,SUM(RVSBSSOI.QUANTITY*(RVSBSSOI.SELLING_PRICE/100)) AS SELLING_PRICE
			FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER RVSBSSOL
			LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_ITEM RVSBSSOI 
				ON (RVSBSSOL.ORDER_ID = RVSBSSOI.ORDER_ID)
			WHERE UPPER(RVSBSSOI.REF_ID) in ('WSM','AC1','AC2','DTV1','DTV2','DTV3','REF3','REF4','WSM3')
		  	GROUP BY RVSBSSOL.ORDER_ID, RVSBSSOL."SEQUENCE") URVSBSSOL2
	ON (ONFNCLIDOI."ASSIGNMENT" = URVSBSSOL2."SEQUENCE" OR ONFNCLIDOI."ASSIGNMENT" = URVSBSSOL2.ORDER_ID)
LEFT JOIN OW_LAO.ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING ONZASOT 
	ON (RVSBSSOL.ORDER_ID =  ONZASOT.CUSTOMER_PO  OR TO_CHAR(RVSBSSOL."SEQUENCE") =  ONZASOT.CUSTOMER_PO)
LEFT JOIN (SELECT ONZOT.* 
			FROM OW_LAO.ODS_NERP_ZLLEJ50090_OUTBOUND_TRACKING ONZOT
			WHERE  ONZOT.SO_TYPE = 'YS10' AND ONZOT.DO_TYPE = 'ZND1') ONZOT
	ON (ONZASOT.SALES_DOCUMENT =ONZOT.REFERENCE_DOC_SO_PO AND ONZASOT.MATERIAL = ONZOT.MATERIAL
	AND ONZASOT.DELIVERY_ITEM = ONZOT.DELIVERY_ITEM AND ONZASOT.DELIVERY = ONZOT.DELIVERY_NO)
LEFT JOIN (SELECT DISTINCT
				   ONZDDTIR.RETURN_DO_NO
				  ,ONZDDTIR.MATERIAL
				  ,ONZDDTIR.R_SO_ITEM
				  ,ONZDDTIR.R_DO_ITEM
				  ,ONZDDTIR.R_SO_TYPE
				  ,ONZDDTIR.R_DO_TYPE
				  ,ONZDDTIR.O_SO_NO 
				  ,ONZDDTIR.O_DO_NO 
				  ,ONZDDTIR.O_SO_ITEM 
				  ,ONZDDTIR.O_DO_ITEM 
				  ,ONZDDTIR.REMARK 
			FROM OW_LAO.ODS_NERP_ZLLEE50090_DISPLAY_DO_TRACKING_INFO_RETURN ONZDDTIR
			WHERE(R_SO_TYPE = 'YR01' AND R_DO_TYPE = 'ZRC1')
			OR   (R_SO_TYPE = 'YS10' AND R_DO_TYPE = 'ZRLA')
			OR   (R_SO_TYPE = 'YRT1' AND R_DO_TYPE = 'ZRT1')
			OR   (R_SO_TYPE = 'YN01' AND R_DO_TYPE = 'ZRLA')
			OR   (R_SO_TYPE = 'YS03' AND R_DO_TYPE = 'ZRLA')
			OR   (R_SO_TYPE = 'YS02' AND R_DO_TYPE = 'ZRLA')
			OR   (R_SO_TYPE = 'YRT3' AND R_DO_TYPE = 'ZRLA')
			OR   (R_SO_TYPE = 'YNC1' AND R_DO_TYPE = 'ZRLA')
			OR   (R_SO_TYPE = 'YFT1' AND R_DO_TYPE = 'ZRLA')
			OR   (R_SO_TYPE = 'YRH1' AND R_DO_TYPE = 'ZRC1')
			OR   (R_SO_TYPE = 'YF01' AND R_DO_TYPE = 'ZRLA')
			OR   (R_SO_TYPE = 'YP01' AND R_DO_TYPE = 'ZRLA')
		   ) ONZDDTIR 
	ON (ONZOT.REFERENCE_DOC_SO_PO = ONZDDTIR.O_SO_NO AND ONZOT.MATERIAL = ONZDDTIR.MATERIAL
		AND ONZOT.DELIVERY_ITEM = ONZDDTIR.O_DO_ITEM AND ONZOT.DELIVERY_NO = ONZDDTIR.O_DO_NO )
LEFT JOIN (SELECT RONZOT.* FROM OW_LAO.ODS_NERP_ZLLEJ50090_OUTBOUND_TRACKING RONZOT) RONZOT 
	ON (ONZDDTIR.RETURN_DO_NO = RONZOT.DELIVERY_NO AND ONZDDTIR.MATERIAL = RONZOT.MATERIAL)		   				 	
LEFT JOIN OW_LAO.DIM_AFFILIATE_CHANNEL DAC 
	ON DAC.AFFILIATE_ID = OW_LAO.AFFILIATE_ID_ADJUSTED(OVSBSDESS.ID_STORE, RVSBSSOL.AFFILIATE_ID, RVSBSSOL.SALES_CHANNEL)
LEFT JOIN (SELECT DISTINCT FUTC."DO No." 
			  ,FUTC."Order Status " AS "DO_STATUS" 
			  ,FUTC."NF Amt" AS "DO_AMT"
		  	FROM OW_SEDA_S.FT_UNION_TSS_CELLO FUTC 
	  	  WHERE YEAR(FUTC."DO Insert Date") >= YEAR(ADD_YEARS(CURRENT_DATE,-1))
	  	  		AND SUBSTRING("DO No.",1,1)  = '7') AS FUTCA 
	ON (ONZASOT.DELIVERY = FUTCA."DO No.")  
LEFT JOIN (SELECT * 
		      ,VCRT.RDO_NUMBER AS RDO
			  --,ORIG_DO_NO
			  --,VCRT.STATUS_NM
			  --,VCRT.RDO_INSERT_DATE
			  ,VCRT.RDO_RETURN_IOD_DATE AS RDO_IOD
			  --,VCRT.GR_DATE
			  --,VCRT.IOD_DT 
			  --,VCRT.RDO_RETURN_IOD_DATE 
			  ,(CASE WHEN UPPER(VCRT.RDO_ORDER_TYPE) LIKE '%STORE_RTN%'
		   			THEN 'Sit'
		   	 	WHEN UPPER(VCRT.RDO_ORDER_TYPE) LIKE '%CORREIOS%'
		   	 		THEN 'Post'
		   	 	WHEN UPPER(VCRT.RDO_ORDER_TYPE) LIKE '%COLLECT%'
		   	 		THEN 'Pick-up'
		   	 		ELSE NULL 
		   	  END) AS RDO_ORDER_TYPE
		   	  ,VCRT.NF_AMT AS RDO_AMT
		     FROM OW_SEDA_S.VW_CELLO_RETURN_TRACKING VCRT
		   WHERE VCRT.RDO_DELIVERY_TYPE <> 'DUMMY'
		   ) AS VUTCRT 
	ON ONZOT.DELIVERY_NO = VUTCRT.ORIG_DO_NO
	
LEFT JOIN (SELECT DISTINCT MAX(ONZCF.CLAIM_CREATION_DATE) AS CLAIM_CREATION_DATE
				 ,MAX(ONZCF.CREDIT_MEMO_NO) AS CREDIT_MEMO_NO
				 ,ONZCF.DELIVERY_NO 
				 ,MAX(TO_DOUBLE(CLAIM_AMOUNT)) AS CLAIM_AMT
		FROM OW_LAO.ODS_NERP_ZLLEB57910_CLAIM_FOLDER ONZCF
		WHERE 
		ONZCF.CLAIM_DESC <> 'POD Request'
		AND TO_DATE(ONZCF.CLAIM_CREATION_DATE) >'2023-05-31'
	  GROUP BY ONZCF.DELIVERY_NO) UONZCF 
	ON (ONZASOT.DELIVERY = UONZCF.DELIVERY_NO)
LEFT JOIN (SELECT (CASE WHEN OPMO.CHANNEL = 'Cnova' 
			THEN SUBSTRING(OPMO.ORIGINAL_ORDER_ID, 5, 99)
		    WHEN OPMO.CHANNEL = 'MagazineLuiza' 
		    	THEN SUBSTRING(OPMO.ORIGINAL_ORDER_ID, 1, LENGTH(OPMO.ORIGINAL_ORDER_ID) - 4)
		    WHEN OPMO.CHANNEL = 'b2w' 
		    	THEN REPLACE(OPMO.ORIGINAL_ORDER_ID, ' ', '_')
			ELSE OPMO.ORIGINAL_ORDER_ID
		   END) AS ORIGINAL_ORDER_ID_2
		   ,OPMO.*
	  	FROM OW_SEDA_S.ODS_PLUGG_MARKETPLACE_ORDER OPMO) OPMO 
	ON (RVSBSSOL.MARKETPLACE_ORDER_ID = OPMO.ORIGINAL_ORDER_ID_2)
LEFT JOIN OW_SEDA_S.RAW_DATA_API_AFTER_SALES_DETAIL_CONSOLIDATED RDAASDC 
	ON (VUTCRT.RDO = (CASE WHEN RDAASDC.RDO  LIKE 'RDO%' 
							THEN RIGHT(SUBSTR_AFTER(UPPER(RDAASDC.RDO), 'RDO:'), 10)
							ELSE NULL
					  END))
LEFT JOIN OW_MD.MAP_AR_MONTH_CUSTOMER MAC 
	ON (ONFNCLIDOI.CUSTOMER = MAC.CUSTOMER_CODE)
LEFT JOIN 	  (SELECT * FROM OW_MD.MAP_AR_WEEK_TO_FROM_AR_SCM_CLASSIFICATION  
	  			WHERE PERIOD = (SELECT DISTINCT MAX(PERIOD) FROM OW_MD.MAP_AR_WEEK_TO_FROM_AR_SCM_CLASSIFICATION)) MTFASC
	ON (IFNULL(ONFNCLIDOI.CUSTOMER,'') || IFNULL(ONFNCLIDOI."ASSIGNMENT",'') || IFNULL(ONFNCLIDOI.DOCUMENT_NUMBER,'') || IFNULL(REPLACE(ONFNCLIDOI.AMOUNT_IN_LOCAL_CURRENCY,'.',','),'') || IFNULL(ONFNCLIDOI.LINE_ITEM,'')
		= MTFASC."KEY"
		--AND (SELECT DISTINCT DC.YYYYWW_NORMAL_CALENDAR
		--		FROM OW_SEDA_S.ODS_NERP_FBL5N_CUSTOMER_LINE_ITEM_DISPLAY_OPEN_ITEMS ONFNCLIDOI 
		--	LEFT JOIN OW_MD.DIM_CALENDAR DC ON (DC.YYYYMMDD =  ADD_DAYS(TO_DATE(SUBSTRING(ONFNCLIDOI.FILE_NAME,20,8)),-7))
		--	WHERE ONFNCLIDOI.FILE_NAME LIKE '%RPASCMAROPEN_%') = MTFASC.PERIOD
		)
			
LEFT JOIN  OW_MD.MAP_AR_ASSIGNMENT_ADJUSTED MAAA ON (IFNULL(ONFNCLIDOI.CUSTOMER,'') || IFNULL(ONFNCLIDOI."ASSIGNMENT",'') || IFNULL(ONFNCLIDOI.DOCUMENT_NUMBER,'') || IFNULL(REPLACE(ONFNCLIDOI.AMOUNT_IN_LOCAL_CURRENCY,'.',','),'') = MAAA.KEY2)		
WHERE --ONFNCLIDOI.FILE_NAME LIKE '%RPASCMAROPEN_%' 
(ONFNCLIDOI.LOAD_DATE, ONFNCLIDOI.FILE_NAME ) = 
(SELECT DISTINCT MAX(LOAD_DATE), FILE_NAME 
FROM OW_SEDA_S.ODS_NERP_FBL5N_CUSTOMER_LINE_ITEM_DISPLAY_OPEN_ITEMS_HIST onfnclidoih 
WHERE FILE_NAME LIKE '%RPASCMAROPEN_%' 	
GROUP BY FILE_NAME 
ORDER BY 1 DESC LIMIT 1)
	--aND ONZASOT.SALES_DOCUMENT = '1102893176'
--)
;	
--Truncate Table OW_LAO.TF_D2C_AR_ONE_VIEW_TABLE_02
TRUNCATE TABLE OW_LAO.TF_D2C_AR_ONE_VIEW_TABLE_02;
	
	
INSERT INTO OW_LAO.TF_D2C_AR_ONE_VIEW_TABLE_02
--DROP TABLE OW_LAO.TF_D2C_AR_ONE_VIEW_TABLE_02
--CREATE TABLE OW_LAO.TF_D2C_AR_ONE_VIEW_TABLE_02 AS ( 
SELECT 
	T1.AFFILIATE_CHANNEL,
	T1.AFFILIATE_SUB_CHANNEL,
	T1.CUSTOMER,
	T1.DOCUMENT_TYPE,
	T1.POSTING_KEY,
	T1.PAYMENT_TERMS,
	T1.REFERENCE,
	T1.DOCUMENT_DATE,
	T1.AMOUNT_IN_LOCAL_CURRENCY,
	T1.NET_DUE_DATE,
	T1.ARREARS_BY_NET_DUE_DATE,
	T1.DOCUMENT_NUMBER,
	T1."ASSIGNMENT",
	T1."TEXT",
	T1.REASON_CODE,
	T1.ENTRY_DATE,
	T1."G/L_ACCOUNT",
	T1.BILLING_DOCUMENT,
	T1.INVOICE_REFERENCE,
	T1.POSTING_DATE,
	T1."YEAR/MONTH",
	T1.USER_NAME,
	T1."SEQUENCE",
	T1.ORDER_ID,
	T1.VTEX_STATUS,
	T1.VTEX_AMOUNT,
	T1.VTEX_SC_PLUS,
	T1.VTEX_INSTAL,
	T1.VTEX_FREIGHT,
	T1.MKP_STATUS,
	T1.MKP_AMT,
	T1.SALES_DOCUMENT,
	T1.REJECT_REASON_1,
	T1."VOUCHER (Y/N)",
	T1.VOUCHER_NO,
	T1."DO Count",
	T1.DO_NERP,
	T1.DO_IOD_NERP,
	T1.DO_AMT_NERP,
	T1.DO_CELLO,
	T1.DO_STATUS_CELLO,
	T1.RDO_NERP,
	T1.RDO_IOD_NERP,
	T1.RDO_AMT_NERP,
	T1.ID,
	T1.COURIER_COLLECT,
	T1.TOTAL_AMOUNT,
	T1.STATUS_DESCRIPTION,
	T1.CLAIM_AMT,
	T1.CREDIT_MEMO_NO,
	T1.RDO_CELLO,
	T1.RDO_STATUS_CELLO,
	T1.DO_IOD_CELLO,
	T1.RDO_IOD_CELLO,
	T1.RDO_AMT_CELLO,
	T1.RDO_GR_DATE_CELLO,
	T1."In/Over",
	T1."Range",
	T1."TYPE",
	T1."1_CATE",
	T1."2_CATE",
	T1."3_CATE",
	T1.PIC,
	T1.NEW_OPEN_ITEM,
	T1.LINE_ITEM,
	T1."Key",
	T1."Key2",
	T1.ACQUIRER,
	T1.PAYMENT_SYSTEM,
	T1.PAYMENT_SYSTEM_NAME,
	ROW_NUMBER() OVER (PARTITION BY T1."Key" ORDER BY T1."Key") AS ASSIGNMENT_KEY_DISTINTIC,
	ROW_NUMBER() OVER (PARTITION BY T1."Key" ORDER BY T1.AMOUNT_IN_LOCAL_CURRENCY) AS AMOUNT_IN_LOCAL_CURRENCY_KEY_DISTINCT,
	T1.LAST_UPDATE,
	T1.LOAD_DATE
FROM OW_LAO.TF_D2C_AR_ONE_VIEW_TABLE_01 AS T1
--)
;
	/*********************************************************
	* CRIA A Tabela temporária TMP_D2C_AR_ONE_VIEW_TABLE
	* *******************************************************/
	IF EXISTS ( SELECT TABLE_NAME FROM SYS.TABLES WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TMP_D2C_AR_ONE_VIEW_TABLE' ) THEN
		DROP TABLE OW_LAO.TMP_D2C_AR_ONE_VIEW_TABLE;
	END IF ;
	CREATE TABLE OW_LAO.TMP_D2C_AR_ONE_VIEW_TABLE AS (
		SELECT  RVSBSSOL."SEQUENCE",
				RVSBSSOL.ORDER_ID,
				RVSBSSOL.CUSTOM_DATA ,
		 	   JSON_VALUE(RVSBSSOL.CD_2, '$.transactions[0].payments[0].connectorResponses.Tid') AS TID
		
		FROM (
		SELECT  RVSBSSOL."SEQUENCE",
				RVSBSSOL.ORDER_ID,
				RVSBSSOL.CUSTOM_DATA ,
		 JSON_VALUE(RVSBSSOL.CUSTOM_DATA, '$.customApps[0].fields.transaction') AS CD_2
		FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER RVSBSSOL
		WHERE ORDER_ID IN (SELECT DISTINCT ORDER_ID FROM OW_LAO.TF_D2C_AR_ONE_VIEW_TABLE_02) 
			OR "SEQUENCE" IN (SELECT DISTINCT "SEQUENCE" FROM OW_LAO.TF_D2C_AR_ONE_VIEW_TABLE_02)
			--JSON_VALUE(RVSBSSOL.CUSTOM_DATA, '$.customApps[0].fields.transaction') IS NOT NULL
		) RVSBSSOL
		ORDER BY 4 DESC
	)
	;
--Truncate Table OW_LAO.FT_D2C_AR_ONE_VIEW_TABLE
TRUNCATE TABLE OW_LAO.FT_D2C_AR_ONE_VIEW_TABLE;
INSERT INTO OW_LAO.FT_D2C_AR_ONE_VIEW_TABLE
--DROP TABLE OW_LAO.FT_D2C_AR_ONE_VIEW_TABLE
--CREATE TABLE OW_LAO.FT_D2C_AR_ONE_VIEW_TABLE AS ( 
SELECT	T2.AFFILIATE_CHANNEL,
		T2.AFFILIATE_SUB_CHANNEL,
		T2.CUSTOMER,
		T2.DOCUMENT_TYPE,
		T2.POSTING_KEY,
		T2.PAYMENT_TERMS,
		T2.REFERENCE,
		T2.DOCUMENT_DATE,
		T2.AMOUNT_IN_LOCAL_CURRENCY,
		T2.NET_DUE_DATE,
		T2.ARREARS_BY_NET_DUE_DATE,
		T2.DOCUMENT_NUMBER,
		T2."ASSIGNMENT",
		T2."TEXT",
		T2.REASON_CODE,
		T2.ENTRY_DATE,
		T2."G/L_ACCOUNT",
		T2.BILLING_DOCUMENT,
		T2.INVOICE_REFERENCE,
		T2.POSTING_DATE,
		T2."YEAR/MONTH",
		T2.USER_NAME,
		T2."SEQUENCE",
		T2.ORDER_ID,
		T2.VTEX_STATUS,
		T2.VTEX_AMOUNT,
		T2.VTEX_SC_PLUS,
		T2.VTEX_INSTAL,
		T2.VTEX_FREIGHT,
		T2.MKP_STATUS,
		T2.MKP_AMT,
		T2.SALES_DOCUMENT,
		T2.REJECT_REASON_1,
		T2."VOUCHER (Y/N)",
		T2.VOUCHER_NO,
		T2."DO Count",
		T2.DO_NERP,
		T2.DO_IOD_NERP,
		T2.DO_AMT_NERP,
		T2.DO_CELLO,
		T2.DO_STATUS_CELLO,
		T2.RDO_NERP,
		T2.RDO_IOD_NERP,
		T2.RDO_AMT_NERP,
		T2.ID,
		T2.COURIER_COLLECT,
		T2.TOTAL_AMOUNT,
		T2.STATUS_DESCRIPTION,
		T2.CLAIM_AMT,
		T2.CREDIT_MEMO_NO,
		T2.RDO_CELLO,
		T2.RDO_STATUS_CELLO,
		T2.DO_IOD_CELLO,
		T2.RDO_IOD_CELLO,
		T2.RDO_AMT_CELLO,
		T2.RDO_GR_DATE_CELLO,
		T2."In/Over",
		T2."Range",
		T2."TYPE",
		T2."1_CATE",
		T2."2_CATE",
		T2."3_CATE",
		T2.PIC,
		T2.NEW_OPEN_ITEM,
		T2.LINE_ITEM,
		T2."Key",
		T2."Key2",
		T2.ACQUIRER,
		T2.PAYMENT_SYSTEM,
		T2.PAYMENT_SYSTEM_NAME,
		(CASE WHEN T2.ASSIGNMENT_KEY_DISTINTIC <> 1 
				THEN 0
				ELSE T2.ASSIGNMENT_KEY_DISTINTIC
		END) AS ASSIGNMENT_KEY_DISTINTIC,
		(CASE WHEN T2.AMOUNT_IN_LOCAL_CURRENCY_KEY_DISTINCT <> 1 
				THEN '0'
				ELSE T2.AMOUNT_IN_LOCAL_CURRENCY
		END) AS AMOUNT_IN_LOCAL_CURRENCY_KEY_DISTINCT,
		TDAOVT.TID,
		T2.LAST_UPDATE,
		T2.LOAD_DATE
FROM OW_LAO.TF_D2C_AR_ONE_VIEW_TABLE_02 AS T2
LEFT JOIN OW_LAO.TMP_D2C_AR_ONE_VIEW_TABLE TDAOVT ON (T2.ORDER_ID = TDAOVT.ORDER_ID OR T2."SEQUENCE" = TDAOVT."SEQUENCE")
--)
;	
	/*DROP TABLES*/
	DROP TABLE OW_LAO.TMP_D2C_AR_ONE_VIEW_TABLE;
    /**/
END