CREATE OR REPLACE PROCEDURE OW_LAO.PROC_D2C_ONE_VIEW_TABLE()
LANGUAGE PLvSQL AS $$
BEGIN
	-- CRIA A TF_ONE_VIEW_TABLE_BASE_ORDERS
	IF EXISTS (SELECT 1 FROM v_catalog.tables WHERE table_schema = 'OW_LAO' AND table_name = 'TF_ONE_VIEW_TABLE_BASE_ORDERS') THEN
		PERFORM DROP TABLE OW_LAO.TF_ONE_VIEW_TABLE_BASE_ORDERS;
	END IF;
	PERFORM CREATE TABLE OW_LAO.TF_ONE_VIEW_TABLE_BASE_ORDERS AS (
	 SELECT
	        RVSBSSOL.ORDER_ID,
	        RVSBSSOL.MARKETPLACE_ORDER_ID,
	        RVSBSSOL.AFFILIATE_ID,
	        RVSBSSOL."SEQUENCE",
	        CAST(RVSBSSOL.CREATION_TIMESTAMP AS DATE) AS CREATION_DATE,
	        RVSBSSOL.CANCELLATION_DATE,
	        RVSBSSOL.STATUS_DESCRIPTION,
	        RVSBSSOL.SALES_CHANNEL,
	        RVSBSSOL.LAST_CHANGE,
	        (RVSBSSOL.VALUE / 100) AS PO_AMOUNT,
	        RVSBSSOI.ITEM_INDEX,
	        CASE
	            WHEN RVSBSSOIC.REF_ID IS NULL THEN RVSBSSOI.REF_ID
	            ELSE RVSBSSOIC.REF_ID
	        END AS REF_ID,
	        (RVSBSSOI.QUANTITY * COALESCE(RVSBSSOIC.QUANTITY, 1)) AS QUANTITY,
	        ((RVSBSSOI.SELLING_PRICE / 100) * RVSBSSOI.QUANTITY) AS SKU_AMT_TTL,
	        CASE
	            WHEN RVSBSSOL.CD_STORE_INFORMATION IS NOT NULL THEN RVSBSSOL.CD_STORE_INFORMATION
	            WHEN RVSBSO.CD_STORE_INFORMATION IS NOT NULL THEN RVSBSO.CD_STORE_INFORMATION
	            WHEN RVSBSSOL.UTM_SOURCE IS NOT NULL THEN RVSBSSOL.UTM_SOURCE
	            ELSE RVSBSO.UTM_SOURCE
	        END AS ID_STORE
	    FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER RVSBSSOL
	    LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_ITEM RVSBSSOI
	        ON RVSBSSOL.ORDER_ID = RVSBSSOI.ORDER_ID
	    LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_ITEM_COMPONENTS RVSBSSOIC
	        ON RVSBSSOI.ORDER_ID = RVSBSSOIC.ORDER_ID AND RVSBSSOI.SKU_ID = RVSBSSOIC.SKU_ID
	    LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SALES_ORDER RVSBSO
	        ON RVSBSSOL.MARKETPLACE_ORDER_ID = RVSBSO.ORDER_ID
	    WHERE CAST(RVSBSSOL.CREATION_TIMESTAMP AS DATE) >= ADD_MONTHS(CURRENT_DATE, -12)
	      AND RVSBSSOL.STATUS_DESCRIPTION IS NOT NULL
	 );

	-- CRIA A TF_ONE_VIEW_TABLE_SHIPPING_INFO
	IF EXISTS (SELECT 1 FROM v_catalog.tables WHERE table_schema = 'OW_LAO' AND table_name = 'TF_ONE_VIEW_TABLE_SHIPPING_INFO') THEN
		PERFORM DROP TABLE OW_LAO.TF_ONE_VIEW_TABLE_SHIPPING_INFO;
	END IF;
	PERFORM CREATE TABLE OW_LAO.TF_ONE_VIEW_TABLE_SHIPPING_INFO AS (
	    SELECT
	        ORDER_ID,
	        ITEM_INDEX,
	        MAX(MAPLOOKUP(MAPJSONEXTRACTOR(PICKUP_STORE_INFO), 'address.addressType')) AS ADDRESSTYPE,
	        MAX(MAPLOOKUP(MAPJSONEXTRACTOR(PICKUP_STORE_INFO), 'friendlyName')) AS FRIENDLYNAME,
	        MAX(STATE) AS STATE,
	        MAX(CITY) AS CITY,
	        MAX(SELECTED_SLA) AS SELECTED_SLA,
	        CAST(LISTAGG(WAREHOUSE_ID USING PARAMETERS separator=' | ') AS VARCHAR(10000)) AS WAREHOUSE_ID_GROUP,
	        SELLING_PRICE / 100 AS SHIPPING_AMT_TTL
	    FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_SHIPPING
	    WHERE ORDER_ID IN (SELECT DISTINCT ORDER_ID FROM OW_LAO.TF_ONE_VIEW_TABLE_BASE_ORDERS)
	    GROUP BY ORDER_ID, ITEM_INDEX, SELLING_PRICE
	);

	-- CRIA A TF_ONE_VIEW_TABLE_STORE_INFO
	IF EXISTS (SELECT 1 FROM v_catalog.tables WHERE table_schema = 'OW_LAO' AND table_name = 'TF_ONE_VIEW_TABLE_STORE_INFO') THEN
		PERFORM DROP TABLE OW_LAO.TF_ONE_VIEW_TABLE_STORE_INFO;
	END IF;
	PERFORM CREATE TABLE OW_LAO.TF_ONE_VIEW_TABLE_STORE_INFO AS (
	    SELECT
	        ID_STORE,
	        NAME AS NAME_STORE
	    FROM U_PRJ_ECOM.ODS_VTEX_SSG_BR_SHOP_DATA_ENTITIES_STORES_SDS
	);

	-- CRIA A TF_ONE_VIEW_TABLE_O2O_DATA
	IF EXISTS (SELECT 1 FROM v_catalog.tables WHERE table_schema = 'OW_LAO' AND table_name = 'TF_ONE_VIEW_TABLE_O2O_DATA') THEN
		PERFORM DROP TABLE OW_LAO.TF_ONE_VIEW_TABLE_O2O_DATA;
	END IF;
	PERFORM CREATE TABLE OW_LAO.TF_ONE_VIEW_TABLE_O2O_DATA AS (
	  SELECT
	        BO.*,
	        SI.SELECTED_SLA,
	        SI.ADDRESSTYPE,
	        SI.FRIENDLYNAME,
	        SI.WAREHOUSE_ID_GROUP,
	        SI.SHIPPING_AMT_TTL,
	        (BO.SKU_AMT_TTL + SI.SHIPPING_AMT_TTL) AS TTL_SKU_SHIPPING_TTL,
	        ST.NAME_STORE,
	        CASE
	            WHEN TRIM(UPPER(SI.SELECTED_SLA)) LIKE 'SHIP TO STORE%'
	              OR TRIM(UPPER(SI.SELECTED_SLA)) LIKE 'PONTO DE RETIRADA%'
	              OR TRIM(UPPER(SI.SELECTED_SLA)) LIKE 'CLIQUE%'
	              THEN CASE WHEN BO.ID_STORE IS NOT NULL THEN 'BOPIS + EA' ELSE 'BOPIS' END
	            WHEN BO.ID_STORE IS NOT NULL THEN 'EA'
	            ELSE NULL
	        END AS O2O_TYPE
	    FROM OW_LAO.TF_ONE_VIEW_TABLE_BASE_ORDERS BO
	    LEFT JOIN OW_LAO.TF_ONE_VIEW_TABLE_SHIPPING_INFO SI
	        ON BO.ORDER_ID = SI.ORDER_ID AND BO.ITEM_INDEX = SI.ITEM_INDEX
	    LEFT JOIN OW_LAO.TF_ONE_VIEW_TABLE_STORE_INFO ST
	        ON BO.ID_STORE = ST.ID_STORE
	);

	-- CRIA A TF_ONE_VIEW_TABLE_SKU_REF
	IF EXISTS (SELECT 1 FROM v_catalog.tables WHERE table_schema = 'OW_LAO' AND table_name = 'TF_ONE_VIEW_TABLE_SKU_REF') THEN
		PERFORM DROP TABLE OW_LAO.TF_ONE_VIEW_TABLE_SKU_REF;
	END IF;
	PERFORM CREATE TABLE OW_LAO.TF_ONE_VIEW_TABLE_SKU_REF AS (
	    SELECT
	        CAJAMAR_SKU_REFERENCE,
	        MANAUS_SKU_REFERENCE
	    FROM "OW_MD"."MAP_SKU_REFERENCE_BY_PLANT"
	);

	-- CRIA A TF_D2C_ONE_VIEW_TABLE_01
	IF EXISTS (SELECT 1 FROM v_catalog.tables WHERE table_schema = 'OW_LAO' AND table_name = 'TF_D2C_ONE_VIEW_TABLE_01') THEN
		PERFORM DROP TABLE OW_LAO.TF_D2C_ONE_VIEW_TABLE_01;
	END IF;
	PERFORM CREATE TABLE OW_LAO.TF_D2C_ONE_VIEW_TABLE_01 AS (
	SELECT DISTINCT
	    OD.REF_ID,
	    SR.MANAUS_SKU_REFERENCE AS MATERIAL_ADJUSTED,
	    SR.CAJAMAR_SKU_REFERENCE,
	    OW_LAO.AFFILIATE_ID_ADJUSTED(OD.ID_STORE, OD.AFFILIATE_ID, OD.SALES_CHANNEL) AS AFFILIATE_ID_ADJUSTED,
	    NULL AS DIMPROD_PRODUCT_GROUP,
	    NULL AS DIMPROD_DIVISION,
	    NULL AS DIMPROD_PRODUCT,
	    OD.QUANTITY,
	    OD.PO_AMOUNT,
	    OD.STATUS_DESCRIPTION,
	    OD."SEQUENCE",
	    OD.ORDER_ID,
	    OD.MARKETPLACE_ORDER_ID,
	    NULL AS SALES_DOCUMENT,
	    OD.CREATION_DATE,
	    OD.CANCELLATION_DATE,
	    NULL AS SO_CREATED_ON,
	    NULL AS REJECT_REASON,
	    NULL AS REJECT_REASON_1,
	    NULL AS DELIVERY_BLOCK,
	    NULL AS SOLD_TO_PARTY,
	    CASE
	        WHEN O2O_TYPE = 'BOPIS' THEN
	            CASE
	                WHEN (UPPER(SELECTED_SLA) LIKE 'CLIQUE RETIRE%') AND UPPER(ADDRESSTYPE) = 'PICKUP' THEN 'LOCKER'
	                WHEN TRIM(REGEXP_SUBSTR(SELECTED_SLA, '(CSP[a-zA-Z0-9]+)', 1, 1)) LIKE 'CSP%' THEN 'CSP'
	            END
	        ELSE TRIM(SPLIT_PART(NAME_STORE, '|', 1))
	    END AS CHANNEL_O2O,
	    CASE
	        WHEN O2O_TYPE = 'BOPIS' THEN
	            CASE
	                WHEN (UPPER(SELECTED_SLA) LIKE 'CLIQUE RETIRE%') AND UPPER(ADDRESSTYPE) = 'PICKUP' THEN 'Clique Retire'
	                WHEN TRIM(REGEXP_SUBSTR(SELECTED_SLA, '(CSP[a-zA-Z0-9]+)', 1, 1)) LIKE 'CSP%' THEN 'CSP'
	            END
	        ELSE TRIM(SPLIT_PART(NAME_STORE, '|', 2))
	    END AS PARTNER_O2O,
	    TRIM(SPLIT_PART(NAME_STORE, '|', 3)) AS STORE_TYPE_O2O,
	    CASE
	        WHEN O2O_TYPE = 'BOPIS' THEN
	            COALESCE(
	                CAST(OW_LAO.REPLACE_TEXT(TRIM(REGEXP_SUBSTR(SELECTED_SLA, '(CSP[a-zA-Z0-9]+)', 1, 1)),'CSP','',FALSE) AS VARCHAR(5000)),
	                CASE WHEN UPPER(SELECTED_SLA) LIKE 'CLIQUE RETIRE%' THEN CAST(FRIENDLYNAME AS VARCHAR(5000)) END
	            )
	        ELSE TRIM(SPLIT_PART(NAME_STORE, '|', 4))
	    END AS STORE_NAME_O2O,
	    OD.LAST_CHANGE,
	    NULL AS CUSTOMER_PO,
	    NULL AS MATERIAL,
	    NULL AS DELIVERY_ITEM,
	    NULL AS DELIVERY,
	    OD.SKU_AMT_TTL,
	    OD.SHIPPING_AMT_TTL,
	    OD.TTL_SKU_SHIPPING_TTL
	FROM OW_LAO.TF_ONE_VIEW_TABLE_O2O_DATA OD
	LEFT JOIN OW_LAO.TF_ONE_VIEW_TABLE_SKU_REF SR ON OD.REF_ID = SR.CAJAMAR_SKU_REFERENCE);

	-- CRIA A TF_D2C_ONE_VIEW_TABLE_02
	IF EXISTS (SELECT 1 FROM v_catalog.tables WHERE table_schema = 'OW_LAO' AND table_name = 'TF_D2C_ONE_VIEW_TABLE_02') THEN
		PERFORM DROP TABLE OW_LAO.TF_D2C_ONE_VIEW_TABLE_02;
	END IF;
	PERFORM CREATE TABLE OW_LAO.TF_D2C_ONE_VIEW_TABLE_02 AS (
	SELECT
			TDCOVT.REF_ID
			,(CASE WHEN TDCOVT.REF_ID = ONZASOT.MATERIAL
					THEN TDCOVT.REF_ID
				   WHEN TDCOVT.REF_ID = ONZASOT.MATERIAL AND TDCOVT.MATERIAL_ADJUSTED IS NOT NULL
					THEN TDCOVT.MATERIAL_ADJUSTED
				   ELSE TDCOVT.REF_ID
			END) AS MATERIAL_ADJUSTED
			,TDCOVT.CAJAMAR_SKU_REFERENCE
			,TDCOVT.AFFILIATE_ID_ADJUSTED
			,DP.SEDA_BU_ESTORE AS DIMPROD_PRODUCT_GROUP
			,DP.SEDA_DIVISION_ESTORE AS DIMPROD_DIVISION
			,DP.SEDA_DESC_ESTORE AS DIMPROD_PRODUCT
			,(CASE WHEN TDCOVT.QUANTITY = ONZASOT.DELIVERY_QTY_BASE
					THEN TDCOVT.QUANTITY
					ELSE ONZASOT.DELIVERY_QTY_BASE
			END) AS QUANTITY
			,(CASE WHEN TDCOVT.QUANTITY = ONZASOT.DELIVERY_QTY_BASE OR TDCOVT.QUANTITY = 0
        			THEN TDCOVT.PO_AMOUNT
    				ELSE TDCOVT.PO_AMOUNT * (ONZASOT.DELIVERY_QTY_BASE / NULLIF(TDCOVT.QUANTITY,0))
			END) AS PO_AMOUNT
			,TDCOVT.STATUS_DESCRIPTION
			,TDCOVT."SEQUENCE"
			,TDCOVT.ORDER_ID
			,TDCOVT.MARKETPLACE_ORDER_ID
			,ONZASOT.SALES_DOCUMENT
			,TDCOVT.CREATION_DATE
			,TDCOVT.CANCELLATION_DATE
			,CAST(ONZASOT.SO_LOCAL_CREATE_ON_D AS DATE) AS SO_CREATED_ON
			,ONZASOT.REJECT_REASON
			,ONZASOT.REJECT_REASON_1
			,ONZASOT.DELIVERY_BLOCK
			,ONZASOT.SOLD_TO_PARTY
			,TDCOVT.CHANNEL_O2O
			,TDCOVT.PARTNER_O2O
			,TDCOVT.STORE_TYPE_O2O
			,TDCOVT.STORE_NAME_O2O
			,TDCOVT.LAST_CHANGE
			,ONZASOT.CUSTOMER_PO
			,ONZASOT.MATERIAL
			,ONZASOT.DELIVERY_ITEM
			,ONZASOT.DELIVERY
			,(CASE WHEN TDCOVT.QUANTITY = ONZASOT.DELIVERY_QTY_BASE OR TDCOVT.QUANTITY = 0
					THEN TDCOVT.SKU_AMT_TTL
					ELSE TDCOVT.SKU_AMT_TTL*(ONZASOT.DELIVERY_QTY_BASE/ NULLIF(TDCOVT.QUANTITY,0))
			END) AS SKU_AMT_TTL
			,(CASE WHEN TDCOVT.QUANTITY = ONZASOT.DELIVERY_QTY_BASE OR TDCOVT.QUANTITY = 0
					THEN TDCOVT.SHIPPING_AMT_TTL
					ELSE TDCOVT.SHIPPING_AMT_TTL*(ONZASOT.DELIVERY_QTY_BASE/ NULLIF(TDCOVT.QUANTITY,0))
			END) AS SHIPPING_AMT_TTL
	        ,(CASE WHEN TDCOVT.QUANTITY = ONZASOT.DELIVERY_QTY_BASE OR TDCOVT.QUANTITY = 0
					THEN TDCOVT.TTL_SKU_SHIPPING_TTL
					ELSE TDCOVT.TTL_SKU_SHIPPING_TTL*(ONZASOT.DELIVERY_QTY_BASE/ NULLIF(TDCOVT.QUANTITY,0))
			END) AS TTL_SKU_SHIPPING_TTL
			,ONZASOT."2ND_GI_CREATE_ON" AS "2ST_GI_DATE"
			,ONZASOT.SPEC_PROCESSING
	FROM OW_LAO.TF_D2C_ONE_VIEW_TABLE_01 TDCOVT
	LEFT JOIN (
		SELECT *
		FROM OW_LAO.ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING
		WHERE ORDER_QTY_BASE > 0
	) ONZASOT ON ((TDCOVT.ORDER_ID =  ONZASOT.CUSTOMER_PO
					OR TDCOVT."SEQUENCE" =  ONZASOT.CUSTOMER_PO)
							AND (CASE WHEN TDCOVT.REF_ID = ONZASOT.MATERIAL
									THEN TDCOVT.REF_ID
								   WHEN TDCOVT.MATERIAL_ADJUSTED = ONZASOT.MATERIAL
									THEN TDCOVT.MATERIAL_ADJUSTED
								   ELSE TDCOVT.REF_ID
								END) = ONZASOT.MATERIAL)
	LEFT JOIN OW_MD.DIM_PRODUCT DP ON ((CASE WHEN TDCOVT.REF_ID = ONZASOT.MATERIAL
											THEN TDCOVT.REF_ID
									   		WHEN TDCOVT.MATERIAL_ADJUSTED = ONZASOT.MATERIAL
											THEN TDCOVT.MATERIAL_ADJUSTED
										   ELSE TDCOVT.REF_ID
									END) = DP.SKU)
	);

	-- CRIA A FT_D2C_ONE_VIEW_TABLE
	IF EXISTS (SELECT 1 FROM v_catalog.tables WHERE table_schema = 'OW_LAO' AND table_name = 'FT_D2C_ONE_VIEW_TABLE') THEN
		PERFORM DROP TABLE OW_LAO.FT_D2C_ONE_VIEW_TABLE;
	END IF;
	PERFORM CREATE TABLE OW_LAO.FT_D2C_ONE_VIEW_TABLE AS (
		SELECT   TDCOVT.MATERIAL_ADJUSTED AS REF_ID
				,TDCOVT.AFFILIATE_ID_ADJUSTED
				,DAC.AFFILIATE_CHANNEL AS AFFILIATE_CHANNEL
				,DAC.AFFILIATE_SUB_CHANNEL AS AFFILIATE_SUB_CHANNEL
				,TDCOVT.DIMPROD_PRODUCT_GROUP
				,TDCOVT.DIMPROD_DIVISION
				,TDCOVT.DIMPROD_PRODUCT
				,TDCOVT.QUANTITY
				,TDCOVT.PO_AMOUNT
				,TDCOVT.SKU_AMT_TTL
				,TDCOVT.SHIPPING_AMT_TTL
	        	,TDCOVT.TTL_SKU_SHIPPING_TTL
				,TDCOVT.STATUS_DESCRIPTION
				,TDCOVT."SEQUENCE"
				,TDCOVT.ORDER_ID
				,TDCOVT.MARKETPLACE_ORDER_ID
				,FUTCA."NF Amt" AS "NF Amt"
				,FUTCA."Order Status" AS "Order Status"
				,TDCOVT.SALES_DOCUMENT
				,ONZOT.DELIVERY_NO
				,ONZOT.NOTA_INTERNAL_NO
				,ONZOT.BILLING_DOC
				,TDCOVT.CREATION_DATE
				,TDCOVT.CANCELLATION_DATE
				,TDCOVT.SO_CREATED_ON
				,CAST(ONZOT.DOCUMENT_DATE_LOCAL AS DATE) AS DOCUMENT_DATE_LOCAL
				,CAST(ONZOT.NOTA_POSTING_DATE AS DATE) AS NOTA_POSTING_DATE
				,CAST(ONZOT.PLANNED_GI AS DATE) AS PLANNED_GI
				,CAST(ONZOT."1ST_GI_DATE" AS DATE) AS "1ST_GI_DATE"
				,CAST(TDCOVT."2ST_GI_DATE" AS DATE) AS "2ST_GI_DATE"
				,CAST(ONZOT.BILLING_DATE AS DATE) AS BILLING_DATE
				,CAST(ONZOT.EPOD_DATE AS DATE) AS EPOD_DATE
				,TDCOVT.SPEC_PROCESSING
				,TDCOVT.REJECT_REASON
				,TDCOVT.REJECT_REASON_1
				,TDCOVT.DELIVERY_BLOCK
				,TDCOVT.SOLD_TO_PARTY
				,TDCOVT.LAST_CHANGE
				,VUTCRT.RDO_NUMBER
				,VUTCRT.STATUS_NM AS "Return Track Status"
				,VUTCRT.RDO_INSERT_DATE
				,VUTCRT.RDO_RETURN_IOD_DATE
				,VUTCRT.GR_DATE
				,VUTCRT.RDO_ORDER_TYPE
				,TDCOVT.CHANNEL_O2O
				,TDCOVT.PARTNER_O2O
				,TDCOVT.STORE_TYPE_O2O
				,TDCOVT.STORE_NAME_O2O
				,UONZCF.CLAIM_CREATION_DATE
	        	,UONZCF.CREDIT_MEMO_NO
				,OPMO.STATUS AS STATUS_PLUGTO
				,OPMO.MODIFIED AS "3PD_CANCEL"
				,CURRENT_TIMESTAMP AS LAST_UPDATE
		FROM OW_LAO.TF_D2C_ONE_VIEW_TABLE_02 TDCOVT
			LEFT JOIN OW_LAO.DIM_AFFILIATE_CHANNEL DAC ON
				DAC.AFFILIATE_ID = TDCOVT.AFFILIATE_ID_ADJUSTED
			LEFT JOIN (
					SELECT *
					FROM OW_LAO.ODS_NERP_ZLLEJ50090_OUTBOUND_TRACKING
					WHERE SO_TYPE = 'YS10'
					   AND DO_TYPE = 'ZND1'
			) ONZOT ON (TDCOVT.SALES_DOCUMENT =ONZOT.REFERENCE_DOC_SO_PO
					   AND TDCOVT.MATERIAL = ONZOT.MATERIAL
					   AND TDCOVT.DELIVERY_ITEM = ONZOT.DELIVERY_ITEM AND TDCOVT.DELIVERY = ONZOT.DELIVERY_NO)
			LEFT JOIN (
					SELECT DISTINCT FUTC."DO No."
					  ,FUTC."Order Status " AS "Order Status"
					  ,FUTC."NF Amt"
				  FROM OW_SEDA_S.FT_UNION_TSS_CELLO FUTC
			  WHERE EXTRACT(YEAR FROM FUTC."DO Insert Date") >= EXTRACT(YEAR FROM ADD_MONTHS(CURRENT_DATE,-12))
			) AS FUTCA ON (TDCOVT.DELIVERY = FUTCA."DO No.")
			LEFT JOIN (
				SELECT DISTINCT VCRT.RDO_NUMBER
					  ,ORIG_DO_NO
					  ,VCRT.STATUS_NM
					  ,VCRT.RDO_INSERT_DATE
					  ,CAST(VCRT.RDO_RETURN_IOD_DATE AS DATE) AS RDO_RETURN_IOD_DATE
					  ,VCRT.GR_DATE
					  ,CASE WHEN UPPER(VCRT.RDO_ORDER_TYPE) LIKE '%STORE_RTN%'
		   				THEN 'Sit'
		   				WHEN UPPER(VCRT.RDO_ORDER_TYPE) LIKE '%CORREIOS%'
		   					THEN 'Post'
		   				WHEN UPPER(VCRT.RDO_ORDER_TYPE) LIKE '%COLLECT%'
		   					THEN 'Pick-up'
		   					ELSE NULL
		   			  END AS RDO_ORDER_TYPE
				FROM OW_SEDA_S.VW_CELLO_RETURN_TRACKING VCRT
				WHERE VCRT.RDO_DELIVERY_TYPE <> 'DUMMY') AS VUTCRT ON ONZOT.DELIVERY_NO = VUTCRT.ORIG_DO_NO
			LEFT JOIN (
					SELECT DISTINCT
						   MAX(ONZCF.CLAIM_CREATION_DATE) AS CLAIM_CREATION_DATE
						  ,MAX(ONZCF.CREDIT_MEMO_NO) AS CREDIT_MEMO_NO
						  ,ONZCF.DELIVERY_NO
						  ,ONZCF.MATERIAL
					FROM OW_LAO.ODS_NERP_ZLLEB57910_CLAIM_FOLDER ONZCF
					GROUP BY ONZCF.DELIVERY_NO  ,ONZCF.MATERIAL
			) UONZCF ON (TDCOVT.DELIVERY = UONZCF.DELIVERY_NO AND TDCOVT.MATERIAL = UONZCF.MATERIAL )
			LEFT JOIN (
				SELECT (CASE WHEN OPMO.CHANNEL = 'Cnova'
					THEN SUBSTR(OPMO.ORIGINAL_ORDER_ID, 5, 99)
				    WHEN OPMO.CHANNEL = 'MagazineLuiza'
				    	THEN SUBSTR(OPMO.ORIGINAL_ORDER_ID, 1, LENGTH(OPMO.ORIGINAL_ORDER_ID) - 4)
				    WHEN OPMO.CHANNEL = 'b2w'
				    	THEN REPLACE(OPMO.ORIGINAL_ORDER_ID, ' ', '_')
					ELSE OPMO.ORIGINAL_ORDER_ID
				   END) AS ORIGINAL_ORDER_ID_2
				   ,OPMO.*
				  FROM OW_SEDA_S.ODS_PLUGG_MARKETPLACE_ORDER OPMO
			) OPMO ON (TDCOVT.MARKETPLACE_ORDER_ID = OPMO.ORIGINAL_ORDER_ID_2)
	);

	-- APAGA TEMPORÁRIAS
	PERFORM DROP TABLE OW_LAO.TF_ONE_VIEW_TABLE_BASE_ORDERS;
	PERFORM DROP TABLE OW_LAO.TF_ONE_VIEW_TABLE_SHIPPING_INFO;
	PERFORM DROP TABLE OW_LAO.TF_ONE_VIEW_TABLE_STORE_INFO;
	PERFORM DROP TABLE OW_LAO.TF_ONE_VIEW_TABLE_O2O_DATA;
	PERFORM DROP TABLE OW_LAO.TF_ONE_VIEW_TABLE_SKU_REF;
	PERFORM DROP TABLE OW_LAO.TF_D2C_ONE_VIEW_TABLE_01;
	PERFORM DROP TABLE OW_LAO.TF_D2C_ONE_VIEW_TABLE_02;
END
$$;

-- CALL OW_LAO.PROC_D2C_ONE_VIEW_TABLE();