CREATE OR REPLACE PROCEDURE PROC_CRAWLING_AP1_WERABLES_PT1()
LANGUAGE PLvSQL AS $$
BEGIN
  -- Delete current day data to avoid duplicates
  PERFORM DELETE FROM OW_LAO.FT_CRAWLING_AP1_WERABLES_SEGMENT
  WHERE PROCESS_DATETIME = CURRENT_DATE;

  -- Load FT_CRAWLING_AP1_WERABLES_SEGMENT
  PERFORM INSERT INTO OW_LAO.FT_CRAWLING_AP1_WERABLES_SEGMENT (
    BRAND_NM,
    MODEL_DESC,
    SUBSIDIARY,
    COUNTRY,
    SITE_COMPANY_NAME,
    VENDOR,
    SITE_NM,
    SITE_URL,
    SITE_PAGE,
    SITE_POSITION,
    SITE_PRICE_CURRENCY,
    SITE_RATING,
    SITE_RATING_AMOUNT,
    SITE_RATING_SCALE,
    REFER_DATE,
    PRICE_LOCAL_BASE,
    PRICE_LOCAL_ACT,
    PROCESS_DATETIME,
    FROM_CURRENCY,
    TO_CURRENCY,
    VALID_FROM,
    EXCHANGE_RATE,
    PRICE_LOCAL_BASE_USD,
    PRICE_LOCAL_ACT_USD,
    INITIAL_URL,
    REFER_WEEK,
    REFER_WEEK_T,
    REFER_YEAR
  )
  SELECT 
    DETAIL_PRICE.PROD_BRAND AS BRAND_NM,
    DETAIL_PRICE."DESC" AS MODEL_DESC,
    DETAIL_PRICE.AP2 AS SUBSIDIARY,
    DETAIL_PRICE.COUNTRY AS COUNTRY,
    DETAIL_PRICE.COMPANY_NAME AS SITE_COMPANY_NAME,
    DETAIL_PRICE.VENDOR,
    DETAIL_PRICE.SITE AS SITE_NM,
    DETAIL_PRICE.PROD_HREF AS SITE_URL,
    DETAIL_PRICE.PAGE_NUMBER AS SITE_PAGE,
    DETAIL_PRICE.POSITION AS SITE_POSITION,
    DETAIL_PRICE.CURRENCY AS SITE_PRICE_CURRENCY,
    REGEXP_SUBSTR(UPPER(TRIM(REPLACE(RATING, ',', '.'))), '\\d+(\\.\\d{1,2})?', 1, 1) AS SITE_RATING,
    REGEXP_SUBSTR(UPPER(TRIM(REPLACE(RATING_AMOUNT, ',', '.'))), '\\d+(\\.\\d{1,2})?', 1, 1) AS SITE_RATING_AMOUNT,
    DETAIL_PRICE.RATING_SCALE AS SITE_RATING_SCALE,
    DETAIL_PRICE.TODAY_DATE AS REFER_DATE,

    -- Proteção para múltiplos pontos decimais
    CASE 
      WHEN DETAIL_PRICE."DE_VALUE" ~ '^-?\d+(\.\d+)?$' 
        THEN CAST(DETAIL_PRICE."DE_VALUE" AS NUMERIC) 
      ELSE NULL 
    END AS PRICE_LOCAL_BASE,

    CASE 
      WHEN DETAIL_PRICE."POR_VALUE" ~ '^-?\d+(\.\d+)?$' 
        THEN CAST(DETAIL_PRICE."POR_VALUE" AS NUMERIC) 
      ELSE NULL 
    END AS PRICE_LOCAL_ACT,

    CURRENT_DATE AS PROCESS_DATETIME,
    DETAIL_PRICE.CURRENCY AS FROM_CURRENCY,
    'USD' AS TO_CURRENCY,
    ER.VALID_FROM,  
    ER.EXCHANGE_RATE,

    CASE 
      WHEN DETAIL_PRICE.CURRENCY = 'UDS' AND DETAIL_PRICE."DE_VALUE" ~ '^-?\d+(\.\d+)?$'
        THEN CAST(DETAIL_PRICE."DE_VALUE" AS NUMERIC)
      WHEN DETAIL_PRICE."DE_VALUE" ~ '^-?\d+(\.\d+)?$'
        THEN CAST(DETAIL_PRICE."DE_VALUE" AS NUMERIC) / ER.EXCHANGE_RATE
      ELSE NULL
    END AS PRICE_LOCAL_BASE_USD,

    CASE 
      WHEN DETAIL_PRICE.CURRENCY = 'UDS' AND DETAIL_PRICE."POR_VALUE" ~ '^-?\d+(\.\d+)?$'
        THEN CAST(DETAIL_PRICE."POR_VALUE" AS NUMERIC)
      WHEN DETAIL_PRICE."POR_VALUE" ~ '^-?\d+(\.\d+)?$'
        THEN CAST(DETAIL_PRICE."POR_VALUE" AS NUMERIC) / ER.EXCHANGE_RATE
      ELSE NULL
    END AS PRICE_LOCAL_ACT_USD,

    DETAIL_PRICE.INITIAL_URL,
    D.REFER_WEEK,
    D.REFER_WEEK_T,
    D.REFER_YEAR

  FROM (
    SELECT DISTINCT
      CASE WHEN P.DE_VALUE IS NOT NULL AND LENGTH(P.DE_VALUE) <> 0 THEN P.DE_VALUE ELSE NULL END AS DE_VALUE,
      P.INITIAL_URL,
      P.PAGE_NUMBER,
      CASE WHEN P.POR_VALUE IS NOT NULL AND LENGTH(P.POR_VALUE) <> 0 THEN P.POR_VALUE ELSE NULL END AS POR_VALUE,
      P.POSITION,
      P.PRODUCT_TYPE,
      P.REPEAT,
      P.SUB,
      P.TODAY_DATE,
      P.TODAY_DATE_LONG,
      P.TODAY_DATE_TIME,
      D.* 
    FROM 
      OW_LAO.ODS_CRAWLING_AP1_WEARABLES_PRODUCT_DETAIL D
    LEFT JOIN (
      SELECT 
        ROW_NUMBER() OVER (PARTITION BY KEY ORDER BY TODAY_DATE DESC) AS RANK,
        INITIAL_URL,
        KEY,
        REPLACE(DE_VALUE, '$', '') AS DE_VALUE,
        PAGE_NUMBER,
        PRODUCT_TYPE,
        REPLACE(POR_VALUE, '$', '') AS POR_VALUE,
        POSITION,
        REPEAT,
        SITE,
        TODAY_DATE_LONG,
        TODAY_DATE_TIME,
        SUB,
        TODAY_DATE,
        AVAILABLE
      FROM OW_LAO.ODS_CRAWLING_AP1_IM_PRODUCT_DAILY_PRICE
      WHERE UPPER(TRIM(PRODUCT_TYPE)) = 'WEARABLES'
        AND CAST(TODAY_DATE AS DATE) = CURRENT_DATE - 1
    ) P
      ON D.KEY = P.KEY AND P.RANK = 1
    WHERE UPPER(TRIM(PRODUCT_TYPE)) = 'WEARABLES'
  ) DETAIL_PRICE
  LEFT JOIN OW_LAO.FT_AP2_EXCHANGE_RATE ER 
    ON TO_CHAR(DETAIL_PRICE.TODAY_DATE, 'YYYY-MM-DD') = ER.VALID_FROM  
   AND DETAIL_PRICE.CURRENCY = ER.TO_CURRENCY
  LEFT JOIN (
    SELECT DISTINCT YYYYWW AS REFER_WEEK, YYYYMMDD, 'W' || RIGHT(YYYYWW, 2) AS REFER_WEEK_T, YYYY AS REFER_YEAR
    FROM OW_MD.DIM_CALENDAR
  ) D 
    ON TO_CHAR(DETAIL_PRICE.TODAY_DATE, 'YYYY-MM-DD') = TO_CHAR(D.YYYYMMDD, 'YYYY-MM-DD') -- tirar to_char
  WHERE CAST(DETAIL_PRICE.TODAY_DATE AS DATE) = CURRENT_DATE - 1;

END;
$$;


 CALL PROC_CRAWLING_AP1_WERABLES_PT1();