CREATE OR REPLACE PROCEDURE PROC_CRAWLING_AP1_NPC_SITE_MAPPING_MERGE_AUTOMATIC()
LANGUAGE PLvSQL AS $$
BEGIN
-- INPUT DO ARQUIVO
PERFORM MERGE INTO OW_LAO.INPUT_CRAWLING_AP1_NPC_SITE_MAPPING AS Destino
USING (
  SELECT 
      MIN(REPLACE(ITEM_ID,'.0',''))  AS MODEL_MAPPING,
      MIN(AP2) AS AP2,
      MIN(COUNTRY) AS COUNTRY,
      MIN(COMPANY_NAME) AS COMPANY_NAME,
      MIN(BRAND_NM) AS BRAND_NM,
      MIN(DESCRIPTION) AS DESCRIPTION,
      MIN(MODEL_REF_1) AS MODEL_REF_1,
      MIN(MODEL_REF_2) AS MODEL_REF_2,
      MIN(MODEL_REF_3) AS MODEL_REF_3,
      MIN(MODEL_REF_4) AS MODEL_REF_4,
      SITE_URL,
      MIN(LOWER_POSITION) AS LOWER_POSITION,
      MIN(CRAWLING_QTY) AS CRAWLING_QTY,
      MIN(FILE_NAME) AS FILE_NAME,
      MIN(LOAD_DATE) AS LOAD_DATE
  FROM OW_LAO.INPUT_CRAWLING_AP1_NPC_SITE_MAPPING_TMP 
  WHERE SITE_URL IN (
      SELECT DISTINCT PROD_HREF FROM OW_LAO.ODS_CRAWLING_AP1_NPC_PRODUCT_DETAIL
  )
  GROUP BY SITE_URL
) AS Origem
ON (Destino.SITE_URL = Origem.SITE_URL)
WHEN MATCHED THEN
    UPDATE SET 
      MODEL_MAPPING = Origem.MODEL_MAPPING,
      AP2 = Origem.AP2,
      COUNTRY = Origem.COUNTRY,
      COMPANY_NAME = Origem.COMPANY_NAME,
      BRAND_NM = Origem.BRAND_NM,
      DESCRIPTION = Origem.DESCRIPTION,
      MODEL_REF_1 = Origem.MODEL_REF_1,
      MODEL_REF_2 = Origem.MODEL_REF_2,
      MODEL_REF_3 = Origem.MODEL_REF_3,
      MODEL_REF_4 = Origem.MODEL_REF_4,
      LOWER_POSITION = Origem.LOWER_POSITION,
      CRAWLING_QTY = Origem.CRAWLING_QTY,
      FILE_NAME = Origem.FILE_NAME,
      LOAD_DATE = Origem.LOAD_DATE,
      MAPPING_TYPE = 'MANUAL',
      CREATED_DATE = Destino.CREATED_DATE,
      UPDATED_DATE = CURRENT_DATE
WHEN NOT MATCHED THEN
    INSERT (
      MODEL_MAPPING,
      AP2,
      COUNTRY,
      COMPANY_NAME,
      BRAND_NM,
      DESCRIPTION,
      MODEL_REF_1,
      MODEL_REF_2,
      MODEL_REF_3,
      MODEL_REF_4,
      SITE_URL,
      LOWER_POSITION,
      CRAWLING_QTY,
      FILE_NAME,
      LOAD_DATE,
      MAPPING_TYPE,
      CREATED_DATE,
      UPDATED_DATE
    ) VALUES (
      Origem.MODEL_MAPPING,
      Origem.AP2,
      Origem.COUNTRY,
      Origem.COMPANY_NAME,
      Origem.BRAND_NM,
      Origem.DESCRIPTION,
      Origem.MODEL_REF_1,
      Origem.MODEL_REF_2,
      Origem.MODEL_REF_3,
      Origem.MODEL_REF_4,
      Origem.SITE_URL,
      Origem.LOWER_POSITION,
      Origem.CRAWLING_QTY,
      Origem.FILE_NAME,
      Origem.LOAD_DATE,
      'MANUAL',
      CURRENT_DATE,
      CURRENT_DATE
    );

-- INPUT AUTOMATICO - URL COM MODEL_MAPPING ENCONTRADO
PERFORM MERGE INTO OW_LAO.INPUT_CRAWLING_AP1_NPC_SITE_MAPPING AS Destino
USING (
  SELECT * FROM OW_LAO.VW_CRAWLING_AP1_NPC_SITE_SPEC_MAPPING_AUTOMATIC
) AS Origem
ON (Destino.SITE_URL = Origem.SITE_URL AND Origem.MODEL_MAPPING IS NOT NULL)
WHEN MATCHED THEN
    UPDATE SET 
      MODEL_MAPPING = Origem.MODEL_MAPPING,
      AP2 = Origem.SUB,
      COUNTRY = Origem.COUNTRY,
      COMPANY_NAME = Origem.COMPANY_NAME,
      BRAND_NM = Origem.BRAND_NM,
      DESCRIPTION = Origem.DESCRIPTION,
      MODEL_REF_1 = Origem.MODEL_REF_1,
      MODEL_REF_2 = Origem.MODEL_REF_2,
      MODEL_REF_3 = Origem.MODEL_REF_3,
      MODEL_REF_4 = Origem.MODEL_REF_4,
      LOWER_POSITION = Origem.LOWER_POSITION,
      CRAWLING_QTY = Origem.CRAWLING_QTY,
      FILE_NAME = Destino.FILE_NAME,
      LOAD_DATE = Destino.LOAD_DATE,
      MAPPING_TYPE = Origem.MAPPING_ORIGEM,
      CREATED_DATE = Destino.CREATED_DATE,
      UPDATED_DATE = CURRENT_DATE;

-- URL SEM MODEL_MAPPING ENCONTRADO ATUALIZANDO SOMENTE DADOS
PERFORM MERGE INTO OW_LAO.INPUT_CRAWLING_AP1_NPC_SITE_MAPPING AS Destino
USING (
  SELECT * FROM OW_LAO.VW_CRAWLING_AP1_NPC_SITE_SPEC_MAPPING_AUTOMATIC
) AS Origem
ON (Destino.SITE_URL = Origem.SITE_URL AND Origem.MODEL_MAPPING IS NULL)
WHEN MATCHED THEN
    UPDATE SET 
      AP2 = Origem.SUB,
      COUNTRY = Origem.COUNTRY,
      COMPANY_NAME = Origem.COMPANY_NAME,
      BRAND_NM = Origem.BRAND_NM,
      DESCRIPTION = Origem.DESCRIPTION,
      LOWER_POSITION = Origem.LOWER_POSITION,
      CRAWLING_QTY = Origem.CRAWLING_QTY,
      UPDATED_DATE = CURRENT_DATE;

-- NOVA URL ENCONTRADA NO RPA SENDO INSERIDA NA INPUT
PERFORM MERGE INTO OW_LAO.INPUT_CRAWLING_AP1_NPC_SITE_MAPPING AS Destino
USING (
  SELECT * FROM OW_LAO.VW_CRAWLING_AP1_NPC_SITE_SPEC_MAPPING_AUTOMATIC
) AS Origem
ON (Destino.SITE_URL = Origem.SITE_URL)
WHEN NOT MATCHED THEN
    INSERT (
      MODEL_MAPPING,
      AP2,
      COUNTRY,
      COMPANY_NAME,
      BRAND_NM,
      DESCRIPTION,
      MODEL_REF_1,
      MODEL_REF_2,
      MODEL_REF_3,
      MODEL_REF_4,
      SITE_URL,
      LOWER_POSITION,
      CRAWLING_QTY,
      FILE_NAME,
      LOAD_DATE,
      MAPPING_TYPE,
      CREATED_DATE,
      UPDATED_DATE
    ) VALUES (
      Origem.MODEL_MAPPING,
      Origem.SUB,
      Origem.COUNTRY,
      Origem.COMPANY_NAME,
      Origem.BRAND_NM,
      Origem.DESCRIPTION,
      Origem.MODEL_REF_1,
      Origem.MODEL_REF_2,
      Origem.MODEL_REF_3,
      Origem.MODEL_REF_4,
      Origem.SITE_URL,
      Origem.LOWER_POSITION,
      Origem.CRAWLING_QTY,
      NULL,
      NULL,
      Origem.MAPPING_ORIGEM,
      CURRENT_DATE,
      CURRENT_DATE
    );

-- TRUNCATE/POPULATE MP TABLE
PERFORM TRUNCATE TABLE OW_LAO.MP_CRAWLING_AP1_NPC_SITE_SPEC_MAPPING;

PERFORM INSERT INTO OW_LAO.MP_CRAWLING_AP1_NPC_SITE_SPEC_MAPPING
(
    MAPPING_ORIGEM,
    MODEL_MAPPING,
    SITE_URL,
    MODEL,
    SEGMENTS,
    ULTRA_THIN,
    KEYBOARD_TYPE,
    DEPTH_MM,
    OPERATING_SYSTEM,
    HEIGHT_MM,
    HARD_DRIVE_TYPE,
    STORAGE_IN_GB,
    RAM_IN_MB,
    WEIGHT_GRAMM,
    TOUCHSCREEN,
    CSP_MHZ,
    DVD_WRITER,
    DISTRIBUTION_TYPE,
    PROCESSOR_BRAND,
    OS_VERSION,
    PROCESSOR,
    PROCESSOR_NUMBER,
    GPU_BRAND,
    GPU_MODEL,
    CONVERTIBLE,
    GAMING_PRODUCTS,
    GPU_TYPE,
    DESIGN,
    DISPLAY_SIZE,
    INSTANT_ON,
    LOAD_DATE
)
SELECT
  CASE WHEN S.ITEM_ID IS NULL THEN NULL ELSE MAPPING_AUTOMATICO.MAPPING_ORIGEM END AS MAPPING_ORIGEM,
  COALESCE(S.ITEM_ID, 'NÃO MAPEADO') AS MODEL_MAPPING,
  MAPPING_AUTOMATICO.SITE_URL,
  S.MODEL,
  S.SEGMENTS,
  S.ULTRA_THIN,
  S.KEYBOARD_TYPE,
  S.DEPTH_MM,
  S.OPERATING_SYSTEM,
  S.HEIGHT_MM,
  S.HARD_DRIVE_TYPE,
  S.STORAGE_IN_GB,
  S.RAM_IN_MB,
  S.WEIGHT_GRAMM,
  S.TOUCHSCREEN,
  S.CSP_MHZ,
  S.DVD_WRITER,
  S.DISTRIBUTION_TYPE,
  S.PROCESSOR_BRAND,
  S.OS_VERSION,
  S.PROCESSOR,
  S.PROCESSOR_NUMBER,
  S.GPU_BRAND,
  S.GPU_MODEL,
  S.CONVERTIBLE,
  S.GAMING_PRODUCTS,
  S.GPU_TYPE,
  S.DESIGN,
  S.DISPLAY_SIZE,
  S.INSTANT_ON,
  S.LOAD_DATE
FROM (
  SELECT
    CASE 
      WHEN LENGTH(TRIM(MODEL_MAPPING)) > 0 THEN 'MODEL_MAPPING'
      WHEN LENGTH(TRIM(D.MODEL)) > 0 THEN 'REF_1'
      WHEN LENGTH(TRIM(D.MODEL2)) > 0 THEN 'REF_2'
      WHEN LENGTH(TRIM(D.REF)) > 0 THEN 'REF_3'
      WHEN LENGTH(TRIM(D.REF2)) > 0 THEN 'REF_4'
      ELSE 'NÃO MAPEADO'
    END AS MAPPING_ORIGEM,
    CASE 
      WHEN LENGTH(TRIM(MODEL_MAPPING)) > 0 THEN MODEL_MAPPING
      WHEN LENGTH(TRIM(D.MODEL)) > 0 THEN SUBSTR(D.MODEL,1,99)
      WHEN LENGTH(TRIM(D.MODEL2)) > 0 THEN SUBSTR(D.MODEL2,1,99)
      WHEN LENGTH(TRIM(D.REF)) > 0 THEN SUBSTR(D.REF,1,99)
      WHEN LENGTH(TRIM(D.REF2)) > 0 THEN SUBSTR(D.REF2,1,99)
      ELSE NULL
    END AS MODEL_MAPPING,
    M.SITE_URL
  FROM OW_LAO.INPUT_CRAWLING_AP1_NPC_SITE_MAPPING AS M
  INNER JOIN OW_LAO.ODS_CRAWLING_AP1_NPC_PRODUCT_DETAIL AS D 
    ON TRIM(M.SITE_URL) = TRIM(D.PROD_HREF)
) AS MAPPING_AUTOMATICO
LEFT JOIN (
  SELECT B.* FROM (
    SELECT ITEM_ID, MAX(ROW_NUM) AS ROW_NUM
    FROM (
      SELECT S.ITEM_ID, ROW_NUMBER() OVER (PARTITION BY S.ITEM_ID) AS ROW_NUM
      FROM OW_LAO.INPUT_CRAWLING_AP1_NPC_SPEC_MAPPING AS S
    ) X
    GROUP BY ITEM_ID
  ) AS A
  INNER JOIN (
    SELECT 
      S.ITEM_ID,
      S.MODEL,
      S.SEGMENTS,
      S.ULTRA_THIN,
      S.KEYBOARD_TYPE,
      S.DEPTH_MM,
      S.OPERATING_SYSTEM,
      S.HEIGHT_MM,
      S.HARD_DRIVE_TYPE,
      S.STORAGE_IN_GB,
      S.RAM_IN_MB,
      S.WEIGHT_GRAMM,
      S.TOUCHSCREEN,
      S.CSP_MHZ,
      S.DVD_WRITER,
      S.DISTRIBUTION_TYPE,
      S.PROCESSOR_BRAND,
      S.OS_VERSION,
      S.PROCESSOR,
      S.PROCESSOR_NUMBER,
      S.GPU_BRAND,
      S.GPU_MODEL,
      S.CONVERTIBLE,
      S.GAMING_PRODUCTS,
      S.GPU_TYPE,
      S.DESIGN,
      S.DISPLAY_SIZE,
      S.INSTANT_ON,
      S.LOAD_DATE,
      ROW_NUMBER() OVER (PARTITION BY S.ITEM_ID) AS ROW_NUM
    FROM OW_LAO.INPUT_CRAWLING_AP1_NPC_SPEC_MAPPING AS S
  ) AS B
  ON A.ITEM_ID = B.ITEM_ID AND A.ROW_NUM = B.ROW_NUM
) AS S
  ON TRIM(UPPER(MAPPING_AUTOMATICO.MODEL_MAPPING)) = TRIM(UPPER(S.ITEM_ID));

END;
$$;

CALL PROC_CRAWLING_AP1_NPC_SITE_MAPPING_MERGE_AUTOMATIC();
