
CREATE PROCEDURE OW_LAO.PROC_D2C_NERP_WAREHOUSE_OPERATION
LANGUAGE SQLSCRIPT as
BEGIN
--Truncate tabela granular de WAREHOUSE_OPERATION
TRUNCATE TABLE OW_LAO.TF_WAREHOUSE_OPERATION;
--Inserir dados na tabela granular de WAREHOUSE_OPERATION
INSERT INTO  OW_LAO.TF_WAREHOUSE_OPERATION
SELECT	 DS.SUBSIDIARY
	,DP.PRODUCT_GROUP_1 AS DIMPROD_PRODUCT_GROUP
	,DP."DIVISION" AS DIMPROD_DIVISION
	,DP.PRODUCT_1 AS DIMPROD_PRODUCT
	,ONZOT.DELIVERY_NO
	,ONZOT.PLANT
	,DPL.ORIGIN AS PLANT_NAME
	,DC.YYYY AS "YEAR"
	,DC.YYYYQQ AS "QUARTER"
	,DC.YYYYMM AS "YEAR_MONTH"
	,DC.YYYYWW AS "WEEK"
	,ONZOT.DOCUMENT_DATE_LOCAL
	,ONZOT.NOTA_POSTING_DATE
	,ONZOT."1ST_GI_DATE"
	,ONZOT.BILLING_CREATED_ON
	,ONZOT.PLANNED_GI
	,ONZOT.DELIVERY_QTY
	,ONZOT.SOLDTO_CODE
	,ONZOT.EPOD_DATE
	,PP.PICK_DATETIME
	,ROUND((DTLTWD."TGT_WK_DO_PICKING"+DTLTWD."TGT_WK_PICKING_NF"+DTLTWD."TGT_WK_NF_GI"),1)  AS "Target LT_DO_GI_WK" 
	,ROUND((DTLTCD."TGT_CAL_DO_PICKING"+DTLTCD."TGT_CAL_PICKING_NF"+DTLTCD."TGT_CAL_NF_GI"),1) AS "Target LT_DO_GI_CAL"
	
	
	,NULL AS TOTAL_PLANNED_GI
	
	,CASE WHEN ONZOT."1ST_GI_DATE" IS NOT NULL THEN DELIVERY_QTY
		ELSE 0
	END AS ACTUAL_GI
		
	,CASE WHEN ONZOT."1ST_GI_DATE" <= ONZOT.PLANNED_GI THEN DELIVERY_QTY
		ELSE 0
	END AS ON_TIME_GI
	
	,CASE WHEN ONZOT."1ST_GI_DATE" = ONZOT.DOCUMENT_DATE_LOCAL THEN DELIVERY_QTY
		ELSE 0
	END AS SAME_DAY_GI
	
	--LT_DO_GI in Working Days
	,(SELECT CASE WHEN (SUM(WORK_DAY_SEDA)-1) = -1 THEN 0 WHEN (WEEKDAY(TO_DATE(ONZOT.DOCUMENT_DATE_LOCAL)) IN (5,6) AND WEEKDAY(TO_DATE(ONZOT."1ST_GI_DATE")) IN (5,6)) THEN SUM(WORK_DAY_SEDA) ELSE (SUM(WORK_DAY_SEDA)-1) END
	FROM OW_MD.DIM_CALENDAR DC WHERE (YYYYMMDD BETWEEN TO_DATE(ONZOT.DOCUMENT_DATE_LOCAL) AND TO_DATE(ONZOT."1ST_GI_DATE"))
	) AS "LT_WK_DO_GI" 
	--LT_DO_PICKING in Working Days
	,(SELECT CASE WHEN (SUM(WORK_DAY_SEDA)-1) = -1 THEN 0 WHEN (WEEKDAY(TO_DATE(ONZOT.DOCUMENT_DATE_LOCAL)) IN (5,6) AND WEEKDAY(TO_DATE(PP.PICK_DATETIME)) IN (5,6)) THEN SUM(WORK_DAY_SEDA) ELSE (SUM(WORK_DAY_SEDA)-1) END
	FROM OW_MD.DIM_CALENDAR DC WHERE (YYYYMMDD BETWEEN TO_DATE(ONZOT.DOCUMENT_DATE_LOCAL) AND TO_DATE(PP.PICK_DATETIME))
	) AS "LT_WK_DO_PICKING"
	--LT_PICKING_NF in Working Days
	,(SELECT CASE WHEN (SUM(WORK_DAY_SEDA)-1) = -1 THEN 0 WHEN (WEEKDAY(TO_DATE(PP.PICK_DATETIME)) IN (5,6) AND WEEKDAY(TO_DATE(ONZOT.NOTA_POSTING_DATE)) IN (5,6)) THEN SUM(WORK_DAY_SEDA) ELSE (SUM(WORK_DAY_SEDA)-1) END
	FROM OW_MD.DIM_CALENDAR DC WHERE (YYYYMMDD BETWEEN TO_DATE(PP.PICK_DATETIME) AND TO_DATE(ONZOT.NOTA_POSTING_DATE))
	) AS "LT_WK_PICKING_NF"
	--LT_PICKING_NF_GI in Working Days
	,(SELECT CASE WHEN (SUM(WORK_DAY_SEDA)-1) = -1 THEN 0 WHEN (WEEKDAY(TO_DATE(ONZOT.NOTA_POSTING_DATE)) IN (5,6) AND WEEKDAY(TO_DATE(ONZOT."1ST_GI_DATE")) IN (5,6)) THEN SUM(WORK_DAY_SEDA) ELSE (SUM(WORK_DAY_SEDA)-1) END
	FROM OW_MD.DIM_CALENDAR DC WHERE (YYYYMMDD BETWEEN TO_DATE(ONZOT.NOTA_POSTING_DATE) AND TO_DATE(ONZOT."1ST_GI_DATE"))
	) AS "LT_WK_PICKING_NF_GI"
	
	--Over Target DO
	,(CASE WHEN (SELECT CASE WHEN (SUM(WORK_DAY_SEDA)-1) = -1 THEN 0 WHEN (WEEKDAY(TO_DATE(ONZOT.DOCUMENT_DATE_LOCAL)) IN (5,6) AND WEEKDAY(TO_DATE(ONZOT."1ST_GI_DATE")) IN (5,6)) THEN SUM(WORK_DAY_SEDA) ELSE (SUM(WORK_DAY_SEDA)-1) END
	FROM OW_MD.DIM_CALENDAR DC WHERE (YYYYMMDD BETWEEN TO_DATE(ONZOT.DOCUMENT_DATE_LOCAL) AND TO_DATE(ONZOT."1ST_GI_DATE"))) 
	> ROUND((DTLTWD."TGT_WK_DO_PICKING"+DTLTWD."TGT_WK_PICKING_NF"+DTLTWD."TGT_WK_NF_GI"),1) THEN 1 ELSE 0 END) AS "OVER_TARGET_DO_WK"
	
	
	--LT_DO_GI in Days
	,(DAYS_BETWEEN(TO_DATE(ONZOT.DOCUMENT_DATE_LOCAL), TO_DATE(ONZOT."1ST_GI_DATE"))) AS "LT_DO_GI" 
	--LT_DO_PICKING in Days
	,(DAYS_BETWEEN(TO_DATE(ONZOT.DOCUMENT_DATE_LOCAL), TO_DATE(PP.PICK_DATETIME))) AS "LT_DO_PICKING"
	--LT_PICKING_NF in Days
	,(DAYS_BETWEEN(TO_DATE(PP.PICK_DATETIME), TO_DATE(ONZOT.NOTA_POSTING_DATE))) AS "LT_PICKING_NF"
	--LT_PICKING_NF_GI in Days
	,(DAYS_BETWEEN(TO_DATE(ONZOT.NOTA_POSTING_DATE), TO_DATE(ONZOT."1ST_GI_DATE"))) AS "LT_PICKING_NF_GI"
	,(CASE WHEN DAYS_BETWEEN(TO_DATE(ONZOT.DOCUMENT_DATE_LOCAL), TO_DATE(ONZOT."1ST_GI_DATE"))> 
	ROUND((DTLTCD."TGT_CAL_DO_PICKING"+DTLTCD."TGT_CAL_PICKING_NF"+DTLTCD."TGT_CAL_NF_GI"),1) THEN 1 ELSE 0 END ) AS "OVER_TARGET_DO_CAL"
	,NULL AS LAST_UPDATE
	
	
FROM OW_LAO.ODS_NERP_ZLLEJ50090_OUTBOUND_TRACKING ONZOT
	LEFT JOIN OW_SEDA_S.ODS_WMS_PICKING_PACKING PP ON ONZOT.DELIVERY_NO = PP.REF_NO AND ORDER_QTY= ONZOT.DELIVERY_QTY AND ONZOT.MATERIAL =PP.ITEM_CD 
	LEFT JOIN OW_MD.DIM_SUBSIDIARY DS ON DS.SALES_ORG =ONZOT.SALES_ORG 
	LEFT JOIN OW_MD.DIM_PRODUCT DP ON ONZOT.MATERIAL  = DP.SKU 
	LEFT JOIN OW_MD.DIM_PLANT DPL ON ONZOT.PLANT  = DPL.PLANT_CODE 
	LEFT JOIN OW_MD.DIM_TARGET_LEAD_TIME_CALENDAR_DAY DTLTCD ON (CASE WHEN UPPER(DP.DIVISION) IN ('DA','VD') THEN 'CE' ELSE 'OTHER'END = DTLTCD.DIVISION)
	LEFT JOIN OW_MD.DIM_TARGET_LEAD_TIME_WORKING_DAY DTLTWD ON (CASE WHEN UPPER(DP.DIVISION) IN ('DA','VD') THEN 'CE' ELSE 'OTHER'END = DTLTWD.DIVISION)
	LEFT JOIN OW_MD.DIM_CALENDAR DC ON (TO_DATE(ONZOT."1ST_GI_DATE")  = DC.YYYYMMDD)
WHERE ONZOT.EPOD_DATE IS NOT NULL 
	AND ONZOT.SO_TYPE = 'YS10' -- AND ONZASOT.SALES_DOC_TYPE = 'YS10'
	AND ONZOT.DO_TYPE = 'ZND1'
--	AND ONZOT.SHIPPING_TYPE IN ('P3','P4')
-- Esse UNION foi construido para termos a visão por Planned_GI	
UNION ALL 
SELECT	 DS.SUBSIDIARY
	,DP.PRODUCT_GROUP_1 AS DIMPROD_PRODUCT_GROUP
	,DP."DIVISION" AS DIMPROD_DIVISION
	,DP.PRODUCT_1 AS DIMPROD_PRODUCT
	,ONZOT.DELIVERY_NO
	,ONZOT.PLANT
	,DPL.ORIGIN AS PLANT_NAME
	,DC.YYYY AS "YEAR"
	,DC.YYYYQQ AS "QUARTER"
	,DC.YYYYMM AS "YEAR_MONTH"
	,DC.YYYYWW AS "WEEK"
	,ONZOT.DOCUMENT_DATE_LOCAL
	,ONZOT.NOTA_POSTING_DATE
	,ONZOT."1ST_GI_DATE"
	,ONZOT.BILLING_CREATED_ON
	,ONZOT.PLANNED_GI
	,ONZOT.DELIVERY_QTY
	,ONZOT.SOLDTO_CODE
	--,ONZOT.NET_VALUE
	--,ONZOT.AR_AMOUNT
	,ONZOT.EPOD_DATE
	,PP.PICK_DATETIME
	,ROUND((DTLTWD."TGT_WK_DO_PICKING"+DTLTWD."TGT_WK_PICKING_NF"+DTLTWD."TGT_WK_NF_GI"),1)  AS "Target LT_DO_GI_WK" 
	,ROUND((DTLTCD."TGT_CAL_DO_PICKING"+DTLTCD."TGT_CAL_PICKING_NF"+DTLTCD."TGT_CAL_NF_GI"),1) AS "Target LT_DO_GI_CAL"
	
	
	,CASE WHEN ONZOT.PLANNED_GI IS NOT NULL THEN DELIVERY_QTY
		ELSE 0
	END AS TOTAL_PLANNED_GI
	
	,NULL AS ACTUAL_GI
	
	
	,NULL AS ON_TIME_GI
	
	,NULL AS SAME_DAY_GI
	
	--LT_DO_GI in Working Days
	,NULL AS "LT_WK_DO_GI" 
	--LT_DO_PICKING in Working Days
	,NULL AS "LT_WK_DO_PICKING"
	--LT_PICKING_NF in Working Days
	,NULL AS "LT_WK_PICKING_NF"
	--LT_PICKING_NF_GI in Working Days
	,NULL AS "LT_WK_PICKING_NF_GI"
	
	--Over Target DO
	,NULL AS "OVER_TARGET_DO_WK"
	
	
	--LT_DO_GI in Days
	,NULL AS "LT_DO_GI" 
	--LT_DO_PICKING in Days
	,NULL AS "LT_DO_PICKING"
	--LT_PICKING_NF in Days
	,NULL AS "LT_PICKING_NF"
	--LT_PICKING_NF_GI in Days
	,NULL AS "LT_PICKING_NF_GI"
	
	--Over Target DO
	,NULL AS "OVER_TARGET_DO_CAL"
	
	,NULL AS LAST_UPDATE
FROM OW_LAO.ODS_NERP_ZLLEJ50090_OUTBOUND_TRACKING ONZOT
	LEFT JOIN OW_SEDA_S.ODS_WMS_PICKING_PACKING PP ON ONZOT.DELIVERY_NO = PP.REF_NO AND ORDER_QTY= ONZOT.DELIVERY_QTY AND ONZOT.MATERIAL =PP.ITEM_CD 
	LEFT JOIN OW_MD.DIM_SUBSIDIARY DS ON DS.SALES_ORG =ONZOT.SALES_ORG 
	LEFT JOIN OW_MD.DIM_PRODUCT DP ON ONZOT.MATERIAL  = DP.SKU 
	LEFT JOIN OW_MD.DIM_PLANT DPL ON ONZOT.PLANT  = DPL.PLANT_CODE 
	LEFT JOIN OW_MD.DIM_TARGET_LEAD_TIME_CALENDAR_DAY DTLTCD ON (CASE WHEN UPPER(DP.DIVISION) IN ('DA','VD') THEN 'CE' ELSE 'OTHER'END = DTLTCD.DIVISION)
	LEFT JOIN OW_MD.DIM_TARGET_LEAD_TIME_WORKING_DAY DTLTWD ON (CASE WHEN UPPER(DP.DIVISION) IN ('DA','VD') THEN 'CE' ELSE 'OTHER'END = DTLTWD.DIVISION)	
	LEFT JOIN OW_MD.DIM_CALENDAR DC ON (TO_DATE(ONZOT.PLANNED_GI)  = DC.YYYYMMDD)
WHERE ONZOT.EPOD_DATE IS NOT NULL 
	AND ONZOT.SO_TYPE = 'YS10' -- AND ONZASOT.SALES_DOC_TYPE = 'YS10'
	AND ONZOT.DO_TYPE = 'ZND1'
--	AND ONZOT.SHIPPING_TYPE IN ('P3','P4')
;
-- Update para Setar o horário de carga. Obs.: Estou fazendo aqui para não ter probemas com milisegundos
UPDATE OW_LAO.TF_WAREHOUSE_OPERATION 
	SET LAST_UPDATE = NOW()
	WHERE LAST_UPDATE IS NULL;
--Truncar os dados na tabela FT de WAREHOUSE_OPERATION
TRUNCATE TABLE OW_LAO.FT_WAREHOUSE_OPERATION ;
--Inserir dados na tabela FT de WAREHOUSE_OPERATION
INSERT INTO OW_LAO.FT_WAREHOUSE_OPERATION 
SELECT 
	SUBSIDIARY
	,DIMPROD_PRODUCT_GROUP 
	,DIMPROD_DIVISION
	,DIMPROD_PRODUCT
	,PLANT
	,PLANT_NAME
	,"YEAR" 
	,"QUARTER"
	,"YEAR_MONTH"
	,"WEEK"
	,"Target LT_DO_GI_WK" 
	,"Target LT_DO_GI_CAL"
	,AVG("LT_WK_DO_GI") AS "LT_WK_DO_GI" 
	,AVG("LT_WK_DO_PICKING") AS "LT_WK_DO_PICKING"
	,AVG("LT_WK_PICKING_NF") AS "LT_WK_PICKING_NF"
	,AVG("LT_WK_PICKING_NF_GI") AS "LT_WK_PICKING_NF_GI"
	,SUM(OVER_TARGET_DO_WK) AS OVER_TARGET_DO_WK
	,AVG("LT_DO_GI") AS "LT_DO_GI" 
	,AVG("LT_DO_PICKING") AS "LT_DO_PICKING"
	,AVG("LT_PICKING_NF") AS "LT_PICKING_NF"
	,AVG("LT_PICKING_NF_GI") AS "LT_PICKING_NF_GI"
	,SUM(OVER_TARGET_DO_CAL) AS OVER_TARGET_DO_CAL
	,COUNT(DELIVERY_NO) AS COUNT_DO
	--,SUM(NET_VALUE) AS NET_VALUE
	--,SUM(AR_AMOUNT) AS AR_AMOUNT
	,SUM(TOTAL_PLANNED_GI) AS TOTAL_PLANNED_GI
	,SUM(ACTUAL_GI) AS ACTUAL_GI
	,SUM(ON_TIME_GI) AS ON_TIME_GI
	,SUM(SAME_DAY_GI) AS SAME_DAY_GI
	,LAST_UPDATE
FROM OW_LAO.TF_WAREHOUSE_OPERATION
	GROUP BY 
	SUBSIDIARY
	,DIMPROD_PRODUCT_GROUP 
	,DIMPROD_DIVISION
	,DIMPROD_PRODUCT
	,PLANT
	,PLANT_NAME
	,"YEAR" 
	,"QUARTER"
	,"YEAR_MONTH"
	,"WEEK"
	,"Target LT_DO_GI_WK" 
	,"Target LT_DO_GI_CAL"
	,LAST_UPDATE
;	
END