CREATE PROCEDURE OW_LAO.PROC_D2C_NERP_ORDER_PENDING
 
LANGUAGE SQLSCRIPT as
 
BEGIN
	
--Truncar Tabela com os dados no nivel granular mais baixo para tratamento de dados 
TRUNCATE TABLE OW_LAO.FT_D2C_NERP_ORDER_PENDING;
	
--Inserir os dados no nivel granular mais baixo na tabela de transformação
INSERT INTO OW_LAO.FT_D2C_NERP_ORDER_PENDING  
SELECT SUBSIDIARY
,DIMPROD_PRODUCT_GROUP
,DIMPROD_DIVISION
,DIMPROD_PRODUCT
,MKT
,MATERIAL
,SALES_DOCUMENT
,ORDER_ID
,ITEM_INDEX
,PLANT
,PLANT_NAME
,STOR_LOC
,SPEC_PROCESSING
,PAYMENT_STATUS,SELECTED_SLA,QUANTITY,SO_CREATED_ON,PO_CREATED_ON,PENDING_DAYS,FLAG_PENDING_DAYS,DELIVERY_BLOCK,LAST_UPDATE
FROM (
SELECT  IFNULL(DS.SUBSIDIARY,'SEDA') AS SUBSIDIARY
	,DP.PRODUCT_GROUP_1 AS DIMPROD_PRODUCT_GROUP
	,DP."DIVISION" AS DIMPROD_DIVISION
	,DP.PRODUCT_1 AS DIMPROD_PRODUCT
	,DP.SEDA_DESC_ESTORE AS MKT
	,URVSBSSOL.REF_ID AS MATERIAL
	,ONZASOT.SALES_DOCUMENT
	,URVSBSSOL.ORDER_ID 
	,URVSBSSOL.ITEM_INDEX
	,DP2.PLANT_CODE AS PLANT
	,DP2.ORIGIN AS PLANT_NAME
	,ONZASOT.STOR_LOC
	,ONZASOT.SPEC_PROCESSING
	,CASE WHEN URVSBSSOL.AUTHORIZED_DATE IS NULL 
		THEN 'PENDING' 
		ELSE 'APPROVED' 
	END AS PAYMENT_STATUS
	,URVSBSSOL.SELECTED_SLA
	,URVSBSSOL.QUANTITY
	,TO_DATE(ONZASOT.SO_LOCAL_CREATE_ON_D) AS SO_CREATED_ON
	,TO_DATE(URVSBSSOL.CREATION_DATE) AS PO_CREATED_ON
	,CASE WHEN ONZASOT.SO_LOCAL_CREATE_ON_D IS NULL 
		THEN (DAYS_BETWEEN(TO_DATE(URVSBSSOL.CREATION_DATE), TO_DATE(CURRENT_DATE)))
		ELSE (DAYS_BETWEEN(TO_DATE(ONZASOT.SO_LOCAL_CREATE_ON_D), TO_DATE(CURRENT_DATE)))
	END AS PENDING_DAYS
	,CASE WHEN ONZASOT.SO_LOCAL_CREATE_ON_D IS NULL 
		THEN 'PO_WITHOUT_SO'
		ELSE 'SO_WITHOUT_DO'
	END AS FLAG_PENDING_DAYS
	,ONZASOT.DELIVERY_BLOCK
	,NULL AS LAST_UPDATE
	,ONZASOT.DO_LOCAL_CREATE_ON_D
	,ONZASOT.SALES_DOC_TYPE
	,ONZASOT.REJECT_REASON
	,ONZASOT.REJECT_REASON_1
	
FROM 	 (
SELECT RVSBSSOL.ORDER_ID, "SEQUENCE", TO_DATE(RVSBSSOL.CREATION_TIMESTAMP) AS CREATION_DATE, RVSBSSOL.STATUS_DESCRIPTION,
				RVSBSSOL.SALES_CHANNEL, RVSBSSOL.AUTHORIZED_DATE, RVSBSSOL.STATUS
				, RVSBSSOI.ITEM_INDEX,
				CASE WHEN RVSBSSOIC.REF_ID IS NULL 
					THEN RVSBSSOI.REF_ID
					ELSE RVSBSSOIC.REF_ID
				END AS REF_ID 
				,(RVSBSSOI.QUANTITY*IFNULL(RVSBSSOIC.QUANTITY,1)) AS QUANTITY
				, SELECTED_SLA 
				FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER RVSBSSOL
				LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_ITEM RVSBSSOI 
				ON (RVSBSSOL.ORDER_ID = RVSBSSOI.ORDER_ID)
				LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_ITEM_COMPONENTS RVSBSSOIC  
				ON (RVSBSSOI.ORDER_ID = RVSBSSOIC.ORDER_ID AND RVSBSSOI.SKU_ID = RVSBSSOIC.SKU_ID)
				LEFT JOIN ( 	
				SELECT DISTINCT ORDER_ID, ITEM_INDEX, SELECTED_SLA 
				FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_SHIPPING rvsbssos 
	   			) URVSBSSOS  ON RVSBSSOI.ORDER_ID = URVSBSSOS.ORDER_ID AND RVSBSSOI.ITEM_INDEX = URVSBSSOS.ITEM_INDEX
				WHERE RVSBSSOL.STATUS NOT IN ('canceled','cancel') AND RVSBSSOL.STATUS IS NOT NULL
				AND TO_DATE(RVSBSSOL.CREATION_TIMESTAMP)>='2022.12.18' --DATA de SO mais antiga Sales_Order_Tracking
          ) URVSBSSOL			
LEFT JOIN OW_LAO.ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING ONZASOT ON  ((URVSBSSOL.ORDER_ID =  ONZASOT.CUSTOMER_PO  OR TO_CHAR(URVSBSSOL."SEQUENCE") =  ONZASOT.CUSTOMER_PO )  
		AND URVSBSSOL.REF_ID = ONZASOT.MATERIAL )
LEFT JOIN OW_MD.DIM_SUBSIDIARY DS ON (ONZASOT.SALES_ORG = DS.SALES_ORG)
LEFT JOIN OW_MD.DIM_PLANT DP2 ON (ONZASOT.PLANT = DP2.PLANT_CODE)
LEFT JOIN OW_MD.DIM_PRODUCT DP ON (URVSBSSOL.REF_ID = DP.SKU)
WHERE 1=1
        AND DP.SEDA_BU_ESTORE <> 'SERVICE'  -- REMOVER SKUs de Serviço (Baseado na tabela do time de E Store)
	AND DO_LOCAL_CREATE_ON_D IS NULL 
	AND (SALES_DOC_TYPE = 'YS10' OR SALES_DOC_TYPE IS NULL)
	AND REJECT_REASON IS NULL 
	AND REJECT_REASON_1 IS NULL 
UNION ALL 
SELECT  IFNULL(DS.SUBSIDIARY,CASE WHEN AOHS.COUNTRY_CD = 'pe' THEN 'SEPR'
				  WHEN AOHS.COUNTRY_CD = 'mx' THEN 'SEM'
				  WHEN AOHS.COUNTRY_CD = 'co' THEN 'SAMCOL'
				  WHEN AOHS.COUNTRY_CD = 'cl' THEN 'SECH'
				  ELSE 'OTHERS' 
			     END) AS SUBSIDIARY
	,DP.PRODUCT_GROUP_1 AS DIMPROD_PRODUCT_GROUP
	,DP."DIVISION" AS DIMPROD_DIVISION
	,DP.PRODUCT_1 AS DIMPROD_PRODUCT
	,DP.SEDA_DESC_ESTORE AS MKT
	,AOHS.PRODUCT_CODE AS MATERIAL
	,ONZASOT.SALES_DOCUMENT
	,AOHS.ORDER_CODE AS ORDER_ID 
	,NULL AS ITEM_INDEX
	,ONZASOT.PLANT AS PLANT
	,DP2.ORIGIN AS PLANT_NAME
	,ONZASOT.STOR_LOC
	,ONZASOT.SPEC_PROCESSING
	,AOHS.PAYMENT_STATUS AS PAYMENT_STATUS
	,NULL AS SELECTED_SLA
	,AOHS.ORDER_ENTRY_QUANTITY AS QUANTITY
	,TO_DATE(ONZASOT.SO_LOCAL_CREATE_ON_D) AS SO_CREATED_ON
	,TO_DATE(AOHS.ORDER_CREATION_DATE) AS PO_CREATED_ON
	,CASE WHEN ONZASOT.SO_LOCAL_CREATE_ON_D IS NULL 
		THEN (DAYS_BETWEEN(TO_DATE(AOHS.ORDER_CREATION_DATE), TO_DATE(CURRENT_DATE)))
		ELSE (DAYS_BETWEEN(TO_DATE(ONZASOT.SO_LOCAL_CREATE_ON_D), TO_DATE(CURRENT_DATE)))
	END AS PENDING_DAYS
	,CASE WHEN ONZASOT.SO_LOCAL_CREATE_ON_D IS NULL 
		THEN 'PO_WITHOUT_SO'
		ELSE 'SO_WITHOUT_DO'
	END AS FLAG_PENDING_DAYS
	,ONZASOT.DELIVERY_BLOCK
	,NULL AS LAST_UPDATE
	,ONZASOT.DO_LOCAL_CREATE_ON_D
	,ONZASOT.SALES_DOC_TYPE
	,ONZASOT.REJECT_REASON
	,ONZASOT.REJECT_REASON_1
	
FROM
(SELECT DISTINCT OHS.ORDER_CREATION_DATE
				  ,OHS.SALES_ORDER
				  ,OHS.DELIVERY_ORDER
				  ,OHS.ORDER_STATUS
				  ,OHS.PRODUCT_CODE 
				  ,OHS.ORDER_ENTRY_QUANTITY 
				  ,OHS.COUNTRY_CD 
				  ,OHS.ORDER_CODE
				  ,CASE WHEN OHP.PAYMENT_STATUS = 'REJECTED'
				  		THEN OHP.PAYMENT_STATUS
					WHEN OHP.PAYMENT_STATUS IN ('ACCEPTED', 'SUCCESS') 
				  		THEN 'APPROVED'
					WHEN OHP.PAYMENT_STATUS IN ('ERROR','REVIEW')  OR 
					     OHP.PAYMENT_STATUS IS NULL  
						THEN 'PENDING'
					     	ELSE 'OTHER STATUS'
				   END AS PAYMENT_STATUS
			FROM OW_LAO.ODS_HYBRIS_SALES OHS
			LEFT JOIN OW_MD.DIM_PO_STATUS DPS ON OHS.ORDER_STATUS = DPS.STATUS_PO 
			LEFT JOIN OW_LAO.ODS_HYBRIS_PAYMENTS OHP ON (OHS.ID = OHP.ID)
			WHERE DPS.STATUS IN ('Canceled','Pending')
			AND OHS.CANCEL_REASON IS NULL 
			AND LENGTH(OHS.SALES_ORDER) = 10 
		) AOHS 
LEFT JOIN OW_LAO.ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING ONZASOT 
ON  (AOHS.SALES_ORDER = ONZASOT.SALES_DOCUMENT AND  AOHS.PRODUCT_CODE = ONZASOT.MATERIAL 
    AND AOHS.ORDER_CODE = ONZASOT.CUSTOMER_PO) 
LEFT JOIN OW_MD.DIM_SUBSIDIARY DS ON (ONZASOT.SALES_ORG = DS.SALES_ORG)
LEFT JOIN OW_MD.DIM_PLANT DP2 ON (ONZASOT.PLANT = DP2.PLANT_CODE)
LEFT JOIN OW_MD.DIM_PRODUCT DP ON (AOHS.PRODUCT_CODE = DP.SKU)							
WHERE 1=1
--       AND DP.SEDA_BU_ESTORE <> 'SERVICE'  -- REMOVER SKUs de Serviço (Baseado na tabela do time de E Store)
--	AND DO_LOCAL_CREATE_ON_D IS NULL 
	AND (SALES_DOC_TYPE = 'YS10' OR SALES_DOC_TYPE = 'YN01' OR SALES_DOC_TYPE IS NULL)
	AND REJECT_REASON IS NULL 
	AND REJECT_REASON_1 IS NULL
)
;
-- Update para Setar o horário de carga. Obs.: Estou fazendo aqui para não ter probemas com milisegundos
UPDATE OW_LAO.FT_D2C_NERP_ORDER_PENDING
	SET LAST_UPDATE = NOW()
	WHERE LAST_UPDATE IS NULL;
END