CREATE PROCEDURE OW_LAO.PROC_D2C_AR_CREATION_X_OPEN_OPENITEM_MONTH
LANGUAGE SQLSCRIPT as
BEGIN
--------------------------------------------MONTH-------------------------------------------------------------------------	
--Truncar Tabela com os dados no nivel granular mais baixo para tratamento de dados 
TRUNCATE TABLE OW_LAO.TMP_D2C_AR_CREATION_X_OPEN_OPENITEM_MONTH;
--Inserir os dados no nivel granular mais baixo na tabela de temporária
INSERT INTO  OW_LAO.TMP_D2C_AR_CREATION_X_OPEN_OPENITEM_MONTH
	SELECT   ONFNCLIDOI."Key"	
		,MKGA.SHORT_TEXT_ENGLISH AS GL_ACCOUNT_ENGLISH
		,ONFNCLIDOI."System Due date (In/Over)"	
		,ONFNCLIDOI."Range"
		,DP.SEDA_BU_ESTORE AS DIMPROD_PRODUCT_GROUP 
		,DP.SEDA_DIVISION_ESTORE AS DIMPROD_DIVISION 
		,ONFNCLIDOI."(+/-) AR"
		,MAC.CUSTOMER_NAME_SUMMARY AS "Customer Group (eStore/MKP)"
		,MAC.CUSTOMER_NAME_DETAIL AS CUSTOMER_NAME
		,ONFNCLIDOI.CUSTOMER
		,ONFNCLIDOI.AMOUNT_IN_LOCAL_CURRENCY
		,ONFNCLIDOI.ARREARS_BY_NET_DUE_DATE
		,ONFNCLIDOI.DOCUMENT_NUMBER
		,ONFNCLIDOI.CLEARING_DOCUMENT
		,ONFNCLIDOI.CLEARING_DATE
		,ONFNCLIDOI."ASSIGNMENT"
		,URVSBSSOL.ORDER_ID
		,URVSBSSOL.PO_AMOUNT
		,URVSBSSOL."SEQUENCE"		
		,ONFNCLIDOI.QTY_PO_DISTINCT
		,ONFNCLIDOI."TEXT"
		,ONFNCLIDOI.ENTRY_DATE
		,ONFNCLIDOI."G/L_ACCOUNT"
		,ONFNCLIDOI.LINE_ITEM
		,ONFNCLIDOI."G/L_ACCOUNT_1"
		,ONFNCLIDOI.POSTING_DATE
		,ONFNCLIDOI.USER_NAME
		,ONFNCLIDOI.FILE_NAME
		,ONFNCLIDOI.WEEK_MONTH_FILE_NAME
		,ONFNCLIDOI.OPEN_ALL_FILE_NAME
		,ONFNCLIDOI.YEAR_WEEK_FILE_NAME
		,ONFNCLIDOI.YEAR_MONTH_FILE_NAME
		,NOW() AS LOAD_DATE
		,NULL AS "TYPE"
		,NULL AS "1_CATE"
		,NULL AS "2_CATE"
		,NULL AS "3_CATE"
		,NULL AS "REASON TYPE"
		,NULL AS "PIC"
		,NULL AS REMARK
		,NULL AS "NEXT STEP"		
	FROM (SELECT
		ROW_NUMBER() OVER () AS NUM_LINE
		,ROW_NUMBER() OVER (PARTITION BY ONFNCLIDOI2."ASSIGNMENT" ORDER BY ONFNCLIDOI2."ASSIGNMENT" DESC, ONFNCLIDOI2.FILE_NAME) AS QTY_PO_DISTINCT
		,IFNULL(ONFNCLIDOI2.CUSTOMER,'') || IFNULL(ONFNCLIDOI2."ASSIGNMENT",'') || IFNULL(ONFNCLIDOI2.DOCUMENT_NUMBER,'') || IFNULL(REPLACE(ONFNCLIDOI2.AMOUNT_IN_LOCAL_CURRENCY,'.',','),'') || IFNULL(ONFNCLIDOI2.LINE_ITEM,'') AS "Key"	
		,(CASE WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE > 0
			THEN 'Over'
			ELSE 'In'
		END) AS "System Due date (In/Over)"	
		,(CASE WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE<=-46
			THEN '* Indue'
		 WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN -45 AND -38
			THEN '0~7 Indue'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN -37 AND -30
			THEN '8~15 Indue'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN -29 AND -15
			THEN '16~30 Indue'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN -14 AND 0
			THEN '31~45 Indue'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN 1 AND 7
			THEN '1 ~ 7 days'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN 8 AND 14
			THEN '8 ~ 14 days'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN 15 AND 31
			THEN '15 ~ 31 days'	
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN 32 AND 60
			THEN '32 ~ 60 days'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN 61 AND 90
			THEN '61 ~ 90 days'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN 91 AND 180
			THEN '91~180 days'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN 181 AND 360
			THEN '181~360 days'
			ELSE 'Over 360'
		END) AS "Range"
		,(CASE WHEN TO_DOUBLE(ONFNCLIDOI2.AMOUNT_IN_LOCAL_CURRENCY) > 0
			THEN '(+) AR'
			ELSE '(-) AR'
		END) AS "(+/-) AR"
		,ONFNCLIDOI2.CUSTOMER
		,REPLACE(ONFNCLIDOI2.AMOUNT_IN_LOCAL_CURRENCY,'.',',') AS AMOUNT_IN_LOCAL_CURRENCY
		,ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE
		,ONFNCLIDOI2.DOCUMENT_NUMBER
		,ONFNCLIDOI2.CLEARING_DOCUMENT
		,ONFNCLIDOI2.CLEARING_DATE
		,ONFNCLIDOI2."ASSIGNMENT"	
		,ONFNCLIDOI2."TEXT"
		,TO_DATE(ONFNCLIDOI2.ENTRY_DATE) AS ENTRY_DATE
		,ONFNCLIDOI2."G/L_ACCOUNT"
		,ONFNCLIDOI2.LINE_ITEM
		,ONFNCLIDOI2."G/L_ACCOUNT_1"
		,TO_DATE(ONFNCLIDOI2.POSTING_DATE) AS POSTING_DATE
		,ONFNCLIDOI2.USER_NAME
		,ONFNCLIDOI2.FILE_NAME
		,(CASE WHEN ONFNCLIDOI2.FILE_NAME LIKE '%WEEK%' 
			THEN 'WEEK'
		       WHEN ONFNCLIDOI2.FILE_NAME LIKE'%MONTH%'
		 	THEN 'MONTH'
		 	ELSE NULL
		 END) AS WEEK_MONTH_FILE_NAME
		,(CASE WHEN ONFNCLIDOI2.FILE_NAME LIKE '%ALL%' 
			THEN 'ALL'
		       WHEN ONFNCLIDOI2.FILE_NAME LIKE'%OPEN%'
		 	THEN 'OPEN'
		 	ELSE NULL
		 END) AS OPEN_ALL_FILE_NAME
		 
		 ,(SELECT DC.YYYYWW_NORMAL_CALENDAR FROM OW_MD.DIM_CALENDAR DC WHERE DC.YYYYMMDD = TO_DATE(SUBSTRING(ONFNCLIDOI2.FILE_NAME,26,8))) AS "YEAR_WEEK_FILE_NAME"
		 ,(SELECT DC.YYYYMM_NORMAL_CALENDAR FROM OW_MD.DIM_CALENDAR DC WHERE DC.YYYYMMDD = TO_DATE(SUBSTRING(ONFNCLIDOI2.FILE_NAME,26,8))) AS "YEAR_MONTH_FILE_NAME"
		,ONFNCLIDOI2.LOAD_DATE
	FROM OW_SEDA_S.ODS_NERP_FBL5N_CUSTOMER_LINE_ITEM_DISPLAY_OPEN_ITEMS_HIST ONFNCLIDOI2 
	WHERE UPPER(ONFNCLIDOI2.FILE_NAME) LIKE '%OPENITEM_MONTH%'
	-- TO REPROCESS THE COMPLETE BASE, COMMENT ON THE TWO LINES BELOW
	AND YEAR(TO_DATE(SUBSTRING(ONFNCLIDOI2.FILE_NAME,26,8)))||MONTH(TO_DATE(SUBSTRING(ONFNCLIDOI2.FILE_NAME,26,8)))
	= YEAR(ADD_MONTHS(CURRENT_DATE,-1))||MONTH(ADD_MONTHS(CURRENT_DATE,-1))	
		ORDER BY  ROW_NUMBER() OVER () ASC, ONFNCLIDOI2.CUSTOMER, ONFNCLIDOI2."ASSIGNMENT", ONFNCLIDOI2.DOCUMENT_NUMBER, REPLACE(ONFNCLIDOI2.AMOUNT_IN_LOCAL_CURRENCY,'.',',')
	) ONFNCLIDOI 
	LEFT JOIN (SELECT * FROM (SELECT --DISTINCT 
				 	ROW_NUMBER() OVER (PARTITION BY IFNULL(RVSBSSOL."SEQUENCE",RVSBSSOL.ORDER_ID) 
	         				ORDER BY IFNULL(RVSBSSOL."SEQUENCE",RVSBSSOL.ORDER_ID) DESC, RVSBSSOI.PRICE DESC) AS ROW_NUM
				 	,RVSBSSOL.ORDER_ID
				 	, RVSBSSOL.MARKETPLACE_ORDER_ID
				 	, RVSBSSOL.AFFILIATE_ID
				        , RVSBSSOL."SEQUENCE"
				        , TO_DATE(RVSBSSOL.CREATION_TIMESTAMP) AS CREATION_DATE
				        , RVSBSSOL.CANCELLATION_DATE
				        , RVSBSSOL.STATUS_DESCRIPTION
				        , RVSBSSOL.SALES_CHANNEL
				        , RVSBSSOL.AUTHORIZED_DATE
				        , RVSBSSOL.STATUS
					, RVSBSSOI.ITEM_INDEX,
					CASE WHEN RVSBSSOIC.REF_ID IS NULL 
						THEN RVSBSSOI.REF_ID
						ELSE RVSBSSOIC.REF_ID
					END AS REF_ID 
					, (RVSBSSOI.QUANTITY*IFNULL(RVSBSSOIC.QUANTITY,1)) AS QUANTITY
					, (RVSBSSOL.VALUE/100) AS "PO_AMOUNT"
					, URVSBSSOS."SELECTED_SLA"
	                  		, URVSBSSOS."WAREHOUSE_ID_GROUP"
	                  		, URVSBSSOS.ADDRESSTYPE
	                  		, URVSBSSOS.FRIENDLYNAME
	                  		, URVSBSSOS.STATE
	                  		, URVSBSSOS.CITY
			  		, CASE WHEN ( TRIM(UPPER(URVSBSSOS."SELECTED_SLA")) LIKE 'SHIP TO STORE %' 
	                                   		OR TRIM(UPPER(URVSBSSOS."SELECTED_SLA"))LIKE 'PONTO DE RETIRADA %'
	                                   		OR TRIM(UPPER(URVSBSSOS."SELECTED_SLA"))LIKE 'CLIQUE%'
	                             		    )
	                        		    AND OVSBSDESS.ID_STORE IS NOT NULL --PO.CHANNEL_TYPE = 'Store+'
	                        				THEN 'BOPIS + EA'
	                        	       WHEN ( TRIM(UPPER(URVSBSSOS."SELECTED_SLA")) LIKE 'SHIP TO STORE %'
	                                 		OR TRIM(UPPER(URVSBSSOS."SELECTED_SLA"))LIKE 'PONTO DE RETIRADA %'
	                                 		OR TRIM(UPPER(URVSBSSOS."SELECTED_SLA"))LIKE 'CLIQUE%'
	                        		    )
	                        				THEN 'BOPIS'
	                        	       WHEN OVSBSDESS.ID_STORE IS NOT NULL --( PO.CHANNEL_TYPE = 'Store+' )
	                        				THEN 'EA'
	                  					ELSE NULL 
	                  		END AS O2O_TYPE
					, OVSBSDESS.ID_STORE
					, CASE WHEN OVSBSDESS.ID_STORE IS NOT NULL THEN 'Store+' ELSE 'Shop' END AS CHANNEL_TYPE
					, OVSBSDESS.NAME AS NAME_STORE
					, RVSBSSOL.LAST_CHANGE
					--,RVSBSSOI.*
					FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER RVSBSSOL
					LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_ITEM RVSBSSOI 
					ON (RVSBSSOL.ORDER_ID = RVSBSSOI.ORDER_ID)
					LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_ITEM_COMPONENTS RVSBSSOIC  
					ON (RVSBSSOI.ORDER_ID = RVSBSSOIC.ORDER_ID AND RVSBSSOI.SKU_ID = RVSBSSOIC.SKU_ID)
					LEFT JOIN ( 	SELECT DISTINCT ORDER_ID
										, ITEM_INDEX
										, MAX(JSON_VALUE('[' || PICKUP_STORE_INFO || ']', '$.address.addressType')) AS ADDRESSTYPE
					                        		, MAX(JSON_VALUE('[' || PICKUP_STORE_INFO || ']', '$.friendlyName')) AS FRIENDLYNAME
					                        		, MAX(STATE) AS STATE
					                        		, MAX(CITY) AS CITY
					                        		, MAX(SELECTED_SLA) AS SELECTED_SLA
					                        		, STRING_AGG(WAREHOUSE_ID, ' | ') AS WAREHOUSE_ID_GROUP
							FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_SHIPPING rvsbssos
									GROUP BY ORDER_ID
	                           				,ITEM_INDEX
		   				  ) URVSBSSOS  ON RVSBSSOI.ORDER_ID = URVSBSSOS.ORDER_ID 
		   				              AND RVSBSSOI.ITEM_INDEX = URVSBSSOS.ITEM_INDEX
					LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SALES_ORDER RVSBSO  /* (SSG BR - ORDER) */ 	
					ON (RVSBSSOL.MARKETPLACE_ORDER_ID = RVSBSO.ORDER_ID)   				            
					LEFT JOIN U_PRJ_ECOM.ODS_VTEX_SSG_BR_SHOP_DATA_ENTITIES_STORES_SDS OVSBSDESS 
					ON ((CASE WHEN (CASE
								-- CD_STORE_INFORMATION
					       			WHEN RVSBSSOL.CD_STORE_INFORMATION IS NOT NULL 
									THEN RVSBSSOL.CD_STORE_INFORMATION
									ELSE RVSBSO.CD_STORE_INFORMATION
							  END) IS NOT NULL 
								THEN(CASE
									 -- CD_STORE_INFORMATION 
									 WHEN RVSBSSOL.CD_STORE_INFORMATION IS NOT NULL 
									 	THEN RVSBSSOL.CD_STORE_INFORMATION
										ELSE RVSBSO.CD_STORE_INFORMATION
								     END)
								ELSE(CASE
									  -- UTM_SOURCE
									  WHEN RVSBSSOL.UTM_SOURCE IS NOT NULL 
									  	THEN RVSBSSOL.UTM_SOURCE
										ELSE RVSBSO.UTM_SOURCE
								    END)
						END) = OVSBSDESS.ID_STORE)	
	        WHERE  1=1
	        AND RVSBSSOL.STATUS_DESCRIPTION IS NOT NULL
				)
	
	WHERE ROW_NUM = 1
	) URVSBSSOL
	ON (ONFNCLIDOI."ASSIGNMENT" = URVSBSSOL."SEQUENCE" OR ONFNCLIDOI."ASSIGNMENT" = URVSBSSOL.ORDER_ID)
		LEFT JOIN OW_MD.DIM_PRODUCT DP ON (URVSBSSOL.REF_ID = DP.SKU)
		LEFT JOIN OW_MD.MAP_AR_MONTH_KEY_GL_ACCOUNT MKGA ON (ONFNCLIDOI."G/L_ACCOUNT" = MKGA.GL_ACCT)
		LEFT JOIN OW_MD.MAP_AR_MONTH_CUSTOMER MAC ON (ONFNCLIDOI.CUSTOMER = MAC.CUSTOMER_CODE)
		;
--Truncar Tabela com os dados no nivel granular mais baixo para tratamento de dados 
TRUNCATE TABLE OW_LAO.TMP_D2C_AR_CREATION_X_ALLITEM_MONTH;
--Inserir os dados no nivel granular mais baixo na tabela de temporária
INSERT INTO  OW_LAO.TMP_D2C_AR_CREATION_X_ALLITEM_MONTH
		SELECT   ONFNCLIDOI."Key"	
		,MKGA.SHORT_TEXT_ENGLISH AS GL_ACCOUNT_ENGLISH
		,ONFNCLIDOI."System Due date (In/Over)"	
		,ONFNCLIDOI."Range"
		,DP.SEDA_BU_ESTORE AS DIMPROD_PRODUCT_GROUP 
		,DP.SEDA_DIVISION_ESTORE AS DIMPROD_DIVISION 
		,ONFNCLIDOI."(+/-) AR"
		,MAC.CUSTOMER_NAME_SUMMARY AS "Customer Group (eStore/MKP)"
		,MAC.CUSTOMER_NAME_DETAIL AS CUSTOMER_NAME
		,ONFNCLIDOI.CUSTOMER
		,ONFNCLIDOI.AMOUNT_IN_LOCAL_CURRENCY
		,ONFNCLIDOI.ARREARS_BY_NET_DUE_DATE
		,ONFNCLIDOI.DOCUMENT_NUMBER
		,ONFNCLIDOI.CLEARING_DOCUMENT
		,ONFNCLIDOI.CLEARING_DATE
		,ONFNCLIDOI."ASSIGNMENT"
		,URVSBSSOL.ORDER_ID
		,URVSBSSOL.PO_AMOUNT
		,URVSBSSOL."SEQUENCE"		
		,ONFNCLIDOI.QTY_PO_DISTINCT
		,ONFNCLIDOI."TEXT"
		,ONFNCLIDOI.ENTRY_DATE
		,ONFNCLIDOI."G/L_ACCOUNT"
		,ONFNCLIDOI.LINE_ITEM
		,ONFNCLIDOI."G/L_ACCOUNT_1"
		,ONFNCLIDOI.POSTING_DATE
		,ONFNCLIDOI.USER_NAME
		,ONFNCLIDOI.FILE_NAME
		,ONFNCLIDOI.WEEK_MONTH_FILE_NAME
		,ONFNCLIDOI.OPEN_ALL_FILE_NAME
		,ONFNCLIDOI.YEAR_WEEK_FILE_NAME
		,ONFNCLIDOI.YEAR_MONTH_FILE_NAME
		,NOW() AS LOAD_DATE
		,NULL AS "TYPE"
		,NULL AS "1_CATE"
		,NULL AS "2_CATE"
		,NULL AS "3_CATE"
		,NULL AS "REASON TYPE"
		,NULL AS "PIC"
		,NULL AS REMARK
		,NULL AS "NEXT STEP"		
	FROM (SELECT
		ROW_NUMBER() OVER () AS NUM_LINE
		,ROW_NUMBER() OVER (PARTITION BY ONFNCLIDOI2."ASSIGNMENT" ORDER BY ONFNCLIDOI2."ASSIGNMENT" DESC, ONFNCLIDOI2.FILE_NAME) AS QTY_PO_DISTINCT
		,IFNULL(ONFNCLIDOI2.CUSTOMER,'') || IFNULL(ONFNCLIDOI2."ASSIGNMENT",'') || IFNULL(ONFNCLIDOI2.DOCUMENT_NUMBER,'') || IFNULL(REPLACE(ONFNCLIDOI2.AMOUNT_IN_LOCAL_CURRENCY,'.',','),'') || IFNULL(ONFNCLIDOI2.LINE_ITEM,'') AS "Key"	
		,(CASE WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE > 0
			THEN 'Over'
			ELSE 'In'
		END) AS "System Due date (In/Over)"	
		,(CASE WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE<=-46
			THEN '* Indue'
		 WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN -45 AND -38
			THEN '0~7 Indue'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN -37 AND -30
			THEN '8~15 Indue'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN -29 AND -15
			THEN '16~30 Indue'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN -14 AND 0
			THEN '31~45 Indue'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN 1 AND 7
			THEN '1 ~ 7 days'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN 8 AND 14
			THEN '8 ~ 14 days'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN 15 AND 31
			THEN '15 ~ 31 days'	
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN 32 AND 60
			THEN '32 ~ 60 days'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN 61 AND 90
			THEN '61 ~ 90 days'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN 91 AND 180
			THEN '91~180 days'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN 181 AND 360
			THEN '181~360 days'
			ELSE 'Over 360'
		END) AS "Range"
		,(CASE WHEN TO_DOUBLE(ONFNCLIDOI2.AMOUNT_IN_LOCAL_CURRENCY) > 0
			THEN '(+) AR'
			ELSE '(-) AR'
		END) AS "(+/-) AR"
		,ONFNCLIDOI2.CUSTOMER
		,REPLACE(ONFNCLIDOI2.AMOUNT_IN_LOCAL_CURRENCY,'.',',') AS AMOUNT_IN_LOCAL_CURRENCY
		,ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE
		,ONFNCLIDOI2.DOCUMENT_NUMBER
		,ONFNCLIDOI2.CLEARING_DOCUMENT
		,ONFNCLIDOI2.CLEARING_DATE
		,ONFNCLIDOI2."ASSIGNMENT"	
		,ONFNCLIDOI2."TEXT"
		,TO_DATE(ONFNCLIDOI2.ENTRY_DATE) AS ENTRY_DATE
		,ONFNCLIDOI2."G/L_ACCOUNT"
		,ONFNCLIDOI2.LINE_ITEM
		,ONFNCLIDOI2."G/L_ACCOUNT_1"
		,TO_DATE(ONFNCLIDOI2.POSTING_DATE) AS POSTING_DATE
		,ONFNCLIDOI2.USER_NAME
		,ONFNCLIDOI2.FILE_NAME
		,(CASE WHEN ONFNCLIDOI2.FILE_NAME LIKE '%WEEK%' 
			THEN 'WEEK'
		       WHEN ONFNCLIDOI2.FILE_NAME LIKE'%MONTH%'
		 	THEN 'MONTH'
		 	ELSE NULL
		 END) AS WEEK_MONTH_FILE_NAME
		,(CASE WHEN ONFNCLIDOI2.FILE_NAME LIKE '%ALL%' 
			THEN 'ALL'
		       WHEN ONFNCLIDOI2.FILE_NAME LIKE'%OPEN%'
		 	THEN 'OPEN'
		 	ELSE NULL
		 END) AS OPEN_ALL_FILE_NAME
		 
		 ,(SELECT DC.YYYYWW_NORMAL_CALENDAR FROM OW_MD.DIM_CALENDAR DC WHERE DC.YYYYMMDD = TO_DATE(SUBSTRING(ONFNCLIDOI2.FILE_NAME,25,8))) AS "YEAR_WEEK_FILE_NAME"
		 ,(SELECT DC.YYYYMM_NORMAL_CALENDAR FROM OW_MD.DIM_CALENDAR DC WHERE DC.YYYYMMDD = TO_DATE(SUBSTRING(ONFNCLIDOI2.FILE_NAME,25,8))) AS "YEAR_MONTH_FILE_NAME"
		,ONFNCLIDOI2.LOAD_DATE
	FROM OW_SEDA_S.ODS_NERP_FBL5N_CUSTOMER_LINE_ITEM_DISPLAY_OPEN_ITEMS_HIST ONFNCLIDOI2 
	WHERE UPPER(ONFNCLIDOI2.FILE_NAME) LIKE '%ALLITEM_MONTH%'
	-- TO REPROCESS THE COMPLETE BASE, COMMENT ON THE TWO LINES BELOW
	AND YEAR(TO_DATE(SUBSTRING(ONFNCLIDOI2.FILE_NAME,25,8)))||MONTH(TO_DATE(SUBSTRING(ONFNCLIDOI2.FILE_NAME,25,8)))
	= YEAR(ADD_MONTHS(CURRENT_DATE,-1))||MONTH(ADD_MONTHS(CURRENT_DATE,-1))	
		ORDER BY  ROW_NUMBER() OVER () ASC, ONFNCLIDOI2.CUSTOMER, ONFNCLIDOI2."ASSIGNMENT", ONFNCLIDOI2.DOCUMENT_NUMBER, REPLACE(ONFNCLIDOI2.AMOUNT_IN_LOCAL_CURRENCY,'.',',')
	) ONFNCLIDOI 
	LEFT JOIN (SELECT * FROM (SELECT --DISTINCT 
				 	ROW_NUMBER() OVER (PARTITION BY IFNULL(RVSBSSOL."SEQUENCE",RVSBSSOL.ORDER_ID) 
	         				ORDER BY IFNULL(RVSBSSOL."SEQUENCE",RVSBSSOL.ORDER_ID) DESC, RVSBSSOI.PRICE DESC) AS ROW_NUM
				 	,RVSBSSOL.ORDER_ID
				 	, RVSBSSOL.MARKETPLACE_ORDER_ID
				 	, RVSBSSOL.AFFILIATE_ID
				        , RVSBSSOL."SEQUENCE"
				        , TO_DATE(RVSBSSOL.CREATION_TIMESTAMP) AS CREATION_DATE
				        , RVSBSSOL.CANCELLATION_DATE
				        , RVSBSSOL.STATUS_DESCRIPTION
				        , RVSBSSOL.SALES_CHANNEL
				        , RVSBSSOL.AUTHORIZED_DATE
				        , RVSBSSOL.STATUS
					, RVSBSSOI.ITEM_INDEX,
					CASE WHEN RVSBSSOIC.REF_ID IS NULL 
						THEN RVSBSSOI.REF_ID
						ELSE RVSBSSOIC.REF_ID
					END AS REF_ID 
					, (RVSBSSOI.QUANTITY*IFNULL(RVSBSSOIC.QUANTITY,1)) AS QUANTITY
					, (RVSBSSOL.VALUE/100) AS "PO_AMOUNT"
					, URVSBSSOS."SELECTED_SLA"
	                  		, URVSBSSOS."WAREHOUSE_ID_GROUP"
	                  		, URVSBSSOS.ADDRESSTYPE
	                  		, URVSBSSOS.FRIENDLYNAME
	                  		, URVSBSSOS.STATE
	                  		, URVSBSSOS.CITY
			  		, CASE WHEN ( TRIM(UPPER(URVSBSSOS."SELECTED_SLA")) LIKE 'SHIP TO STORE %' 
	                                   		OR TRIM(UPPER(URVSBSSOS."SELECTED_SLA"))LIKE 'PONTO DE RETIRADA %'
	                                   		OR TRIM(UPPER(URVSBSSOS."SELECTED_SLA"))LIKE 'CLIQUE%'
	                             		    )
	                        		    AND OVSBSDESS.ID_STORE IS NOT NULL --PO.CHANNEL_TYPE = 'Store+'
	                        				THEN 'BOPIS + EA'
	                        	       WHEN ( TRIM(UPPER(URVSBSSOS."SELECTED_SLA")) LIKE 'SHIP TO STORE %'
	                                 		OR TRIM(UPPER(URVSBSSOS."SELECTED_SLA"))LIKE 'PONTO DE RETIRADA %'
	                                 		OR TRIM(UPPER(URVSBSSOS."SELECTED_SLA"))LIKE 'CLIQUE%'
	                        		    )
	                        				THEN 'BOPIS'
	                        	       WHEN OVSBSDESS.ID_STORE IS NOT NULL --( PO.CHANNEL_TYPE = 'Store+' )
	                        				THEN 'EA'
	                  					ELSE NULL 
	                  		END AS O2O_TYPE
					, OVSBSDESS.ID_STORE
					, CASE WHEN OVSBSDESS.ID_STORE IS NOT NULL THEN 'Store+' ELSE 'Shop' END AS CHANNEL_TYPE
					, OVSBSDESS.NAME AS NAME_STORE
					, RVSBSSOL.LAST_CHANGE
					--,RVSBSSOI.*
					FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER RVSBSSOL
					LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_ITEM RVSBSSOI 
					ON (RVSBSSOL.ORDER_ID = RVSBSSOI.ORDER_ID)
					LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_ITEM_COMPONENTS RVSBSSOIC  
					ON (RVSBSSOI.ORDER_ID = RVSBSSOIC.ORDER_ID AND RVSBSSOI.SKU_ID = RVSBSSOIC.SKU_ID)
					LEFT JOIN ( 	SELECT DISTINCT ORDER_ID
										, ITEM_INDEX
										, MAX(JSON_VALUE('[' || PICKUP_STORE_INFO || ']', '$.address.addressType')) AS ADDRESSTYPE
					                        		, MAX(JSON_VALUE('[' || PICKUP_STORE_INFO || ']', '$.friendlyName')) AS FRIENDLYNAME
					                        		, MAX(STATE) AS STATE
					                        		, MAX(CITY) AS CITY
					                        		, MAX(SELECTED_SLA) AS SELECTED_SLA
					                        		, STRING_AGG(WAREHOUSE_ID, ' | ') AS WAREHOUSE_ID_GROUP
							FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_SHIPPING rvsbssos
									GROUP BY ORDER_ID
	                           				,ITEM_INDEX
		   				  ) URVSBSSOS  ON RVSBSSOI.ORDER_ID = URVSBSSOS.ORDER_ID 
		   				              AND RVSBSSOI.ITEM_INDEX = URVSBSSOS.ITEM_INDEX
					LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SALES_ORDER RVSBSO  /* (SSG BR - ORDER) */ 	
					ON (RVSBSSOL.MARKETPLACE_ORDER_ID = RVSBSO.ORDER_ID)   				            
					LEFT JOIN U_PRJ_ECOM.ODS_VTEX_SSG_BR_SHOP_DATA_ENTITIES_STORES_SDS OVSBSDESS 
					ON ((CASE WHEN (CASE
								-- CD_STORE_INFORMATION
					       			WHEN RVSBSSOL.CD_STORE_INFORMATION IS NOT NULL 
									THEN RVSBSSOL.CD_STORE_INFORMATION
									ELSE RVSBSO.CD_STORE_INFORMATION
							  END) IS NOT NULL 
								THEN(CASE
									 -- CD_STORE_INFORMATION 
									 WHEN RVSBSSOL.CD_STORE_INFORMATION IS NOT NULL 
									 	THEN RVSBSSOL.CD_STORE_INFORMATION
										ELSE RVSBSO.CD_STORE_INFORMATION
								     END)
								ELSE(CASE
									  -- UTM_SOURCE
									  WHEN RVSBSSOL.UTM_SOURCE IS NOT NULL 
									  	THEN RVSBSSOL.UTM_SOURCE
										ELSE RVSBSO.UTM_SOURCE
								    END)
						END) = OVSBSDESS.ID_STORE)	
	        WHERE  1=1
	        AND RVSBSSOL.STATUS_DESCRIPTION IS NOT NULL
				)
	
	WHERE ROW_NUM = 1
	) URVSBSSOL
	ON (ONFNCLIDOI."ASSIGNMENT" = URVSBSSOL."SEQUENCE" OR ONFNCLIDOI."ASSIGNMENT" = URVSBSSOL.ORDER_ID)
		LEFT JOIN OW_MD.DIM_PRODUCT DP ON (URVSBSSOL.REF_ID = DP.SKU)
		LEFT JOIN OW_MD.MAP_AR_MONTH_KEY_GL_ACCOUNT MKGA ON (ONFNCLIDOI."G/L_ACCOUNT" = MKGA.GL_ACCT)
		LEFT JOIN OW_MD.MAP_AR_MONTH_CUSTOMER MAC ON (ONFNCLIDOI.CUSTOMER = MAC.CUSTOMER_CODE)
	;
--------------------------------------------WEEK-------------------------------------------------------------------------
--Truncar Tabela com os dados no nivel granular mais baixo para tratamento de dados 
TRUNCATE TABLE OW_LAO.TMP_D2C_AR_CREATION_X_OPEN_OPENITEM_WEEK;
--Inserir os dados no nivel granular mais baixo na tabela de temporária
INSERT INTO  OW_LAO.TMP_D2C_AR_CREATION_X_OPEN_OPENITEM_WEEK
	SELECT   ONFNCLIDOI."Key"	
		,MKGA.SHORT_TEXT_ENGLISH AS GL_ACCOUNT_ENGLISH
		,ONFNCLIDOI."System Due date (In/Over)"	
		,ONFNCLIDOI."Range"
		,DP.SEDA_BU_ESTORE AS DIMPROD_PRODUCT_GROUP 
		,DP.SEDA_DIVISION_ESTORE AS DIMPROD_DIVISION 
		,ONFNCLIDOI."(+/-) AR"
		,MAC.CUSTOMER_NAME_SUMMARY AS "Customer Group (eStore/MKP)"
		,MAC.CUSTOMER_NAME_DETAIL AS CUSTOMER_NAME
		,ONFNCLIDOI.CUSTOMER
		,ONFNCLIDOI.AMOUNT_IN_LOCAL_CURRENCY
		,ONFNCLIDOI.ARREARS_BY_NET_DUE_DATE
		,ONFNCLIDOI.DOCUMENT_NUMBER
		,ONFNCLIDOI.CLEARING_DOCUMENT
		,ONFNCLIDOI.CLEARING_DATE
		,ONFNCLIDOI."ASSIGNMENT"
		,URVSBSSOL.ORDER_ID
		,URVSBSSOL.PO_AMOUNT
		,URVSBSSOL."SEQUENCE"		
		,ONFNCLIDOI.QTY_PO_DISTINCT
		,ONFNCLIDOI."TEXT"
		,ONFNCLIDOI.ENTRY_DATE
		,ONFNCLIDOI."G/L_ACCOUNT"
		,ONFNCLIDOI.LINE_ITEM
		,ONFNCLIDOI."G/L_ACCOUNT_1"
		,ONFNCLIDOI.POSTING_DATE
		,ONFNCLIDOI.USER_NAME
		,ONFNCLIDOI.FILE_NAME
		,ONFNCLIDOI.WEEK_MONTH_FILE_NAME
		,ONFNCLIDOI.OPEN_ALL_FILE_NAME
		,ONFNCLIDOI.YEAR_WEEK_FILE_NAME
		,ONFNCLIDOI.YEAR_MONTH_FILE_NAME
		,NOW() AS LOAD_DATE
		,NULL AS "TYPE"
		,NULL AS "1_CATE"
		,NULL AS "2_CATE"
		,NULL AS "3_CATE"
		,NULL AS "REASON TYPE"
		,NULL AS "PIC"
		,NULL AS REMARK
		,NULL AS "NEXT STEP"		
	FROM (SELECT
		ROW_NUMBER() OVER () AS NUM_LINE
		,ROW_NUMBER() OVER (PARTITION BY ONFNCLIDOI2."ASSIGNMENT" ORDER BY ONFNCLIDOI2."ASSIGNMENT" DESC, ONFNCLIDOI2.FILE_NAME) AS QTY_PO_DISTINCT
		,IFNULL(ONFNCLIDOI2.CUSTOMER,'') || IFNULL(ONFNCLIDOI2."ASSIGNMENT",'') || IFNULL(ONFNCLIDOI2.DOCUMENT_NUMBER,'') || IFNULL(REPLACE(ONFNCLIDOI2.AMOUNT_IN_LOCAL_CURRENCY,'.',','),'') || IFNULL(ONFNCLIDOI2.LINE_ITEM,'') AS "Key"	
		,(CASE WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE > 0
			THEN 'Over'
			ELSE 'In'
		END) AS "System Due date (In/Over)"	
		,(CASE WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE<=-46
			THEN '* Indue'
		 WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN -45 AND -38
			THEN '0~7 Indue'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN -37 AND -30
			THEN '8~15 Indue'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN -29 AND -15
			THEN '16~30 Indue'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN -14 AND 0
			THEN '31~45 Indue'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN 1 AND 7
			THEN '1 ~ 7 days'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN 8 AND 14
			THEN '8 ~ 14 days'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN 15 AND 31
			THEN '15 ~ 31 days'	
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN 32 AND 60
			THEN '32 ~ 60 days'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN 61 AND 90
			THEN '61 ~ 90 days'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN 91 AND 180
			THEN '91~180 days'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN 181 AND 360
			THEN '181~360 days'
			ELSE 'Over 360'
		END) AS "Range"
		,(CASE WHEN TO_DOUBLE(ONFNCLIDOI2.AMOUNT_IN_LOCAL_CURRENCY) > 0
			THEN '(+) AR'
			ELSE '(-) AR'
		END) AS "(+/-) AR"
		,ONFNCLIDOI2.CUSTOMER
		,REPLACE(ONFNCLIDOI2.AMOUNT_IN_LOCAL_CURRENCY,'.',',') AS AMOUNT_IN_LOCAL_CURRENCY
		,ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE
		,ONFNCLIDOI2.DOCUMENT_NUMBER
		,ONFNCLIDOI2.CLEARING_DOCUMENT
		,ONFNCLIDOI2.CLEARING_DATE
		,ONFNCLIDOI2."ASSIGNMENT"	
		,ONFNCLIDOI2."TEXT"
		,TO_DATE(ONFNCLIDOI2.ENTRY_DATE) AS ENTRY_DATE
		,ONFNCLIDOI2."G/L_ACCOUNT"
		,ONFNCLIDOI2.LINE_ITEM
		,ONFNCLIDOI2."G/L_ACCOUNT_1"
		,TO_DATE(ONFNCLIDOI2.POSTING_DATE) AS POSTING_DATE
		,ONFNCLIDOI2.USER_NAME
		,ONFNCLIDOI2.FILE_NAME
		,(CASE WHEN ONFNCLIDOI2.FILE_NAME LIKE '%WEEK%' 
			THEN 'WEEK'
		       WHEN ONFNCLIDOI2.FILE_NAME LIKE'%MONTH%'
		 	THEN 'MONTH'
		 	ELSE NULL
		 END) AS WEEK_MONTH_FILE_NAME
		,(CASE WHEN ONFNCLIDOI2.FILE_NAME LIKE '%ALL%' 
			THEN 'ALL'
		       WHEN ONFNCLIDOI2.FILE_NAME LIKE'%OPEN%'
		 	THEN 'OPEN'
		 	ELSE NULL
		 END) AS OPEN_ALL_FILE_NAME
		 
		 ,(SELECT DC.YYYYWW_NORMAL_CALENDAR FROM OW_MD.DIM_CALENDAR DC WHERE DC.YYYYMMDD = TO_DATE(SUBSTRING(ONFNCLIDOI2.FILE_NAME,25,8))) AS "YEAR_WEEK_FILE_NAME"
		 ,(SELECT DC.YYYYMM_NORMAL_CALENDAR FROM OW_MD.DIM_CALENDAR DC WHERE DC.YYYYMMDD = TO_DATE(SUBSTRING(ONFNCLIDOI2.FILE_NAME,25,8))) AS "YEAR_MONTH_FILE_NAME"
		,ONFNCLIDOI2.LOAD_DATE
	FROM OW_SEDA_S.ODS_NERP_FBL5N_CUSTOMER_LINE_ITEM_DISPLAY_OPEN_ITEMS_HIST ONFNCLIDOI2 
	WHERE UPPER(ONFNCLIDOI2.FILE_NAME) LIKE '%OPENITEM_WEEK%'
	-- TO REPROCESS THE COMPLETE BASE, COMMENT ON THE TEN LINES BELOW
	
	AND TO_DATE(SUBSTRING(ONFNCLIDOI2.FILE_NAME,25,8)) = (CASE WHEN DAYOFWEEK(CURRENT_DATE) = 6
									THEN ADD_DAYS(CURRENT_DATE,-1)
								WHEN DAYOFWEEK(CURRENT_DATE) = 2 
									THEN ADD_DAYS(CURRENT_DATE,-4)
								WHEN DAYOFWEEK(CURRENT_DATE) = 3 
									THEN ADD_DAYS(CURRENT_DATE,-5)
								WHEN DAYOFWEEK(CURRENT_DATE) = 4 
									THEN ADD_DAYS(CURRENT_DATE,-6)	
								ELSE NULL 
							     END)
	
		ORDER BY  ROW_NUMBER() OVER () ASC, ONFNCLIDOI2.CUSTOMER, ONFNCLIDOI2."ASSIGNMENT", ONFNCLIDOI2.DOCUMENT_NUMBER, REPLACE(ONFNCLIDOI2.AMOUNT_IN_LOCAL_CURRENCY,'.',',')
	) ONFNCLIDOI 
	LEFT JOIN (SELECT * FROM (SELECT --DISTINCT 
				 	ROW_NUMBER() OVER (PARTITION BY IFNULL(RVSBSSOL."SEQUENCE",RVSBSSOL.ORDER_ID) 
	         				ORDER BY IFNULL(RVSBSSOL."SEQUENCE",RVSBSSOL.ORDER_ID) DESC, RVSBSSOI.PRICE DESC) AS ROW_NUM
				 	,RVSBSSOL.ORDER_ID
				 	, RVSBSSOL.MARKETPLACE_ORDER_ID
				 	, RVSBSSOL.AFFILIATE_ID
				        , RVSBSSOL."SEQUENCE"
				        , TO_DATE(RVSBSSOL.CREATION_TIMESTAMP) AS CREATION_DATE
				        , RVSBSSOL.CANCELLATION_DATE
				        , RVSBSSOL.STATUS_DESCRIPTION
				        , RVSBSSOL.SALES_CHANNEL
				        , RVSBSSOL.AUTHORIZED_DATE
				        , RVSBSSOL.STATUS
					, RVSBSSOI.ITEM_INDEX,
					CASE WHEN RVSBSSOIC.REF_ID IS NULL 
						THEN RVSBSSOI.REF_ID
						ELSE RVSBSSOIC.REF_ID
					END AS REF_ID 
					, (RVSBSSOI.QUANTITY*IFNULL(RVSBSSOIC.QUANTITY,1)) AS QUANTITY
					, (RVSBSSOL.VALUE/100) AS "PO_AMOUNT"
					, URVSBSSOS."SELECTED_SLA"
	                  		, URVSBSSOS."WAREHOUSE_ID_GROUP"
	                  		, URVSBSSOS.ADDRESSTYPE
	                  		, URVSBSSOS.FRIENDLYNAME
	                  		, URVSBSSOS.STATE
	                  		, URVSBSSOS.CITY
			  		, CASE WHEN ( TRIM(UPPER(URVSBSSOS."SELECTED_SLA")) LIKE 'SHIP TO STORE %' 
	                                   		OR TRIM(UPPER(URVSBSSOS."SELECTED_SLA"))LIKE 'PONTO DE RETIRADA %'
	                                   		OR TRIM(UPPER(URVSBSSOS."SELECTED_SLA"))LIKE 'CLIQUE%'
	                             		    )
	                        		    AND OVSBSDESS.ID_STORE IS NOT NULL --PO.CHANNEL_TYPE = 'Store+'
	                        				THEN 'BOPIS + EA'
	                        	       WHEN ( TRIM(UPPER(URVSBSSOS."SELECTED_SLA")) LIKE 'SHIP TO STORE %'
	                                 		OR TRIM(UPPER(URVSBSSOS."SELECTED_SLA"))LIKE 'PONTO DE RETIRADA %'
	                                 		OR TRIM(UPPER(URVSBSSOS."SELECTED_SLA"))LIKE 'CLIQUE%'
	                        		    )
	                        				THEN 'BOPIS'
	                        	       WHEN OVSBSDESS.ID_STORE IS NOT NULL --( PO.CHANNEL_TYPE = 'Store+' )
	                        				THEN 'EA'
	                  					ELSE NULL 
	                  		END AS O2O_TYPE
					, OVSBSDESS.ID_STORE
					, CASE WHEN OVSBSDESS.ID_STORE IS NOT NULL THEN 'Store+' ELSE 'Shop' END AS CHANNEL_TYPE
					, OVSBSDESS.NAME AS NAME_STORE
					, RVSBSSOL.LAST_CHANGE
					--,RVSBSSOI.*
					FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER RVSBSSOL
					LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_ITEM RVSBSSOI 
					ON (RVSBSSOL.ORDER_ID = RVSBSSOI.ORDER_ID)
					LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_ITEM_COMPONENTS RVSBSSOIC  
					ON (RVSBSSOI.ORDER_ID = RVSBSSOIC.ORDER_ID AND RVSBSSOI.SKU_ID = RVSBSSOIC.SKU_ID)
					LEFT JOIN ( 	SELECT DISTINCT ORDER_ID
										, ITEM_INDEX
										, MAX(JSON_VALUE('[' || PICKUP_STORE_INFO || ']', '$.address.addressType')) AS ADDRESSTYPE
					                        		, MAX(JSON_VALUE('[' || PICKUP_STORE_INFO || ']', '$.friendlyName')) AS FRIENDLYNAME
					                        		, MAX(STATE) AS STATE
					                        		, MAX(CITY) AS CITY
					                        		, MAX(SELECTED_SLA) AS SELECTED_SLA
					                        		, STRING_AGG(WAREHOUSE_ID, ' | ') AS WAREHOUSE_ID_GROUP
							FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_SHIPPING rvsbssos
									GROUP BY ORDER_ID
	                           				,ITEM_INDEX
		   				  ) URVSBSSOS  ON RVSBSSOI.ORDER_ID = URVSBSSOS.ORDER_ID 
		   				              AND RVSBSSOI.ITEM_INDEX = URVSBSSOS.ITEM_INDEX
					LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SALES_ORDER RVSBSO  /* (SSG BR - ORDER) */ 	
					ON (RVSBSSOL.MARKETPLACE_ORDER_ID = RVSBSO.ORDER_ID)   				            
					LEFT JOIN U_PRJ_ECOM.ODS_VTEX_SSG_BR_SHOP_DATA_ENTITIES_STORES_SDS OVSBSDESS 
					ON ((CASE WHEN (CASE
								-- CD_STORE_INFORMATION
					       			WHEN RVSBSSOL.CD_STORE_INFORMATION IS NOT NULL 
									THEN RVSBSSOL.CD_STORE_INFORMATION
									ELSE RVSBSO.CD_STORE_INFORMATION
							  END) IS NOT NULL 
								THEN(CASE
									 -- CD_STORE_INFORMATION 
									 WHEN RVSBSSOL.CD_STORE_INFORMATION IS NOT NULL 
									 	THEN RVSBSSOL.CD_STORE_INFORMATION
										ELSE RVSBSO.CD_STORE_INFORMATION
								     END)
								ELSE(CASE
									  -- UTM_SOURCE
									  WHEN RVSBSSOL.UTM_SOURCE IS NOT NULL 
									  	THEN RVSBSSOL.UTM_SOURCE
										ELSE RVSBSO.UTM_SOURCE
								    END)
						END) = OVSBSDESS.ID_STORE)	
	        WHERE  1=1
	        AND RVSBSSOL.STATUS_DESCRIPTION IS NOT NULL
				)
	
	WHERE ROW_NUM = 1
	) URVSBSSOL
	ON (ONFNCLIDOI."ASSIGNMENT" = URVSBSSOL."SEQUENCE" OR ONFNCLIDOI."ASSIGNMENT" = URVSBSSOL.ORDER_ID)
		LEFT JOIN OW_MD.DIM_PRODUCT DP ON (URVSBSSOL.REF_ID = DP.SKU)
		LEFT JOIN OW_MD.MAP_AR_MONTH_KEY_GL_ACCOUNT MKGA ON (ONFNCLIDOI."G/L_ACCOUNT" = MKGA.GL_ACCT)
		LEFT JOIN OW_MD.MAP_AR_MONTH_CUSTOMER MAC ON (ONFNCLIDOI.CUSTOMER = MAC.CUSTOMER_CODE)
		;
--Truncar Tabela com os dados no nivel granular mais baixo para tratamento de dados 
TRUNCATE TABLE OW_LAO.TMP_D2C_AR_CREATION_X_ALLITEM_WEEK;
--Inserir os dados no nivel granular mais baixo na tabela de temporária
INSERT INTO  OW_LAO.TMP_D2C_AR_CREATION_X_ALLITEM_WEEK
		SELECT   ONFNCLIDOI."Key"	
		,MKGA.SHORT_TEXT_ENGLISH AS GL_ACCOUNT_ENGLISH
		,ONFNCLIDOI."System Due date (In/Over)"	
		,ONFNCLIDOI."Range"
		,DP.SEDA_BU_ESTORE AS DIMPROD_PRODUCT_GROUP 
		,DP.SEDA_DIVISION_ESTORE AS DIMPROD_DIVISION 
		,ONFNCLIDOI."(+/-) AR"
		,MAC.CUSTOMER_NAME_SUMMARY AS "Customer Group (eStore/MKP)"
		,MAC.CUSTOMER_NAME_DETAIL AS CUSTOMER_NAME
		,ONFNCLIDOI.CUSTOMER
		,ONFNCLIDOI.AMOUNT_IN_LOCAL_CURRENCY
		,ONFNCLIDOI.ARREARS_BY_NET_DUE_DATE
		,ONFNCLIDOI.DOCUMENT_NUMBER
		,ONFNCLIDOI.CLEARING_DOCUMENT
		,ONFNCLIDOI.CLEARING_DATE
		,ONFNCLIDOI."ASSIGNMENT"
		,URVSBSSOL.ORDER_ID
		,URVSBSSOL.PO_AMOUNT
		,URVSBSSOL."SEQUENCE"		
		,ONFNCLIDOI.QTY_PO_DISTINCT
		,ONFNCLIDOI."TEXT"
		,ONFNCLIDOI.ENTRY_DATE
		,ONFNCLIDOI."G/L_ACCOUNT"
		,ONFNCLIDOI.LINE_ITEM
		,ONFNCLIDOI."G/L_ACCOUNT_1"
		,ONFNCLIDOI.POSTING_DATE
		,ONFNCLIDOI.USER_NAME
		,ONFNCLIDOI.FILE_NAME
		,ONFNCLIDOI.WEEK_MONTH_FILE_NAME
		,ONFNCLIDOI.OPEN_ALL_FILE_NAME
		,ONFNCLIDOI.YEAR_WEEK_FILE_NAME
		,ONFNCLIDOI.YEAR_MONTH_FILE_NAME
		,NOW() AS LOAD_DATE
		,NULL AS "TYPE"
		,NULL AS "1_CATE"
		,NULL AS "2_CATE"
		,NULL AS "3_CATE"
		,NULL AS "REASON TYPE"
		,NULL AS "PIC"
		,NULL AS REMARK
		,NULL AS "NEXT STEP"		
	FROM (SELECT
		ROW_NUMBER() OVER () AS NUM_LINE
		,ROW_NUMBER() OVER (PARTITION BY ONFNCLIDOI2."ASSIGNMENT" ORDER BY ONFNCLIDOI2."ASSIGNMENT" DESC, ONFNCLIDOI2.FILE_NAME) AS QTY_PO_DISTINCT
		,IFNULL(ONFNCLIDOI2.CUSTOMER,'') || IFNULL(ONFNCLIDOI2."ASSIGNMENT",'') || IFNULL(ONFNCLIDOI2.DOCUMENT_NUMBER,'') || IFNULL(REPLACE(ONFNCLIDOI2.AMOUNT_IN_LOCAL_CURRENCY,'.',','),'') || IFNULL(ONFNCLIDOI2.LINE_ITEM,'') AS "Key"	
		,(CASE WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE > 0
			THEN 'Over'
			ELSE 'In'
		END) AS "System Due date (In/Over)"	
		,(CASE WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE<=-46
			THEN '* Indue'
		 WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN -45 AND -38
			THEN '0~7 Indue'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN -37 AND -30
			THEN '8~15 Indue'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN -29 AND -15
			THEN '16~30 Indue'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN -14 AND 0
			THEN '31~45 Indue'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN 1 AND 7
			THEN '1 ~ 7 days'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN 8 AND 14
			THEN '8 ~ 14 days'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN 15 AND 31
			THEN '15 ~ 31 days'	
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN 32 AND 60
			THEN '32 ~ 60 days'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN 61 AND 90
			THEN '61 ~ 90 days'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN 91 AND 180
			THEN '91~180 days'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN 181 AND 360
			THEN '181~360 days'
			ELSE 'Over 360'
		END) AS "Range"
		,(CASE WHEN TO_DOUBLE(ONFNCLIDOI2.AMOUNT_IN_LOCAL_CURRENCY) > 0
			THEN '(+) AR'
			ELSE '(-) AR'
		END) AS "(+/-) AR"
		,ONFNCLIDOI2.CUSTOMER
		,REPLACE(ONFNCLIDOI2.AMOUNT_IN_LOCAL_CURRENCY,'.',',') AS AMOUNT_IN_LOCAL_CURRENCY
		,ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE
		,ONFNCLIDOI2.DOCUMENT_NUMBER
		,ONFNCLIDOI2.CLEARING_DOCUMENT
		,ONFNCLIDOI2.CLEARING_DATE
		,ONFNCLIDOI2."ASSIGNMENT"	
		,ONFNCLIDOI2."TEXT"
		,TO_DATE(ONFNCLIDOI2.ENTRY_DATE) AS ENTRY_DATE
		,ONFNCLIDOI2."G/L_ACCOUNT"
		,ONFNCLIDOI2.LINE_ITEM
		,ONFNCLIDOI2."G/L_ACCOUNT_1"
		,TO_DATE(ONFNCLIDOI2.POSTING_DATE) AS POSTING_DATE
		,ONFNCLIDOI2.USER_NAME
		,ONFNCLIDOI2.FILE_NAME
		,(CASE WHEN ONFNCLIDOI2.FILE_NAME LIKE '%WEEK%' 
			THEN 'WEEK'
		       WHEN ONFNCLIDOI2.FILE_NAME LIKE'%MONTH%'
		 	THEN 'MONTH'
		 	ELSE NULL
		 END) AS WEEK_MONTH_FILE_NAME
		,(CASE WHEN ONFNCLIDOI2.FILE_NAME LIKE '%ALL%' 
			THEN 'ALL'
		       WHEN ONFNCLIDOI2.FILE_NAME LIKE'%OPEN%'
		 	THEN 'OPEN'
		 	ELSE NULL
		 END) AS OPEN_ALL_FILE_NAME
		 
		 ,(SELECT DC.YYYYWW_NORMAL_CALENDAR FROM OW_MD.DIM_CALENDAR DC WHERE DC.YYYYMMDD = TO_DATE(SUBSTRING(ONFNCLIDOI2.FILE_NAME,24,8))) AS "YEAR_WEEK_FILE_NAME"
		 ,(SELECT DC.YYYYMM_NORMAL_CALENDAR FROM OW_MD.DIM_CALENDAR DC WHERE DC.YYYYMMDD = TO_DATE(SUBSTRING(ONFNCLIDOI2.FILE_NAME,24,8))) AS "YEAR_MONTH_FILE_NAME"
		,ONFNCLIDOI2.LOAD_DATE
	FROM OW_SEDA_S.ODS_NERP_FBL5N_CUSTOMER_LINE_ITEM_DISPLAY_OPEN_ITEMS_HIST ONFNCLIDOI2 
	WHERE UPPER(ONFNCLIDOI2.FILE_NAME) LIKE '%ALLITEM_WEEK%'
	-- TO REPROCESS THE COMPLETE BASE, COMMENT ON THE TEN LINES BELOW
	
	AND TO_DATE(SUBSTRING(ONFNCLIDOI2.FILE_NAME,25,8)) = (CASE WHEN DAYOFWEEK(CURRENT_DATE) = 6
									THEN ADD_DAYS(CURRENT_DATE,-1)
								WHEN DAYOFWEEK(CURRENT_DATE) = 2 
									THEN ADD_DAYS(CURRENT_DATE,-4)
								WHEN DAYOFWEEK(CURRENT_DATE) = 3 
									THEN ADD_DAYS(CURRENT_DATE,-5)
								WHEN DAYOFWEEK(CURRENT_DATE) = 4 
									THEN ADD_DAYS(CURRENT_DATE,-6)	
								ELSE NULL 
							     END)
	
		ORDER BY  ROW_NUMBER() OVER () ASC, ONFNCLIDOI2.CUSTOMER, ONFNCLIDOI2."ASSIGNMENT", ONFNCLIDOI2.DOCUMENT_NUMBER, REPLACE(ONFNCLIDOI2.AMOUNT_IN_LOCAL_CURRENCY,'.',',')
	) ONFNCLIDOI 
	LEFT JOIN (SELECT * FROM (SELECT --DISTINCT 
				 	ROW_NUMBER() OVER (PARTITION BY IFNULL(RVSBSSOL."SEQUENCE",RVSBSSOL.ORDER_ID) 
	         				ORDER BY IFNULL(RVSBSSOL."SEQUENCE",RVSBSSOL.ORDER_ID) DESC, RVSBSSOI.PRICE DESC) AS ROW_NUM
				 	,RVSBSSOL.ORDER_ID
				 	, RVSBSSOL.MARKETPLACE_ORDER_ID
				 	, RVSBSSOL.AFFILIATE_ID
				        , RVSBSSOL."SEQUENCE"
				        , TO_DATE(RVSBSSOL.CREATION_TIMESTAMP) AS CREATION_DATE
				        , RVSBSSOL.CANCELLATION_DATE
				        , RVSBSSOL.STATUS_DESCRIPTION
				        , RVSBSSOL.SALES_CHANNEL
				        , RVSBSSOL.AUTHORIZED_DATE
				        , RVSBSSOL.STATUS
					, RVSBSSOI.ITEM_INDEX,
					CASE WHEN RVSBSSOIC.REF_ID IS NULL 
						THEN RVSBSSOI.REF_ID
						ELSE RVSBSSOIC.REF_ID
					END AS REF_ID 
					, (RVSBSSOI.QUANTITY*IFNULL(RVSBSSOIC.QUANTITY,1)) AS QUANTITY
					, (RVSBSSOL.VALUE/100) AS "PO_AMOUNT"
					, URVSBSSOS."SELECTED_SLA"
	                  		, URVSBSSOS."WAREHOUSE_ID_GROUP"
	                  		, URVSBSSOS.ADDRESSTYPE
	                  		, URVSBSSOS.FRIENDLYNAME
	                  		, URVSBSSOS.STATE
	                  		, URVSBSSOS.CITY
			  		, CASE WHEN ( TRIM(UPPER(URVSBSSOS."SELECTED_SLA")) LIKE 'SHIP TO STORE %' 
	                                   		OR TRIM(UPPER(URVSBSSOS."SELECTED_SLA"))LIKE 'PONTO DE RETIRADA %'
	                                   		OR TRIM(UPPER(URVSBSSOS."SELECTED_SLA"))LIKE 'CLIQUE%'
	                             		    )
	                        		    AND OVSBSDESS.ID_STORE IS NOT NULL --PO.CHANNEL_TYPE = 'Store+'
	                        				THEN 'BOPIS + EA'
	                        	       WHEN ( TRIM(UPPER(URVSBSSOS."SELECTED_SLA")) LIKE 'SHIP TO STORE %'
	                                 		OR TRIM(UPPER(URVSBSSOS."SELECTED_SLA"))LIKE 'PONTO DE RETIRADA %'
	                                 		OR TRIM(UPPER(URVSBSSOS."SELECTED_SLA"))LIKE 'CLIQUE%'
	                        		    )
	                        				THEN 'BOPIS'
	                        	       WHEN OVSBSDESS.ID_STORE IS NOT NULL --( PO.CHANNEL_TYPE = 'Store+' )
	                        				THEN 'EA'
	                  					ELSE NULL 
	                  		END AS O2O_TYPE
					, OVSBSDESS.ID_STORE
					, CASE WHEN OVSBSDESS.ID_STORE IS NOT NULL THEN 'Store+' ELSE 'Shop' END AS CHANNEL_TYPE
					, OVSBSDESS.NAME AS NAME_STORE
					, RVSBSSOL.LAST_CHANGE
					--,RVSBSSOI.*
					FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER RVSBSSOL
					LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_ITEM RVSBSSOI 
					ON (RVSBSSOL.ORDER_ID = RVSBSSOI.ORDER_ID)
					LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_ITEM_COMPONENTS RVSBSSOIC  
					ON (RVSBSSOI.ORDER_ID = RVSBSSOIC.ORDER_ID AND RVSBSSOI.SKU_ID = RVSBSSOIC.SKU_ID)
					LEFT JOIN ( 	SELECT DISTINCT ORDER_ID
										, ITEM_INDEX
										, MAX(JSON_VALUE('[' || PICKUP_STORE_INFO || ']', '$.address.addressType')) AS ADDRESSTYPE
					                        		, MAX(JSON_VALUE('[' || PICKUP_STORE_INFO || ']', '$.friendlyName')) AS FRIENDLYNAME
					                        		, MAX(STATE) AS STATE
					                        		, MAX(CITY) AS CITY
					                        		, MAX(SELECTED_SLA) AS SELECTED_SLA
					                        		, STRING_AGG(WAREHOUSE_ID, ' | ') AS WAREHOUSE_ID_GROUP
							FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_SHIPPING rvsbssos
									GROUP BY ORDER_ID
	                           				,ITEM_INDEX
		   				  ) URVSBSSOS  ON RVSBSSOI.ORDER_ID = URVSBSSOS.ORDER_ID 
		   				              AND RVSBSSOI.ITEM_INDEX = URVSBSSOS.ITEM_INDEX
					LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SALES_ORDER RVSBSO  /* (SSG BR - ORDER) */ 	
					ON (RVSBSSOL.MARKETPLACE_ORDER_ID = RVSBSO.ORDER_ID)   				            
					LEFT JOIN U_PRJ_ECOM.ODS_VTEX_SSG_BR_SHOP_DATA_ENTITIES_STORES_SDS OVSBSDESS 
					ON ((CASE WHEN (CASE
								-- CD_STORE_INFORMATION
					       			WHEN RVSBSSOL.CD_STORE_INFORMATION IS NOT NULL 
									THEN RVSBSSOL.CD_STORE_INFORMATION
									ELSE RVSBSO.CD_STORE_INFORMATION
							  END) IS NOT NULL 
								THEN(CASE
									 -- CD_STORE_INFORMATION 
									 WHEN RVSBSSOL.CD_STORE_INFORMATION IS NOT NULL 
									 	THEN RVSBSSOL.CD_STORE_INFORMATION
										ELSE RVSBSO.CD_STORE_INFORMATION
								     END)
								ELSE(CASE
									  -- UTM_SOURCE
									  WHEN RVSBSSOL.UTM_SOURCE IS NOT NULL 
									  	THEN RVSBSSOL.UTM_SOURCE
										ELSE RVSBSO.UTM_SOURCE
								    END)
						END) = OVSBSDESS.ID_STORE)	
	        WHERE  1=1
	        AND RVSBSSOL.STATUS_DESCRIPTION IS NOT NULL
				)
	
	WHERE ROW_NUM = 1
	) URVSBSSOL
	ON (ONFNCLIDOI."ASSIGNMENT" = URVSBSSOL."SEQUENCE" OR ONFNCLIDOI."ASSIGNMENT" = URVSBSSOL.ORDER_ID)
		LEFT JOIN OW_MD.DIM_PRODUCT DP ON (URVSBSSOL.REF_ID = DP.SKU)
		LEFT JOIN OW_MD.MAP_AR_MONTH_KEY_GL_ACCOUNT MKGA ON (ONFNCLIDOI."G/L_ACCOUNT" = MKGA.GL_ACCT)
		LEFT JOIN OW_MD.MAP_AR_MONTH_CUSTOMER MAC ON (ONFNCLIDOI.CUSTOMER = MAC.CUSTOMER_CODE)
	;
-- UPDATE OPEN MONTH 
UPDATE OW_LAO.TMP_D2C_AR_CREATION_X_OPEN_OPENITEM_MONTH AS TDACXOOM 
	SET TDACXOOM ."TYPE"			=	(CASE WHEN /*MTFASC."TYPE"*/MTFASC."KEY" IS NULL 
								THEN 'Process Delay'
								ELSE MTFASC."TYPE"
							END)
		,TDACXOOM ."1_CATE"		=	(CASE WHEN /*MTFASC."1_CATE"*/MTFASC."KEY" IS NULL
								THEN 'Others (In analysis)'
								ELSE MTFASC."1_CATE"
							END)
		,TDACXOOM ."2_CATE"		=	(CASE WHEN /*MTFASC."2_CATE"*/MTFASC."KEY" IS NULL
								THEN 'In analysis (1st and 2nd analysis)'
								ELSE MTFASC."2_CATE"
							END) 
		,TDACXOOM ."3_CATE"		=	MTFASC."3_CATE"
		,TDACXOOM ."REASON TYPE"	=	(CASE WHEN /*MTFASC."REASON TYPE"*/MTFASC."KEY" IS NULL
								THEN 'System (Manual, missing I/F)'
								ELSE MTFASC."REASON TYPE"
							END)
		,TDACXOOM ."PIC"			=	(CASE WHEN /*MTFASC.PIC*/MTFASC."KEY" IS NULL
								THEN 'OST'
								ELSE MTFASC.PIC
							END)
		,TDACXOOM ."REMARK"		=	MTFASC.REMARK
		,TDACXOOM ."NEXT STEP"		=	MTFASC."NEXT STEP"
FROM OW_LAO.TMP_D2C_AR_CREATION_X_OPEN_OPENITEM_MONTH AS TDACXOOM	   
LEFT JOIN OW_MD.MAP_AR_MONTH_TO_FROM_AR_SCM_CLASSIFICATION MTFASC ON (TDACXOOM."Key" = MTFASC."KEY"
	AND TDACXOOM.YEAR_MONTH_FILE_NAME = YEAR(TO_DATE(MTFASC.PERIOD))||
		(CASE WHEN MONTH(TO_DATE(MTFASC.PERIOD)) BETWEEN 1 AND 9
			THEN '0'
			ELSE NULL
		END)||
		MONTH(TO_DATE(TO_DATE(MTFASC.PERIOD))))
;
-- UPDATE OPEN WEEK 
UPDATE OW_LAO.TMP_D2C_AR_CREATION_X_OPEN_OPENITEM_WEEK AS TDACXOOM 
	SET TDACXOOM ."TYPE"			=	(CASE WHEN /*MTFASC."TYPE"*/MTFASC."KEY" IS NULL 
								THEN 'Process Delay'
								ELSE MTFASC."TYPE"
							END)
		,TDACXOOM ."1_CATE"		=	(CASE WHEN /*MTFASC."1_CATE"*/MTFASC."KEY" IS NULL
								THEN 'Others (In analysis)'
								ELSE MTFASC."1_CATE"
							END)
		,TDACXOOM ."2_CATE"		=	(CASE WHEN /*MTFASC."2_CATE"*/MTFASC."KEY" IS NULL
								THEN 'In analysis (1st and 2nd analysis)'
								ELSE MTFASC."2_CATE"
							END) 
		,TDACXOOM ."3_CATE"		=	MTFASC."3_CATE"
		,TDACXOOM ."REASON TYPE"	=	(CASE WHEN /*MTFASC."REASON TYPE"*/MTFASC."KEY" IS NULL
								THEN 'System (Manual, missing I/F)'
								ELSE MTFASC."REASON TYPE"
							END)
		,TDACXOOM ."PIC"			=	(CASE WHEN /*MTFASC.PIC*/MTFASC."KEY" IS NULL
								THEN 'OST'
								ELSE MTFASC.PIC
							END)
		,TDACXOOM ."REMARK"		=	MTFASC.REMARK
		,TDACXOOM ."NEXT STEP"		=	MTFASC."NEXT STEP"
FROM OW_LAO.TMP_D2C_AR_CREATION_X_OPEN_OPENITEM_WEEK AS TDACXOOM	   
LEFT JOIN OW_MD.MAP_AR_WEEK_TO_FROM_AR_SCM_CLASSIFICATION MTFASC 
ON (TDACXOOM."Key" = MTFASC."KEY" AND TDACXOOM.YEAR_WEEK_FILE_NAME = MTFASC.PERIOD)
		;
--DELETE Records at FT with same Year Month in TMP MONTHS
DELETE FROM OW_LAO.FT_D2C_AR_CREATION_X_OPEN FT
WHERE FT.YEAR_MONTH_FILE_NAME IN (SELECT DISTINCT YEAR_MONTH_FILE_NAME FROM 
								 (
								 SELECT DISTINCT TDACXAM.YEAR_MONTH_FILE_NAME 
								 FROM OW_LAO.TMP_D2C_AR_CREATION_X_ALLITEM_MONTH TDACXAM
									UNION ALL 
								 SELECT	TDACXOOM.YEAR_MONTH_FILE_NAME
								 FROM OW_LAO.TMP_D2C_AR_CREATION_X_OPEN_OPENITEM_MONTH TDACXOOM
								 )					
								);
--DELETE Records at FT with same Year Month in TMP WEEKS
DELETE FROM OW_LAO.FT_D2C_AR_CREATION_X_OPEN FT
WHERE FT.YEAR_WEEK_FILE_NAME IN (SELECT DISTINCT YEAR_WEEK_FILE_NAME FROM 
								 (
								 SELECT DISTINCT TDACXAW.YEAR_WEEK_FILE_NAME 
								 FROM OW_LAO.TMP_D2C_AR_CREATION_X_ALLITEM_WEEK TDACXAW
									UNION ALL 
								 SELECT	TDACXOOW.YEAR_WEEK_FILE_NAME
								 FROM OW_LAO.TMP_D2C_AR_CREATION_X_OPEN_OPENITEM_WEEK TDACXOOW
								 )					
								);							
INSERT	INTO OW_LAO.FT_D2C_AR_CREATION_X_OPEN
SELECT TDACXAM.*
FROM OW_LAO.TMP_D2C_AR_CREATION_X_ALLITEM_MONTH TDACXAM
	UNION ALL
SELECT TACXAW.*
FROM OW_LAO.TMP_D2C_AR_CREATION_X_ALLITEM_WEEK TACXAW
	UNION ALL 
SELECT	TDACXOOM.*
FROM OW_LAO.TMP_D2C_AR_CREATION_X_OPEN_OPENITEM_MONTH TDACXOOM
	UNION ALL
SELECT	TDACXOOW.*
FROM OW_LAO.TMP_D2C_AR_CREATION_X_OPEN_OPENITEM_WEEK TDACXOOW
;
TRUNCATE TABLE OW_LAO.TMP_D2C_AR_CREATION_X_ALLITEM_MONTH;
TRUNCATE TABLE OW_LAO.TMP_D2C_AR_CREATION_X_ALLITEM_WEEK;
TRUNCATE TABLE OW_LAO.TMP_D2C_AR_CREATION_X_OPEN_OPENITEM_MONTH;
TRUNCATE TABLE OW_LAO.TMP_D2C_AR_CREATION_X_OPEN_OPENITEM_WEEK;
END