/***********************************************************************************************
CREATED BY :Luciano Mariani
CREATION DATE : 2023-08-01
CALL OW_LAO.PROC_D2C_NERP_WEEKLY_SALES_KPI
***********************************************************************************************/
CREATE PROCEDURE OW_LAO.PROC_D2C_NERP_WEEKLY_SALES_KPI LANGUAGE SQLSCRIPT
AS
BEGIN
	-- TMP_PREMIUM_MODELS_WEEKLY_SALES
	IF EXISTS( SELECT TABLE_NAME FROM SYS.TABLES WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TMP_PREMIUM_MODELS_WEEKLY_SALES') THEN
		DROP TABLE OW_LAO.TMP_PREMIUM_MODELS_WEEKLY_SALES;
	END IF;
	CREATE COLUMN TABLE OW_LAO.TMP_PREMIUM_MODELS_WEEKLY_SALES AS (
		SELECT DISTINCT TRIM(ITEM) AS MATERIAL
		FROM OW_LAO.ODS_GSCM_PREMIUM_MODELS
	);
	--APAGA TABELA OW_LAO.TMP_GSCM_FILES
	IF EXISTS( SELECT TABLE_NAME FROM SYS.TABLES WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TMP_GSCM_FILES' ) THEN
		DROP TABLE OW_LAO.TMP_GSCM_FILES;
	END IF;
	CREATE COLUMN TABLE OW_LAO.TMP_GSCM_FILES AS (
		-- VIEW GSCM
		WITH GSCM AS(
			SELECT 'CE' AS DIVISION
				 , CAST(CONCAT( LEFT(RIGHT(FILE_NAME,42),4),  REPLACE(LEFT(MEASURE, 5), '/','')) AS DATE) AS DATE_REF
				 , AP2 AS SUBSIDIARY
				 , "Item" AS SKU
				 , CAST(VALUE AS INTEGER) AS QTY
				 , LEFT(RIGHT(FILE_NAME,42),6) AS PERIODO_SCM
				 , CAST(LEFT(RIGHT(FILE_NAME,17),8) AS DATE) AS FILE_DATE
			FROM "OW_LAO"."RAW_GSCM_CE_SELL_OUT"
			WHERE MEASURE LIKE '%/%' -- (NÃO SÃO TOTALIZADORES)
				AND OW_LAO.ISNUMERIC(CONCAT( LEFT(RIGHT(FILE_NAME,42),4),  REPLACE(LEFT(MEASURE, 5), '/',''))) = 1 -- tratA erro DATA
				AND OW_LAO.ISNUMERIC(LEFT(RIGHT(FILE_NAME,17),8)) = 1 -- trata erro DATA
			
			UNION ALL
			SELECT 'MX' AS DIVISION
				 , CAST(CONCAT( LEFT(RIGHT(FILE_NAME,42),4),  REPLACE(LEFT(MEASURE, 5), '/','')) AS DATE) AS DATE_REF
				 , AP2 AS SUBSIDIARY
				 , "Item" AS SKU
				 , CAST(VALUE AS INTEGER) AS QTY
				 , LEFT(RIGHT(FILE_NAME,42),6) AS PERIODO_SCM
				 , CAST(LEFT(RIGHT(FILE_NAME,17),8) AS DATE) AS FILE_DATE
			FROM "OW_LAO"."RAW_GSCM_MX_SELL_OUT"
			WHERE MEASURE LIKE '%/%' -- (NÃO SÃO TOTALIZADORES)
				--AND LEFT(RIGHT(FILE_NAME, 17), 8) != 'y Sell-o' -- evita arquivo com nome errado (l.sposito 2023-11-02)
				AND OW_LAO.ISNUMERIC(CONCAT( LEFT(RIGHT(FILE_NAME,42),4),  REPLACE(LEFT(MEASURE, 5), '/',''))) = 1 -- tratA erro DATA
				AND OW_LAO.ISNUMERIC(LEFT(RIGHT(FILE_NAME,17),8)) = 1 -- trata erro DATA	
		)
		SELECT G.SUBSIDIARY
			 , G.SKU
			 , G.DATE_REF
			 , SUM(G.QTY) AS QTY
		FROM GSCM G
			INNER JOIN ( -- GET LAST FILE
				SELECT SUBSIDIARY
					 , PERIODO_SCM
					 , MAX(FILE_DATE) AS FILE_DATE
				FROM GSCM
				GROUP BY SUBSIDIARY
					   , PERIODO_SCM
			) L -- LAST FILE
			ON L.SUBSIDIARY = G.SUBSIDIARY
			   AND L.PERIODO_SCM = G.PERIODO_SCM
			   AND L.FILE_DATE = G.FILE_DATE
		GROUP BY G.SUBSIDIARY
			   , G.SKU
			   , G.DATE_REF
	);
	-- APAGA TATBELA OW_LAO.TF_D2C_NERP_WEEKLY_SALES_KPI
	--IF EXISTS( SELECT TABLE_NAME FROM SYS.TABLES WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TF_D2C_NERP_WEEKLY_SALES_KPI' ) THEN
	--	DROP TABLE OW_LAO.TF_D2C_NERP_WEEKLY_SALES_KPI;
	--END IF;
	
	DELETE FROM OW_LAO.TF_D2C_NERP_WEEKLY_SALES_KPI
	WHERE DATE_REF >= ADD_DAYS(CURRENT_TIMESTAMP, -60) 
		--AND "SOURCE" NOT IN ('TAR','STR','MP','GSCM','FCST')
	;
	--CRIA NOVA TABELA TF_D2C_NERP_WEEKLY_SALES_KPI
	--CREATE COLUMN TABLE OW_LAO.TF_D2C_NERP_WEEKLY_SALES_KPI AS (
		/*********************************************
		TF_D2C_NERP_SALES
		*********************************************/	
	INSERT INTO OW_LAO.TF_D2C_NERP_WEEKLY_SALES_KPI
		SELECT
			 "SOURCE"
			,DATE_REF
			,YYYYWW
			,YYYYMM
			,YYYYQQ
			,SUBSIDIARY
			,CHANNEL
			,SUB_CHANNEL
			,SALES_CHANNEL_ATTR_1
			,SALES_CHANNEL_ATTR_2
			,CHANNEL_TYPE
			,SKU
			,PDROD_DIVISION
			,PDROD_PRODUCT_GROUP
			,PDROD_PRODUCT
			,PROD_ATTB_1
			,SEDA_BU_ESTORE
			,SEDA_CATEGORY_ESTORE
			,SEDA_DESC_ESTORE
			,SEDA_DIVISION_ESTORE
			,SEDA_FAMILY_ESTORE
			,STATUS_PO --,CASE WHEN "SOURCE" = 'PO' THEN STATUS_PO ELSE NULL END AS STATUS_PO
			-- AFFILIATE
			,AFFILIATE_CHANNEL
			,AFFILIATE_SUB_CHANNEL
			,AFFILIATE_PARTNER_LEVEL
			,GLOBAL_CHANNEL
			--,BIZ_TYPE
			,AUDIENCE_TYPE
			,COUNTRY
			,CURRENCY
			,MODEL_TYPE
			,CORPORATENAME
			,SUM(QTY) AS QTY
			,SUM(AMOUNT_LOCAL) AS AMOUNT_LOCAL
			,SUM(AMOUNT_USD) AS AMOUNT_USD
			,CURRENT_TIMESTAMP AS KPI_LAST_UPDATE --,KPI_LAST_UPDATE
		FROM OW_LAO.TF_D2C_NERP_SALES
		WHERE 1=1
			AND DATE_REF >= ADD_DAYS(CURRENT_TIMESTAMP, -60) 
			AND ( STATUS_PO IS NULL
				  OR STATUS_PO NOT IN('cancel','canceled')
			)
		GROUP BY
			 "SOURCE"
			,DATE_REF
			,YYYYWW
			,YYYYMM
			,YYYYQQ
			,SUBSIDIARY
			,CHANNEL
			,SUB_CHANNEL
			,SALES_CHANNEL_ATTR_1
			,SALES_CHANNEL_ATTR_2
			,CHANNEL_TYPE
			,SKU
			,PDROD_DIVISION
			,PDROD_PRODUCT_GROUP
			,PDROD_PRODUCT
			,PROD_ATTB_1
			,SEDA_BU_ESTORE
			,SEDA_CATEGORY_ESTORE
			,SEDA_DESC_ESTORE
			,SEDA_DIVISION_ESTORE
			,SEDA_FAMILY_ESTORE
			,STATUS_PO --CASE WHEN "SOURCE" = 'PO' THEN STATUS_PO ELSE NULL END --AS STATUS_PO
			,AFFILIATE_CHANNEL
			,AFFILIATE_SUB_CHANNEL
			,AFFILIATE_PARTNER_LEVEL
			,GLOBAL_CHANNEL
			--,BIZ_TYPE
			,AUDIENCE_TYPE
			,COUNTRY
			,CURRENCY
			,MODEL_TYPE
			,CORPORATENAME
			--,IS_TRADE_IN
			
		/*********************************************
		TARGET
		*********************************************/	
		UNION ALL
		SELECT
			 'TAR' AS "SOURCE"
			, TO_DATE(ZR."YEAR" || CASE WHEN ZR."MONTH" BETWEEN 1 AND 9 THEN '-0' ||ZR."MONTH" ELSE '-' ||ZR."MONTH" END  || '-01') AS DATE_REF
			, CL.YYYYWW AS YYYYWW
			, CL.YYYYMM AS YYYYMM
			, CL.YYYYQQ AS YYYYQQ
			, ZR.COMPANY_CODE_DESC AS SUBSIDIARY -- SB.SUBSIDIARY
			, NULL AS CHANNEL
			, NULL AS SUB_CHANNEL
			, NULL AS SALES_CHANNEL_ATTR_1
			, NULL AS SALES_CHANNEL_ATTR_2
			, NULL AS CHANNEL_TYPE
			, ZR.MATERIAL AS SKU
			, PD."DIVISION" AS PDROD_DIVISION
			, PD.PRODUCT_GROUP_1 AS PDROD_PRODUCT_GROUP
			, PD.PRODUCT_1 AS PDROD_PRODUCT
			, PD.ATTB01 AS PROD_ATTB_1
			, PD.SEDA_BU_ESTORE
			, PD.SEDA_CATEGORY_ESTORE
			, PD.SEDA_DESC_ESTORE
			, PD.SEDA_DIVISION_ESTORE
			, PD.SEDA_FAMILY_ESTORE
			, NULL AS STATUS_PO
			, NULL AS AFFILIATE_CHANNEL
			, NULL AS AFFILIATE_SUB_CHANNEL
			, NULL AS AFFILIATE_PARTNER_LEVEL
			, NULL AS GLOBAL_CHANNEL
			, NULL AS AUDIENCE_TYPE
			, NULL AS COUNTRY --SB.COUNTRY
			, ZR.CURR AS CURRENCY
			, CASE WHEN PR.MATERIAL IS NOT NULL THEN 'PREMIUM MODEL' ELSE 'NORMAL MODEL' END AS MODEL_TYPE
			, NULL AS CORPORATENAME
			, SUM(ZR.QTY)
			, SUM(CAST( ZR.AMOUNT AS DECIMAL(18,2) )) AS AMOUNT_LOCAL
			, SUM(CAST( ZR.AMOUNT_USD AS DECIMAL(18,2) )) AS AMOUNT_USD
			, CURRENT_TIMESTAMP AS KPI_LAST_UPDATE --,KPI_LAST_UPDATE
		FROM OW_LAO.VIEW_NERP_ZRCOS43400_TARGET ZR
			LEFT JOIN OW_MD.DIM_PRODUCT PD ON PD.SKU = ZR.MATERIAL
			LEFT JOIN OW_MD.DIM_CALENDAR CL ON CL.YYYYMMDD = TO_DATE(ZR."YEAR" || CASE WHEN ZR."MONTH" BETWEEN 1 AND 9 THEN '-0' ||ZR."MONTH" ELSE '-' ||ZR."MONTH" END  || '-01')
			LEFT JOIN OW_LAO.TMP_PREMIUM_MODELS_WEEKLY_SALES PR ON PR.MATERIAL = ZR.MATERIAL
		WHERE 1 = 1
			AND TO_DATE(ZR."YEAR" || CASE WHEN ZR."MONTH" BETWEEN 1 AND 9 THEN '-0' ||ZR."MONTH" ELSE '-' ||ZR."MONTH" END  || '-01') >= ADD_DAYS(CURRENT_TIMESTAMP, -60) 		
		GROUP BY
			 TO_DATE(ZR."YEAR" || CASE WHEN ZR."MONTH" BETWEEN 1 AND 9 THEN '-0' ||ZR."MONTH" ELSE '-' ||ZR."MONTH" END  || '-01') --AS DATE_REF
			,CL.YYYYWW --AS YYYYWW
			,CL.YYYYMM --AS YYYYMM
			,CL.YYYYQQ --AS YYYYQQ
			,ZR.COMPANY_CODE_DESC --AS SUBSIDIARY -- SB.SUBSIDIARY
			,ZR.MATERIAL --AS SKU
			,PD."DIVISION" --AS PDROD_DIVISION
			,PD.PRODUCT_GROUP_1 --AS PDROD_PRODUCT_GROUP
			,PD.PRODUCT_1 --AS PDROD_PRODUCT
			,PD.ATTB01 --AS PROD_ATTB_1
			,PD.SEDA_BU_ESTORE
			,PD.SEDA_CATEGORY_ESTORE
			,PD.SEDA_DESC_ESTORE
			,PD.SEDA_DIVISION_ESTORE
			,PD.SEDA_FAMILY_ESTORE
			--,SB.COUNTRY
			,ZR.CURR --SB.CURRENCY
			,--CASE WHEN PM.MONTH IS NOT NULL THEN
			CASE WHEN PR.MATERIAL IS NOT NULL THEN 'PREMIUM MODEL' ELSE 'NORMAL MODEL' END
			 --ELSE NULL END
		
			
		/*********************************************
		STRETCH
		*********************************************/	
		UNION ALL
		SELECT
			'STR' AS "SOURCE"
			,TO_DATE(ST."YEAR" || CASE WHEN ST."MONTH" BETWEEN 1 AND 9 THEN '-0' ||ST."MONTH" ELSE '-' ||ST."MONTH" END  || '-01') AS DATE_REF
			,CL.YYYYWW AS YYYYWW
			,CL.YYYYMM AS YYYYMM
			,CL.YYYYQQ AS YYYYQQ
			,ST.SUBSIDIARY -- SB.SUBSIDIARY
			,NULL AS CHANNEL
			,NULL AS SUB_CHANNEL
			,NULL AS SALES_CHANNEL_ATTR_1
			,NULL AS SALES_CHANNEL_ATTR_2
			,NULL AS CHANNEL_TYPE
			,NULL AS SKU
			,ST."DIVISION" AS PDROD_DIVISION --,PD."DIVISION" AS PDROD_DIVISION
			,NULL AS PDROD_PRODUCT_GROUP
			,NULL AS PDROD_PRODUCT
			,NULL AS PROD_ATTB_1
			,NULL AS SEDA_BU_ESTORE
			,NULL AS SEDA_DIVISION_ESTORE
			,NULL AS SEDA_CATEGORY_ESTORE
			,NULL AS SEDA_FAMILY_ESTORE
			,NULL AS SEDA_DESC_ESTORE
			,NULL AS STATUS_PO
			,NULL AS AFFILIATE_CHANNEL
			,NULL AS AFFILIATE_SUB_CHANNEL
			,NULL AS AFFILIATE_PARTNER_LEVEL
			,NULL AS GLOBAL_CHANNEL
			,NULL AS AUDIENCE_TYPE
			,SB.COUNTRY
			,SB.CURRENCY
			-- PREMIUM MODEL
			,NULL AS MODEL_TYPE
			, NULL AS CORPORATENAME
			,0 AS QTY
			,SUM(CAST( ST.TARGET * EX.EXCHANGE_RATE AS DECIMAL(18,2) )) AS AMOUNT_LOCAL
			,SUM(CAST( ST.TARGET AS DECIMAL(18,2) )) AS AMOUNT_USD
			,CURRENT_TIMESTAMP AS KPI_LAST_UPDATE --,KPI_LAST_UPDATE
		FROM OW_LAO.ODS_TARGET_STRETCH ST
			LEFT JOIN(
				SELECT
					 SUBSIDIARY
					,MAX(COUNTRY) AS COUNTRY
					,MAX(CURRENCY) AS CURRENCY
				FROM OW_LAO.DIM_AFFILIATE_CHANNEL
				WHERE SALES_ORG IS NOT NULL
					AND BUSINESS_AREA IS NOT NULL
					AND COMPANY_CODE IS NOT NULL
				GROUP BY
					 SUBSIDIARY
			) SB ON ST.SUBSIDIARY = SB.SUBSIDIARY
			LEFT JOIN OW_MD.DIM_CALENDAR CL ON CL.YYYYMMDD = TO_DATE(ST."YEAR" || CASE WHEN ST."MONTH" BETWEEN 1 AND 9 THEN '-0' ||ST."MONTH" ELSE '-' ||ST."MONTH" END  || '-01')
			LEFT JOIN OW_LAO.FT_AP2_EXCHANGE_RATE EX
				ON 	EX.VALID_FROM = TO_DATE(ST."YEAR" || CASE WHEN ST."MONTH" BETWEEN 1 AND 9 THEN '-0' ||ST."MONTH" ELSE '-' ||ST."MONTH" END  || '-01')
					AND EX.TO_CURRENCY = SB.CURRENCY
					AND EX.FROM_CURRENCY = 'USD'
		WHERE 1 = 1
			AND TO_DATE(ST."YEAR" || CASE WHEN ST."MONTH" BETWEEN 1 AND 9 THEN '-0' ||ST."MONTH" ELSE '-' ||ST."MONTH" END  || '-01') >= ADD_DAYS(CURRENT_TIMESTAMP, -60) 
		GROUP BY
			TO_DATE(ST."YEAR" || CASE WHEN ST."MONTH" BETWEEN 1 AND 9 THEN '-0' ||ST."MONTH" ELSE '-' ||ST."MONTH" END  || '-01') --AS DATE_REF
			,CL.YYYYWW --AS YYYYWW
			,CL.YYYYMM --AS YYYYMM
			,CL.YYYYQQ --AS YYYYQQ
			,ST.SUBSIDIARY -- SB.SUBSIDIARY
			,ST."DIVISION" --AS PDROD_DIVISION --,PD."DIVISION" AS PDROD_DIVISION
			,SB.COUNTRY
			,SB.CURRENCY
		
			
		/*********************************************
		MP
		*********************************************/	
		UNION ALL
		SELECT
			  'MP' AS "SOURCE"
			, TO_DATE(MP."YEAR" || CASE WHEN MP."MONTH" BETWEEN 1 AND 9	THEN '-0' || MP."MONTH"	ELSE '-' || MP."MONTH" END || '-01') AS DATE_REF
			, CL.YYYYWW AS YYYYWW
			, MP."YEAR" || CASE WHEN MP."MONTH" BETWEEN 1 AND 9	THEN '-0' || MP."MONTH"	ELSE '-' || MP."MONTH" END AS YYYYMM
			, CL.YYYYQQ AS YYYYQQ
			, MP.SUBSIDIARY -- SB.SUBSIDIARY
			-- INFO CANAIS
			, NULL AS CHANNEL
			, NULL AS SUB_CHANNEL
			, NULL AS SALES_CHANNEL_ATTR_1
			, NULL AS SALES_CHANNEL_ATTR_2
			, NULL AS CHANNEL_TYPE
			-- INFO PRODUTO
			, NULL AS SKU
			, MP.PDROD_DIVISION AS PDROD_DIVISION --,PD."DIVISION" AS PDROD_DIVISION
			, MP.PDROD_PRODUCT_GROUP AS PDROD_PRODUCT_GROUP
			, NULL AS PDROD_PRODUCT
			, NULL AS PROD_ATTB_1
			, NULL AS SEDA_BU_ESTORE
			, NULL AS SEDA_DIVISION_ESTORE
			, NULL AS SEDA_CATEGORY_ESTORE
			, NULL AS SEDA_FAMILY_ESTORE
			, NULL AS SEDA_DESC_ESTORE
			-- INFO AFFILIATE
			, NULL AS STATUS_PO
			, NULL AS AFFILIATE_CHANNEL
			, NULL AS AFFILIATE_SUB_CHANNEL
			, NULL AS AFFILIATE_PARTNER_LEVEL
			, NULL AS GLOBAL_CHANNEL
			, NULL AS AUDIENCE_TYPE
			-- INFO COUNTRY/CURRENCY
			, SB.COUNTRY
			, SB.CURRENCY
			, CASE WHEN PR.MATERIAL IS NOT NULL THEN 'PREMIUM MODEL' ELSE 'NORMAL MODEL' END AS MODEL_TYPE
			, NULL AS CORPORATENAME
			, SUM(CAST(MP.NET_SALES_QTY AS DECIMAL(18, 2))) AS QTY
			, SUM(CAST(MP.NET_SALES AS DECIMAL(18, 2)) * EX.EXCHANGE_RATE) AS AMOUNT_LOCAL
			, SUM(CAST(MP.NET_SALES AS DECIMAL(18, 2))) AS AMOUNT_USD
			, CURRENT_TIMESTAMP AS KPI_LAST_UPDATE --,KPI_LAST_UPDATE
		FROM OW_MD.ODS_MP_ESTORE MP
		LEFT JOIN (
			SELECT SUBSIDIARY
				, MAX(COUNTRY) AS COUNTRY
				, MAX(CURRENCY) AS CURRENCY
			FROM OW_LAO.DIM_AFFILIATE_CHANNEL
			WHERE SALES_ORG IS NOT NULL
				AND BUSINESS_AREA IS NOT NULL
				AND COMPANY_CODE IS NOT NULL
			GROUP BY SUBSIDIARY
			) SB ON 1 = 1
			AND MP.SUBSIDIARY = SB.SUBSIDIARY
		LEFT JOIN OW_MD.DIM_CALENDAR CL
			ON 1 = 1
			AND CL.YYYYMMDD = TO_DATE(MP."YEAR" || CASE WHEN MP."MONTH" BETWEEN 1 AND 9 THEN '-0' || MP."MONTH" ELSE '-' || MP."MONTH" END || '-01')
		LEFT JOIN OW_LAO.FT_AP2_EXCHANGE_RATE EX
			ON 1 = 1
			AND EX.VALID_FROM = TO_DATE(MP."YEAR" || CASE WHEN MP."MONTH" BETWEEN 1 AND 9 THEN '-0' || MP."MONTH" ELSE '-' || MP."MONTH" END || '-01')
			AND EX.TO_CURRENCY = SB.CURRENCY
			AND EX.FROM_CURRENCY = 'USD'
		LEFT JOIN OW_MD.DIM_PRODUCT PRD
			ON 1 = 1
			AND MP.MATERIAL = PRD.SKU
		LEFT JOIN OW_LAO.TMP_PREMIUM_MODELS_WEEKLY_SALES PR
			ON 1=1
			AND PR.MATERIAL = MP.MATERIAL
		WHERE 1 = 1
			AND TO_DATE(MP."YEAR" || CASE WHEN MP."MONTH" BETWEEN 1 AND 9	THEN '-0' || MP."MONTH"	ELSE '-' || MP."MONTH" END || '-01') >= ADD_DAYS(CURRENT_TIMESTAMP, -60)
		GROUP BY
			  TO_DATE(MP."YEAR" || CASE WHEN MP."MONTH" BETWEEN 1 AND 9	THEN '-0' || MP."MONTH"	ELSE '-' || MP."MONTH" END || '-01')
			, CL.YYYYWW --AS YYYYWW
			, MP."YEAR" || CASE WHEN MP."MONTH" BETWEEN 1 AND 9	THEN '-0' || MP."MONTH"	ELSE '-' || MP."MONTH" END
			, CL.YYYYQQ --AS YYYYQQ
			, MP.PDROD_DIVISION
			, MP.PDROD_PRODUCT_GROUP
			, MP.SUBSIDIARY -- SB.SUBSIDIARY
			, SB.COUNTRY
			, SB.CURRENCY
			, CASE WHEN PR.MATERIAL IS NOT NULL THEN 'PREMIUM MODEL' ELSE 'NORMAL MODEL' END
		
			
		/*********************************************
		--GSCM
		*********************************************/	
		UNION ALL 
		SELECT
			 'GSCM' AS "SOURCE"
			, TO_DATE(GS.DATE_REF) AS DATE_REF
			, CL.YYYYWW AS YYYYWW
			, CL.YYYYMM AS YYYYMM
			, CL.YYYYQQ AS YYYYQQ
			, GS.SUBSIDIARY
			-- INFO CANAIS
			, NULL AS CHANNEL
			, NULL AS SUB_CHANNEL
			, NULL AS SALES_CHANNEL_ATTR_1
			, NULL AS SALES_CHANNEL_ATTR_2
			, NULL AS CHANNEL_TYPE
			-- INFO PRODUTO
			, GS.SKU
			, PD."DIVISION" AS PDROD_DIVISION
			, PD.PRODUCT_GROUP_1 AS PDROD_PRODUCT_GROUP
			, PD.PRODUCT_1 AS PDROD_PRODUCT
			, PD.ATTB01 AS PROD_ATTB_1
			, PD.SEDA_BU_ESTORE
			, PD.SEDA_CATEGORY_ESTORE
			, PD.SEDA_DESC_ESTORE
			, PD.SEDA_DIVISION_ESTORE
			, PD.SEDA_FAMILY_ESTORE
			-- INFO AFFILIATE
			, NULL AS STATUS_PO
			, NULL AS AFFILIATE_CHANNEL
			, NULL AS AFFILIATE_SUB_CHANNEL
			, NULL AS AFFILIATE_PARTNER_LEVEL
			, NULL AS GLOBAL_CHANNEL
			, NULL AS AUDIENCE_TYPE
			-- INFO COUNTRY/CURRENCY
			, NULL AS COUNTRY
			, NULL AS CURRENCY
			-- PREMIUM MODEL
			, CASE WHEN PR.MATERIAL IS NOT NULL THEN 'PREMIUM MODEL' ELSE 'NORMAL MODEL' END AS MODEL_TYPE
			, NULL AS CORPORATENAME
			, SUM(CAST(GS.QTY AS DECIMAL(18, 2))) AS QTY
			, NULL AS AMOUNT_LOCAL
			, NULL AS AMOUNT_USD
			, CURRENT_TIMESTAMP AS KPI_LAST_UPDATE
		FROM OW_LAO.TMP_GSCM_FILES GS
			LEFT JOIN OW_MD.DIM_CALENDAR CL ON CL.YYYYMMDD = GS.DATE_REF
			LEFT JOIN OW_MD.DIM_PRODUCT PD ON PD.SKU = GS.SKU
			LEFT JOIN OW_LAO.TMP_PREMIUM_MODELS_WEEKLY_SALES PR ON PR.MATERIAL = GS.SKU
		WHERE 1=1
			AND TO_DATE(GS.DATE_REF) >= ADD_DAYS(CURRENT_TIMESTAMP, -60)
		GROUP BY
			  TO_DATE(GS.DATE_REF) --AS DATE_REF
			, CL.YYYYWW --AS YYYYWW
			, CL.YYYYMM --AS YYYYMM
			, CL.YYYYQQ --AS YYYYQQ
			, GS.SUBSIDIARY
			-- INFO PRODUTO
			, GS.SKU
			, PD."DIVISION" --AS PDROD_DIVISION
			, PD.PRODUCT_GROUP_1 --AS PDROD_PRODUCT_GROUP
			, PD.PRODUCT_1 --AS PDROD_PRODUCT
			, PD.ATTB01 --AS PROD_ATTB_1
			, PD.SEDA_BU_ESTORE
			, PD.SEDA_CATEGORY_ESTORE
			, PD.SEDA_DESC_ESTORE
			, PD.SEDA_DIVISION_ESTORE
			, PD.SEDA_FAMILY_ESTORE
			, CASE WHEN PR.MATERIAL IS NOT NULL THEN 'PREMIUM MODEL' ELSE 'NORMAL MODEL' END --AS MODEL_TYPE
		
			
		/*********************************************
		FORECAST
		*********************************************/				
		UNION ALL
 		SELECT
			 'FCST' AS "SOURCE"
			, TO_DATE( CONCAT( CONCAT( LEFT(FCT.PERIOD,4),RIGHT(FCT.PERIOD,2) ),'01')) AS DATE_REF
			, CL.YYYYWW AS YYYYWW
			, CL.YYYYMM AS YYYYMM
			, CL.YYYYQQ AS YYYYQQ
			, SUB.SUBSIDIARY
			-- INFO CANAIS
			, NULL AS CHANNEL
			, NULL AS SUB_CHANNEL
			, NULL AS SALES_CHANNEL_ATTR_1
			, NULL AS SALES_CHANNEL_ATTR_2
			, NULL AS CHANNEL_TYPE
			-- INFO PRODUTO
			, FCT.PRODUCT_NUMBER AS SKU
			, PD."DIVISION" AS PDROD_DIVISION
			, PD.PRODUCT_GROUP_1 AS PDROD_PRODUCT_GROUP
			, PD.PRODUCT_1 AS PDROD_PRODUCT
			, PD.ATTB01 AS PROD_ATTB_1
			, PD.SEDA_BU_ESTORE
			, PD.SEDA_CATEGORY_ESTORE
			, PD.SEDA_DESC_ESTORE
			, PD.SEDA_DIVISION_ESTORE
			, PD.SEDA_FAMILY_ESTORE
			-- INFO AFFILIATE
			, NULL AS STATUS_PO
			, NULL AS AFFILIATE_CHANNEL
			, NULL AS AFFILIATE_SUB_CHANNEL
			, NULL AS AFFILIATE_PARTNER_LEVEL
			, NULL AS GLOBAL_CHANNEL
			, NULL AS AUDIENCE_TYPE
			-- INFO COUNTRY/CURRENCY
			, NULL AS COUNTRY
			, FCT.CURRENCY AS CURRENCY
			, CASE WHEN PR.MATERIAL IS NOT NULL THEN 'PREMIUM MODEL' ELSE 'NORMAL MODEL' END AS MODEL_TYPE
			, NULL AS CORPORATENAME
			, SUM(FCT.QUANTITY_NET) AS QTY
			, SUM(FCT.NET_SALES) AS AMOUNT_LOCAL
			, SUM(CAST( FCT.NET_SALES / EX.EXCHANGE_RATE AS DECIMAL(18,2) )) AS AMOUNT_USD		
			, CURRENT_TIMESTAMP AS KPI_LAST_UPDATE				
		FROM OW_LAO.RAW_NERP_ZRCOA20250_FORECAST_SALES FCT
			INNER JOIN OW_MD.DIM_SUBSIDIARY SUB ON 1=1
				AND FCT.SALES_ORGANIZATION = SUB.SALES_ORG
				--AND SUB.SUBSIDIARY = 'SEDA' -- SOMENTE SEDA
			INNER JOIN ( -- GET LAST FILE
				SELECT LEFT(F.PERIOD,4) AS "YEAR"
					 , RIGHT(F.PERIOD,2) AS "MONTH"
					 , S.SUBSIDIARY
					 , MAX(CAST(SUBSTR_REGEXPR('([[:digit:]]{8})' IN F.FILE_NAME) AS DATE)) AS FILE_NAME_DATE
				FROM OW_LAO.RAW_NERP_ZRCOA20250_FORECAST_SALES F
					INNER JOIN OW_MD.DIM_SUBSIDIARY S ON F.SALES_ORGANIZATION = S.SALES_ORG
				WHERE --S.SUBSIDIARY = 'SEDA'
					OW_LAO.ISNUMERIC(SUBSTR_REGEXPR('([[:digit:]]{8})' IN F.FILE_NAME)) = 1
				GROUP BY LEFT(F.PERIOD,4)
					, RIGHT(F.PERIOD,2)
					, S.SUBSIDIARY
			) LF -- LAST FILE
			ON  LF.FILE_NAME_DATE = CAST(SUBSTR_REGEXPR('([[:digit:]]{8})' IN FCT.FILE_NAME) AS DATE)
				AND LF."YEAR" = LEFT(FCT.PERIOD,4)
				AND LF."MONTH" = RIGHT(FCT.PERIOD,2)
				AND LF.SUBSIDIARY = SUB.SUBSIDIARY
			LEFT JOIN OW_MD.DIM_CALENDAR CL ON CL.YYYYMMDD = TO_DATE( CONCAT( CONCAT( LEFT(FCT.PERIOD,4),RIGHT(FCT.PERIOD,2) ),'01'))
			LEFT JOIN OW_MD.DIM_PRODUCT PD ON PD.SKU = FCT.PRODUCT_NUMBER 
			LEFT JOIN OW_LAO.TMP_PREMIUM_MODELS_WEEKLY_SALES PR ON PR.MATERIAL = FCT.PRODUCT_NUMBER
			LEFT JOIN OW_LAO.FT_AP2_EXCHANGE_RATE EX
				ON 	EX.VALID_FROM = TO_DATE( CONCAT( CONCAT( LEFT(FCT.PERIOD,4),RIGHT(FCT.PERIOD,2) ),'01'))
					AND EX.TO_CURRENCY = FCT.CURRENCY
					AND EX.FROM_CURRENCY = 'USD'
		WHERE FCT.CUSTOMER IN (
				SELECT DISTINCT CAST(SOLD_TO_PARTY AS VARCHAR(50)) SOLD_TO_PARTY
				FROM OW_LAO.DIM_SOLD_TO 
				--WHERE SUBSIDIARY = 'SEDA'
			)
			AND OW_LAO.ISNUMERIC(SUBSTR_REGEXPR('([[:digit:]]{8})' IN FCT.FILE_NAME)) = 1
			AND TO_DATE( CONCAT( CONCAT( LEFT(FCT.PERIOD,4),RIGHT(FCT.PERIOD,2) ),'01'))  >= ADD_DAYS(CURRENT_TIMESTAMP, -60)
		GROUP BY
			  TO_DATE( CONCAT( CONCAT( LEFT(FCT.PERIOD,4),RIGHT(FCT.PERIOD,2) ),'01'))
			, CL.YYYYWW --AS YYYYWW
			, CL.YYYYMM --AS YYYYMM
			, CL.YYYYQQ --AS YYYYQQ
			, SUB.SUBSIDIARY
			-- INFO PRODUTO
			, FCT.PRODUCT_NUMBER
			, PD."DIVISION" --AS PDROD_DIVISION
			, PD.PRODUCT_GROUP_1 --AS PDROD_PRODUCT_GROUP
			, PD.PRODUCT_1 --AS PDROD_PRODUCT
			, PD.ATTB01 --AS PROD_ATTB_1
			, PD.SEDA_BU_ESTORE
			, PD.SEDA_CATEGORY_ESTORE
			, PD.SEDA_DESC_ESTORE
			, PD.SEDA_DIVISION_ESTORE
			, PD.SEDA_FAMILY_ESTORE
			, FCT.CURRENCY
			, CASE WHEN PR.MATERIAL IS NOT NULL THEN 'PREMIUM MODEL' ELSE 'NORMAL MODEL' END --AS MODEL_TYPE
	--)
	;
	UPDATE OW_LAO.TF_D2C_NERP_WEEKLY_SALES_KPI SET
		KPI_LAST_UPDATE = (
				SELECT MAX(PO_CREATION_DATE)
				FROM OW_LAO.TF_D2C_NERP_SALES
				WHERE "SOURCE" = 'PO'
					AND SUBSIDIARY = 'SEDA'
			  ) --AS KPI_LAST_UPDATE					
	;
	/******************************
	-- APAGA TABELAS TEMPORÁRIAS
	******************************/
	DROP TABLE OW_LAO.TMP_PREMIUM_MODELS_WEEKLY_SALES;
	DROP TABLE OW_LAO.TMP_GSCM_FILES;
END