
	/***********************************************************************************************
	CREATED BY : Luciano Mariani
	CREATION DATE : 2023-05-25
	ALTER DATE : 2023-06-07
	VERSION: 3.0
	DESCRIPTION: Feeds unified table with KPI 4.3 KPI Daily Sales indicators
		TF_D2C_NERP_DAILY_SALES_KPI regarding Sales Order transactions (ZRSDD6A120)
		and Outbound (ZLLEJ50090) by Dimension Product and Dimension Sales Channel.
	-- CALL OW_LAO.PROC_D2C_NERP_DAILY_SALES;
	-- SELECT TOP 100 * FROM OW_LAO.TF_D2C_NERP_DAILY_SALES_KPI WHERE "SOURCE" = 'PO'
	***********************************************************************************************/
	CREATE PROCEDURE OW_LAO.PROC_D2C_NERP_DAILY_SALES
	LANGUAGE SQLSCRIPT as
	BEGIN
		
		-- VERIFICA SE ALGUMA DAS TABELAS USADAS NO PROCESSO ESTÁ VAZIA
		IF(
			   (SELECT COUNT('') FROM OW_LAO.ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING) = 0
			OR (SELECT COUNT('') FROM OW_LAO.ODS_NERP_ZLLEJ50090_OUTBOUND_TRACKING) = 0
			OR (SELECT COUNT('') FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER VO) = 0
		)
		THEN
			-- SE ALGUMA ESTIVER VAZIA ENVIA MSG E SAI
			SELECT 'NÃO HÁ REGISTROS EM UMA OU MAIS TABELAS' AS RESULTADO ,CURRENT_DATE AS DATE_NOW FROM dummy;
		ELSE
			DECLARE v_UPDATE BOOLEAN;
			SELECT FALSE INTO v_UPDATE FROM DUMMY;
			
			-- TABELAS TEMPORARIAS VTEX SO TMP
			CREATE LOCAL TEMPORARY TABLE #VTEX_SO_TMP (
				 ORDER_ID NVARCHAR(100)
				,CUSTOMER_PO NVARCHAR(100)
				,SALES_CHANNEL NVARCHAR(100)
			) ;
			INSERT INTO #VTEX_SO_TMP
			SELECT
				 ORDER_ID
				,MAX(CUSTOMER_PO) AS CUSTOMER_PO
				,MAX(SALES_CHANNEL) AS SALES_CHANNEL
			FROM(
				SELECT
					 V.ORDER_ID
					,CASE WHEN S.CUSTOMER_PO IS NOT NULL THEN
						S.CUSTOMER_PO
					 ELSE 
						CAST("SEQUENCE" AS VARCHAR(80)) 
					 END AS CUSTOMER_PO
					,CAST(SALES_CHANNEL AS VARCHAR(80)) AS SALES_CHANNEL
				FROM  -- U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_LIST V (DESATUALIZADA 15 DIAS)
					U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER V
					LEFT JOIN OW_LAO.ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING S ON V.ORDER_ID = S.CUSTOMER_PO
			)
			GROUP BY
				 ORDER_ID ;
			/*****************************************************************
				PO
			*****************************************************************/	
			-- CASO A DATA DA ULTIMA INGESTION DE VTEX SEJA MAIOR QUE ULTIMA UPDATE DE PO
			IF (
				(
					SELECT MAX(UPDATED_AT) AS VTEX_LOAD_DATE
					FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER
				) > 
				(
					SELECT -- PEGA ULTIMA ATUALIZAÇÃO DE CADA PROCESSO
						MAX(KPI_LAST_UPDATE) AS PO_UPDATED
					FROM OW_LAO.TF_D2C_NERP_DAILY_SALES_KPI
					WHERE SOURCE = 'PO'
				)  OR (SELECT COUNT('') FROM OW_LAO.TF_D2C_NERP_DAILY_SALES_KPI WHERE SOURCE = 'PO') = 0
			) THEN
				SELECT TRUE INTO v_UPDATE FROM DUMMY;
				-- ITEM_COMPONENTS_TMP
				CREATE LOCAL TEMPORARY TABLE #ITEM_COMPONENTS_TMP (
					 ORDER_ID NVARCHAR(100)
					,SKU_ID NVARCHAR(100)
					,SKU NVARCHAR(100)
					,QUANTITY INTEGER
					,PRICE DECIMAL(18)
				);
				INSERT INTO #ITEM_COMPONENTS_TMP	
				SELECT DISTINCT
					 ORDER_ID
					,SKU_ID
					,REF_ID AS SKU
					,QUANTITY
					,PRICE
				FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_ITEM_COMPONENTS
				WHERE REF_ID IS NOT NULL;
			
				-- APAGA DADOS ANTERIORES DE PO
				DELETE FROM OW_LAO.TF_D2C_NERP_DAILY_SALES_KPI
				WHERE SOURCE = 'PO';
				
				-- INSERE DADOS DE PO
				INSERT INTO OW_LAO.TF_D2C_NERP_DAILY_SALES_KPI(
					"SOURCE"
					,DATE_REF
					,YYYYWW
					,YYYYMM
					,YYYYQQ
					,SUBSIDIARY
					,CHANNEL
					,SUB_CHANNEL
					,SALES_CHANNEL_ATTR_1
					,SALES_CHANNEL_ATTR_2
					,SKU
					,PDROD_DIVISION
					,PDROD_PRODUCT_GROUP
					,PDROD_PRODUCT
					,PROD_ATTB_1
					,SEDA_BU_ESTORE
					,SEDA_DIVISION_ESTORE
					,SEDA_CATEGORY_ESTORE
					,SEDA_FAMILY_ESTORE
					,SEDA_DESC_ESTORE
					,QTY
					,AMOUNT_LOCAL
					,AMOUNT_USD
					,STATUS_PO
					,KPI_LAST_UPDATE
				)
				SELECT 
					"SOURCE"
					,DATE_REF
					,YYYYWW
					,YYYYMM
					,YYYYQQ
					,SUBSIDIARY
					,CHANNEL
					,SUB_CHANNEL
					,SALES_CHANNEL_ATTR_1
					,SALES_CHANNEL_ATTR_2
					,SKU
					,PDROD_DIVISION
					,PDROD_PRODUCT_GROUP
					,PDROD_PRODUCT
					,PROD_ATTB_1		
					,SEDA_BU_ESTORE
					,SEDA_DIVISION_ESTORE
					,SEDA_CATEGORY_ESTORE
					,SEDA_FAMILY_ESTORE
					,SEDA_DESC_ESTORE
					,SUM(QTY) AS QTY
					,SUM(AMOUNT_LOCAL) AS AMOUNT_LOCAL
					,SUM(AMOUNT_USD) AS AMOUNT_USD
					,STATUS_PO
					,CURRENT_TIMESTAMP AS KPI_LAST_UPDATE
				FROM(
					/*****************************************************************
					PO (VTEX [SOMENTE ITENS]) {CREATION_TIMESTAMP}
					*****************************************************************/
					SELECT
						'PO' AS "SOURCE"
						,TO_DATE(VO.CREATION_TIMESTAMP) AS DATE_REF			
						,CPO.YYYYWW AS YYYYWW
						,CPO.YYYYMM AS YYYYMM
						,CPO.YYYYQQ AS YYYYQQ
						,'SEDA' AS SUBSIDIARY
						,CH.CHANNEL 
						,CH.SUB_CHANNEL 
						,CH.SALES_CHANNEL_ATTR_1 
						,CH.SALES_CHANNEL_ATTR_2
						,PD.SKU
						,PD."DIVISION" AS PDROD_DIVISION
						,PD.PRODUCT_GROUP_1 AS PDROD_PRODUCT_GROUP 
						,PD.PRODUCT_1 AS PDROD_PRODUCT 
						,PD.ATTB01 AS PROD_ATTB_1 
						,PD.SEDA_BU_ESTORE
						,PD.SEDA_DIVISION_ESTORE
						,PD.SEDA_CATEGORY_ESTORE
						,PD.SEDA_FAMILY_ESTORE
						,PD.SEDA_DESC_ESTORE
						,CAST(VI.QUANTITY AS INTEGER) AS QTY
						,CAST((
								( VI.PRICE * VI.QUANTITY ) 
								+ CASE WHEN (VO.TOTAL_DISCOUNTS <> 0 AND VO.TOTAL_ITEMS > 0) THEN -- (SUBTRAI OS DESCONTOS)
									( (VI.PRICE * VI.QUANTITY) / VO.TOTAL_ITEMS ) * VO.TOTAL_DISCOUNTS
								 ELSE 0 END
								+ CASE WHEN (VO.TOTAL_SHIPPING <> 0 AND VO.TOTAL_ITEMS > 0) THEN -- FRETE SOMA O FRETE
									( (VI.PRICE * VI.QUANTITY) / VO.TOTAL_ITEMS ) * VO.TOTAL_SHIPPING
								 ELSE 0 END
							) / 100
						 AS DECIMAL(18,2)) AS AMOUNT_LOCAL
						,CAST(
							((
								( VI.PRICE * VI.QUANTITY ) 
								+ CASE WHEN (VO.TOTAL_DISCOUNTS <> 0 AND VO.TOTAL_ITEMS > 0) THEN -- (SUBTRAI OS DESCONTOS)
									( (VI.PRICE * VI.QUANTITY) / VO.TOTAL_ITEMS ) * VO.TOTAL_DISCOUNTS
								 ELSE 0 END
								+ CASE WHEN (VO.TOTAL_SHIPPING <> 0 AND VO.TOTAL_ITEMS > 0) THEN -- FRETE SOMA O FRETE
									( (VI.PRICE * VI.QUANTITY) / VO.TOTAL_ITEMS ) * VO.TOTAL_SHIPPING
								 ELSE 0 END
							) / 100)
							/ EX.EXCHANGE_RATE
						 AS DECIMAL(18,2)) AS AMOUNT_USD 
						,VO.STATUS AS STATUS_PO
					FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER VO
						INNER JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_ITEM VI ON VO.ORDER_ID = VI.ORDER_ID
						LEFT JOIN #ITEM_COMPONENTS_TMP VC ON VI.ORDER_ID = VC.ORDER_ID AND VI.SKU_ID = VC.SKU_ID
						LEFT JOIN #VTEX_SO_TMP LT ON VO.ORDER_ID = LT.ORDER_ID
						LEFT JOIN OW_MD.DIM_SALES_CHANNEL CH ON LT.SALES_CHANNEL = CH.VTEX_POLICY
						LEFT JOIN OW_MD.DIM_PRODUCT PD ON PD.SKU = VI.REF_ID
						LEFT JOIN OW_MD.DIM_CALENDAR CPO ON CPO.YYYYMMDD = TO_DATE(VO.CREATION_TIMESTAMP) -- PO
						LEFT JOIN OW_LAO.FT_AP2_EXCHANGE_RATE EX
							ON 	EX.VALID_FROM = TO_DATE(VO.CREATION_TIMESTAMP)
								AND EX.TO_CURRENCY = 'BRL' -- SO.SO_CURR
								AND EX.FROM_CURRENCY = 'USD'
					WHERE
						VC.SKU IS NULL  -- NÃO DEVE TER COMPONENTS
						AND VI.QUANTITY IS NOT NULL
						AND VI.PRICE IS NOT NULL
						AND VO.STATUS IS NOT NULL
						AND VO.STATUS NOT IN('cancel','canceled')
						
					/*****************************************************************
					PO (VTEX-[SOMENTE COMPONENTES] {CREATION_TIMESTAMP}) 
					******************************************************************/
					UNION ALL
					SELECT
						'PO' AS "SOURCE"
						,TO_DATE(VO.CREATION_TIMESTAMP) AS DATE_REF			
						,CPO.YYYYWW AS YYYYWW
						,CPO.YYYYMM AS YYYYMM
						,CPO.YYYYQQ AS YYYYQQ
						,'SEDA' AS SUBSIDIARY
						,CH.CHANNEL 
						,CH.SUB_CHANNEL 
						,CH.SALES_CHANNEL_ATTR_1 
						,CH.SALES_CHANNEL_ATTR_2
						,PD.SKU
						,PD."DIVISION" AS PDROD_DIVISION
						,PD.PRODUCT_GROUP_1 AS PDROD_PRODUCT_GROUP 
						,PD.PRODUCT_1 AS PDROD_PRODUCT 
						,PD.ATTB01 AS PROD_ATTB_1
						,PD.SEDA_BU_ESTORE
						,PD.SEDA_DIVISION_ESTORE
						,PD.SEDA_CATEGORY_ESTORE
						,PD.SEDA_FAMILY_ESTORE
						,PD.SEDA_DESC_ESTORE
						,CAST((VC.QUANTITY * VI.QUANTITY) AS INTEGER) AS QTY
						,CAST((
								(VC.PRICE * (VC.QUANTITY * VI.QUANTITY)) 
								+ CASE WHEN (VO.TOTAL_DISCOUNTS <> 0 AND VO.TOTAL_ITEMS > 0) THEN -- (SUBTRAI OS DESCONTOS)
									( (VC.PRICE * (VC.QUANTITY * VI.QUANTITY)) / VO.TOTAL_ITEMS ) * VO.TOTAL_DISCOUNTS
								 ELSE 0 END
								+ CASE WHEN (VO.TOTAL_SHIPPING <> 0 AND VO.TOTAL_ITEMS > 0) THEN -- FRETE SOMA O FRETE
									( (VC.PRICE * (VC.QUANTITY * VI.QUANTITY)) / VO.TOTAL_ITEMS ) * VO.TOTAL_SHIPPING
								 ELSE 0 END
							) / 100
						 AS DECIMAL(18,2)) AS AMOUNT_LOCAL
						,CAST(((
								(VC.PRICE * (VC.QUANTITY * VI.QUANTITY)) 
								+ CASE WHEN (VO.TOTAL_DISCOUNTS <> 0 AND VO.TOTAL_ITEMS > 0) THEN -- (SUBTRAI OS DESCONTOS)
									( (VC.PRICE * (VC.QUANTITY * VI.QUANTITY)) / VO.TOTAL_ITEMS ) * VO.TOTAL_DISCOUNTS
								 ELSE 0 END
								+ CASE WHEN (VO.TOTAL_SHIPPING <> 0 AND VO.TOTAL_ITEMS > 0) THEN -- FRETE SOMA O FRETE
									( (VC.PRICE * (VC.QUANTITY * VI.QUANTITY)) / VO.TOTAL_ITEMS ) * VO.TOTAL_SHIPPING
								 ELSE 0 END
								) / 100)
								/ EX.EXCHANGE_RATE
						 AS DECIMAL(18,2)) AS AMOUNT_USD 
						,VO.STATUS AS STATUS_PO
					FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER VO
						INNER JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_ITEM VI ON VO.ORDER_ID = VI.ORDER_ID
						INNER JOIN #ITEM_COMPONENTS_TMP VC ON VI.ORDER_ID = VC.ORDER_ID AND VI.SKU_ID = VC.SKU_ID
						LEFT JOIN #VTEX_SO_TMP LT ON VO.ORDER_ID = LT.ORDER_ID
						LEFT JOIN OW_MD.DIM_SALES_CHANNEL CH ON LT.SALES_CHANNEL = CH.VTEX_POLICY
						LEFT JOIN OW_MD.DIM_PRODUCT PD ON PD.SKU = VC.SKU
						LEFT JOIN OW_MD.DIM_CALENDAR CPO ON CPO.YYYYMMDD = TO_DATE(VO.CREATION_TIMESTAMP) -- PO
						LEFT JOIN OW_LAO.FT_AP2_EXCHANGE_RATE EX
							ON 	EX.VALID_FROM = TO_DATE(VO.CREATION_TIMESTAMP)
								AND EX.TO_CURRENCY = 'BRL' -- SO.SO_CURR
								AND EX.FROM_CURRENCY = 'USD'
					WHERE
						VC.SKU IS NOT NULL -- SOMENTE COMPONENTS
						AND VC.QUANTITY IS NOT NULL -- SOMENTE QUANDO TEM COMPONENTES
						AND VC.PRICE IS NOT NULL
						AND VO.STATUS IS NOT NULL
						AND VO.STATUS NOT IN('cancel','canceled')			
				)
				GROUP BY
					"SOURCE"
					,DATE_REF
					,YYYYWW
					,YYYYMM
					,YYYYQQ
					,SUBSIDIARY
					,CHANNEL
					,SUB_CHANNEL
					,SALES_CHANNEL_ATTR_1
					,SALES_CHANNEL_ATTR_2
					,SKU
					,PDROD_DIVISION
					,PDROD_PRODUCT_GROUP
					,PDROD_PRODUCT
					,PROD_ATTB_1
					,SEDA_BU_ESTORE
					,SEDA_DIVISION_ESTORE
					,SEDA_CATEGORY_ESTORE
					,SEDA_FAMILY_ESTORE
					,SEDA_DESC_ESTORE
					,STATUS_PO
				ORDER BY
					 "SOURCE"
					,DATE_REF
				;
				
				-- APAGA TEMPORÁRIA
				DROP TABLE #ITEM_COMPONENTS_TMP;
			END IF;
			/*****************************************************************
				SO E IOD
			*****************************************************************/			
			-- CASO A DATA DA ULTIMA INGESTION SALES ORDER TRACKING SEJA MAIOR QUE A ULTIMA ATUALIZAÇÃO DE SO E IOD
			IF (
				(
					SELECT MAX(LOAD_DATE) AS SALES_ORDER_LOAD_DATE
					FROM OW_LAO.ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING
				) > 
				(
					SELECT -- PEGA ULTIMA ATUALIZAÇÃO DE CADA PROCESSO
						MAX(KPI_LAST_UPDATE) AS SO_IOD_UPDATED
					FROM OW_LAO.TF_D2C_NERP_DAILY_SALES_KPI
					WHERE "SOURCE" IN('SO','IOD')
				)  OR (SELECT COUNT('') FROM OW_LAO.TF_D2C_NERP_DAILY_SALES_KPI WHERE SOURCE IN('SO','IOD')) = 0
			)
			THEN
				SELECT TRUE INTO v_UPDATE FROM DUMMY;
			
				-- APAGA DADOS DE SO E IOD
				DELETE FROM OW_LAO.TF_D2C_NERP_DAILY_SALES_KPI
				WHERE SOURCE IN('SO','IOD');
		
				-- INSERE DADOS DE SO E IOD
				INSERT INTO OW_LAO.TF_D2C_NERP_DAILY_SALES_KPI(
					"SOURCE"
					,DATE_REF
					,YYYYWW
					,YYYYMM
					,YYYYQQ
					,SUBSIDIARY
					,CHANNEL
					,SUB_CHANNEL
					,SALES_CHANNEL_ATTR_1
					,SALES_CHANNEL_ATTR_2
					,SKU
					,PDROD_DIVISION
					,PDROD_PRODUCT_GROUP
					,PDROD_PRODUCT
					,PROD_ATTB_1
					,SEDA_BU_ESTORE
					,SEDA_DIVISION_ESTORE
					,SEDA_CATEGORY_ESTORE
					,SEDA_FAMILY_ESTORE
					,SEDA_DESC_ESTORE
					,QTY
					,AMOUNT_LOCAL
					,AMOUNT_USD
					,STATUS_PO
					,KPI_LAST_UPDATE
				)
				SELECT 
					"SOURCE"
					,DATE_REF
					,YYYYWW
					,YYYYMM
					,YYYYQQ
					,SUBSIDIARY
					,CHANNEL
					,SUB_CHANNEL
					,SALES_CHANNEL_ATTR_1
					,SALES_CHANNEL_ATTR_2
					,SKU
					,PDROD_DIVISION
					,PDROD_PRODUCT_GROUP
					,PDROD_PRODUCT
					,PROD_ATTB_1		
					,SEDA_BU_ESTORE
					,SEDA_DIVISION_ESTORE
					,SEDA_CATEGORY_ESTORE
					,SEDA_FAMILY_ESTORE
					,SEDA_DESC_ESTORE
					,SUM(QTY) AS QTY
					,SUM(AMOUNT_LOCAL) AS AMOUNT_LOCAL
					,SUM(AMOUNT_USD) AS AMOUNT_USD
					,'' AS STATUS_PO	
					,CURRENT_TIMESTAMP AS KPI_LAST_UPDATE
				FROM(
					/*****************************************************************
					 SO (SALES ORDER TRACKING {SO_CREATE_ON})
					*****************************************************************/
					SELECT 
						'SO' AS SOURCE
						--,OW_LAO.Add_Hours(SO.SO_CREATE_ON, SO.SO_CREATE_ON_TIME, -12) AS DATE_REF
						,TO_DATE(SO.SO_LOCAL_CREATE_ON_D) AS DATE_REF
						,CSO.YYYYWW AS YYYYWW
						,CSO.YYYYMM AS YYYYMM
						,CSO.YYYYQQ AS YYYYQQ
						,CASE WHEN SO.SALES_ORG = '8201' THEN 'SEDA' ELSE 'OTHERS' END AS SUBSIDIARY --	1	Subsidiary
						,CH.CHANNEL --	2 Channel
						,CH.SUB_CHANNEL --	3 Sub Channel
						,CH.SALES_CHANNEL_ATTR_1 --	4 Ch. Attb 1
						,CH.SALES_CHANNEL_ATTR_2 --	5 Ch. Attb 2
						,SO.MATERIAL AS SKU
						,PD."DIVISION" AS PDROD_DIVISION --	6	Division
						,PD.PRODUCT_GROUP_1 AS PDROD_PRODUCT_GROUP -- 7	Product Group
						,PD.PRODUCT_1 AS PDROD_PRODUCT -- 8	Product
						,PD.ATTB01 AS PROD_ATTB_1
						,PD.SEDA_BU_ESTORE
						,PD.SEDA_DIVISION_ESTORE
						,PD.SEDA_CATEGORY_ESTORE
						,PD.SEDA_FAMILY_ESTORE
						,PD.SEDA_DESC_ESTORE
						,CAST(SO.ORDER_QTY_BASE AS INTEGER) AS QTY
						,CAST(REPLACE(SO.SO_NET_VALUE, ',', '') AS DECIMAL(18,2)) AS AMOUNT_LOCAL
						,CAST((REPLACE(SO.SO_NET_VALUE, ',', '') / EX.EXCHANGE_RATE	)AS DECIMAL(18,2)) AS AMOUNT_USD --  20 AS AMOUNT_USD_PAYMENT_SO -- 21 [Amount($USD)_Payment]
					FROM OW_LAO.ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING SO
						LEFT JOIN #VTEX_SO_TMP VO ON VO.ORDER_ID = SO.CUSTOMER_PO
						LEFT JOIN OW_MD.DIM_SALES_CHANNEL CH ON VO.SALES_CHANNEL = CH.VTEX_POLICY
						LEFT JOIN OW_MD.DIM_PRODUCT PD ON SO.MATERIAL = PD.SKU
						LEFT JOIN OW_MD.DIM_CALENDAR CSO ON CSO.YYYYMMDD = TO_DATE(SO.SO_LOCAL_CREATE_ON_D)
						LEFT JOIN OW_LAO.FT_AP2_EXCHANGE_RATE EX
							ON 	EX.VALID_FROM = TO_DATE(SO.SO_LOCAL_CREATE_ON_D)
								AND EX.TO_CURRENCY = SO.SO_CURR
								AND EX.FROM_CURRENCY = 'USD'
					WHERE
						-- COMMON FILTERS 
						SO.SALES_DOC_TYPE = 'YS10' -- (SOMENTE D2C)
						AND SO.SALES_ORG = '8201' -- SEDA
						--AND SO.SHIPPING_TYPE IN('P3','P4')
						AND SO.REJECT_REASON IS NULL
						AND SO.REJECT_REASON_1 IS NULL
						AND SO.SO_LOCAL_CREATE_ON_D IS NOT NULL
					
					/************************************************
					 IOD (SALES ORDER TRACKING {BILLING_DATE})
					************************************************/
					UNION ALL
					SELECT
						'IOD' AS SOURCE
						--,OW_LAO.Add_Hours(SO.SO_CREATE_ON, SO.SO_CREATE_ON_TIME, -12) AS DATE_REF
						,TO_DATE(SO.BILLING_DATE) AS DATE_REF
						,CSO.YYYYWW AS YYYYWW
						,CSO.YYYYMM AS YYYYMM
						,CSO.YYYYQQ AS YYYYQQ
						,CASE WHEN SO.SALES_ORG = '8201' THEN 'SEDA' ELSE 'OTHERS' END AS SUBSIDIARY --	1	Subsidiary
						,CH.CHANNEL --	2 Channel
						,CH.SUB_CHANNEL --	3 Sub Channel
						,CH.SALES_CHANNEL_ATTR_1 --	4 Ch. Attb 1
						,CH.SALES_CHANNEL_ATTR_2 --	5 Ch. Attb 2
						,SO.MATERIAL AS SKU
						,PD."DIVISION" AS PDROD_DIVISION --	6	Division
						,PD.PRODUCT_GROUP_1 AS PDROD_PRODUCT_GROUP -- 7	Product Group
						,PD.PRODUCT_1 AS PDROD_PRODUCT -- 8	Product
						,PD.ATTB01 AS PROD_ATTB_1
						,PD.SEDA_BU_ESTORE
						,PD.SEDA_DIVISION_ESTORE
						,PD.SEDA_CATEGORY_ESTORE
						,PD.SEDA_FAMILY_ESTORE
						,PD.SEDA_DESC_ESTORE
						,CAST(SO.BILLED_QTY_BASE AS INTEGER) AS QTY
						,CAST(REPLACE(SO.BILLING_NET_VALUE, ',', '') AS DECIMAL(18,2)) AS AMOUNT_LOCAL
						,CAST(
							(REPLACE(SO.BILLING_NET_VALUE, ',', '') / EX.EXCHANGE_RATE
						)AS DECIMAL(18,2)) AS AMOUNT_USD --  20 AS AMOUNT_USD_PAYMENT_SO -- 21 [Amount($USD)_Payment]
					FROM OW_LAO.ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING SO
						LEFT JOIN #VTEX_SO_TMP VO ON VO.ORDER_ID = SO.CUSTOMER_PO
						LEFT JOIN OW_MD.DIM_SALES_CHANNEL CH ON VO.SALES_CHANNEL = CH.VTEX_POLICY
						LEFT JOIN OW_MD.DIM_PRODUCT PD ON SO.MATERIAL = PD.SKU
						LEFT JOIN OW_MD.DIM_CALENDAR CSO ON CSO.YYYYMMDD = TO_DATE(SO.BILLING_DATE)
						LEFT JOIN OW_LAO.FT_AP2_EXCHANGE_RATE EX
							ON 	EX.VALID_FROM = TO_DATE(SO.BILLING_DATE)
								AND EX.TO_CURRENCY = SO.SO_CURR
								AND EX.FROM_CURRENCY = 'USD'
					WHERE
						-- COMMON FILTERS 
						SO.SALES_DOC_TYPE = 'YS10' -- (SOMENTE D2C)
						AND SO.SALES_ORG = '8201' -- SEDA
						--AND SO.SHIPPING_TYPE IN('P3','P4')
						AND SO.REJECT_REASON IS NULL
						AND SO.REJECT_REASON_1 IS NULL
						AND SO.BILLING_DATE IS NOT NULL
				)
				GROUP BY
					"SOURCE"
					,DATE_REF
					,YYYYWW
					,YYYYMM
					,YYYYQQ
					,SUBSIDIARY
					,CHANNEL
					,SUB_CHANNEL
					,SALES_CHANNEL_ATTR_1
					,SALES_CHANNEL_ATTR_2
					,SKU
					,PDROD_DIVISION
					,PDROD_PRODUCT_GROUP
					,PDROD_PRODUCT
					,PROD_ATTB_1
					,SEDA_BU_ESTORE
					,SEDA_DIVISION_ESTORE
					,SEDA_CATEGORY_ESTORE
					,SEDA_FAMILY_ESTORE
					,SEDA_DESC_ESTORE
				ORDER BY
					 "SOURCE"
					,DATE_REF
				;
			END IF;
			
			/*****************************************************************
				GI
			*****************************************************************/		
			-- CASO A DATA DA ULTIMA INGESTION NA OUTBOUND SEJA MAIOR QUE A DATA DE PROCESSAMENTO DE GI
			IF (
				(
					SELECT MAX(LOAD_DATE) AS OUTBOUND_LOAD_DATE
					FROM OW_LAO.ODS_NERP_ZLLEJ50090_OUTBOUND_TRACKING
				) > 
				(
					SELECT -- PEGA ULTIMA ATUALIZAÇÃO DE CADA PROCESSO
						MAX(KPI_LAST_UPDATE) AS GI_UPDATED
					FROM OW_LAO.TF_D2C_NERP_DAILY_SALES_KPI
					WHERE "SOURCE" = 'GI'
				) OR (SELECT COUNT('') FROM OW_LAO.TF_D2C_NERP_DAILY_SALES_KPI WHERE "SOURCE" = 'GI') = 0
			)
			THEN
				SELECT TRUE INTO v_UPDATE FROM DUMMY;
				
				-- APAGA DADOS DE GI
				DELETE FROM OW_LAO.TF_D2C_NERP_DAILY_SALES_KPI
				WHERE SOURCE = 'GI';
				
				-- INSERE DADOS DE GI
				INSERT INTO OW_LAO.TF_D2C_NERP_DAILY_SALES_KPI(
					"SOURCE"
					,DATE_REF
					,YYYYWW
					,YYYYMM
					,YYYYQQ
					,SUBSIDIARY
					,CHANNEL
					,SUB_CHANNEL
					,SALES_CHANNEL_ATTR_1
					,SALES_CHANNEL_ATTR_2
					,SKU
					,PDROD_DIVISION
					,PDROD_PRODUCT_GROUP
					,PDROD_PRODUCT
					,PROD_ATTB_1
					,SEDA_BU_ESTORE
					,SEDA_DIVISION_ESTORE
					,SEDA_CATEGORY_ESTORE
					,SEDA_FAMILY_ESTORE
					,SEDA_DESC_ESTORE
					,QTY
					,AMOUNT_LOCAL
					,AMOUNT_USD
					,STATUS_PO
					,KPI_LAST_UPDATE
				)
				-- GI (OUTBOUND {1ST_GI_DATE})
				SELECT
					'GI' AS SOURCE
					,OB."1ST_GI_DATE" AS DATE_REF --	9 Calendar "SO create on"	
					,CGI.YYYYWW AS YYYYWW_GI
					,CGI.YYYYMM AS YYYYMM_GI
					,CGI.YYYYQQ AS YYYYQQ_GI 
					,CASE WHEN SO.SALES_ORG = '8201' THEN 'SEDA' ELSE 'OTHERS' END AS SUBSIDIARY --	1	Subsidiary
					,CH.CHANNEL --	2 Channel
					,CH.SUB_CHANNEL --	3 Sub Channel
					,CH.SALES_CHANNEL_ATTR_1 --	4 Ch. Attb 1
					,CH.SALES_CHANNEL_ATTR_2 --	5 Ch. Attb 2
					,SO.MATERIAL AS SKU
					,PD."DIVISION" AS PDROD_DIVISION --	6	Division
					,PD.PRODUCT_GROUP_1 AS PDROD_PRODUCT_GROUP -- 7	Product Group
					,PD.PRODUCT_1 AS PDROD_PRODUCT -- 8	Product
					,PD.ATTB01 AS PROD_ATTB_1
					,PD.SEDA_BU_ESTORE
					,PD.SEDA_DIVISION_ESTORE
					,PD.SEDA_CATEGORY_ESTORE
					,PD.SEDA_FAMILY_ESTORE
					,PD.SEDA_DESC_ESTORE
					,SUM(CAST(SUBSTR(OB."1ST_GI_QTY", 1, LENGTH(OB."1ST_GI_QTY") - 2) AS INTEGER)) AS QTY
					,SUM(CAST(REPLACE(OB.NET_VALUE, ',', '') AS DECIMAL(18,2))) AS AMOUNT_LOCAL
					,SUM(CAST(
						(REPLACE(OB.NET_VALUE, ',', '') / EX.EXCHANGE_RATE
					)AS DECIMAL(18,2))) AS AMOUNT_USD --  20 AS AMOUNT_USD_PAYMENT_SO -- 21 [Amount($USD)_Payment]
					,'' AS STATUS_PO
					,CURRENT_TIMESTAMP AS KPI_LAST_UPDATE
				FROM OW_LAO.ODS_NERP_ZLLEJ50090_OUTBOUND_TRACKING OB 
					LEFT JOIN OW_LAO.ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING SO
						ON 	OB.DELIVERY_NO = SO.DELIVERY
							AND OB.MATERIAL = SO.MATERIAL
							AND OB.DELIVERY_ITEM = SO.DELIVERY_ITEM
					LEFT JOIN #VTEX_SO_TMP VO ON VO.ORDER_ID = SO.CUSTOMER_PO
					LEFT JOIN OW_MD.DIM_SALES_CHANNEL CH ON VO.SALES_CHANNEL = CH.VTEX_POLICY
					LEFT JOIN OW_MD.DIM_PRODUCT PD ON SO.MATERIAL = PD.SKU
					LEFT JOIN OW_MD.DIM_CALENDAR CGI ON CGI.YYYYMMDD = TO_DATE(OB."1ST_GI_DATE") -- GI
					LEFT JOIN OW_LAO.FT_AP2_EXCHANGE_RATE EX
						ON 	EX.VALID_FROM = OB."1ST_GI_DATE"
							AND EX.TO_CURRENCY = SO.SO_CURR
							AND EX.FROM_CURRENCY = 'USD'
				WHERE
					OB.SO_TYPE = 'YS10' -- (SOMENTE D2C)
					AND OB.SALES_ORG = '8201' -- SEDA
					--AND OB.SHIPPING_TYPE  IN('P3','P4')
					AND OB.DO_TYPE = 'ZND1'
					AND OB.SO_TYPE = 'YS10'
					AND OB."1ST_GI_DATE" IS NOT NULL
				GROUP BY
					 OB."1ST_GI_DATE"
					,CGI.YYYYWW 
					,CGI.YYYYMM
					,CGI.YYYYQQ
					,CASE WHEN SO.SALES_ORG = '8201' THEN 'SEDA' ELSE 'OTHERS' END
					,CH.CHANNEL
					,CH.SUB_CHANNEL
					,CH.SALES_CHANNEL_ATTR_1
					,CH.SALES_CHANNEL_ATTR_2
					,SO.MATERIAL
					,PD."DIVISION"
					,PD.PRODUCT_GROUP_1
					,PD.PRODUCT_1
					,PD.ATTB01
					,PD.SEDA_BU_ESTORE
					,PD.SEDA_DIVISION_ESTORE
					,PD.SEDA_CATEGORY_ESTORE
					,PD.SEDA_FAMILY_ESTORE
					,PD.SEDA_DESC_ESTORE
				ORDER BY
					 DATE_REF
				;
			END IF;
			
			IF (v_UPDATE = TRUE) THEN
				UPDATE OW_LAO.TF_D2C_NERP_DAILY_SALES_KPI SET
					KPI_LAST_UPDATE = (
						SELECT -- PEGA ULTIMA ATUALIZAÇÃO PARA TODOS OS PROCESSOS
							MAX(KPI_LAST_UPDATE) AS PO_UPDATED
						FROM OW_LAO.TF_D2C_NERP_DAILY_SALES_KPI
					);
			END IF;
			
			-- APAGA TABELAS TEMPORÁRIAS
			DROP TABLE #VTEX_SO_TMP;
			--MENSAGEM
			SELECT 'TF_D2C_NERP_DAILY_SALES_KPI ATUALIZADA COM SUCESSO!' AS RESULTADO ,CURRENT_DATE AS DATE_NOW FROM dummy;
		END IF;
	END;