/***********************************************************************************************
CREATED BY : Luciano Mariani
CREATION DATE : 2023-08-01
-- CALL OW_LAO.PROC_D2C_NERP_SALES_COUPON_KPI;
SELECT TOP 100 * FROM OW_LAO.TF_D2C_NERP_SALES_COUPON_KPI
***********************************************************************************************/
CREATE PROCEDURE OW_LAO.PROC_D2C_NERP_SALES_COUPON_KPI LANGUAGE SQLSCRIPT
AS
BEGIN
	
	--APAGA TATBELA FATO TF_D2C_NERP_SALES_COUPON_KPI
	IF EXISTS(
		SELECT TABLE_NAME
		FROM SYS.TABLES
		WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TF_D2C_NERP_SALES_COUPON_KPI'
	)
	THEN
		DROP TABLE OW_LAO.TF_D2C_NERP_SALES_COUPON_KPI;
	END IF;
	
	--CRIA NOVA TATBELA FATO TF_D2C_NERP_SALES_REWARDS_KPI
	CREATE COLUMN TABLE OW_LAO.TF_D2C_NERP_SALES_COUPON_KPI AS (
			SELECT
				  NS."SOURCE"
				, NS.DATE_REF
				, NS.YYYYWW
				, NS.YYYYMM
				, NS.YYYYQQ
				, NS.SUBSIDIARY
				, NS.CHANNEL_TYPE
				, NS.SKU
				, NS.PDROD_DIVISION
				, NS.PDROD_PRODUCT_GROUP
				, NS.PDROD_PRODUCT
				, NS.PROD_ATTB_1
				, NS.SEDA_BU_ESTORE
				, NS.SEDA_CATEGORY_ESTORE
				, NS.SEDA_DESC_ESTORE
				, NS.SEDA_DIVISION_ESTORE
				, NS.SEDA_FAMILY_ESTORE
				, NS.STATUS_PO
				-- AFFILIATE
				, NS.AFFILIATE_CHANNEL
				, NS.AFFILIATE_SUB_CHANNEL
				, NS.AFFILIATE_PARTNER_LEVEL
				, NS.GLOBAL_CHANNEL
				--,BIZ_TYPE
				, NS.AUDIENCE_TYPE
				, NS.COUNTRY
				, NS.CURRENCY
				, NS.MODEL_TYPE
		
				--, LOWER(NS.COUPON) AS COUPON
				, UPPER(SUBSTR_REGEXPR( '([-])([^-]*)(?=-)' IN CONCAT(CONCAT('-', NS.COUPON),'-') OCCURRENCE 1 GROUP 2)) AS COUPON 
				, NS.COUPON AS COUPON_ORIGINAL
				/***********
				, LOWER(NS.CASE
					WHEN 
						UPPER(COUPON) LIKE '%REW%'
						OR UPPER(COUPON) LIKE '%RWD%'
					THEN 'REWARDS'					
					WHEN 
						UPPER(COUPON) LIKE '%LIVE%'
					THEN 'LIVE'
					WHEN 
						UPPER(COUPON) LIKE '%BLUE%'
					THEN 'BLUE'
					WHEN 
						UPPER(COUPON) LIKE '%GALAXYWATCH%'
						OR UPPER(COUPON) LIKE '%GALAXYBUDS%'
						OR UPPER(COUPON) LIKE '%GALAXYTAB%'
						OR UPPER(COUPON) LIKE '%GALAXYBOOK%'
						OR UPPER(COUPON) LIKE '%LPREWARDS%'
					THEN 'REWARDS'
				ELSE 'OTHERS' END) --AS "COUPON_FILTER"
				***********/	
				
				, SUM(NS.QTY) AS QTY
				, SUM(NS.AMOUNT_LOCAL) AS AMOUNT_LOCAL
				, SUM(NS.AMOUNT_USD) AS AMOUNT_USD
				, CURRENT_TIMESTAMP AS KPI_LAST_UPDATE --,KPI_LAST_UPDATE
			FROM OW_LAO.TF_D2C_NERP_SALES NS
			WHERE "SOURCE" = 'PO'
				AND STATUS_PO NOT IN('cancel','canceled')
			GROUP BY
				  "SOURCE"
				, NS.DATE_REF
				, NS.YYYYWW
				, NS.YYYYMM
				, NS.YYYYQQ
				, NS.SUBSIDIARY
				, NS.CHANNEL_TYPE
				, NS.SKU
				, NS.PDROD_DIVISION
				, NS.PDROD_PRODUCT_GROUP
				, NS.PDROD_PRODUCT
				, NS.PROD_ATTB_1
				, NS.SEDA_BU_ESTORE
				, NS.SEDA_CATEGORY_ESTORE
				, NS.SEDA_DESC_ESTORE
				, NS.SEDA_DIVISION_ESTORE
				, NS.SEDA_FAMILY_ESTORE
				, NS.STATUS_PO
				, NS.AFFILIATE_CHANNEL
				, NS.AFFILIATE_SUB_CHANNEL
				, NS.AFFILIATE_PARTNER_LEVEL
				, NS.GLOBAL_CHANNEL
				--,BIZ_TYPE
				, NS.AUDIENCE_TYPE
				, NS.COUNTRY
				, NS.CURRENCY
				, NS.MODEL_TYPE
				--, LOWER(NS.COUPON) -- AS COUPON
				, UPPER(SUBSTR_REGEXPR( '([-])([^-]*)(?=-)' IN CONCAT(CONCAT('-', NS.COUPON),'-') OCCURRENCE 1 GROUP 2)) --AS COUPON
				, NS.COUPON
	);
	UPDATE OW_LAO.TF_D2C_NERP_SALES_COUPON_KPI SET
		KPI_LAST_UPDATE = (
				SELECT MAX(PO_CREATION_DATE)
				FROM OW_LAO.TF_D2C_NERP_SALES
				WHERE "SOURCE" = 'PO'
					AND SUBSIDIARY = 'SEDA'
			  )
	;
	
END