/***********************************************************************************************
ALTER BY : LUCIANO MARIANI
CREATION DATE : 2023-11-14
-- CALL OW_LAO.PROC_D2C_VTEX_PROMOTION( ADD_DAYS(CURRENT_TIMESTAMP, -1),  ADD_DAYS(CURRENT_TIMESTAMP, 1))
***********************************************************************************************/
CREATE PROCEDURE OW_LAO.PROC_D2C_VTEX_PROMOTION (
	 p_DATE_INI DATE DEFAULT NULL
	,P_DATE_FIM DATE DEFAULT NULL
) LANGUAGE SQLSCRIPT
AS
BEGIN
	
	/*********************************************************
	* DECLARAÇÃO DE VARIAVEIS E CURSOR
	* *******************************************************/
	DECLARE v_ORDER_ID VARCHAR(80); 
	DECLARE v_SKU_ID VARCHAR(80);
	DECLARE v_SKU_ID_COMPONENT VARCHAR(80);
	DECLARE v_PRICE_TAGS VARCHAR(5000);
	DECLARE v_PRICE_TAGS_ORIGIN VARCHAR(5000);	
	DECLARE v_PRICE_TAGS_EPP VARCHAR(5000);
	DECLARE v_PRICE_TAGS_SSGBR VARCHAR(5000);
	DECLARE v_PRICE_TAGS_B2B VARCHAR(5000);
	DECLARE v_REF_ID_COUNT INTEGER;
	DECLARE v_PRICE_TAGS_INSTANCES NVARCHAR(10000);
	DECLARE CURSOR c_select FOR 
		SELECT ORDER_ID
			, SKU_ID
			, SKU_ID_COMPONENT
			, REF_ID_COUNT
			, PRICE_TAGS
			, PRICE_TAGS_ORIGIN	
			, PRICE_TAGS_EPP
			, PRICE_TAGS_SSGBR
			, PRICE_TAGS_B2B
		FROM OW_LAO.TMP_PO_VTEX_PROMOTION;
	-- OBS PRECISA CRIAR A TABELA OW_LAO.TMP_PO_VTEX_PROMOTION PARA PODER CRIAR A PROC
	
	/*********************************************************
	* CRIA A TMP_PARAMETER_VTEX_PROMOTION
	* *******************************************************/
	IF EXISTS ( SELECT TABLE_NAME FROM SYS.TABLES WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TMP_PARAMETER_VTEX_PROMOTION' ) THEN
		DROP TABLE OW_LAO.TMP_PARAMETER_VTEX_PROMOTION;
	END IF ;
	CREATE COLUMN TABLE OW_LAO.TMP_PARAMETER_VTEX_PROMOTION AS (
		SELECT ADD_DAYS(CURRENT_TIMESTAMP, -1) AS DATE_INI, ADD_DAYS(CURRENT_TIMESTAMP, 1) AS DATE_FIM FROM DUMMY
	);
	UPDATE OW_LAO.TMP_PARAMETER_VTEX_PROMOTION SET
		 DATE_INI = IFNULL(p_DATE_INI, ADD_DAYS(CURRENT_TIMESTAMP, -1))
		,DATE_FIM = IFNULL(P_DATE_FIM, ADD_DAYS(CURRENT_TIMESTAMP, 1)) 
	;
	
	 /*********************************************************
	 * CRIA TEMP CUSTOMER_PO E FAZ FILTRO
	 * CRIA TMP_PO_ORDER_ID_PO_VTEX_PROMOTION E ( FAZ O CORTE DO PERIODO CLASSIFICA O CUSTOMER_PO E E AGRUPA AS ORDERS)
	 * *******************************************************/	
	IF EXISTS ( SELECT TABLE_NAME FROM SYS.TABLES WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TMP_PO_ORDER_ID_PO_VTEX_PROMOTION' ) THEN
		DROP TABLE OW_LAO.TMP_PO_ORDER_ID_PO_VTEX_PROMOTION;
	END IF;
	CREATE COLUMN TABLE OW_LAO.TMP_PO_ORDER_ID_PO_VTEX_PROMOTION AS (
		SELECT DISTINCT
			  LI.ORDER_ID
			, LI.CUSTOMER_PO
		FROM (
				SELECT V.ORDER_ID
					, MAX( CASE WHEN S.CUSTOMER_PO IS NOT NULL THEN S.CUSTOMER_PO ELSE CAST(V."SEQUENCE" AS VARCHAR(100)) END ) AS CUSTOMER_PO
					, MAX(V.UPDATED_AT) AS UPDATED_AT 
				FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER V 
					LEFT JOIN OW_LAO.ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING S ON V.ORDER_ID = S.CUSTOMER_PO
				WHERE V.CREATION_TIMESTAMP BETWEEN ( SELECT DATE_INI FROM OW_LAO.TMP_PARAMETER_VTEX_PROMOTION ) AND (SELECT DATE_FIM FROM OW_LAO.TMP_PARAMETER_VTEX_PROMOTION )
				--WHERE V.ORDER_ID = '1520759668523-01'
				GROUP BY V.ORDER_ID
			) LI
			
			/********** BR SHOP ***********/
			INNER JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER BSO -- (BR SHOP - ORDER )
				ON BSO.ORDER_ID = LI.ORDER_ID
			INNER JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_ITEM BSI -- (BR SHOP - ITEM)
				ON BSO.ORDER_ID = BSI.ORDER_ID
				
			/********** SSG BR ***********/
			LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SALES_ORDER SSO -- (SSG BR - ORDER )
				ON BSO.MARKETPLACE_ORDER_ID = SSO.ORDER_ID
			LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SALES_ORDER_ITEM SSI -- (BR SHOP - ITEM)
				ON BSO.MARKETPLACE_ORDER_ID = SSI.ORDER_ID ----
				   AND BSI.REF_ID = CASE WHEN RIGHT(SSI.REF_ID,5) LIKE '_OUT%' THEN SUBSTRING(SSI.REF_ID, 1, LENGTH(SSI.REF_ID) - 5) ELSE SSI.REF_ID END
				   AND BSI.ITEM_INDEX = SSI.ITEM_INDEX
				   
			/********** EPP2 ***********/
			LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_EPP2_SALES_ORDER EPO --(EPP2 - ORDER)
				ON BSO.MARKETPLACE_ORDER_ID = EPO.ORDER_ID
			LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_EPP2_SALES_ORDER_ITEM EPI -- (BR SHOP - ITEM)
				ON BSO.MARKETPLACE_ORDER_ID = EPI.ORDER_ID
				   AND BSI.REF_ID = CASE WHEN RIGHT(EPI.REF_ID,5) LIKE '_OUT%' THEN SUBSTRING(EPI.REF_ID, 1, LENGTH(EPI.REF_ID) - 5) ELSE EPI.REF_ID END
				   AND BSI.ITEM_INDEX = EPI.ITEM_INDEX		
				   
			/********** B2B ***********/
			LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_B2B_SALES_ORDER B2O --(EPP2 - ORDER)
				ON BSO.MARKETPLACE_ORDER_ID = B2O.ORDER_ID
			LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_B2B_SALES_ORDER_ITEM B2I -- (BR SHOP - ITEM)
				ON BSO.MARKETPLACE_ORDER_ID = B2I.ORDER_ID
				   AND BSI.REF_ID = CASE WHEN RIGHT(B2I.REF_ID,5) LIKE '_OUT%' THEN SUBSTRING(B2I.REF_ID, 1, LENGTH(B2I.REF_ID) - 5) ELSE B2I.REF_ID END
				   AND BSI.ITEM_INDEX = B2I.ITEM_INDEX
				   
		WHERE 
			   (       ( IFNULL(B2I.PRICE_TAGS,'') NOT IN ('','[]') )
			   		OR ( IFNULL(EPI.PRICE_TAGS,'') NOT IN ('','[]') )
					OR ( IFNULL(SSI.PRICE_TAGS,'') NOT IN ('','[]') )
					OR ( IFNULL(BSI.PRICE_TAGS,'') NOT IN ('','[]') )
					-- OU PRECISA TER UM COUPON
					OR COALESCE(EPO.COUPON,SSO.COUPON,BSO.COUPON,B2O.COUPON) IS NOT NULL
				)
			AND BSO.STATUS IS NOT NULL
			AND ( CASE WHEN B2O.ORDER_ID IS NOT NULL THEN B2O.STATUS
					   WHEN EPO.ORDER_ID IS NOT NULL THEN EPO.STATUS
				       WHEN SSO.ORDER_ID IS NOT NULL THEN SSO.STATUS
				       ELSE BSO.STATUS
			      END 
			    ) IS NOT NULL
	);
	/***********************************
	-- CRIA TABELA TMP_ITEM_COMPONENTS_PO_VTEX_PROMOTION DO DISCO
	***********************************/
	IF EXISTS( SELECT TABLE_NAME FROM SYS.TABLES WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TMP_ITEM_COMPONENTS_PO_VTEX_PROMOTION') THEN
		DROP TABLE OW_LAO.TMP_ITEM_COMPONENTS_PO_VTEX_PROMOTION;
	END IF;
	CREATE COLUMN TABLE OW_LAO.TMP_ITEM_COMPONENTS_PO_VTEX_PROMOTION AS(
		SELECT --DISTINCT
			  CP.ORDER_ID
			, CP.SKU_ID
			, CP.SKU_ID_COMPONENT
			, CP.REF_ID
			, CP.NAME
			, CP.QUANTITY
			, CP.PRICE
			, CP.COST_PRICE
			, CP.SELLING_PRICE
			, ( CP.SELLING_PRICE * CP.QUANTITY ) AS SELLING_PRICE_AMOUNT
			, CAST( 0 AS DECIMAL(18,4) ) AS SELLING_PRICE_TOTAL
			, 1 AS ITEM_INDEX_COMPONENT
			, ROW_NUMBER() OVER (PARTITION BY CP.ORDER_ID, CP.SKU_ID ORDER BY CP.ORDER_ID, CP.SKU_ID, CP.SKU_ID_COMPONENT, CP.QUANTITY, ( CP.SELLING_PRICE * CP.QUANTITY )) AS ITEM_INDEX_KIT
		FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_ITEM_COMPONENTS CP
			 INNER JOIN OW_LAO.TMP_PO_ORDER_ID_PO_VTEX_PROMOTION TP ON CP.ORDER_ID = TP.ORDER_ID
		WHERE (CP.REF_ID IS NOT NULL)
	);
	
	-- ATUALIZA ITEM_INDEX_COMPONENT (PARA CASOS DE SKU_ID DUPLICADOS NOS KITS)
	UPDATE CP SET 
		  ITEM_INDEX_COMPONENT = CT.ITEM_INDEX_COMPONENT 
	FROM OW_LAO.TMP_ITEM_COMPONENTS_PO_VTEX_PROMOTION CP
		INNER JOIN (
			SELECT ORDER_ID
			    , SKU_ID
			    , SKU_ID_COMPONENT
			    , ROW_NUMBER() OVER (PARTITION BY ORDER_ID, SKU_ID ORDER BY ORDER_ID, SKU_ID) AS ITEM_INDEX_COMPONENT
			FROM (
			     SELECT DISTINCT ORDER_ID, SKU_ID, SKU_ID_COMPONENT
			     FROM OW_LAO.TMP_ITEM_COMPONENTS_PO_VTEX_PROMOTION
			)
		) CT ON  CP.ORDER_ID = CT.ORDER_ID
			    AND CP.SKU_ID = CT.SKU_ID
			    AND CP.SKU_ID_COMPONENT = CT.SKU_ID_COMPONENT
	;
	
	/*******************************
	-- ATUALIZA SELLING_PRICE_TOTAL PARA RATEIO
	*******************************/
	UPDATE TP SET TP.SELLING_PRICE_TOTAL = TT.SELLING_PRICE_TOTAL
	FROM OW_LAO.TMP_ITEM_COMPONENTS_PO_VTEX_PROMOTION TP
		INNER JOIN (
				SELECT ORDER_ID
					 , SKU_ID
					 , SUM(SELLING_PRICE_AMOUNT) AS SELLING_PRICE_TOTAL 
				FROM OW_LAO.TMP_ITEM_COMPONENTS_PO_VTEX_PROMOTION
				GROUP BY
					  ORDER_ID
					, SKU_ID				
		) TT ON TP.ORDER_ID = TT.ORDER_ID
				AND TP.SKU_ID = TT.SKU_ID
	;
	
	/***********************************
	-- CRIA TABELA ITENS SOMENTE PARA (COMPONENTS)
	***********************************/
	IF EXISTS( SELECT TABLE_NAME FROM SYS.TABLES WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TMP_ORDER_ITEM_TO_COMPONENTS_PO_VTEX_PROMOTION' ) THEN
		DROP TABLE OW_LAO.TMP_ORDER_ITEM_TO_COMPONENTS_PO_VTEX_PROMOTION;
	END IF;
	CREATE COLUMN TABLE OW_LAO.TMP_ORDER_ITEM_TO_COMPONENTS_PO_VTEX_PROMOTION AS (
		SELECT *
			, ROW_NUMBER() OVER (PARTITION BY ORDER_ID, SKU_ID ORDER BY ORDER_ID, SKU_ID) AS ITEM_INDEX_COMPONENT
			, 1 AS ITEM_INDEX_COMPONENT_COUNT -- DEFAULT 1
		FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_ITEM
		WHERE ORDER_ID IN ( SELECT DISTINCT ORDER_ID FROM OW_LAO.TMP_ITEM_COMPONENTS_PO_VTEX_PROMOTION )
	);
	
	UPDATE OW_LAO.TMP_ORDER_ITEM_TO_COMPONENTS_PO_VTEX_PROMOTION SET 
		ITEM_INDEX_COMPONENT_COUNT = 0 -- IF ORDER HAS MORE THEN 1 SAME ITEM 
	WHERE ORDER_ID IN (
			SELECT ORDER_ID	
			FROM OW_LAO.TMP_ORDER_ITEM_TO_COMPONENTS_PO_VTEX_PROMOTION
			GROUP BY ORDER_ID
			HAVING MAX(ITEM_INDEX_COMPONENT) > 1
		);
	 /*********************************************************
	 * CRIA TMP_SSG_BR_SHOP_SALES_ORDER_SHIPPING_VTEX_PROMOTION   
	 * *******************************************************/	 
	IF EXISTS( SELECT TABLE_NAME FROM SYS.TABLES WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TMP_SSG_BR_SHOP_SALES_ORDER_SHIPPING_VTEX_PROMOTION' ) THEN
		DROP TABLE OW_LAO.TMP_SSG_BR_SHOP_SALES_ORDER_SHIPPING_VTEX_PROMOTION;
	END IF ;
	CREATE COLUMN TABLE OW_LAO.TMP_SSG_BR_SHOP_SALES_ORDER_SHIPPING_VTEX_PROMOTION AS (
		-- PEGA O SELECTED_SLA
		SELECT CP.ORDER_ID
			 , CP.ITEM_INDEX
			 , MAX(JSON_VALUE('[' || CP.PICKUP_STORE_INFO || ']', '$.address.addressType')) AS ADDRESSTYPE
			 , MAX(JSON_VALUE('[' || CP.PICKUP_STORE_INFO || ']', '$.friendlyName')) AS FRIENDLYNAME
			 , MAX(CP.STATE) AS STATE
			 , MAX(CP.CITY) AS CITY
			 , MAX(CP.SELECTED_SLA) AS SELECTED_SLA
			 , STRING_AGG(CP.WAREHOUSE_ID, ' | ') AS WAREHOUSE_ID_GROUP
			 , MAX(CP.SELLING_PRICE) AS SHIPPING_PRICE
		FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_SHIPPING CP
			INNER JOIN OW_LAO.TMP_PO_ORDER_ID_PO_VTEX_PROMOTION TP ON CP.ORDER_ID = TP.ORDER_ID
		GROUP BY CP.ORDER_ID
			   , CP.ITEM_INDEX
	);
	/*********************************************************
	* CRIA TMP_PO_VTEX_PROMOTION    
	* *******************************************************/
	IF EXISTS ( SELECT TABLE_NAME FROM SYS.TABLES WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TMP_PO_VTEX_PROMOTION' ) THEN
		DROP TABLE OW_LAO.TMP_PO_VTEX_PROMOTION;
	END IF ;
	CREATE COLUMN TABLE OW_LAO.TMP_PO_VTEX_PROMOTION AS (
		SELECT
			  TO_DATE(BSO.CREATION_TIMESTAMP) AS DATE_REF
			, BSO.CREATION_TIMESTAMP AS PO_CREATION_DATE
			, BSO.AFFILIATE_ID
			, BSO.ORDER_ID
			, BSO.MARKETPLACE_ORDER_ID
			, BSO.HOSTNAME AS ENVIRONMENT
			, BSO.STATUS AS STATUS_PO 
			, CASE
				 -- CD_STORE_INFORMATION
				 WHEN ( CASE WHEN BSO.CD_STORE_INFORMATION IS NOT NULL THEN BSO.CD_STORE_INFORMATION ELSE SSO.CD_STORE_INFORMATION END ) IS NOT NULL
				 -- CD_STORE_INFORMATION
				 THEN ( CASE WHEN BSO.CD_STORE_INFORMATION IS NOT NULL THEN BSO.CD_STORE_INFORMATION ELSE SSO.CD_STORE_INFORMATION END )
				 -- UTM_SOURCE
				 ELSE ( CASE WHEN BSO.UTM_SOURCE IS NOT NULL THEN BSO.UTM_SOURCE ELSE SSO.UTM_SOURCE END )
			  END AS STORE_ID
			, BSO.SALES_CHANNEL
			, CASE 
				WHEN BSO.CD_VENDEDOR IS NOT NULL THEN BSO.CD_VENDEDOR
				WHEN SSO.CD_VENDEDOR IS NOT NULL THEN SSO.CD_VENDEDOR
			  END AS STORE_EMPLOYEE_CPF
			, LI.CUSTOMER_PO
			, BSI.ITEM_INDEX
			, '' AS REFERENCE_CODE_KIT -- NULO PARA ITEM POIS NÃO É KIT
			, BSI.REF_ID AS REFERENCE_CODE -- não é kit (item)
			, BSI.NAME AS ITEM_NAME
			  
			, COALESCE( B2I.SKU_ID , EPI.SKU_ID ,SSI.SKU_ID ,BSI.SKU_ID) AS SKU_ID -- não é kit (item)
			, NULL AS SKU_ID_COMPONENT -- NULO POIS NÃO É KIT
			
			--, IFNULL(IFNULL(EPO.COUPON,SSO.COUPON),BSO.COUPON) AS COUPON
			, COALESCE( B2O.COUPON, EPO.COUPON, SSO.COUPON, BSO.COUPON) AS COUPON
			  
			, CASE -- NETE PROCESSO ESPECIFICO  RETORNA PRIMEIRO BR SHOP E AS INSTANCIAS CASO BR SHOP FIQUE NULO 
				  WHEN IFNULL(BSI.PRICE_TAGS,'') NOT IN ('','[]') THEN BSI.PRICE_TAGS
				  WHEN IFNULL(B2I.PRICE_TAGS,'') NOT IN ('','[]') THEN B2I.PRICE_TAGS
				  WHEN IFNULL(EPI.PRICE_TAGS,'') NOT IN ('','[]') THEN EPI.PRICE_TAGS
				  WHEN IFNULL(SSI.PRICE_TAGS,'') NOT IN ('','[]') THEN SSI.PRICE_TAGS
			  END
			  AS PRICE_TAGS
			  			 
			, CASE -- NETE PROCESSO ESPECIFICO  RETORNA PRIMEIRO BR SHOP E AS INSTANCIAS CASO BR SHOP FIQUE NULO
				  WHEN IFNULL(BSI.PRICE_TAGS,'') NOT IN ('','[]') THEN 'BRSHOP'
				  WHEN IFNULL(B2I.PRICE_TAGS,'') NOT IN ('','[]') THEN 'B2B'
				  WHEN IFNULL(EPI.PRICE_TAGS,'') NOT IN ('','[]') THEN 'EPP2'
				  WHEN IFNULL(SSI.PRICE_TAGS,'') NOT IN ('','[]') THEN 'SSGBR'
			  END
			  AS PRICE_TAGS_ORIGIN
			  
			, EPI.PRICE_TAGS AS PRICE_TAGS_EPP
			, SSI.PRICE_TAGS AS PRICE_TAGS_SSGBR
			, B2I.PRICE_TAGS AS PRICE_TAGS_B2B
			, ROW_NUMBER () OVER ( ORDER BY BSI.REF_ID ) AS REF_ID_COUNT -- Não é KIT
			
			, CAST((
					( BSI.SELLING_PRICE * BSI.QUANTITY) 
					  + IFNULL(SP.SHIPPING_PRICE,0) -- FRETE SOMA O FRETE
			  ) / 100
			  AS DECIMAL(18,4)) AS SELLING_AMOUNT_LOCAL
			  
			, NULL AS ITEM_INDEX_KIT	
			
		FROM OW_LAO.TMP_PO_ORDER_ID_PO_VTEX_PROMOTION LI -- (LISTA DE ALTERAÇÕES E INSERÇÕES)
		
			/********** BR SHOP  ***********/
			INNER JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER BSO -- (BR SHOP - ORDER )
				ON BSO.ORDER_ID = LI.ORDER_ID
			INNER JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_ITEM BSI -- (BR SHOP - ITEM)
				ON BSO.ORDER_ID = BSI.ORDER_ID
			LEFT JOIN OW_LAO.TMP_ITEM_COMPONENTS_PO_VTEX_PROMOTION BSC -- (BR SHOP - COMPONENTES) [NÃO DEVE TER COMPONENTS POR ISSO LEFT]
				ON BSI.ORDER_ID = BSC.ORDER_ID
				AND BSI.SKU_ID = BSC.SKU_ID
			
			LEFT JOIN OW_LAO.TMP_SSG_BR_SHOP_SALES_ORDER_SHIPPING_VTEX_PROMOTION SP -- SHIPPING
				ON BSI.ORDER_ID = SP.ORDER_ID 
				   AND BSI.ITEM_INDEX = SP.ITEM_INDEX				
			
			/********** SSG BR  ***********/
			LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SALES_ORDER SSO -- (SSG BR - ORDER )
				ON BSO.MARKETPLACE_ORDER_ID = SSO.ORDER_ID
			LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SALES_ORDER_ITEM SSI -- (BR SHOP - ITEM)
				ON BSO.MARKETPLACE_ORDER_ID = SSI.ORDER_ID
				   AND BSI.REF_ID = CASE WHEN RIGHT(SSI.REF_ID,5) LIKE '_OUT%' THEN SUBSTRING(SSI.REF_ID, 1, LENGTH(SSI.REF_ID) - 5) ELSE SSI.REF_ID END
				   AND BSI.ITEM_INDEX = SSI.ITEM_INDEX
				   
			/********** EPP2  ***********/
			LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_EPP2_SALES_ORDER EPO --(EPP2 - ORDER)
				ON BSO.MARKETPLACE_ORDER_ID = EPO.ORDER_ID
			LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_EPP2_SALES_ORDER_ITEM EPI -- (BR SHOP - ITEM)
				ON BSO.MARKETPLACE_ORDER_ID = EPI.ORDER_ID
				   AND BSI.REF_ID = CASE WHEN RIGHT(EPI.REF_ID,5) LIKE '_OUT%' THEN SUBSTRING(EPI.REF_ID, 1, LENGTH(EPI.REF_ID) - 5) ELSE EPI.REF_ID END
				   AND BSI.ITEM_INDEX = EPI.ITEM_INDEX
			
			/********** B2B ***********/
			LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_B2B_SALES_ORDER B2O --(EPP2 - ORDER)
				ON BSO.MARKETPLACE_ORDER_ID = B2O.ORDER_ID
			LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_B2B_SALES_ORDER_ITEM B2I -- (BR SHOP - ITEM)
				ON BSO.MARKETPLACE_ORDER_ID = B2I.ORDER_ID
				   AND BSI.REF_ID = CASE WHEN RIGHT(B2I.REF_ID,5) LIKE '_OUT%' THEN SUBSTRING(B2I.REF_ID, 1, LENGTH(B2I.REF_ID) - 5) ELSE B2I.REF_ID END
				   AND BSI.ITEM_INDEX = B2I.ITEM_INDEX
		WHERE BSC.REF_ID IS NULL -- NÃO DEVE TER COMPONENTS
			AND BSI.QUANTITY IS NOT NULL
			AND BSI.PRICE IS NOT NULL
	
		/*****************************************************************
		 *  PO (VTEX-[SOMENTE COMPONENTES] {CREATION_TIMESTAMP}) 
		******************************************************************/
		UNION ALL
		SELECT 
			  TO_DATE(BSO.CREATION_TIMESTAMP) AS DATE_REF
			, BSO.CREATION_TIMESTAMP AS PO_CREATION_DATE
			, BSO.AFFILIATE_ID
			, BSO.ORDER_ID
			, BSO.MARKETPLACE_ORDER_ID
			, BSO.HOSTNAME AS ENVIRONMENT
			, BSO.STATUS AS STATUS_PO
			, CASE
				 -- CD_STORE_INFORMATION
				 WHEN ( CASE WHEN BSO.CD_STORE_INFORMATION IS NOT NULL THEN BSO.CD_STORE_INFORMATION ELSE SSO.CD_STORE_INFORMATION END ) IS NOT NULL
				 -- CD_STORE_INFORMATION
				 THEN ( CASE WHEN BSO.CD_STORE_INFORMATION IS NOT NULL THEN BSO.CD_STORE_INFORMATION ELSE SSO.CD_STORE_INFORMATION END )
				 -- UTM_SOURCE
				 ELSE ( CASE WHEN BSO.UTM_SOURCE IS NOT NULL THEN BSO.UTM_SOURCE ELSE SSO.UTM_SOURCE END )
			  END AS STORE_ID
			, BSO.SALES_CHANNEL
			
			, CASE 	
				WHEN BSO.CD_VENDEDOR IS NOT NULL THEN BSO.CD_VENDEDOR
				WHEN SSO.CD_VENDEDOR IS NOT NULL THEN SSO.CD_VENDEDOR
			  END AS STORE_EMPLOYEE_CPF
			  
			, LI.CUSTOMER_PO
			, BSI.ITEM_INDEX
			, BSI.REF_ID AS REFERENCE_CODE_KIT
			, BSC.REF_ID AS REFERENCE_CODE -- é kit (components)
			, BSC.NAME AS ITEM_NAME
			
			, COALESCE( B2I.SKU_ID, EPI.SKU_ID, SSI.SKU_ID, BSI.SKU_ID ) AS SKU_ID 
			, BSC.SKU_ID_COMPONENT AS SKU_ID_COMPONENT
			, COALESCE(B2O.COUPON, EPO.COUPON, SSO.COUPON, BSO.COUPON) AS COUPON
			
			--, IFNULL(IFNULL(EPI.PRICE_TAGS, SSI.PRICE_TAGS), BSI.PRICE_TAGS) AS PRICE_TAGS			
			, CASE -- NETE PROCESSO ESPECIFICO  RETORNA PRIMEIRO BR SHOP E AS INSTANCIAS CASO BR SHOP FIQUE NULO 
				  WHEN IFNULL(BSI.PRICE_TAGS,'') NOT IN ('','[]') THEN BSI.PRICE_TAGS
				  WHEN IFNULL(B2I.PRICE_TAGS,'') NOT IN ('','[]') THEN B2I.PRICE_TAGS 
				  WHEN IFNULL(EPI.PRICE_TAGS,'') NOT IN ('','[]') THEN EPI.PRICE_TAGS
				  WHEN IFNULL(SSI.PRICE_TAGS,'') NOT IN ('','[]') THEN SSI.PRICE_TAGS
			  END			
			  AS PRICE_TAGS
			 
			, CASE -- NETE PROCESSO ESPECIFICO  RETORNA PRIMEIRO BR SHOP E AS INSTANCIAS CASO BR SHOP FIQUE NULO				
				  WHEN IFNULL(BSI.PRICE_TAGS,'') NOT IN ('','[]') THEN 'BRSHOP'
				  WHEN IFNULL(B2I.PRICE_TAGS,'') NOT IN ('','[]') THEN 'B2B'
				  WHEN IFNULL(EPI.PRICE_TAGS,'') NOT IN ('','[]') THEN 'EPP2'
				  WHEN IFNULL(SSI.PRICE_TAGS,'') NOT IN ('','[]') THEN 'SSGBR'
			  END
			  AS PRICE_TAGS_ORIGIN
			 
			, EPI.PRICE_TAGS AS PRICE_TAGS_EPP
			, SSI.PRICE_TAGS AS PRICE_TAGS_SSGBR
			, B2I.PRICE_TAGS AS PRICE_TAGS_B2B
			, ROW_NUMBER () OVER ( ORDER BY BSC.REF_ID ) AS REF_ID_COUNT -- é KIT
			
			/****************************
			, CAST(( ( BSC.SELLING_PRICE * (BSC.QUANTITY * BSI.QUANTITY) ) 
					  + IFNULL(CASE WHEN BSC.SELLING_PRICE_TOTAL > 0 THEN 
										 (SP.SHIPPING_PRICE * ( BSC.SELLING_PRICE_AMOUNT / BSC.SELLING_PRICE_TOTAL) ) 
							   END ,0) -- FRETE SOMA O FRETE
			  ) / 100
			  AS DECIMAL(18,4)) AS SELLING_AMOUNT_LOCAL
			**************************/  
			
			-- ************* SELLING PRICE *************
			--, CAST(( IFNULL(CASE WHEN BSC.SELLING_PRICE_TOTAL > 0 THEN 
			--		  	              (SP.SHIPPING_PRICE * ( BSC.SELLING_PRICE_AMOUNT / BSC.SELLING_PRICE_TOTAL) ) 
			--		  	       END ,0)
			--) / 100 AS DECIMAL(18,4)) AS SELLING_AMOUNT_SHIPPING -- FRETE NOVO
			
			, CAST(( ( BSC.SELLING_PRICE * (BSC.QUANTITY * BSI.QUANTITY) ) 
					  + IFNULL(CASE WHEN BSC.SELLING_PRICE_TOTAL > 0 THEN 
					  	                 (SP.SHIPPING_PRICE * ( BSC.SELLING_PRICE_AMOUNT / BSC.SELLING_PRICE_TOTAL) ) 
					  	       END ,0) -- FRETE SOMA O FRETE
			  ) / 100
			  AS DECIMAL(18,4)) AS SELLING_AMOUNT_LOCAL
			  
			, BSC.ITEM_INDEX_KIT
		FROM OW_LAO.TMP_PO_ORDER_ID_PO_VTEX_PROMOTION LI -- (LISTA DE ALTERAÇÕES E INSERÇÕES)
			
			/********** BR SHOP  ***********/
			INNER JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER BSO -- (BR SHOP - ORDER )
				ON BSO.ORDER_ID = LI.ORDER_ID
			
			--INNER JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_ITEM BSI -- (BR SHOP - ITEM)
			--	ON BSO.ORDER_ID = BSI.ORDER_ID
			INNER JOIN OW_LAO.TMP_ORDER_ITEM_TO_COMPONENTS_PO_VTEX_PROMOTION BSI -- (BR SHOP - ITEM)
				ON BSO.ORDER_ID = BSI.ORDER_ID	
				
			-- INNER JOIN OW_LAO.TMP_ITEM_COMPONENTS_PO_VTEX_PROMOTION BSC -- (BR SHOP - COMPONENTES) [NÃO DEVE TER COMPONENTS POR ISSO LEFT]
			--	ON BSI.ORDER_ID = BSC.ORDER_ID
			--	   AND BSI.SKU_ID = BSC.SKU_ID
			INNER JOIN OW_LAO.TMP_ITEM_COMPONENTS_PO_VTEX_PROMOTION BSC -- (VTEX COMPONENTES) [TEM SOMENTE COMPONENTS POR ISSO INNER]
				ON BSI.ORDER_ID = BSC.ORDER_ID 
				   AND BSI.SKU_ID = BSC.SKU_ID
				   AND  ( 
				   		 	BSI.ITEM_INDEX_COMPONENT_COUNT = 1 
				   		 	OR BSI.ITEM_INDEX_COMPONENT = BSC.ITEM_INDEX_COMPONENT
				   		)
			LEFT JOIN OW_LAO.TMP_SSG_BR_SHOP_SALES_ORDER_SHIPPING_VTEX_PROMOTION SP -- SHIPPING
				ON BSI.ORDER_ID = SP.ORDER_ID 
				   AND BSI.ITEM_INDEX = SP.ITEM_INDEX				
			 
			/********** SSG BR  ***********/
			LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SALES_ORDER SSO -- (SSG BR - ORDER )
				ON BSO.MARKETPLACE_ORDER_ID = SSO.ORDER_ID
			LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SALES_ORDER_ITEM SSI -- (BR SHOP - ITEM)
				ON BSO.MARKETPLACE_ORDER_ID = SSI.ORDER_ID ----
				   AND BSI.REF_ID = --SSI.REF_ID
							     CASE WHEN RIGHT(SSI.REF_ID,5) LIKE '_OUT%' THEN SUBSTRING(SSI.REF_ID, 1, LENGTH(SSI.REF_ID) - 5) ELSE SSI.REF_ID END
				   AND BSI.ITEM_INDEX = SSI.ITEM_INDEX
			   
			/********** EPP2  ***********/
			LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_EPP2_SALES_ORDER EPO --(EPP2 - ORDER)
				ON BSO.MARKETPLACE_ORDER_ID = EPO.ORDER_ID
			LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_EPP2_SALES_ORDER_ITEM EPI -- (BR SHOP - ITEM)
				ON BSO.MARKETPLACE_ORDER_ID = EPI.ORDER_ID
				   AND BSI.REF_ID = --EPI.REF_ID
								 CASE WHEN RIGHT(EPI.REF_ID,5) LIKE '_OUT%' THEN SUBSTRING(EPI.REF_ID, 1, LENGTH(EPI.REF_ID) - 5) ELSE EPI.REF_ID END
				   AND BSI.ITEM_INDEX = EPI.ITEM_INDEX
			
			/********** B2B ***********/
			LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_B2B_SALES_ORDER B2O --(EPP2 - ORDER)
				ON BSO.MARKETPLACE_ORDER_ID = B2O.ORDER_ID
			LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_B2B_SALES_ORDER_ITEM B2I -- (BR SHOP - ITEM)
				ON BSO.MARKETPLACE_ORDER_ID = B2I.ORDER_ID
				   AND BSI.REF_ID = CASE WHEN RIGHT(B2I.REF_ID,5) LIKE '_OUT%' THEN SUBSTRING(B2I.REF_ID, 1, LENGTH(B2I.REF_ID) - 5) ELSE B2I.REF_ID END
				   AND BSI.ITEM_INDEX = B2I.ITEM_INDEX
			
		WHERE BSC.REF_ID IS NOT NULL -- SOMENTE COMPONENTS
			AND BSC.QUANTITY IS NOT NULL
			AND BSC.PRICE IS NOT NULL	
	);
	/*********************************************************
	* CRIA A TMP_JSON_VTEX_PROMOTION
	* PARA TRATA UMA LIMITAÇÃO DO JSON_TABLE NO HANA QUE NÃO POSSIBILITA 
	* A LEITURA DE TABELA GRANDE DEMAIS (ACIMA 81.702 REGISTROS) 
	* *******************************************************/
	IF EXISTS ( SELECT TABLE_NAME FROM SYS.TABLES WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TMP_JSON_VTEX_PROMOTION') THEN
		DROP TABLE OW_LAO.TMP_JSON_VTEX_PROMOTION;
	END IF ;
	CREATE COLUMN TABLE OW_LAO.TMP_JSON_VTEX_PROMOTION AS (
		--WITH PVP AS ( SELECT PRICE_TAGS FROM OW_LAO.TMP_PO_VTEX_PROMOTION )
		SELECT *
			, CAST(NULL AS INTEGER) AS PRC_TAG_COUNT
			, CAST(NULL AS INTEGER) AS REF_ID_COUNT
			, CAST(NULL AS VARCHAR(8000)) AS ORDER_ID
			, CAST(NULL AS VARCHAR(8000)) AS SKU_ID
			, CAST(NULL AS VARCHAR(8000)) AS SKU_ID_COMPONENT
		FROM JSON_TABLE( OW_LAO.TMP_PO_VTEX_PROMOTION.PRICE_TAGS,'$'
			/******
			COLUMNS (
		        ORDER_ID NVARCHAR(10000) PATH '$.ORDER_ID',
		        SKU_ID NVARCHAR(10000) PATH '$.SKU_ID',
		        SKU_ID_COMPONENT  NVARCHAR(10000) PATH '$.SKU_ID_COMPONENT',
		        NESTED PATH '$.promotions[*]' 
		    ************/
		        COLUMNS ( 
					name NVARCHAR(10000) PATH '$.name',
					value NVARCHAR(10000) PATH '$.value',
					isPercentual NVARCHAR(10000) PATH '$.isPercentual',
					ID_CALCULATOR_CONFIGURATION NVARCHAR(10000) PATH '$.identifier',
					rawValue NVARCHAR(10000) PATH '$.rawValue',
					rate NVARCHAR(10000) PATH '$.rate',
					jurisCode NVARCHAR(10000) PATH '$.jurisCode',
					jurisType NVARCHAR(10000) PATH '$.jurisType',
					jurisName NVARCHAR(10000) PATH '$.jurisName'
			 	)
			--)
		)
	);
	/*********************************************************
	* CRIA A TMP_JSON_VTEX_PROMOTION_INSTANCES
	* *******************************************************/
	IF EXISTS ( SELECT TABLE_NAME FROM SYS.TABLES WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TMP_JSON_VTEX_PROMOTION_INSTANCES' ) THEN
		DROP TABLE OW_LAO.TMP_JSON_VTEX_PROMOTION_INSTANCES;
	END IF ;
    CREATE TABLE OW_LAO.TMP_JSON_VTEX_PROMOTION_INSTANCES (
		  name NVARCHAR(5000)
		, value NVARCHAR(5000)
		, isPercentual NVARCHAR(5000)
		, ID_CALCULATOR_CONFIGURATION NVARCHAR(5000)
		, rawValue NVARCHAR(5000)
		, rate NVARCHAR(5000)
		, jurisCode NVARCHAR(5000)
		, jurisType NVARCHAR(5000)
		, jurisName NVARCHAR(5000)
 	);
	
	/****************************************************************************************
	-- EXECUTA CURSOR
	****************************************************************************************/
	FOR cursorRow as c_select DO
		
		v_PRICE_TAGS := cursorRow.PRICE_TAGS;
		v_PRICE_TAGS_ORIGIN := cursorRow.PRICE_TAGS_ORIGIN;
		v_PRICE_TAGS_EPP := cursorRow.PRICE_TAGS_EPP;
		v_PRICE_TAGS_SSGBR := cursorRow.PRICE_TAGS_SSGBR;
		v_PRICE_TAGS_B2B := cursorRow.PRICE_TAGS_B2B;
	
		v_ORDER_ID := cursorRow.ORDER_ID;
		v_SKU_ID := cursorRow.SKU_ID;
		v_SKU_ID_COMPONENT := cursorRow.SKU_ID_COMPONENT;
		v_REF_ID_COUNT := cursorRow.REF_ID_COUNT;
	
		-- LIMPA VARIAVEL TABLE 
		DELETE FROM OW_LAO.TMP_JSON_VTEX_PROMOTION_INSTANCES;
	
		-- VERIFICA SE TEM PRICE TAGS NAS INSTANCIAS 
		v_PRICE_TAGS_INSTANCES :=
				CASE
				   WHEN IFNULL(v_PRICE_TAGS_B2B,'') NOT IN ('','[]') AND v_PRICE_TAGS_ORIGIN <> 'B2B' THEN v_PRICE_TAGS_B2B
				   WHEN IFNULL(v_PRICE_TAGS_EPP,'') NOT IN ('','[]') AND v_PRICE_TAGS_ORIGIN <> 'EPP' THEN v_PRICE_TAGS_EPP
				   WHEN IFNULL(v_PRICE_TAGS_SSGBR,'') NOT IN ('','[]') AND v_PRICE_TAGS_ORIGIN <> 'SSGBR' THEN v_PRICE_TAGS_SSGBR
				END;
		
		-- PREENCHE TABELA INSTANCIA CASO TENHA
		IF ( :v_PRICE_TAGS_INSTANCES IS NOT NULL) THEN
			INSERT INTO OW_LAO.TMP_JSON_VTEX_PROMOTION_INSTANCES 
			SELECT *
			FROM JSON_TABLE( :v_PRICE_TAGS_INSTANCES,'$'
		        COLUMNS ( 
					name NVARCHAR(5000) PATH '$.name',
					value NVARCHAR(5000) PATH '$.value',
					isPercentual NVARCHAR(5000) PATH '$.isPercentual',
					ID_CALCULATOR_CONFIGURATION NVARCHAR(5000) PATH '$.identifier',
					rawValue NVARCHAR(5000) PATH '$.rawValue',
					rate NVARCHAR(5000) PATH '$.rate',
					jurisCode NVARCHAR(5000) PATH '$.jurisCode',
					jurisType NVARCHAR(5000) PATH '$.jurisType',
					jurisName NVARCHAR(5000) PATH '$.jurisName'
			 	)
			 );
		END IF;
		
		-- insere json na tabela
		INSERT INTO OW_LAO.TMP_JSON_VTEX_PROMOTION 
		SELECT
			  CASE WHEN UPPER(PT.name) = 'DISCOUNT@MARKETPLACE' AND IT.name IS NOT NULL THEN IT.name ELSE PT.name END AS name
			, PT.value
			, PT.isPercentual
			, IFNULL(PT.ID_CALCULATOR_CONFIGURATION, IT.ID_CALCULATOR_CONFIGURATION) AS ID_CALCULATOR_CONFIGURATION
			, PT.rawValue
			, PT.rate
			, PT.jurisCode
			, PT.jurisType
			, PT.jurisName	
		 	, ROW_NUMBER () OVER ( ORDER BY CASE WHEN UPPER(PT.name) = 'DISCOUNT@MARKETPLACE' AND IT.name IS NOT NULL THEN IT.name ELSE PT.name END ) AS PRC_TAG_COUNT -- VARIAVEL CHAVE PARA PRICE TAG
			, :v_REF_ID_COUNT AS REF_ID_COUNT
			, :v_ORDER_ID AS ORDER_ID
			, :v_SKU_ID AS SKU_ID
			, :v_SKU_ID_COMPONENT AS SKU_ID_COMPONENT
		FROM (
			SELECT *
			FROM JSON_TABLE( :v_PRICE_TAGS,'$'
		        COLUMNS ( 
					name NVARCHAR(5000) PATH '$.name',
					value NVARCHAR(5000) PATH '$.value',
					isPercentual NVARCHAR(5000) PATH '$.isPercentual',
					ID_CALCULATOR_CONFIGURATION NVARCHAR(5000) PATH '$.identifier',
					rawValue NVARCHAR(5000) PATH '$.rawValue',
					rate NVARCHAR(5000) PATH '$.rate',
					jurisCode NVARCHAR(5000) PATH '$.jurisCode',
					jurisType NVARCHAR(5000) PATH '$.jurisType',
					jurisName NVARCHAR(5000) PATH '$.jurisName'
			 	)
			 )
		) PT
		LEFT JOIN (
			SELECT 
				  VALUE
				, RAWVALUE
				, ISPERCENTUAL
				, MAX(ID_CALCULATOR_CONFIGURATION) AS ID_CALCULATOR_CONFIGURATION
				, MAX(NAME) AS NAME
			FROM OW_LAO.TMP_JSON_VTEX_PROMOTION_INSTANCES
			GROUP BY
				  VALUE
				, RAWVALUE
				, ISPERCENTUAL
		) IT ON PT.VALUE = IT.VALUE
				AND PT.RAWVALUE = IT.RAWVALUE
				AND PT.ISPERCENTUAL = IT.ISPERCENTUAL
		 ;
	END FOR;
	
 	/********************************************************
	* LIMPA ORDERS CASO EXISTAM NA TABELA FINAL
	* DROP TABLE OW_LAO.FT_D2C_VTEX_PROMOTION 
	********************************************************/	
	DELETE FROM OW_LAO.FT_D2C_VTEX_PROMOTION
	WHERE ORDER_ID IN ( SELECT DISTINCT ORDER_ID FROM OW_LAO.TMP_PO_VTEX_PROMOTION );
	
	 /*********************************************************
	 * ALIMENTA TABELA FATO D2C PROMOTION -- ALTER TABLE SELECT TOP 10 * FROM OW_LAO.FT_D2C_VTEX_PROMOTION ADD (ITEM_INDEX INTEGER);
	 * *******************************************************/	
    INSERT INTO OW_LAO.FT_D2C_VTEX_PROMOTION -- CREATE COLUMN TABLE OW_LAO.FT_D2C_VTEX_PROMOTION AS (
	SELECT
		  PO_.DATE_REF
		, PO_.PO_CREATION_DATE
		, PO_.SALES_CHANNEL
		, OW_LAO.AFFILIATE_ID_ADJUSTED(ES.ID_STORE, PO_.AFFILIATE_ID, PO_.SALES_CHANNEL) AS AFFILIATE_ID_ADJUSTED
		, PO_.ORDER_ID
		, PO_.MARKETPLACE_ORDER_ID
		, PO_.ENVIRONMENT
		, PO_.REFERENCE_CODE_KIT
		, PO_.REFERENCE_CODE
		, PO_.ITEM_NAME
		, PO_.STATUS_PO
		, PO_.COUPON			
		
		/***** PRICE TAGS INFORMATION *****/
		, JS.PRC_TAG_COUNT
		, JS.name AS "PRC_TAG_NAME"
		, JS.ID_CALCULATOR_CONFIGURATION AS "PRC_TAG_IDENTIFIER" -- JS.identifier AS "PRC_TAG_IDENTIFIER"
		, JS.rawValue AS "PRC_TAG_RAWVALUE"
		, CAST(0.0 AS DECIMAL (18,2)) AS AMOUNT_DISCOUNT
		, CASE WHEN UPPER(JS.name) LIKE 'DISCOUNT@SHIPPING%' THEN TRUE ELSE FALSE END AS IS_SHIPPING
		
		/***** PROMOTION INFORMATION *****/
		, JS.ID_CALCULATOR_CONFIGURATION
		, PRM.NAME AS PROM_NAME
		, PRM.BEGIN_DATE AS PROM_BEGIN_DATE
		, PRM.END_DATE AS PROM_END_DATE
		, PRM.DESCRIPTION AS PROM_DESCRIPTION
		, PRM.TYPE AS PROM_TYPE_DESC
		, PRM.STATUS AS PROM_STATUS
		, PRMI.NOMINAL_DISCOUNT_VALUE AS PROM_NOMINAL_DSCNT_VALUE
		, PRMI.NOMINAL_SHIPPING_DISCOUNT_VALUE AS PROM_NOMINAL_SHIP_DSCNT_VALUE
		, PRMI.PERCENTUAL_DISCOUNT_VALUE AS PROM_PERCENT_DSCNT_VALUE
		, PRMI.MAXIMUM_UNIT_PRICE_DISCOUNT AS PROM_MAXIMUM_UNIT_PRICE_DSCNT
		, PRMI.PERCENTUAL_SHIPPING_DISCOUNT_VALUE AS PROM_PERCENT_SHIP_DSCNT_VALUE
		, PRMI.ABSOLUTE_SHIPPING_DISCOUNT_VALUE AS PROM_ABSLTE_SHIP_DSCNT_VALUE
		, PRMI.DISCOUNT_EXPRESSION AS PROM_DSCNT_EXPRESSION
		, PRMI.PRICE_TABLE_NAME AS PROM_PRICE_TABLE_NAME
		, PRMI.NOMINAL_REWARD_VALUE AS PROM_NOMINAL_REWARD_VALUE
		, PRMI.PERCENTUAL_REWARD_VALUE AS PROM_PERCENT_REWARD_VALUE
		
		,( CASE 
			    WHEN UPPER(PRM.TYPE) = 'REGULAR' THEN 'REGULAR'
				WHEN UPPER(PRM.TYPE) = 'COMBO' THEN 'COMPRE JUNTO'
				WHEN UPPER(PRM.TYPE) = 'FORTHEPRICEOF' THEN 'LEVE MAIS POR MENOS'
				WHEN UPPER(PRM.TYPE) = 'PROGRESSIVE' THEN 'DESCONTO PROGRESSIVO'
				WHEN UPPER(PRM.TYPE) = 'BUYANDWIN' THEN 'COMPRE E GANHE'
				WHEN UPPER(PRM.TYPE) = 'CAMPAIGN' THEN 'PROMOÇÃO DE CAMPANHA' 
			ELSE UPPER(PRM.TYPE)
		  END ) AS "PROMOTION_TYPE"
		
		,( CASE 
			   WHEN UPPER(PRM.TYPE) = 'REGULAR' AND PRMI.NOMINAL_DISCOUNT_VALUE <> '0.0' THEN 'NOMINAL'
			   WHEN UPPER(PRM.TYPE) = 'REGULAR' AND PRMI.NOMINAL_SHIPPING_DISCOUNT_VALUE <> '0.0' THEN 'FRETE NOMINAL'
			   WHEN UPPER(PRM.TYPE) = 'REGULAR' AND PRMI.PERCENTUAL_DISCOUNT_VALUE <> '0.0' THEN 'PERCENTUAL'
			   WHEN UPPER(PRM.TYPE) = 'REGULAR' AND PRMI.MAXIMUM_UNIT_PRICE_DISCOUNT <> '0.0' THEN 'PREÇO MAXIMO POR ITEM'
			   WHEN UPPER(PRM.TYPE) = 'REGULAR' AND PRMI.PERCENTUAL_SHIPPING_DISCOUNT_VALUE <> '0.0' THEN 'FRETE PERCENTUAL'
			   WHEN UPPER(PRM.TYPE) = 'REGULAR' AND PRMI.ABSOLUTE_SHIPPING_DISCOUNT_VALUE <> '0.0' THEN 'FRETE MAXIMO'
			   WHEN UPPER(PRM.TYPE) = 'REGULAR' AND PRMI.DISCOUNT_EXPRESSION IS NOT NULL THEN 'DESCONTO NOMINAL BASEADO EM FÓRMULA'
			   WHEN UPPER(PRM.TYPE) = 'REGULAR' AND PRMI.PRICE_TABLE_NAME IS NOT NULL THEN 'TABELA DE PREÇOS PROMOCIONAIS'
			   WHEN UPPER(PRM.TYPE) = 'REGULAR' AND PRM.ACTIVATE_GIFTS_MULTIPLIER ='TRUE' THEN 'BRINDE'
			   WHEN UPPER(PRM.TYPE) = 'REGULAR' AND PRMI.NOMINAL_REWARD_VALUE <> '0.0' THEN 'VALOR DE FIDELIDADE NOMINAL'
			   WHEN UPPER(PRM.TYPE) = 'REGULAR' AND PRMI.PERCENTUAL_REWARD_VALUE <> '0.0' THEN 'VALOR DE FIDELIDADE PERCENTUAL'
		  END ) AS PROMOTION_SUBTYPE
		  
		, PO_.SKU_ID
		, PO_.SKU_ID_COMPONENT		  
		, PO_.PRICE_TAGS
		, CURRENT_TIMESTAMP AS KPI_LAST_UPDATE
		, PO_.ITEM_INDEX
		, PO_.SELLING_AMOUNT_LOCAL
		, PO_.ITEM_INDEX_KIT
	FROM OW_LAO.TMP_PO_VTEX_PROMOTION PO_
	
		 LEFT JOIN OW_LAO.TMP_JSON_VTEX_PROMOTION JS 
			  ON JS.ORDER_ID = PO_.ORDER_ID
				 AND JS.SKU_ID = PO_.SKU_ID
				 AND IFNULL(JS.SKU_ID_COMPONENT,'') = IFNULL(PO_.SKU_ID_COMPONENT,'')
				 AND JS.REF_ID_COUNT = PO_.REF_ID_COUNT
		LEFT JOIN U_PRJ_ECOM.VIEW_VTEX_PROMOTION PRM
			ON PRM.ID_CALCULATOR_CONFIGURATION = JS.ID_CALCULATOR_CONFIGURATION
		
		LEFT JOIN U_PRJ_ECOM.ODS_VTEX_SSG_BR_SHOP_DATA_ENTITIES_STORES_SDS ES
			ON ES.ID_STORE = PO_.STORE_ID -- ENDLESS_STORE	
		LEFT JOIN U_PRJ_ECOM.VIEW_VTEX_PROMOTION_ITEM PRMI
			ON PRMI.ID_CALCULATOR_CONFIGURATION = JS.ID_CALCULATOR_CONFIGURATION
	;
	
	/*********************************************************
	* FAZ RATEIO NO AMOUNT_DISCOUNT
	* SELECT TOP 100 * FROM OW_LAO.FT_D2C_VTEX_PROMOTION PM
	* *******************************************************/
	UPDATE PM SET PM.AMOUNT_DISCOUNT = 
		IFNULL(
			CASE WHEN TT.ITEM_INDEX IS NOT NULL -- COM TOTALIZADOR
				 THEN -- SE TEM TOTALIZADOR FAZ RATEIO DE ACORDO COM O SELLING_AMOUNT_LOCAL DO ITEM
				 	CASE WHEN TT.SELLING_AMOUNT_LOCAL_TOTAL > 0 THEN 
						( ( CAST(PM.SELLING_AMOUNT_LOCAL AS DECIMAL(18,6)) / TT.SELLING_AMOUNT_LOCAL_TOTAL ) * CAST(PM.PRC_TAG_RAWVALUE AS DECIMAL(18,6)) ) -- RATIO
					END
				 ELSE -- SENÃO PEGA O VALOR TODO DO ITEM
				 	CAST (PM.PRC_TAG_RAWVALUE AS DECIMAL(18,2) )
			END
		,0)
	FROM OW_LAO.FT_D2C_VTEX_PROMOTION PM
		INNER JOIN OW_LAO.TMP_PO_ORDER_ID_PO_VTEX_PROMOTION LI ON PM.ORDER_ID = LI.ORDER_ID  -- SOMENTE AS ORDER NOVAS
		LEFT JOIN ( -- TOTALIZADOR (KITS COM MAIS DE 1 SKU)
			SELECT 
				  ORDER_ID
				, ITEM_INDEX
				, SUM(CAST (SELLING_AMOUNT_LOCAL AS DECIMAL(18,6))) AS SELLING_AMOUNT_LOCAL_TOTAL
			FROM(
				SELECT
					  T.ORDER_ID
					, T.ITEM_INDEX
					, T.ITEM_INDEX_KIT
					, MAX(CAST(T.SELLING_AMOUNT_LOCAL AS DECIMAL(18,6))) AS SELLING_AMOUNT_LOCAL
				FROM OW_LAO.FT_D2C_VTEX_PROMOTION T
					 INNER JOIN OW_LAO.TMP_PO_ORDER_ID_PO_VTEX_PROMOTION L ON T.ORDER_ID = L.ORDER_ID -- SOMENTE AS ORDER NOVAS
				WHERE T.ITEM_INDEX_KIT IS NOT NULL  -- SOMENTE PARA KITS
				GROUP BY
					  T.ORDER_ID
					, T.ITEM_INDEX
					, T.ITEM_INDEX_KIT
			)
			GROUP BY 
				  ORDER_ID
				, ITEM_INDEX
			HAVING
				COUNT(ITEM_INDEX_KIT) > 1 -- TEM MAIS DE 1 REFERENCE_CODE NO REFERENCE_CODE_KIT POR ISSO PRECISA FAZER A PROPORÇÃO PELO SELLING
		) TT ON PM.ORDER_ID = TT.ORDER_ID
				AND PM.ITEM_INDEX = TT.ITEM_INDEX
	;
	/*********************************************************
	* FAZ RATEIO NO AMOUNT_DISCOUNT_PROMOTION (DW DETALHADO)
	* *******************************************************/
	UPDATE PM SET
		PM.AMOUNT_DISCOUNT_PROMOTION = PR.AMOUNT_DISCOUNT_PROMOTION_TOTAL
	FROM OW_LAO.TF_D2C_NERP_SALES PM
		INNER JOIN( -- PROMOTION
			SELECT
				  ORDER_ID
				, ITEM_INDEX	
				, ITEM_INDEX_KIT
				, SUM(AMOUNT_DISCOUNT) AS AMOUNT_DISCOUNT_PROMOTION_TOTAL -- SOMA TODAS AS PROMOÇÕES
			FROM OW_LAO.FT_D2C_VTEX_PROMOTION
			WHERE REFERENCE_CODE IS NOT NULL
			GROUP BY
				  ORDER_ID
				, ITEM_INDEX	
				, ITEM_INDEX_KIT
		) PR ON PM.ORDER_ID = PR.ORDER_ID
				AND PM.ITEM_INDEX = PR.ITEM_INDEX
				AND IFNULL(PM.ITEM_INDEX_KIT,9999) = IFNULL(PR.ITEM_INDEX_KIT,9999)
	WHERE 1=1
		AND PM.AMOUNT_DISCOUNT_PROMOTION IS NULL
	;
	
	/*********************************************************
	* ATUALIZA STATUS CASO TENHA MUDADO
	* *******************************************************/		
	UPDATE PMT SET PMT.STATUS_PO = BSO.STATUS
	FROM OW_LAO.FT_D2C_VTEX_PROMOTION PMT
		INNER JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER BSO ON PMT.ORDER_ID = BSO.ORDER_ID
	WHERE PMT.STATUS_PO <> BSO.STATUS;
	
	/*********************************************************
	* APAGA TEMPORÁRIAS
	* *******************************************************/	
	DROP TABLE OW_LAO.TMP_PARAMETER_VTEX_PROMOTION;
	DROP TABLE OW_LAO.TMP_PO_ORDER_ID_PO_VTEX_PROMOTION;
	DROP TABLE OW_LAO.TMP_JSON_VTEX_PROMOTION;
	DROP TABLE OW_LAO.TMP_SSG_BR_SHOP_SALES_ORDER_SHIPPING_VTEX_PROMOTION;
	--DROP TABLE OW_LAO.TMP_PO_VTEX_PROMOTION;
	DELETE FROM OW_LAO.TMP_PO_VTEX_PROMOTION;
	DROP TABLE OW_LAO.TMP_ITEM_COMPONENTS_PO_VTEX_PROMOTION;
	DROP TABLE OW_LAO.TMP_ORDER_ITEM_TO_COMPONENTS_PO_VTEX_PROMOTION;
	DROP TABLE OW_LAO.TMP_JSON_VTEX_PROMOTION_INSTANCES;
	
END;