/***********************************************************************************************
ALTER BY : LUCIANO MARIANI
CREATION DATE : 2023-11-14
-- CALL OW_LAO.PROC_D2C_PO_VTEX_MONITORING_SKU 
-- ( ADD_DAYS(CURRENT_TIMESTAMP, -1),  ADD_DAYS(CURRENT_TIMESTAMP, 2))
SELECT TOP 1000 * 
FROM OW_LAO.TF_VTEX_MONITORING_SKU
***********************************************************************************************/
CREATE PROCEDURE OW_LAO.PROC_D2C_PO_VTEX_MONITORING_SKU 
/************************
(
	 p_DATE_INI DATE DEFAULT NULL 
	,P_DATE_FIM DATE DEFAULT NULL 
) LANGUAGE SQLSCRIPT
*************************/
AS
BEGIN
		
	/*********************************************************
	* CRIA A TMP_PARAMETER_MONITORING_SKU
	********************************************************* /
	IF EXISTS ( SELECT TABLE_NAME FROM SYS.TABLES WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TMP_PARAMETER_MONITORING_SKU' ) THEN
		DROP TABLE OW_LAO.TMP_PARAMETER_MONITORING_SKU;
	END IF ;
	CREATE COLUMN TABLE OW_LAO.TMP_PARAMETER_MONITORING_SKU AS (
		SELECT ADD_DAYS(CURRENT_TIMESTAMP, -15) AS DATE_INI , ADD_DAYS(CURRENT_TIMESTAMP, 2) AS DATE_FIM 
		FROM DUMMY
	);
	UPDATE OW_LAO.TMP_PARAMETER_MONITORING_SKU SET
		 DATE_INI = IFNULL(p_DATE_INI, ADD_DAYS(CURRENT_TIMESTAMP, -7))
		,DATE_FIM = IFNULL(P_DATE_FIM, ADD_DAYS(CURRENT_TIMESTAMP, 1)) 
	;
	-- *******************************************************/ 
	IF EXISTS ( SELECT TABLE_NAME FROM SYS.TABLES WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TF_VTEX_MONITORING_SKU' ) THEN
		DROP TABLE OW_LAO.TF_VTEX_MONITORING_SKU;
	END IF ;
	CREATE COLUMN TABLE OW_LAO.TF_VTEX_MONITORING_SKU AS (
		SELECT -- IS_ACTIVE	ACTIVATE_IF_POSSIBLE	IS_KIT	TP_AVAILABLE
			  FP.LOAD_DATE
			, 'SEDA' AS SUBSIDIARY
			, FP.ACCOUNT_NAME
			, FP.ITEM_ID
			, FP.TRADE_POLICY_ID
			, TD.NOME_VTEX
			, TD.NOME_TABLEAU
			, FP.VALUE
			, FP.LIST_PRICE
			, FP.MIN_QUANTITY
			, FP.DATE_RANGE_FROM
			, FP.DATE_RANGE_TO
			, SK.PRODUCT_ID
			, CASE WHEN SK.IS_ACTIVE = TRUE THEN 1 WHEN SK.IS_ACTIVE = FALSE THEN 0 END AS IS_ACTIVE
			, CASE WHEN SK.ACTIVATE_IF_POSSIBLE = TRUE THEN 1 WHEN SK.ACTIVATE_IF_POSSIBLE = FALSE THEN 0 END AS ACTIVATE_IF_POSSIBLE
			, SK.NAME
			, SK.REF_ID
			, CASE WHEN SK.IS_KIT = TRUE THEN 1 WHEN SK.IS_KIT = FALSE THEN 0 END AS IS_KIT
			, SK.CREATION_DATE
			
			, CASE WHEN TP.PRODUCT_ID IS NOT NULL THEN 1 ELSE 0 END AS TP_AVAILABLE
			
			-- PRODUCT
			, SK.REF_ID AS SKU
			, PD."DIVISION" AS PDROD_DIVISION
			, PD.PRODUCT_GROUP_1 AS PDROD_PRODUCT_GROUP
			, PD.PRODUCT_1 AS PDROD_PRODUCT
			, PD.ATTB01 AS PROD_ATTB_1
			, IFNULL(PD.SEDA_BU_ESTORE, 'Unmapped') AS SEDA_BU_ESTORE
			, IFNULL(PD.SEDA_DIVISION_ESTORE, 'Unmapped') AS SEDA_DIVISION_ESTORE
			, IFNULL(PD.SEDA_CATEGORY_ESTORE, 'Unmapped') AS SEDA_CATEGORY_ESTORE
			, IFNULL(PD.SEDA_FAMILY_ESTORE, 'Unmapped') AS SEDA_FAMILY_ESTORE
			, IFNULL(PD.SEDA_DESC_ESTORE, 'Unmapped') AS SEDA_DESC_ESTORE
			
			, CURRENT_TIMESTAMP AS KPI_LAST_UPDATE
		-- SELECT DISTINCT FP.TRADE_POLICY_ID, count('') as total
		FROM U_PRJ_ECOM.ODS_VTEX_SSG_BR_SHOP_FIXED_PRICES FP -- Essa tabela puxa informações dos preços de cada SKU em cada trade policy.
				--GROUP BY FP.TRADE_POLICY_ID
			LEFT JOIN U_PRJ_ECOM.ODS_VTEX_SSG_BR_SHOP_SKU_BY_REF_ID SK -- Essa tabela puxa o catalogo de produtos cadastrados na VTEX.
				ON FP.ITEM_ID  = SK.ID
					AND FP.LOAD_DATE = SK.LOAD_DATE
				
			LEFT JOIN U_PRJ_ECOM.ODS_VTEX_SSG_BR_SHOP_SKU_TRADE_POLICIES TP -- 3.	Tabela 03: Essa tabela puxa os trade policies habilitados para determinado SKU.
				  ON SK.PRODUCT_ID = TP.PRODUCT_ID
				  	 AND FP.TRADE_POLICY_ID = TP.STORE_ID
					 AND SK.LOAD_DATE = TO_DATE(TP.LOAD_DATE)
			
			LEFT JOIN OW_MD.DIM_PRODUCT PD ON PD.SKU = SK.REF_ID
			
			LEFT JOIN OW_MD.MASTER_TRADE_POLICIES TD ON TD.TRADE_POLICY = FP.TRADE_POLICY_ID -- CAST( CASE WHEN OW_LAO.ISNUMERIC(FP.TRADE_POLICY_ID) = 1 THEN FP.TRADE_POLICY_ID END AS INTEGER)
			
		WHERE 1=1 --SK.LOAD_DATE > '2024-07-10'
			AND SK.LOAD_DATE = ( SELECT MAX(LOAD_DATE) FROM U_PRJ_ECOM.ODS_VTEX_SSG_BR_SHOP_FIXED_PRICES )
			AND OW_LAO.ISNUMERIC(FP.TRADE_POLICY_ID) = 1 -- SOMENTE NUMÉRICO
	);
	
	/*********************************************************
	* APAGA TEMPORÁRIAS
	* *******************************************************/	
	-- DROP TABLE OW_LAO.TMP_PARAMETER_MONITORING_SKU;
	
END