
CREATE PROCEDURE OW_LAO.PROC_D2C_AR_TABLE_MONTH_PT1
LANGUAGE SQLSCRIPT as
BEGIN
--Truncar Tabela com os dados no nivel granular mais baixo para tratamento de dados 
TRUNCATE TABLE OW_LAO.TMP_D2C_AR_TABLE_MONTH;
--Inserir os dados no nivel granular mais baixo na tabela de temporária
INSERT INTO  OW_LAO.TMP_D2C_AR_TABLE_MONTH
SELECT --FNL.ROW_NUM --,
	 FNL.ORDER_ID
	,FNL."SEQUENCE"
	,FNL.PO_AMOUNT
	,(CASE WHEN FNL.QTY_PO_DISTINCT = 1
		THEN FNL.PO_AMOUNT
		ELSE 0
	END) AS AMT_PO_DISTINCT
	,(CASE WHEN FNL.QTY_PO_DISTINCT <> 1
		THEN 0
		ELSE 1
	END) AS QTY_PO_DISTINCT
	,FNL.DIMPROD_PRODUCT_GROUP
	,FNL.DIMPROD_DIVISION
	,FNL.DIMPROD_PRODUCT
	,FNL.AFFILIATE_CHANNEL
	,FNL.AFFILIATE_SUB_CHANNEL
	,FNL."Key"
	,FNL."Key2"
	,FNL.GL_ACCOUNT_KOREAN
	,FNL.GL_ACCOUNT_ENGLISH	
	,FNL."System Due date (In/Over)"
	,FNL."Range"
	,FNL."Customer Group (eStore/MKP)"
	,FNL."(+/-) AR"
	,FNL.CUSTOMER_NAME
	,FNL.CUSTOMER
	,FNL.DOCUMENT_TYPE
	,FNL.POSTING_KEY
	,FNL.PAYMENT_TERMS
	,FNL.REFERENCE
	,FNL.DOCUMENT_DATE
	,FNL."ASSIGNMENT"
	,FNL.AMOUNT_IN_LOCAL_CURRENCY
	,FNL.NET_DUE_DATE
	,FNL.ARREARS_BY_NET_DUE_DATE
	,FNL.DOCUMENT_NUMBER
	,FNL.CLEARING_DOCUMENT
	,FNL.CLEARING_DATE
	,FNL."TEXT"
	,FNL.REASON_CODE
	,FNL.ENTRY_DATE
	,FNL."Week Entry"
	,FNL."G/L_ACCOUNT"
	,FNL.BILLING_DOCUMENT
	,FNL.BUSINESS_AREA
	,FNL.LINE_ITEM
	,FNL.INVOICE_REFERENCE
	,FNL."G/L_ACCOUNT_1"
	,FNL.POSTING_DATE
	,FNL."Week Posting"
	,FNL.REFERENCE_KEY_3
	,FNL.DOCUMENT_HEADER_TEXT
	,FNL.REFERENCE_KEY_1
	,FNL.REFERENCE_KEY_2
	,FNL."YEAR/MONTH"
	,FNL.USER_NAME
	,FNL.LOCAL_CURRENCY
	,FNL.LOAD_DATE AS FILE_LOAD_DATE
	,FNL.YEARMONTH_BY_FILENAME
	,FNL."Month/Year"
	,FNL."TYPE ITEM"
	,FNL."TYPE"
	,FNL."1_CATE"
	,FNL."2_CATE"
	,FNL."3_CATE"
	,FNL."REASON TYPE"
	,FNL.PIC
	,FNL.REMARK
	,FNL."NEXT STEP"
	,FNL."SUB. CATEGORY 2"
	,FNL."System due date (in/Over)&(+/-) AR&Sub. Category 2" 
	,NOW() AS LOAD_DATE
FROM (
	SELECT  
	        --ONFNCLIDOI.ROW_NUM
		--,
		URVSBSSOL.ORDER_ID
		,URVSBSSOL."SEQUENCE"		
		,URVSBSSOL.PO_AMOUNT
		,ONFNCLIDOI.QTY_PO_DISTINCT
		,DP.SEDA_BU_ESTORE AS DIMPROD_PRODUCT_GROUP 
		,DP.SEDA_DIVISION_ESTORE AS DIMPROD_DIVISION 
		,DP.SEDA_DESC_ESTORE AS DIMPROD_PRODUCT 
		,OW_LAO.AFFILIATE_ID_ADJUSTED(URVSBSSOL.ID_STORE, URVSBSSOL.AFFILIATE_ID, URVSBSSOL.SALES_CHANNEL) AS AFFILIATE_ID_ADJUSTED
		,DAC.AFFILIATE_CHANNEL
		,DAC.AFFILIATE_SUB_CHANNEL
		,ONFNCLIDOI."Key"	
		,ONFNCLIDOI."Key2"
		,MKGA.SHORT_TEXT_KOREAN AS GL_ACCOUNT_KOREAN
		,MKGA.SHORT_TEXT_ENGLISH AS GL_ACCOUNT_ENGLISH	
		,ONFNCLIDOI."System Due date (In/Over)"	
		,ONFNCLIDOI."Range"
		,MAC.CUSTOMER_NAME_SUMMARY AS "Customer Group (eStore/MKP)"
		,ONFNCLIDOI."(+/-) AR"
		,MAC.CUSTOMER_NAME_DETAIL AS CUSTOMER_NAME
		,ONFNCLIDOI.CUSTOMER
		,ONFNCLIDOI.DOCUMENT_TYPE
		,ONFNCLIDOI.POSTING_KEY
		,ONFNCLIDOI.PAYMENT_TERMS
		,ONFNCLIDOI.REFERENCE
		,ONFNCLIDOI.DOCUMENT_DATE
		,ONFNCLIDOI.AMOUNT_IN_LOCAL_CURRENCY
		,ONFNCLIDOI.NET_DUE_DATE
		,ONFNCLIDOI.ARREARS_BY_NET_DUE_DATE
		,ONFNCLIDOI.DOCUMENT_NUMBER
		,ONFNCLIDOI.CLEARING_DOCUMENT
		,ONFNCLIDOI.CLEARING_DATE
		,ONFNCLIDOI."ASSIGNMENT"
		,ONFNCLIDOI."TEXT"
		,ONFNCLIDOI.REASON_CODE
		,ONFNCLIDOI.ENTRY_DATE
		,ONFNCLIDOI."Week Entry"
		,ONFNCLIDOI."G/L_ACCOUNT"
		,ONFNCLIDOI.BILLING_DOCUMENT
		,ONFNCLIDOI.BUSINESS_AREA
		,ONFNCLIDOI.LINE_ITEM
		,ONFNCLIDOI.INVOICE_REFERENCE
		,ONFNCLIDOI."G/L_ACCOUNT_1"
		,ONFNCLIDOI.POSTING_DATE
		,ONFNCLIDOI."Week Posting"
		,ONFNCLIDOI.REFERENCE_KEY_3
		,ONFNCLIDOI.DOCUMENT_HEADER_TEXT
		,ONFNCLIDOI.REFERENCE_KEY_1
		,ONFNCLIDOI.REFERENCE_KEY_2
		,ONFNCLIDOI."YEAR/MONTH"
		,ONFNCLIDOI.USER_NAME
		,ONFNCLIDOI.LOCAL_CURRENCY
		,ONFNCLIDOI.LOAD_DATE
		,ONFNCLIDOI.YEARMONTH_BY_FILENAME
		,ONFNCLIDOI."Month/Year"
		,NULL AS "TYPE ITEM"
		,NULL AS "TYPE"
		,NULL AS "1_CATE"
		,NULL AS "2_CATE"
		,NULL AS "3_CATE"
		,NULL AS "REASON TYPE"
		,NULL AS "PIC"
		,NULL AS REMARK
		,NULL AS "NEXT STEP"
		,NULL AS "SUB. CATEGORY 2"
		,ONFNCLIDOI."System due date (in/Over)&(+/-) AR&Sub. Category 2"
		,ONFNCLIDOI.NUM_LINE
	FROM (
	SELECT  -- ONFNCLIDOI2.*
		ROW_NUMBER() OVER () AS NUM_LINE
		--,ROW_NUMBER() OVER (PARTITION BY ONFNCLIDOI2.CUSTOMER, ONFNCLIDOI2."ASSIGNMENT", ONFNCLIDOI2.DOCUMENT_NUMBER, REPLACE(ONFNCLIDOI2.AMOUNT_IN_LOCAL_CURRENCY,'.',',') 
	        -- ORDER BY ONFNCLIDOI2.CUSTOMER, ONFNCLIDOI2."ASSIGNMENT", ONFNCLIDOI2.DOCUMENT_NUMBER, REPLACE(ONFNCLIDOI2.AMOUNT_IN_LOCAL_CURRENCY,'.',',')  DESC) AS ROW_NUM
		,ROW_NUMBER() OVER (PARTITION BY ONFNCLIDOI2."ASSIGNMENT" ORDER BY ONFNCLIDOI2."ASSIGNMENT" DESC, ONFNCLIDOI2.FILE_NAME) AS QTY_PO_DISTINCT
		,IFNULL(ONFNCLIDOI2.CUSTOMER,'') || IFNULL(ONFNCLIDOI2."ASSIGNMENT",'') || IFNULL(ONFNCLIDOI2.DOCUMENT_NUMBER,'') || IFNULL(REPLACE(ONFNCLIDOI2.AMOUNT_IN_LOCAL_CURRENCY,'.',','),'') || IFNULL(ONFNCLIDOI2.LINE_ITEM,'') AS "Key"	
		,IFNULL(ONFNCLIDOI2.CUSTOMER,'') || IFNULL(ONFNCLIDOI2."ASSIGNMENT",'') || IFNULL(ONFNCLIDOI2.DOCUMENT_NUMBER,'') || IFNULL(REPLACE(ONFNCLIDOI2.AMOUNT_IN_LOCAL_CURRENCY,'.',','),'')  AS "Key2"
		,(CASE WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE > 0
			THEN 'Over'
			ELSE 'In'
		END) AS "System Due date (In/Over)"	
		,(CASE WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE<=-46
			THEN '* Indue'
		 WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN -45 AND -38
			THEN '0~7 Indue'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN -37 AND -30
			THEN '8~15 Indue'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN -29 AND -15
			THEN '16~30 Indue'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN -14 AND 0
			THEN '31~45 Indue'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN 1 AND 7
			THEN '1 ~ 7 days'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN 8 AND 14
			THEN '8 ~ 14 days'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN 15 AND 31
			THEN '15 ~ 31 days'	
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN 32 AND 60
			THEN '32 ~ 60 days'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN 61 AND 90
			THEN '61 ~ 90 days'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN 91 AND 180
			THEN '91~180 days'
		WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE BETWEEN 181 AND 360
			THEN '181~360 days'
			ELSE 'Over 360'
		END) AS "Range"
		,(CASE WHEN TO_DOUBLE(/*REPLACE(*/ONFNCLIDOI2.AMOUNT_IN_LOCAL_CURRENCY/*,'.',',')*/) > 0
			THEN '(+) AR'
			ELSE '(-) AR'
		END) AS "(+/-) AR"
		,ONFNCLIDOI2.CUSTOMER
		,ONFNCLIDOI2.DOCUMENT_TYPE
		,ONFNCLIDOI2.POSTING_KEY
		,ONFNCLIDOI2.PAYMENT_TERMS
		,ONFNCLIDOI2.REFERENCE
		,TO_DATE(ONFNCLIDOI2.DOCUMENT_DATE) AS DOCUMENT_DATE
		,REPLACE(ONFNCLIDOI2.AMOUNT_IN_LOCAL_CURRENCY,'.',',') AS AMOUNT_IN_LOCAL_CURRENCY
		,TO_DATE(ONFNCLIDOI2.NET_DUE_DATE) AS NET_DUE_DATE
		,ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE
		,ONFNCLIDOI2.DOCUMENT_NUMBER
		,ONFNCLIDOI2.CLEARING_DOCUMENT
		,ONFNCLIDOI2.CLEARING_DATE
		,IFNULL(MAAA."ASSIGNMENT",ONFNCLIDOI2."ASSIGNMENT") AS "ASSIGNMENT"
		,ONFNCLIDOI2."TEXT"
		,ONFNCLIDOI2.REASON_CODE
		,TO_DATE(ONFNCLIDOI2.ENTRY_DATE) AS ENTRY_DATE
		,(SELECT DC.YYYYWW FROM OW_MD.DIM_CALENDAR DC WHERE DC.YYYYMMDD = ONFNCLIDOI2.ENTRY_DATE) AS "Week Entry"
		,ONFNCLIDOI2."G/L_ACCOUNT"
		,ONFNCLIDOI2.BILLING_DOCUMENT
		,ONFNCLIDOI2.BUSINESS_AREA
		,ONFNCLIDOI2.LINE_ITEM
		,ONFNCLIDOI2.INVOICE_REFERENCE
		,ONFNCLIDOI2."G/L_ACCOUNT_1"
		,TO_DATE(ONFNCLIDOI2.POSTING_DATE) AS POSTING_DATE
		,(SELECT DC.YYYYWW FROM OW_MD.DIM_CALENDAR DC WHERE DC.YYYYMMDD = ONFNCLIDOI2.POSTING_DATE) AS "Week Posting"
		,ONFNCLIDOI2.REFERENCE_KEY_3
		,ONFNCLIDOI2.DOCUMENT_HEADER_TEXT
		,ONFNCLIDOI2.REFERENCE_KEY_1
		,ONFNCLIDOI2.REFERENCE_KEY_2
		,ONFNCLIDOI2."YEAR/MONTH"
		,ONFNCLIDOI2.USER_NAME
		,ONFNCLIDOI2.LOCAL_CURRENCY
		,ONFNCLIDOI2.LOAD_DATE
		--,YEAR(TO_DATE(SUBSTRING(ONFNCLIDOI2.FILE_NAME,20,8))) || MONTH(TO_DATE(SUBSTRING(ONFNCLIDOI2.FILE_NAME,20,8))) AS YEARMONTH_BY_FILENAME
		--,YEAR(TO_DATE(SUBSTRING(ONFNCLIDOI2.FILE_NAME,26,8)))||MONTH(TO_DATE(SUBSTRING(ONFNCLIDOI2.FILE_NAME,26,8))) AS YEARMONTH_BY_FILENAME
		,YEAR(TO_DATE(SUBSTRING(ONFNCLIDOI2.FILE_NAME,26,8)))||
		(CASE WHEN MONTH(TO_DATE(SUBSTRING(ONFNCLIDOI2.FILE_NAME,26,8))) BETWEEN 1 AND 9
			THEN '0'
			ELSE ''
		END)||
		MONTH(TO_DATE(SUBSTRING(ONFNCLIDOI2.FILE_NAME,26,8))) 
		AS YEARMONTH_BY_FILENAME
		,(SELECT DC.YYYYMM_NORMAL_CALENDAR FROM OW_MD.DIM_CALENDAR DC WHERE DC.YYYYMMDD = TO_DATE(ONFNCLIDOI2.LOAD_DATE)) AS "Month/Year"
		,(CASE WHEN ONFNCLIDOI2.ARREARS_BY_NET_DUE_DATE >= 0
			THEN 'Over(+) AR'
			ELSE 'In(-) AR'
		END) AS "System due date (in/Over)&(+/-) AR&Sub. Category 2"
	FROM OW_SEDA_S.ODS_NERP_FBL5N_CUSTOMER_LINE_ITEM_DISPLAY_OPEN_ITEMS_HIST ONFNCLIDOI2 
	LEFT JOIN  OW_MD.MAP_AR_ASSIGNMENT_ADJUSTED MAAA ON (IFNULL(ONFNCLIDOI2.CUSTOMER,'') || IFNULL(ONFNCLIDOI2."ASSIGNMENT",'') || IFNULL(ONFNCLIDOI2.DOCUMENT_NUMBER,'') || IFNULL(REPLACE(ONFNCLIDOI2.AMOUNT_IN_LOCAL_CURRENCY,'.',','),'') = MAAA.KEY2)
	WHERE UPPER(ONFNCLIDOI2.FILE_NAME)  LIKE '%OPENITEM_MONTH%'
	-- TO REPROCESS THE COMPLETE BASE, COMMENT ON THE TWO LINES BELOW
	--AND YEAR(TO_DATE(SUBSTRING(ONFNCLIDOI2.FILE_NAME,26,8)))||MONTH(TO_DATE(SUBSTRING(ONFNCLIDOI2.FILE_NAME,26,8)))
	--= YEAR(ADD_MONTHS(CURRENT_DATE,-1))||MONTH(ADD_MONTHS(CURRENT_DATE,-1))	
		
	ORDER BY ONFNCLIDOI2.CUSTOMER, ONFNCLIDOI2."ASSIGNMENT", ONFNCLIDOI2.DOCUMENT_NUMBER, REPLACE(ONFNCLIDOI2.AMOUNT_IN_LOCAL_CURRENCY,'.',',')--, ROW_NUM ASC
	) ONFNCLIDOI 
	LEFT JOIN (SELECT * FROM (SELECT --DISTINCT 
				 	ROW_NUMBER() OVER (PARTITION BY IFNULL(RVSBSSOL."SEQUENCE",RVSBSSOL.ORDER_ID) 
	         				ORDER BY IFNULL(RVSBSSOL."SEQUENCE",RVSBSSOL.ORDER_ID) DESC, RVSBSSOI.PRICE DESC) AS ROW_NUM
				 	,RVSBSSOL.ORDER_ID
				 	, RVSBSSOL.MARKETPLACE_ORDER_ID
				 	, RVSBSSOL.AFFILIATE_ID
				        , RVSBSSOL."SEQUENCE"
				        , TO_DATE(RVSBSSOL.CREATION_TIMESTAMP) AS CREATION_DATE
				        , RVSBSSOL.CANCELLATION_DATE
				        , RVSBSSOL.STATUS_DESCRIPTION
				        , RVSBSSOL.SALES_CHANNEL
				        , RVSBSSOL.AUTHORIZED_DATE
				        , RVSBSSOL.STATUS
					, RVSBSSOI.ITEM_INDEX,
					CASE WHEN RVSBSSOIC.REF_ID IS NULL 
						THEN RVSBSSOI.REF_ID
						ELSE RVSBSSOIC.REF_ID
					END AS REF_ID 
					, (RVSBSSOI.QUANTITY*IFNULL(RVSBSSOIC.QUANTITY,1)) AS QUANTITY
					, (RVSBSSOL.VALUE/100) AS "PO_AMOUNT"
					, URVSBSSOS."SELECTED_SLA"
	                  		, URVSBSSOS."WAREHOUSE_ID_GROUP"
	                  		, URVSBSSOS.ADDRESSTYPE
	                  		, URVSBSSOS.FRIENDLYNAME
	                  		, URVSBSSOS.STATE
	                  		, URVSBSSOS.CITY
			  		, CASE WHEN ( TRIM(UPPER(URVSBSSOS."SELECTED_SLA")) LIKE 'SHIP TO STORE %' 
	                                   		OR TRIM(UPPER(URVSBSSOS."SELECTED_SLA"))LIKE 'PONTO DE RETIRADA %'
	                                   		OR TRIM(UPPER(URVSBSSOS."SELECTED_SLA"))LIKE 'CLIQUE%'
	                             		    )
	                        		    AND OVSBSDESS.ID_STORE IS NOT NULL --PO.CHANNEL_TYPE = 'Store+'
	                        				THEN 'BOPIS + EA'
	                        	       WHEN ( TRIM(UPPER(URVSBSSOS."SELECTED_SLA")) LIKE 'SHIP TO STORE %'
	                                 		OR TRIM(UPPER(URVSBSSOS."SELECTED_SLA"))LIKE 'PONTO DE RETIRADA %'
	                                 		OR TRIM(UPPER(URVSBSSOS."SELECTED_SLA"))LIKE 'CLIQUE%'
	                        		    )
	                        				THEN 'BOPIS'
	                        	       WHEN OVSBSDESS.ID_STORE IS NOT NULL --( PO.CHANNEL_TYPE = 'Store+' )
	                        				THEN 'EA'
	                  					ELSE NULL 
	                  		END AS O2O_TYPE
					, OVSBSDESS.ID_STORE
					, CASE WHEN OVSBSDESS.ID_STORE IS NOT NULL THEN 'Store+' ELSE 'Shop' END AS CHANNEL_TYPE
					, OVSBSDESS.NAME AS NAME_STORE
					, RVSBSSOL.LAST_CHANGE
					--,RVSBSSOI.*
					FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER RVSBSSOL
					LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_ITEM RVSBSSOI 
					ON (RVSBSSOL.ORDER_ID = RVSBSSOI.ORDER_ID)
					LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_ITEM_COMPONENTS RVSBSSOIC  
					ON (RVSBSSOI.ORDER_ID = RVSBSSOIC.ORDER_ID AND RVSBSSOI.SKU_ID = RVSBSSOIC.SKU_ID)
					LEFT JOIN ( 	SELECT DISTINCT ORDER_ID
										, ITEM_INDEX
										, MAX(JSON_VALUE('[' || PICKUP_STORE_INFO || ']', '$.address.addressType')) AS ADDRESSTYPE
					                        		, MAX(JSON_VALUE('[' || PICKUP_STORE_INFO || ']', '$.friendlyName')) AS FRIENDLYNAME
					                        		, MAX(STATE) AS STATE
					                        		, MAX(CITY) AS CITY
					                        		, MAX(SELECTED_SLA) AS SELECTED_SLA
					                        		, STRING_AGG(WAREHOUSE_ID, ' | ') AS WAREHOUSE_ID_GROUP
							FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_SHIPPING rvsbssos
									GROUP BY ORDER_ID
	                           				,ITEM_INDEX
		   				  ) URVSBSSOS  ON RVSBSSOI.ORDER_ID = URVSBSSOS.ORDER_ID 
		   				              AND RVSBSSOI.ITEM_INDEX = URVSBSSOS.ITEM_INDEX
					LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SALES_ORDER RVSBSO  /* (SSG BR - ORDER) */ 	
					ON (RVSBSSOL.MARKETPLACE_ORDER_ID = RVSBSO.ORDER_ID)   				            
					LEFT JOIN U_PRJ_ECOM.ODS_VTEX_SSG_BR_SHOP_DATA_ENTITIES_STORES_SDS OVSBSDESS 
					ON ((CASE WHEN (CASE
								-- CD_STORE_INFORMATION
					       			WHEN RVSBSSOL.CD_STORE_INFORMATION IS NOT NULL 
									THEN RVSBSSOL.CD_STORE_INFORMATION
									ELSE RVSBSO.CD_STORE_INFORMATION
							  END) IS NOT NULL 
								THEN(CASE
									 -- CD_STORE_INFORMATION 
									 WHEN RVSBSSOL.CD_STORE_INFORMATION IS NOT NULL 
									 	THEN RVSBSSOL.CD_STORE_INFORMATION
										ELSE RVSBSO.CD_STORE_INFORMATION
								     END)
								ELSE(CASE
									  -- UTM_SOURCE
									  WHEN RVSBSSOL.UTM_SOURCE IS NOT NULL 
									  	THEN RVSBSSOL.UTM_SOURCE
										ELSE RVSBSO.UTM_SOURCE
								    END)
						END) = OVSBSDESS.ID_STORE)	
	        WHERE  1=1
	        --AND YEAR(TO_DATE(RVSBSSOL.CREATION_TIMESTAMP)) >= YEAR(ADD_YEARS(CURRENT_DATE,-1)) --TO_DATE(RVSBSSOL.CREATION_TIMESTAMP) >= '2023.01.01'
	        AND RVSBSSOL.STATUS_DESCRIPTION IS NOT NULL
				)
	
	WHERE ROW_NUM = 1
	) URVSBSSOL
	        ON (ONFNCLIDOI."ASSIGNMENT" = URVSBSSOL."SEQUENCE" OR ONFNCLIDOI."ASSIGNMENT" = URVSBSSOL.ORDER_ID)
		LEFT JOIN OW_LAO.DIM_AFFILIATE_CHANNEL DAC ON 
		DAC.AFFILIATE_ID = OW_LAO.AFFILIATE_ID_ADJUSTED(URVSBSSOL.ID_STORE, URVSBSSOL.AFFILIATE_ID, URVSBSSOL.SALES_CHANNEL)
		LEFT JOIN OW_MD.DIM_PRODUCT DP ON (URVSBSSOL.REF_ID = DP.SKU)
		LEFT JOIN OW_MD.MAP_AR_MONTH_KEY_GL_ACCOUNT MKGA ON (ONFNCLIDOI."G/L_ACCOUNT" = MKGA.GL_ACCT)
		LEFT JOIN OW_MD.MAP_AR_MONTH_CUSTOMER MAC ON (ONFNCLIDOI.CUSTOMER = MAC.CUSTOMER_CODE)
		--WHERE ONFNCLIDOI.ROW_NUM = 1
) FNL
;
CALL OW_LAO.PROC_D2C_AR_TABLE_MONTH_PT2;
END
