
CREATE PROCEDURE OW_LAO.PROC_D2C_NERP_WH_OPERATION_PENDING
 
LANGUAGE SQLSCRIPT as
 
BEGIN
--Truncar Tabela com os dados no nivel granular mais baixo para tratamento de dados 
TRUNCATE TABLE OW_LAO.FT_D2C_NERP_WH_OPERATION_PENDING;
	
--Inserir os dados no nivel granular mais baixo na tabela de transformação
INSERT INTO OW_LAO.FT_D2C_NERP_WH_OPERATION_PENDING
SELECT DS.SUBSIDIARY
	,DP.PRODUCT_GROUP_1 AS DIMPROD_PRODUCT_GROUP
	,DP."DIVISION" AS DIMPROD_DIVISION
	,DP.PRODUCT_1 AS DIMPROD_PRODUCT
	,ONZOT.DELIVERY_NO
	,ONZOT.PLANT
	,DP2.ORIGIN AS PLANT_NAME
	,(SELECT CASE WHEN (SUM(WORK_DAY_SEDA)-1) = -1 
			THEN 0 
		      WHEN (WEEKDAY(TO_DATE(ONZOT.PLANNED_GI)) IN (5,6) 
		      AND WEEKDAY(TO_DATE(CURRENT_DATE)) IN (5,6)) 
		      	THEN SUM(WORK_DAY_SEDA) 
		      	ELSE (SUM(WORK_DAY_SEDA)-1) 
		END
		FROM OW_MD.DIM_CALENDAR DC 
		WHERE (YYYYMMDD BETWEEN TO_DATE(ONZOT.PLANNED_GI) AND TO_DATE(CURRENT_DATE))
	) AS "PENDING_DAY_WK" 
	,(DAYS_BETWEEN(TO_DATE(ONZOT.PLANNED_GI), TO_DATE(CURRENT_DATE))) AS "PENDING_DAY"
	,TO_DATE(ONZASOT.SO_LOCAL_CREATE_ON_D) AS  SO_CREATED_ON 
	,TO_DATE(ONZOT.DOCUMENT_DATE_LOCAL) AS DOCUMENT_DATE_LOCAL
	,TO_DATE(ONZOT.NOTA_POSTING_DATE) AS NOTA_POSTING_DATE
	,TO_DATE(ONZOT.PLANNED_GI) AS PLANNED_GI
	,TO_DATE(ONZOT.RDD_SO_ITEM) AS RDD_SO_ITEM
	,TO_DATE(ONZOT.DELIVERY_DATE) AS DELIVERY_DATE
	,ONZASOT.SALES_DOCUMENT
	,ONZOT.REFERENCE_DOC_SO_PO
	,ONZOT.MATERIAL
	,ONZOT.DELIVERY_QTY
	,ONZOT.STORAGE_LOCATION
	,NULL AS LAST_UPDATE
	
FROM OW_LAO.ODS_NERP_ZLLEJ50090_OUTBOUND_TRACKING ONZOT 
LEFT JOIN OW_LAO.ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING  ONZASOT ON (ONZOT.REFERENCE_DOC_SO_PO = ONZASOT.SALES_DOCUMENT AND ONZOT.MATERIAL = ONZASOT.MATERIAL 
AND ONZOT.DELIVERY_ITEM = ONZASOT.DELIVERY_ITEM AND ONZOT.DELIVERY_NO = ONZASOT.DELIVERY)
LEFT JOIN OW_MD.DIM_SUBSIDIARY DS ON ONZOT.SALES_ORG = DS.SALES_ORG
LEFT JOIN OW_MD.DIM_PRODUCT DP ON ONZOT.MATERIAL  = DP.SKU 
LEFT JOIN OW_MD.DIM_PLANT DP2 ON ONZOT.PLANT = DP2.PLANT_CODE
WHERE ONZOT."1ST_GI_DATE" IS NULL AND ONZOT.SO_TYPE = 'YS10' -- AND ONZASOT.SALES_DOC_TYPE = 'YS10'
AND ONZOT.DO_TYPE = 'ZND1'
--AND ONZOT.SHIPPING_TYPE  IN ('P3','P4')
AND ONZASOT.REJECT_REASON IS NULL 
AND ONZASOT.REJECT_REASON_1 IS NULL 
ORDER BY ONZOT.DOCUMENT_DATE_LOCAL DESC 
;
-- Update para Setar o horário de carga. Obs.: Estou fazendo aqui para não ter probemas com milisegundos
UPDATE OW_LAO.FT_D2C_NERP_WH_OPERATION_PENDING
	SET LAST_UPDATE = NOW()
	WHERE LAST_UPDATE IS NULL;
END