/***********************************************************************************************
CREATED BY : Luciano Mariani
CREATION DATE : 2025-01-20
CALL OW_LAO.PROC_D2C_VTEX_PO_TARGET_LAUNCH_S25 
***********************************************************************************************/
CREATE PROCEDURE OW_LAO.PROC_D2C_VTEX_PO_TARGET_LAUNCH_S25
LANGUAGE SQLSCRIPT
AS
BEGIN
	IF EXISTS ( SELECT '' FROM SYS.TABLES WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TF_D2C_VTEX_PO_TARGET_LAUNCH_S25' ) THEN
		DROP TABLE OW_LAO.TF_D2C_VTEX_PO_TARGET_LAUNCH_S25;
	END IF;
	CREATE TABLE OW_LAO.TF_D2C_VTEX_PO_TARGET_LAUNCH_S25 AS (
		SELECT 
			  TG.MARKETING_NAME	
			, TG.COLOR
			, TG.PA_SE
			, TG.PA_MAO
			, TG.CHANNEL
			, TG.SUB_CANAL
			, TG."DAY"
			, TG."HOUR"
			, TG.TARGET
			, IFNULL(AC.QTY_APPROVED,0) AS ACTUAL_APPROVED
			--, IFNULL(AC.QTY_CANCELED,0) AS QTY_CANCELED
			, IFNULL(AC.QTY_PENDING,0) AS ACTUAL_PENDING
			, TG.OLD_FAMILY
			--, TG.FILE_NAME
			--, TG.LAST_MODIFICATION_FILE
			--, TG.LOAD_DATE
			--, CURRENT_TIMESTAMP AS KPI_LAST_UPDATE --,KPI_LAST_UPDATE	
			, (
				SELECT MAX(PO_CREATION_DATE)
				FROM OW_LAO.TF_D2C_NERP_SALES
				WHERE "SOURCE" = 'PO'
					AND SUBSIDIARY = 'SEDA'
			  ) AS KPI_LAST_UPDATE
		FROM OW_MD.TARGET_LAUNCH_S25 TG
		LEFT JOIN
			(
				SELECT 
					  TS.PA_SE
					, TS.PA_MAO
					, NS.AFFILIATE_CHANNEL -- AS "TARGET_CANAL.CHANNEL"
					, NS.AFFILIATE_SUB_CHANNEL -- AS SUB_CANAL	
					, NS.DATE_REF -- AS "DAY"
					, NS.PO_HOUR -- AS "HOUR" 
					, SUM(CASE WHEN ST.STATUS_GROUP = 'Approved' THEN NS.QTY END) AS QTY_Approved
					, SUM(CASE WHEN ST.STATUS_GROUP = 'Canceled' THEN NS.QTY END) AS QTY_Canceled
					, SUM(CASE WHEN ST.STATUS_GROUP = 'Pending' THEN NS.QTY END) AS QTY_Pending
				FROM OW_LAO.TF_D2C_NERP_SALES NS
					INNER JOIN OW_MD.TARGET_LAUNCH_S25_STATUS_VTEX ST
						ON ST.STATUS_VTEX = NS.STATUS_PO
					INNER JOIN OW_MD.TARGET_LAUNCH_S25_SKU TS
						ON TS.SKU = NS.REFERENCE_CODE  --- **************** INSERIR *****************
							-- (CASE WHEN TS.SKU = 'SM-S931BDBJZTO' THEN 'SM-S926BZAKZTO' ELSE TS.SKU END ) = NS.REFERENCE_CODE  --- ****************RETIRAR*****************
				WHERE NS.SUBSIDIARY = 'SEDA'
				    AND NS.SOURCE = 'PO'
					AND TO_DATE(NS.DATE_REF) IN (
						SELECT DISTINCT 
							TO_DATE("DAY") AS DATE_REF
						FROM OW_MD.TARGET_LAUNCH_S25
					)
					GROUP BY
					  TS.PA_SE
					, TS.PA_MAO
					, NS.AFFILIATE_CHANNEL -- AS "TARGET_CANAL.CHANNEL"
					, NS.AFFILIATE_SUB_CHANNEL -- AS SUB_CANAL	
					, NS.DATE_REF -- AS "DAY"
					, NS.PO_HOUR -- AS "HOUR" 
			) AC 
			ON  AC.PA_SE = TG.PA_SE
				AND AC.PA_MAO = TG.PA_MAO
				AND AC.AFFILIATE_CHANNEL = TG.CHANNEL
				AND AC.AFFILIATE_SUB_CHANNEL  = TG.SUB_CANAL	
				AND AC.DATE_REF = TO_DATE(TG."DAY")
				AND AC.PO_HOUR = TG."HOUR" 
			WHERE 1=1
	);
END		
		