
CREATE PROCEDURE OW_LAO.PROC_D2C_NERP_DELIVERY_PENDING
LANGUAGE SQLSCRIPT as
BEGIN
--Truncate tabela referente as informações de Delivery Pending
TRUNCATE TABLE OW_LAO.FT_D2C_NERP_DELIVERY_PENDING;
--Cria tabela referente  as informações de Delivery Pending
INSERT INTO OW_LAO.FT_D2C_NERP_DELIVERY_PENDING
SELECT 	DS.SUBSIDIARY--1
	,ONZOT.REGION AS STATE --2
	,ONZOT.CITY --3
	,ONZOT.TRANSPORTER_NAME--4
	,ONZOT.PLANT--5
	,DP."DIVISION" AS DIMPROD_DIVISION 
	,DP.PRODUCT_GROUP_1 AS DIMPROD_PRODUCT_GROUP 
	,DP.PRODUCT_1 AS DIMPROD_PRODUCT 
	,DP2.ORIGIN AS PLANT_NAME --6
	,ONZOT.DELIVERY_NO --7
	,ONZOT.MATERIAL
	,ONZOT.REFERENCE_DOC_SO_PO  --8
	,ONZOT."1ST_GI_DATE" --9 
	,ONZOT.PLANNED_GI 
	,ONZOT.DELIVERY_DATE
	,ONZOT.RDD_SO_ITEM
	,(
	  SELECT CASE WHEN (SUM(WORK_DAY_SEDA)-1) = -1 
	  		THEN 0 
	  	      WHEN (WEEKDAY(TO_DATE(ONZOT."1ST_GI_DATE")) IN (5,6) 
	  	      AND WEEKDAY(TO_DATE(CURRENT_DATE)) IN (5,6)) 
	  	      	THEN SUM(WORK_DAY_SEDA) 
	  	      	ELSE (SUM(WORK_DAY_SEDA)-1) 
	  	END
	FROM OW_MD.DIM_CALENDAR DC 
	WHERE (YYYYMMDD BETWEEN TO_DATE(ONZOT."1ST_GI_DATE") AND TO_DATE(CURRENT_DATE))
	) AS "LT_GI_IOD" 
	,(CASE WHEN DS.SUBSIDIARY = 'SEDA' AND (ONZOT.SPI = 'CR02' OR ONZOT.SPI = 'AGS1') 
		THEN COALESCE((SELECT CASE WHEN (SUM(WORK_DAY_SEDA)-1) = -1 
						THEN 0 
					     WHEN (WEEKDAY(TO_DATE(ONZOT.PLANNED_GI)) IN (5,6) 
					     AND WEEKDAY(TO_DATE(ONZOT.DELIVERY_DATE)) IN (5,6)) 
					     	THEN SUM(WORK_DAY_SEDA) 
					     	ELSE (SUM(WORK_DAY_SEDA)-1) 
					     END
				FROM OW_MD.DIM_CALENDAR DC 
				WHERE (YYYYMMDD BETWEEN TO_DATE(ONZOT.PLANNED_GI) AND TO_DATE(ONZOT.DELIVERY_DATE))),0)
		ELSE COALESCE((SELECT CASE WHEN (SUM(WORK_DAY_SEDA)-1) = -1 
						THEN 0 
					     WHEN (WEEKDAY(TO_DATE(ONZOT.PLANNED_GI)) IN (5,6) 
					     AND WEEKDAY(TO_DATE(ONZOT.RDD_SO_ITEM)) IN (5,6)) 
					     	THEN SUM(WORK_DAY_SEDA) 
					     	ELSE (SUM(WORK_DAY_SEDA)-1) 
					     END
				FROM OW_MD.DIM_CALENDAR DC 
				WHERE (YYYYMMDD BETWEEN TO_DATE(ONZOT.PLANNED_GI) AND TO_DATE(ONZOT.RDD_SO_ITEM))),0)
	END) AS "TGT_WK_GI_IOD"
	--,DLTW.LEAD_TIME_GI_IOD AS "Target LT_GI_IOD" 
	,CASE WHEN ((SELECT CASE WHEN (SUM(WORK_DAY_SEDA)-1) = -1 
					THEN 0 
				WHEN (WEEKDAY(TO_DATE(ONZOT."1ST_GI_DATE")) IN (5,6) AND WEEKDAY(TO_DATE(CURRENT_DATE)) IN (5,6)) 
					THEN SUM(WORK_DAY_SEDA) 
					ELSE (SUM(WORK_DAY_SEDA)-1) 
			    END
		     FROM OW_MD.DIM_CALENDAR DC 
		     WHERE (YYYYMMDD BETWEEN TO_DATE(ONZOT."1ST_GI_DATE") AND TO_DATE(CURRENT_DATE)))
		     -/*DLTW.LEAD_TIME_GI_IOD*/
		     (CASE WHEN DS.SUBSIDIARY = 'SEDA' AND (ONZOT.SPI = 'CR02' OR ONZOT.SPI = 'AGS1') 
				THEN COALESCE((SELECT CASE WHEN (SUM(WORK_DAY_SEDA)-1) = -1 
					       			THEN 0 
					     		   WHEN (WEEKDAY(TO_DATE(ONZOT.PLANNED_GI)) IN (5,6) 
					     		   AND WEEKDAY(TO_DATE(ONZOT.DELIVERY_DATE)) IN (5,6)) 
					     			THEN SUM(WORK_DAY_SEDA) 
					     			ELSE (SUM(WORK_DAY_SEDA)-1) 
					     	      END
				FROM OW_MD.DIM_CALENDAR DC 
		WHERE (YYYYMMDD BETWEEN TO_DATE(ONZOT.PLANNED_GI) AND TO_DATE(ONZOT.DELIVERY_DATE))),0)
				ELSE COALESCE((SELECT CASE WHEN (SUM(WORK_DAY_SEDA)-1) = -1 
					       			THEN 0 
					     		   WHEN (WEEKDAY(TO_DATE(ONZOT.PLANNED_GI)) IN (5,6) 
					     		   AND WEEKDAY(TO_DATE(ONZOT.RDD_SO_ITEM)) IN (5,6)) 
					     			THEN SUM(WORK_DAY_SEDA) 
					     			ELSE (SUM(WORK_DAY_SEDA)-1) 
					     	      END
				FROM OW_MD.DIM_CALENDAR DC 
		WHERE (YYYYMMDD BETWEEN TO_DATE(ONZOT.PLANNED_GI) AND TO_DATE(ONZOT.RDD_SO_ITEM))),0)
		END)     ) <= 0 
		     
		     THEN 0 
		     ELSE ((SELECT CASE WHEN (SUM(WORK_DAY_SEDA)-1) = -1 
		     		 		THEN 0 
		     		 	WHEN (WEEKDAY(TO_DATE(ONZOT."1ST_GI_DATE")) IN (5,6) 
		     	    		AND WEEKDAY(TO_DATE(CURRENT_DATE)) IN (5,6)) 
		     	    			THEN SUM(WORK_DAY_SEDA) 
		     	    			ELSE (SUM(WORK_DAY_SEDA)-1) 
		     	    	   END
			   FROM OW_MD.DIM_CALENDAR DC WHERE (YYYYMMDD BETWEEN TO_DATE(ONZOT."1ST_GI_DATE") AND TO_DATE(CURRENT_DATE)))
			   -/*DLTW.LEAD_TIME_GI_IOD*/
			   (CASE WHEN DS.SUBSIDIARY = 'SEDA' AND (ONZOT.SPI = 'CR02' OR ONZOT.SPI = 'AGS1') 
					THEN COALESCE((SELECT CASE WHEN (SUM(WORK_DAY_SEDA)-1) = -1 
				       			THEN 0 
				     		   WHEN (WEEKDAY(TO_DATE(ONZOT.PLANNED_GI)) IN (5,6) 
				     		   AND WEEKDAY(TO_DATE(ONZOT.DELIVERY_DATE)) IN (5,6)) 
				     			THEN SUM(WORK_DAY_SEDA) 
				     			ELSE (SUM(WORK_DAY_SEDA)-1) 
				     	      END
					FROM OW_MD.DIM_CALENDAR DC 
						WHERE (YYYYMMDD BETWEEN TO_DATE(ONZOT.PLANNED_GI) AND TO_DATE(ONZOT.DELIVERY_DATE))),0)
					ELSE COALESCE((SELECT CASE WHEN (SUM(WORK_DAY_SEDA)-1) = -1 
				       			THEN 0 
				     		   WHEN (WEEKDAY(TO_DATE(ONZOT.PLANNED_GI)) IN (5,6) 
				     		   AND WEEKDAY(TO_DATE(ONZOT.RDD_SO_ITEM)) IN (5,6)) 
				     			THEN SUM(WORK_DAY_SEDA) 
				     			ELSE (SUM(WORK_DAY_SEDA)-1) 
				     	      END
					FROM OW_MD.DIM_CALENDAR DC 
						WHERE (YYYYMMDD BETWEEN TO_DATE(ONZOT.PLANNED_GI) AND TO_DATE(ONZOT.RDD_SO_ITEM))),0)
			  END)
			   ) 
	END AS LEAD_TIME_VS_TARGET_LEAD_TIME
	,(DAYS_BETWEEN(TO_DATE(ONZOT."1ST_GI_DATE"),TO_DATE(CURRENT_DATE))) AS "LT_CAL_GI_IOD" 
	,(CASE WHEN DS.SUBSIDIARY = 'SEDA' AND (ONZOT.SPI = 'CR02' OR ONZOT.SPI = 'AGS1') 
		THEN COALESCE(DAYS_BETWEEN(TO_DATE(ONZOT.PLANNED_GI),TO_DATE(ONZOT.DELIVERY_DATE)),0)
		ELSE COALESCE(DAYS_BETWEEN(TO_DATE(ONZOT.PLANNED_GI),TO_DATE(ONZOT.RDD_SO_ITEM)),0)
	END) AS "TGT_CAL_GI_IOD"
	
	--,DLTW.LEAD_TIME_GI_IOD AS "Target LT_GI_IOD" 
	,CASE WHEN ((DAYS_BETWEEN(TO_DATE(ONZOT."1ST_GI_DATE"), TO_DATE(CURRENT_DATE)))
		     -/*DLTW.LEAD_TIME_GI_IOD*/
		     (CASE WHEN DS.SUBSIDIARY = 'SEDA' AND (ONZOT.SPI = 'CR02' OR ONZOT.SPI = 'AGS1') 
				THEN COALESCE(DAYS_BETWEEN(TO_DATE(ONZOT.PLANNED_GI), TO_DATE(ONZOT.DELIVERY_DATE)),0)
				ELSE COALESCE(DAYS_BETWEEN(TO_DATE(ONZOT.PLANNED_GI), TO_DATE(ONZOT.RDD_SO_ITEM)),0)
		     END)
		     ) <= 0 
		     
		     THEN 0 
		     ELSE ((DAYS_BETWEEN(TO_DATE(ONZOT."1ST_GI_DATE"),TO_DATE(CURRENT_DATE)))
			   -/*DLTW.LEAD_TIME_GI_IOD*/
		     (CASE WHEN DS.SUBSIDIARY = 'SEDA' AND (ONZOT.SPI = 'CR02' OR ONZOT.SPI = 'AGS1') 
				THEN COALESCE(DAYS_BETWEEN(TO_DATE(ONZOT.PLANNED_GI), TO_DATE(ONZOT.DELIVERY_DATE)),0)
				ELSE COALESCE(DAYS_BETWEEN(TO_DATE(ONZOT.PLANNED_GI), TO_DATE(ONZOT.RDD_SO_ITEM)),0)
		     END)			   
			   ) 
	END AS LEAD_TIME_CAL_VS_TARGET_LEAD_TIME_CAL
	,ONZOT.DELIVERY_QTY AS ORDER_QTY 
	--,(SELECT DC.YYYY FROM OW_MD.DIM_CALENDAR DC WHERE DC.YYYYMMDD = TO_DATE(ONZOT."1ST_GI_DATE")) AS "YEAR" --5
	--,(SELECT DC.YYYYQQ FROM OW_MD.DIM_CALENDAR DC WHERE DC.YYYYMMDD = TO_DATE(ONZOT."1ST_GI_DATE")) AS "QUARTER" --6
	--,(SELECT DC.YYYYMM FROM OW_MD.DIM_CALENDAR DC WHERE DC.YYYYMMDD = TO_DATE(ONZOT."1ST_GI_DATE")) AS "YEAR_MONTH"
	--,(SELECT DC.YYYYWW FROM OW_MD.DIM_CALENDAR DC WHERE DC.YYYYMMDD = TO_DATE(ONZOT."1ST_GI_DATE")) AS "WEEK" --7
	, NULL AS LAST_UPDATE
FROM OW_LAO.ODS_NERP_ZLLEJ50090_OUTBOUND_TRACKING ONZOT
LEFT JOIN OW_LAO.ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING ONZASOT ON (ONZOT.REFERENCE_DOC_SO_PO = ONZASOT.SALES_DOCUMENT AND ONZOT.MATERIAL = ONZASOT.MATERIAL 
AND ONZOT.DELIVERY_ITEM = ONZASOT.DELIVERY_ITEM AND ONZOT.DELIVERY_NO = ONZASOT.DELIVERY)
/*
LEFT JOIN ( 	SELECT ORDER_ID, SALES_CHANNEL, CREATION_TIMESTAMP FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SALES_ORDER UNION
		SELECT ORDER_ID, SALES_CHANNEL, CREATION_TIMESTAMP FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER
	  ) URVSSO ON ONZASOT.CUSTOMER_PO = URVSSO.ORDER_ID	-- VERIFICAR ESSE JOIN
LEFT JOIN (	SELECT ORDER_ID, SALES_CHANNEL, "SEQUENCE", CREATION_TIMESTAMP FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SALES_ORDER UNION
		SELECT ORDER_ID, SALES_CHANNEL, "SEQUENCE", CREATION_TIMESTAMP FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER
	  ) URVSSO2 ON ONZASOT.CUSTOMER_PO = URVSSO2."SEQUENCE" -- VERIFICAR ESSE JOIN
*/
--LEFT JOIN OW_MD.DIM_LEAD_TIME_UF DLTU ON (ONZOT.REGION = DLTU.DESTINATION) --plant
LEFT JOIN OW_MD.DIM_SUBSIDIARY DS ON ONZOT.SALES_ORG = DS.SALES_ORG
LEFT JOIN OW_MD.DIM_PLANT DP2 ON (ONZOT.PLANT = DP2.PLANT_CODE) 
--LEFT JOIN OW_MD.DIM_LEAD_TIME_WH DLTW ON (DP2.ORIGIN = DLTW."FROM" AND ONZOT.REGION = DLTW."TO")
LEFT JOIN OW_MD.DIM_PRODUCT DP ON (ONZOT.MATERIAL = DP.SKU) 
--LEFT JOIN OW_MD.DIM_TARGET_LEAD_TIME_WORKING_DAY DTLTWD ON (DS.SUBSIDIARY = DTLTWD.SUBSIDIARY)
	WHERE ONZOT."1ST_GI_DATE" IS NOT NULL 
	AND (ONZOT.EPOD_DATE IS NULL AND ONZOT."2ND_GI_DATE" IS NULL)
	AND ONZOT.SO_TYPE = 'YS10' -- AND ONZASOT.SALES_DOC_TYPE = 'YS10'
	AND ONZOT.DO_TYPE = 'ZND1'
--	AND ONZOT.SHIPPING_TYPE  IN ('P3','P4')
	AND ONZASOT.REJECT_REASON IS NULL 
--	AND ONZOT.DELIVERY_NO NOT IN (SELECT REFERENCE_NO FROM OW_LAO.ODS_NERP_ZLLEB57910_CLAIM_FOLDER WHERE REFERENCE_NO IS NOT NULL)
	AND ONZOT.DELIVERY_NO NOT IN (SELECT DELIVERY_NO FROM OW_LAO.ODS_NERP_ZLLEB57910_CLAIM_FOLDER WHERE DELIVERY_NO IS NOT NULL)	
AND ONZASOT.REJECT_REASON_1 IS NULL 
;
-- Update para Setar o horário de carga. Obs.: Estou fazendo aqui para não ter probemas com milisegundos
UPDATE OW_LAO.FT_D2C_NERP_DELIVERY_PENDING
	SET LAST_UPDATE = NOW()
	WHERE LAST_UPDATE IS NULL;
END
