CREATE PROCEDURE OW_LAO.PROC_D2C_DIM_SOLD_TO
LANGUAGE SQLSCRIPT as
BEGIN
INSERT INTO OW_LAO.DIM_SOLD_TO
SELECT DISTINCT SUBSIDIARY 
				,SOLD_TO_PARTY 
				,LOAD_DATE 
FROM (
SELECT DISTINCT DS.SUBSIDIARY
				--, AP2_NAME
				, SOLD_TO_PARTY
				--, NAME
				, NOW() AS LOAD_DATE
FROM OW_LAO.ODS_NERP_ZLLEJ50090_OUTBOUND_TRACKING ONZOT
LEFT JOIN OW_LAO.ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING ONZASOT ON (
ONZOT.REFERENCE_DOC_SO_PO = ONZASOT.SALES_DOCUMENT 
                       AND ONZOT.MATERIAL = ONZASOT.MATERIAL 
                       AND ONZOT.DELIVERY_ITEM = ONZASOT.DELIVERY_ITEM 
                       AND ONZOT.DELIVERY_NO = ONZASOT.DELIVERY) 
LEFT JOIN OW_MD.DIM_SUBSIDIARY DS ON (ONZOT.SALES_ORG = DS.SALES_ORG)
WHERE (TO_DATE(ONZASOT.LOAD_DATE) BETWEEN ADD_DAYS(CURRENT_DATE,-30) AND CURRENT_DATE)
          AND ONZOT.SO_TYPE = 'YS10'
          AND ONZOT.DO_TYPE = 'ZND1'
          AND ONZASOT.REJECT_REASON IS NULL 
          AND ONZASOT.REJECT_REASON_1 IS NULL 
)
UNION  ALL 
SELECT DISTINCT SUBSIDIARY 
				,SOLD_TO_PARTY 
				,NOW() AS LOAD_DATE 
FROM (
SELECT 'SELA' AS SUBSIDIARY ,1480984 AS SOLD_TO_PARTY FROM DUMMY
UNION ALL 
SELECT 'SELA' AS SUBSIDIARY ,2358558 AS SOLD_TO_PARTY FROM DUMMY
UNION ALL 
SELECT 'SELA' AS SUBSIDIARY ,3183649 AS SOLD_TO_PARTY FROM DUMMY
UNION ALL 
SELECT 'SELA' AS SUBSIDIARY ,4499796 AS SOLD_TO_PARTY FROM DUMMY
UNION ALL 
SELECT 'SELA' AS SUBSIDIARY ,4757459 AS SOLD_TO_PARTY FROM DUMMY
UNION ALL 
SELECT 'SELA' AS SUBSIDIARY ,4782456 AS SOLD_TO_PARTY FROM DUMMY
UNION ALL 
SELECT 'SELA' AS SUBSIDIARY ,4782457 AS SOLD_TO_PARTY FROM DUMMY
UNION ALL 
SELECT 'SELA' AS SUBSIDIARY ,4918519 AS SOLD_TO_PARTY FROM DUMMY
UNION ALL 
SELECT 'SELA' AS SUBSIDIARY ,4918541 AS SOLD_TO_PARTY FROM DUMMY
)
 ORDER BY  3 DESC, 1 DESC, 2 DESC 
;
END