
CREATE PROCEDURE OW_LAO.PROC_D2C_GSCM_INVENTORY
LANGUAGE SQLSCRIPT as
BEGIN
--Truncate tabela referente as informações de Inventory
TRUNCATE TABLE OW_LAO.FT_D2C_GSCM_INVENTORY;
--Cria tabela referente  as informações de Inventory
INSERT INTO OW_LAO.FT_D2C_GSCM_INVENTORY
SELECT
     IFNULL(DS.SUBSIDIARY, RDGAOH.ORG_2) AS "SUBSIDIARY" 
     ,DP.PRODUCT_GROUP_1 AS DIMPROD_PRODUCT_GROUP
     ,DP."DIVISION" AS DIMPROD_DIVISION
     ,DP.PRODUCT_1 AS DIMPROD_PRODUCT
     ,RDGAOH.ITEM AS SKU
     ,MSL.INV_TYPE
     ,DP2.ORIGIN AS PLANT_NAME
     ,IFNULL(DP2.PLANT_CODE, RDGAOH.PLANT) AS PLANT
     ,RDGAOH.PLANT_DESC
     ,RDGAOH.STORAGE 
     ,RDGAOH.S_LOC_DESC 
     ,RDGAOH.ORG_SITE_ID
     ,SUM(RDGAOH.AVAILABLE) AS AVAILABLE
     ,SUM(RDGAOH.UNAVAILABLE) AS UNAVAILABLE
     ,SUM(RDGAOH.AMOUNT_USD) AS AMOUNT_USD
     ,AVG(RDGAOH.AGING_30) AS AGING_30 
     ,AVG(RDGAOH.AGING_30_60) AS AGING_30_60 
     ,AVG(RDGAOH.AGING_60) AS AGING_60
     ,DC.YYYYWW AS "YEAR_WEEK"
     ,DC.YYYYMMDD AS "DATE"
     ,NOW() AS "LOAD_DATE"
FROM OW_LAO.RAW_DATA_GSCM_ACTUAL_ON_HAND RDGAOH
LEFT JOIN OW_MD.DIM_SUBSIDIARY DS ON
     ((CASE
           WHEN RDGAOH.ORG_2 = 'SELA-MI' THEN 'SELA-M'
           WHEN RDGAOH.ORG_2 = 'SELA-PA' THEN 'SELA-P'
           ELSE RDGAOH.ORG_2
     END) = DS.SUBSIDIARY)
LEFT JOIN OW_MD.DIM_PRODUCT DP ON (RDGAOH.ITEM = DP.SKU)
LEFT JOIN OW_MD.DIM_CALENDAR DC ON
     (TO_DATE((RIGHT(SUBSTR_BEFORE(UPPER(RDGAOH.FILE_NAME), '.XLSX'), 8)), 'YYYYMMDD') = DC.YYYYMMDD )
LEFT JOIN OW_MD.DIM_PLANT DP2 ON (RDGAOH.PLANT = DP2.PLANT_CODE)
LEFT JOIN OW_MD.MAP_STORAGE_LOCATION MSL ON (RDGAOH.PLANT = MSL.PLANT  AND RDGAOH.STORAGE  = MSL.S_LOC)
GROUP BY 
     IFNULL(DS.SUBSIDIARY, RDGAOH.ORG_2)
     ,DP.PRODUCT_GROUP_1
     ,DP."DIVISION"
     ,DP.PRODUCT_1
     ,RDGAOH.ITEM
     ,MSL.INV_TYPE
     ,DP2.ORIGIN
     ,IFNULL(DP2.PLANT_CODE, RDGAOH.PLANT)
     ,RDGAOH.PLANT_DESC
     ,RDGAOH.STORAGE 
     ,RDGAOH.S_LOC_DESC 
     ,RDGAOH.ORG_SITE_ID
     ,DC.YYYYWW
     ,DC.YYYYMMDD
     ,NOW()
;    
END
