CREATE PROCEDURE PROC_CRAWLING_AP1_WERABLES_PT1
LANGUAGE SQLSCRIPT as
BEGIN
--DELETAR dia aTUAL da fATO para EVITAR DUPLICIDADE
delete from OW_LAO.FT_CRAWLING_AP1_WERABLES_SEGMENT
where "PROCESS_DATETIME" = CURRENT_DATE
;
--CARREGAR A  FT_CRAWLING_AP1_WERABLES_SEGMENT
INSERT INTO  OW_LAO.FT_CRAWLING_AP1_WERABLES_SEGMENT
select 
DETAIL_PRICE."PROD_BRAND" as "BRAND_NM"
,DETAIL_PRICE."DESC" as "MODEL_DESC"
,DETAIL_PRICE."AP2" as "SUBSIDIARY"
,DETAIL_PRICE."COUNTRY" as "COUNTRY"
,DETAIL_PRICE."COMPANY_NAME" as "SITE_COMPANY_NAME"
,DETAIL_PRICE."VENDOR"
,DETAIL_PRICE."SITE" as "SITE_NM"
,DETAIL_PRICE."PROD_HREF" as "SITE_URL"
,DETAIL_PRICE."PAGE_NUMBER" as "SITE_PAGE"
,DETAIL_PRICE."POSITION" as "SITE_POSITION"
,DETAIL_PRICE."CURRENCY" as "SITE_PRICE_CURRENCY"
,SUBSTRING_REGEXPR('\d+(\.\d{1,2})?' IN UPPER(TRIM( REPLACE(RATING, ',','.'))) FROM 1 OCCURRENCE 1) as "SITE_RATING"
,SUBSTRING_REGEXPR('\d+(\.\d{1,2})?' IN UPPER(TRIM( REPLACE(RATING_AMOUNT, ',','.'))) FROM 1 OCCURRENCE 1) as  "SITE_RATING_AMOUNT"
,DETAIL_PRICE."RATING_SCALE" as"SITE_RATING_SCALE"
,DETAIL_PRICE."TODAY_DATE" as REFER_DATE
,TO_DECIMAL(DETAIL_PRICE."DE_VALUE")  as PRICE_LOCAL_BASE
,TO_DECIMAL(DETAIL_PRICE."POR_VALUE") as PRICE_LOCAL_ACT
,CURRENT_DATE as "PROCESS_DATETIME"
,DETAIL_PRICE."CURRENCY" as "FROM_CURRENCY"
,'USD' as "TO_CURRENCY"
,ER.VALID_FROM  
,ER.EXCHANGE_RATE
,CASE WHEN 	DETAIL_PRICE.CURRENCY='UDS' then  TO_DECIMAL("DE_VALUE") else  TO_DECIMAL("DE_VALUE"/EXCHANGE_RATE, 21,5) end as PRICE_LOCAL_BASE_USD
,CASE WHEN 	DETAIL_PRICE.CURRENCY='UDS' then  TO_DECIMAL("POR_VALUE") else TO_DECIMAL("POR_VALUE"/EXCHANGE_RATE,21,5) end as PRICE_LOCAL_ACT_USD
,DETAIL_PRICE."INITIAL_URL"
,D."REFER_WEEK"
,D."REFER_WEEK_T"
,D."REFER_YEAR"
from(
SELECT DISTINCT
case when length(P."DE_VALUE")!=0 then P."DE_VALUE" else NULL end as "DE_VALUE" ,
P."INITIAL_URL",
P."PAGE_NUMBER",
case when length(P."POR_VALUE")!=0 then P."POR_VALUE" else NULL end as "POR_VALUE",
P."POSITION",
P."PRODUCT_TYPE",
P."REPEAT",
P."SUB",
P."TODAY_DATE",
P."TODAY_DATE_LONG",
P."TODAY_DATE_TIME",
D.*	 
from 
 "OW_LAO"."ODS_CRAWLING_AP1_WEARABLES_PRODUCT_DETAIL" D
left join 
(
select 
row_number() over  (partition by "KEY" order by  "TODAY_DATE" desc) as RANK,
"INITIAL_URL",
"KEY",
REPLACE("DE_VALUE",'$','') AS "DE_VALUE",
"PAGE_NUMBER",
"PRODUCT_TYPE",
REPLACE("POR_VALUE",'$','') AS "POR_VALUE",
"POSITION",
"REPEAT",
"SITE",
"TODAY_DATE_LONG",
"TODAY_DATE_TIME",
"SUB",
"TODAY_DATE",
"AVAILABLE"
 from "OW_LAO"."ODS_CRAWLING_AP1_IM_PRODUCT_DAILY_PRICE"
 where 
 UPPER(TRIM(PRODUCT_TYPE)) = 'WEARABLES'
 and  to_date(to_char("TODAY_DATE",'dd/mm/yyyy') ,'dd/mm/yyyy') = to_date(to_char(add_days(CURRENT_DATE,-1),'dd/mm/yyyy'),'dd/mm/yyyy')
)
P on D.KEY=P.KEY and P.RANK=1
WHERE 1=1
AND UPPER(TRIM(PRODUCT_TYPE)) = 'WEARABLES'
)DETAIL_PRICE
LEFT JOIN "OW_LAO".FT_AP2_EXCHANGE_RATE ER ON TO_CHAR(DETAIL_PRICE."TODAY_DATE",
	 'YYYY-MM-DD' ) = ER.VALID_FROM  
AND DETAIL_PRICE.CURRENCY = ER.TO_CURRENCY
left join  (SELECT DISTINCT YYYYWW as "REFER_WEEK"  ,YYYYMMDD,'W' || RIGHT(YYYYWW,2) as "REFER_WEEK_T" ,YYYY as "REFER_YEAR" FROM OW_MD.DIM_CALENDAR) D on to_char(DETAIL_PRICE."TODAY_DATE",'YYYY-MM-DD') = to_char(D.YYYYMMDD,'YYYY-MM-DD')
where to_date(to_char("TODAY_DATE",'dd/mm/yyyy') ,'dd/mm/yyyy') = to_date(to_char(add_days(CURRENT_DATE,-1),'dd/mm/yyyy'),'dd/mm/yyyy')
;
END