CREATE PROCEDURE OW_LAO.PROC_D2C_NERP_VS_GSCM_WOS
LANGUAGE SQLSCRIPT as
BEGIN
	
--Truncar Tabela de tratamento 01 com weeks referente ao NERP para cruzar futuramente com os dados de GSCM
TRUNCATE TABLE OW_LAO.TF_D2C_NERP_TO_STOCK_OVERVIEW;	
-- Inserir dados na tabela de tratamento  01 com weeks referente ao NERP 
INSERT INTO OW_LAO.TF_D2C_NERP_TO_STOCK_OVERVIEW
SELECT SUBSIDIARY
,DIMPROD_DIVISION
,DIMPROD_PRODUCT_GROUP
,DIMPROD_PRODUCT
,DIVISION
,MATERIAL
,PLANT
,PLANT_NAME
,TIME_YEAR
,TIME_YEAR_QUARTER
,"WEEK-4"
,"WEEK-3"
,"WEEK-2"
,"WEEK-1"
,TIME_YEAR_WEEK
,"WEEK+1"
,"WEEK+2"
,"WEEK+3"
,"WEEK+4"
,SUM(ON_HAND) AS ON_HAND
,LOAD_DATE FROM (
SELECT 
 DS.SUBSIDIARY 
,DP."DIVISION" AS DIMPROD_DIVISION --2
,DP.PRODUCT_GROUP_1 AS DIMPROD_PRODUCT_GROUP --3
,DP.PRODUCT_1 AS DIMPROD_PRODUCT--4
, (CASE ONZDASO.DIVISON
WHEN 'C1' THEN 'MONITOR'
WHEN 'A1' THEN 'TV'
WHEN 'E2' THEN 'REF'
WHEN 'E4' THEN 'VC'
WHEN 'E3' THEN 'LAUNDRY'
WHEN 'E1' THEN 'A/C_RAC'
WHEN 'A6' THEN 'AV'
WHEN 'C1' THEN 'MONITOR'
WHEN 'G1' THEN 'MOBILE'
WHEN 'E6' THEN 'OTHERS'
WHEN 'C3' THEN 'PC'
END) AS "DIVISION"--5
,ONZDASO.MATERIAL --6
,ONZDASO.PLANT--7
,DP2.ORIGIN AS PLANT_NAME--8
--,TO_DATE((RIGHT(SUBSTR_BEFORE(UPPER(ONZDASO.FILE_NAME),'_AFTERNOON.XLSX'),8)),'DDMMYYYY') AS "DATE_BASE" --7 9 ----Utilizada para pegar os dados de OW_LAO
,TO_DATE((RIGHT(SUBSTR_BEFORE(UPPER(ONZDASO.FILE_NAME),'_MORNING.XLSX'),8)),'DDMMYYYY') AS "DATE_BASE" --Utilizada para pegar os dados de OW_SEDA_S
,DC.YYYY AS "TIME_YEAR"
,DC.YYYYQQ AS "TIME_YEAR_QUARTER"
/*
,(CASE WHEN UPPER(ONZDASO.FILE_NAME) LIKE '%MORNING%' THEN (SELECT DC.YYYYWW FROM OW_MD.DIM_CALENDAR DC WHERE DC.YYYYMMDD = ADD_DAYS(TO_DATE((RIGHT(SUBSTR_BEFORE(UPPER(ONZDASO.FILE_NAME),'_MORNING.XLSX'),8)),'DDMMYYYY'),-28))ELSE NULL END) AS "WEEK-4"
,(CASE WHEN UPPER(ONZDASO.FILE_NAME) LIKE '%MORNING%' THEN (SELECT DC.YYYYWW FROM OW_MD.DIM_CALENDAR DC WHERE DC.YYYYMMDD = ADD_DAYS(TO_DATE((RIGHT(SUBSTR_BEFORE(UPPER(ONZDASO.FILE_NAME),'_MORNING.XLSX'),8)),'DDMMYYYY'),-21))ELSE NULL END) AS "WEEK-3"
,(CASE WHEN UPPER(ONZDASO.FILE_NAME) LIKE '%MORNING%' THEN (SELECT DC.YYYYWW FROM OW_MD.DIM_CALENDAR DC WHERE DC.YYYYMMDD = ADD_DAYS(TO_DATE((RIGHT(SUBSTR_BEFORE(UPPER(ONZDASO.FILE_NAME),'_MORNING.XLSX'),8)),'DDMMYYYY'),-14))ELSE NULL END) AS "WEEK-2"
,(CASE WHEN UPPER(ONZDASO.FILE_NAME) LIKE '%MORNING%' THEN (SELECT DC.YYYYWW FROM OW_MD.DIM_CALENDAR DC WHERE DC.YYYYMMDD = ADD_DAYS(TO_DATE((RIGHT(SUBSTR_BEFORE(UPPER(ONZDASO.FILE_NAME),'_MORNING.XLSX'),8)),'DDMMYYYY'),-7))ELSE NULL END) AS "WEEK-1"
*/
,(SELECT DC.YYYYWW FROM OW_MD.DIM_CALENDAR DC WHERE DC.YYYYMMDD = (CASE WHEN UPPER(ONZDASO.FILE_NAME) LIKE '%MORNING%' THEN ADD_DAYS(TO_DATE((RIGHT(SUBSTR_BEFORE(UPPER(ONZDASO.FILE_NAME),'_MORNING.XLSX'),8)),'DDMMYYYY'),-28)ELSE NULL END)) AS "WEEK-4"
,(SELECT DC.YYYYWW FROM OW_MD.DIM_CALENDAR DC WHERE DC.YYYYMMDD = (CASE WHEN UPPER(ONZDASO.FILE_NAME) LIKE '%MORNING%' THEN ADD_DAYS(TO_DATE((RIGHT(SUBSTR_BEFORE(UPPER(ONZDASO.FILE_NAME),'_MORNING.XLSX'),8)),'DDMMYYYY'),-21)ELSE NULL END)) AS "WEEK-3"
,(SELECT DC.YYYYWW FROM OW_MD.DIM_CALENDAR DC WHERE DC.YYYYMMDD = (CASE WHEN UPPER(ONZDASO.FILE_NAME) LIKE '%MORNING%' THEN ADD_DAYS(TO_DATE((RIGHT(SUBSTR_BEFORE(UPPER(ONZDASO.FILE_NAME),'_MORNING.XLSX'),8)),'DDMMYYYY'),-14)ELSE NULL END)) AS "WEEK-2"
,(SELECT DC.YYYYWW FROM OW_MD.DIM_CALENDAR DC WHERE DC.YYYYMMDD = (CASE WHEN UPPER(ONZDASO.FILE_NAME) LIKE '%MORNING%' THEN ADD_DAYS(TO_DATE((RIGHT(SUBSTR_BEFORE(UPPER(ONZDASO.FILE_NAME),'_MORNING.XLSX'),8)),'DDMMYYYY'),-7)ELSE NULL END)) AS "WEEK-1"
,DC.YYYYWW AS "TIME_YEAR_WEEK"
/*
,(CASE WHEN UPPER(ONZDASO.FILE_NAME) LIKE '%MORNING%' THEN (SELECT DC.YYYYWW FROM OW_MD.DIM_CALENDAR DC WHERE DC.YYYYMMDD = ADD_DAYS(TO_DATE((RIGHT(SUBSTR_BEFORE(UPPER(ONZDASO.FILE_NAME),'_MORNING.XLSX'),8)),'DDMMYYYY'),7))ELSE NULL END) AS "WEEK+1"
,(CASE WHEN UPPER(ONZDASO.FILE_NAME) LIKE '%MORNING%' THEN (SELECT DC.YYYYWW FROM OW_MD.DIM_CALENDAR DC WHERE DC.YYYYMMDD = ADD_DAYS(TO_DATE((RIGHT(SUBSTR_BEFORE(UPPER(ONZDASO.FILE_NAME),'_MORNING.XLSX'),8)),'DDMMYYYY'),14))ELSE NULL END) AS "WEEK+2"
,(CASE WHEN UPPER(ONZDASO.FILE_NAME) LIKE '%MORNING%' THEN (SELECT DC.YYYYWW FROM OW_MD.DIM_CALENDAR DC WHERE DC.YYYYMMDD = ADD_DAYS(TO_DATE((RIGHT(SUBSTR_BEFORE(UPPER(ONZDASO.FILE_NAME),'_MORNING.XLSX'),8)),'DDMMYYYY'),21))ELSE NULL END) AS "WEEK+3"
,(CASE WHEN UPPER(ONZDASO.FILE_NAME) LIKE '%MORNING%' THEN (SELECT DC.YYYYWW FROM OW_MD.DIM_CALENDAR DC WHERE DC.YYYYMMDD = ADD_DAYS(TO_DATE((RIGHT(SUBSTR_BEFORE(UPPER(ONZDASO.FILE_NAME),'_MORNING.XLSX'),8)),'DDMMYYYY'),28))ELSE NULL END) AS "WEEK+4"
*/
,(SELECT DC.YYYYWW FROM OW_MD.DIM_CALENDAR DC WHERE DC.YYYYMMDD = (CASE WHEN UPPER(ONZDASO.FILE_NAME) LIKE '%MORNING%' THEN ADD_DAYS(TO_DATE((RIGHT(SUBSTR_BEFORE(UPPER(ONZDASO.FILE_NAME),'_MORNING.XLSX'),8)),'DDMMYYYY'),7)ELSE NULL END)) AS "WEEK+1"
,(SELECT DC.YYYYWW FROM OW_MD.DIM_CALENDAR DC WHERE DC.YYYYMMDD = (CASE WHEN UPPER(ONZDASO.FILE_NAME) LIKE '%MORNING%' THEN ADD_DAYS(TO_DATE((RIGHT(SUBSTR_BEFORE(UPPER(ONZDASO.FILE_NAME),'_MORNING.XLSX'),8)),'DDMMYYYY'),14)ELSE NULL END)) AS "WEEK+2"
,(SELECT DC.YYYYWW FROM OW_MD.DIM_CALENDAR DC WHERE DC.YYYYMMDD = (CASE WHEN UPPER(ONZDASO.FILE_NAME) LIKE '%MORNING%' THEN ADD_DAYS(TO_DATE((RIGHT(SUBSTR_BEFORE(UPPER(ONZDASO.FILE_NAME),'_MORNING.XLSX'),8)),'DDMMYYYY'),21)ELSE NULL END)) AS "WEEK+3"
,(SELECT DC.YYYYWW FROM OW_MD.DIM_CALENDAR DC WHERE DC.YYYYMMDD = (CASE WHEN UPPER(ONZDASO.FILE_NAME) LIKE '%MORNING%' THEN ADD_DAYS(TO_DATE((RIGHT(SUBSTR_BEFORE(UPPER(ONZDASO.FILE_NAME),'_MORNING.XLSX'),8)),'DDMMYYYY'),28)ELSE NULL END)) AS "WEEK+4"
,ONZDASO.ON_HAND --11 13
,ONZDASO.LOAD_DATE
FROM /*OW_LAO*//*OW_SEDA_S*/OW_LAO.ODS_NERP_ZRMMJ310410_DISPLAY_AVALIABLE_STOCK_OVERVIEW ONZDASO --Alterado de OW_SEDA_S para OW_LAO dia 25/04/2023
LEFT JOIN  OW_MD.DIM_CALENDAR DC ON (TO_DATE((RIGHT(SUBSTR_BEFORE(UPPER(ONZDASO.FILE_NAME),'_MORNING.XLSX'),8)),'DDMMYYYY') = DC.YYYYMMDD)
--LEFT JOIN  OW_MD.DIM_CALENDAR DC ON (TO_DATE((RIGHT(SUBSTR_BEFORE(UPPER(ONZDASO.FILE_NAME),'_AFTERNOON.XLSX'),8)),'DDMMYYYY') = DC.YYYYMMDD) -- CASO A TABELA ZRMMJ310410 vier de OW_LAO
LEFT JOIN OW_MD.DIM_SUBSIDIARY DS ON  (ONZDASO.COMPANY = DS.COMPANY_CODE) --Adicionado dia 25/04/2023
LEFT JOIN OW_MD.DIM_PRODUCT DP ON (ONZDASO.MATERIAL = DP.SKU) --Adicionado dia 30/03/2023
LEFT JOIN OW_MD.DIM_PLANT DP2 ON (ONZDASO.PLANT = DP2.PLANT_CODE)
LEFT JOIN OW_MD.MAP_STORAGE_LOCATION MSL ON (ONZDASO.PLANT = MSL.PLANT  AND ONZDASO.STORAGE_LOCATION  = MSL.S_LOC)-- ADD 10/10/2023
WHERE UPPER(ONZDASO.FILE_NAME) LIKE '%MORNING%'--'%AFTERNOON%' --dia 26/04/2023 Considerar apenas arquivos que tenham Afternoon para o SCHEMA OW_LAO
      AND MSL.INV_TYPE = 'D2C'-- ADD 10/10/2023
      AND (DC.YYYYWW ,DC.YYYYMMDD) IN (SELECT DC.YYYYWW AS "TIME_YEAR_WEEK"
					     ,MAX(TO_DATE((RIGHT(SUBSTR_BEFORE(UPPER(ONZDASO.FILE_NAME),'_MORNING.XLSX'),8)),'DDMMYYYY')) AS "LAST_DATE"
					   --,MAX(TO_DATE((RIGHT(SUBSTR_BEFORE(UPPER(ONZDASO.FILE_NAME),'_AFTERNOON.XLSX'),8)),'DDMMYYYY')) AS "LAST_DATE" -- Considerar apenas arquivos que tenham Afternoon para o SCHEMA OW_LAO
					FROM /*OW_LAO*//*OW_SEDA_S*/OW_LAO.ODS_NERP_ZRMMJ310410_DISPLAY_AVALIABLE_STOCK_OVERVIEW ONZDASO
				      LEFT JOIN OW_MD.DIM_CALENDAR DC ON (TO_DATE((RIGHT(SUBSTR_BEFORE(UPPER(ONZDASO.FILE_NAME),'_MORNING.XLSX'),8)),'DDMMYYYY') = DC.YYYYMMDD)
				    --LEFT JOIN OW_MD.DIM_CALENDAR DC ON (TO_DATE((RIGHT(SUBSTR_BEFORE(UPPER(ONZDASO.FILE_NAME),'_AFTERNOON.XLSX'),8)),'DDMMYYYY') = DC.YYYYMMDD)-- Considerar apenas arquivos que tenham Afternoon para o SCHEMA OW_LAO
				     GROUP BY DC.YYYYWW ORDER BY 1 DESC)-- Pegar o arquivo mais recente de cada semana
ORDER BY  9 /*"DATE_BASE"*/ DESC, 12 /*"TIME_YEAR_WEEK"*/ DESC
)
GROUP BY SUBSIDIARY
,DIMPROD_DIVISION
,DIMPROD_PRODUCT_GROUP
,DIMPROD_PRODUCT
,DIVISION
,MATERIAL
,PLANT
,PLANT_NAME
,TIME_YEAR
,TIME_YEAR_QUARTER
,"WEEK-4"
,"WEEK-3"
,"WEEK-2"
,"WEEK-1"
,TIME_YEAR_WEEK
,"WEEK+1"
,"WEEK+2"
,"WEEK+3"
,"WEEK+4"
,LOAD_DATE
ORDER BY TIME_YEAR_WEEK DESC, SUBSIDIARY, DIVISION
;
--Truncar a tabela de transformation dos dados que vem do nerp ODS_NERP_ZRMMJ310410_DISPLAY_AVALIABLE_STOCK_OVERVIEW, transação ZRMMJ310410 (Inventário)
TRUNCATE TABLE OW_LAO.FT_D2C_NERP_TO_STOCK_OVERVIEW_BY_PLANT ;
-- Inserir os dados tratados na transformation FT_D2C_NERP_TO_STOCK_OVERVIEW_BY_PLANT, referente a transação ZRMMJ310410 (Inventário)
INSERT INTO OW_LAO.FT_D2C_NERP_TO_STOCK_OVERVIEW_BY_PLANT
SELECT SUBSIDIARY
,DIMPROD_DIVISION
,DIMPROD_PRODUCT_GROUP
,DIMPROD_PRODUCT
,DIVISION
,MATERIAL
,PLANT
,PLANT_NAME
,TIME_YEAR
,TIME_YEAR_QUARTER
,TIME_YEAR_WEEK
,SUM(ON_HAND) AS ON_HAND 
,LOAD_DATE
FROM OW_LAO.TF_D2C_NERP_TO_STOCK_OVERVIEW
GROUP BY SUBSIDIARY
,DIMPROD_DIVISION
,DIMPROD_PRODUCT_GROUP
,DIMPROD_PRODUCT
,DIVISION
,MATERIAL
,PLANT
,PLANT_NAME
,TIME_YEAR
,TIME_YEAR_QUARTER
,TIME_YEAR_WEEK
,LOAD_DATE
ORDER BY TIME_YEAR_WEEK DESC, SUBSIDIARY, DIVISION;
	
	
	
	
	
	
--Truncar a tabela de transformation dos dados que vem do nerp ODS_NERP_ZRMMJ310410_DISPLAY_AVALIABLE_STOCK_OVERVIEW, transação ZRMMJ310410 (Inventário)
TRUNCATE TABLE OW_LAO.TF_D2C_NERP_TO_WOS ;
-- Inserir os dados tratados na transformation TF_D2C_NERP_TO_WOS, referente a transação ZRMMJ310410 (Inventário)
INSERT INTO OW_LAO.TF_D2C_NERP_TO_WOS
SELECT SUBSIDIARY
,DIMPROD_DIVISION
,DIMPROD_PRODUCT_GROUP
,DIMPROD_PRODUCT
,DIVISION
,MATERIAL
,TIME_YEAR
,TIME_YEAR_QUARTER
,"WEEK-4"
,"WEEK-3"
,"WEEK-2"
,"WEEK-1"
,TIME_YEAR_WEEK
,"WEEK+1"
,"WEEK+2"
,"WEEK+3"
,"WEEK+4"
,SUM(ON_HAND) AS ON_HAND 
,LOAD_DATE
FROM OW_LAO.TF_D2C_NERP_TO_STOCK_OVERVIEW
GROUP BY SUBSIDIARY
,DIMPROD_DIVISION
,DIMPROD_PRODUCT_GROUP
,DIMPROD_PRODUCT
,DIVISION
,MATERIAL
,TIME_YEAR
,TIME_YEAR_QUARTER
,"WEEK-4"
,"WEEK-3"
,"WEEK-2"
,"WEEK-1"
,TIME_YEAR_WEEK
,"WEEK+1"
,"WEEK+2"
,"WEEK+3"
,"WEEK+4"
,LOAD_DATE
;
--Truncar a tabela de transformation dos dados que vem do GSCM referente ao FORECAST, os dados estão consolidados na view: VW_D2C_SO_FSCT (HHP, VD, DA, OTHERS)
TRUNCATE TABLE OW_LAO.TF_D2C_GSCM_TO_WOS ;
-- Inserir os dados tratados  que vem do GSCM referente ao FORECAST na transformation, os dados estão consolidados na view: VW_D2C_SO_FSCT (HHP, VD, DA, OTHERS)
INSERT INTO  OW_LAO.TF_D2C_GSCM_TO_WOS 
SELECT SUBSIDIARY, PRODUCT_GRP, ITEM, "WEEK", SUM("VALUE") AS "QUANTITY" FROM (
SELECT  NULL AS LOAD_DATE,--Adicionado dia 16/01/2023
	NULL AS FILE_DATE,--Adicionado dia 16/01/2023
	VDSF.AP2 AS SUBSIDIARY
    	,VDSF.PRODUCT_GRP
	, VDSF."WEEK"
	, VDSF.ITEM
	, VDSF."VALUE"
FROM OW_LAO.ODS_GSCM_FCST_MGMT_D2C /*OW_SEDA_S.VW_D2C_SO_FSCT*/ VDSF
WHERE	1=1 AND LENGTH(VDSF."WEEK")>5 AND (VDSF.ACCOUNT LIKE '%D2C%' AND VDSF.AP2 ='SEDA') AND CATEGORY ='S/O FCST AP1'
AND TO_DATE(VDSF.LOAD_DATE) = (SELECT DISTINCT MAX(TO_DATE(VDSF.LOAD_DATE)) FROM OW_LAO.ODS_GSCM_FCST_MGMT_D2C VDSF)
AND TO_DATE((RIGHT(SUBSTR_BEFORE(UPPER(VDSF.FILE_NAME),'.XLSX'),8)),'YYYYMMDD')=(SELECT DISTINCT MAX(TO_DATE((RIGHT(SUBSTR_BEFORE(UPPER(VDSF.FILE_NAME),'.XLSX'),8)),'YYYYMMDD')) FROM OW_LAO.ODS_GSCM_FCST_MGMT_D2C VDSF)
UNION 
SELECT  NULL AS LOAD_DATE,--Adicionado dia 16/01/2023
	NULL AS FILE_DATE,--Adicionado dia 16/01/2023
	VDSF.AP2 AS SUBSIDIARY
    	,VDSF.PRODUCT_GRP
	, VDSF."WEEK"
	, VDSF.ITEM
	, VDSF."VALUE"
FROM OW_LAO.ODS_GSCM_FCST_MGMT_D2C /*OW_SEDA_S.VW_D2C_SO_FSCT*/ VDSF
WHERE	1=1 AND LENGTH(VDSF."WEEK")>5 AND VDSF.AP2 <>'SEDA' AND CATEGORY ='S/O FCST AP1'
AND TO_DATE(VDSF.LOAD_DATE) = (SELECT DISTINCT MAX(TO_DATE(VDSF.LOAD_DATE)) FROM OW_LAO.ODS_GSCM_FCST_MGMT_D2C VDSF)
AND TO_DATE((RIGHT(SUBSTR_BEFORE(UPPER(VDSF.FILE_NAME),'.XLSX'),8)),'YYYYMMDD')=(SELECT DISTINCT MAX(TO_DATE((RIGHT(SUBSTR_BEFORE(UPPER(VDSF.FILE_NAME),'.XLSX'),8)),'YYYYMMDD')) FROM OW_LAO.ODS_GSCM_FCST_MGMT_D2C VDSF)
/***********************************Adicionado dia 16/01/2023***********************************/
UNION
SELECT DISTINCT 
	MAX(TO_DATE(VDSF.LOAD_DATE)) AS LOAD_DATE,
	MAX(TO_DATE((RIGHT(SUBSTR_BEFORE(UPPER(VDSF.FILE_NAME),'.XLSX'),8)),'YYYYMMDD')) AS LOAD_FILE
	,
	VDSF.AP2 AS SUBSIDIARY
    	,VDSF.PRODUCT_GRP
	,VDSF."WEEK"
	,VDSF.ITEM
	,VDSF."VALUE"
	FROM OW_LAO.ODS_GSCM_FCST_MGMT_D2C VDSF
	WHERE 1=1
	AND LENGTH(VDSF."WEEK")>5 
	AND VDSF.AP2 ='SEDA' 
	AND CATEGORY ='S/O FCST AP1'
	/*AND YEAR(VDSF.LOAD_DATE) = YEAR(ADD_YEARS(CURRENT_DATE,-1))
	AND YEAR(TO_DATE((RIGHT(SUBSTR_BEFORE(UPPER(VDSF.FILE_NAME),'.XLSX'),8)),'YYYYMMDD')) = YEAR(ADD_YEARS(CURRENT_DATE,-1))*/
	AND TO_DATE(LOAD_DATE) = TO_DATE(YEAR(ADD_YEARS(CURRENT_DATE,-1))||'-'||'12'||'-'||'31')
	AND TO_DATE(RIGHT(SUBSTR_BEFORE(UPPER(VDSF.FILE_NAME),'.XLSX'),8)) = TO_DATE(YEAR(ADD_YEARS(CURRENT_DATE,-1))||'-'||'12'||'-'||'31')
	AND YEAR(SUBSTRING(VDSF."WEEK",1,4)) =  YEAR(ADD_YEARS(CURRENT_DATE,-1))
GROUP BY VDSF.AP2
    	,VDSF.PRODUCT_GRP
	,VDSF."WEEK"
	,VDSF.ITEM
	,VDSF."VALUE"
UNION ALL 
SELECT DISTINCT 
	MAX(TO_DATE(VDSF.LOAD_DATE)) AS LOAD_DATE,
	MAX(TO_DATE((RIGHT(SUBSTR_BEFORE(UPPER(VDSF.FILE_NAME),'.XLSX'),8)),'YYYYMMDD')) AS LOAD_FILE
	,
	VDSF.AP2 AS SUBSIDIARY
    	,VDSF.PRODUCT_GRP
	, VDSF."WEEK"
	, VDSF.ITEM
	, VDSF."VALUE"
FROM OW_LAO.ODS_GSCM_FCST_MGMT_D2C  VDSF
	WHERE	1=1 
	AND LENGTH(VDSF."WEEK")>5 
	AND VDSF.AP2 <>'SEDA' 
	AND CATEGORY ='S/O FCST AP1'
/*	AND TO_DATE(VDSF.LOAD_DATE) = (SELECT DISTINCT MAX(TO_DATE(VDSF.LOAD_DATE)) FROM OW_LAO.ODS_GSCM_FCST_MGMT_D2C VDSF)
	AND TO_DATE((RIGHT(SUBSTR_BEFORE(UPPER(VDSF.FILE_NAME),'.XLSX'),8)),'YYYYMMDD')=(SELECT DISTINCT MAX(TO_DATE((RIGHT(SUBSTR_BEFORE(UPPER(VDSF.FILE_NAME),'.XLSX'),8)),'YYYYMMDD')) FROM OW_LAO.ODS_GSCM_FCST_MGMT_D2C VDSF)	*/
	AND TO_DATE(LOAD_DATE) = TO_DATE(YEAR(ADD_YEARS(CURRENT_DATE,-1))||'-'||'12'||'-'||'31')
	AND TO_DATE(RIGHT(SUBSTR_BEFORE(UPPER(VDSF.FILE_NAME),'.XLSX'),8)) = TO_DATE(YEAR(ADD_YEARS(CURRENT_DATE,-1))||'-'||'12'||'-'||'31')
	AND YEAR(SUBSTRING(VDSF."WEEK",1,4)) =  YEAR(ADD_YEARS(CURRENT_DATE,-1))
GROUP BY VDSF.AP2
    	,VDSF.PRODUCT_GRP
	,VDSF."WEEK"
	,VDSF.ITEM
	,VDSF."VALUE"
/***********************************Adicionado dia 16/01/2023***********************************/
)
GROUP BY SUBSIDIARY, PRODUCT_GRP, ITEM, "WEEK"
ORDER BY "WEEK" DESC, PRODUCT_GRP
;
--Truncar a tabela FT referente aos dados de WOS (Inventário NERP x Forecast GSCM)
TRUNCATE TABLE OW_LAO.FT_D2C_WOS ;
--Criando a tabela FT referente aos dados de WOS (Inventário NERP x Forecast GSCM)
INSERT INTO  OW_LAO.FT_D2C_WOS
SELECT 
	 NERP_INV.SUBSIDIARY
	/*,NERP_INV.GSCM_GLOBAL_DISIVION
	,NERP_INV.GSCM_DISIVION
	,NERP_INV.GSCM_GROUP_DISIVION
	,NERP_INV.GSCM_PRODUCT_CATEGORY
	,NERP_INV.GSCM_GROUP_PRODUCT_CATEGORY*/
	,NERP_INV.MATERIAL
	,NERP_INV.DIMPROD_DIVISION
	,NERP_INV.DIMPROD_PRODUCT_GROUP
	,NERP_INV.DIMPROD_PRODUCT
	,NERP_INV.DIVISION
	,NERP_INV.TIME_YEAR
	,NERP_INV.TIME_YEAR_QUARTER
	,NERP_INV.TIME_YEAR_WEEK
	,SUM(NERP_INV.ON_HAND) AS ON_HAND
	,SUM(FCSTN4.QUANTITY) AS "SO_W-4"
	,SUM(FCSTN3.QUANTITY) AS "SO_W-3"
	,SUM(FCSTN2.QUANTITY) AS "SO_W-2"
	,SUM(FCSTN1.QUANTITY) AS "SO_W-1"
	,SUM(FCST0.QUANTITY) AS "SO_W0"
	,SUM(FCST1.QUANTITY) AS "SO_W+1"
	,SUM(FCST2.QUANTITY) AS "SO_W+2"
	,SUM(FCST3.QUANTITY) AS "SO_W+3"
	,SUM(FCST4.QUANTITY) AS "SO_W+4"
	--,ROUND(((SUM(FCSTN4.QUANTITY)+SUM(FCSTN3.QUANTITY)+SUM(FCSTN2.QUANTITY)+SUM(FCSTN1.QUANTITY))/4),2) AS "SO_AVG_B4W" 
	,ROUND(((IFNULL(SUM(FCSTN4.QUANTITY),0)+IFNULL(SUM(FCSTN3.QUANTITY),0)+
	         IFNULL(SUM(FCSTN2.QUANTITY),0)+IFNULL(SUM(FCSTN1.QUANTITY),0))/4),2) AS "SO_AVG_B4W" 
	/*,CASE WHEN ROUND(((SUM(NERP_INV.ON_HAND))/(NULLIF((SUM(FCSTN3.QUANTITY)+SUM(FCSTN2.QUANTITY)+SUM(FCSTN1.QUANTITY)+SUM(FCST0.QUANTITY)),0)/4)),2) IS NULL THEN 1 ELSE 0 END AS "COUNT_SKU_B4W_NoSellOut"
	,CASE WHEN ROUND(((SUM(NERP_INV.ON_HAND))/(NULLIF((SUM(FCSTN3.QUANTITY)+SUM(FCSTN2.QUANTITY)+SUM(FCSTN1.QUANTITY)+SUM(FCST0.QUANTITY)),0)/4)),2) <=2 THEN 1 ELSE 0 END AS "COUNT_SKU_B4W_WOS<=2"
	,CASE WHEN ROUND(((SUM(NERP_INV.ON_HAND))/(NULLIF((SUM(FCSTN3.QUANTITY)+SUM(FCSTN2.QUANTITY)+SUM(FCSTN1.QUANTITY)+SUM(FCST0.QUANTITY)),0)/4)),2) >2
	 AND ROUND(((SUM(NERP_INV.ON_HAND))/(NULLIF((SUM(FCSTN3.QUANTITY)+SUM(FCSTN2.QUANTITY)+SUM(FCSTN1.QUANTITY)+SUM(FCST0.QUANTITY)),0)/4)),2) <=4
	THEN 1 ELSE 0 END AS "COUNT_SKU_B4W_2<WOS<=4"
	,CASE WHEN ROUND(((SUM(NERP_INV.ON_HAND))/(NULLIF((SUM(FCSTN3.QUANTITY)+SUM(FCSTN2.QUANTITY)+SUM(FCSTN1.QUANTITY)+SUM(FCST0.QUANTITY)),0)/4)),2) >4
	 AND ROUND(((SUM(NERP_INV.ON_HAND))/(NULLIF((SUM(FCSTN3.QUANTITY)+SUM(FCSTN2.QUANTITY)+SUM(FCSTN1.QUANTITY)+SUM(FCST0.QUANTITY)),0)/4)),2) <=6
	THEN 1 ELSE 0 END AS "COUNT_SKU_B4W_4<WOS<=6"
	,CASE WHEN ROUND(((SUM(NERP_INV.ON_HAND))/(NULLIF((SUM(FCSTN3.QUANTITY)+SUM(FCSTN2.QUANTITY)+SUM(FCSTN1.QUANTITY)+SUM(FCST0.QUANTITY)),0)/4)),2) >6 THEN 1 ELSE 0 END AS "COUNT_SKU_B4W_WOS>6"*/
        /**/
	--,ROUND(((SUM(FCST1.QUANTITY)+SUM(FCST2.QUANTITY)+SUM(FCST3.QUANTITY)+SUM(FCST4.QUANTITY))/4),2) AS "SO_AVG_F4W" 
	/**/
	,ROUND(((IFNULL(SUM(FCST1.QUANTITY),0)+IFNULL(SUM(FCST2.QUANTITY),0)+
        	 IFNULL(SUM(FCST3.QUANTITY),0)+IFNULL(SUM(FCST4.QUANTITY),0))/4),2) AS "SO_AVG_F4W" 
	,ROUND(((SUM(NERP_INV.ON_HAND))/(NULLIF((SUM(FCST1.QUANTITY)+SUM(FCST2.QUANTITY)+SUM(FCST3.QUANTITY)+SUM(FCST4.QUANTITY)),0)/4)),2) AS WOS -- Alteração realizada dia 29/03/2023. Caso a (soma de Quantity/4) for 0 considerar NULL, foi necessário pois estamos utilizando Material ao invés de division para relacionar
        --,NULLIF(SUM(NERP_INV.ON_HAND),0)/NULLIF((SUM(FCST1.QUANTITY)+SUM(FCST2.QUANTITY)+SUM(FCST3.QUANTITY)+SUM(FCST4.QUANTITY)),0)
	/*,CASE WHEN ROUND(((SUM(NERP_INV.ON_HAND))/(NULLIF((SUM(FCST1.QUANTITY)+SUM(FCST2.QUANTITY)+SUM(FCST3.QUANTITY)+SUM(FCST4.QUANTITY)),0)/4)),2) IS NULL THEN 1 ELSE 0 END AS "COUNT_SKU_F4W_NoSellOut"
	,CASE WHEN ROUND(((SUM(NERP_INV.ON_HAND))/(NULLIF((SUM(FCST1.QUANTITY)+SUM(FCST2.QUANTITY)+SUM(FCST3.QUANTITY)+SUM(FCST4.QUANTITY)),0)/4)),2) <=2 THEN 1 ELSE 0 END AS "COUNT_SKU_F4W_WOS<=2"
	,CASE WHEN ROUND(((SUM(NERP_INV.ON_HAND))/(NULLIF((SUM(FCST1.QUANTITY)+SUM(FCST2.QUANTITY)+SUM(FCST3.QUANTITY)+SUM(FCST4.QUANTITY)),0)/4)),2) >2
	 AND ROUND(((SUM(NERP_INV.ON_HAND))/(NULLIF((SUM(FCST1.QUANTITY)+SUM(FCST2.QUANTITY)+SUM(FCST3.QUANTITY)+SUM(FCST4.QUANTITY)),0)/4)),2) <=4
	THEN 1 ELSE 0 END AS "COUNT_SKU_F4W_2<WOS<=4"
	,CASE WHEN ROUND(((SUM(NERP_INV.ON_HAND))/(NULLIF((SUM(FCST1.QUANTITY)+SUM(FCST2.QUANTITY)+SUM(FCST3.QUANTITY)+SUM(FCST4.QUANTITY)),0)/4)),2) >4
	 AND ROUND(((SUM(NERP_INV.ON_HAND))/(NULLIF((SUM(FCST1.QUANTITY)+SUM(FCST2.QUANTITY)+SUM(FCST3.QUANTITY)+SUM(FCST4.QUANTITY)),0)/4)),2) <=6
	THEN 1 ELSE 0 END AS "COUNT_SKU_F4W_4<WOS<=6"
	,CASE WHEN ROUND(((SUM(NERP_INV.ON_HAND))/(NULLIF((SUM(FCST1.QUANTITY)+SUM(FCST2.QUANTITY)+SUM(FCST3.QUANTITY)+SUM(FCST4.QUANTITY)),0)/4)),2) >6 THEN 1 ELSE 0 END AS "COUNT_SKU_F4W_WOS>6"*/
	,NULL AS LAST_UPDATE
	,LOAD_DATE 
FROM OW_LAO.TF_D2C_NERP_TO_WOS AS NERP_INV
LEFT JOIN  OW_LAO.TF_D2C_GSCM_TO_WOS FCSTN4 ON NERP_INV.MATERIAL = FCSTN4.ITEM AND NERP_INV.SUBSIDIARY = FCSTN4.SUBSIDIARY AND -- Mudança realizada no dia 29/03/2023 substituir division por material 
			NERP_INV."WEEK-4"  = FCSTN4.WEEK
LEFT JOIN  OW_LAO.TF_D2C_GSCM_TO_WOS FCSTN3 ON NERP_INV.MATERIAL = FCSTN3.ITEM AND NERP_INV.SUBSIDIARY = FCSTN3.SUBSIDIARY AND -- Mudança realizada no dia 29/03/2023 substituir division por material 
			NERP_INV."WEEK-3"  = FCSTN3.WEEK
LEFT JOIN  OW_LAO.TF_D2C_GSCM_TO_WOS FCSTN2 ON NERP_INV.MATERIAL = FCSTN2.ITEM AND NERP_INV.SUBSIDIARY = FCSTN2.SUBSIDIARY AND 
			 NERP_INV."WEEK-2"  = FCSTN2.WEEK
LEFT JOIN  OW_LAO.TF_D2C_GSCM_TO_WOS FCSTN1 ON NERP_INV.MATERIAL = FCSTN1.ITEM AND NERP_INV.SUBSIDIARY = FCSTN1.SUBSIDIARY AND 
			 NERP_INV."WEEK-1"  = FCSTN1.WEEK
LEFT JOIN  OW_LAO.TF_D2C_GSCM_TO_WOS FCST0 ON NERP_INV.MATERIAL = FCST0.ITEM AND NERP_INV.SUBSIDIARY = FCST0.SUBSIDIARY AND 
			 NERP_INV.TIME_YEAR_WEEK = FCST0.WEEK 
LEFT JOIN  OW_LAO.TF_D2C_GSCM_TO_WOS FCST1 ON NERP_INV.MATERIAL = FCST1.ITEM AND NERP_INV.SUBSIDIARY = FCST1.SUBSIDIARY AND 
			 NERP_INV."WEEK+1" = FCST1.WEEK 
LEFT JOIN  OW_LAO.TF_D2C_GSCM_TO_WOS FCST2 ON NERP_INV.MATERIAL = FCST2.ITEM AND NERP_INV.SUBSIDIARY = FCST2.SUBSIDIARY AND 
			 NERP_INV."WEEK+2" = FCST2.WEEK 
LEFT JOIN  OW_LAO.TF_D2C_GSCM_TO_WOS FCST3 ON NERP_INV.MATERIAL = FCST3.ITEM AND NERP_INV.SUBSIDIARY = FCST3.SUBSIDIARY AND 
			 NERP_INV."WEEK+3" = FCST3.WEEK 
LEFT JOIN  OW_LAO.TF_D2C_GSCM_TO_WOS FCST4 ON NERP_INV.MATERIAL = FCST4.ITEM AND NERP_INV.SUBSIDIARY = FCST4.SUBSIDIARY AND 
			 NERP_INV."WEEK+4" = FCST4.WEEK 
GROUP BY NERP_INV.SUBSIDIARY
	/*,NERP_INV.GSCM_GLOBAL_DISIVION
	,NERP_INV.GSCM_DISIVION
	,NERP_INV.GSCM_GROUP_DISIVION
	,NERP_INV.GSCM_PRODUCT_CATEGORY
	,NERP_INV.GSCM_GROUP_PRODUCT_CATEGORY*/
	,NERP_INV.MATERIAL
    	,NERP_INV.DIMPROD_DIVISION
	,NERP_INV.DIMPROD_PRODUCT_GROUP
	,NERP_INV.DIMPROD_PRODUCT
	,NERP_INV.DIVISION
	,NERP_INV.TIME_YEAR
	,NERP_INV.TIME_YEAR_QUARTER
	,NERP_INV.TIME_YEAR_WEEK
	,LOAD_DATE
	--,SUM(NERP_INV.ON_HAND)
	--,NULLIF(SUM(NERP_INV.ON_HAND),0)/NULLIF(FCST1.QUANTITY,0)
	
ORDER BY NERP_INV.TIME_YEAR_WEEK DESC 
	,NERP_INV.SUBSIDIARY
	,NERP_INV.DIVISION
;
-- Update para Setar o horário de carga. Obs.: Estou fazendo aqui para não ter probemas com milisegundos
UPDATE OW_LAO.FT_D2C_WOS
	SET LAST_UPDATE = NOW()
	WHERE LAST_UPDATE IS NULL;
END