/***********************************************************************************************
CREATED BY : Luciano Mariani
CREATION DATE : 2023-06-29
ALTER BY : Luciano Mariani
ALTER DATE : 2025-04-17 
'2025-04-02'
ALTER BY :  mv.silva
ALTER DATE: 2025-05-01
CALL OW_LAO.PROC_D2C_PO_VTEX_SALES_TMP ( ADD_DAYS(CURRENT_TIMESTAMP, -32),  ADD_DAYS(CURRENT_TIMESTAMP, 2))
***********************************************************************************************/
CREATE PROCEDURE OW_LAO.PROC_D2C_PO_VTEX_SALES_TMP (
	  p_DATE_INI DATE DEFAULT NULL 
	, P_DATE_FIM DATE DEFAULT NULL 
) LANGUAGE SQLSCRIPT
AS
BEGIN
	
	/*********************************************************
	* CRIA A TMP_PARAMETER_PO_VTEX
	********************************************************/
	IF EXISTS ( SELECT '' FROM SYS.TABLES WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TMP_PARAMETER_PO_VTEX' ) THEN
		DROP TABLE OW_LAO.TMP_PARAMETER_PO_VTEX_TMP;
	END IF ;
	CREATE COLUMN TABLE OW_LAO.TMP_PARAMETER_PO_VTEX_TMP AS (
		SELECT ADD_DAYS(CURRENT_TIMESTAMP, -30) AS DATE_INI, ADD_DAYS(CURRENT_TIMESTAMP, 2) AS DATE_FIM FROM DUMMY
	);
	UPDATE OW_LAO.TMP_PARAMETER_PO_VTEX_TMP SET
		  DATE_INI = IFNULL( p_DATE_INI, ADD_DAYS(CURRENT_TIMESTAMP, -7) ) -- 30 dias dafault
		, DATE_FIM = IFNULL( P_DATE_FIM, ADD_DAYS(CURRENT_TIMESTAMP, 2) ) 
	;
	
	/*************************************************************
 	CRIA TMP_PO_ORDER_ID_PO_VTEX PARA CAPTURAR O CUSTOMER PO NA ORDER ID
 	TAMBÉM VERIFICA SE JÁ EXISTE NA TF_D2C_NERP_SALES
	*************************************************************/
	IF EXISTS( SELECT '' FROM SYS.TABLES WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TMP_PO_ORDER_ID_PO_VTEX') THEN
		DROP TABLE OW_LAO.TMP_PO_ORDER_ID_PO_VTEX_TMP;
	END IF;
	CREATE COLUMN TABLE OW_LAO.TMP_PO_ORDER_ID_PO_VTEX_TMP AS(
		SELECT 
			   V.ORDER_ID
			 , V.MARKETPLACE_ORDER_ID
			 , MAX( CREATION_TIMESTAMP ) AS CREATION_TIMESTAMP
			 , MAX( CASE WHEN S.CUSTOMER_PO IS NOT NULL THEN S.CUSTOMER_PO
				   		ELSE CAST("SEQUENCE" AS VARCHAR(100)) END
			   ) AS CUSTOMER_PO
			--, 1 AS IS_NEW
		    --, 1 AS IS_UPDATE  
		FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER V
			 LEFT JOIN OW_LAO.ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING S ON V.ORDER_ID = S.CUSTOMER_PO
		WHERE 1=1
			AND V.CREATION_TIMESTAMP BETWEEN ( SELECT DATE_INI FROM OW_LAO.TMP_PARAMETER_PO_VTEX_TMP ) 
				 						      AND ( SELECT DATE_FIM FROM OW_LAO.TMP_PARAMETER_PO_VTEX_TMP )
			AND V.ORDER_ID IN ( 						      
					SELECT DISTINCT ORDER_ID
					FROM  OW_LAO.TF_D2C_NERP_SALES
					WHERE 1 = 1
					      AND SUBSIDIARY = 'SEDA'
					      AND SOURCE = 'PO'
					      --ND REFERENCE_CODE IN ('F-AR12DYFAAWK', 'F-AR18DXFAAWK')
					      AND SEDA_DIVISION_ESTORE IS NULL				      
			) 						      
			/******************************	 						      
			AND V.MARKETPLACE_ORDER_ID IN(
							SELECT DISTINCT ORDER_ID
							FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_B2B_SALES_ORDER
							WHERE EMAIL_DOMAIN IS NOT NULL
			)
			AND  V.ORDER_ID IN(
				SELECT DISTINCT ORDER_ID
				FROM OW_LAO.TF_D2C_NERP_SALES
				WHERE SOURCE = 'PO'
					AND EMAIL_DOMAIN IS NULL
			)
			 **************************/			
		GROUP BY
			   V.ORDER_ID
			 , V.MARKETPLACE_ORDER_ID
	);
	/***********************************
	-- CRIA TABELA TMP_ITEM_COMPONENTS_PO_VTEX DO DISCO
	***********************************/
	IF EXISTS( SELECT TABLE_NAME FROM SYS.TABLES WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TMP_ITEM_COMPONENTS_PO_VTEX') THEN
		DROP TABLE OW_LAO.TMP_ITEM_COMPONENTS_PO_VTEX_TMP;
	END IF;
	CREATE COLUMN TABLE OW_LAO.TMP_ITEM_COMPONENTS_PO_VTEX_TMP AS(
		SELECT --DISTINCT
			  CP.ORDER_ID
			, CP.SKU_ID
			, CP.SKU_ID_COMPONENT
			, CP.REF_ID
			, CP.NAME
			, CP.QUANTITY
			, CP.PRICE
			, CP.COST_PRICE
			, CP.SELLING_PRICE
			, ( CP.SELLING_PRICE * CP.QUANTITY ) AS SELLING_PRICE_AMOUNT
			, CAST( 0 AS DECIMAL(18,4) ) AS SELLING_PRICE_TOTAL
			, 1 AS ITEM_INDEX_COMPONENT
			, ROW_NUMBER() OVER (PARTITION BY CP.ORDER_ID, CP.SKU_ID ORDER BY CP.ORDER_ID, CP.SKU_ID, CP.SKU_ID_COMPONENT, CP.QUANTITY, ( CP.SELLING_PRICE * CP.QUANTITY )) AS ITEM_INDEX_KIT
		FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_ITEM_COMPONENTS CP
			 INNER JOIN OW_LAO.TMP_PO_ORDER_ID_PO_VTEX_TMP TP ON CP.ORDER_ID = TP.ORDER_ID
		WHERE (CP.REF_ID IS NOT NULL)
	);
	
	-- ATUALIZA ITEM_INDEX_COMPONENT (PARA CASOS DE SKU_ID DUPLICADOS NOS KITS)
	UPDATE CP SET 
		  ITEM_INDEX_COMPONENT = CT.ITEM_INDEX_COMPONENT 
	FROM OW_LAO.TMP_ITEM_COMPONENTS_PO_VTEX_TMP CP
		INNER JOIN (
			SELECT ORDER_ID
			    , SKU_ID
			    , SKU_ID_COMPONENT
			    , ROW_NUMBER() OVER (PARTITION BY ORDER_ID, SKU_ID ORDER BY ORDER_ID, SKU_ID) AS ITEM_INDEX_COMPONENT
			FROM (
			     SELECT DISTINCT ORDER_ID, SKU_ID, SKU_ID_COMPONENT
			     FROM OW_LAO.TMP_ITEM_COMPONENTS_PO_VTEX_TMP
			)
		) CT ON  CP.ORDER_ID = CT.ORDER_ID
			    AND CP.SKU_ID = CT.SKU_ID
			    AND CP.SKU_ID_COMPONENT = CT.SKU_ID_COMPONENT
	;
	
	/*******************************
	-- ATUALIZA SELLING_PRICE_TOTAL PARA RATEIO
	*******************************/
	UPDATE TP SET TP.SELLING_PRICE_TOTAL = TT.SELLING_PRICE_TOTAL
	FROM OW_LAO.TMP_ITEM_COMPONENTS_PO_VTEX_TMP TP
		INNER JOIN (
				SELECT ORDER_ID
					 , SKU_ID
					 , SUM(SELLING_PRICE_AMOUNT) AS SELLING_PRICE_TOTAL 
				FROM OW_LAO.TMP_ITEM_COMPONENTS_PO_VTEX_TMP
				GROUP BY
					  ORDER_ID
					, SKU_ID				
		) TT ON TP.ORDER_ID = TT.ORDER_ID
				AND TP.SKU_ID = TT.SKU_ID
	;
	
	/***********************************
	-- CRIA TABELA ITENS SOMENTE PARA (COMPONENTS)
	***********************************/
	IF EXISTS( SELECT TABLE_NAME FROM SYS.TABLES WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TMP_ORDER_ITEM_TO_COMPONENTS_PO_VTEX' ) THEN
		DROP TABLE OW_LAO.TMP_ORDER_ITEM_TO_COMPONENTS_PO_VTEX_TMP;
	END IF;
	CREATE COLUMN TABLE OW_LAO.TMP_ORDER_ITEM_TO_COMPONENTS_PO_VTEX_TMP AS (
		SELECT *
			, ROW_NUMBER() OVER (PARTITION BY ORDER_ID, SKU_ID ORDER BY ORDER_ID, SKU_ID) AS ITEM_INDEX_COMPONENT
			, 1 AS ITEM_INDEX_COMPONENT_COUNT -- DEFAULT 1
		FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_ITEM
		WHERE ORDER_ID IN ( SELECT DISTINCT ORDER_ID FROM OW_LAO.TMP_ITEM_COMPONENTS_PO_VTEX_TMP )
	);
	
	UPDATE OW_LAO.TMP_ORDER_ITEM_TO_COMPONENTS_PO_VTEX_TMP SET 
		ITEM_INDEX_COMPONENT_COUNT = 0 -- IF ORDER HAS MORE THEN 1 SAME ITEM 
	WHERE ORDER_ID IN (
			SELECT ORDER_ID	
			FROM OW_LAO.TMP_ORDER_ITEM_TO_COMPONENTS_PO_VTEX_TMP
			GROUP BY ORDER_ID
			HAVING MAX(ITEM_INDEX_COMPONENT) > 1
		);
	
	/***********************************
	-- CRIA TABELA SHIPPING_TMP
	***********************************/
	IF EXISTS( SELECT TABLE_NAME FROM SYS.TABLES WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TMP_SHIPPING_VTEX') THEN
		DROP TABLE OW_LAO.TMP_SHIPPING_VTEX_TMP;
	END IF;
	CREATE TABLE OW_LAO.TMP_SHIPPING_VTEX_TMP AS ( -- PEGA O SELECTED_SLA
		SELECT CP.ORDER_ID
			 , CP.ITEM_INDEX
			 , MAX(JSON_VALUE('[' || CP.PICKUP_STORE_INFO || ']', '$.address.addressType')) AS ADDRESSTYPE
			 , MAX(JSON_VALUE('[' || CP.PICKUP_STORE_INFO || ']', '$.friendlyName')) AS FRIENDLYNAME
			 , MAX(CP.STATE) AS STATE
			 , MAX(CP.CITY) AS CITY
			 , MAX(CP.SELECTED_SLA) AS SELECTED_SLA
			 , STRING_AGG(CP.WAREHOUSE_ID, ' | ') AS WAREHOUSE_ID_GROUP
			 , MAX(CP.SELLING_PRICE) AS SHIPPING_PRICE
		FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_SHIPPING CP
			INNER JOIN OW_LAO.TMP_PO_ORDER_ID_PO_VTEX_TMP TP ON CP.ORDER_ID = TP.ORDER_ID
		GROUP BY CP.ORDER_ID
			   , CP.ITEM_INDEX
	);
	/**************************************
	-- PROMOTION
	**************************************/
	IF EXISTS( SELECT TABLE_NAME FROM SYS.TABLES WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TMP_PROMOTION_VTEX_NERP_SALES') THEN
		DROP TABLE OW_LAO.TMP_PROMOTION_VTEX_NERP_SALES_TMP;
	END IF;
	CREATE TABLE OW_LAO.TMP_PROMOTION_VTEX_NERP_SALES_TMP AS ( -- PEGA O SELECTED_SLA		
		SELECT 
			  ORDER_ID
			, ITEM_INDEX
			, ITEM_INDEX_KIT --, REFERENCE_CODE_KIT,	REFERENCE_CODE, ITEM_NAME
			, STRING_AGG(
				CASE WHEN LOWER(PRC_TAG_NAME) LIKE '%giftcard_ssg_rewards%' THEN '-'  ELSE ID_CALCULATOR_CONFIGURATION END
				, CHAR(13) || CHAR(10)  || ','
			) AS PROMOS_IDS
			, STRING_AGG(
				CASE WHEN LOWER(PRC_TAG_NAME) LIKE '%giftcard_ssg_rewards%' THEN PRC_TAG_NAME  ELSE PROM_NAME END
				, CHAR(13) || CHAR(10)  || ',' 
			) AS PROMOS_NAME
			, STRING_AGG(
				  ROUND((AMOUNT_DISCOUNT * -1), 2)
				, CHAR(13) || CHAR(10)  || ',' 
			) AS PROMOS_DISCOUNTS    
		FROM (
			SELECT
				  ORDER_ID
				, ITEM_INDEX
				, ITEM_INDEX_KIT --, REFERENCE_CODE_KIT,	REFERENCE_CODE, ITEM_NAME
				, ID_CALCULATOR_CONFIGURATION
				, PROM_NAME
				, PRC_TAG_NAME
				, AMOUNT_DISCOUNT
			FROM OW_LAO.FT_D2C_VTEX_PROMOTION
			WHERE 1=1 -- AND REFERENCE_CODE = 'EF-PS931CMEGWW'
				  AND ( ORDER_ID IN ( SELECT ORDER_ID FROM OW_LAO.TMP_PO_ORDER_ID_PO_VTEX_TMP)
						OR ORDER_ID IN ( SELECT MARKETPLACE_ORDER_ID FROM OW_LAO.TMP_PO_ORDER_ID_PO_VTEX_TMP)
				  )
			GROUP BY
				  ORDER_ID
				, ITEM_INDEX
				, ITEM_INDEX_KIT --, REFERENCE_CODE_KIT,	REFERENCE_CODE, ITEM_NAME
				, ID_CALCULATOR_CONFIGURATION
				, PROM_NAME
				, PRC_TAG_NAME
				, AMOUNT_DISCOUNT
			ORDER BY 
				  ORDER_ID
				, ITEM_INDEX
				, ITEM_INDEX_KIT --, REFERENCE_CODE_KIT,	REFERENCE_CODE, ITEM_NAME
				, AMOUNT_DISCOUNT
				/*Adicionado dia 01/05/2025*/
				, PRC_TAG_NAME
				, ID_CALCULATOR_CONFIGURATION
				, PROM_NAME
		)
		GROUP BY
			  ORDER_ID
			, ITEM_INDEX
			, ITEM_INDEX_KIT --, REFERENCE_CODE_KIT,	REFERENCE_CODE, ITEM_NAME
		/*Adicionado dia 01/05/2025*/
		ORDER BY ORDER_ID
			, ITEM_INDEX
			, ITEM_INDEX_KIT
	);
	/***********************************
	-- APAGA DADOS ANTERIORES DE PO
	***********************************/
	DELETE FROM OW_LAO.TF_D2C_NERP_SALES
	WHERE SOURCE = 'PO' 
	AND SUBSIDIARY = 'SEDA'
		  AND ORDER_ID IN(
				SELECT ORDER_ID
				FROM OW_LAO.TMP_PO_ORDER_ID_PO_VTEX_TMP
				--WHERE IS_UPDATE = 1 -- ATUALIZAÇÃO
		  )
	;
	
	/***********************************	
	-- ATUALIZA MOEDA DE PO ULTIMO DIA
	***********************************/	
	UPDATE NS SET AMOUNT_USD = CAST( NS.AMOUNT_LOCAL / EX.EXCHANGE_RATE AS DECIMAL(18,2) )
	FROM OW_LAO.TF_D2C_NERP_SALES NS
		 INNER JOIN OW_LAO.VIEW_PTAX_EXCHANGE_RATE EX ON EX.VALID_FROM = NS.DATE_REF
													 AND EX.TO_CURRENCY = NS.CURRENCY --'BRL'
													 AND EX.FROM_CURRENCY = 'USD'
	WHERE "SOURCE" = 'PO' AND SUBSIDIARY = 'SEDA'
		  AND NS.DATE_REF >=  ADD_DAYS(CURRENT_DATE,-1) -- ULTIMO DIA
	;
	
	/***********************************
	-- INSERE NOVOS DADOS DE PO (VTEX)
	***********************************/		
	INSERT INTO OW_LAO.TF_D2C_NERP_SALES (
		  "SOURCE"
		, DATE_REF
		, YYYYWW
		, YYYYMM
		, YYYYQQ
		, PO_CREATION_DATE
		, "PO_WEEK_DAY_NUM"
		, "PO_WEEK_DAY_NAME"
		, "PO_HOUR"
		, SALES_CHANNEL
		, SUBSIDIARY
		, CHANNEL
		, SUB_CHANNEL
		, SALES_CHANNEL_ATTR_1
		, SALES_CHANNEL_ATTR_2
		, AFFILIATE_ID
		, SKU
		, PDROD_DIVISION
		, PDROD_PRODUCT_GROUP
		, PDROD_PRODUCT
		, PROD_ATTB_1
		, SEDA_BU_ESTORE
		, SEDA_DIVISION_ESTORE
		, SEDA_CATEGORY_ESTORE
		, SEDA_FAMILY_ESTORE
		, SEDA_DESC_ESTORE
		, QTY
		, AMOUNT_LOCAL
		, AMOUNT_USD
		, PRICE_TO
		, AMOUNT_DISCOUNT
		, AMOUNT_SHIPPING
		, ITEM_NAME
		, ORDER_ID
		, "SELECTED_SLA"
		, "WAREHOUSE_ID_GROUP"
		, "ADDRESSTYPE"
		, "FRIENDLYNAME"
		, "STATE"
		, "CITY"
		, MARKETPLACE_ORDER_ID
		, CUSTOMER_PO
		, ENVIRONMENT
		, STORE_ID
		, NAME_STORE
		, "STORE_EMPLOYEE_CPF"
		, CHANNEL_TYPE
		, "O2O_TYPE" -- 020
		, REFERENCE_CODE_KIT
		, REFERENCE_CODE
		, STATUS_PO
		, AFFILIATE_ID_ADJUSTED
		, AFFILIATE_CHANNEL
		, AFFILIATE_SUB_CHANNEL
		, AFFILIATE_PARTNER_LEVEL
		, GLOBAL_CHANNEL
		, BIZ_TYPE
		, AUDIENCE_TYPE
		, "COUPON"
		, COUNTRY
		, CURRENCY
		, MODEL_TYPE
		, KPI_LAST_UPDATE
		, EMAIL_DOMAIN
		, SKU_ID
		, SKU_ID_COMPONENT
		, PO_MINUTE
		, SELLING_PRICE
		, UTM_SOURCE
		, UTM_MEDIUM 
		, UTM_PARTNER
		, UTM_CAMPAIGN
		, MARKETING_TAGS
		, CORPORATENAME
		, ITEM_INDEX
		, SELLING_AMOUNT_SHIPPING
		, SELLING_AMOUNT_LOCAL
		--, PAYMENT_DETAILS
		--, PROMOTION_DETAILS
		, ITEM_INDEX_KIT
		, PROMOS_IDS
		, PROMOS_NAME
		, PROMOS_DISCOUNTS
	)
	SELECT
		 'PO' AS SOURCE
		, PO.DATE_REF
		, CL.YYYYWW AS YYYYWW
		, CL.YYYYMM AS YYYYMM
		, CL.YYYYQQ AS YYYYQQ
		, PO.PO_CREATION_DATE
		, WEEKDAY(PO.PO_CREATION_DATE) AS "PO_WEEK_DAY_NUM"
		, DAYNAME(PO.PO_CREATION_DATE) AS "PO_WEEK_DAY_NAME"
		, EXTRACT_HOUR(PO.PO_CREATION_DATE) AS "PO_HOUR"
		-- CHANNEL
		, PO.SALES_CHANNEL
		, CASE WHEN AF.SUBSIDIARY IS NOT NULL THEN TRIM(AF.SUBSIDIARY) ELSE 'SEDA' END AS SUBSIDIARY
		, CH.CHANNEL 
		, CH.SUB_CHANNEL 
		, CH.SALES_CHANNEL_ATTR_1 
		, CH.SALES_CHANNEL_ATTR_2
		, PO.AFFILIATE_ID
		-- PRODUCT
		, PO.REFERENCE_CODE AS SKU --PD.SKU
		, PD."DIVISION" AS PDROD_DIVISION
		, PD.PRODUCT_GROUP_1 AS PDROD_PRODUCT_GROUP 
		, PD.PRODUCT_1 AS PDROD_PRODUCT 
		, PD.ATTB01 AS PROD_ATTB_1 
		, PD.SEDA_BU_ESTORE
		, PD.SEDA_DIVISION_ESTORE
		, PD.SEDA_CATEGORY_ESTORE
		, PD.SEDA_FAMILY_ESTORE
		, PD.SEDA_DESC_ESTORE		
		, PO.QTY
		, PO.AMOUNT_LOCAL
		--,0 AS AMOUNT_USD
		, CAST( PO.AMOUNT_LOCAL / IFNULL(EX.EXCHANGE_RATE, EX2.EXCHANGE_RATE) AS DECIMAL(18,2) ) AS AMOUNT_USD
		--,PO.PRICE_FROM
		, PO.PRICE_TO
		, PO.AMOUNT_DISCOUNT
		, PO.AMOUNT_SHIPPING
		, PO.ITEM_NAME
		, PO.ORDER_ID
		, SL."SELECTED_SLA"
		, SL."WAREHOUSE_ID_GROUP"
		, SL.ADDRESSTYPE
		, SL.FRIENDLYNAME
		, SL.STATE
		, SL.CITY
		, PO.MARKETPLACE_ORDER_ID
		, PO.CUSTOMER_PO
		, PO.ENVIRONMENT
		, PO.STORE_ID
		, PO.NAME_STORE
		, PO."STORE_EMPLOYEE_CPF"
		, PO.CHANNEL_TYPE
		, CASE 
			WHEN ( TRIM(UPPER(SL."SELECTED_SLA")) LIKE 'SHIP TO STORE %' 
					OR TRIM(UPPER(SL."SELECTED_SLA"))LIKE 'PONTO DE RETIRADA %'
					OR TRIM(UPPER(SL."SELECTED_SLA"))LIKE 'CLIQUE%'
				 ) AND PO.CHANNEL_TYPE = 'Store+'
			THEN 'BOPIS + EA'
			WHEN ( TRIM(UPPER(SL."SELECTED_SLA")) LIKE 'SHIP TO STORE %'
				   OR TRIM(UPPER(SL."SELECTED_SLA"))LIKE 'PONTO DE RETIRADA %'
				   OR TRIM(UPPER(SL."SELECTED_SLA"))LIKE 'CLIQUE%' )
			THEN 'BOPIS'
			WHEN ( PO.CHANNEL_TYPE = 'Store+' )
			THEN 'EA'
		  ELSE NULL END AS O2O_TYPE
		, PO.REFERENCE_CODE_KIT
		, PO.REFERENCE_CODE
		, PO.STATUS_PO
		-- AFFILIATE INFORMATION
		, PO.AFFILIATE_ID_ADJUSTED
		, AF.AFFILIATE_CHANNEL
		, AF.AFFILIATE_SUB_CHANNEL
		, AF.AFFILIATE_PARTNER_LEVEL
		, AF.GLOBAL_CHANNEL
		, AF.BIZ_TYPE
		, AF.AUDIENCE_TYPE
		, PO."COUPON"
		, AF.COUNTRY
		, AF.CURRENCY
		-- PREMIUM MODEL
		, CASE WHEN PR.MATERIAL IS NOT NULL THEN 'PREMIUM MODEL' ELSE 'NORMAL MODEL' END AS MODEL_TYPE
		--KPI_LAST_UPDATE
		, CURRENT_TIMESTAMP AS KPI_LAST_UPDATE
		, PO.EMAIL_DOMAIN
		
		, PO.SKU_ID
		, PO.SKU_ID_COMPONENT
		, PO.PO_MINUTE
		, PO.SELLING_PRICE
		, PO.UTM_SOURCE
		, PO.UTM_MEDIUM 
		, PO.UTM_PARTNER
		, PO.UTM_CAMPAIGN
		, PO.MARKETING_TAGS
		, PO.CORPORATENAME
		, PO.ITEM_INDEX
		, PO.SELLING_AMOUNT_SHIPPING
		, PO.SELLING_AMOUNT_LOCAL
		--, PMT.PAYMENT_DETAILS
		--, PRM.PROMOTION_DETAILS
		, PO.ITEM_INDEX_KIT
		, PRM.PROMOS_IDS
		, PRM.PROMOS_NAME
		, PRM.PROMOS_DISCOUNTS    		
	FROM(
		SELECT
			  PO_.DATE_REF
			, PO_.PO_CREATION_DATE
			, PO_.SALES_CHANNEL
			, PO_.AFFILIATE_ID
			--,'BRL' AS CURRENCY
			, PO_.ORDER_ID
			, PO_.MARKETPLACE_ORDER_ID
			, PO_.CUSTOMER_PO
			, PO_.ITEM_INDEX
			, PO_.ITEM_INDEX_KIT
			, PO_.ENVIRONMENT
			, ES.ID_STORE AS STORE_ID --,PO_.STORE_ID
			, ES.NAME AS NAME_STORE
			, PO_."STORE_EMPLOYEE_CPF"
			, CASE WHEN ES.ID_STORE IS NOT NULL THEN 'Store+' ELSE 'Shop' END AS CHANNEL_TYPE				 
			, PO_.REFERENCE_CODE_KIT
			
			--, PO_.REFERENCE_CODE
			, CASE WHEN UPPER(PO_.REFERENCE_CODE) LIKE '%_OUT%' THEN SUBSTRING(PO_.REFERENCE_CODE, 1, LENGTH(PO_.REFERENCE_CODE) - 5 ) ELSE PO_.REFERENCE_CODE END AS REFERENCE_CODE			
			
			, PO_.ITEM_NAME
			, PO_.STATUS_PO
			--, PO_.PRICE_FROM
			, PO_.PRICE_TO
			, PO_.AMOUNT_DISCOUNT
			, PO_.AMOUNT_SHIPPING
			, PO_.QTY
			, PO_.AMOUNT_LOCAL
			
			--, OW_LAO.AFFILIATE_ID_ADJUSTED(ES.ID_STORE, PO_.AFFILIATE_ID, PO_.SALES_CHANNEL) AS AFFILIATE_ID_ADJUSTED
			, CASE
				WHEN UPPER(PO_.REFERENCE_CODE) LIKE '%_OUT1' THEN 'TLB'
				WHEN UPPER(PO_.REFERENCE_CODE) LIKE '%_OUT3' THEN 'TLD'
				ELSE OW_LAO.AFFILIATE_ID_ADJUSTED(ES.ID_STORE, PO_.AFFILIATE_ID, PO_.SALES_CHANNEL) 
			END AS AFFILIATE_ID_ADJUSTED			
			
			, PO_.SKU_ID
			, PO_.SKU_ID_COMPONENT
			, PO_.COUPON
			, PO_.EMAIL_DOMAIN
			, PO_.PO_MINUTE
			, PO_.SELLING_PRICE
			, PO_.UTM_SOURCE
			, PO_.UTM_MEDIUM 
			, PO_.UTM_PARTNER
			, PO_.UTM_CAMPAIGN
			, PO_.MARKETING_TAGS
			, PO_.CORPORATENAME
			, PO_.SELLING_AMOUNT_SHIPPING
			, PO_.SELLING_AMOUNT_LOCAL
		FROM(
			/*****************************************************************
				PO (VTEX [SOMENTE ITENS]) {CREATION_TIMESTAMP}
			*****************************************************************/			
			SELECT
				  TO_DATE(VO.CREATION_TIMESTAMP) AS DATE_REF
				, VO.CREATION_TIMESTAMP AS PO_CREATION_DATE
				, VO.AFFILIATE_ID
				, VO.ORDER_ID
				, VO.MARKETPLACE_ORDER_ID
				, VO.HOSTNAME AS ENVIRONMENT
				, VO.STATUS AS STATUS_PO
				  --CASE WHEN EP.ORDER_ID IS NOT NULL THEN EP.STATUS
					--   WHEN VD.ORDER_ID IS NOT NULL THEN VD.STATUS
					--   ELSE VO.STATUS
				  --END AS STATUS_PO			
				, CASE WHEN ( CASE WHEN VO.CD_STORE_INFORMATION IS NOT NULL THEN VO.CD_STORE_INFORMATION ELSE VD.CD_STORE_INFORMATION END ) IS NOT NULL -- CD_STORE_INFORMATION
					   THEN ( CASE WHEN VO.CD_STORE_INFORMATION IS NOT NULL THEN VO.CD_STORE_INFORMATION ELSE VD.CD_STORE_INFORMATION END ) -- CD_STORE_INFORMATION
					   ELSE ( CASE WHEN VO.UTM_SOURCE IS NOT NULL THEN VO.UTM_SOURCE ELSE VD.UTM_SOURCE END ) -- UTM_SOURCE
				  END AS STORE_ID				
				, VO.SALES_CHANNEL
				, CASE
					WHEN VO.CD_VENDEDOR IS NOT NULL THEN VO.CD_VENDEDOR 
					WHEN VD.CD_VENDEDOR IS NOT NULL THEN VD.CD_VENDEDOR
				  END AS STORE_EMPLOYEE_CPF					
				, LI.CUSTOMER_PO					
				, VI.ITEM_INDEX
				, NULL AS ITEM_INDEX_KIT
				, '' AS REFERENCE_CODE_KIT -- NULO PARA ITEM POIS NÃO É KIT
				
				, VI.REF_ID AS REFERENCE_CODE -- não é kit (item)
				--, CASE WHEN UPPER(VI.REF_ID) LIKE '%_OUT%' THEN SUBSTRING(VI.REF_ID, 1, LENGTH(VI.REF_ID) - 5 ) ELSE VI.REF_ID END AS REFERENCE_CODE
				
				, VI.NAME AS ITEM_NAME
				--,(VI.COST_PRICE / 100) AS PRICE_FROM
				, (VI.PRICE / 100) AS PRICE_TO
				, CAST(VI.QUANTITY AS INTEGER) AS QTY
				, (CASE WHEN (VO.TOTAL_DISCOUNTS <> 0 AND VO.TOTAL_ITEMS > 0) THEN -- DESCONTOS
					( (VI.PRICE * VI.QUANTITY) / VO.TOTAL_ITEMS ) * VO.TOTAL_DISCOUNTS
				  ELSE 0 END / 100) AS AMOUNT_DISCOUNT
				, (CASE WHEN (VO.TOTAL_SHIPPING <> 0 AND VO.TOTAL_ITEMS > 0) THEN -- FRETE
					( (VI.PRICE * VI.QUANTITY) / VO.TOTAL_ITEMS ) * VO.TOTAL_SHIPPING
				  ELSE 0 END / 100) AS AMOUNT_SHIPPING					
				, CAST((
						( VI.PRICE * VI.QUANTITY ) 
						+ CASE WHEN (VO.TOTAL_DISCOUNTS <> 0 AND VO.TOTAL_ITEMS > 0) THEN -- (SUBTRAI OS DESCONTOS)
							( (VI.PRICE * VI.QUANTITY) / VO.TOTAL_ITEMS ) * VO.TOTAL_DISCOUNTS
						 ELSE 0 END
						+ CASE WHEN (VO.TOTAL_SHIPPING <> 0 AND VO.TOTAL_ITEMS > 0) THEN -- FRETE SOMA O FRETE
							( (VI.PRICE * VI.QUANTITY) / VO.TOTAL_ITEMS ) * VO.TOTAL_SHIPPING
						 ELSE 0 END
					) / 100
				  AS DECIMAL(18,2)) AS AMOUNT_LOCAL
				  
				-- ************* SELLING PRICE *************
				, CAST(( SP.SHIPPING_PRICE ) / 100 AS DECIMAL(18,4)) AS SELLING_AMOUNT_SHIPPING
				
				, CAST((
						( VI.SELLING_PRICE * VI.QUANTITY) 
						  + IFNULL(SP.SHIPPING_PRICE,0) -- FRETE SOMA O FRETE
				  ) / 100
				  AS DECIMAL(18,4)) AS SELLING_AMOUNT_LOCAL
				  
				, VI.SKU_ID -- não é kit (item)
				, NULL AS SKU_ID_COMPONENT
				  
				, COALESCE( EP.COUPON, B2.COUPON, VD.COUPON, VO.COUPON) AS COUPON
				  
				, SUBSTRING (  SUBSTR_REGEXPR('@(.+?)-[[:digit:]]' IN COALESCE( EP.EMAIL_DOMAIN, B2.EMAIL_DOMAIN, VD.EMAIL_DOMAIN, VO.EMAIL_DOMAIN)  ), 2
							 , LENGTH ( SUBSTR_REGEXPR('@(.+?)-[[:digit:]]' IN COALESCE( EP.EMAIL_DOMAIN, B2.EMAIL_DOMAIN, VD.EMAIL_DOMAIN, VO.EMAIL_DOMAIN)  )) - 3
				  ) AS EMAIL_DOMAIN
				
				, EXTRACT_MINUTE(VO.CREATION_TIMESTAMP) AS "PO_MINUTE"
				, CAST(( VI.SELLING_PRICE ) / 100 AS DECIMAL(18,2)) AS SELLING_PRICE
				, COALESCE( EP.UTM_SOURCE, B2.UTM_SOURCE, VD.UTM_SOURCE, VO.UTM_SOURCE) AS UTM_SOURCE
				, COALESCE( EP.UTM_MEDIUM, B2.UTM_MEDIUM, VD.UTM_MEDIUM, VO.UTM_MEDIUM) AS UTM_MEDIUM 
				, COALESCE( EP.UTM_PARTNER, B2.UTM_PARTNER, VD.UTM_PARTNER, VO.UTM_PARTNER) AS UTM_PARTNER
				, COALESCE( EP.UTM_CAMPAIGN, B2.UTM_CAMPAIGN, VD.UTM_CAMPAIGN, VO.UTM_CAMPAIGN) AS UTM_CAMPAIGN
				, COALESCE( EP.MARKETING_TAGS, B2.MARKETING_TAGS, VD.MARKETING_TAGS, VO.MARKETING_TAGS) AS MARKETING_TAGS
				, B2.CORPORATENAME ---- É SÓ NO B2B
				
			FROM OW_LAO.TMP_PO_ORDER_ID_PO_VTEX_TMP LI -- (LIST)
				INNER JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER VO -- (VTEX ORDER)
					ON VO.ORDER_ID = LI.ORDER_ID
				INNER JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_ITEM VI -- (VTEX ITEM)
					ON VO.ORDER_ID = VI.ORDER_ID
				LEFT JOIN OW_LAO.TMP_ITEM_COMPONENTS_PO_VTEX_TMP VC -- (VTEX COMPONENTES) [NÃO DEVE TER COMPONENTS POR ISSO LEFT]
					ON VI.ORDER_ID = VC.ORDER_ID 
					   AND VI.SKU_ID = VC.SKU_ID
				LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SALES_ORDER VD -- (VTEX DETAIL)
					ON VO.MARKETPLACE_ORDER_ID = VD.ORDER_ID
				LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_EPP2_SALES_ORDER EP 
					ON VO.MARKETPLACE_ORDER_ID = EP.ORDER_ID --(EPP2)
				LEFT JOIN --U_PRJ_ECOM.RAW_VTEX_SSG_BR_B2B_SALES_ORDER B2 -- B2
						(
							SELECT DISTINCT
								  ORDER_ID
								, COUPON
								, EMAIL_DOMAIN
								, UTM_SOURCE
								, UTM_MEDIUM 
								, UTM_PARTNER
								, UTM_CAMPAIGN
								, MARKETING_TAGS
								, CORPORATENAME ---- É SÓ NO B2B
							FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_B2B_SALES_ORDER -- B2				
							WHERE SELLER_ORDER_ID IN ( SELECT ORDER_ID FROM OW_LAO.TMP_PO_ORDER_ID_PO_VTEX_TMP)
						) B2
					ON VO.MARKETPLACE_ORDER_ID = B2.ORDER_ID
				LEFT JOIN OW_LAO.TMP_SHIPPING_VTEX_TMP SP -- SHIPPING
						ON VI.ORDER_ID = SP.ORDER_ID 
					       AND VI.ITEM_INDEX = SP.ITEM_INDEX
			WHERE VC.REF_ID IS NULL -- NÃO DEVE TER COMPONENTS
				  AND VI.QUANTITY IS NOT NULL
				  AND VI.PRICE IS NOT NULL
				  AND VO.STATUS IS NOT NULL
  				  AND CASE WHEN EP.ORDER_ID IS NOT NULL THEN EP.STATUS
						   WHEN VD.ORDER_ID IS NOT NULL THEN VD.STATUS
					       ELSE VO.STATUS
					  END IS NOT NULL
			
			/*****************************************************************
			PO (VTEX-[SOMENTE COMPONENTES] {CREATION_TIMESTAMP}) 
			******************************************************************/
			UNION ALL
			SELECT
				  TO_DATE(VO.CREATION_TIMESTAMP) AS DATE_REF
				, VO.CREATION_TIMESTAMP AS PO_CREATION_DATE
				, VO.AFFILIATE_ID
				, VO.ORDER_ID
				, VO.MARKETPLACE_ORDER_ID
				, VO.HOSTNAME AS ENVIRONMENT
				, VO.STATUS AS STATUS_PO
				  -- CASE WHEN EP.ORDER_ID IS NOT NULL THEN EP.STATUS
					--   WHEN VD.ORDER_ID IS NOT NULL THEN VD.STATUS
					--   ELSE VO.STATUS
				  -- END AS STATUS_PO
				, CASE WHEN ( CASE WHEN VO.CD_STORE_INFORMATION IS NOT NULL THEN VO.CD_STORE_INFORMATION ELSE VD.CD_STORE_INFORMATION END ) IS NOT NULL -- CD_STORE_INFORMATION
					   THEN ( CASE WHEN VO.CD_STORE_INFORMATION IS NOT NULL THEN VO.CD_STORE_INFORMATION ELSE VD.CD_STORE_INFORMATION END ) -- CD_STORE_INFORMATION
					   ELSE ( CASE WHEN VO.UTM_SOURCE IS NOT NULL THEN VO.UTM_SOURCE ELSE VD.UTM_SOURCE END ) -- UTM_SOURCE
				  END AS STORE_ID
				, VO.SALES_CHANNEL
				, CASE
					WHEN VO.CD_VENDEDOR IS NOT NULL THEN VO.CD_VENDEDOR 
					WHEN VD.CD_VENDEDOR IS NOT NULL THEN VD.CD_VENDEDOR
				  END AS STORE_EMPLOYEE_CPF
				, LI.CUSTOMER_PO
				, VI.ITEM_INDEX
				, VC.ITEM_INDEX_KIT
				, VI.REF_ID AS REFERENCE_CODE_KIT
				
				, VC.REF_ID AS REFERENCE_CODE -- é kit (components)
				--, CASE WHEN UPPER(VC.REF_ID) LIKE '%_OUT%' THEN SUBSTRING(VC.REF_ID, 1, LENGTH(VC.REF_ID) - 5 ) ELSE VC.REF_ID END AS REFERENCE_CODE
				
				, VC.NAME AS ITEM_NAME
				--,(VC.COST_PRICE / 100) AS PRICE_FROM
				, (VC.PRICE/ 100) AS PRICE_TO
				, CAST(VC.QUANTITY * VI.QUANTITY AS INTEGER) AS QTY -- (MULTIPLICA QTY DE KIT PELO DE ITEM )
				, (CASE WHEN (VO.TOTAL_DISCOUNTS <> 0 AND VO.TOTAL_ITEMS > 0) THEN -- DESCONTOS
					( (VC.PRICE * (VC.QUANTITY * VI.QUANTITY)) / VO.TOTAL_ITEMS ) * VO.TOTAL_DISCOUNTS
				  ELSE 0 END / 100) AS AMOUNT_DISCOUNT
				, (CASE WHEN (VO.TOTAL_SHIPPING <> 0 AND VO.TOTAL_ITEMS > 0) THEN -- FRETE
					( (VC.PRICE * (VC.QUANTITY * VI.QUANTITY)) / VO.TOTAL_ITEMS ) * VO.TOTAL_SHIPPING
				  ELSE 0 END / 100) AS AMOUNT_SHIPPING
				, CAST((
						(VC.PRICE * (VC.QUANTITY * VI.QUANTITY)) 
						+ CASE WHEN (VO.TOTAL_DISCOUNTS <> 0 AND VO.TOTAL_ITEMS > 0) THEN -- (SUBTRAI OS DESCONTOS)
							( (VC.PRICE * (VC.QUANTITY * VI.QUANTITY)) / VO.TOTAL_ITEMS ) * VO.TOTAL_DISCOUNTS
						 ELSE 0 END
						+ CASE WHEN (VO.TOTAL_SHIPPING <> 0 AND VO.TOTAL_ITEMS > 0) THEN -- FRETE SOMA O FRETE
							( (VC.PRICE * (VC.QUANTITY * VI.QUANTITY)) / VO.TOTAL_ITEMS ) * VO.TOTAL_SHIPPING
						 ELSE 0 END
					)  / 100
				  AS DECIMAL(18,2)) AS AMOUNT_LOCAL
				  
				-- ************* SELLING PRICE *************
				, CAST(( IFNULL(CASE WHEN VC.SELLING_PRICE_TOTAL > 0 THEN 
						  	              (SP.SHIPPING_PRICE * ( VC.SELLING_PRICE_AMOUNT / VC.SELLING_PRICE_TOTAL) ) 
						  	       END ,0)
				) / 100 AS DECIMAL(18,4)) AS SELLING_AMOUNT_SHIPPING -- FRETE NOVO
				
				, CAST(( ( VC.SELLING_PRICE * (VC.QUANTITY * VI.QUANTITY) ) 
						  + IFNULL(CASE WHEN VC.SELLING_PRICE_TOTAL > 0 THEN 
						  	                 (SP.SHIPPING_PRICE * ( VC.SELLING_PRICE_AMOUNT / VC.SELLING_PRICE_TOTAL) ) 
						  	       END ,0) -- FRETE SOMA O FRETE
				  ) / 100
				  AS DECIMAL(18,4)) AS SELLING_AMOUNT_LOCAL
				  
				 , VI.SKU_ID
				 , VC.SKU_ID_COMPONENT -- é kit (components)
				
				--, IFNULL(IFNULL(EP.COUPON, VD.COUPON), VO.COUPON) AS COUPON
				--, SUBSTRING (  SUBSTR_REGEXPR('@(.+?)-[[:digit:]]' IN IFNULL(IFNULL(EP.EMAIL_DOMAIN, VD.EMAIL_DOMAIN), VO.EMAIL_DOMAIN)  ), 2
				--			 , LENGTH ( SUBSTR_REGEXPR('@(.+?)-[[:digit:]]' IN IFNULL(IFNULL(EP.EMAIL_DOMAIN, VD.EMAIL_DOMAIN), VO.EMAIL_DOMAIN)  )) - 3
				--  ) AS EMAIL_DOMAIN
				
				, COALESCE( EP.COUPON, B2.COUPON, VD.COUPON, VO.COUPON) AS COUPON
				, SUBSTRING (  SUBSTR_REGEXPR('@(.+?)-[[:digit:]]' IN COALESCE( EP.EMAIL_DOMAIN, B2.EMAIL_DOMAIN, VD.EMAIL_DOMAIN, VO.EMAIL_DOMAIN)  ), 2
							 , LENGTH ( SUBSTR_REGEXPR('@(.+?)-[[:digit:]]' IN COALESCE( EP.EMAIL_DOMAIN, B2.EMAIL_DOMAIN, VD.EMAIL_DOMAIN, VO.EMAIL_DOMAIN)  )) - 3
				  ) AS EMAIL_DOMAIN
				
				, EXTRACT_MINUTE(VO.CREATION_TIMESTAMP) AS "PO_MINUTE"
				, CAST(( VC.SELLING_PRICE ) / 100 AS DECIMAL(18,2)) AS SELLING_PRICE -- COMPONENTE
				, COALESCE( EP.UTM_SOURCE, B2.UTM_SOURCE, VD.UTM_SOURCE, VO.UTM_SOURCE) AS UTM_SOURCE
				, COALESCE( EP.UTM_MEDIUM, B2.UTM_MEDIUM, VD.UTM_MEDIUM, VO.UTM_MEDIUM) AS UTM_MEDIUM 
				, COALESCE( EP.UTM_PARTNER, B2.UTM_PARTNER, VD.UTM_PARTNER, VO.UTM_PARTNER) AS UTM_PARTNER
				, COALESCE( EP.UTM_CAMPAIGN, B2.UTM_CAMPAIGN, VD.UTM_CAMPAIGN, VO.UTM_CAMPAIGN) AS UTM_CAMPAIGN
				, COALESCE( EP.MARKETING_TAGS, B2.MARKETING_TAGS, VD.MARKETING_TAGS, VO.MARKETING_TAGS) AS MARKETING_TAGS
				, B2.CORPORATENAME ---- É SÓ NO B2B
				
			FROM OW_LAO.TMP_PO_ORDER_ID_PO_VTEX_TMP LI -- (LIST)
				
				INNER JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER VO -- (VTEX ORDER)
					ON VO.ORDER_ID = LI.ORDER_ID	
				INNER JOIN -- U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_ITEM VI -- (VTEX ITEM)
 					OW_LAO.TMP_ORDER_ITEM_TO_COMPONENTS_PO_VTEX_TMP VI ON VO.ORDER_ID = VI.ORDER_ID
				INNER JOIN OW_LAO.TMP_ITEM_COMPONENTS_PO_VTEX_TMP VC -- (VTEX COMPONENTES) [TEM SOMENTE COMPONENTS POR ISSO INNER]
					ON VI.ORDER_ID = VC.ORDER_ID 
					   AND VI.SKU_ID = VC.SKU_ID
					   AND  ( 
					   		 	VI.ITEM_INDEX_COMPONENT_COUNT = 1 
					   		 	OR VI.ITEM_INDEX_COMPONENT = VC.ITEM_INDEX_COMPONENT
					   		)
				LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SALES_ORDER VD -- (VTEX DETAIL)
					ON VO.MARKETPLACE_ORDER_ID = VD.ORDER_ID
				LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_EPP2_SALES_ORDER EP 
					ON VO.MARKETPLACE_ORDER_ID = EP.ORDER_ID --(EPP2)
				LEFT JOIN -- B2B
						(
							SELECT DISTINCT
								  ORDER_ID
								, COUPON
								, EMAIL_DOMAIN
								, UTM_SOURCE
								, UTM_MEDIUM 
								, UTM_PARTNER
								, UTM_CAMPAIGN
								, MARKETING_TAGS
								, CORPORATENAME ---- É SÓ NO B2B
							FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_B2B_SALES_ORDER -- B2				
							WHERE SELLER_ORDER_ID IN ( SELECT ORDER_ID FROM OW_LAO.TMP_PO_ORDER_ID_PO_VTEX_TMP)
						) B2
					ON VO.MARKETPLACE_ORDER_ID = B2.ORDER_ID
				LEFT JOIN OW_LAO.TMP_SHIPPING_VTEX_TMP SP -- SHIPPING
						ON VI.ORDER_ID = SP.ORDER_ID 
					       AND VI.ITEM_INDEX = SP.ITEM_INDEX
			WHERE VC.REF_ID IS NOT NULL -- SOMENTE COMPONENTS
				AND VC.QUANTITY IS NOT NULL -- SOMENTE QUANDO TEM COMPONENTES
				AND VC.PRICE IS NOT NULL
				AND VO.STATUS IS NOT NULL
  				AND CASE WHEN EP.ORDER_ID IS NOT NULL THEN EP.STATUS
						 WHEN VD.ORDER_ID IS NOT NULL THEN VD.STATUS
						 ELSE VO.STATUS
					END IS NOT NULL
		)PO_
		LEFT JOIN U_PRJ_ECOM.ODS_VTEX_SSG_BR_SHOP_DATA_ENTITIES_STORES_SDS ES
			ON ES.ID_STORE = PO_.STORE_ID -- ENDLESS_STORE
	) PO
	LEFT JOIN OW_MD.DIM_SALES_CHANNEL CH ON PO.SALES_CHANNEL = CH.VTEX_POLICY
	LEFT JOIN OW_MD.DIM_PRODUCT PD ON PD.SKU = PO.REFERENCE_CODE
	LEFT JOIN (
			SELECT DISTINCT TRIM(ITEM) AS MATERIAL
			FROM OW_LAO.ODS_GSCM_PREMIUM_MODELS
		) PR ON PR.MATERIAL = PO.REFERENCE_CODE		
	LEFT JOIN OW_MD.DIM_CALENDAR CL ON CL.YYYYMMDD = PO.DATE_REF
	LEFT JOIN OW_LAO.DIM_AFFILIATE_CHANNEL AF ON AF.AFFILIATE_ID = PO.AFFILIATE_ID_ADJUSTED
	LEFT JOIN OW_LAO.VIEW_PTAX_EXCHANGE_RATE EX ON EX.VALID_FROM = PO.DATE_REF
											AND EX.TO_CURRENCY = 'BRL' -- AF.CURRENCY
											AND EX.FROM_CURRENCY = 'USD'
	LEFT JOIN (
			SELECT TO_CURRENCY
				, VALID_FROM
				, EXCHANGE_RATE
			FROM ( SELECT TO_CURRENCY
						, VALID_FROM
						, EXCHANGE_RATE
						, RANK() OVER( PARTITION BY TO_CURRENCY ORDER BY VALID_FROM DESC) AS SEQ
					FROM OW_LAO.VIEW_PTAX_EXCHANGE_RATE EX
					WHERE FROM_CURRENCY = 'USD'
				)
			WHERE SEQ = 1
		) EX2 ON EX2.TO_CURRENCY = 'BRL' -- AF.CURRENCY
	LEFT JOIN OW_LAO.TMP_SHIPPING_VTEX_TMP SL -- PEGA O SELECTED_SLA
			ON PO.ORDER_ID = SL.ORDER_ID 
		       AND SL.ITEM_INDEX = PO.ITEM_INDEX
	LEFT JOIN OW_LAO.TMP_PROMOTION_VTEX_NERP_SALES_TMP PRM 
		ON PO.ORDER_ID = PRM.ORDER_ID 
		   AND PO.ITEM_INDEX = PRM.ITEM_INDEX
		   AND IFNULL(PO.ITEM_INDEX_KIT,9999) = IFNULL(PRM.ITEM_INDEX_KIT,9999)
	;
	/**************************************
	-- PAYMENT
	**************************************/
	IF EXISTS( SELECT TABLE_NAME FROM SYS.TABLES WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TMP_PAYMENT_VTEX_NERP_SALES') THEN
		DROP TABLE OW_LAO.TMP_PAYMENT_VTEX_NERP_SALES_TMP;
	END IF;
	CREATE TABLE OW_LAO.TMP_PAYMENT_VTEX_NERP_SALES_TMP AS ( -- PEGA O SELECTED_SLA
		SELECT ORDER_ID
			 , ITEM_INDEX
			 , ITEM_INDEX_KIT
			 , STRING_AGG(
				  PAYMENT_SYSTEM_NAME
				, CHAR(13) || CHAR(10)  || ','
			 ) AS PAYMENT_NAME
			 , STRING_AGG(
				  INSTALLMENTS
				, CHAR(13) || CHAR(10)  || ','
			 ) AS PAYMENT_INSTALLMENTS
			 , STRING_AGG(
				  ROUND(VALUE, 2)
				, CHAR(13) || CHAR(10)  || ','
			 ) AS PAYMENT_VALUE
		FROM (
			SELECT NS.ORDER_ID
				 , NS.ITEM_INDEX
				 , NS.ITEM_INDEX_KIT
				 --, (NS.SELLING_AMOUNT_LOCAL / NT.SELLING_AMOUNT_LOCAL_TOTAL) AS RATIO
				 , CASE WHEN NT.SELLING_AMOUNT_LOCAL_TOTAL > 0 THEN 
				 	(NS.SELLING_AMOUNT_LOCAL / NT.SELLING_AMOUNT_LOCAL_TOTAL) * (PY.VALUE / 100) 
				   END AS VALUE
				 , PY.INSTALLMENTS
				 , PY.PAYMENT_SYSTEM_NAME
			FROM (
				SELECT ORDER_ID
					 , ITEM_INDEX
					 , ITEM_INDEX_KIT
					 , SELLING_AMOUNT_LOCAL AS SELLING_AMOUNT_LOCAL
				FROM OW_LAO.TF_D2C_NERP_SALES 
				WHERE ORDER_ID IN ( SELECT ORDER_ID FROM OW_LAO.TMP_PO_ORDER_ID_PO_VTEX_TMP )
					AND SOURCE = 'PO'
			) NS
			INNER JOIN	(
				SELECT ORDER_ID
					 , SUM(SELLING_AMOUNT_LOCAL) AS SELLING_AMOUNT_LOCAL_TOTAL
				FROM OW_LAO.TF_D2C_NERP_SALES
				WHERE ORDER_ID IN (  SELECT ORDER_ID FROM OW_LAO.TMP_PO_ORDER_ID_PO_VTEX_TMP )
					AND SOURCE = 'PO'
				GROUP BY 
					ORDER_ID
			) NT ON NS.ORDER_ID = NT.ORDER_ID
			INNER JOIN ( -- PAYMENT
				SELECT DISTINCT
					  BRS.ORDER_ID
					, COALESCE (PAYMENT_B2B.VALUE, PAYMENT_EPP.VALUE, PAYMENT_BR.VALUE, PAYMENT.VALUE) AS VALUE
					, PAYMENT.INSTALLMENTS AS INSTALLMENTS
					, COALESCE (PAYMENT_B2B.PAYMENT_SYSTEM_NAME, PAYMENT_EPP.PAYMENT_SYSTEM_NAME, PAYMENT_BR.PAYMENT_SYSTEM_NAME, PAYMENT.PAYMENT_SYSTEM_NAME) AS "PAYMENT_SYSTEM_NAME"
					, CASE
						WHEN COALESCE (PAYMENT_B2B.PAYMENT_SYSTEM_NAME, PAYMENT_EPP.PAYMENT_SYSTEM_NAME, PAYMENT_BR.PAYMENT_SYSTEM_NAME, PAYMENT.PAYMENT_SYSTEM_NAME) IN ('Boleto Bancário') THEN 'BOLETO BANCARIO'
						WHEN COALESCE (PAYMENT_B2B.PAYMENT_SYSTEM_NAME, PAYMENT_EPP.PAYMENT_SYSTEM_NAME, PAYMENT_BR.PAYMENT_SYSTEM_NAME, PAYMENT.PAYMENT_SYSTEM_NAME) IN ('Visa','Samsung Itaucard','Elo','Hipercard','Mastercard','American Express','Cartão Santander','Porto Seguro Mastercard','Diners','Porto Seguro Visa','Cartões Bradesco') THEN	'CREDIT CARD'
						WHEN COALESCE (PAYMENT_B2B.PAYMENT_SYSTEM_NAME, PAYMENT_EPP.PAYMENT_SYSTEM_NAME, PAYMENT_BR.PAYMENT_SYSTEM_NAME, PAYMENT.PAYMENT_SYSTEM_NAME) IN ('Pix') THEN 'PIX'
						WHEN COALESCE (PAYMENT_B2B.PAYMENT_SYSTEM_NAME, PAYMENT_EPP.PAYMENT_SYSTEM_NAME, PAYMENT_BR.PAYMENT_SYSTEM_NAME, PAYMENT.PAYMENT_SYSTEM_NAME) IN ('PicPay','Samsung Pay','AmeDigital') THEN 'DIGITAL'
						WHEN COALESCE (PAYMENT_B2B.PAYMENT_SYSTEM_NAME, PAYMENT_EPP.PAYMENT_SYSTEM_NAME, PAYMENT_BR.PAYMENT_SYSTEM_NAME, PAYMENT.PAYMENT_SYSTEM_NAME) IN ('Vale') THEN 'VALE'
						WHEN COALESCE (PAYMENT_B2B.PAYMENT_SYSTEM_NAME, PAYMENT_EPP.PAYMENT_SYSTEM_NAME, PAYMENT_BR.PAYMENT_SYSTEM_NAME, PAYMENT.PAYMENT_SYSTEM_NAME) LIKE 'Valor assumido pelo afiliado%' THEN 'MKT PLACE'
						ELSE 'CHECK VALUES' END
					  AS PAYMENT_SYSTEM
				FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER BRS
					LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_PAYMENT PAYMENT ON BRS.ORDER_ID = PAYMENT.ORDER_ID
					LEFT JOIN (
						SELECT ORDER_ID, MAX(UPDATED_AT), PAYMENT_SYSTEM_NAME, ACQUIRER, SUM(VALUE) AS VALUE
						FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SALES_ORDER_PAYMENT
						WHERE ( ORDER_ID IN ( SELECT ORDER_ID FROM OW_LAO.TMP_PO_ORDER_ID_PO_VTEX_TMP )
								OR ORDER_ID IN ( SELECT ORDER_ID FROM OW_LAO.TMP_PO_ORDER_ID_PO_VTEX_TMP))
						GROUP BY ORDER_ID, PAYMENT_SYSTEM_NAME, ACQUIRER
					) PAYMENT_BR ON BRS.MARKETPLACE_ORDER_ID = PAYMENT_BR.ORDER_ID
					LEFT JOIN(
						SELECT ORDER_ID, MAX(UPDATED_AT), PAYMENT_SYSTEM_NAME , ACQUIRER, SUM(VALUE) AS VALUE
						FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_EPP2_SALES_ORDER_PAYMENT
						WHERE ( ORDER_ID IN (  SELECT ORDER_ID FROM OW_LAO.TMP_PO_ORDER_ID_PO_VTEX_TMP )
								OR ORDER_ID IN ( SELECT ORDER_ID FROM OW_LAO.TMP_PO_ORDER_ID_PO_VTEX_TMP))
						GROUP BY ORDER_ID, PAYMENT_SYSTEM_NAME, ACQUIRER
					) PAYMENT_EPP ON BRS.MARKETPLACE_ORDER_ID = PAYMENT_EPP.ORDER_ID
					LEFT JOIN(
						SELECT ORDER_ID, MAX(UPDATED_AT), PAYMENT_SYSTEM_NAME , ACQUIRER, SUM(VALUE) AS VALUE
						FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_B2B_SALES_ORDER_PAYMENT
						WHERE ( ORDER_ID IN (  SELECT ORDER_ID FROM OW_LAO.TMP_PO_ORDER_ID_PO_VTEX_TMP )
								OR ORDER_ID IN ( SELECT ORDER_ID FROM OW_LAO.TMP_PO_ORDER_ID_PO_VTEX_TMP))
						GROUP BY ORDER_ID, PAYMENT_SYSTEM_NAME, ACQUIRER
					) PAYMENT_B2B ON BRS.MARKETPLACE_ORDER_ID = PAYMENT_B2B.ORDER_ID
				WHERE BRS.ORDER_ID IN (  SELECT ORDER_ID FROM OW_LAO.TMP_PO_ORDER_ID_PO_VTEX_TMP )
			)PY ON NS.ORDER_ID = PY.ORDER_ID
		)
		GROUP BY
			  ORDER_ID
			, ITEM_INDEX
			, ITEM_INDEX_KIT
	);
	/*********************************************************
	* GROSS MARGIN
	* *******************************************************/
	UPDATE NS SET
         TAX_SKU = TS.TAX_SKU --, TC.TAX_SEDA_CATEGORY_ESTORE ) 
       , TAX_INCENTIVE_SKU = TS.TAX_INCENTIVE_SKU --, TC.TAX_INCENTIVE_SEDA_CATEGORY_ESTORE)
       , COGS_UNIT = CG.COGS_UNIT
       , COGS_TTL = (CG.COGS_UNIT * NS.QTY) -- AS COGS_TTL
       , NET_SALES = (NS.SELLING_AMOUNT_LOCAL * COALESCE ( TS.TAX_SKU, TC.TAX_SEDA_CATEGORY_ESTORE )) + (NS.SELLING_AMOUNT_LOCAL * COALESCE ( TS.TAX_INCENTIVE_SKU, TC.TAX_INCENTIVE_SEDA_CATEGORY_ESTORE)) -- AS NET_SALES
       , GROSS_PROFIT =  (NS.SELLING_AMOUNT_LOCAL * COALESCE ( TS.TAX_SKU, TC.TAX_SEDA_CATEGORY_ESTORE ) ) +  (NS.SELLING_AMOUNT_LOCAL * COALESCE ( TS.TAX_INCENTIVE_SKU, TC.TAX_INCENTIVE_SEDA_CATEGORY_ESTORE)) - (CG.COGS_UNIT * NS.QTY) -- AS GROSS_PROFIT_SKU
       , TAX_CATEGORY = TC.TAX_SEDA_CATEGORY_ESTORE
       , TAX_INCENTIVE_CATEGORY = TC.TAX_INCENTIVE_SEDA_CATEGORY_ESTORE
       , SKU_MAN = MSK.SKU_MAN
	FROM OW_LAO.TF_D2C_NERP_SALES NS
		LEFT JOIN OW_MD.MAP_SKU_GROSS_MARGIN AS MSK
			 ON NS.REFERENCE_CODE = MSK.SKU_SE
			   AND TRIM(UPPER(NS.STATE)) = TRIM(UPPER(MSK.UF))
			   
		/*********
		LEFT JOIN (
			SELECT 
				  SK.SKU
				, SK.REGION
				, SK.TAX_SKU
				, SK.TAX_INCENTIVE_SKU
			FROM OW_LAO.DIM_TAX_GROSS_MARGIN_BY_SKU SK
				INNER JOIN (
					SELECT SKU
						, REGION
						, MAX(BILLING_DATE_MIN) AS BILLING_DATE_MIN
					FROM OW_LAO.DIM_TAX_GROSS_MARGIN_BY_SKU
					WHERE BILLING_DATE_MIN <= ADD_DAYS(CURRENT_TIMESTAMP, -60)-- ( SELECT DATE_FIM FROM OW_LAO.TMP_PARAMETER_PO_VTEX_TMP )
					GROUP BY SKU
						, REGION
				) DT ON SK.SKU  = DT.SKU
						AND SK.REGION  = DT.REGION
						AND SK.BILLING_DATE_MIN  = DT.BILLING_DATE_MIN
		) TS ON IFNULL(MSK.SKU_MAN, NS.REFERENCE_CODE) = TS.SKU --NS.REFERENCE_CODE = TS.SKU
			AND TRIM(UPPER(NS.STATE)) = TRIM(UPPER(TS.REGION))
		********/
			
		LEFT JOIN (
		     SELECT SKU
		            ,REGION
		            ,SUM (AMOUNT_ZKE) / SUM (NF_TOTAL_AMT) AS TAX_SKU
		            ,SUM (TAX_INCENTIVE_ZKE) / SUM (NF_TOTAL_AMT) AS TAX_INCENTIVE_SKU
		     FROM OW_LAO.TF_NERP_GROSS_MARGIN
		     WHERE 1 = 1
			     AND BILLING_DATE BETWEEN ADD_DAYS(NOW (), -60) AND NOW()
			     AND AFFILIATE_SUB_CHANNEL <> 'Outlet'
			     AND SALES_DOCUMENT_TYPE = 'YS10'
			     AND AMOUNT_ZKE >= 0
			     AND TAX_INCENTIVE_ZKE >= 0
		     GROUP BY SKU, REGION
		) TS ON IFNULL(MSK.SKU_MAN, NS.REFERENCE_CODE) = TS.SKU --NS.REFERENCE_CODE = TS.SKU
			AND TRIM(UPPER(NS.STATE)) = TRIM(UPPER(TS.REGION))
			
		/****************
		LEFT JOIN (
			SELECT -- CATEGORIA MAIS RECENTE NO BILLING_DATE_MIN
				  SK.SEDA_CATEGORY_ESTORE
				, SK.REGION
				, SK.TAX_SEDA_CATEGORY_ESTORE
				, SK.TAX_INCENTIVE_SEDA_CATEGORY_ESTORE
			FROM OW_LAO.DIM_TAX_GROSS_MARGIN_BY_CATEGORY SK
				INNER JOIN (
					SELECT SEDA_CATEGORY_ESTORE
						, REGION
						, MAX(BILLING_DATE_MIN) AS BILLING_DATE_MIN
					FROM OW_LAO.DIM_TAX_GROSS_MARGIN_BY_CATEGORY
					WHERE BILLING_DATE_MIN <= ADD_DAYS(CURRENT_TIMESTAMP, -60)--( SELECT DATE_FIM FROM OW_LAO.TMP_PARAMETER_PO_VTEX_TMP )
					GROUP BY SEDA_CATEGORY_ESTORE
						, REGION
				) DT ON SK.SEDA_CATEGORY_ESTORE  = DT.SEDA_CATEGORY_ESTORE
						AND UPPER(SK.REGION) = UPPER(DT.REGION)
						AND SK.BILLING_DATE_MIN  = DT.BILLING_DATE_MIN
		) TC ON TRIM(UPPER(NS.SEDA_CATEGORY_ESTORE)) = TRIM(UPPER(TC.SEDA_CATEGORY_ESTORE))
			AND TRIM(UPPER(NS.STATE)) = TRIM(UPPER(TC.REGION))
		****************/	
			
		--/****************
		LEFT JOIN (
			     SELECT SEDA_CATEGORY_ESTORE
			            , REGION
			            , SUM (AMOUNT_ZKE) / SUM (NF_TOTAL_AMT) AS TAX_SEDA_CATEGORY_ESTORE
			            , SUM (TAX_INCENTIVE_ZKE) / SUM (NF_TOTAL_AMT) AS TAX_INCENTIVE_SEDA_CATEGORY_ESTORE
			     FROM OW_LAO.TF_NERP_GROSS_MARGIN
			     WHERE 1 = 1 
				     AND BILLING_DATE BETWEEN ADD_DAYS(NOW (), -60) AND NOW()
				     AND AFFILIATE_SUB_CHANNEL <> 'Outlet'
				     AND SALES_DOCUMENT_TYPE = 'YS10'
				     AND AMOUNT_ZKE >= 0
				     AND TAX_INCENTIVE_ZKE >= 0
			     GROUP BY SEDA_CATEGORY_ESTORE, REGION
		) TC ON TRIM(UPPER(NS.SEDA_CATEGORY_ESTORE)) = TRIM(UPPER(TC.SEDA_CATEGORY_ESTORE))
			AND TRIM(UPPER(NS.STATE)) = TRIM(UPPER(TC.REGION))
		--****************/	
			
		LEFT JOIN OW_MD.COGS CG
			ON 1=1-- CG.YYYYMM = NS.YYYYMM
				AND CG.YYYYMM = TO_CHAR(NS.DATE_REF, 'YYYYMM') 
			    -- AND CG.REFERENCE_CODE = NS.REFERENCE_CODE
				AND IFNULL(MSK.SKU_MAN, NS.REFERENCE_CODE) = CG.REFERENCE_CODE
	WHERE NS.ORDER_ID IN ( SELECT ORDER_ID FROM OW_LAO.TMP_PO_ORDER_ID_PO_VTEX_TMP )
		AND NS.SUBSIDIARY = 'SEDA'
		AND NS.SOURCE = 'PO'
		-- AND LOWER(NS.STATUS_PO) NOT LIKE '%cancel%'
		-- AND LOWER(NS.AFFILIATE_SUB_CHANNEL) <> 'outlet'
		-- AND TRIM(UPPER(NS.SEDA_CATEGORY_ESTORE)) IN ('AC', 'COOK', 'DW', 'REF', 'WM', 'VC', 'WRB', 'SMTP', 'NPC', 'TABLET','AV', 'MONITOR', 'TV')
		-- AND TRIM(UPPER(NS.STATE)) IN ('AC', 'AL', 'AM', 'AP', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MG', 'MS', 'MT', 'PA',
		--		   'PB', 'PE', 'PI', 'PR', 'RJ', 'RN', 'RO', 'RR', 'RS', 'SC', 'SE', 'SP', 'TO')
		 -- AND NS.DATE_REF BETWEEN ADD_DAYS(NOW (), -30) AND NOW()
	;
	
	/*********************************************************
	* ATUALIZA DADOS DE PAYMENT RATEADOS NA LINHA DO PEDIDO
	* *******************************************************/
	UPDATE PM SET
		   PM.PAYMENT_NAME = PR.PAYMENT_NAME
		 , PM.PAYMENT_INSTALLMENTS = PR.PAYMENT_INSTALLMENTS
		 , PM.PAYMENT_VALUE = PR.PAYMENT_VALUE
	FROM OW_LAO.TF_D2C_NERP_SALES PM
		INNER JOIN OW_LAO.TMP_PAYMENT_VTEX_NERP_SALES_TMP PR 
			ON PM.ORDER_ID = PR.ORDER_ID
				AND PM.ITEM_INDEX = PR.ITEM_INDEX
				AND IFNULL(PM.ITEM_INDEX_KIT,9999) = IFNULL(PR.ITEM_INDEX_KIT,9999)
	;
	
	/*********************************************************
	* ATUALIZA STATUS CASO TENHA MUDADO
	* *******************************************************/		
	UPDATE FT SET FT.STATUS_PO = BSO.STATUS
	FROM OW_LAO.TF_D2C_NERP_SALES FT
		INNER JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER BSO ON FT.ORDER_ID = BSO.ORDER_ID
	WHERE FT.STATUS_PO <> BSO.STATUS;
	/*********************************************************
	* ATUALIZA SEQUENCE 
	* *******************************************************/		
	UPDATE FT SET FT."SEQUENCE" = BSO."SEQUENCE"
	FROM OW_LAO.TF_D2C_NERP_SALES FT
		INNER JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER BSO ON FT.ORDER_ID = BSO.ORDER_ID
	WHERE FT.SEQUENCE IS NULL
		  AND BSO.SEQUENCE IS NOT NULL;
	/*********************************************************
	* ATUALIZA COUPON_HEAD 
	* *******************************************************/		
	UPDATE FT SET COUPON_HEAD = UPPER(SUBSTR_REGEXPR( '([-])([^-]*)(?=-)' IN CONCAT(CONCAT('-', FT.COUPON),'-') OCCURRENCE 1 GROUP 2)) --AS COUPON 
	FROM OW_LAO.TF_D2C_NERP_SALES FT
	WHERE COUPON IS NOT NULL
		  AND FT.COUPON_HEAD IS NULL;
	
	/*********************************************************
	* ATUALIZA HIERARQUIA NOVA
	* *******************************************************/		
	UPDATE FT SET
		  CHANNEL_NEW_DIM = CN.CHANNEL 
		, SUB_CHANNEL_NEW_DIM = CN.SUB_CHANNEL 
		, PARTNER_LEVEL_NEW_DIM = CN.PARTNER_LEVEL 
		, GLOBAL_NEW_DIM = CN.GLOBAL_CHANNEL 
	FROM OW_LAO.TF_D2C_NERP_SALES FT
		LEFT JOIN OW_MD.SALES_CHANNEL CN ON
			(CASE WHEN FT.STORE_ID IS NOT NULL THEN 'Y' ELSE 'N' END) = CN.HAS_STORE_ID
			AND IFNULL(FT.SALES_CHANNEL,'') = IFNULL(CN.SALES_CHANNEL,'')
			AND IFNULL(FT.AFFILIATE_ID,'') = IFNULL(CN.AFFILIATE_ID,'')
			AND FT.SUBSIDIARY = CN.SALES_ORG 
			AND FT.SUBSIDIARY = 'SEDA'
	WHERE FT.CHANNEL_NEW_DIM IS NULL
		AND "SOURCE" = 'PO'
		AND FT.SUBSIDIARY = 'SEDA'
	;
	/*********************************************************
	* ATUALIZA TF_D2C_NERP_SALES COM FLAGS :
	* 		 IS_TRADE_IN, IS_GTI E IS_ECO_TROCA
	* *******************************************************/	
	UPDATE NS SET 
		   IS_TRADE_IN = TI.IS_TRADE_IN
		 , IS_GTI = TI.IS_GTI
		 , IS_ECO_TROCA = TI.IS_ECO_TROCA
	FROM OW_LAO.TF_D2C_NERP_SALES NS
		INNER JOIN (
			SELECT 
				  FT.ORDER_ID
				, CASE WHEN UPPER(MAX(IS_TRADE_IN)) = 'TRUE' THEN TRUE ELSE FALSE END AS IS_TRADE_IN
				, CASE WHEN MAX(CAST(IS_GTI AS INTEGER)) = 1 THEN TRUE ELSE FALSE END AS IS_GTI
				, CASE WHEN MAX(CAST(IS_ECO_TROCA AS INTEGER)) = 1 THEN TRUE ELSE FALSE END AS IS_ECO_TROCA
			FROM OW_LAO.TF_D2C_PO_VTEX_TRADE_IN FT
			GROUP BY
				  FT.ORDER_ID
		) TI ON NS.ORDER_ID = TI.ORDER_ID 
	WHERE NS."SOURCE" = 'PO'
		AND NS.SUBSIDIARY = 'SEDA'
		AND (
			   IFNULL(NS.IS_TRADE_IN,FALSE) <> TI.IS_TRADE_IN
			OR IFNULL(NS.IS_GTI,FALSE) <> TI.IS_GTI
			OR IFNULL(NS.IS_ECO_TROCA,FALSE) <> TI.IS_ECO_TROCA
		);
	
	UPDATE NS SET IS_TRADE_IN = FALSE
	FROM OW_LAO.TF_D2C_NERP_SALES NS
	WHERE NS."SOURCE" = 'PO' AND NS.SUBSIDIARY = 'SEDA' AND NS.IS_TRADE_IN IS NULL;
	
	UPDATE NS SET IS_GTI = FALSE
	FROM OW_LAO.TF_D2C_NERP_SALES NS
	WHERE NS."SOURCE" = 'PO' AND NS.SUBSIDIARY = 'SEDA' AND NS.IS_GTI IS NULL ;
	
	UPDATE NS SET IS_ECO_TROCA = FALSE
	FROM OW_LAO.TF_D2C_NERP_SALES NS
	WHERE NS."SOURCE" = 'PO' AND NS.SUBSIDIARY = 'SEDA' AND NS.IS_ECO_TROCA IS NULL ;
	/******************************
	-- CORRIGE PRODUTOS SEM REFERENCE_CODE NA VTEX
	******************************/
	UPDATE OW_LAO.TF_D2C_NERP_SALES SET 
		 REFERENCE_CODE = 
		 	CASE
			 	WHEN UPPER(ITEM_NAME) LIKE '%SAMSUNG CARE+  (BALLOON) COBERTURA: TELA PROTEGIDA [FFP]%'	THEN 'BRASIL-SP-1EV-FP-FLAGSHIP-BLP'
			 	WHEN UPPER(ITEM_NAME) LIKE '%SAMSUNG CARE+ (BALLOON) COBERTURA: TELA PROTEGIDA [FFP]%'	THEN 'BRASIL-SP-1EV-FP-FLAGSHIP-BLP'			
				WHEN UPPER(ITEM_NAME) LIKE '%SAMSUNG CARE+ COMBO PROTEÇÃO COMPLETA%' THEN 'BRASIL-COMBO-1EV-FLAGSHIP'
				WHEN UPPER(ITEM_NAME) LIKE '%SAMSUNG CARE+ GARANTIA ESTENDIDA%' THEN 'BRASIL-EW-FLAGSHIP'
				WHEN UPPER(ITEM_NAME) LIKE '%SAMSUNG CARE+ TELA PROTEGID%' THEN 'BRASIL-SP-2EV-FLAGSHIP'
			END
		 ,SKU =
		 	CASE
			 	WHEN UPPER(ITEM_NAME) LIKE '%SAMSUNG CARE+  (BALLOON) COBERTURA: TELA PROTEGIDA [FFP]%'	THEN 'BRASIL-SP-1EV-FP-FLAGSHIP-BLP'
			 	WHEN UPPER(ITEM_NAME) LIKE '%SAMSUNG CARE+ (BALLOON) COBERTURA: TELA PROTEGIDA [FFP]%'	THEN 'BRASIL-SP-1EV-FP-FLAGSHIP-BLP'			
				WHEN UPPER(ITEM_NAME) LIKE '%SAMSUNG CARE+ COMBO PROTEÇÃO COMPLETA%' THEN 'BRASIL-COMBO-1EV-FLAGSHIP'
				WHEN UPPER(ITEM_NAME) LIKE '%SAMSUNG CARE+ GARANTIA ESTENDIDA%' THEN 'BRASIL-EW-FLAGSHIP'
				WHEN UPPER(ITEM_NAME) LIKE '%SAMSUNG CARE+ TELA PROTEGID%' THEN 'BRASIL-SP-2EV-FLAGSHIP'
			END
	WHERE REFERENCE_CODE IS NULL
		AND SOURCE = 'PO'
		AND SUBSIDIARY = 'SEDA'
	;
	
	/******************************
	-- ATUALIZA KPI_LAST_UPDATE
	******************************/
	UPDATE OW_LAO.TF_D2C_NERP_SALES SET 
			KPI_LAST_UPDATE = (
								SELECT MAX(PO_CREATION_DATE)
								FROM OW_LAO.TF_D2C_NERP_SALES
								WHERE "SOURCE" = 'PO'
									AND SUBSIDIARY = 'SEDA'
									AND ORDER_ID IN ( SELECT ORDER_ID FROM OW_LAO.TMP_PO_ORDER_ID_PO_VTEX_TMP)
							  )
	FROM OW_LAO.TF_D2C_NERP_SALES 
	WHERE SOURCE = 'PO'
		AND SUBSIDIARY = 'SEDA'
		AND ORDER_ID IN ( SELECT ORDER_ID FROM OW_LAO.TMP_PO_ORDER_ID_PO_VTEX_TMP)
	;
	
	/******************************
	-- APAGA TABELAS TEMPORÁRIAS
	******************************/
	DROP TABLE OW_LAO.TMP_PARAMETER_PO_VTEX_TMP;
	DROP TABLE OW_LAO.TMP_PAYMENT_VTEX_NERP_SALES_TMP;
	DROP TABLE OW_LAO.TMP_PROMOTION_VTEX_NERP_SALES_TMP;
	DROP TABLE OW_LAO.TMP_PO_ORDER_ID_PO_VTEX_TMP;
	DROP TABLE OW_LAO.TMP_ITEM_COMPONENTS_PO_VTEX_TMP;
	DROP TABLE OW_LAO.TMP_ORDER_ITEM_TO_COMPONENTS_PO_VTEX_TMP;
	DROP TABLE OW_LAO.TMP_SHIPPING_VTEX_TMP;
END
