/***********************************************************************************************
CREATED BY : Luciano Mariani
CREATION DATE : 2024-09-19
CALL OW_LAO.PROC_D2C_MELI_COLETAS
***********************************************************************************************/
CREATE PROCEDURE OW_LAO.PROC_D2C_MELI_COLETAS (
	  p_DATE_INI DATE DEFAULT NULL 
	, P_DATE_FIM DATE DEFAULT NULL 
) LANGUAGE SQLSCRIPT
AS
BEGIN
	
	DECLARE v_JSON_PACKAGE_ATTACHMENT CLOB;
	
	-- OBS PRECISA CRIAR A TABELA OW_LAO.TMP_D2C_MELI_COLETAS PARA PODER CRIAR A PROC
	DECLARE CURSOR c_select FOR
		SELECT
			'{"ORDER_ID": "' || VT.ORDER_ID || '", "SEQUENCE":"' || VT.SEQUENCE || '", "JSON": ' || BS.PACKAGE_ATTACHMENT || '}' AS JSON_PACKAGE_ATTACHMENT
		FROM OW_LAO.TMP_D2C_MELI_COLETAS VT
			LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER BS ON VT.ORDER_ID = BS.ORDER_ID
		WHERE 1=1
			AND BS.PACKAGE_ATTACHMENT IS NOT NULL
	;
	
	/*********************************************************
	* CRIA A TMP_PARAMETER_MELI_COLETAS
	********************************************************/
	IF EXISTS ( SELECT '' FROM SYS.TABLES WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TMP_PARAMETER_MELI_COLETAS' ) THEN
		DROP TABLE OW_LAO.TMP_PARAMETER_MELI_COLETAS;
	END IF ;
	CREATE COLUMN TABLE OW_LAO.TMP_PARAMETER_MELI_COLETAS AS (
		SELECT ADD_DAYS(CURRENT_TIMESTAMP, -7) AS DATE_INI, ADD_DAYS(CURRENT_TIMESTAMP, 2) AS DATE_FIM FROM DUMMY
	);
	UPDATE OW_LAO.TMP_PARAMETER_MELI_COLETAS SET
		  DATE_INI = IFNULL( p_DATE_INI, ADD_DAYS(CURRENT_TIMESTAMP, -7) ) -- 30 dias dafault
		, DATE_FIM = IFNULL( P_DATE_FIM, ADD_DAYS(CURRENT_TIMESTAMP, 2) ) 
	;
	
	IF EXISTS ( SELECT '' FROM SYS.TABLES WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TMP_D2C_MELI_COLETAS' ) THEN
		DROP TABLE OW_LAO.TMP_D2C_MELI_COLETAS; 
	END IF ;
	CREATE TABLE OW_LAO.TMP_D2C_MELI_COLETAS AS ( -- SELECT * FROM  OW_LAO.TMP_D2C_MELI_COLETAS
		SELECT
			  VT.PO_CREATION_DATE -- Data do Pedido	PO_CREATION_DATE	VTEX (Dw Detalhado: OW_LAO.TF_D2C_NERP_SALES)		NA
			, VT.ORDER_ID --Número do Pedido	ORDER_ID	VTEX (Dw Detalhado: OW_LAO.TF_D2C_NERP_SALES)		NA
			, VT.SEQUENCE --Sequence Pedido	SEQUENCE	VTEX (Dw Detalhado: OW_LAO.TF_D2C_NERP_SALES)		NA
			, VT.AFFILIATE_PARTNER_LEVEL
			, VT.REFERENCE_CODE_KIT --Item Pedido (KIT)	REFERENCE_CODE_KIT	VTEX (Dw Detalhado: OW_LAO.TF_D2C_NERP_SALES)		NA
			, VT.REFERENCE_CODE --Item Pedido (SKU)	REFERENCE_CODE	VTEX (Dw Detalhado: OW_LAO.TF_D2C_NERP_SALES)		NA
			, VT.QTY --Quantidade Itens	QTY	VTEX (Dw Detalhado: OW_LAO.TF_D2C_NERP_SALES)		NA
			, VT.AMOUNT_LOCAL --Valor do Pedido	AMOUNT_LOCAL	VTEX (Dw Detalhado: OW_LAO.TF_D2C_NERP_SALES)		NA
			, VT.STATUS_PO --Status faturamento em Vtex	STATUS_PO	VTEX (Dw Detalhado: OW_LAO.TF_D2C_NERP_SALES)		NA
			, VT.SELECTED_SLA  --Meio de Entrega	SELECTED_SLA	VTEX (Dw Detalhado: OW_LAO.TF_D2C_NERP_SALES)		NA
			, VT.WAREHOUSE_ID_GROUP --Warehouse ID Group	WAREHOUSE_ID_GROUP	VTEX (Dw Detalhado: OW_LAO.TF_D2C_NERP_SALES)		NA
			
			, RDD.MKT_CREATION_DATE --MKT_CREATION_DATE	MKT_CREATION_DATE	VTEX (Dw MKT RDD: OW_LAO.TF_D2C_PO_VTEX_RDD)		Chave pelo campo pedido: ORDER_ID
			, RDD.MKT_LEAD_TIME --MKT_LEAD_TIME	MKT_LEAD_TIME	VTEX (Dw MKT RDD: OW_LAO.TF_D2C_PO_VTEX_RDD)		Chave pelo campo pedido: ORDER_ID
			, RDD.MKT_DELIVERY_DATE --MKT_DELIVERY_DATE	MKT_DELIVERY_DATE	VTEX (Dw MKT RDD: OW_LAO.TF_D2C_PO_VTEX_RDD)		Chave pelo campo pedido: ORDER_ID
			, RDD.ESTIMATEDDELIVERYDATE_REVISED --MKT_DELIVERYDATE_REVISED	ESTIMATEDDELIVERYDATE_REVISED	VTEX (Dw MKT RDD: OW_LAO.TF_D2C_PO_VTEX_RDD)		Chave pelo campo pedido: ORDER_ID
			
			--, '{"ORDER_ID": "' || VT.ORDER_ID || '", "JSON": ' || BS.PACKAGE_ATTACHMENT || '}' AS PACKAGE_ATTACHMENT
		FROM OW_LAO.TF_D2C_NERP_SALES VT
			LEFT JOIN OW_LAO.TF_D2C_PO_VTEX_RDD RDD ON VT.ORDER_ID = RDD.ORDER_ID
			--LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER BS ON VT.ORDER_ID = BS.ORDER_ID
		WHERE 1=1
			AND VT."SOURCE" = 'PO'
			AND VT.SUBSIDIARY = 'SEDA'
			AND VT.DATE_REF BETWEEN ( SELECT DATE_INI FROM OW_LAO.TMP_PARAMETER_MELI_COLETAS )
								AND ( SELECT DATE_FIM FROM OW_LAO.TMP_PARAMETER_MELI_COLETAS )		
			-- Mostrar apenas tracking de pedidos MercadoLivre
			-- Opção 1: (o que eu uso):  (todo Coletas vem com o FOB como meio de entrega) E AFFILIATE_PARTNER_LEVEL IN “Mercado Livre”				
			-- Opção 2: AFFILIATE_PARTNER_LEVEL IN “Mercado Livre” E customData > customApps  > fields > mode IN “me2”				
			AND UPPER(VT.SELECTED_SLA) LIKE '%VTEX:FOB%' 
			AND UPPER(VT.AFFILIATE_PARTNER_LEVEL) LIKE '%MERCADO LIVRE%'
			AND VT.STATUS_PO IS NOT NULL 
	);
	
	/*********************************************************
	* CRIA A TMP_JSON_PACKAGE_ATTACHMENT
	********************************************************/
	IF EXISTS ( SELECT '' FROM SYS.TABLES WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TMP_JSON_PACKAGE_ATTACHMENT' ) THEN
		DROP TABLE OW_LAO.TMP_JSON_PACKAGE_ATTACHMENT; 
	END IF ;
	CREATE COLUMN TABLE "OW_LAO"."TMP_JSON_PACKAGE_ATTACHMENT" (
		"ORDER_ID" NVARCHAR(256),
		"SEQUENCE" NVARCHAR(256),
		"INVOICENUMBER" NVARCHAR(1000),
		"INVOICEKEY" NVARCHAR(1000)
	) UNLOAD PRIORITY 5 AUTO MERGE;	
	
	/****************************************************************************************
	-- EXECUTA CURSOR
	****************************************************************************************/
	FOR cursorRow as c_select DO
		v_JSON_PACKAGE_ATTACHMENT := cursorRow.JSON_PACKAGE_ATTACHMENT;
		
		INSERT INTO OW_LAO.TMP_JSON_PACKAGE_ATTACHMENT(
			  "ORDER_ID"
			, "SEQUENCE"
			, "INVOICENUMBER"
			, "INVOICEKEY"		
		)
		SELECT 
			  "ORDER_ID"
			, "SEQUENCE"
			, "INVOICENUMBER"
			, "INVOICEKEY"
		FROM JSON_TABLE( :v_JSON_PACKAGE_ATTACHMENT,'$'
			COLUMNS (
		        "ORDER_ID" NVARCHAR(256) PATH '$.ORDER_ID',
		        "SEQUENCE" NVARCHAR(256) PATH '$.SEQUENCE',
		        NESTED PATH '$.JSON[*]' 
		        COLUMNS ( 
					"INVOICENUMBER" NVARCHAR(1000) PATH '$.invoiceNumber',
					"INVOICEKEY" NVARCHAR(1000) PATH '$.invoiceKey'
			 	)
			)
		 );
		
	END FOR;
	
	
	-- apaga orders que estiverem na tmp
	DELETE FROM OW_LAO.TF_D2C_MELI_COLETAS
	WHERE ORDER_ID IN (
		SELECT DISTINCT ORDER_ID
		FROM OW_LAO.TMP_D2C_MELI_COLETAS
	);
	
	--IF EXISTS ( SELECT '' FROM SYS.TABLES WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TMP_D2C_MELI_COLETAS' ) THEN
	--	DROP TABLE OW_LAO.TF_D2C_MELI_COLETAS; 
	--END IF ;
	--CREATE TABLE OW_LAO.TF_D2C_MELI_COLETAS AS (
	INSERT INTO OW_LAO.TF_D2C_MELI_COLETAS
	SELECT
		  JP.PO_CREATION_DATE -- Data do Pedido	PO_CREATION_DATE	VTEX (Dw Detalhado: OW_LAO.TF_D2C_NERP_SALES)		NA
		, JP.ORDER_ID --Número do Pedido	ORDER_ID	VTEX (Dw Detalhado: OW_LAO.TF_D2C_NERP_SALES)		NA
		, JP.SEQUENCE --Sequence Pedido	SEQUENCE	VTEX (Dw Detalhado: OW_LAO.TF_D2C_NERP_SALES)		NA
		, JP.AFFILIATE_PARTNER_LEVEL
		, JP.REFERENCE_CODE_KIT --Item Pedido (KIT)	REFERENCE_CODE_KIT	VTEX (Dw Detalhado: OW_LAO.TF_D2C_NERP_SALES)		NA
		, JP.REFERENCE_CODE --Item Pedido (SKU)	REFERENCE_CODE	VTEX (Dw Detalhado: OW_LAO.TF_D2C_NERP_SALES)		NA
		, JP.QTY --Quantidade Itens	QTY	VTEX (Dw Detalhado: OW_LAO.TF_D2C_NERP_SALES)		NA
		, JP.AMOUNT_LOCAL --Valor do Pedido	AMOUNT_LOCAL	VTEX (Dw Detalhado: OW_LAO.TF_D2C_NERP_SALES)		NA
		, JP.STATUS_PO --Status faturamento em Vtex	STATUS_PO	VTEX (Dw Detalhado: OW_LAO.TF_D2C_NERP_SALES)		NA
		, JP.SELECTED_SLA  --Meio de Entrega	SELECTED_SLA	VTEX (Dw Detalhado: OW_LAO.TF_D2C_NERP_SALES)		NA
		, JP.WAREHOUSE_ID_GROUP --Warehouse ID Group	WAREHOUSE_ID_GROUP	VTEX (Dw Detalhado: OW_LAO.TF_D2C_NERP_SALES)		NA
		, JP.MKT_CREATION_DATE --MKT_CREATION_DATE	MKT_CREATION_DATE	VTEX (Dw MKT RDD: OW_LAO.TF_D2C_PO_VTEX_RDD)		Chave pelo campo pedido: ORDER_ID
		, JP.MKT_LEAD_TIME --MKT_LEAD_TIME	MKT_LEAD_TIME	VTEX (Dw MKT RDD: OW_LAO.TF_D2C_PO_VTEX_RDD)		Chave pelo campo pedido: ORDER_ID
		, JP.MKT_DELIVERY_DATE --MKT_DELIVERY_DATE	MKT_DELIVERY_DATE	VTEX (Dw MKT RDD: OW_LAO.TF_D2C_PO_VTEX_RDD)		Chave pelo campo pedido: ORDER_ID
		, JP.ESTIMATEDDELIVERYDATE_REVISED --MKT_DELIVERYDATE_REVISED	ESTIMATEDDELIVERYDATE_REVISED	VTEX (Dw MKT RDD: OW_LAO.TF_D2C_PO_VTEX_RDD)		Chave pelo campo pedido: ORDER_ID
		, SO.SALES_DOCUMENT
		, SO.SO_LOCAL_CREATE_ON_D
		, SO.DELIVERY
		, SO.DO_LOCAL_CREATE_ON_D
		, SO."1ST_GI_NO"
		, SO."1ST_GI_LOCAL_CREATE"
		, SO."2ND_GI_NO"
		, SO."2ND_GI_CREATE_ON"
		, SO.BILLING_DOC
		, SO.BILLING_CREATE_ON
		-- Esses do Sales Order Tracking--
		, SO.SPEC_PROCESSING
		, SO.REJECT_REASON_1	
		
		, NF.EPOD_DATE
		, NF.NOTA_INTERNAL_NO
		, NF.NOTA_POSTING_DATE
		
		, CL.RDO_NUMBER
		, CL.RDO_ORDER_TYPE
		, CL.GR_DATE
		, CL.RDO_RETURN_IOD_DATE
		
		-- Esses do Cello--
		, CL.LAST_OCCURRENCE
		, CL.RETURN_REASON_DESC
	FROM OW_LAO.TMP_D2C_MELI_COLETAS JP
		
		LEFT JOIN (
				SELECT 
					  SO.CUSTOMER_PO
					, SO.MATERIAL
					, SO.ORDER_QTY_BASE 
					, SO.SALES_DOCUMENT
					, SO.SO_LOCAL_CREATE_ON_D
					, SO.DELIVERY
					, SO.DO_LOCAL_CREATE_ON_D
					, SO."1ST_GI_NO"
					, SO."1ST_GI_LOCAL_CREATE"
					, SO."2ND_GI_NO"
					, SO."2ND_GI_CREATE_ON"
					, SO.BILLING_DOC
					, SO.BILLING_CREATE_ON
					-- Esses do Sales Order Tracking--
					, SO.SPEC_PROCESSING
					, SO.REJECT_REASON_1	
				FROM OW_LAO.TMP_D2C_MELI_COLETAS JP
					INNER JOIN OW_LAO.ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING SO
						ON JP."SEQUENCE" = SO.CUSTOMER_PO 
							AND JP.REFERENCE_CODE = SO.MATERIAL
							AND SO.ORDER_QTY_BASE > 0 -- SALES ORDER TRACKING 
			) SO ON JP."SEQUENCE" = SO.CUSTOMER_PO 
				    AND JP.REFERENCE_CODE = SO.MATERIAL
		
		LEFT JOIN ( -- cello
			SELECT JP.ORDER_ID
				, JP."SEQUENCE"
				, OT.MATERIAL
				, OT.DELIVERY_NO
				, OT.DELIVERY_ITEM
				, RT.RDO_NUMBER
				, RT.RDO_ORDER_TYPE
				, RT.GR_DATE
				, RT.RDO_RETURN_IOD_DATE
				-- Esses do Cello--
				, RT.LAST_OCCURRENCE
				, RT.RETURN_REASON_DESC
			FROM OW_LAO.ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING SO
								
				INNER JOIN (SELECT DISTINCT ORDER_ID, "SEQUENCE" FROM  OW_LAO.TMP_JSON_PACKAGE_ATTACHMENT ) JP
							ON JP."SEQUENCE" = SO.CUSTOMER_PO 
								AND SO.ORDER_QTY_BASE > 0 -- SALES ORDER TRACKING 
								
				INNER JOIN OW_LAO.ODS_NERP_ZLLEJ50090_OUTBOUND_TRACKING OT
							ON OT.REFERENCE_DOC_SO_PO = SO.SALES_DOCUMENT 
								AND OT.MATERIAL = SO.MATERIAL 
								AND OT.DELIVERY_NO = SO.DELIVERY
								AND OT.DELIVERY_ITEM = SO.DELIVERY_ITEM
								AND OT.DO_TYPE = 'ZND1' --para a outbound
								
				
				INNER JOIN OW_SEDA_S.VW_CELLO_RETURN_TRACKING RT
					ON RT.ORIG_DO_NO = OT.DELIVERY_NO
						AND RT.MATERIAL_CODE = OT.MATERIAL
						AND RT.RDO_DELIVERY_TYPE <> 'DUMMY' --para o CELLO
		) CL ON JP.ORDER_ID = CL.ORDER_ID
			AND JP.REFERENCE_CODE = CL.MATERIAL
		
		LEFT JOIN ( -- OUTBOUND NF
			SELECT JP.ORDER_ID
				, JP."SEQUENCE"
				, OT.NFE_NUM_BILLTO
				, OT.MATERIAL
				, OT.DELIVERY_NO
				, OT.DELIVERY_ITEM
				, OT.EPOD_DATE
				, OT.NOTA_INTERNAL_NO
				, OT.NOTA_POSTING_DATE
			FROM OW_LAO.ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING SO
	
				INNER JOIN OW_LAO.ODS_NERP_ZLLEJ50090_OUTBOUND_TRACKING OT
							ON OT.REFERENCE_DOC_SO_PO = SO.SALES_DOCUMENT 
								AND OT.MATERIAL = SO.MATERIAL 
								AND OT.DELIVERY_NO = SO.DELIVERY
								AND OT.DELIVERY_ITEM = SO.DELIVERY_ITEM
								AND OT.DO_TYPE = 'ZND1' --para a outbound 
								AND SO.ORDER_QTY_BASE > 0 -- SALES ORDER TRACKING 
								
				INNER JOIN (SELECT DISTINCT ORDER_ID, "SEQUENCE", INVOICENUMBER FROM  OW_LAO.TMP_JSON_PACKAGE_ATTACHMENT ) JP
							ON JP."SEQUENCE" = SO.CUSTOMER_PO 
								AND JP.INVOICENUMBER = OT.NFE_NUM_BILLTO	
		) NF
			ON JP.ORDER_ID = NF.ORDER_ID
			AND JP.REFERENCE_CODE = NF.MATERIAL
			-- AND JP.INVOICENUMBER = NF.NFE_NUM_BILLTO
	--)
	;
	
	DELETE FROM OW_LAO.TMP_D2C_MELI_COLETAS;
	DROP TABLE OW_LAO.TMP_JSON_PACKAGE_ATTACHMENT; 
	DROP TABLE OW_LAO.TMP_PARAMETER_MELI_COLETAS;
	
END