/***********************************************************************************************
CREATED BY : Luciano Mariani
CREATION DATE : 2023-06-29
ALTER BY : Luciano Mariani
ALTER DATE : 2024-10-18 
CALL OW_LAO.PROC_D2C_FORECAST_OST 
SELECT * FROM OW_LAO.FT_D2C_FORECAST_OST
***********************************************************************************************/
CREATE PROCEDURE OW_LAO.PROC_D2C_FORECAST_OST 
LANGUAGE SQLSCRIPT
AS
BEGIN
	/********************************
	
	Criteria FBL5N
	Document Type = DK  ( FBL5N.DOCUMENT_TYPE = 'DK' )
	Posting Key = 19 ( FBL5N.POSTING_KEY = 19)
	Key - Único = 'Customer' & 'Document Date' & 'Document Number' & 'Amount in Local Currency' & 'Line item'
	
	Calculated field = Média últimos três meses
		1. Campo: Amount in Local currency LOCAL_CURRENCY
		2. Aberto a nível Canal
		3. Aberto nível mensal
		
	********************************/
	DECLARE counter INT DEFAULT 1;
	/*******************************
	 CORRIGE FBL5N
	*******************************/
	IF EXISTS( SELECT TABLE_NAME FROM SYS.TABLES WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TMP_FBL5N_FORECAST') THEN
		DROP TABLE OW_LAO.TMP_FBL5N_FORECAST;
	END IF;
	CREATE COLUMN TABLE OW_LAO.TMP_FBL5N_FORECAST AS (
		SELECT
			  CUSTOMER
			, DOCUMENT_DATE
			, DOCUMENT_NUMBER
			, LINE_ITEM
			, LOAD_DATE
			, CUSTOMER_NAME_SUMMARY AS CHANNEL
			, CUSTOMER_NAME_DETAIL AS SUBCHANNEL
			--, LOCAL_CURRENCY
			, ( CAST(AMOUNT_IN_LOCAL_CURRENCY AS DECIMAL(18,2) ) * -1 ) AS AMOUNT
		FROM (
			SELECT -- ROWCOUNT DA CHAVE
				  ROW_NUMBER() OVER (PARTITION BY FB.CUSTOMER, FB.DOCUMENT_DATE, FB.DOCUMENT_NUMBER, FB.LINE_ITEM ORDER BY FB.CUSTOMER, FB.DOCUMENT_DATE, FB.DOCUMENT_NUMBER, FB.LINE_ITEM ) AS ROW_COUNT
				, FB.CUSTOMER
				, FB.DOCUMENT_DATE
				, FB.DOCUMENT_NUMBER
				, FB.LINE_ITEM
				, FB.LOAD_DATE
				, MAC.CUSTOMER_NAME_SUMMARY --AS AFFILIATE_CHANNEL
				, MAC.CUSTOMER_NAME_DETAIL --AS AFFILIATE_SUB_CHANNEL
				, FB.LOCAL_CURRENCY
				, FB.AMOUNT_IN_LOCAL_CURRENCY
			FROM OW_SEDA_S.ODS_NERP_FBL5N_CUSTOMER_LINE_ITEM_DISPLAY_OPEN_ITEMS_HIST FB
				INNER JOIN (
					 -- pega o ultimo load date da chave ()
					SELECT CUSTOMER
						, DOCUMENT_DATE
						, DOCUMENT_NUMBER
						, LINE_ITEM
						, MAX(LOAD_DATE) AS LOAD_DATE
					FROM  OW_SEDA_S.ODS_NERP_FBL5N_CUSTOMER_LINE_ITEM_DISPLAY_OPEN_ITEMS_HIST
					WHERE 1=1
						AND DOCUMENT_TYPE = 'DK'
						AND POSTING_KEY = 19
					GROUP BY CUSTOMER
						, DOCUMENT_DATE
						, DOCUMENT_NUMBER
						, LINE_ITEM
				) FL ON
					FB.CUSTOMER = FL.CUSTOMER
					AND FB.DOCUMENT_DATE = FL.DOCUMENT_DATE
					AND FB.DOCUMENT_NUMBER = FL.DOCUMENT_NUMBER
					AND FB.LINE_ITEM = FL.LINE_ITEM
					AND FB.LOAD_DATE = FL.LOAD_DATE
				LEFT JOIN OW_MD.MAP_AR_MONTH_CUSTOMER MAC ON FB.CUSTOMER = MAC.CUSTOMER_CODE
		) FBL
		WHERE FBL.ROW_COUNT = 1
	);
	
	/*********************************************
	Cria temporária e calcula 3 ultimos meses 
	*********************************************/	
	IF EXISTS( SELECT TABLE_NAME FROM SYS.TABLES WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TMP_OST_FORECAST') THEN
		DROP TABLE OW_LAO.TMP_OST_FORECAST;
	END IF;
	CREATE COLUMN TABLE OW_LAO.TMP_OST_FORECAST AS (	
		SELECT
		      YEAR_MONTH
		    , CHANNEL
		    , SUBCHANNEL
		    , SUM(AMOUNT) AS AMOUNT
		    --, AVG(SUM(AMOUNT)) OVER (PARTITION BY SUBCHANNEL ORDER BY YEAR_MONTH ROWS BETWEEN 3 PRECEDING AND 1 PRECEDING) AS AVG_LAST_3_MONTHS
		    , AVG(SUM(AMOUNT)) OVER (PARTITION BY SUBCHANNEL ORDER BY YEAR_MONTH ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS AVG_LAST_3_MONTHS_ACTUAL
		    , 0 AS IS_FORECAST
		FROM (
			SELECT 
			      TO_CHAR(DOCUMENT_DATE, 'YYYY-MM') AS YEAR_MONTH
			    , CHANNEL
			    , SUBCHANNEL
			    , SUM(AMOUNT) AS AMOUNT
			FROM OW_LAO.TMP_FBL5N_FORECAST
			WHERE YEAR(DOCUMENT_DATE) >= 2024
				--AND SUBCHANNEL like '%AMER%'
			GROUP BY 
			      TO_CHAR(DOCUMENT_DATE, 'YYYY-MM') 
			    , CHANNEL
			    , SUBCHANNEL
			    
			 UNION ALL 
			 SELECT 
			      TO_CHAR(DOCUMENT_DATE, 'YYYY-MM') AS YEAR_MONTH
			    , CHANNEL
			    , SUBCHANNEL
			    , SUM(AMOUNT * -1) AS AMOUNT
			FROM OW_LAO.RAW_REPASSES_D2C_2022_2024
			WHERE YEAR(DOCUMENT_DATE) < 2024
				--AND SUBCHANNEL like '%AMER%'
			GROUP BY 
			      TO_CHAR(DOCUMENT_DATE, 'YYYY-MM') 
			    , CHANNEL
			    , SUBCHANNEL
		) B
		GROUP BY
		      YEAR_MONTH
		    , CHANNEL
		    , SUBCHANNEL
		ORDER BY 3,1
	);
	/*******************************************
	LOOP FORECAST PARA OS PRÓXIMOS 3 MESES  
	*******************************************/
	WHILE counter <= 3 DO
	    -- Bloco de código que será executado 3 vezes
	
		/*******************************************
		INSERE 1 MES DE FORECAST  
		*******************************************/
		INSERT INTO  OW_LAO.TMP_OST_FORECAST (
			  YEAR_MONTH
			, CHANNEL
			, SUBCHANNEL
			, AMOUNT
			--, AVG_LAST_3_MONTHS_ACTUAL
			, IS_FORECAST
		)  
		SELECT 
			  TO_CHAR( ADD_MONTHS(F.YEAR_MONTH || '-01', 1) , 'YYYY-MM') AS YEAR_MONTH_
		    --, F.YEAR_MONTH
		    , F.CHANNEL
		    , F.SUBCHANNEL
		    , F.AVG_LAST_3_MONTHS_ACTUAL AS AMOUNT
		    , 1 AS IS_FORECAST
		FROM OW_LAO.TMP_OST_FORECAST F
			INNER JOIN ( -- ULTIMO MES DE CADA CANAL
				 SELECT CHANNEL
				    , SUBCHANNEL
				    , MAX(YEAR_MONTH) AS YEAR_MONTH
				FROM OW_LAO.TMP_OST_FORECAST
				GROUP BY CHANNEL
				    , SUBCHANNEL
			) L ON F.YEAR_MONTH = L.YEAR_MONTH
		    	   AND F.CHANNEL = L.CHANNEL
		    	   AND F.SUBCHANNEL = L.SUBCHANNEL
		;
	
		/*******************************************
		ATUALIZA AVG_LAST_3_MONTHS_ACTUAL
		*******************************************/
		UPDATE F SET
			F.AVG_LAST_3_MONTHS_ACTUAL = L.AVG_LAST_3_MONTHS_ACTUAL
		FROM OW_LAO.TMP_OST_FORECAST F
			INNER JOIN ( 
				SELECT
				      YEAR_MONTH
				    , CHANNEL
				    , SUBCHANNEL
				    --, CASE WHEN IS_FORECAST =  0 THEN AMOUNT END AS AMOUNT
				    --, AVG_LAST_3_MONTHS_ACTUAL
				    , AVG(SUM(AMOUNT)) OVER (PARTITION BY SUBCHANNEL ORDER BY YEAR_MONTH ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS AVG_LAST_3_MONTHS_ACTUAL
				    --, AVG(SUM(AMOUNT)) OVER (PARTITION BY SUBCHANNEL ORDER BY YEAR_MONTH ROWS BETWEEN 3 PRECEDING AND 1 PRECEDING) AS AVG_LAST_3_MONTHS
				FROM OW_LAO.TMP_OST_FORECAST
				GROUP BY
				      YEAR_MONTH
				    , CHANNEL
				    , SUBCHANNEL
				    , CASE WHEN IS_FORECAST =  0 THEN AMOUNT END
				    , AVG_LAST_3_MONTHS_ACTUAL
				ORDER BY 3,1
			) L ON F.YEAR_MONTH = L.YEAR_MONTH
		    	   AND F.CHANNEL = L.CHANNEL
		    	   AND F.SUBCHANNEL = L.SUBCHANNEL
	  	;
	 
	    -- Incrementa o contador
	    counter := counter + 1;
	END WHILE;
	/*******************************
	 CRIA FT
	*******************************/
	IF EXISTS( SELECT TABLE_NAME FROM SYS.TABLES WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'FT_D2C_FORECAST_OST') THEN
		DROP TABLE OW_LAO.FT_D2C_FORECAST_OST;
	END IF;
	CREATE TABLE OW_LAO.FT_D2C_FORECAST_OST AS (
		SELECT YEAR_MONTH
		    , CHANNEL
		    , SUBCHANNEL
		    , CASE WHEN IS_FORECAST = 0 THEN AMOUNT END AS AMOUNT
		    -- , AVG_LAST_3_MONTHS_ACTUAL
		    -- , AVG(SUM(AMOUNT)) OVER (PARTITION BY SUBCHANNEL ORDER BY YEAR_MONTH ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS AVG_LAST_3_MONTHS_ACTUAL
		    , AVG(SUM(AMOUNT)) OVER (PARTITION BY SUBCHANNEL ORDER BY YEAR_MONTH ROWS BETWEEN 3 PRECEDING AND 1 PRECEDING) AS FORECAST_AMOUNT
		    , IS_FORECAST 
		FROM OW_LAO.TMP_OST_FORECAST F
		GROUP BY
		      YEAR_MONTH
		    , CHANNEL
		    , SUBCHANNEL
		    , CASE WHEN IS_FORECAST = 0 THEN AMOUNT END
		    , IS_FORECAST
		ORDER BY 3,1
	);
	/*******************************
	 APAGA TEMPORÁRIAS
	*******************************/
	DROP TABLE OW_LAO.TMP_FBL5N_FORECAST;
	DROP TABLE OW_LAO.TMP_OST_FORECAST;
	
END
