/***********************************************************************************************
ALTER BY : LUCIANO MARIANI
CREATION DATE : 2023-11-14
-- CALL OW_LAO.PROC_D2C_NERP_GROSS_MARGIN -- ( ADD_DAYS(CURRENT_TIMESTAMP, -1),  ADD_DAYS(CURRENT_TIMESTAMP, 2))
SELECT TOP 100 * 
FROM OW_LAO.TF_NERP_GROSS_MARGIN
where GROSS_PROFIT_LOCAL > 0
***********************************************************************************************/
CREATE PROCEDURE OW_LAO.PROC_D2C_NERP_GROSS_MARGIN (
	 p_DATE_INI DATE DEFAULT NULL 
	,P_DATE_FIM DATE DEFAULT NULL 
) LANGUAGE SQLSCRIPT
AS
BEGIN
	
	/*********************************************************
	* CRIA A TMP_PARAMETER_GROSS_MARGIN
	********************************************************/
	IF EXISTS ( SELECT TABLE_NAME FROM SYS.TABLES WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TMP_PARAMETER_GROSS_MARGIN' ) THEN
		DROP TABLE OW_LAO.TMP_PARAMETER_GROSS_MARGIN;
	END IF ;
	CREATE COLUMN TABLE OW_LAO.TMP_PARAMETER_GROSS_MARGIN AS (
		SELECT ADD_DAYS(CURRENT_TIMESTAMP, -90) AS DATE_INI, ADD_DAYS(CURRENT_TIMESTAMP, 10) AS DATE_FIM FROM DUMMY
	);
	UPDATE OW_LAO.TMP_PARAMETER_GROSS_MARGIN SET
		 DATE_INI = IFNULL(p_DATE_INI, ADD_DAYS(CURRENT_TIMESTAMP, -90))
		,DATE_FIM = IFNULL(P_DATE_FIM, ADD_DAYS(CURRENT_TIMESTAMP, 10)) 
	;
	
	
	-- *******************************************************/ 
	
	/*********************************************************
	* CRIA A TMP_EXCHANGE_RATE_GM
	* *******************************************************/
	IF EXISTS ( SELECT TABLE_NAME FROM SYS.TABLES WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TMP_EXCHANGE_RATE_GM' ) THEN
		DROP TABLE OW_LAO.TMP_EXCHANGE_RATE_GM;
	END IF ;
	CREATE COLUMN TABLE OW_LAO.TMP_EXCHANGE_RATE_GM AS (
		SELECT EX.*
			, AG.FROM_CURRENCY
			, AG.TO_CURRENCY
			, AG.RATE AS EXCHANGE_RATE		
		FROM (
			SELECT YEAR(TO_DATE(REPLACE(DATE_REF, '.', '-'), 'YYYY-MM-DD')) AS YEAR
				, MONTH(TO_DATE(REPLACE(DATE_REF, '.', '-'), 'YYYY-MM-DD')) AS MONTH
				, MAX(TO_DATE(REPLACE(DATE_REF, '.', '-'), 'YYYY-MM-DD')) AS DATE_REF
			FROM OW_LAO.ODS_PTAX_EXCHANGE_RATE
			WHERE EXCHANGE_RATE_TYPE = 'MHQA'
				AND FROM_CURRENCY = 'USD'
				AND TO_CURRENCY = 'BRL'
			GROUP BY
				  YEAR(TO_DATE(REPLACE(DATE_REF, '.', '-'), 'YYYY-MM-DD')) 
				, MONTH(TO_DATE(REPLACE(DATE_REF, '.', '-'), 'YYYY-MM-DD')) 
		) EX 
		INNER JOIN OW_LAO.ODS_PTAX_EXCHANGE_RATE AG
			ON EX.DATE_REF = TO_DATE(REPLACE(AG.DATE_REF, '.', '-'), 'YYYY-MM-DD')
				AND AG.EXCHANGE_RATE_TYPE = 'MHQA'
				AND AG.FROM_CURRENCY = 'USD'
				AND AG.TO_CURRENCY = 'BRL'
	);
	/*********************************************************
	* TABELA TMP_COGS_NEXT_MONTH CASO O MÊS ESTEJA SEM COGS 
	* *******************************************************/	
	IF EXISTS ( SELECT TABLE_NAME FROM SYS.TABLES WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TMP_COGS_NEXT_MONTH' ) THEN
		DROP TABLE OW_LAO.TMP_COGS_NEXT_MONTH;
	END IF ;
	CREATE COLUMN TABLE OW_LAO.TMP_COGS_NEXT_MONTH AS (
		SELECT TOP 0 REFERENCE_CODE, YYYYMM, COGS_UNIT, FILE_NAME, LAST_MODIFICATION_FILE, LOAD_DATE
		FROM OW_MD.COGS 
	);
	
	IF NOT EXISTS(
		SELECT DISTINCT YYYYMM
		FROM OW_MD.COGS 
		WHERE YYYYMM = TO_CHAR( CURRENT_DATE , 'YYYYMM')
	)
	THEN 
		INSERT INTO OW_LAO.TMP_COGS_NEXT_MONTH( REFERENCE_CODE, YYYYMM, COGS_UNIT, FILE_NAME, LAST_MODIFICATION_FILE, LOAD_DATE )
		SELECT REFERENCE_CODE, TO_CHAR( CURRENT_DATE , 'YYYYMM') AS YYYYMM, COGS_UNIT, FILE_NAME, LAST_MODIFICATION_FILE, LOAD_DATE
		FROM OW_MD.COGS 
		WHERE YYYYMM = TO_CHAR( ADD_MONTHS(CURRENT_DATE, -1) , 'YYYYMM')
		;
	END IF ;
	
	/*********************************************************
	* CRIA A TMP_GROSS_MARGIN_ZKE
	* *******************************************************/
	IF EXISTS ( SELECT TABLE_NAME FROM SYS.TABLES WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TMP_GROSS_MARGIN_ZKE' ) THEN
		DROP TABLE OW_LAO.TMP_GROSS_MARGIN_ZKE;
	END IF ;
	CREATE COLUMN TABLE OW_LAO.TMP_GROSS_MARGIN_ZKE AS (
		SELECT
			  ZK.SALES_ORDER
			, ZK.PRODUCT
			
			--, CONCAT(
			--		ZK."YEAR" , CONCAT( CASE WHEN to_int(ZK.POSTING_PERIOD) < 10 THEN '0' ELSE '' END , ZK.POSTING_PERIOD ) 
			--  ) AS YYYYMM 
			, (ZK."YEAR" * 100 + ZK.POSTING_PERIOD) AS YYYYMM_ZKE
			
			, TO_DATE(
				CONCAT(
					ZK."YEAR" , CONCAT( CASE WHEN TO_INT(ZK.POSTING_PERIOD) < 10 THEN '0' ELSE '' END , ZK.POSTING_PERIOD ) 
				) || '01'
			) AS YYYYMMDD		  
			 
			, CAST(ZK.POSTING_PERIOD AS VARCHAR(6)) AS POSTING_PERIOD
			, ZK.CUSTOMER
			, ZK.PA_COST_ELEMENT
			, UPPER(ZK.PA_CE_DESCRIPTION) AS PA_CE_DESCRIPTION
			, ZK.AMOUNT_COMPANY_CODE_CURRENCY AS AMOUNT
			, TI.TAX_INCENTIVE	
			, ZK.SALES_QTY AS QTY
		FROM
			(
				SELECT
					  SALES_ORDER
					, PRODUCT
					, MIN("YEAR") AS "YEAR" -- SOMENTE PARA CAMBIO QUANDO NÃO EXISTE BILLING_DATE
					, MIN(POSTING_PERIOD) AS POSTING_PERIOD -- SOMENTE PARA CAMBIO QUANDO NÃO EXISTE BILLING_DATE
					, CUSTOMER
					, PA_COST_ELEMENT
					, PA_CE_DESCRIPTION
					, SUM( AMOUNT_COMPANY_CODE_CURRENCY ) AS AMOUNT_COMPANY_CODE_CURRENCY
					, SUM( SALES_QTY ) AS SALES_QTY
				FROM OW_LAO.ODS_NERP_ZKE24_DISPLAY_ACTUAL_LINE_ITEMS
				WHERE PA_COST_ELEMENT <> 81103000 -- DIFERENTE DE Tax Incentive
					AND ("YEAR" * 100 + POSTING_PERIOD) BETWEEN (SELECT (YEAR(DATE_INI) * 100 + MONTH(DATE_INI)) FROM OW_LAO.TMP_PARAMETER_GROSS_MARGIN )
															AND (SELECT (YEAR(DATE_FIM) * 100 + MONTH(DATE_FIM)) FROM OW_LAO.TMP_PARAMETER_GROSS_MARGIN )
				GROUP BY
					  SALES_ORDER
					, PRODUCT
					-- , "YEAR"
					-- , POSTING_PERIOD
					, CUSTOMER
					, PA_COST_ELEMENT
					, PA_CE_DESCRIPTION
			) ZK
			LEFT JOIN (
				SELECT 
				      CUSTOMER
					, PRODUCT
					, SALES_ORDER
					-- , "YEAR"
					-- , POSTING_PERIOD
					, SUM(AMOUNT_COMPANY_CODE_CURRENCY) AS TAX_INCENTIVE
				FROM OW_LAO.ODS_NERP_ZKE24_DISPLAY_ACTUAL_LINE_ITEMS
				WHERE PA_COST_ELEMENT = 81103000 -- SOMENTE DCR Incentive
					AND ("YEAR" * 100 + POSTING_PERIOD) BETWEEN (SELECT (YEAR(DATE_INI) * 100 + MONTH(DATE_INI)) FROM OW_LAO.TMP_PARAMETER_GROSS_MARGIN )
															AND (SELECT (YEAR(DATE_FIM) * 100 + MONTH(DATE_FIM)) FROM OW_LAO.TMP_PARAMETER_GROSS_MARGIN )				
				GROUP BY
					  CUSTOMER
					, PRODUCT
					, SALES_ORDER
					-- , "YEAR"
					-- , POSTING_PERIOD
			) TI ON 1=1
					AND ZK.CUSTOMER = TI.CUSTOMER
					AND ZK.PRODUCT = TI.PRODUCT
					AND ZK.SALES_ORDER = TI.SALES_ORDER
					-- AND ZK."YEAR" = TI."YEAR"
					-- AND ZK.POSTING_PERIOD = TI.POSTING_PERIOD
			
	);
	IF EXISTS ( SELECT TABLE_NAME FROM SYS.TABLES WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TMP_GROSS_MARGIN_DCR' ) THEN
		DROP TABLE OW_LAO.TMP_GROSS_MARGIN_DCR; --  SELECT TOP 100 * FROM OW_LAO.TMP_GROSS_MARGIN_DCR
	END IF ;
	CREATE COLUMN TABLE OW_LAO.TMP_GROSS_MARGIN_DCR AS (
		SELECT
			  SALES_ORDER
			, MATERIAL_CODE
			--, SALES_ORDER_ITEM
			, SOLD_TO_PARTY AS SOLD_TO
			, SALES_DOCUMENT_TYPE
			, BILLING_DATE
			, CONCAT( 
				  SUBSTRING(CAST(BILLING_DATE AS VARCHAR(30)),1,4)
				, SUBSTRING(CAST(BILLING_DATE AS VARCHAR(30)),6,2)
			)AS YYYYMM
			
			, MAX(DESC_MAT_GROUP) AS DESC_MAT_GROUP
			
			--, MONTH(BILLING_DATE) AS "POSTING_PERIOD" 
			--, YEAR(BILLING_DATE) AS "YEAR"				
			
			, UPPER(MAX( REGION )) AS REGION
			, UPPER(MAX( CITY )) AS CITY
			, SUM(CAST( NET_AMOUNT AS DECIMAL(18,2))) AS NET_AMOUNT
			, SUM(CAST( INCENTIVE AS DECIMAL(18,2))) AS INCENTIVE
			, SUM(CAST( NF_TOTAL_AMT AS DECIMAL(18,2)) ) AS NF_TOTAL_AMT
						
			, SUM(CAST(	ICMS AS DECIMAL(18,2))) AS 	ICMS
			, SUM(CAST(	ICMS_BASE AS DECIMAL(18,2))) AS	ICMS_BASE
			, SUM(CAST(	ICMS_RATE AS DECIMAL(18,2))) AS	ICMS_RATE
			, SUM(CAST(	IPI AS DECIMAL(18,2))) AS 	IPI
			, SUM(CAST(	IPI_BASE AS DECIMAL(18,2))) AS IPI_BASE
			, SUM(CAST(	IPI_RATE AS DECIMAL(18,2))) AS IPI_RATE
			, SUM(CAST(	PIS AS DECIMAL(18,2))) AS PIS
			, SUM(CAST(	PIS_BASE AS DECIMAL(18,2))) AS PIS_BASE
			, SUM(CAST(	PIS_RATE AS DECIMAL(18,2))) AS PIS_RATE
			, SUM(CAST(	ISS AS DECIMAL(18,2))) AS ISS
			, SUM(CAST(	ISS_BASE AS DECIMAL(18,2))) AS ISS_BASE
			, SUM(CAST(	ISS_RATE AS DECIMAL(18,2))) AS ISS_RATE
			, SUM(CAST(	COFINS AS DECIMAL(18,2))) AS COFINS
			, SUM(CAST(	COFINS_BASE AS DECIMAL(18,2))) AS COFINS_BASE
			, SUM(CAST(	COFINS_RATE AS DECIMAL(18,2))) AS COFINS_RATE
			, SUM(CAST(	ST AS DECIMAL(18,2))) AS ST
			, SUM(CAST(	ST_BASE AS DECIMAL(18,2))) AS ST_BASE
			, SUM(CAST(	ST_RATE AS DECIMAL(18,2))) AS ST_RATE
			, SUM(CAST(	ICAP_TAXVAL AS DECIMAL(18,2))) AS ICAP_TAXVAL
			, SUM(CAST(	ICAP_BASE AS DECIMAL(18,2))) AS	ICAP_BASE
			, SUM(CAST(	ICAP_RATE AS DECIMAL(18,2))) AS	ICAP_RATE
			
		FROM OW_LAO.ODS_NERP_ZLSDK66820_DISPLAY_CLOSING_REPORT
		GROUP BY
			  SALES_ORDER
			, MATERIAL_CODE
			, SOLD_TO_PARTY
			, SALES_DOCUMENT_TYPE
			, BILLING_DATE
			, CONCAT( 
				  SUBSTRING(CAST(BILLING_DATE AS VARCHAR(30)),1,4)
				, SUBSTRING(CAST(BILLING_DATE AS VARCHAR(30)),6,2)		
			) --AS YYYYMM
			--, MONTH(BILLING_DATE) --AS "POSTING_PERIOD"
			--, YEAR(BILLING_DATE) --AS "YEAR"
	);
	IF EXISTS ( SELECT TABLE_NAME FROM SYS.TABLES WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TMP_GROSS_MARGIN_CHANNEL' ) THEN
		DROP TABLE OW_LAO.TMP_GROSS_MARGIN_CHANNEL; 
	END IF ;
	CREATE COLUMN TABLE OW_LAO.TMP_GROSS_MARGIN_CHANNEL AS (
		SELECT 
			  SO.SALES_DOCUMENT
			, SO.CUSTOMER_PO
			, MAX(NS.AFFILIATE_CHANNEL) AS AFFILIATE_CHANNEL
			, MAX(NS.AFFILIATE_SUB_CHANNEL) AS AFFILIATE_SUB_CHANNEL
			, MAX(NS.AFFILIATE_PARTNER_LEVEL) AS AFFILIATE_PARTNER_LEVEL
		FROM OW_LAO.TF_D2C_NERP_SALES NS
			INNER JOIN (
				SELECT 
					  SALES_DOCUMENT
					, MAX(CUSTOMER_PO) AS CUSTOMER_PO
				FROM OW_LAO.ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING
				WHERE SALES_DOCUMENT IN (SELECT SALES_ORDER FROM OW_LAO.TMP_GROSS_MARGIN_ZKE)
					AND SALES_ORG = '8201' -- SEDA
				GROUP BY
					SALES_DOCUMENT			
			) SO ON NS.CUSTOMER_PO = SO.CUSTOMER_PO
		WHERE SOURCE = 'PO'
			AND SUBSIDIARY = 'SEDA'
		GROUP BY
			  SO.SALES_DOCUMENT
			, SO.CUSTOMER_PO
	);
	
	-- APAGA PERIODOS
	DELETE FROM OW_LAO.TF_NERP_GROSS_MARGIN
	WHERE YYYYMM_ZKE IN (SELECT DISTINCT YYYYMM_ZKE FROM OW_LAO.TMP_GROSS_MARGIN_ZKE)
	--YYYYMM_ZKE BETWEEN (SELECT (YEAR(DATE_INI) * 100 + MONTH(DATE_INI)) FROM OW_LAO.TMP_PARAMETER_GROSS_MARGIN )
	--										AND (SELECT (YEAR(DATE_FIM) * 100 + MONTH(DATE_FIM)) FROM OW_LAO.TMP_PARAMETER_GROSS_MARGIN )	
	;
	
	--IF EXISTS ( SELECT TABLE_NAME FROM SYS.TABLES WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TF_NERP_GROSS_MARGIN' ) THEN
	--	DROP TABLE OW_LAO.TF_NERP_GROSS_MARGIN;
	--END IF ;
	--CREATE COLUMN TABLE OW_LAO.TF_NERP_GROSS_MARGIN AS (
	
	INSERT INTO OW_LAO.TF_NERP_GROSS_MARGIN
		SELECT
			  ZKE.PA_COST_ELEMENT
			, ZKE.PA_CE_DESCRIPTION	
			, DCR.SALES_DOCUMENT_TYPE
			, ZKE.SALES_ORDER
			, POCH.CUSTOMER_PO
		
			, TO_DATE(DCR.BILLING_DATE) AS BILLING_DATE
			, DCR.YYYYMM --AS YYYYMM_BD
			, ZKE.YYYYMM_ZKE			
			--, CL.YYYYWW AS YYYYWW
			--, CL.YYYYMM AS YYYYMM
			--, CL.YYYYQQ AS YYYYQQ
			-- CHANNEL
		
			, ZKE.CUSTOMER AS SOLD_TO_ID
			--, CH."Sold-To Party" VARCHAR(5000)
			, CH."Sold-To Party2" AS "SOLD-TO PART" -- VARCHAR(5000)
			, CH.D2C --VARCHAR(5000)
			, CH."D2C GROUP 1" --VARCHAR(5000)
			, CH."D2C GROUP 2" --VARCHAR(5000)
			, CH."Recebimento repasse" as "RECEBIMENTO REPASSE"--VARCHAR(5000)
			
			, POCH.AFFILIATE_CHANNEL
			, POCH.AFFILIATE_SUB_CHANNEL
			, POCH.AFFILIATE_PARTNER_LEVEL AS PARTNER_LEVEL
			
			--, CH.PARTNER_LEVEL --VARCHAR(5000)
			--, CH.AFFILIATE_SUB_CHANNEL --VARCHAR(5000)
			--, CH.AFFILIATE_CHANNEL --VARCHAR(5000)
			
			-- PRODUCT
			, ZKE.PRODUCT AS SKU
			, PD."DIVISION" AS PDROD_DIVISION
			, PD.PRODUCT_GROUP_1 AS PDROD_PRODUCT_GROUP 
			, PD.PRODUCT_1 AS PDROD_PRODUCT 
			, PD.ATTB01 AS PROD_ATTB_1 
			, PD.SEDA_BU_ESTORE
			, PD.SEDA_DIVISION_ESTORE
			, PD.SEDA_CATEGORY_ESTORE
			, PD.SEDA_FAMILY_ESTORE
			, PD.SEDA_DESC_ESTORE
			, CASE WHEN PR.MATERIAL IS NOT NULL THEN 'PREMIUM MODEL' ELSE 'NORMAL MODEL' END AS MODEL_TYPE
			
			, DCR.DESC_MAT_GROUP
			, DCR.REGION
			, DCR.CITY
			, ZKE.AMOUNT AS AMOUNT_ZKE
			, CASE WHEN SALES_DOCUMENT_TYPE LIKE 'YR%' AND DCR.NF_TOTAL_AMT > 0 THEN (DCR.NF_TOTAL_AMT * -1)  ELSE DCR.NF_TOTAL_AMT END AS NF_TOTAL_AMT
			
			, RB_TT.AMOUNT_TOTAL_RB AS AMOUNT_TOTAL_SOLD_TO
			, RB_TT.AMOUNT_TOTAL_RB_RT AS AMOUNT_TOTAL_SOLD_TO_RT
			
			, IFNULL(ZKE.TAX_INCENTIVE,0)	AS TAX_INCENTIVE_ZKE
			, DCR.NET_AMOUNT AS NET_AMOUNT_DCR
			, DCR.INCENTIVE AS INCENTIVE_DCR
			--NEW FIELDS
			, DCR.ICMS AS ICMS_DCR
			, DCR.ICMS_BASE AS ICMS_BASE_DCR
			, DCR.ICMS_RATE AS ICMS_RATE_DCR
			, DCR.IPI AS IPI_DCR
			, DCR.IPI_BASE AS IPI_BASE_DCR
			, DCR.IPI_RATE AS IPI_RATE_DCR
			, DCR.PIS AS PIS_DCR
			, DCR.PIS_BASE AS PIS_BASE_DCR
			, DCR.PIS_RATE AS PIS_RATE_DCR
			, DCR.ISS AS ISS_DCR
			, DCR.ISS_BASE AS ISS_BASE_DCR
			, DCR.ISS_RATE AS ISS_RATE_DCR
			, DCR.COFINS AS COFINS_DCR
			, DCR.COFINS_BASE AS COFINS_BASE_DCR
			, DCR.COFINS_RATE AS COFINS_RATE_DCR
			, DCR.ST AS ST_DCR
			, DCR.ST_BASE AS ST_BASE_DCR
			, DCR.ST_RATE AS ST_RATE_DCR
			, DCR.ICAP_TAXVAL AS ICAP_TAXVAL_DCR
			, DCR.ICAP_BASE AS ICAP_BASE_DCR
			, DCR.ICAP_RATE AS ICAP_RATE_DCR
			
			, ZKE.QTY
			
			, IFNULL(CG.COGS_UNIT,0) AS COGS
			, (IFNULL(CG.COGS_UNIT,0) * ZKE.QTY) AS COGS_TOTAL
			
			, CAST(RB.REBATE AS DECIMAL(18,2) ) AS REBATE_TOTAL_SOLD_TO
			
			, CAST( ( CASE WHEN RB.REBATE IS NOT NULL THEN 
				 CASE
					 WHEN ZKE.AMOUNT > 0 AND RB_TT.AMOUNT_TOTAL_RB > 0 AND RB.REBATE > 0 AND ZKE.PA_COST_ELEMENT = 81101000 THEN
						(ZKE.AMOUNT / RB_TT.AMOUNT_TOTAL_RB) * RB.REBATE
					 WHEN ZKE.AMOUNT < 0 AND RB_TT.AMOUNT_TOTAL_RB_RT < 0 AND RB.REBATE < 0 AND ZKE.PA_COST_ELEMENT = 81105000 THEN -- NEGATIVO
						(ZKE.AMOUNT / RB_TT.AMOUNT_TOTAL_RB_RT) * RB.REBATE
					ELSE 0 END
			  ELSE 0 END ) AS DECIMAL(18,2) ) AS REBATE
			  
			--, CASE WHEN ZKE.AMOUNT > 0 AND RB.REBATE IS NOT NULL THEN (ZKE.AMOUNT / IFNULL(RB_TT.AMOUNT_TOTAL_RB,0)) * RB.REBATE ELSE 0 END 
			--  AS REBATE
			--, (ZKE.AMOUNT - ( IFNULL(CG.COGS_UNIT,0)  * ZKE.QTY)) + IFNULL(ZKE.TAX_INCENTIVE,0)  AS GROSS_AMT
			
			,CAST( (ZKE.AMOUNT + IFNULL(ZKE.TAX_INCENTIVE,0) 
			+  ( CASE WHEN RB.REBATE IS NOT NULL THEN 
				 CASE
					 WHEN ZKE.AMOUNT > 0 AND RB_TT.AMOUNT_TOTAL_RB > 0 AND RB.REBATE > 0 AND ZKE.PA_COST_ELEMENT = 81101000 THEN
						(ZKE.AMOUNT / RB_TT.AMOUNT_TOTAL_RB) * RB.REBATE
					 WHEN ZKE.AMOUNT < 0 AND RB_TT.AMOUNT_TOTAL_RB_RT < 0 AND RB.REBATE < 0 AND ZKE.PA_COST_ELEMENT = 81105000 THEN -- NEGATIVO
						(ZKE.AMOUNT / RB_TT.AMOUNT_TOTAL_RB_RT) * RB.REBATE
					ELSE 0 END
			  ELSE 0 END ) 
			 ) AS DECIMAL(18,2) ) AS NET_SALES_TTL_LOCAL
			 
			 ,CAST( (
				(ZKE.AMOUNT + IFNULL(ZKE.TAX_INCENTIVE,0) 
				+  ( CASE WHEN RB.REBATE IS NOT NULL THEN 
					 CASE
						 WHEN ZKE.AMOUNT > 0 AND RB_TT.AMOUNT_TOTAL_RB > 0 AND RB.REBATE > 0 AND ZKE.PA_COST_ELEMENT = 81101000 THEN
							(ZKE.AMOUNT / RB_TT.AMOUNT_TOTAL_RB) * RB.REBATE
						 WHEN ZKE.AMOUNT < 0 AND RB_TT.AMOUNT_TOTAL_RB_RT < 0 AND RB.REBATE < 0 AND ZKE.PA_COST_ELEMENT = 81105000 THEN -- NEGATIVO
							(ZKE.AMOUNT / RB_TT.AMOUNT_TOTAL_RB_RT) * RB.REBATE
						ELSE 0 END
				  ELSE 0 END ) 
				 )
			 / IFNULL( EX.EXCHANGE_RATE , EX2.EXCHANGE_RATE)
			 /******************
							(
								SELECT EXCHANGE_RATE
								FROM (
									SELECT EXCHANGE_RATE 
										,RANK() OVER( PARTITION BY TO_CURRENCY ORDER BY VALID_FROM DESC) AS SEQ
									FROM OW_LAO.FT_AP2_EXCHANGE_RATE EX 
									WHERE FROM_CURRENCY = 'USD'
										AND TO_CURRENCY = 'BRL'
								)
								WHERE SEQ = 1
							)
			   )
			   ******************/
			 
			 ) AS DECIMAL(18,2) ) AS NET_SALES_TTL_USD
			
			, -- NET_SALES_TTL 
			  CAST((( ZKE.AMOUNT + IFNULL(ZKE.TAX_INCENTIVE,0) 
			+  ( CASE WHEN RB.REBATE IS NOT NULL THEN 
				 CASE
					 WHEN ZKE.AMOUNT > 0 AND RB_TT.AMOUNT_TOTAL_RB > 0 AND RB.REBATE > 0 AND ZKE.PA_COST_ELEMENT = 81101000 THEN
						(ZKE.AMOUNT / RB_TT.AMOUNT_TOTAL_RB) * RB.REBATE
					 WHEN ZKE.AMOUNT < 0 AND RB_TT.AMOUNT_TOTAL_RB_RT < 0 AND RB.REBATE < 0 AND ZKE.PA_COST_ELEMENT = 81105000 THEN -- NEGATIVO
						(ZKE.AMOUNT / RB_TT.AMOUNT_TOTAL_RB_RT) * RB.REBATE
					ELSE 0 END
			  ELSE 0 END ) 
			 ) - (IFNULL(CG.COGS_UNIT,0) * ZKE.QTY)) AS DECIMAL(18,2) ) AS  GROSS_PROFIT_LOCAL
			 
			 
			, CURRENT_TIMESTAMP AS KPI_LAST_UPDATE
			
		FROM
			OW_LAO.TMP_GROSS_MARGIN_ZKE ZKE
			LEFT JOIN OW_LAO.TMP_GROSS_MARGIN_DCR DCR 
			     ON DCR.SALES_ORDER = ZKE.SALES_ORDER
					AND DCR.MATERIAL_CODE = ZKE.PRODUCT
					AND DCR.SOLD_TO = ZKE.CUSTOMER
					--AND DCR.YYYYMM = ZKE.YYYYMM
					-- AND DCR.POSTING_PERIOD = ZKE.POSTING_PERIOD
					-- AND DCR."YEAR" = ZKE."YEAR"
					
			LEFT JOIN(
				SELECT REFERENCE_CODE, YYYYMM, COGS_UNIT, FILE_NAME, LAST_MODIFICATION_FILE, LOAD_DATE 
				FROM OW_MD.COGS
				UNION ALL 
				SELECT REFERENCE_CODE, YYYYMM, COGS_UNIT, FILE_NAME, LAST_MODIFICATION_FILE, LOAD_DATE 
				FROM OW_LAO.TMP_COGS_NEXT_MONTH
			) CG ON CG.REFERENCE_CODE = ZKE.PRODUCT
					  		 AND CG.YYYYMM = DCR.YYYYMM
					  		 
			LEFT JOIN OW_MD.REBATE RB
					 	  ON RB.REFERENCE_CODE = ZKE.PRODUCT
					  		 AND RB.YYYYMM = DCR.YYYYMM
					  		 AND RB.SOLD_TO = ZKE.CUSTOMER
			
			LEFT JOIN (
				SELECT
					  Z.PRODUCT
					, D.YYYYMM	
					, Z.CUSTOMER
					, SUM(CASE WHEN Z.AMOUNT > 0 AND R.REBATE > 0 AND Z.PA_COST_ELEMENT = 81101000 THEN Z.AMOUNT ELSE 0 END) AS AMOUNT_TOTAL_RB -- POSITIVOS
					, SUM(CASE WHEN Z.AMOUNT < 0 AND R.REBATE < 0 THEN Z.AMOUNT ELSE 0 END) AS AMOUNT_TOTAL_RB_RT -- NEGATIVOS
				FROM OW_LAO.TMP_GROSS_MARGIN_ZKE Z
					INNER JOIN OW_LAO.TMP_GROSS_MARGIN_DCR D 
						 ON D.SALES_ORDER = Z.SALES_ORDER
							AND D.MATERIAL_CODE = Z.PRODUCT
							AND D.SOLD_TO = Z.CUSTOMER
					INNER JOIN OW_MD.REBATE R
							 	  ON R.REFERENCE_CODE = Z.PRODUCT
							  		 AND R.YYYYMM = D.YYYYMM
							  		 AND R.SOLD_TO = Z.CUSTOMER
				--WHERE Z.AMOUNT > 0 -- POSITIVO
				GROUP BY
					  Z.PRODUCT
					, D.YYYYMM	
					, Z.CUSTOMER
			) RB_TT
				ON RB_TT.PRODUCT = ZKE.PRODUCT
					AND RB_TT.YYYYMM = DCR.YYYYMM
					AND RB_TT.CUSTOMER = ZKE.CUSTOMER	 
					  		
			LEFT JOIN OW_MD.DIM_PRODUCT PD ON PD.SKU = ZKE.PRODUCT
			
			LEFT JOIN (
					SELECT DISTINCT TRIM(ITEM) AS MATERIAL
					FROM OW_LAO.ODS_GSCM_PREMIUM_MODELS
				) PR ON PR.MATERIAL = ZKE.PRODUCT
				
			-- LEFT JOIN OW_MD.DIM_CALENDAR CL ON CL.YYYYMMDD = TO_DATE(DCR.BILLING_DATE) 
			
			LEFT JOIN OW_MD.SOLD_TO_CHANNEL CH ON CH."Sold-To Party" = ZKE.CUSTOMER
			
			LEFT JOIN OW_LAO.TMP_EXCHANGE_RATE_GM EX ON 
					YEAR(IFNULL(TO_DATE(DCR.BILLING_DATE) , ZKE.YYYYMMDD)) = EX.YEAR
				AND MONTH(IFNULL(TO_DATE(DCR.BILLING_DATE) , ZKE.YYYYMMDD)) = EX.MONTH
				
			LEFT JOIN OW_LAO.TMP_EXCHANGE_RATE_GM EX2 ON -- Mês anterior
					YEAR(IFNULL(TO_DATE(DCR.BILLING_DATE) , ZKE.YYYYMMDD)) = EX2.YEAR
				AND ( MONTH(IFNULL(TO_DATE(DCR.BILLING_DATE) , ZKE.YYYYMMDD)) - 1) = EX2.MONTH -- Mês anterior
							
			LEFT JOIN OW_LAO.TMP_GROSS_MARGIN_CHANNEL POCH ON ZKE.SALES_ORDER = POCH.SALES_DOCUMENT
			/*************
			LEFT JOIN OW_LAO.FT_AP2_EXCHANGE_RATE EX
				ON 	EX.VALID_FROM =  IFNULL(TO_DATE(DCR.BILLING_DATE) , ZKE.YYYYMMDD)  
					AND EX.TO_CURRENCY = 'BRL'
					AND EX.FROM_CURRENCY = 'USD'
			*******************/
	--)
	;
	
	/*********************************************************
	* APAGA TEMPORÁRIAS
	* *******************************************************/
	DROP TABLE OW_LAO.TMP_PARAMETER_GROSS_MARGIN;
	DROP TABLE OW_LAO.TMP_COGS_NEXT_MONTH;
	DROP TABLE OW_LAO.TMP_GROSS_MARGIN_ZKE;
	DROP TABLE OW_LAO.TMP_GROSS_MARGIN_DCR;
	DROP TABLE OW_LAO.TMP_EXCHANGE_RATE_GM;
	DROP TABLE OW_LAO.TMP_GROSS_MARGIN_CHANNEL;
	
END