/***********************************************************************************************
CREATED BY : Luciano Mariani
CREATION DATE : 2023-08-01
-- CALL OW_LAO.PROC_D2C_VTEX_SELLOUT_PLATFORM_KPI;
SELECT TOP 100 * FROM OW_LAO.TF_D2C_VTEX_SELLOUT_PLATFORM_KPI
***********************************************************************************************/
CREATE PROCEDURE OW_LAO.PROC_D2C_VTEX_SELLOUT_PLATFORM_KPI LANGUAGE SQLSCRIPT
AS
BEGIN
	
	--APAGA TATBELA FATO TF_D2C_VTEX_SELLOUT_PLATFORM_KPI
	IF EXISTS(
		SELECT TABLE_NAME
		FROM SYS.TABLES
		WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TF_D2C_VTEX_SELLOUT_PLATFORM_KPI'
	)
	THEN
		DROP TABLE OW_LAO.TF_D2C_VTEX_SELLOUT_PLATFORM_KPI;
	END IF;
	
	--CRIA NOVA TATBELA FATO TF_D2C_NERP_SALES_REWARDS_KPI
	CREATE COLUMN TABLE OW_LAO.TF_D2C_VTEX_SELLOUT_PLATFORM_KPI AS (
			SELECT
				  NS."SOURCE"
				, NS.DATE_REF
				, NS.YYYYWW
				, NS.YYYYMM
				, NS.YYYYQQ
				, NS.SUBSIDIARY
				, NS.CHANNEL_TYPE
				, NS.SKU
				, NS.PDROD_DIVISION
				, NS.PDROD_PRODUCT_GROUP
				, NS.PDROD_PRODUCT
				, NS.PROD_ATTB_1
				, NS.SEDA_BU_ESTORE
				, NS.SEDA_CATEGORY_ESTORE
				, NS.SEDA_DESC_ESTORE
				, NS.SEDA_DIVISION_ESTORE
				, NS.SEDA_FAMILY_ESTORE
				, NS.STATUS_PO
				-- AFFILIATE
				, NS.AFFILIATE_CHANNEL
				, NS.AFFILIATE_SUB_CHANNEL
				, NS.AFFILIATE_PARTNER_LEVEL
				, NS.GLOBAL_CHANNEL
				--,BIZ_TYPE
				, NS.AUDIENCE_TYPE
				, NS.COUNTRY
				, NS.CURRENCY
				, NS.MODEL_TYPE
		
				--, LOWER(NS.COUPON) AS COUPON
				, UPPER(SUBSTR_REGEXPR( '([-])([^-]*)(?=-)' IN CONCAT(CONCAT('-', NS.COUPON),'-') OCCURRENCE 1 GROUP 2)) AS COUPON 
				
				, NS.COUPON AS COUPON_ORIGINAL
				
				, CASE WHEN NS.IS_TRADE_IN = TRUE THEN 1 ELSE 0 END AS IS_TRADE_IN
				, CASE WHEN NS.IS_GTI = TRUE THEN 1 ELSE 0 END AS IS_GTI
				, CASE WHEN NS.IS_ECO_TROCA = TRUE THEN 1 ELSE 0 END AS IS_ECO_TROCA
				
				, CASE 
					  WHEN UPPER(NS.COUPON) LIKE '%LIVE%' OR UPPER(NS.COUPON) LIKE '%BLUE%' THEN TRUE
					  ELSE FALSE 
				  END AS IS_LIVE_COMMERCE
				
				, SUM(NS.QTY) AS QTY
				, SUM(NS.AMOUNT_LOCAL) AS AMOUNT_LOCAL
				, SUM(NS.AMOUNT_USD) AS AMOUNT_USD
				
				, SUM(CASE WHEN NS.IS_TRADE_IN = TRUE THEN NS.QTY ELSE 0 END) AS QTY_TRADE_IN
				, SUM(CASE WHEN NS.IS_TRADE_IN = TRUE THEN NS.AMOUNT_LOCAL ELSE 0 END) AS AMOUNT_LOCAL_TRADE_IN
				, SUM(CASE WHEN NS.IS_TRADE_IN = TRUE THEN NS.AMOUNT_USD ELSE 0 END) AS AMOUNT_USD_TRADE_IN
				
				, SUM(CASE WHEN NS.IS_GTI = TRUE THEN NS.QTY ELSE 0 END) AS QTY_GTI
				, SUM(CASE WHEN NS.IS_GTI = TRUE THEN NS.AMOUNT_LOCAL ELSE 0 END) AS AMOUNT_LOCAL_GTI
				, SUM(CASE WHEN NS.IS_GTI = TRUE THEN NS.AMOUNT_USD ELSE 0 END) AS AMOUNT_USD_GTI
				
				, SUM(CASE WHEN NS.IS_ECO_TROCA = TRUE THEN NS.QTY ELSE 0 END) AS QTY_ECO_TROCA
				, SUM(CASE WHEN NS.IS_ECO_TROCA = TRUE THEN NS.AMOUNT_LOCAL ELSE 0 END) AS AMOUNT_LOCAL_ECO_TROCA
				, SUM(CASE WHEN NS.IS_ECO_TROCA = TRUE THEN NS.AMOUNT_USD ELSE 0 END) AS AMOUNT_USD_ECO_TROCA				
				, SUM(CASE WHEN (CASE 
					  WHEN UPPER(NS.COUPON) LIKE '%LIVE%' OR UPPER(NS.COUPON) LIKE '%BLUE%' THEN TRUE
					  ELSE FALSE 
				  END) = TRUE THEN NS.QTY ELSE 0 END) AS QTY_LIVE_COMMERCE
				, SUM(CASE WHEN (CASE 
					  WHEN UPPER(NS.COUPON) LIKE '%LIVE%' OR UPPER(NS.COUPON) LIKE '%BLUE%' THEN TRUE
					  ELSE FALSE 
				  END) = TRUE THEN NS.AMOUNT_LOCAL ELSE 0 END) AS AMOUNT_LOCAL_LIVE_COMMERCE
				, SUM(CASE WHEN (CASE 
					  WHEN UPPER(NS.COUPON) LIKE '%LIVE%' OR UPPER(NS.COUPON) LIKE '%BLUE%' THEN TRUE
					  ELSE FALSE 
				  END) = TRUE THEN NS.AMOUNT_USD ELSE 0 END) AS AMOUNT_USD_LIVE_COMMERCE			
				
				, CURRENT_TIMESTAMP AS KPI_LAST_UPDATE --,KPI_LAST_UPDATE
			FROM (
				SELECT
					  "SOURCE", DATE_REF, YYYYWW, YYYYMM, YYYYQQ, SUBSIDIARY, CHANNEL_TYPE, SKU, PDROD_DIVISION, PDROD_PRODUCT_GROUP, PDROD_PRODUCT, PROD_ATTB_1, SEDA_BU_ESTORE
					, SEDA_CATEGORY_ESTORE, SEDA_DESC_ESTORE, SEDA_DIVISION_ESTORE, SEDA_FAMILY_ESTORE, STATUS_PO, AFFILIATE_CHANNEL, AFFILIATE_SUB_CHANNEL, AFFILIATE_PARTNER_LEVEL
					, GLOBAL_CHANNEL, AUDIENCE_TYPE, COUNTRY, CURRENCY, MODEL_TYPE, COUPON, IS_TRADE_IN, IS_GTI, IS_ECO_TROCA, QTY
					, AMOUNT_LOCAL, AMOUNT_USD
				FROM OW_LAO.TF_D2C_NERP_SALES
				WHERE ORDER_ID NOT IN (SELECT DISTINCT ORDER_ID FROM OW_LAO.TF_D2C_PO_VTEX_TRADE_IN)
				UNION ALL
				SELECT
					  "SOURCE", DATE_REF, YYYYWW, YYYYMM, YYYYQQ, SUBSIDIARY, CHANNEL_TYPE, SKU, PDROD_DIVISION, PDROD_PRODUCT_GROUP, PDROD_PRODUCT, PROD_ATTB_1, SEDA_BU_ESTORE
					, SEDA_CATEGORY_ESTORE, SEDA_DESC_ESTORE, SEDA_DIVISION_ESTORE, SEDA_FAMILY_ESTORE, STATUS_PO, AFFILIATE_CHANNEL, AFFILIATE_SUB_CHANNEL, AFFILIATE_PARTNER_LEVEL
					, GLOBAL_CHANNEL, AUDIENCE_TYPE, COUNTRY, CURRENCY, MODEL_TYPE, COUPON, IS_TRADE_IN, IS_GTI, IS_ECO_TROCA, QTY
					, AMOUNT_LOCAL, AMOUNT_USD
				FROM OW_LAO.TF_D2C_PO_VTEX_TRADE_IN
			) NS
			WHERE "SOURCE" = 'PO'
				AND STATUS_PO NOT IN('cancel','canceled')
			GROUP BY
				  "SOURCE"
				, NS.DATE_REF
				, NS.YYYYWW
				, NS.YYYYMM
				, NS.YYYYQQ
				, NS.SUBSIDIARY
				, NS.CHANNEL_TYPE
				, NS.SKU
				, NS.PDROD_DIVISION
				, NS.PDROD_PRODUCT_GROUP
				, NS.PDROD_PRODUCT
				, NS.PROD_ATTB_1
				, NS.SEDA_BU_ESTORE
				, NS.SEDA_CATEGORY_ESTORE
				, NS.SEDA_DESC_ESTORE
				, NS.SEDA_DIVISION_ESTORE
				, NS.SEDA_FAMILY_ESTORE
				, NS.STATUS_PO
				, NS.AFFILIATE_CHANNEL
				, NS.AFFILIATE_SUB_CHANNEL
				, NS.AFFILIATE_PARTNER_LEVEL
				, NS.GLOBAL_CHANNEL
				--,BIZ_TYPE
				, NS.AUDIENCE_TYPE
				, NS.COUNTRY
				, NS.CURRENCY
				, NS.MODEL_TYPE
				--, LOWER(NS.COUPON) -- AS COUPON
				, UPPER(SUBSTR_REGEXPR( '([-])([^-]*)(?=-)' IN CONCAT(CONCAT('-', NS.COUPON),'-') OCCURRENCE 1 GROUP 2)) --AS COUPON
				, NS.COUPON
				, NS.IS_TRADE_IN
				, NS.IS_GTI
				, NS.IS_ECO_TROCA
				, CASE 
					  WHEN UPPER(NS.COUPON) LIKE '%LIVE%' OR UPPER(NS.COUPON) LIKE '%BLUE%' THEN TRUE
					  ELSE FALSE 
				  END				
	);
	UPDATE OW_LAO.TF_D2C_VTEX_SELLOUT_PLATFORM_KPI SET
	KPI_LAST_UPDATE = (
			SELECT MAX(PO_CREATION_DATE)
			FROM OW_LAO.TF_D2C_NERP_SALES
			WHERE "SOURCE" = 'PO'
				AND SUBSIDIARY = 'SEDA'
		  ) --AS KPI_LAST_UPDATE					
	;
END