/***********************************************************************************************
CREATED BY : Luciano Mariani
CREATION DATE : 2023-08-01
ALTER DATE : 
VERSION: 1.0
-- CALL OW_LAO.PROC_D2C_VTEX_PROMOTION_KPI;
SELECT TOP 100 * 
FROM OW_LAO.TF_D2C_VTEX_PROMOTION_KPI 
WHERE IS_TRADE_IN = 'true'
	  AND DATE_REF > '2023-09-01'
***********************************************************************************************/
CREATE PROCEDURE OW_LAO.PROC_D2C_VTEX_PROMOTION_KPI LANGUAGE SQLSCRIPT
AS
BEGIN
	
	-- EXECUTA TRADE IN
	CALL OW_LAO.PROC_D2C_VTEX_PROMOTION;
	
	--APAGA TATBELA OW_LAO.TF_D2C_VTEX_PROMOTION_KPI
	IF EXISTS( SELECT TABLE_NAME
			   FROM SYS.TABLES
			   WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TF_D2C_VTEX_PROMOTION_KPI'
	)THEN DROP TABLE OW_LAO.TF_D2C_VTEX_PROMOTION_KPI;
	END IF;
	--CRIA NOVA TABELA TF_D2C_VTEX_PROMOTION_KPI
	CREATE COLUMN TABLE OW_LAO.TF_D2C_VTEX_PROMOTION_KPI AS (		
		SELECT
			  CL.YYYYWW AS YYYYWW
			, CL.YYYYMM AS YYYYMM
			, CL.YYYYQQ AS YYYYQQ
			, 'SEDA' AS SUBSIDIARY
			-- INFO PRODUTO
			, PO.REFERENCE_CODE
			, PD."DIVISION" AS PDROD_DIVISION
			, PD.PRODUCT_GROUP_1 AS PDROD_PRODUCT_GROUP
			, PD.PRODUCT_1 AS PDROD_PRODUCT
			, PD.ATTB01 AS PROD_ATTB_1
			, PD.SEDA_BU_ESTORE
			, PD.SEDA_CATEGORY_ESTORE
			, PD.SEDA_DESC_ESTORE
			, PD.SEDA_DIVISION_ESTORE
			, PD.SEDA_FAMILY_ESTORE
			, PO.STATUS_PO
			, SP.STATUS			
			-- PROMOTION INFO
			, PO.PROM_PRICE_TABLE_NAME
			, PO.PROMOTION_TYPE
			, PO.PROMOTION_SUBTYPE
			, PO.PROM_STATUS
			, PO.ENVIRONMENT
			, PO.PROM_NAME
			, PO.PRC_TAG_NAME--, PRICE_TABLE_NAME
			, PO.PROM_BEGIN_DATE
			, PO.PROM_END_DATE
			
			, CASE WHEN PO.PRICE_TAGS IS NOT NULL THEN 1 ELSE 0 END AS HAS_PRICE_TAGS
			--,PO.IS_SHIPPING
			, CASE WHEN PO.IS_SHIPPING = TRUE THEN 'YES' ELSE 'NO' END AS IS_SHIPPING			
			,SUM( CAST(PO.PROM_ABSLTE_SHIP_DSCNT_VALUE AS DECIMAL(18,2)) ) AS PROM_ABSLTE_SHIP_DSCNT_VALUE
			,SUM( CAST(PO.PROM_PERCENT_SHIP_DSCNT_VALUE AS DECIMAL(18,2)) ) AS PROM_PERCENT_SHIP_DSCNT_VALUE
			
			/***
			, SUM(
				CASE WHEN PO.IS_SHIPPING = TRUE THEN
					CAST (PO.PROM_ABSLTE_SHIP_DSCNT_VALUE AS DECIMAL(18,2)) 
				ELSE NULL END
			) AS PROM_ABSLTE_SHIP_DSCNT_VALUE
			***/
			--, SUM(CAST (PO.PROM_ABSLTE_SHIP_DSCNT_VALUE AS DECIMAL(5,2)) ) AS PROM_ABSLTE_SHIP_DSCNT_VALUE
			, SUM(PO.AMOUNT_DISCOUNT) AS AMOUNT_DISCOUNT
			, COUNT('') AS QTY
			, COUNT( DISTINCT PO.ORDER_ID) AS QTY_ORDER
			, CURRENT_TIMESTAMP AS KPI_LAST_UPDATE --,KPI_LAST_UPDATE
		FROM OW_LAO.FT_D2C_VTEX_PROMOTION PO
			LEFT JOIN OW_MD.DIM_CALENDAR CL ON CL.YYYYMMDD = PO.DATE_REF 
			LEFT JOIN OW_MD.DIM_PRODUCT PD ON PD.SKU = PO.REFERENCE_CODE
			--LEFT JOIN OW_LAO.TMP_PREMIUM_MODELS_WEEKLY_SALES PR ON PR.MATERIAL = FCT.PRODUCT_NUMBER		
			LEFT JOIN OW_MD.DIM_PO_STATUS SP ON UPPER(SP.STATUS_PO) = UPPER(PO.STATUS_PO)
		GROUP BY
		  	  CL.YYYYWW --AS YYYYWW
			, CL.YYYYMM --AS YYYYMM
			, CL.YYYYQQ --AS YYYYQQ
			-- INFO PRODUTO
			, PO.REFERENCE_CODE
			, PD."DIVISION" --AS PDROD_DIVISION
			, PD.PRODUCT_GROUP_1 --AS PDROD_PRODUCT_GROUP
			, PD.PRODUCT_1 --AS PDROD_PRODUCT
			, PD.ATTB01 --AS PROD_ATTB_1
			, PD.SEDA_BU_ESTORE
			, PD.SEDA_CATEGORY_ESTORE
			, PD.SEDA_DESC_ESTORE
			, PD.SEDA_DIVISION_ESTORE
			, PD.SEDA_FAMILY_ESTORE
			, PO.STATUS_PO
			, SP.STATUS			
			-- PROMOTION INFO
			, PO.PROM_PRICE_TABLE_NAME
			, PO.PROMOTION_TYPE
			, PO.PROMOTION_SUBTYPE
			, PO.PROM_STATUS
			, PO.ENVIRONMENT
			, PO.PROM_NAME
			, PO.PRC_TAG_NAME--, PRICE_TABLE_NAME
			, PO.PROM_BEGIN_DATE
			, PO.PROM_END_DATE
			, CASE WHEN PO.PRICE_TAGS IS NOT NULL THEN 1 ELSE 0 END --AS HAS_PRICE_TAGS
			--,PO.IS_SHIPPING
			, CASE WHEN PO.IS_SHIPPING = TRUE THEN 'YES' ELSE 'NO' END
			--, CASE WHEN PO.IS_SHIPPING = TRUE THEN 1 ELSE 0 END AS IS_SHIPPING			
			--,PO.PROM_ABSLTE_SHIP_DSCNT_VALUE
			--,PO.PROM_PERCENT_SHIP_DSCNT_VALUE
	);
	UPDATE OW_LAO.TF_D2C_VTEX_PROMOTION_KPI SET
		KPI_LAST_UPDATE = (
				SELECT MAX(PO_CREATION_DATE)
				FROM OW_LAO.TF_D2C_NERP_SALES
				WHERE "SOURCE" = 'PO'
					AND SUBSIDIARY = 'SEDA'
			  ) --AS KPI_LAST_UPDATE					
	;
	
END