CREATE PROCEDURE OW_LAO.PROC_ATU_LAO_SALES_DEDUCTION_MONITORING_STATUS_HIST
AS 
BEGIN
    INSERT INTO OW_LAO.FT_LAO_SALES_DEDUCTION_MONITORING_STATUS_HIST (
        PROCESS,
        SUB_PROCESS,
        PIC,
        DAY_WEEK,
        STATUS,
        BIZ_AREA_GROUP,
        BIZ_AREA_STATUS,
        UPDATE_DATE,
        WEEK,
        DT_FOTO
   )
    SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'MON' AS DAY_WEEK,
		MON AS STATUS,
		'390A' AS BIZ_AREA_GROUP,
		"390A" AS BIZ_AREA_STATUS,
		NULL AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'TUE' AS DAY_WEEK,
		TUE AS STATUS,
		'390A' AS BIZ_AREA_GROUP,
		"390A" AS BIZ_AREA_STATUS,
		NULL AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'WED' AS DAY_WEEK,
		WED AS STATUS,
		'390A' AS BIZ_AREA_GROUP,
		"390A" AS BIZ_AREA_STATUS,
		NULL AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'THU' AS DAY_WEEK,
		THU AS STATUS,
		'390A' AS BIZ_AREA_GROUP,
		"390A" AS BIZ_AREA_STATUS,
		NULL AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'FRI' AS DAY_WEEK,
		FRI AS STATUS,
		'390A' AS BIZ_AREA_GROUP,
		"390A" AS BIZ_AREA_STATUS,
		NULL AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'MON' AS DAY_WEEK,
		MON AS STATUS,
		'810A' AS BIZ_AREA_GROUP,
		"810A" AS BIZ_AREA_STATUS,
		NULL AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'TUE' AS DAY_WEEK,
		TUE AS STATUS,
		'810A' AS BIZ_AREA_GROUP,
		"810A" AS BIZ_AREA_STATUS,
		NULL AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'WED' AS DAY_WEEK,
		WED AS STATUS,
		'810A' AS BIZ_AREA_GROUP,
		"810A" AS BIZ_AREA_STATUS,
		NULL AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'THU' AS DAY_WEEK,
		THU AS STATUS,
		'810A' AS BIZ_AREA_GROUP,
		"810A" AS BIZ_AREA_STATUS,
		NULL AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'FRI' AS DAY_WEEK,
		FRI AS STATUS,
		'810A' AS BIZ_AREA_GROUP,
		"810A" AS BIZ_AREA_STATUS,
		NULL AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'MON' AS DAY_WEEK,
		MON AS STATUS,
		'810C' AS BIZ_AREA_GROUP,
		"810C" AS BIZ_AREA_STATUS,
		UPDATE_DATE_810C AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'TUE' AS DAY_WEEK,
		TUE AS STATUS,
		'810C' AS BIZ_AREA_GROUP,
		"810C" AS BIZ_AREA_STATUS,
		UPDATE_DATE_810C AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'WED' AS DAY_WEEK,
		WED AS STATUS,
		'810C' AS BIZ_AREA_GROUP,
		"810C" AS BIZ_AREA_STATUS,
		UPDATE_DATE_810C AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'THU' AS DAY_WEEK,
		THU AS STATUS,
		'810C' AS BIZ_AREA_GROUP,
		"810C" AS BIZ_AREA_STATUS,
		UPDATE_DATE_810C AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'FRI' AS DAY_WEEK,
		FRI AS STATUS,
		'810C' AS BIZ_AREA_GROUP,
		"810C" AS BIZ_AREA_STATUS,
		UPDATE_DATE_810C AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'MON' AS DAY_WEEK,
		MON AS STATUS,
		'810D' AS BIZ_AREA_GROUP,
		"810D" AS BIZ_AREA_STATUS,
		UPDATE_DATE_810D AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'TUE' AS DAY_WEEK,
		TUE AS STATUS,
		'810D' AS BIZ_AREA_GROUP,
		"810D" AS BIZ_AREA_STATUS,
		UPDATE_DATE_810D AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'WED' AS DAY_WEEK,
		WED AS STATUS,
		'810D' AS BIZ_AREA_GROUP,
		"810D" AS BIZ_AREA_STATUS,
		UPDATE_DATE_810D AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'THU' AS DAY_WEEK,
		THU AS STATUS,
		'810D' AS BIZ_AREA_GROUP,
		"810D" AS BIZ_AREA_STATUS,
		UPDATE_DATE_810D AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'FRI' AS DAY_WEEK,
		FRI AS STATUS,
		'810D' AS BIZ_AREA_GROUP,
		"810D" AS BIZ_AREA_STATUS,
		UPDATE_DATE_810D AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'MON' AS DAY_WEEK,
		MON AS STATUS,
		'810F' AS BIZ_AREA_GROUP,
		"810F" AS BIZ_AREA_STATUS,
		UPDATE_DATE_810F AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'TUE' AS DAY_WEEK,
		TUE AS STATUS,
		'810F' AS BIZ_AREA_GROUP,
		"810F" AS BIZ_AREA_STATUS,
		UPDATE_DATE_810F AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'WED' AS DAY_WEEK,
		WED AS STATUS,
		'810F' AS BIZ_AREA_GROUP,
		"810F" AS BIZ_AREA_STATUS,
		UPDATE_DATE_810F AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'THU' AS DAY_WEEK,
		THU AS STATUS,
		'810F' AS BIZ_AREA_GROUP,
		"810F" AS BIZ_AREA_STATUS,
		UPDATE_DATE_810F AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'FRI' AS DAY_WEEK,
		FRI AS STATUS,
		'810F' AS BIZ_AREA_GROUP,
		"810F" AS BIZ_AREA_STATUS,
		UPDATE_DATE_810F AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'MON' AS DAY_WEEK,
		MON AS STATUS,
		'810J' AS BIZ_AREA_GROUP,
		"810J" AS BIZ_AREA_STATUS,
		UPDATE_DATE_810J AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'TUE' AS DAY_WEEK,
		TUE AS STATUS,
		'810J' AS BIZ_AREA_GROUP,
		"810J" AS BIZ_AREA_STATUS,
		UPDATE_DATE_810J AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'WED' AS DAY_WEEK,
		WED AS STATUS,
		'810J' AS BIZ_AREA_GROUP,
		"810J" AS BIZ_AREA_STATUS,
		UPDATE_DATE_810J AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'THU' AS DAY_WEEK,
		THU AS STATUS,
		'810J' AS BIZ_AREA_GROUP,
		"810J" AS BIZ_AREA_STATUS,
		UPDATE_DATE_810J AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'FRI' AS DAY_WEEK,
		FRI AS STATUS,
		'810J' AS BIZ_AREA_GROUP,
		"810J" AS BIZ_AREA_STATUS,
		UPDATE_DATE_810J AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'MON' AS DAY_WEEK,
		MON AS STATUS,
		'810M' AS BIZ_AREA_GROUP,
		"810M" AS BIZ_AREA_STATUS,
		UPDATE_DATE_810M AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'TUE' AS DAY_WEEK,
		TUE AS STATUS,
		'810M' AS BIZ_AREA_GROUP,
		"810M" AS BIZ_AREA_STATUS,
		UPDATE_DATE_810M AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'WED' AS DAY_WEEK,
		WED AS STATUS,
		'810M' AS BIZ_AREA_GROUP,
		"810M" AS BIZ_AREA_STATUS,
		UPDATE_DATE_810M AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'THU' AS DAY_WEEK,
		THU AS STATUS,
		'810M' AS BIZ_AREA_GROUP,
		"810M" AS BIZ_AREA_STATUS,
		UPDATE_DATE_810M AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'FRI' AS DAY_WEEK,
		FRI AS STATUS,
		'810M' AS BIZ_AREA_GROUP,
		"810M" AS BIZ_AREA_STATUS,
		UPDATE_DATE_810M AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'MON' AS DAY_WEEK,
		MON AS STATUS,
		'850A' AS BIZ_AREA_GROUP,
		"850A" AS BIZ_AREA_STATUS,
		UPDATE_DATE_850A AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'TUE' AS DAY_WEEK,
		TUE AS STATUS,
		'850A' AS BIZ_AREA_GROUP,
		"850A" AS BIZ_AREA_STATUS,
		UPDATE_DATE_850A AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'WED' AS DAY_WEEK,
		WED AS STATUS,
		'850A' AS BIZ_AREA_GROUP,
		"850A" AS BIZ_AREA_STATUS,
		UPDATE_DATE_850A AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'THU' AS DAY_WEEK,
		THU AS STATUS,
		'850A' AS BIZ_AREA_GROUP,
		"850A" AS BIZ_AREA_STATUS,
		UPDATE_DATE_850A AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'FRI' AS DAY_WEEK,
		FRI AS STATUS,
		'850A' AS BIZ_AREA_GROUP,
		"850A" AS BIZ_AREA_STATUS,
		UPDATE_DATE_850A AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'MON' AS DAY_WEEK,
		MON AS STATUS,
		'813A' AS BIZ_AREA_GROUP,
		"813A" AS BIZ_AREA_STATUS,
		UPDATE_DATE_813A AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'TUE' AS DAY_WEEK,
		TUE AS STATUS,
		'813A' AS BIZ_AREA_GROUP,
		"813A" AS BIZ_AREA_STATUS,
		UPDATE_DATE_813A AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'WED' AS DAY_WEEK,
		WED AS STATUS,
		'813A' AS BIZ_AREA_GROUP,
		"813A" AS BIZ_AREA_STATUS,
		UPDATE_DATE_813A AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'THU' AS DAY_WEEK,
		THU AS STATUS,
		'813A' AS BIZ_AREA_GROUP,
		"813A" AS BIZ_AREA_STATUS,
		UPDATE_DATE_813A AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'FRI' AS DAY_WEEK,
		FRI AS STATUS,
		'813A' AS BIZ_AREA_GROUP,
		"813A" AS BIZ_AREA_STATUS,
		UPDATE_DATE_813A AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'MON' AS DAY_WEEK,
		MON AS STATUS,
		'860A' AS BIZ_AREA_GROUP,
		"860A" AS BIZ_AREA_STATUS,
		UPDATE_DATE_860A AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'TUE' AS DAY_WEEK,
		TUE AS STATUS,
		'860A' AS BIZ_AREA_GROUP,
		"860A" AS BIZ_AREA_STATUS,
		UPDATE_DATE_860A AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'WED' AS DAY_WEEK,
		WED AS STATUS,
		'860A' AS BIZ_AREA_GROUP,
		"860A" AS BIZ_AREA_STATUS,
		UPDATE_DATE_860A AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'THU' AS DAY_WEEK,
		THU AS STATUS,
		'860A' AS BIZ_AREA_GROUP,
		"860A" AS BIZ_AREA_STATUS,
		UPDATE_DATE_860A AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE))
UNION ALL
	SELECT
		PROCESS,
		SUB_PROCESS,
		PIC,
		'FRI' AS DAY_WEEK,
		FRI AS STATUS,
		'860A' AS BIZ_AREA_GROUP,
		"860A" AS BIZ_AREA_STATUS,
		UPDATE_DATE_860A AS UPDATE_DATE,
		"WEEK",
		CURRENT_DATE AS DT_FOTO
	FROM
		OW_LAO.VW_LAO_SALES_DEDUCTION_DAILY_MONITORING_MAPPING_STATUS
	WHERE
		"WEEK" = CONCAT('W', WEEK(CURRENT_DATE));
END