CREATE PROCEDURE OW_LAO.PROC_D2C_NERP_GSCM_PSI
LANGUAGE SQLSCRIPT as
BEGIN
--Truncar Tabela Fato : FT_D2C_NERP_GSCM_PSI
TRUNCATE TABLE OW_LAO.FT_D2C_NERP_GSCM_PSI;
--Inserir os dados na Fato : FT_D2C_NERP_GSCM_PSI
INSERT INTO OW_LAO.FT_D2C_NERP_GSCM_PSI
--SELECT  INVENTORY.* FROM (
SELECT  'Inventory' AS SOURCE
        ,DS.SUBSIDIARY
	,DP.PRODUCT_GROUP_1 AS DIMPROD_PRODUCT_GROUP
	,DP."DIVISION" AS DIMPROD_DIVISION
	,DP.PRODUCT_1 AS DIMPROD_PRODUCT       
        ,DP.SEDA_BU_ESTORE
	,DP.SEDA_DIVISION_ESTORE
	,DP.SEDA_CATEGORY_ESTORE
	,DP.SEDA_FAMILY_ESTORE
	,DP.SEDA_DESC_ESTORE
	,ONZDASO.MATERIAL AS SKU
	,MSL.INV_TYPE
	,DP2.ORIGIN AS PLANT_NAME
	,DP2.PLANT_CODE AS PLANT
	,RDGAOH2.PLANT_DESC
	,ONZDASO.STORAGE_LOCATION AS STORAGE 
	,RDGAOH.S_LOC_DESC 
	,SUM(ON_HAND) AS QTY 
	,DC.YYYYWW AS "YEAR_WEEK"
	,DC.YYYYMMDD AS "DATE"
	,NOW() AS "LOAD_DATE"	
		
     FROM OW_LAO.ODS_NERP_ZRMMJ310410_DISPLAY_AVALIABLE_STOCK_OVERVIEW ONZDASO
LEFT JOIN OW_MD.DIM_SUBSIDIARY DS ON  (ONZDASO.COMPANY = DS.COMPANY_CODE)
LEFT JOIN OW_MD.DIM_PRODUCT DP ON (ONZDASO.MATERIAL = DP.SKU)
LEFT JOIN OW_MD.DIM_CALENDAR DC ON
	(TO_DATE((RIGHT(SUBSTR_BEFORE(UPPER(ONZDASO.FILE_NAME),'_MORNING.XLSX'),8)),'DDMMYYYY') = DC.YYYYMMDD )
LEFT JOIN OW_MD.DIM_PLANT DP2 ON (ONZDASO.PLANT = DP2.PLANT_CODE)
LEFT JOIN OW_MD.MAP_STORAGE_LOCATION MSL ON (ONZDASO.PLANT = MSL.PLANT  AND ONZDASO.STORAGE_LOCATION  = MSL.S_LOC)
LEFT JOIN (SELECT DISTINCT ONZOT.PLANT, ONZOT.STORAGE_LOCATION  FROM OW_LAO.ODS_NERP_ZLLEJ50090_OUTBOUND_TRACKING ONZOT WHERE  (
		(ONZOT.SALES_ORG NOT IN ('8101','3A01','8105','8107','8109') AND ONZOT.SO_TYPE = 'YS10') 
	    OR  (ONZOT.SALES_ORG IN ('8101','3A01','8105','8107','8109') AND ONZOT.SO_TYPE = 'YN01')
	)
		AND ONZOT.DO_TYPE = 'ZND1' ) DONZOT
ON (ONZDASO.PLANT= DONZOT.PLANT AND ONZDASO.STORAGE_LOCATION = DONZOT.STORAGE_LOCATION)
LEFT JOIN (SELECT DISTINCT RDGAOH.PLANT, RDGAOH.STORAGE,RDGAOH.S_LOC_DESC FROM OW_LAO.RAW_DATA_GSCM_ACTUAL_ON_HAND RDGAOH) RDGAOH ON (ONZDASO.STORAGE_LOCATION = RDGAOH.STORAGE AND ONZDASO.PLANT = RDGAOH.PLANT)
LEFT JOIN (SELECT DISTINCT RDGAOH2.PLANT,RDGAOH2.PLANT_DESC FROM OW_LAO.RAW_DATA_GSCM_ACTUAL_ON_HAND RDGAOH2)RDGAOH2 ON (ONZDASO.PLANT = RDGAOH2.PLANT)
WHERE UPPER(ONZDASO.FILE_NAME) LIKE '%MORNING%'
AND DONZOT.PLANT IS NOT NULL AND DONZOT.STORAGE_LOCATION IS NOT NULL  --FILTRAR APENAS D2C
GROUP BY 
	DS.SUBSIDIARY
	,DP.PRODUCT_GROUP_1
	,DP."DIVISION"
	,DP.PRODUCT_1
	,DP.SEDA_BU_ESTORE
	,DP.SEDA_DIVISION_ESTORE
	,DP.SEDA_CATEGORY_ESTORE
	,DP.SEDA_FAMILY_ESTORE
	,DP.SEDA_DESC_ESTORE
	,ONZDASO.MATERIAL
	,MSL.INV_TYPE
	,DP2.ORIGIN
	,DP2.PLANT_CODE
	,RDGAOH2.PLANT_DESC
	,ONZDASO.STORAGE_LOCATION
	,RDGAOH.S_LOC_DESC 
	,DC.YYYYWW
	,DC.YYYYMMDD
	,NOW()
/*SELECT  'Inventory_Available' AS SOURCE
        ,IFNULL(DS.SUBSIDIARY, RDGAOH.ORG_2) AS "SUBSIDIARY" 
	,DP.PRODUCT_GROUP_1 AS DIMPROD_PRODUCT_GROUP
	,DP."DIVISION" AS DIMPROD_DIVISION
	,DP.PRODUCT_1 AS DIMPROD_PRODUCT       
        ,DP.SEDA_BU_ESTORE
	,DP.SEDA_DIVISION_ESTORE
	,DP.SEDA_CATEGORY_ESTORE
	,DP.SEDA_FAMILY_ESTORE
	,DP.SEDA_DESC_ESTORE
	,RDGAOH.ITEM AS SKU
	,MSL.INV_TYPE
	,DP2.ORIGIN AS PLANT_NAME
	,IFNULL(DP2.PLANT_CODE, RDGAOH.PLANT) AS PLANT
	,RDGAOH.PLANT_DESC
	,RDGAOH.STORAGE 
	,RDGAOH.S_LOC_DESC 
	,SUM(RDGAOH.AVAILABLE) AS QTY 
	,DC.YYYYWW AS "YEAR_WEEK"
	,DC.YYYYMMDD AS "DATE"
	,NOW() AS "LOAD_DATE"	
		
     FROM OW_LAO.RAW_DATA_GSCM_ACTUAL_ON_HAND RDGAOH 
LEFT JOIN OW_MD.DIM_SUBSIDIARY DS ON  
	((CASE
		WHEN RDGAOH.ORG_2 = 'SELA-MI' THEN 'SELA-M'
		WHEN RDGAOH.ORG_2 = 'SELA-PA' THEN 'SELA-P'
		ELSE RDGAOH.ORG_2
	END) = DS.SUBSIDIARY)
LEFT JOIN OW_MD.DIM_PRODUCT DP ON (RDGAOH.ITEM = DP.SKU)
LEFT JOIN OW_MD.DIM_CALENDAR DC ON
	(TO_DATE((RIGHT(SUBSTR_BEFORE(UPPER(RDGAOH.FILE_NAME), '.XLSX'), 8)), 'YYYYMMDD') = DC.YYYYMMDD )
LEFT JOIN OW_MD.DIM_PLANT DP2 ON (RDGAOH.PLANT = DP2.PLANT_CODE)
LEFT JOIN OW_MD.MAP_STORAGE_LOCATION MSL ON (RDGAOH.PLANT = MSL.PLANT  AND RDGAOH.STORAGE  = MSL.S_LOC)
LEFT JOIN (SELECT DISTINCT ONZOT.PLANT, ONZOT.STORAGE_LOCATION  FROM OW_LAO.ODS_NERP_ZLLEJ50090_OUTBOUND_TRACKING ONZOT WHERE  (
		(ONZOT.SALES_ORG NOT IN ('8101','3A01','8105','8107','8109') AND ONZOT.SO_TYPE = 'YS10') 
	    OR  (ONZOT.SALES_ORG IN ('8101','3A01','8105','8107','8109') AND ONZOT.SO_TYPE = 'YN01')
	)
	AND ONZOT.DO_TYPE = 'ZND1' ) DONZOT
ON (RDGAOH.PLANT= DONZOT.PLANT AND RDGAOH.STORAGE = DONZOT.STORAGE_LOCATION)
WHERE DONZOT.PLANT IS NOT NULL AND DONZOT.STORAGE_LOCATION IS NOT NULL  --FILTRAR APENAS D2C
GROUP BY 
	IFNULL(DS.SUBSIDIARY, RDGAOH.ORG_2)
	,DP.PRODUCT_GROUP_1
	,DP."DIVISION"
	,DP.PRODUCT_1
	,DP.SEDA_BU_ESTORE
	,DP.SEDA_DIVISION_ESTORE
	,DP.SEDA_CATEGORY_ESTORE
	,DP.SEDA_FAMILY_ESTORE
	,DP.SEDA_DESC_ESTORE
	,RDGAOH.ITEM
	,MSL.INV_TYPE
	,DP2.ORIGIN
	,IFNULL(DP2.PLANT_CODE, RDGAOH.PLANT)
	,RDGAOH.PLANT_DESC
	,RDGAOH.STORAGE 
	,RDGAOH.S_LOC_DESC 
	,DC.YYYYWW
	,DC.YYYYMMDD
	,NOW()
--) AS INVENTORY	*/
UNION ALL
--SELECT GR.* FROM (
SELECT  'GR' AS SOURCE
        ,DS.SUBSIDIARY AS "SUBSIDIARY" 
	,DP.PRODUCT_GROUP_1 AS DIMPROD_PRODUCT_GROUP
	,DP."DIVISION" AS DIMPROD_DIVISION
	,DP.PRODUCT_1 AS DIMPROD_PRODUCT     
	,DP.SEDA_BU_ESTORE
	,DP.SEDA_DIVISION_ESTORE
	,DP.SEDA_CATEGORY_ESTORE
	,DP.SEDA_FAMILY_ESTORE
	,DP.SEDA_DESC_ESTORE
	,ONMGF.MATERIAL AS SKU
	,MSL.INV_TYPE	
	,DP2.ORIGIN AS PLANT_NAME
	,IFNULL(DP2.PLANT_CODE, ONMGF.PLANT) AS PLANT
	,RDGAOHP.PLANT_DESC
	,ONMGF.STORAGE_LOCATION AS STORAGE
	--,RDGAOHSL.S_LOC_DESC 
	,RDGAOH.S_LOC_DESC 
	,SUM(TO_INTEGER(ONMGF.QUANTITY)) AS QTY
	,DC.YYYYWW
	,DC.YYYYMMDD
	,NOW() AS "LOAD_DATE"		
	
	FROM OW_LAO.ODS_NERP_MB51_GR_FOLDER ONMGF 
LEFT JOIN  OW_MD.DIM_PRODUCT DP ON (ONMGF.MATERIAL = DP.SKU)
LEFT JOIN OW_MD.DIM_CALENDAR DC ON (TO_VARCHAR(TO_DATE(ONMGF.ENTRY_DATE, 'MM/DD/YYYY'), 'YYYYMMDD') = DC.YYYYMMDD)
LEFT JOIN OW_MD.DIM_PLANT DP2 ON (ONMGF.PLANT = DP2.PLANT_CODE)
LEFT JOIN OW_MD.DIM_SUBSIDIARY DS ON (REPLACE(REPLACE(REPLACE(SUBSTR_BEFORE(ONMGF.NAME_1,']'),'[',''),'DA-M','DA'),'-S','') = REPLACE(SUBSTR_BEFORE(DS.SALES_ORG_NAME,']'),'[','') )  
	/*((CASE
	 * TO_VARCHAR(TO_DATE(ONMGF.ENTRY_DATE, 'MM/DD/YYYY'), 'YYYYMMDD')
		WHEN RDGAOHP.ORG_2 = 'SELA-MI' THEN 'SELA-M'
		WHEN RDGAOHP.ORG_2 = 'SELA-PA' THEN 'SELA-P'
		ELSE RDGAOHP.ORG_2
	END) = DS.SUBSIDIARY)*/
--LEFT JOIN OW_LAO.RAW_DATA_GSCM_ACTUAL_ON_HAND RDGAOH  ON (DP2.PLANT_CODE = RDGAOH.PLANT)
LEFT JOIN (SELECT DISTINCT RDGAOH.ORG_2, RDGAOH.PLANT, RDGAOH.PLANT_DESC FROM OW_LAO.RAW_DATA_GSCM_ACTUAL_ON_HAND RDGAOH WHERE RDGAOH.PLANT IS NOT NULL) RDGAOHP ON (ONMGF.PLANT = RDGAOHP.PLANT)
/*
LEFT JOIN (SELECT DISTINCT ORG_2, STORAGE, S_LOC_DESC FROM (
		SELECT ORG_2, STORAGE, S_LOC_DESC, ROW_NUMBER() OVER (PARTITION BY ORG_2,STORAGE) AS ROW_NUM 
		FROM (
			SELECT DISTINCT RDGAOH.ORG_2, RDGAOH.STORAGE, RDGAOH.S_LOC_DESC, COUNT(*)
			   FROM OW_LAO.RAW_DATA_GSCM_ACTUAL_ON_HAND RDGAOH WHERE RDGAOH.S_LOC_DESC IS NOT NULL
			   GROUP BY RDGAOH.ORG_2, RDGAOH.STORAGE, RDGAOH.S_LOC_DESC
			ORDER BY RDGAOH.STORAGE ASC, COUNT(*) DESC --Ordenar por quantidade de Registros por código
			)
			ORDER BY STORAGE, 4 ASC 
	) WHERE ROW_NUM = 1) RDGAOHSL ON (ONMGF.STORAGE_LOCATION = RDGAOHSL.STORAGE
					AND (CASE
						WHEN RDGAOHSL.ORG_2 = 'SELA-MI' THEN 'SELA-M'
						WHEN RDGAOHSL.ORG_2 = 'SELA-PA' THEN 'SELA-P'
						ELSE RDGAOHSL.ORG_2
					END) = DS.SUBSIDIARY) --Subselect para mapear apenas um STORAGE
*/					
LEFT JOIN (SELECT DISTINCT RDGAOH.PLANT, RDGAOH.STORAGE,RDGAOH.S_LOC_DESC FROM OW_LAO.RAW_DATA_GSCM_ACTUAL_ON_HAND RDGAOH) RDGAOH ON (ONMGF.STORAGE_LOCATION = RDGAOH.STORAGE AND ONMGF.PLANT = RDGAOH.PLANT)					
LEFT JOIN OW_MD.MAP_STORAGE_LOCATION MSL ON (ONMGF.PLANT = MSL.PLANT  AND ONMGF.STORAGE_LOCATION  = MSL.S_LOC)
GROUP BY 
	DS.SUBSIDIARY
	,DP.PRODUCT_GROUP_1
	,DP."DIVISION"
	,DP.PRODUCT_1
	,DP.SEDA_BU_ESTORE
	,DP.SEDA_DIVISION_ESTORE
	,DP.SEDA_CATEGORY_ESTORE
	,DP.SEDA_FAMILY_ESTORE
	,DP.SEDA_DESC_ESTORE
	,ONMGF.MATERIAL
	,MSL.INV_TYPE
	,DP2.ORIGIN 
	,IFNULL(DP2.PLANT_CODE, ONMGF.PLANT)
	,RDGAOHP.PLANT_DESC
	,ONMGF.STORAGE_LOCATION
	--,RDGAOHSL.S_LOC_DESC 
	,RDGAOH.S_LOC_DESC 
	,DC.YYYYWW
	,DC.YYYYMMDD
	,NOW()
--) AS GR
UNION ALL
--SELECT GI.* FROM (
SELECT  'GI' AS SOURCE
        ,IFNULL(DS.SUBSIDIARY, ONZOT.SALES_ORG) AS "SUBSIDIARY" 
	,DP.PRODUCT_GROUP_1 AS DIMPROD_PRODUCT_GROUP
	,DP."DIVISION" AS DIMPROD_DIVISION
	,DP.PRODUCT_1 AS DIMPROD_PRODUCT 
	,DP.SEDA_BU_ESTORE
	,DP.SEDA_DIVISION_ESTORE
	,DP.SEDA_CATEGORY_ESTORE
	,DP.SEDA_FAMILY_ESTORE
	,DP.SEDA_DESC_ESTORE
	,ONZOT.MATERIAL AS SKU
	,MSL.INV_TYPE
	,DP2.ORIGIN AS PLANT_NAME
	,IFNULL(DP2.PLANT_CODE, ONZOT.PLANT) AS PLANT
	,RDGAOHP.PLANT_DESC
	,ONZOT.STORAGE_LOCATION AS STORAGE
	--,RDGAOHSL.S_LOC_DESC
	,RDGAOH.S_LOC_DESC
	,SUM(ONZOT.DELIVERY_QTY) AS QTY
	,DC.YYYYWW
	,DC.YYYYMMDD
	,NOW()
FROM OW_LAO.ODS_NERP_ZLLEJ50090_OUTBOUND_TRACKING ONZOT
LEFT JOIN OW_LAO.ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING ONZASOT ON (ONZOT.REFERENCE_DOC_SO_PO = ONZASOT.SALES_DOCUMENT 
							AND ONZOT.MATERIAL = ONZASOT.MATERIAL 
							AND ONZOT.DELIVERY_ITEM = ONZASOT.DELIVERY_ITEM AND ONZOT.DELIVERY_NO = ONZASOT.DELIVERY) 
LEFT JOIN OW_MD.DIM_SUBSIDIARY DS ON (ONZOT.SALES_ORG = DS.SALES_ORG)
LEFT JOIN OW_MD.DIM_PRODUCT DP ON (ONZOT.MATERIAL = DP.SKU)
LEFT JOIN OW_MD.DIM_CALENDAR DC ON (TO_DATE(ONZOT."1ST_GI_DATE") = DC.YYYYMMDD)
LEFT JOIN OW_MD.MAP_STORAGE_LOCATION MSL ON (ONZOT.PLANT = MSL.PLANT  AND ONZOT.STORAGE_LOCATION  = MSL.S_LOC)
LEFT JOIN OW_MD.DIM_PLANT DP2 ON (ONZOT.PLANT = DP2.PLANT_CODE)
LEFT JOIN (SELECT DISTINCT RDGAOH.PLANT, RDGAOH.PLANT_DESC FROM OW_LAO.RAW_DATA_GSCM_ACTUAL_ON_HAND RDGAOH WHERE RDGAOH.PLANT IS NOT NULL) RDGAOHP ON (ONZOT.PLANT = RDGAOHP.PLANT)
/*LEFT JOIN (SELECT DISTINCT ORG_2, STORAGE, S_LOC_DESC FROM (
		SELECT ORG_2, STORAGE, S_LOC_DESC, ROW_NUMBER() OVER (PARTITION BY ORG_2,STORAGE) AS ROW_NUM 
		FROM (
			SELECT DISTINCT RDGAOH.ORG_2, RDGAOH.STORAGE, RDGAOH.S_LOC_DESC, COUNT(*)
			   FROM OW_LAO.RAW_DATA_GSCM_ACTUAL_ON_HAND RDGAOH WHERE RDGAOH.S_LOC_DESC IS NOT NULL
			   GROUP BY RDGAOH.ORG_2, RDGAOH.STORAGE, RDGAOH.S_LOC_DESC
			ORDER BY RDGAOH.STORAGE ASC, COUNT(*) DESC --Ordenar por quantidade de Registros por código
			)
			ORDER BY STORAGE, 4 ASC 
	) WHERE ROW_NUM = 1) RDGAOHSL ON (ONZOT.STORAGE_LOCATION = RDGAOHSL.STORAGE
					AND (CASE
						WHEN RDGAOHSL.ORG_2 = 'SELA-MI' THEN 'SELA-M'
						WHEN RDGAOHSL.ORG_2 = 'SELA-PA' THEN 'SELA-P'
						ELSE RDGAOHSL.ORG_2
					END) = DS.SUBSIDIARY) --Subselect para mapear apenas um STORAGE
*/
LEFT JOIN (SELECT DISTINCT RDGAOH.PLANT, RDGAOH.STORAGE,RDGAOH.S_LOC_DESC FROM OW_LAO.RAW_DATA_GSCM_ACTUAL_ON_HAND RDGAOH) RDGAOH ON (ONZOT.STORAGE_LOCATION = RDGAOH.STORAGE AND ONZOT.PLANT = RDGAOH.PLANT)
WHERE 
ONZOT."1ST_GI_DATE" IS NOT NULL
AND ONZOT.SO_TYPE = 'YS10'
AND ONZOT.DO_TYPE = 'ZND1'
AND ONZASOT.REJECT_REASON IS NULL 
AND ONZASOT.REJECT_REASON_1 IS NULL 
GROUP BY 
	IFNULL(DS.SUBSIDIARY, ONZOT.SALES_ORG)
	,DP.PRODUCT_GROUP_1
	,DP."DIVISION"
	,DP.PRODUCT_1
	,DP.SEDA_BU_ESTORE
	,DP.SEDA_DIVISION_ESTORE
	,DP.SEDA_CATEGORY_ESTORE
	,DP.SEDA_FAMILY_ESTORE
	,DP.SEDA_DESC_ESTORE
	,ONZOT.MATERIAL
	,MSL.INV_TYPE
	,DP2.ORIGIN 
	,IFNULL(DP2.PLANT_CODE, ONZOT.PLANT)
	,RDGAOHP.PLANT_DESC
	,ONZOT.STORAGE_LOCATION
	--,RDGAOHSL.S_LOC_DESC
	,RDGAOH.S_LOC_DESC
	,DC.YYYYWW
	,DC.YYYYMMDD
	,NOW()
/*UNION ALL 
SELECT  'Inventory_Unavailable' AS SOURCE
        ,IFNULL(DS.SUBSIDIARY, RDGAOH.ORG_2) AS "SUBSIDIARY" 
	,DP.PRODUCT_GROUP_1 AS DIMPROD_PRODUCT_GROUP
	,DP."DIVISION" AS DIMPROD_DIVISION
	,DP.PRODUCT_1 AS DIMPROD_PRODUCT       
        ,DP.SEDA_BU_ESTORE
	,DP.SEDA_DIVISION_ESTORE
	,DP.SEDA_CATEGORY_ESTORE
	,DP.SEDA_FAMILY_ESTORE
	,DP.SEDA_DESC_ESTORE
	,RDGAOH.ITEM AS SKU
	,MSL.INV_TYPE
	,DP2.ORIGIN AS PLANT_NAME
	,IFNULL(DP2.PLANT_CODE, RDGAOH.PLANT) AS PLANT
	,RDGAOH.PLANT_DESC
	,RDGAOH.STORAGE 
	,RDGAOH.S_LOC_DESC 
	,SUM(RDGAOH.UNAVAILABLE) AS QTY
	,DC.YYYYWW AS "YEAR_WEEK"
	,DC.YYYYMMDD AS "DATE"
	,NOW() AS "LOAD_DATE"	
		
     FROM OW_LAO.RAW_DATA_GSCM_ACTUAL_ON_HAND RDGAOH 
LEFT JOIN OW_MD.DIM_SUBSIDIARY DS ON  
	((CASE
		WHEN RDGAOH.ORG_2 = 'SELA-MI' THEN 'SELA-M'
		WHEN RDGAOH.ORG_2 = 'SELA-PA' THEN 'SELA-P'
		ELSE RDGAOH.ORG_2
	END) = DS.SUBSIDIARY)
LEFT JOIN OW_MD.DIM_PRODUCT DP ON (RDGAOH.ITEM = DP.SKU)
LEFT JOIN OW_MD.DIM_CALENDAR DC ON
	(TO_DATE((RIGHT(SUBSTR_BEFORE(UPPER(RDGAOH.FILE_NAME), '.XLSX'), 8)), 'YYYYMMDD') = DC.YYYYMMDD )
LEFT JOIN OW_MD.DIM_PLANT DP2 ON (RDGAOH.PLANT = DP2.PLANT_CODE)
LEFT JOIN OW_MD.MAP_STORAGE_LOCATION MSL ON (RDGAOH.PLANT = MSL.PLANT  AND RDGAOH.STORAGE  = MSL.S_LOC)
LEFT JOIN (SELECT DISTINCT ONZOT.PLANT, ONZOT.STORAGE_LOCATION  FROM OW_LAO.ODS_NERP_ZLLEJ50090_OUTBOUND_TRACKING ONZOT WHERE  (
		(ONZOT.SALES_ORG NOT IN ('8101','3A01','8105','8107','8109') AND ONZOT.SO_TYPE = 'YS10') 
	    OR  (ONZOT.SALES_ORG IN ('8101','3A01','8105','8107','8109') AND ONZOT.SO_TYPE = 'YN01')
	)
	AND ONZOT.DO_TYPE = 'ZND1' ) DONZOT
ON (RDGAOH.PLANT= DONZOT.PLANT AND RDGAOH.STORAGE = DONZOT.STORAGE_LOCATION)
WHERE DONZOT.PLANT IS NOT NULL AND DONZOT.STORAGE_LOCATION IS NOT NULL  --FILTRAR APENAS D2C
GROUP BY 
	IFNULL(DS.SUBSIDIARY, RDGAOH.ORG_2)
	,DP.PRODUCT_GROUP_1
	,DP."DIVISION"
	,DP.PRODUCT_1
	,DP.SEDA_BU_ESTORE
	,DP.SEDA_DIVISION_ESTORE
	,DP.SEDA_CATEGORY_ESTORE
	,DP.SEDA_FAMILY_ESTORE
	,DP.SEDA_DESC_ESTORE
	,RDGAOH.ITEM
	,MSL.INV_TYPE
	,DP2.ORIGIN
	,IFNULL(DP2.PLANT_CODE, RDGAOH.PLANT)
	,RDGAOH.PLANT_DESC
	,RDGAOH.STORAGE 
	,RDGAOH.S_LOC_DESC 
	,DC.YYYYWW
	,DC.YYYYMMDD
	,NOW()
--ORDER BY MSL.INV_TYPE DESC*/
--) AS GI 
;
END