CREATE PROCEDURE PROC_CRAWLING_AP1_NPC_SITE_MAPPING_MERGE_AUTOMATIC
LANGUAGE SQLSCRIPT as
BEGIN
--==============================================================
--INPUT DO ARQUIVO
/*DESTINO  tabela OW_LAO.INPUT_CRAWLING_AP1_NPC_SITE_MAPPING*/
MERGE INTO OW_LAO.INPUT_CRAWLING_AP1_NPC_SITE_MAPPING AS Destino
/*ORIGEM dos dados vem da tabela OW_LAO.INPUT_CRAWLING_AP1_NPC_SITE_MAPPING_TMP (job -> J_LAO_INPUT_CRAWLING_AP1_NPC_SITE_URL_MAPPING)
onde o SITE_URL são iguais aos da tabela OW_LAO.ODS_CRAWLING_AP1_NPC_PRODUCT_DETAIL*/
USING 
(SELECT MIN(REPLACE(ITEM_ID,'.0',''))  AS MODEL_MAPPING ,
	MIN(AP2) AS AP2,
	MIN(COUNTRY) AS COUNTRY,
	MIN(COMPANY_NAME) AS COMPANY_NAME,
	MIN(BRAND_NM) AS BRAND_NM,
	MIN(DESCRIPTION) AS DESCRIPTION ,
	MIN(MODEL_REF_1) AS MODEL_REF_1,
	MIN(MODEL_REF_2) AS MODEL_REF_2,
	MIN(MODEL_REF_3) AS MODEL_REF_3,
	MIN(MODEL_REF_4) AS MODEL_REF_4,
	SITE_URL ,
	MIN(LOWER_POSITION) AS LOWER_POSITION,
	MIN(CRAWLING_QTY) AS CRAWLING_QTY,
	MIN(FILE_NAME) AS FILE_NAME,
	MIN(LOAD_DATE) AS LOAD_DATE FROM OW_LAO.INPUT_CRAWLING_AP1_NPC_SITE_MAPPING_TMP WHERE SITE_URL IN (
SELECT DISTINCT PROD_HREF FROM OW_LAO.ODS_CRAWLING_AP1_NPC_PRODUCT_DETAIL
) GROUP BY SITE_URL) AS Origem
--Condição: O produto existe nas 2 tabelas e o cliente também
ON (Destino.SITE_URL = Origem.SITE_URL)
--Se a condição for obedecida, ou seja, existem registros nas duas tabelas
WHEN MATCHED THEN
    UPDATE SET Destino.MODEL_MAPPING = Origem.MODEL_MAPPING ,
	Destino.AP2 = Origem.AP2,
	Destino.COUNTRY = Origem.COUNTRY,
	Destino.COMPANY_NAME = Origem.COMPANY_NAME,
	Destino.BRAND_NM = Origem.BRAND_NM,
	Destino.DESCRIPTION = Origem.DESCRIPTION,
	Destino.MODEL_REF_1 = Origem.MODEL_REF_1,
	Destino.MODEL_REF_2 = Origem.MODEL_REF_2,
	Destino.MODEL_REF_3 = Origem.MODEL_REF_3,
	Destino.MODEL_REF_4 = Origem.MODEL_REF_4,
	Destino.LOWER_POSITION = Origem.LOWER_POSITION,
	Destino.CRAWLING_QTY = Origem.CRAWLING_QTY,
	Destino.FILE_NAME = Origem.FILE_NAME,
	Destino.LOAD_DATE = Origem.LOAD_DATE,
	Destino.MAPPING_TYPE = 'MANUAL',
	Destino.CREATED_DATE = Destino.CREATED_DATE,
	Destino.UPDATED_DATE = CURRENT_DATE 
--Se a condição não foi obedecida porque o registro não existe na tabela de destino, insere os dados da tabela Origem
WHEN NOT MATCHED THEN
   INSERT VALUES (Origem.MODEL_MAPPING ,
	Origem.AP2,
	Origem.COUNTRY,
	Origem.COMPANY_NAME,
	Origem.BRAND_NM,
	Origem.DESCRIPTION,
	Origem.MODEL_REF_1,
	Origem.MODEL_REF_2,
	Origem.MODEL_REF_3,
	Origem.MODEL_REF_4,
	Origem.SITE_URL,
	Origem.LOWER_POSITION,
	Origem.CRAWLING_QTY,
	Origem.FILE_NAME,
	Origem.LOAD_DATE,
	'MANUAL',
	CURRENT_DATE,
	CURRENT_DATE);
--==================================================================
--==================================================================
--INPUT AUTOMATICO
--======== URL COM MODEL_MAPPING ENCONTRADO
/*DESTINO  tabela OW_LAO.INPUT_CRAWLING_AP1_NPC_SITE_MAPPING*/
MERGE INTO OW_LAO.INPUT_CRAWLING_AP1_NPC_SITE_MAPPING AS Destino
/*ORIGEM dos dados vem da view OW_LAO.VW_CRAWLING_AP1_NPC_SITE_SPEC_MAPPING_AUTOMATIC*/
USING 
(SELECT * FROM OW_LAO.VW_CRAWLING_AP1_NPC_SITE_SPEC_MAPPING_AUTOMATIC) AS Origem
--Condição: O produto existe nas 2 tabelas, cliente também e o ORIGEM.MODEL_MAPPING  não é nulo 
ON (Destino.SITE_URL = Origem.SITE_URL AND ORIGEM.MODEL_MAPPING IS NOT NULL)
--Se a condição for obedecida, ou seja, existem registros nas duas tabelas
-- UPDATE DOS REGISTROS ENCONTRADOS NA INPUT COM MODEL_MAPPING NULO OU MAPPING_TYPE <> MANUAL
WHEN MATCHED THEN
    UPDATE SET 
    Destino.MODEL_MAPPING = Origem.MODEL_MAPPING ,
	Destino.AP2 = Origem.SUB,
	Destino.COUNTRY = Origem.COUNTRY,
	Destino.COMPANY_NAME = Origem.COMPANY_NAME,
	Destino.BRAND_NM = Origem.BRAND_NM,
	Destino.DESCRIPTION = Origem.DESCRIPTION,
	Destino.MODEL_REF_1 = Origem.MODEL_REF_1,
	Destino.MODEL_REF_2 = Origem.MODEL_REF_2,
	Destino.MODEL_REF_3 = Origem.MODEL_REF_3,
	Destino.MODEL_REF_4 = Origem.MODEL_REF_4,
	Destino.LOWER_POSITION = Origem.LOWER_POSITION,
	Destino.CRAWLING_QTY = Origem.CRAWLING_QTY,
	Destino.FILE_NAME = Destino.FILE_NAME,
	Destino.LOAD_DATE = Destino.LOAD_DATE,
	Destino.MAPPING_TYPE = Origem.MAPPING_ORIGEM,
	Destino.CREATED_DATE = Destino.CREATED_DATE,
	Destino.UPDATED_DATE = CURRENT_DATE;
	
--======== URL SEM MODEL_MAPPING ENCONTRADO ATUALIZANDO SOMENTE DADOS
/*DESTINO tabela OW_LAO.INPUT_CRAWLING_AP1_NPC_SITE_MAPPING*/
MERGE INTO OW_LAO.INPUT_CRAWLING_AP1_NPC_SITE_MAPPING AS Destino
/*ORIGEM dos dados vem da view OW_LAO.VW_CRAWLING_AP1_NPC_SITE_SPEC_MAPPING_AUTOMATIC*/
USING 
(SELECT * FROM OW_LAO.VW_CRAWLING_AP1_NPC_SITE_SPEC_MAPPING_AUTOMATIC) AS Origem
--Condição: O produto existe nas 2 tabelas, cliente também e o ORIGEM.MODEL_MAPPING é nulo 
ON (Destino.SITE_URL = Origem.SITE_URL AND ORIGEM.MODEL_MAPPING IS NULL)
--Se a condição for obedecida, ou seja, existem registros nas duas tabelas
-- UPDATE DOS REGISTROS ENCONTRADOS NA INPUT COM MODEL_MAPPING NULO OU MAPPING_TYPE <> MANUAL
WHEN MATCHED THEN
    UPDATE SET 
	Destino.AP2 = Origem.SUB,
	Destino.COUNTRY = Origem.COUNTRY,
	Destino.COMPANY_NAME = Origem.COMPANY_NAME,
	Destino.BRAND_NM = Origem.BRAND_NM,
	Destino.DESCRIPTION = Origem.DESCRIPTION,
	Destino.LOWER_POSITION = Origem.LOWER_POSITION,
	Destino.CRAWLING_QTY = Origem.CRAWLING_QTY,
	Destino.UPDATED_DATE = CURRENT_DATE;
--======== NOVA URL ENCONTRADA NO RPA SENDO INSERIDA NA INPUT
/*DESTINO tabela OW_LAO.INPUT_CRAWLING_AP1_NPC_SITE_MAPPING*/
MERGE INTO OW_LAO.INPUT_CRAWLING_AP1_NPC_SITE_MAPPING AS Destino
/*ORIGEM dos dados vem da view OW_LAO.VW_CRAWLING_AP1_NPC_SITE_SPEC_MAPPING_AUTOMATIC*/
USING 
(SELECT * FROM OW_LAO.VW_CRAWLING_AP1_NPC_SITE_SPEC_MAPPING_AUTOMATIC) AS Origem
--Condição: O produto existe nas 2 tabelas e o cliente também
ON (Destino.SITE_URL = Origem.SITE_URL)
--Se a condição NÃO foi obedecida porque o registro não existe na tabela de destino
WHEN NOT MATCHED THEN
   INSERT VALUES (Origem.MODEL_MAPPING , 
	Origem.SUB,
	Origem.COUNTRY,
	Origem.COMPANY_NAME,
	Origem.BRAND_NM, 
	Origem.DESCRIPTION,
	Origem.MODEL_REF_1,
	Origem.MODEL_REF_2,
	Origem.MODEL_REF_3,
	Origem.MODEL_REF_4,
	Origem.SITE_URL,
	Origem.LOWER_POSITION,
	Origem.CRAWLING_QTY,
	NULL,
	NULL,
	Origem.MAPPING_ORIGEM,
	CURRENT_DATE,
	CURRENT_DATE);
	
--==================================================================
--==================================================================
-- TRUNCATE TABLE "OW_LAO"."MP_CRAWLING_AP1_NPC_SITE_SPEC_MAPPING"
TRUNCATE TABLE "OW_LAO"."MP_CRAWLING_AP1_NPC_SITE_SPEC_MAPPING";
--POPULAR TABELA "OW_LAO"."MP_CRAWLING_AP1_NPC_SITE_SPEC_MAPPING"
INSERT INTO "OW_LAO"."MP_CRAWLING_AP1_NPC_SITE_SPEC_MAPPING"
(    "MAPPING_ORIGEM",
	 "MODEL_MAPPING",
	 "SITE_URL",
	 "MODEL",
	 "SEGMENTS",
	 "ULTRA_THIN",
	 "KEYBOARD_TYPE",
	 "DEPTH_MM",
	 "OPERATING_SYSTEM",
	 "HEIGHT_MM",
	 "HARD_DRIVE_TYPE",
	 "STORAGE_IN_GB",
	 "RAM_IN_MB",
	 "WEIGHT_GRAMM",
	 "TOUCHSCREEN",
	 "CSP_MHZ",
	 "DVD_WRITER",
	 "DISTRIBUTION_TYPE",
	 "PROCESSOR_BRAND",
	 "OS_VERSION",
	 "PROCESSOR",
	 "PROCESSOR_NUMBER",
	 "GPU_BRAND",
	 "GPU_MODEL",
	 "CONVERTIBLE",
	 "GAMING_PRODUCTS",
	 "GPU_TYPE",
	 "DESIGN",
	 "DISPLAY_SIZE",
	 "INSTANT_ON",
	 "LOAD_DATE" )  SELECT
	 CASE WHEN S.ITEM_ID/*"S"."MODEL"*/ IS NULL 
THEN NULL 
ELSE "MAPPING_AUTOMATICO"."MAPPING_ORIGEM" 
END AS MAPPING_ORIGEM,
	 COALESCE(S.ITEM_ID/*"S"."MODEL"*/,
	'NÃO MAPEADO') AS MODEL_MAPPING,
	 "MAPPING_AUTOMATICO"."SITE_URL" ,
	 "S"."MODEL",
	 "S"."SEGMENTS",
	 "S"."ULTRA_THIN",
	 "S"."KEYBOARD_TYPE",
	 "S"."DEPTH_MM",
	 "S"."OPERATING_SYSTEM",
	 "S"."HEIGHT_MM",
	 "S"."HARD_DRIVE_TYPE",
	 "S"."STORAGE_IN_GB",
	 "S"."RAM_IN_MB",
	 "S"."WEIGHT_GRAMM",
	 "S"."TOUCHSCREEN",
	 "S"."CSP_MHZ",
	 "S"."DVD_WRITER",
	 "S"."DISTRIBUTION_TYPE",
	 "S"."PROCESSOR_BRAND",
	 "S"."OS_VERSION",
	 "S"."PROCESSOR",
	 "S"."PROCESSOR_NUMBER",
 	 "S"."GPU_BRAND",
	 "S"."GPU_MODEL",
	 "S"."CONVERTIBLE",
	 "S"."GAMING_PRODUCTS",
	 "S"."GPU_TYPE",
	 "S"."DESIGN",
	 "S"."DISPLAY_SIZE",
	 "S"."INSTANT_ON",
	 "S"."LOAD_DATE"
FROM ( SELECT
	 CASE WHEN LENGTH(TRIM(MODEL_MAPPING)) > 0 
	THEN 'MODEL_MAPPING' 
	WHEN LENGTH(TRIM(D.MODEL)) > 0 
	THEN 'REF_1' 
	WHEN LENGTH(TRIM(D.MODEL2)) > 0 
	THEN 'REF_2' 
	WHEN LENGTH(TRIM(D.REF)) > 0 
	THEN 'REF_3' 
	WHEN LENGTH(TRIM(D.REF2)) > 0 
	THEN 'REF_4' 
	ELSE 'NÃO MAPEADO' 
	END AS MAPPING_ORIGEM,
	 CASE WHEN LENGTH(TRIM(MODEL_MAPPING)) > 0 
	THEN MODEL_MAPPING 
	WHEN LENGTH(TRIM(D.MODEL)) > 0 
	THEN SUBSTRING(D.MODEL,0,99) 
	WHEN LENGTH(TRIM(D.MODEL2)) > 0
	THEN SUBSTRING(D.MODEL2,0,99) 
	WHEN LENGTH(TRIM(D.REF)) > 0 
    THEN SUBSTRING(D.REF,0,99) 
	WHEN LENGTH(TRIM(D.REF2)) > 0 
	THEN SUBSTRING(D.REF2,0,99) 
	ELSE NULL 
	END AS MODEL_MAPPING,
	 M.SITE_URL 
	FROM INPUT_CRAWLING_AP1_NPC_SITE_MAPPING AS M 
	INNER JOIN OW_LAO.ODS_CRAWLING_AP1_NPC_PRODUCT_DETAIL AS D ON TRIM(M.SITE_URL) = TRIM(D.PROD_HREF)) AS MAPPING_AUTOMATICO 
LEFT JOIN (SELECT
	 B.* 
	FROM (SELECT
	 ITEM_ID/*"MODEL"*/,
	 MAX(ROW_NUM) as ROW_NUM 
		FROM ( SELECT
	 S.ITEM_ID/*"S"."MODEL"*/,
	 ROW_NUMBER() OVER ( PARTITION BY S.ITEM_ID/*"S"."MODEL"*/) AS ROW_NUM 
			FROM INPUT_CRAWLING_AP1_NPC_SPEC_MAPPING AS S ) 
		GROUP BY ITEM_ID/*"MODEL"*/) AS A 
	INNER JOIN (SELECT
	 S.ITEM_ID,
	 S.MODEL,
	 S.SEGMENTS,
     S.ULTRA_THIN,
     S.KEYBOARD_TYPE,
     S.DEPTH_MM,
     S.OPERATING_SYSTEM,
     S.HEIGHT_MM,
     S.HARD_DRIVE_TYPE,
     S.STORAGE_IN_GB,
     S.RAM_IN_MB,
     S.WEIGHT_GRAMM,
	 S.TOUCHSCREEN,
	 S.CSP_MHZ,
	 S.DVD_WRITER,
	 S.DISTRIBUTION_TYPE,
	 S.PROCESSOR_BRAND,
	 S.OS_VERSION,
	 S.PROCESSOR,
	 S.PROCESSOR_NUMBER,
	 S.GPU_BRAND,
	 S.GPU_MODEL,
	 S.CONVERTIBLE,
	 S.GAMING_PRODUCTS,
	 S.GPU_TYPE,
	 S.DESIGN,
	 S.DISPLAY_SIZE,
	 S.INSTANT_ON,
	 S.LOAD_DATE,
	 ROW_NUMBER() OVER ( PARTITION BY S.ITEM_ID/*"S"."MODEL"*/) AS ROW_NUM 
		from INPUT_CRAWLING_AP1_NPC_SPEC_MAPPING as S) as B on A.ITEM_ID/*"A"."MODEL"*/ = B.ITEM_ID/*"B"."MODEL"*/
	and A.ROW_NUM=B.ROW_NUM) AS S ON TRIM(UPPER(MAPPING_AUTOMATICO.MODEL_MAPPING)) = TRIM(UPPER(S.ITEM_ID/*"S"."MODEL"*/));
--==================================================================
END;