/***********************************************************************************************
CREATED BY : Luciano Mariani
CREATION DATE : 2023-06-29
ALTER BY : Luciano Mariani
ALTER DATE : 2023-10-05
VERSION: 5
	CALL OW_LAO.PROC_D2C_PO_HYBRIS_SALES 
***********************************************************************************************/
CREATE PROCEDURE OW_LAO.PROC_D2C_PO_HYBRIS_SALES 
LANGUAGE SQLSCRIPT
AS
BEGIN
	/*************************************************************
	*						HYBRIS
	*************************************************************/
	/***********************************
	-- INSERE NOVOS DADOS DE PO (HYBRIS)
	***********************************/
	IF EXISTS(
		SELECT TABLE_NAME
		FROM SYS.TABLES
		WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TMP_PO_ORDER_ID_PO_HYBRIS'
	)
	THEN
		DROP TABLE OW_LAO.TMP_PO_ORDER_ID_PO_HYBRIS;
	END IF;
	--CRIA NOVA TATBELA 
	CREATE COLUMN TABLE OW_LAO.TMP_PO_ORDER_ID_PO_HYBRIS AS (
		SELECT *
		FROM (
			SELECT DISTINCT
				 HB.ORDER_ID
				,CASE -- CASO NÃO TENHA NA TABELA É NOVO
					WHEN (KP.ORDER_ID IS NULL) THEN 1
					ELSE 0
				 END AS IS_NEW
				,CASE 
					-- CASO O REGISTRO ESTEJA DESATUALIZADO
					WHEN (HB.UPDATED_AT > KP.KPI_LAST_UPDATE)
						-- OU OS REGISTROS RECENTES - ULTIMOS 180 DIAS
						OR (HB.CREATION_TIMESTAMP BETWEEN ADD_DAYS(CURRENT_TIMESTAMP,-180) AND ADD_DAYS(CURRENT_TIMESTAMP,180)) 
					THEN 1 ELSE 0 
				  END AS IS_UPDATE
			FROM(
					SELECT
						 ORDER_CODE AS ORDER_ID
						,MAX(ORDER_CREATION_DATE) AS CREATION_TIMESTAMP
						,MAX(UPDATED_DATETIME) AS UPDATED_AT
					FROM OW_LAO.ODS_HYBRIS_SALES
					WHERE --TO_DATE(ORDER_CREATION_DATE) BETWEEN p_DATE_INI AND P_DATE_FIM
						YEAR(ORDER_CREATION_DATE) >= 2023
					GROUP BY
						ORDER_CODE
				)HB
				LEFT JOIN ( -- PARA VERIFICAR SE ORDER_ID É NOVA OU ATUALIZAÇÃO
					SELECT ORDER_ID
						  ,MAX(KPI_LAST_UPDATE) AS KPI_LAST_UPDATE
					FROM OW_LAO.TF_D2C_NERP_SALES 
					WHERE "SOURCE" = 'PO'
						AND SUBSIDIARY <> 'SEDA'
						--AND ORIGIN_SYSTEM = 'HYBRIS'
					GROUP BY
						ORDER_ID
				)KP ON HB.ORDER_ID = KP.ORDER_ID
		)
		WHERE 
			IS_NEW = 1
			OR IS_UPDATE = 1
		--WHERE 
		--	KP.ORDER_ID IS NULL -- CASO SEJA NOVO
		--	OR HB.UPDATED_AT > KP.KPI_LAST_UPDATE -- OU CASO O REGISTRO ESTEJA DESATUALIZADO
		--	OR HB.CREATION_TIMESTAMP BETWEEN ADD_DAYS(CURRENT_TIMESTAMP,-180) AND ADD_DAYS(CURRENT_TIMESTAMP,180) -- OU OS REGISTROS RECENTES - ULTIMOS 60 DIAS)
	);
	/***********************************
	-- APAGA DADOS ANTERIORES DE PO HYBRIS
	***********************************/
	DELETE FROM OW_LAO.TF_D2C_NERP_SALES
	WHERE "SOURCE" = 'PO'
		AND SUBSIDIARY <> 'SEDA'
		--AND ORIGIN_SYSTEM = 'HYBRIS'
		AND ORDER_ID IN(
					SELECT DISTINCT ORDER_ID
					FROM OW_LAO.TMP_PO_ORDER_ID_PO_HYBRIS
				)
	;
	/***********************************
	-- INSERE DADOS ATUALIZADOS DE PO HYBRIS
	***********************************/
	INSERT INTO OW_LAO.TF_D2C_NERP_SALES (
		 "SOURCE" 
		, ORIGIN_SYSTEM
		, DATE_REF
		, YYYYWW
		, YYYYMM
		, YYYYQQ
		, PO_CREATION_DATE
		, "PO_WEEK_DAY_NUM"
		, "PO_WEEK_DAY_NAME"
		, "PO_HOUR"
		, SALES_CHANNEL
		, SUBSIDIARY
		--, CHANNEL
		--, SUB_CHANNEL
		--, SALES_CHANNEL_ATTR_1
		--, SALES_CHANNEL_ATTR_2
		, AFFILIATE_ID
		, SKU
		, PDROD_DIVISION
		, PDROD_PRODUCT_GROUP
		, PDROD_PRODUCT
		, PROD_ATTB_1
		, SEDA_BU_ESTORE
		, SEDA_DIVISION_ESTORE
		, SEDA_CATEGORY_ESTORE
		, SEDA_FAMILY_ESTORE
		, SEDA_DESC_ESTORE
		, QTY
		, AMOUNT_LOCAL
		, AMOUNT_USD
		, PRICE_TO
		, AMOUNT_DISCOUNT
		, AMOUNT_SHIPPING
		, ITEM_NAME
		, ORDER_ID
		,"SELECTED_SLA"
		,"WAREHOUSE_ID_GROUP"			
		, MARKETPLACE_ORDER_ID
		, CUSTOMER_PO
		, ENVIRONMENT
		, STORE_ID
		, NAME_STORE
		, "STORE_EMPLOYEE_CPF"
		, CHANNEL_TYPE
		, "O2O_TYPE" -- 020			
		, REFERENCE_CODE_KIT
		, REFERENCE_CODE
		, STATUS_PO
		, AFFILIATE_ID_ADJUSTED
		, AFFILIATE_CHANNEL
		, AFFILIATE_SUB_CHANNEL
		, AFFILIATE_PARTNER_LEVEL
		, GLOBAL_CHANNEL
		, BIZ_TYPE
		, AUDIENCE_TYPE
		
		/********************
		,"ECO_SKUID"
		,"ECO_BRAND"
		,"ECO_BOOST"
		,"ECO_CATEGORY_NAME"
		
		,"TRADE_IN_SKUID"
		,"TRADE_IN_GTI"
		,"TRADE_IN_BOOST"
		,"TRADE_IN_TOTAL"
		,"TRADE_IN_REFID"	
		
		,IS_TRADE_IN
		,TRADE_IN_PRODUCT_NAME
		,TRADE_IN_PRODUCT_PRICE		
		********************/
		,"COUPON"
		, COUNTRY
		, CURRENCY
		, MODEL_TYPE
		, KPI_LAST_UPDATE
	)
	SELECT 
		  'PO' AS SOURCE
		, 'HYBRIS' AS ORIGIN_SYSTEM
		--, TO_DATE(PO.ORDER_CREATION_DATE) AS DATE_REF -- Data da criação do pedido com dia e hora. 
		
		, TO_DATE(
			CASE 
				WHEN SB.SUBSIDIARY IN('SEPR','SAMCOL') THEN
					ADD_SECONDS(CAST(PO.ORDER_CREATION_DATE AS TIMESTAMP), -50400)
				WHEN SB.SUBSIDIARY = 'SEM' THEN
					 ADD_SECONDS(CAST(PO.ORDER_CREATION_DATE AS TIMESTAMP), -54000)
				WHEN SB.SUBSIDIARY = 'SECH' THEN
					 ADD_SECONDS(CAST(PO.ORDER_CREATION_DATE AS TIMESTAMP), -43200) --ADD_SECONDS(CAST(AOHS.ORDER_CREATION_DATE AS TIMESTAMP), -46800)	
				ELSE CAST(PO.ORDER_CREATION_DATE AS TIMESTAMP)
			END
		) AS DATE_REF -- Data da criação do pedido com dia e hora. 		
		
		, CL.YYYYWW AS YYYYWW
		, CL.YYYYMM AS YYYYMM
		, CL.YYYYQQ AS YYYYQQ
		, PO.ORDER_CREATION_DATE AS PO_CREATION_DATE
		, WEEKDAY(
			--PO.ORDER_CREATION_DATE
			CASE 
				WHEN SB.SUBSIDIARY IN('SEPR','SAMCOL') THEN
					ADD_SECONDS(CAST(PO.ORDER_CREATION_DATE AS TIMESTAMP), -50400)
				WHEN SB.SUBSIDIARY = 'SEM' THEN
					 ADD_SECONDS(CAST(PO.ORDER_CREATION_DATE AS TIMESTAMP), -54000)
				WHEN SB.SUBSIDIARY = 'SECH' THEN
					 ADD_SECONDS(CAST(PO.ORDER_CREATION_DATE AS TIMESTAMP), -43200) --ADD_SECONDS(CAST(AOHS.ORDER_CREATION_DATE AS TIMESTAMP), -46800)	
				ELSE CAST(PO.ORDER_CREATION_DATE AS TIMESTAMP)
			END				
		) AS PO_WEEK_DAY_NUM
		, DAYNAME(
			--PO.ORDER_CREATION_DATE
			CASE 
				WHEN SB.SUBSIDIARY IN('SEPR','SAMCOL') THEN
					ADD_SECONDS(CAST(PO.ORDER_CREATION_DATE AS TIMESTAMP), -50400)
				WHEN SB.SUBSIDIARY = 'SEM' THEN
					 ADD_SECONDS(CAST(PO.ORDER_CREATION_DATE AS TIMESTAMP), -54000)
				WHEN SB.SUBSIDIARY = 'SECH' THEN
					 ADD_SECONDS(CAST(PO.ORDER_CREATION_DATE AS TIMESTAMP), -43200) --ADD_SECONDS(CAST(AOHS.ORDER_CREATION_DATE AS TIMESTAMP), -46800)	
				ELSE CAST(PO.ORDER_CREATION_DATE AS TIMESTAMP)
			END		
		) AS PO_WEEK_DAY_NAME
		, EXTRACT_HOUR(
			--PO.ORDER_CREATION_DATE	
			CASE 
				WHEN SB.SUBSIDIARY IN('SEPR','SAMCOL') THEN
					ADD_SECONDS(CAST(PO.ORDER_CREATION_DATE AS TIMESTAMP), -50400)
				WHEN SB.SUBSIDIARY = 'SEM' THEN
					 ADD_SECONDS(CAST(PO.ORDER_CREATION_DATE AS TIMESTAMP), -54000)
				WHEN SB.SUBSIDIARY = 'SECH' THEN
					 ADD_SECONDS(CAST(PO.ORDER_CREATION_DATE AS TIMESTAMP), -43200) --ADD_SECONDS(CAST(AOHS.ORDER_CREATION_DATE AS TIMESTAMP), -46800)	
				ELSE CAST(PO.ORDER_CREATION_DATE AS TIMESTAMP)
			END
		) AS PO_HOUR
		, NULL AS SALES_CHANNEL
		, SB.SUBSIDIARY AS SUBSIDIARY
		--, NULL AS CHANNEL
		--, NULL AS SUB_CHANNEL
		--, NULL AS SALES_CHANNEL_ATTR_1
		--, NULL AS SALES_CHANNEL_ATTR_2
		, UPPER(TRIM(PO.SITE)) AS AFFILIATE_ID
		, PO.PRODUCT_CODE AS SKU
		, PD."DIVISION" AS PDROD_DIVISION
		, PD.PRODUCT_GROUP_1 AS PDROD_PRODUCT_GROUP
		, PD.PRODUCT_1 AS PDROD_PRODUCT
		, PD.ATTB01 AS PROD_ATTB_1
		, PD.SEDA_BU_ESTORE AS SEDA_BU_ESTORE
		, PD.SEDA_DIVISION_ESTORE AS SEDA_DIVISION_ESTORE
		, PD.SEDA_CATEGORY_ESTORE AS SEDA_CATEGORY_ESTORE
		, PD.SEDA_FAMILY_ESTORE AS SEDA_FAMILY_ESTORE
		, PD.SEDA_DESC_ESTORE AS SEDA_DESC_ESTORE
		, CAST( CAST(PO.ORDER_ENTRY_QUANTITY AS DECIMAL(18,2)) AS INTEGER) AS QTY
	
		, CAST( CAST(PO.ORDER_ENTRY_QUANTITY AS DECIMAL(18,2)) * CAST(PO.ORDER_ENTRY_UNIT_PRICE AS DECIMAL(18,2)) AS DECIMAL(18,2)) AS AMOUNT_LOCAL
		, CAST( (CAST(PO.ORDER_ENTRY_QUANTITY AS DECIMAL(18,2)) * CAST(PO.ORDER_ENTRY_UNIT_PRICE AS DECIMAL(18,2)))  
				/ EX.EXCHANGE_RATE AS DECIMAL(18,2) ) AS AMOUNT_USD		
		
		--, CAST( CAST(PO.ORDER_ENTRY_QUANTITY AS DECIMAL(18,2)) * CAST(PO.ORDER_ENTRY_TOTAL_PRICE AS DECIMAL(18,2)) AS DECIMAL(18,2)) AS AMOUNT_LOCAL
		--, CAST( (CAST(PO.ORDER_ENTRY_QUANTITY AS DECIMAL(18,2)) * CAST(PO.ORDER_ENTRY_TOTAL_PRICE AS DECIMAL(18,2)))  
		--	/ EX.EXCHANGE_RATE AS DECIMAL(18,2) ) AS AMOUNT_USD
		
		, PO.ORDER_ENTRY_UNIT_PRICE AS PRICE_TO
		, NULL AS AMOUNT_DISCOUNT
		, NULL AS AMOUNT_SHIPPING
		, PO.PRODUCT_NAME AS ITEM_NAME -- Nome do Produto.
		, PO.ORDER_CODE AS ORDER_ID -- Código do Pedido gerado na plataforma Hybris. 
		, NULL AS SELECTED_SLA
		, NULL AS WAREHOUSE_ID_GROUP
		, NULL AS MARKETPLACE_ORDER_ID
		, PO.SALES_ORDER AS CUSTOMER_PO -- Código gerado pelo NERP para a nota fiscal
		, NULL AS ENVIRONMENT
		, PO.STORE_ID AS STORE_ID -- Identificador da loja caso do pedido
		, PO.STORE_NAME AS NAME_STORE -- Nome da loja física caso do pedido tenha entrega 
		, NULL AS STORE_EMPLOYEE_CPF
		, NULL AS CHANNEL_TYPE
		, NULL AS O2O_TYPE
		, NULL AS REFERENCE_CODE_KIT
		, PO.PRODUCT_CODE AS REFERENCE_CODE
		, ORDER_STATUS AS STATUS_PO -- Status atual do pedido, como COMPLETED, SHIPPED etc... 
		, UPPER(TRIM(PO.SITE)) AS AFFILIATE_ID_ADJUSTED
		, AF.AFFILIATE_CHANNEL AS AFFILIATE_CHANNEL
		, AF.AFFILIATE_SUB_CHANNEL AS AFFILIATE_SUB_CHANNEL
		, AF.AFFILIATE_PARTNER_LEVEL AS AFFILIATE_PARTNER_LEVEL
		, AF.GLOBAL_CHANNEL AS GLOBAL_CHANNEL
		, AF.BIZ_TYPE AS BIZ_TYPE
		, AF.AUDIENCE_TYPE AS AUDIENCE_TYPE
		
		/********************
		, NULL AS "ECO_SKUID"
		, NULL AS "ECO_BRAND"
		, NULL AS "ECO_BOOST"
		, NULL AS "ECO_CATEGORY_NAME"
		, NULL AS "TRADE_IN_SKUID"
		, NULL AS "TRADE_IN_GTI"
		, NULL AS "TRADE_IN_BOOST"
		, NULL AS "TRADE_IN_TOTAL"
		, NULL AS "TRADE_IN_REFID"
		, NULL AS "IS_TRADE_IN"
		, NULL AS TRADE_IN_PRODUCT_NAME -- Marca do aparelho usado na aplicação de trade-in, quando houver. 
		, NULL AS TRADE_IN_PRODUCT_PRICE
		********************/
		
		, LOWER(PO.VOUCER_CODE) AS COUPON -- Código do voucher que foi usado no pedido, se houver.
		, UPPER(AF.COUNTRY_CODE) AS COUNTRY -- Pais em que o pedido teve origem como, PERU, MEXICO, CHI
		, AF.CURRENCY AS CURRENCY -- Código da moeda usado para o pagamento do pedido.  
		, CASE WHEN PR.MATERIAL IS NOT NULL THEN 'PREMIUM MODEL' ELSE 'NORMAL MODEL' END AS MODEL_TYPE
		, CURRENT_TIMESTAMP AS KPI_LAST_UPDATE
	FROM OW_LAO.ODS_HYBRIS_SALES PO
		  INNER JOIN OW_LAO.TMP_PO_ORDER_ID_PO_HYBRIS HP ON HP.ORDER_ID = PO.ORDER_CODE
		  --LEFT JOIN OW_MD.DIM_SALES_CHANNEL CH ON PO.SALES_CHANNEL = CH.VTEX_POLICY
		  LEFT JOIN OW_MD.DIM_PRODUCT PD ON PD.SKU = PO.PRODUCT_CODE
		  LEFT JOIN (
					SELECT DISTINCT TRIM(ITEM) AS MATERIAL
					FROM OW_LAO.ODS_GSCM_PREMIUM_MODELS
				) PR ON PR.MATERIAL = PO.PRODUCT_CODE  
		  LEFT JOIN OW_LAO.DIM_AFFILIATE_CHANNEL AF ON AF.AFFILIATE_ID = UPPER(TRIM(PO.SITE))
		  LEFT JOIN OW_LAO.FT_AP2_EXCHANGE_RATE EX ON EX.VALID_FROM = TO_DATE(PO.ORDER_CREATION_DATE)
		            AND UPPER(EX.TO_CURRENCY) = AF.CURRENCY
		            AND EX.FROM_CURRENCY = 'USD'
		  LEFT JOIN(
				SELECT -- PEGA SUBSIDÁRIA PELA MOEDA
					 CURRENCY
					,MAX(CASE WHEN CURRENCY <> 'USD' THEN SUBSIDIARY ELSE 'SELA' END) AS SUBSIDIARY
				FROM OW_LAO.DIM_AFFILIATE_CHANNEL
				GROUP BY
					CURRENCY
			) SB ON SB.CURRENCY = PO.ORDER_CURRENCY
		  LEFT JOIN OW_MD.DIM_CALENDAR CL ON 
		  			CL.YYYYMMDD = --TO_DATE(PO.ORDER_CREATION_DATE)		
						TO_DATE(
							CASE 
								WHEN SB.SUBSIDIARY IN('SEPR','SAMCOL') THEN
									ADD_SECONDS(CAST(PO.ORDER_CREATION_DATE AS TIMESTAMP), -50400)
								WHEN SB.SUBSIDIARY = 'SEM' THEN
									 ADD_SECONDS(CAST(PO.ORDER_CREATION_DATE AS TIMESTAMP), -54000)
								WHEN SB.SUBSIDIARY = 'SECH' THEN
									 ADD_SECONDS(CAST(PO.ORDER_CREATION_DATE AS TIMESTAMP), -43200) --ADD_SECONDS(CAST(AOHS.ORDER_CREATION_DATE AS TIMESTAMP), -46800)	
								ELSE CAST(PO.ORDER_CREATION_DATE AS TIMESTAMP)
							END
						)			
	WHERE ID NOT IN ( -- FILTRO SUJEIRA
		SELECT DISTINCT ID
		FROM OW_LAO.ODS_HYBRIS_SALES PO
		WHERE ORDER_ENTRY_QUANTITY LIKE_REGEXPR '[a-zA-Z]'
			OR PO.ORDER_ENTRY_TOTAL_PRICE LIKE_REGEXPR '%[a-zA-Z]%'
		UNION ALL 
		SELECT DISTINCT ID--, ORDER_ENTRY_QUANTITY, ORDER_ENTRY_TOTAL_PRICE
		FROM OW_LAO.ODS_HYBRIS_SALES PO
		WHERE ORDER_ENTRY_QUANTITY LIKE '%/%'
			OR PO.ORDER_ENTRY_TOTAL_PRICE  LIKE '%/%'
	);
	
	-- APAGA TABELAS TEMPORÁRIAS DO DISCO
	DROP TABLE OW_LAO.TMP_PO_ORDER_ID_PO_HYBRIS;
	
END;