/***********************************************************************************************
CREATED BY : Luciano Mariani
CREATION DATE : 2023-08-01
ALTER DATE : 
VERSION: 1.0
-- CALL OW_LAO.PROC_D2C_PO_VTEX_SALES_KPI;
SELECT TOP 100 * FROM OW_LAO.TF_D2C_PO_VTEX_SALES_KPI WHERE IS_TRADE_IN = 'true'
***********************************************************************************************/
CREATE PROCEDURE OW_LAO.PROC_D2C_PO_VTEX_SALES_KPI LANGUAGE SQLSCRIPT
AS
BEGIN
	
	-- PREMIUM_MODELS_TMP
	CREATE LOCAL TEMPORARY TABLE #PREMIUM_MODELS_TMP_ AS(
		SELECT DISTINCT
			 TRIM(ITEM) AS MATERIAL
		FROM OW_LAO.ODS_GSCM_PREMIUM_MODELS
	);	
	
	--APAGA TATBELA OW_LAO.TF_D2C_PO_VTEX_SALES_KPI
	IF EXISTS(
		SELECT TABLE_NAME
		FROM SYS.TABLES
		WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TF_D2C_PO_VTEX_SALES_KPI'
	)
	THEN
		DROP TABLE OW_LAO.TF_D2C_PO_VTEX_SALES_KPI;
	END IF;
	--CRIA NOVA TABELA TF_D2C_PO_VTEX_SALES_KPI
	CREATE COLUMN TABLE OW_LAO.TF_D2C_PO_VTEX_SALES_KPI AS (		
		SELECT
			  PO."SOURCE"
			, PO.DATE_REF
			, PO.YYYYWW
			, PO.YYYYMM
			, PO.YYYYQQ
			, PO.SUBSIDIARY
			, PO.CHANNEL
			, PO.SUB_CHANNEL
			, PO.SALES_CHANNEL_ATTR_1
			, PO.SALES_CHANNEL_ATTR_2
			, PO.CHANNEL_TYPE
			, PO.SKU
			, PO.PDROD_DIVISION
			, PO.PDROD_PRODUCT_GROUP
			, PO.PDROD_PRODUCT
			, PO.PROD_ATTB_1
			, PO.SEDA_BU_ESTORE
			, PO.SEDA_CATEGORY_ESTORE
			, PO.SEDA_DESC_ESTORE
			, PO.SEDA_DIVISION_ESTORE
			, PO.SEDA_FAMILY_ESTORE
			--,PO.STATUS_PO --,CASE WHEN "SOURCE" = 'PO' THEN STATUS_PO ELSE NULL END AS STATUS_PO
			, IFNULL( UPPER(SP.STATUS), UPPER(PO.STATUS_PO) ) AS STATUS 	
			-- AFFILIATE
			, PO.AFFILIATE_CHANNEL
			, PO.AFFILIATE_SUB_CHANNEL
			, PO.AFFILIATE_PARTNER_LEVEL
			, PO.GLOBAL_CHANNEL
			--,BIZ_TYPE
			, PO.AUDIENCE_TYPE
			, PO.COUNTRY
			, PO.CURRENCY
			, PO.MODEL_TYPE
			--,STATUS_PO
			, PO.REFERENCE_CODE_KIT
			, PO.STATE
			--,IS_TRADE_IN
			
			-- MEASURES
			--,SUM(CAST("TRADE_IN_GTI" AS DECIMAL(10,2)) ) AS TRADE_IN_GTI
			--,SUM(CAST("TRADE_IN_BOOST" AS DECIMAL(10,2))) AS TRADE_IN_BOOST
			--,SUM(CAST("TRADE_IN_TOTAL" AS DECIMAL(10,2))) AS TRADE_IN_TOTAL
			
			, SUM(PO.QTY) AS QTY
			, SUM(PO.AMOUNT_LOCAL) AS AMOUNT_LOCAL
			, SUM(PO.AMOUNT_USD) AS AMOUNT_USD
			--,CURRENT_TIMESTAMP AS KPI_LAST_UPDATE --,KPI_LAST_UPDATE
			, (
				SELECT MAX(PO_CREATION_DATE)
				FROM OW_LAO.TF_D2C_NERP_SALES
				WHERE "SOURCE" = 'PO'
					AND SUBSIDIARY = 'SEDA'
			  ) AS KPI_LAST_UPDATE			
		FROM OW_LAO.TF_D2C_NERP_SALES PO
				LEFT JOIN OW_MD. DIM_PO_STATUS SP ON UPPER(SP.STATUS_PO) = UPPER(PO.STATUS_PO)
		WHERE PO."SOURCE" = 'PO'
			AND PO.SUBSIDIARY = 'SEDA'
			--IS NULL 
			--OR STATUS_PO NOT IN('cancel','canceled')
		GROUP BY
			  PO."SOURCE"
			, PO.DATE_REF
			, PO.YYYYWW
			, PO.YYYYMM
			, PO.YYYYQQ
			, PO.SUBSIDIARY
			, PO.CHANNEL
			, PO.SUB_CHANNEL
			, PO.SALES_CHANNEL_ATTR_1
			, PO.SALES_CHANNEL_ATTR_2
			, PO.CHANNEL_TYPE
			, PO.SKU
			, PO.PDROD_DIVISION
			, PO.PDROD_PRODUCT_GROUP
			, PO.PDROD_PRODUCT
			, PO.PROD_ATTB_1
			, PO.SEDA_BU_ESTORE
			, PO.SEDA_CATEGORY_ESTORE
			, PO.SEDA_DESC_ESTORE
			, PO.SEDA_DIVISION_ESTORE
			, PO.SEDA_FAMILY_ESTORE
			--, PO.STATUS_PO --CASE WHEN "SOURCE" = 'PO' THEN STATUS_PO ELSE NULL END --AS STATUS_PO
			, IFNULL( UPPER(SP.STATUS), UPPER(PO.STATUS_PO) ) -- AS STATUS
			, PO.AFFILIATE_CHANNEL
			, PO.AFFILIATE_SUB_CHANNEL
			, PO.AFFILIATE_PARTNER_LEVEL
			, PO.GLOBAL_CHANNEL
			--, BIZ_TYPE
			, PO.AUDIENCE_TYPE
			, PO.COUNTRY
			, PO.CURRENCY
			, PO.MODEL_TYPE
			--, STATUS_PO
			, PO.REFERENCE_CODE_KIT
			, PO.STATE
			--, IS_TRADE_IN
	);
	/******************************
	-- APAGA TABELAS TEMPORÁRIAS
	******************************/
	DROP TABLE #PREMIUM_MODELS_TMP_;
	
END