CREATE PROCEDURE OW_LAO.PROC_D2C_NERP_LEAD_TIME
LANGUAGE SQLSCRIPT as
BEGIN
--PO > SO > DO > NF > GI > BILLING(IOD) 
--Truncar Tabela com os dados no nivel granular mais baixo para tratamento de dados 
TRUNCATE TABLE OW_LAO.TF_D2C_NERP_LEAD_TIME_01;
--Inserir os dados no nivel granular mais baixo na tabela de transformação
INSERT INTO OW_LAO.TF_D2C_NERP_LEAD_TIME_01
SELECT 
	 DS.SUBSIDIARY 
	,ONZOT.REGION AS STATE 
	,ONZOT.CITY 
	,DP.PRODUCT_GROUP_1 AS DIMPROD_PRODUCT_GROUP 
	,DP."DIVISION" AS DIMPROD_DIVISION 
	,DP.PRODUCT_1 AS DIMPROD_PRODUCT 
	,ONZOT.MATERIAL
	,ONZOT.DELIVERY_NO 
	,ONZASOT.CUSTOMER_PO
	,ONZOT.REFERENCE_DOC_SO_PO
	,ONZOT.PLANT
	,DP2.ORIGIN AS PLANT_NAME
	,ONZOT.TRANSPORTER_NAME
	,ONZOT.SPI
	,DC.YYYY AS "YEAR" 
	,DC.YYYYQQ AS "QUARTER" 
	,DC.YYYYMM AS "YEAR_MONTH"
	,DC.YYYYWW AS "WEEK"
	,TO_DATE(LEFT(TO_CHAR(IFNULL(URVSSO.CREATION_TIMESTAMP, URVSSO2.CREATION_TIMESTAMP)), 19)) AS VTEX_CREATION_DATE_ADJ
	,TO_DATE(CASE WHEN DS.COMPANY_CODE = 'SEPR' OR DS.COMPANY_CODE = 'SAMCOL' 
		THEN ADD_SECONDS(CAST(AOHS.ORDER_CREATION_DATE AS TIMESTAMP), -50400)
	WHEN DS.COMPANY_CODE = 'SEM'
		THEN ADD_SECONDS(CAST(AOHS.ORDER_CREATION_DATE AS TIMESTAMP), -54000)
	WHEN DS.COMPANY_CODE = 'SECH' 
		THEN ADD_SECONDS(CAST(AOHS.ORDER_CREATION_DATE AS TIMESTAMP), -43200)
		ELSE CAST(AOHS.ORDER_CREATION_DATE AS TIMESTAMP)
	END) AS ORDER_CREATION_DATE_ON_HYBRIS
	,TO_DATE(ONZASOT.SO_LOCAL_CREATE_ON_D) AS SO_CREATED_ON 
	,TO_DATE(ONZOT.DOCUMENT_DATE_LOCAL) AS DOCUMENT_DATE_LOCAL
	,TO_DATE(ONZOT.NOTA_POSTING_DATE) AS NOTA_POSTING_DATE
	,TO_DATE(ONZOT."1ST_GI_DATE") AS "1ST_GI_DATE"
	,TO_DATE(ONZOT.PLANNED_GI) AS PLANNED_GI
	,TO_DATE(ONZOT.EPOD_DATE) AS EPOD_DATE 
	,TO_DATE(ONZOT.RDD_SO_ITEM) AS RDD
	,TO_DATE(ONZOT.DELIVERY_DATE) AS DELIVERY_DATE
	,ONZOT.SOLDTO_CODE
	,ONZOT.NET_VALUE
	,ONZOT.AR_AMOUNT
	,CASE WHEN ONZOT.PLANNED_GI IS NOT NULL 
		THEN DELIVERY_QTY
		ELSE 0
	END AS TOTAL_PLANNED_GI
	,CASE WHEN ONZOT."1ST_GI_DATE" IS NOT NULL 
		THEN DELIVERY_QTY
		ELSE 0
	END AS ACTUAL_GI
	,CASE WHEN ONZOT."1ST_GI_DATE" IS NULL AND CURRENT_DATE > ONZOT.PLANNED_GI 
		THEN DELIVERY_QTY
		ELSE 0
	END AS PENDING_GI
	,CASE WHEN ONZOT."1ST_GI_DATE" <= ONZOT.PLANNED_GI 
		THEN DELIVERY_QTY
		ELSE 0
	END AS ON_TIME_GI
	,CASE WHEN ONZOT."1ST_GI_DATE" = ONZOT.DOCUMENT_DATE_LOCAL 
		THEN DELIVERY_QTY
		ELSE 0
	END AS SAME_DAY_GI
	,CAST(NULL AS INTEGER) AS LT_WK_PO_SO
	,CAST(NULL AS INTEGER) AS LT_WK_SO_DO
	,CAST(NULL AS INTEGER) AS LT_WK_DO_NF
	,CAST(NULL AS INTEGER) AS LT_WK_NF_GI
	,CAST(NULL AS INTEGER) AS LT_WK_DO_GI
	,CAST(NULL AS INTEGER) AS LT_WK_GI_EPOD
	,CAST(NULL AS INTEGER) AS LT_WK_TOTAL_PO_EPOD
	,CAST(NULL AS INTEGER) AS LT_WK_TOTAL_SO_EPOD
	,CAST(NULL AS INTEGER) AS LT_PO_SO
	,CAST(NULL AS INTEGER) AS LT_SO_DO
	,CAST(NULL AS INTEGER) AS LT_DO_NF
	,CAST(NULL AS INTEGER) AS LT_NF_GI
	,CAST(NULL AS INTEGER) AS LT_DO_GI
	,CAST(NULL AS INTEGER) AS LT_GI_EPOD
	,CAST(NULL AS INTEGER) AS LT_TOTAL_PO_EPOD
	,CAST(NULL AS INTEGER) AS LT_TOTAL_SO_EPOD
	,DTLTCD."TGT_CAL_PO_SO"
	,DTLTCD."TGT_CAL_SO_DO"
	,DTLTCD."TGT_CAL_DO_PICKING"
	,DTLTCD."TGT_CAL_PICKING_NF"
	,DTLTCD."TGT_CAL_NF_GI"
	,CAST(NULL AS INTEGER) AS TGT_CAL_GI_IOD
	,CAST(NULL AS INTEGER) AS "Target CAL TTL Lead time"
	,DTLTWD."TGT_WK_PO_SO"
	,DTLTWD."TGT_WK_SO_DO"
	,DTLTWD."TGT_WK_DO_PICKING"
	,DTLTWD."TGT_WK_PICKING_NF"
	,DTLTWD."TGT_WK_NF_GI"
	,CAST(NULL AS INTEGER) AS "TGT_WK_GI_IOD"
	,CAST(NULL AS INTEGER) AS "Target WK TTL Lead time"
	,1 AS RECORD_QTY
	,ONZOT.DELIVERY_QTY AS IOD_QTY
	,CAST(NULL AS INTEGER) AS OTD_QTY
	,CAST(NULL AS INTEGER) AS OTD_DO_QTY
	,CAST(NULL AS INTEGER) AS OVER_TARGET_QTY_WK
	,CAST(NULL AS INTEGER) AS OVER_TARGET_QTY_CAL
	,CAST(NULL AS INTEGER) AS OVER_TGT_QTY_GI_EPOD_WK
	,CAST(NULL AS INTEGER) AS OVER_TGT_QTY_GI_EPOD_CAL
	,NULL AS LAST_UPDATE
FROM OW_LAO.ODS_NERP_ZLLEJ50090_OUTBOUND_TRACKING ONZOT
	LEFT JOIN OW_LAO.ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING ONZASOT ON (ONZOT.REFERENCE_DOC_SO_PO = ONZASOT.SALES_DOCUMENT 
							AND ONZOT.MATERIAL = ONZASOT.MATERIAL 
							AND ONZOT.DELIVERY_ITEM = ONZASOT.DELIVERY_ITEM AND ONZOT.DELIVERY_NO = ONZASOT.DELIVERY) 
	LEFT JOIN OW_MD.DIM_SUBSIDIARY DS ON (ONZOT.SALES_ORG = DS.SALES_ORG)
	LEFT JOIN OW_MD.DIM_CALENDAR DC ON (DC.YYYYMMDD = (CASE WHEN DS.SUBSIDIARY IN ('SELA-M','SELA-P') THEN TO_DATE(ONZOT.BILLING_DATE) ELSE TO_DATE(ONZOT.EPOD_DATE)END)) --VER COM O ERICK SE MANTEM BILLING
	LEFT JOIN (
				SELECT ORDER_ID, SALES_CHANNEL, CREATION_TIMESTAMP 
				FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SALES_ORDER 
				UNION
				SELECT ORDER_ID, SALES_CHANNEL, CREATION_TIMESTAMP 
				FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER
			  ) URVSSO ON ONZASOT.CUSTOMER_PO = URVSSO.ORDER_ID -- VERIFICAR ESSE JOIN
	LEFT JOIN ( 
				SELECT ORDER_ID, SALES_CHANNEL, "SEQUENCE", CREATION_TIMESTAMP 
				FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SALES_ORDER 
				UNION
				SELECT ORDER_ID, SALES_CHANNEL, "SEQUENCE", CREATION_TIMESTAMP 
				FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER
			  ) URVSSO2 ON ONZASOT.CUSTOMER_PO = URVSSO2."SEQUENCE" -- VERIFICAR ESSE JOIN
	LEFT JOIN OW_MD.DIM_PLANT DP2 ON (ONZOT.PLANT = DP2.PLANT_CODE) -- Adicionado dia 31/03/2023
	LEFT JOIN OW_MD.DIM_PRODUCT DP ON (ONZOT.MATERIAL = DP.SKU) --Adicionado dia 31/03/2023
	LEFT JOIN OW_MD.DIM_TARGET_LEAD_TIME_CALENDAR_DAY DTLTCD ON (CASE WHEN UPPER(DP.DIVISION) IN ('DA','VD') THEN 'CE' ELSE 'OTHER'END = DTLTCD.DIVISION)
	LEFT JOIN OW_MD.DIM_TARGET_LEAD_TIME_WORKING_DAY DTLTWD ON (CASE WHEN UPPER(DP.DIVISION) IN ('DA','VD') THEN 'CE' ELSE 'OTHER'END = DTLTWD.DIVISION)
	LEFT JOIN (SELECT DISTINCT OHS.ORDER_CREATION_DATE
				  ,OHS.SALES_ORDER
				  ,OHS.DELIVERY_ORDER
				  ,OHS.ORDER_STATUS
				  ,OHS.PRODUCT_CODE 
				  ,OHS.ORDER_ENTRY_QUANTITY 
			FROM OW_LAO.ODS_HYBRIS_SALES OHS
		  WHERE OHS.ORDER_STATUS IN ('COMPLETED',
				'CREATED',
				'ORDER_SPLIT',
				'PAYMENT_CAPTURED',
				'PICKUP_COMPLETE',
				'READY_FOR_PICKUP',
				'SHIPPED',
				'SHIPPING_PREPARATION',
		'SHIPPING_REQUESTED')
		AND LENGTH(OHS.SALES_ORDER) = 10 
		) AOHS ON  (ONZOT.REFERENCE_DOC_SO_PO = AOHS.SALES_ORDER
							AND ONZOT.MATERIAL = AOHS.PRODUCT_CODE
							--AND ONZOT.DELIVERY_ITEM = TO_INTEGER(AOHS.ORDER_ENTRY_QUANTITY)  
							AND ONZOT.DELIVERY_NO = AOHS.DELIVERY_ORDER) 
WHERE 1=1
	AND (
		(DS.SUBSIDIARY NOT IN ('SEDA','SELA-P','SELA-M') AND ONZOT.SO_TYPE = 'YS10' AND ONZOT.EPOD_DATE IS NOT NULL) 
	OR  (DS.SUBSIDIARY = 'SEDA' AND ONZOT.SO_TYPE = 'YS10' AND ONZOT.EPOD_DATE IS NOT NULL)
	OR  (DS.SUBSIDIARY IN ('SELA-P','SELA-M') AND ONZOT.SO_TYPE = 'YN01' AND ONZOT.BILLING_DATE IS NOT NULL ) --VER SE A REGRA MANTEM BILLING
	)
	AND ONZOT.DO_TYPE = 'ZND1'
	AND ONZASOT.REJECT_REASON IS NULL 
	AND ONZASOT.REJECT_REASON_1 IS NULL 
;
--Truncar Tabela com os dados no nivel granular mais baixo para tratamento de dados 
TRUNCATE TABLE OW_LAO.TF_D2C_NERP_LEAD_TIME_02;
--Inserir os dados no nivel granular mais baixo na tabela de transformação
INSERT INTO OW_LAO.TF_D2C_NERP_LEAD_TIME_02
SELECT 	SUBSIDIARY
	,STATE
	,CITY
	,DIMPROD_PRODUCT_GROUP
	,DIMPROD_DIVISION
	,DIMPROD_PRODUCT
	,MATERIAL
	,DELIVERY_NO
	,CUSTOMER_PO
	,REFERENCE_DOC_SO_PO
	,PLANT
	,PLANT_NAME
	,TRANSPORTER_NAME
	,SPI
	,"YEAR"
	,QUARTER
	,YEAR_MONTH
	,"WEEK"
	,VTEX_CREATION_DATE_ADJ
	,ORDER_CREATION_DATE_ON_HYBRIS
	,SO_CREATED_ON
	,DOCUMENT_DATE_LOCAL
	,NOTA_POSTING_DATE
	,"1ST_GI_DATE"
	,PLANNED_GI
	,EPOD_DATE
	,RDD
	,SOLDTO_CODE
	,NET_VALUE
	,AR_AMOUNT
	,TOTAL_PLANNED_GI
	,ACTUAL_GI
	,PENDING_GI
	,ON_TIME_GI
	,SAME_DAY_GI
	,(
		SELECT (CASE WHEN (SUM(WORK_DAY_SEDA)-1) = -1 
				THEN 0 
			   WHEN (WEEKDAY(VTEX_CREATION_DATE_ADJ) IN (5,6) 
			   AND WEEKDAY(SO_CREATED_ON) IN (5,6)) 
				THEN SUM(WORK_DAY_SEDA) 
				ELSE (SUM(WORK_DAY_SEDA)-1) 
		       END) 
		FROM OW_MD.DIM_CALENDAR DC 
		WHERE (YYYYMMDD BETWEEN VTEX_CREATION_DATE_ADJ AND SO_CREATED_ON)
	) AS "LT_WK_PO_SO"
	,(
		SELECT (CASE WHEN (SUM(WORK_DAY_SEDA)-1) = -1 
				THEN 0 
			   WHEN (WEEKDAY(SO_CREATED_ON) IN (5,6) 
			   AND WEEKDAY(DOCUMENT_DATE_LOCAL) IN (5,6)) 
				THEN SUM(WORK_DAY_SEDA) 
				ELSE (SUM(WORK_DAY_SEDA)-1) 
		      END) 
		FROM OW_MD.DIM_CALENDAR DC 
		WHERE (YYYYMMDD BETWEEN SO_CREATED_ON AND DOCUMENT_DATE_LOCAL)
	) AS "LT_WK_SO_DO"
	,(
		SELECT (CASE WHEN (SUM(WORK_DAY_SEDA)-1) = -1 
				THEN 0 
			   WHEN (WEEKDAY(DOCUMENT_DATE_LOCAL) IN (5,6) 
			   AND WEEKDAY(NOTA_POSTING_DATE) IN (5,6)) 
				THEN SUM(WORK_DAY_SEDA) 
				ELSE (SUM(WORK_DAY_SEDA)-1) 
		        END)
	FROM OW_MD.DIM_CALENDAR DC 
	WHERE (YYYYMMDD BETWEEN DOCUMENT_DATE_LOCAL AND NOTA_POSTING_DATE)
	) AS "LT_WK_DO_NF"
	,(
		SELECT (CASE WHEN (SUM(WORK_DAY_SEDA)-1) = -1 
				THEN 0 
			   WHEN (WEEKDAY(NOTA_POSTING_DATE) IN (5,6) 
			   AND WEEKDAY("1ST_GI_DATE") IN (5,6)) 
				THEN SUM(WORK_DAY_SEDA) 
				ELSE (SUM(WORK_DAY_SEDA)-1) 
		       END)
	FROM OW_MD.DIM_CALENDAR DC 
	WHERE (YYYYMMDD BETWEEN NOTA_POSTING_DATE AND "1ST_GI_DATE")
	) AS "LT_WK_NF_GI"
	,(
		SELECT (CASE WHEN (SUM(WORK_DAY_SEDA)-1) = -1 
				THEN 0 
			   WHEN (WEEKDAY(DOCUMENT_DATE_LOCAL) IN (5,6) 
			   AND WEEKDAY("1ST_GI_DATE") IN (5,6)) 
				THEN SUM(WORK_DAY_SEDA) 
				ELSE (SUM(WORK_DAY_SEDA)-1) 
		       END)
		FROM OW_MD.DIM_CALENDAR DC 
		WHERE (YYYYMMDD BETWEEN DOCUMENT_DATE_LOCAL AND "1ST_GI_DATE")
	) AS "LT_WK_DO_GI"	 
	,(CASE WHEN SUBSIDIARY = 'SEDA'
		THEN 	(
				SELECT CASE WHEN (SUM(WORK_DAY_SEDA)-1) = -1 
						THEN 0 
					   WHEN (WEEKDAY("1ST_GI_DATE") IN (5,6) 
					   AND WEEKDAY(EPOD_DATE) IN (5,6)) 
						THEN SUM(WORK_DAY_SEDA) 
						ELSE (SUM(WORK_DAY_SEDA)-1) 
					   END
			FROM OW_MD.DIM_CALENDAR DC 
			WHERE (YYYYMMDD BETWEEN "1ST_GI_DATE" AND EPOD_DATE)
			)
		ELSE NULL 
	END) AS "LT_WK_GI_EPOD_SEDA"
	,(CASE WHEN SUBSIDIARY <> 'SEDA'
		THEN 	(
				SELECT CASE WHEN (SUM(WORK_DAY_SEDA)-1) = -1 
						THEN 0 
					   WHEN (WEEKDAY("1ST_GI_DATE") IN (5,6) 
					   AND WEEKDAY(DELIVERY_DATE) IN (5,6)) 
						THEN SUM(WORK_DAY_SEDA) 
						ELSE (SUM(WORK_DAY_SEDA)-1) 
					   END
			FROM OW_MD.DIM_CALENDAR DC 
			WHERE (YYYYMMDD BETWEEN "1ST_GI_DATE" AND DELIVERY_DATE)
			)
		ELSE NULL
	END) AS "LT_WK_GI_EPOD_OTHERS"
	,CAST(NULL AS INTEGER) AS LT_WK_TOTAL_PO_EPOD
        ,CAST(NULL AS INTEGER) AS LT_WK_TOTAL_SO_EPOD
	,(CASE WHEN SUBSIDIARY = 'SEDA'
	       	THEN (DAYS_BETWEEN(VTEX_CREATION_DATE_ADJ, SO_CREATED_ON))
	       WHEN SUBSIDIARY IN ('SELA-P','SELA-M') -- ALTERAR QUANDO TIVERMOS A DEFINIÇÃO DE MAGENTO
		THEN (DAYS_BETWEEN(ORDER_CREATION_DATE_ON_HYBRIS, SO_CREATED_ON))
		ELSE (DAYS_BETWEEN(ORDER_CREATION_DATE_ON_HYBRIS, SO_CREATED_ON))
	END) AS "LT_PO_SO"
	,(DAYS_BETWEEN(SO_CREATED_ON, DOCUMENT_DATE_LOCAL)) AS "LT_SO_DO"
	,(DAYS_BETWEEN(DOCUMENT_DATE_LOCAL, NOTA_POSTING_DATE)) AS "LT_DO_NF"
	,(DAYS_BETWEEN(NOTA_POSTING_DATE, "1ST_GI_DATE")) AS "LT_NF_GI"
	,(DAYS_BETWEEN(DOCUMENT_DATE_LOCAL, "1ST_GI_DATE")) AS "LT_DO_GI"
	,(CASE WHEN SUBSIDIARY = 'SEDA'
		THEN (DAYS_BETWEEN("1ST_GI_DATE", EPOD_DATE)) 
		ELSE NULL
	END) AS "LT_GI_EPOD_SEDA"	
	,(CASE WHEN SUBSIDIARY <> 'SEDA'
		THEN (DAYS_BETWEEN("1ST_GI_DATE", DELIVERY_DATE))
		ELSE NULL
	END) AS "LT_GI_EPOD_OTHERS"
	,CAST(NULL AS INTEGER) AS LT_TOTAL_PO_EPOD
	,CAST(NULL AS INTEGER) AS LT_TOTAL_SO_EPOD
	,TGT_CAL_PO_SO
	,TGT_CAL_SO_DO
	,TGT_CAL_DO_PICKING
	,TGT_CAL_PICKING_NF
	,TGT_CAL_NF_GI
	,(CASE WHEN SUBSIDIARY = 'SEDA' AND (SPI = 'CR02' OR SPI = 'AGS1') 
		THEN COALESCE(DAYS_BETWEEN(PLANNED_GI,DELIVERY_DATE),0) 
		ELSE COALESCE(DAYS_BETWEEN(PLANNED_GI,RDD),0) 	
	END) AS "TGT_CAL_GI_IOD"
	,CAST(NULL AS INTEGER) AS "Target CAL TTL Lead time"
	,TGT_WK_PO_SO
	,TGT_WK_SO_DO
	,TGT_WK_DO_PICKING
	,TGT_WK_PICKING_NF
	,TGT_WK_NF_GI
	,(CASE WHEN SUBSIDIARY = 'SEDA' AND (SPI = 'CR02' OR SPI = 'AGS1') 
		THEN COALESCE((SELECT	(CASE WHEN (SUM(WORK_DAY_SEDA)-1) = -1 
							THEN 0
					      WHEN (WEEKDAY(PLANNED_GI) IN (5, 6) AND WEEKDAY(DELIVERY_DATE) IN (5, 6)) 
							THEN SUM(WORK_DAY_SEDA)
							ELSE (SUM(WORK_DAY_SEDA)-1)
					END)
				FROM	OW_MD.DIM_CALENDAR DC
				WHERE	(YYYYMMDD BETWEEN PLANNED_GI AND DELIVERY_DATE)),0)
				
		ELSE COALESCE((SELECT	CASE	WHEN (SUM(WORK_DAY_SEDA)-1) = -1 
							THEN 0
						WHEN (WEEKDAY(PLANNED_GI) IN (5, 6) AND WEEKDAY(RDD) IN (5, 6)) 
							THEN SUM(WORK_DAY_SEDA)
							ELSE (SUM(WORK_DAY_SEDA)-1)
					END
				FROM	OW_MD.DIM_CALENDAR DC
				WHERE	(YYYYMMDD BETWEEN PLANNED_GI AND RDD)),0)
	END) AS "TGT_WK_GI_IOD"
	,CAST(NULL AS INTEGER) AS "Target WK TTL Lead time"
	,RECORD_QTY
	,IOD_QTY
	,(CASE WHEN SUBSIDIARY = 'SEDA' AND (SPI = 'CR02' OR SPI = 'AGS1') 
		THEN 	(CASE WHEN DAYS_BETWEEN(DELIVERY_DATE,EPOD_DATE)>=0
				THEN 0
				ELSE IOD_QTY --DELIVERY_QTY 
			END)
		ELSE 	(CASE WHEN DAYS_BETWEEN(RDD,EPOD_DATE)>=0
				THEN 0
				ELSE IOD_QTY --DELIVERY_QTY 
			END)
	
	END) AS OTD_QTY
	,(CASE WHEN SUBSIDIARY = 'SEDA' AND (SPI = 'CR02' OR SPI = 'AGS1') 
		THEN 	(CASE WHEN DAYS_BETWEEN(DELIVERY_DATE,EPOD_DATE)>0
				THEN 0
				ELSE 1
			END)
		ELSE 	(CASE WHEN DAYS_BETWEEN(RDD,EPOD_DATE)>0
				THEN 0
				ELSE 1
			END)	
	END) AS OTD_DO_QTY
	,CAST(NULL AS INTEGER) AS OVER_TARGET_QTY_WK
	,CAST(NULL AS INTEGER) AS OVER_TARGET_QTY_CAL
	,CAST(NULL AS INTEGER) AS OVER_TGT_QTY_GI_EPOD_WK
	,CAST(NULL AS INTEGER) AS OVER_TGT_QTY_GI_EPOD_CAL
	,LAST_UPDATE
FROM OW_LAO.TF_D2C_NERP_LEAD_TIME_01
;
--Truncar Tabela com os dados no nivel granular mais baixo para tratamento de dados 
TRUNCATE TABLE OW_LAO.TF_D2C_NERP_LEAD_TIME_03;
--Inserir os dados no nivel granular mais baixo na tabela de transformação
INSERT INTO OW_LAO.TF_D2C_NERP_LEAD_TIME_03
SELECT  SUBSIDIARY
	,STATE
	,CITY
	,DIMPROD_PRODUCT_GROUP
	,DIMPROD_DIVISION
	,DIMPROD_PRODUCT
	,MATERIAL
	,DELIVERY_NO
	,CUSTOMER_PO
	,REFERENCE_DOC_SO_PO
	,PLANT
	,PLANT_NAME
	,TRANSPORTER_NAME
	,SPI
	,"YEAR"
	,QUARTER
	,YEAR_MONTH
	,"WEEK"
	,VTEX_CREATION_DATE_ADJ
	,ORDER_CREATION_DATE_ON_HYBRIS
	,SO_CREATED_ON
	,DOCUMENT_DATE_LOCAL
	,NOTA_POSTING_DATE
	,"1ST_GI_DATE"
	,PLANNED_GI
	,EPOD_DATE
	,RDD
	,SOLDTO_CODE
	,NET_VALUE
	,AR_AMOUNT
	,TOTAL_PLANNED_GI
	,ACTUAL_GI
	,PENDING_GI
	,ON_TIME_GI
	,SAME_DAY_GI
	,LT_WK_PO_SO
	,LT_WK_SO_DO
	,LT_WK_DO_NF
	,LT_WK_NF_GI
	,LT_WK_DO_GI
	,LT_WK_GI_EPOD_SEDA
	,LT_WK_GI_EPOD_OTHERS
	--,IFNULL(LT_WK_GI_EPOD_SEDA,LT_WK_GI_EPOD_OTHERS) AS LT_WK_GI_EPOD 
	,CASE WHEN SUBSIDIARY = 'SEDA'
		THEN	ROUND(--"Lead time PO ~SO"+"Lead time SO ~DO"+"Lead time DO ~GI"+"Lead time GI ~IOD"--EPOD_DATE
				(
				"LT_WK_PO_SO"
			+	"LT_WK_SO_DO"
			+	"LT_WK_DO_GI"
			+	"LT_WK_GI_EPOD_SEDA"
				)
			,1)
		ELSE ROUND(--"Lead time PO ~SO"+"Lead time SO ~DO"+"Lead time DO ~GI"+"Lead time GI ~IOD"--DELIVERY_DATE
				(
				"LT_WK_PO_SO"
			+	"LT_WK_SO_DO"
			+	"LT_WK_DO_GI"
			+	"LT_WK_GI_EPOD_OTHERS"
				)
			,1)
	END AS "LT_WK_TOTAL_PO_EPOD"
        ,CASE WHEN SUBSIDIARY = 'SEDA'
		THEN	ROUND(--"Lead time SO ~DO"+"Lead time DO ~GI"+"Lead time GI ~IOD"--EPOD_DATE
				(
				"LT_WK_SO_DO"
			+	"LT_WK_DO_GI"
			+	"LT_WK_GI_EPOD_SEDA"
				)
			,1)
		ELSE	ROUND(--"Lead time SO ~DO"+"Lead time DO ~GI"+"Lead time GI ~IOD"--DELIVERY_DATE
				(
				"LT_WK_SO_DO"
			+	"LT_WK_DO_GI"
			+	"LT_WK_GI_EPOD_OTHERS"
				)
			,1)
	END AS "LT_WK_TOTAL_SO_EPOD"
	,LT_PO_SO
	,LT_SO_DO
	,LT_DO_NF
	,LT_NF_GI
	,LT_DO_GI
	,LT_GI_EPOD_SEDA
	,LT_GI_EPOD_OTHERS
	--,IFNULL(LT_GI_EPOD_SEDA,LT_GI_EPOD_OTHERS) AS LT_GI_EPOD
	,(CASE WHEN SUBSIDIARY = 'SEDA'
		THEN    ROUND(
				(
				IFNULL("LT_PO_SO",0) 
			+	IFNULL("LT_SO_DO",0)
			+	IFNULL("LT_DO_GI",0)
			+	IFNULL("LT_GI_EPOD_SEDA",0)
				)
			,1) 
		ELSE	ROUND(
				(
				IFNULL("LT_PO_SO",0) 
			+	IFNULL("LT_SO_DO",0)
			+	IFNULL("LT_DO_GI",0)
			+	IFNULL("LT_GI_EPOD_OTHERS",0)
				)
			,1)
	END) AS "LT_TOTAL_PO_EPOD"
	,(CASE WHEN SUBSIDIARY = 'SEDA'
		THEN    ROUND(
				(
				IFNULL("LT_SO_DO",0)
			+	IFNULL("LT_DO_GI",0)
			+	IFNULL("LT_GI_EPOD_SEDA",0)
				)
			,1)
		ELSE  ROUND(
				(
			IFNULL("LT_PO_SO",0) 
			+	IFNULL("LT_SO_DO",0)
			+	IFNULL("LT_DO_GI",0)
			+	IFNULL("LT_GI_EPOD_OTHERS",0)
				)
			,1)
	END) AS "LT_TOTAL_SO_EPOD"
	,TGT_CAL_PO_SO
	,TGT_CAL_SO_DO
	,TGT_CAL_DO_PICKING
	,TGT_CAL_PICKING_NF
	,TGT_CAL_NF_GI
	,TGT_CAL_GI_IOD
	,("TGT_CAL_PO_SO"+"TGT_CAL_SO_DO"+"TGT_CAL_DO_PICKING"+
	"TGT_CAL_PICKING_NF"+"TGT_CAL_NF_GI"+"TGT_CAL_GI_IOD") AS "Target CAL TTL Lead time"
	,TGT_WK_PO_SO
	,TGT_WK_SO_DO
	,TGT_WK_DO_PICKING
	,TGT_WK_PICKING_NF
	,TGT_WK_NF_GI
	,TGT_WK_GI_IOD
	,("TGT_WK_PO_SO"+"TGT_WK_SO_DO"+"TGT_WK_DO_PICKING"
	+"TGT_WK_PICKING_NF"+"TGT_WK_NF_GI"+ "TGT_WK_GI_IOD") AS "Target WK TTL Lead time"
	,RECORD_QTY
	,IOD_QTY
	,OTD_QTY
	,OTD_DO_QTY
	,CAST(NULL AS INTEGER) AS OVER_TARGET_QTY_WK
	,CAST(NULL AS INTEGER) AS OVER_TARGET_QTY_CAL
	,CAST(NULL AS INTEGER) AS OVER_TGT_QTY_GI_EPOD_WK
	,CAST(NULL AS INTEGER) AS OVER_TGT_QTY_GI_EPOD_CAL
	,LAST_UPDATE
FROM OW_LAO.TF_D2C_NERP_LEAD_TIME_02
;
--Truncar Tabela com os dados no nivel granular mais baixo para tratamento de dados 
TRUNCATE TABLE OW_LAO.TF_D2C_NERP_LEAD_TIME;
--Inserir os dados no nivel granular mais baixo na tabela de transformação
INSERT INTO OW_LAO.TF_D2C_NERP_LEAD_TIME
SELECT   SUBSIDIARY
	,STATE
	,CITY
	,DIMPROD_PRODUCT_GROUP
	,DIMPROD_DIVISION
	,DIMPROD_PRODUCT
	,MATERIAL
	,DELIVERY_NO
	,CUSTOMER_PO
	,REFERENCE_DOC_SO_PO
	,PLANT
	,PLANT_NAME
	,TRANSPORTER_NAME
	,"YEAR"
	,QUARTER
	,YEAR_MONTH
	,"WEEK"
	,VTEX_CREATION_DATE_ADJ
	,ORDER_CREATION_DATE_ON_HYBRIS
	,SO_CREATED_ON
	,DOCUMENT_DATE_LOCAL
	,NOTA_POSTING_DATE
	,"1ST_GI_DATE"
	,PLANNED_GI
	,EPOD_DATE
	,RDD
	,SOLDTO_CODE
	,NET_VALUE
	,AR_AMOUNT
	,TOTAL_PLANNED_GI
	,ACTUAL_GI
	,PENDING_GI
	,ON_TIME_GI
	,SAME_DAY_GI
	,LT_WK_PO_SO
	,LT_WK_SO_DO
	,LT_WK_DO_NF
	,LT_WK_NF_GI
	,LT_WK_DO_GI
	,IFNULL(LT_WK_GI_EPOD_SEDA,LT_WK_GI_EPOD_OTHERS) AS LT_WK_GI_EPOD 
	,LT_WK_TOTAL_PO_EPOD
	,LT_WK_TOTAL_SO_EPOD
	,LT_PO_SO
	,LT_SO_DO
	,LT_DO_NF
	,LT_NF_GI
	,LT_DO_GI
	,IFNULL(LT_GI_EPOD_SEDA,LT_GI_EPOD_OTHERS) AS LT_GI_EPOD
	,LT_TOTAL_PO_EPOD
	,LT_TOTAL_SO_EPOD
	,TGT_CAL_PO_SO
	,TGT_CAL_SO_DO
	,TGT_CAL_DO_PICKING
	,TGT_CAL_PICKING_NF
	,TGT_CAL_NF_GI
	,TGT_CAL_GI_IOD
	,"Target CAL TTL Lead time"
	,TGT_WK_PO_SO
	,TGT_WK_SO_DO
	,TGT_WK_DO_PICKING
	,TGT_WK_PICKING_NF
	,TGT_WK_NF_GI
	,TGT_WK_GI_IOD
	,"Target WK TTL Lead time"
	,RECORD_QTY
	,IOD_QTY
	,OTD_QTY
	,OTD_DO_QTY
	,(CASE WHEN  ROUND("LT_WK_TOTAL_PO_EPOD" + IFNULL("LT_WK_GI_EPOD_SEDA","LT_WK_GI_EPOD_OTHERS"),1) 
			> "Target WK TTL Lead time"
				THEN IOD_QTY --DELIVERY_QTY 
				ELSE 0 
	END) AS OVER_TARGET_QTY_WK
	,(CASE WHEN ROUND("LT_TOTAL_PO_EPOD" + IFNULL("LT_GI_EPOD_SEDA","LT_GI_EPOD_OTHERS"),1)
		        > "Target CAL TTL Lead time"
		        	THEN IOD_QTY --DELIVERY_QTY 
				ELSE 0 
	END) AS OVER_TARGET_QTY_CAL
	,(CASE WHEN ROUND(IFNULL("LT_WK_GI_EPOD_SEDA","LT_WK_GI_EPOD_OTHERS"),1) > "Target WK TTL Lead time"
		       	THEN IOD_QTY --DELIVERY_QTY 
			ELSE 0 
	END) AS OVER_TGT_QTY_GI_EPOD_WK
	,(CASE WHEN ROUND(IFNULL("LT_GI_EPOD_SEDA","LT_GI_EPOD_OTHERS"),1) > "Target CAL TTL Lead time"
		       	THEN IOD_QTY --DELIVERY_QTY 
			ELSE 0 
	END) AS OVER_TGT_QTY_GI_EPOD_CAL
	,LAST_UPDATE
FROM OW_LAO.TF_D2C_NERP_LEAD_TIME_03
;
-- Update para Setar o horário de carga. Obs.: Estou fazendo aqui para não ter probemas com milisegundos
UPDATE OW_LAO.TF_D2C_NERP_LEAD_TIME 
	SET LAST_UPDATE = NOW()
	WHERE LAST_UPDATE IS NULL;
-- Truncar a tabela fato unificada com os 4 indicadores FT_D2C_NERP_LEAD_TIME, referente as transações ZLLEJ50090 e ZRSDD6A120 (outbound)
TRUNCATE TABLE OW_LAO.FT_D2C_NERP_LEAD_TIME;
-- Inserir os dados tratados na tabela fato unificada com os 3 indicadores FT_D2C_NERP_LEAD_TIME, referente as transações ZLLEJ50090 e ZRSDD6A120 (outbound)
INSERT INTO OW_LAO.FT_D2C_NERP_LEAD_TIME
--indicador consolidado 1, 2, 3 e 4
--
--DROP TABLE OW_LAO.FT_D2C_NERP_LEAD_TIME
--CREATE TABLE OW_LAO.FT_D2C_NERP_LEAD_TIME AS (
SELECT SUBSIDIARY
	,STATE -- indicador 3
	,CITY -- indicador 3
	,DIMPROD_PRODUCT_GROUP
	,DIMPROD_DIVISION
	,DIMPROD_PRODUCT
	,PLANT
	,PLANT_NAME
	,TRANSPORTER_NAME -- Campo de Carrier
	,"YEAR"
	,"QUARTER"
	,"YEAR_MONTH"
	,"WEEK"
	--,SUM(NET_VALUE) AS NET_VALUE
	--,SUM(AR_AMOUNT) AS AR_AMOUNT
	,SUM(TOTAL_PLANNED_GI) AS TOTAL_PLANNED_GI
	,SUM(ACTUAL_GI) AS ACTUAL_GI
	,SUM(PENDING_GI) AS PENDING_GI
	,SUM(ON_TIME_GI) AS ON_TIME_GI
	,SUM(SAME_DAY_GI) AS SAME_DAY_GI
	,AVG("LT_WK_PO_SO") AS "LT_WK_PO_SO"-- Indicador do KPI 6.4.KPI - Operation LT
	,AVG("LT_WK_SO_DO") AS "LT_WK_SO_DO" --indicador 1, 2 e 3
	,AVG("LT_WK_DO_NF") AS "LT_WK_DO_NF"--indicador 2
	,AVG("LT_WK_NF_GI") AS "LT_WK_NF_GI"--indicador 2
	,AVG("LT_WK_DO_GI") AS "LT_WK_DO_GI" --indicador 1 e 3
	,AVG("LT_WK_GI_EPOD") AS "LT_WK_GI_EPOD" --indicador 1, 2 e 3--DI~BILLING 
	--,AVG("LT_WK_DO_PICKING") AS "LT_WK_DO_PICKING"
	--,AVG("LT_WK_PICKING_NF") AS "LT_WK_PICKING_NF"
	--,AVG("LT_WK_PICKING_NF_GI") AS "LT_WK_PICKING_NF_GI"
	,AVG("LT_WK_TOTAL_PO_EPOD") AS "LT_WK_TOTAL_PO_EPOD" -- possivel fazer o calculo aqui AVG(ROUND(("Lead time PO ~ SO"+"Lead time SO ~DO"+"Lead time DO ~GI"+"Lead time GI ~IOD"),1)) AS "TTL L/T" --indicador 3
	,AVG("LT_WK_TOTAL_SO_EPOD") AS "LT_WK_TOTAL_SO_EPOD"
	,AVG("LT_PO_SO") AS "LT_PO_SO"
	,AVG("LT_SO_DO") AS "LT_SO_DO"
	,AVG("LT_DO_NF") AS "LT_DO_NF"
	,AVG("LT_NF_GI") AS "LT_NF_GI"
	,AVG("LT_DO_GI") AS "LT_DO_GI"
	--,AVG("LT_GI_BILLING") AS "LT_GI_BILLING"
	,AVG("LT_GI_EPOD") AS "LT_GI_EPOD"
	--,AVG("LT_DO_PICKING") AS "LT_DO_PICKING"
	--,AVG("LT_PICKING_NF") AS "LT_PICKING_NF"
	--,AVG("LT_PICKING_NF_GI") AS "LT_PICKING_NF_GI"
	,AVG("LT_TOTAL_PO_EPOD") AS "LT_TOTAL_PO_EPOD"
	,AVG("LT_TOTAL_SO_EPOD") AS "LT_TOTAL_SO_EPOD"
	--,AVG("Target LT_PO_SO") AS "Target LT_PO_SO"--indicador 2
	--,AVG("Target LT_SO_DO") AS "Target LT_SO_DO"--indicador 2
	--,AVG("Target LT_DO_GI") AS "Target LT_DO_GI"--indicador 2
	--,AVG("Target LT_GI_IOD") AS "Target LT_GI_IOD"--indicador 2
	--,AVG("Target TTL Lead time") AS "Target TTL Lead time" --indicador 2 e 3
	,AVG("TGT_CAL_PO_SO") AS "TGT_CAL_PO_SO"
	,AVG("TGT_CAL_SO_DO") AS "TGT_CAL_SO_DO"
	,AVG("TGT_CAL_DO_PICKING") AS "TGT_CAL_DO_PICKING"
	,AVG("TGT_CAL_PICKING_NF") AS "TGT_CAL_PICKING_NF"
	,AVG("TGT_CAL_NF_GI") AS "TGT_CAL_NF_GI"
	,AVG("TGT_CAL_GI_IOD") AS "TGT_CAL_GI_IOD"
	,AVG("Target CAL TTL Lead time") AS "Target CAL TTL Lead time"
	
	
	,AVG("TGT_WK_PO_SO") AS "TGT_WK_PO_SO"
	,AVG("TGT_WK_SO_DO") AS "TGT_WK_SO_DO"
	,AVG("TGT_WK_DO_PICKING") AS "TGT_WK_DO_PICKING"
	,AVG("TGT_WK_PICKING_NF") AS "TGT_WK_PICKING_NF"
	,AVG("TGT_WK_NF_GI") AS "TGT_WK_NF_GI"
	,AVG("TGT_WK_GI_IOD") AS "TGT_WK_GI_IOD"
	,AVG("Target WK TTL Lead time") AS "Target WK TTL Lead time"
	
	
	
	,SUM(RECORD_QTY) AS RECORD_QTY 
	,SUM(IOD_QTY) AS IOD_QTY -- indicador 4
	,SUM(OTD_QTY) AS OTD_QTY --indicador 4
	,SUM(OTD_DO_QTY) AS OTD_DO_QTY
	,COUNT(DELIVERY_NO) AS COUNT_DO
	,SUM(OVER_TARGET_QTY_WK) AS OVER_TARGET_QTY_WK
	,SUM(OVER_TARGET_QTY_CAL) AS OVER_TARGET_QTY_CAL
	--,SUM(TARGET_LT_GI_BILLING_WK) AS TARGET_LT_GI_BILLING_WK
	--,SUM(TARGET_LT_GI_BILLING_CAL) AS TARGET_LT_GI_BILLING_CAL
	,SUM(OVER_TGT_QTY_GI_EPOD_WK) AS OVER_TGT_QTY_GI_EPOD_WK
	,SUM(OVER_TGT_QTY_GI_EPOD_CAL) AS OVER_TGT_QTY_GI_EPOD_CAL
	,LAST_UPDATE
	
FROM OW_LAO.TF_D2C_NERP_LEAD_TIME
GROUP BY SUBSIDIARY
	,STATE
	,CITY
	,DIMPROD_PRODUCT_GROUP
	,DIMPROD_DIVISION
	,DIMPROD_PRODUCT
	,PLANT
	,PLANT_NAME
	,TRANSPORTER_NAME
	,"YEAR"
	,"QUARTER"
	,"YEAR_MONTH"
	,"WEEK"
	,LAST_UPDATE
ORDER BY WEEK DESC
--)
;
END
