CREATE PROCEDURE OW_LAO.PROC_CRAWLING_AP1_ESTORE_URL_SKU
LANGUAGE SQLSCRIPT as
BEGIN
/*Se a URL está nas duas tabelas setar o status para ACTIVE*/
UPDATE OW_LAO.MAP_ESTORE_URL_SKU O
SET O.STATUS_SKU = 'ACTIVE',
O.LOAD_DATE = TO_CHAR(NOW())
FROM OW_LAO.MAP_ESTORE_URL_SKU O 
INNER JOIN OW_LAO.TMP_MAP_ESTORE_URL_SKU AS T ON TRIM(O.PROD_HREF) = TRIM(T.PROD_HREF) AND TRIM(UPPER(O.SKU)) = TRIM(UPPER(T.SKU))
;
/*Se a URL está apenas na tabela temporária, adicionar na tabela de MAP --ID_REF_URL é uma primary key */
INSERT INTO OW_LAO.MAP_ESTORE_URL_SKU(AP2,
COMPANY_NAME,
--COUNTRY,
"DESC",
LAST_RUN_DATE, 
LOAD_DATE,
--CURRENCY,
PREMIUM,
PROD_HREF,
PRODUCT_CATEGORY,
PRODUCT_DIVISION,
PRODUCT_FAMILY,
PRODUCT_SERIES,
PRODUCT_SUB_CATEGORY,
SKU,
STATUS_SKU,
COLOR,
MEMORY,
TRADE_IN,
GIFT)
SELECT T.AP2,
T.COMPANY_NAME,
--T.COUNTRY,
T."DESC",
NULL AS LAST_RUN_DATE, 
T.LOAD_DATE,
--T.CURRENCY,
T.PREMIUM,
T.PROD_HREF,
T.PRODUCT_CATEGORY,
T.PRODUCT_DIVISION,
T.PRODUCT_FAMILY,
T.PRODUCT_SERIES,
T.PRODUCT_SUB_CATEGORY,
T.SKU,
'ACTIVE' AS STATUS_SKU,
T.COLOR,
T.MEMORY,
T.TRADE_IN,
T.GIFT
FROM OW_LAO.MAP_ESTORE_URL_SKU AS O
RIGHT JOIN OW_LAO.TMP_MAP_ESTORE_URL_SKU AS T ON (TRIM(O.PROD_HREF) = TRIM(T.PROD_HREF) AND TRIM(UPPER(O.SKU)) = TRIM(UPPER(T.SKU)))
WHERE O.PROD_HREF IS NULL;
/*Se a URL está apenas na tabela de MAP e não estiver na temporária, desativar o campo STATUS_SKU */
UPDATE OW_LAO.MAP_ESTORE_URL_SKU O 
	SET O.STATUS_SKU = 'DISABLED' 
FROM OW_LAO.MAP_ESTORE_URL_SKU O 
LEFT JOIN OW_LAO.TMP_MAP_ESTORE_URL_SKU AS T ON (TRIM(O.PROD_HREF) = TRIM(T.PROD_HREF) AND TRIM(UPPER(O.SKU)) = TRIM(UPPER(T.SKU))) 
WHERE T.PROD_HREF IS NULL
;
 
/*Salvar foto diária na tabela de histórico e utilizazada para a primeira transformation*/
INSERT INTO OW_LAO.MAP_ESTORE_URL_SKU_HISTORICAL (
SELECT ID_REF_URL,
	 AP2,
	 COMPANY_NAME,
--	 COUNTRY,
	 "DESC",
	 LAST_RUN_DATE,
	 LOAD_DATE,
--	 CURRENCY,
	 PREMIUM,
	 PROD_HREF,
	 PRODUCT_CATEGORY,
	 PRODUCT_DIVISION,
	 PRODUCT_FAMILY,
	 PRODUCT_SERIES,
	 PRODUCT_SUB_CATEGORY,
	 SKU,
	 STATUS_SKU,
	 COLOR,
	 MEMORY,
	 TRADE_IN,
	 GIFT,
	 NOW()
	 FROM OW_LAO.MAP_ESTORE_URL_SKU
);
/*Trunca a tabela OW_LAO.TF_CRAWLING_AP1_ESTORE_URL_SKU_1*/
TRUNCATE TABLE OW_LAO.TF_CRAWLING_AP1_ESTORE_URL_SKU_1;
/*Transformation - Cruza as informações da ODS e MAP_HIST por HREF SKU, LOAD_DATE*/
INSERT INTO OW_LAO.TF_CRAWLING_AP1_ESTORE_URL_SKU_1
(SELECT DISTINCT
    P.AP2 AS SUBSIDIARY,
	P.COUNTRY AS COUNTRY,
	P.SKU AS SKU,
	P."DESC" AS MODEL_DESC,	 
	P.COMPANY_NAME AS SITE_COMPANY_NAME,
	P.TODAY_DATE AS REFER_DATE,
	SUBSTRING(P."DE_VALUE",0,16) AS RETAIL_PRICE_BASE,--"retail_price_base"
    SUBSTRING(P."POR_VALUE",0,16) AS RETAIL_PRICE_ACTUAL, --"retail_price_actual"
    SUBSTRING(P."PROD_HREF",0,499) AS SITE_URL, --"site_url"
    SUBSTRING(P."CURRENCY",0,99) AS SITE_PRICE_CURRENCY,--"site_price_currency" SUBSTRING(D."CURRENCY",0,99) AS SITE_PRICE_CURRENCY
	D.PRODUCT_DIVISION AS PRODUCT_DIVISION,
	D.PRODUCT_CATEGORY AS PRODUCT_CATEGORY,
	D.PRODUCT_SUB_CATEGORY AS PRODUCT_SUB_CATEGORY,
	D.PRODUCT_FAMILY AS PRODUCT_FAMILY,
	D.PRODUCT_SERIES AS PRODUCT_SERIES,
	D.PREMIUM AS PREMIUM,
	CASE WHEN TRIM(UPPER(P.PROD_HREF)) <> TRIM(UPPER(P.PROD_HREF_OUT)) THEN 
       'URL  Redirected'
       ELSE P.STATUS_SITE END AS STATUS_SITE  
	
FROM OW_LAO.ODS_CRAWLING_AP1_ESTORE_DAILY_PRICE P		
INNER JOIN OW_LAO.MAP_ESTORE_URL_SKU_HISTORICAL D 
ON  TRIM(UPPER(P.PROD_HREF)) = TRIM(UPPER(D.PROD_HREF)) AND TRIM(UPPER(P.SKU)) = TRIM(UPPER(D.SKU))  AND 
TO_CHAR(P."TODAY_DATE", 'YYYY-MM-DD') = TO_CHAR(D."LOAD_DATE", 'YYYY-MM-DD')
WHERE 1=1
AND to_char(P."TODAY_DATE", 'YYYY-MM-DD')  < to_char(CURRENT_DATE, 'YYYY-MM-DD')
);
UPDATE OW_LAO.TF_CRAWLING_AP1_ESTORE_URL_SKU_1
SET
RETAIL_PRICE_BASE = SUBSTRING_REGEXPR('\d+(\.\d{1,2})?' IN UPPER(TRIM(RETAIL_PRICE_BASE)) FROM 1 OCCURRENCE 1) ,
RETAIL_PRICE_ACTUAL = SUBSTRING_REGEXPR('\d+(\.\d{1,2})?' IN UPPER(TRIM(RETAIL_PRICE_ACTUAL)) FROM 1 OCCURRENCE 1) 
;  
/*Trunca a tabela OW_LAO.TF_CRAWLING_AP1_ESTORE_URL_SKU_2*/
TRUNCATE TABLE OW_LAO.TF_CRAWLING_AP1_ESTORE_URL_SKU_2;
/*Agrupando a tabela para gerar o MAX dos campos PRICE_LOCAL_BASE e PRICE_LOCAL_ACT*/
INSERT INTO OW_LAO.TF_CRAWLING_AP1_ESTORE_URL_SKU_2
(SELECT
	SUBSIDIARY,
	COUNTRY,
	SKU,
	MODEL_DESC,	 
	SITE_COMPANY_NAME,
	REFER_DATE,
	SITE_URL, --"site_url"
    SITE_PRICE_CURRENCY,--"site_price_currency"
	PRODUCT_DIVISION,
	PRODUCT_CATEGORY,
	PRODUCT_SUB_CATEGORY,
	PRODUCT_FAMILY,
	PRODUCT_SERIES,
	PREMIUM,
	STATUS_SITE,  	
	ROUND(MAX(RETAIL_PRICE_BASE),2) as PRICE_LOCAL_FROM, --PRICE_LOCAL_BASE,
	ROUND(MAX(RETAIL_PRICE_ACTUAL),2) as PRICE_LOCAL_TO --PRICE_LOCAL_ACT
	FROM OW_LAO.TF_CRAWLING_AP1_ESTORE_URL_SKU_1
GROUP BY 
	SUBSIDIARY,
	COUNTRY,
	SKU,
	MODEL_DESC,	 
	SITE_COMPANY_NAME,
	REFER_DATE,
	SITE_URL, --"site_url"
    SITE_PRICE_CURRENCY,--"site_price_currency"
	PRODUCT_DIVISION,
	PRODUCT_CATEGORY,
	PRODUCT_SUB_CATEGORY,
	PRODUCT_FAMILY,
	PRODUCT_SERIES,
	PREMIUM,
	STATUS_SITE
);
-- TRUNCAR TABELA DE VALIDAÇÃO DE PREÇO
TRUNCATE TABLE OW_LAO.TF_CRAWLING_AP1_ESTORE_DAILY_PRICE_AUX;
-- INSERIR DADOS PARA VALIDAÇÃO DE PREÇO
INSERT INTO OW_LAO.TF_CRAWLING_AP1_ESTORE_DAILY_PRICE_AUX (
-- 31 Script para gerar a tabela auxiliar. Ordenando por REFER_DATE, SUNSIDIARY, SKU,ROW_NUM
	SELECT DISTINCT * FROM (
-- 30 UNION ENTRE VALID NULL E VALID NOT NULL 	
SELECT 
            J.SUBSIDIARY, 
          J.SKU, 
          J.REFER_DATE, 
          J.SUBSIDIARY_2, 
          J.SKU_2, 
          J.DATE_2, 
          J.VALID_PRICE_SAMSUNG, 
          J.VALID_PRICE_VAREJO, 
          J.VALID_FINAL, 
          J.ROW_NUM,
--        SUB_TO_JOIN, 
--        SKU_TO_JOIN, 
--        DATE_TO_JOIN, 
          J.MAX_TO_JOIN,
          COALESCE(K.VALID,'NOK VAREJO') AS VALID
FROM (
-- 19 CRIANDO CAMPO VALID A PARTIR DOS CAMPOS O(ROW_NUM E VALID_FINAL) E D(MAX_TO_JOIN)	
				SELECT DISTINCT  O.SUBSIDIARY, 
				          O.SKU, 
				          O.REFER_DATE, 
				          O.SUBSIDIARY_2, 
				          O.SKU_2, 
				          O.DATE_2, 
				          O.VALID_PRICE_SAMSUNG, 
				          O.VALID_PRICE_VAREJO, 
				          O.VALID_FINAL, 
				          O.ROW_NUM,
				--        D.SUB_TO_JOIN, 
				--        D.SKU_TO_JOIN, 
				--        D.DATE_TO_JOIN, 
				          D.MAX_TO_JOIN,
				CASE 
				WHEN D.MAX_TO_JOIN = 1 THEN O.VALID_FINAL 
				WHEN O.VALID_PRICE_SAMSUNG IS NULL OR O.VALID_PRICE_SAMSUNG = 'NOK' THEN 'NOK SAMSUNG'
				WHEN D.MAX_TO_JOIN = 2 AND (ROW_NUM = 1 OR ROW_NUM = 2) AND O.VALID_FINAL IN ('OK') THEN 'OK' 
				--WHEN D.MAX_TO_JOIN = 2 AND (O.VALID_PRICE_VAREJO = 'NOK') THEN 'NOK'
				WHEN D.MAX_TO_JOIN = 3 AND (ROW_NUM = 1 OR ROW_NUM = 2 OR ROW_NUM = 3) AND O.VALID_FINAL IN ('OK') THEN 'OK' 
				
				ELSE NULL END AS VALID          
				         
				FROM
				(
-- 13 CASE ENTRE VALID_PRICE_SAMSUNG E VALID_PRICE_VAREJO E ROW_NUM COMO UM CONTADOR PARA OS RETAILS DIFERENTES
					SELECT DISTINCT M.SUBSIDIARY, M.SKU, M.REFER_DATE, 
					N.SUBSIDIARY AS SUBSIDIARY_2, N.SKU AS SKU_2, N.REFER_DATE AS DATE_2,
					M.VALID_PRICE_SAMSUNG,N.VALID_PRICE_VAREJO,
					
					CASE 
					WHEN M.VALID_PRICE_SAMSUNG = 'OK' AND N.VALID_PRICE_VAREJO = 'OK' THEN 'OK'
					WHEN (M.VALID_PRICE_SAMSUNG = 'NOK' OR M.VALID_PRICE_SAMSUNG IS NULL)
					AND (N.VALID_PRICE_VAREJO = 'NOK' OR N.VALID_PRICE_VAREJO IS NULL) THEN 'NOK AMBOS'
					WHEN M.VALID_PRICE_SAMSUNG = 'OK' AND (N.VALID_PRICE_VAREJO = 'NOK' OR N.VALID_PRICE_VAREJO IS NULL) THEN 'NOK VAREJO'
					WHEN N.VALID_PRICE_VAREJO = 'OK' AND (M.VALID_PRICE_SAMSUNG = 'NOK' OR M.VALID_PRICE_SAMSUNG IS NULL) THEN 'NOK SAMSUNG'
					END VALID_FINAL
					       
					, ROW_NUMBER() OVER (PARTITION BY COALESCE(M.SUBSIDIARY,N.SUBSIDIARY), COALESCE(M.SKU,N.SKU), COALESCE(M.REFER_DATE,N.REFER_DATE)
					ORDER BY COALESCE(M.REFER_DATE,N.REFER_DATE) DESC, COALESCE(M.SUBSIDIARY,N.SUBSIDIARY), COALESCE(M.SKU,N.SKU) ASC) as ROW_NUM
					       
					
					FROM 
-- 11 VALIDAR SE O PRICE_LOCAL_TO PARA PRODUTOS SAMSUNG É VALIDO
						(SELECT DISTINCT SUBSIDIARY, SITE_COMPANY_NAME, SKU, PRICE_LOCAL_TO, REFER_DATE,
						CASE WHEN PRICE_LOCAL_TO IS NOT NULL  THEN 'OK'
						ELSE 'NOK' 
						END AS VALID_PRICE_SAMSUNG
						FROM OW_LAO.VW_CRAWLING_AP1_ESTORE_DAILY_PRICE
						WHERE SITE_COMPANY_NAME LIKE '%SAMSUNG%') M
-- 11 VALIDAR SE O PRICE_LOCAL_TO PARA PRODUTOS SAMSUNG É VALIDO
FULL OUTER JOIN
-- 12 VALIDAR SE O PRICE_LOCAL_TO PARA PRODUTOS DIFERENTE DE SAMSUNG É VALIDO E FAZ UM FULL OUTER JOIN CONSIDERANDO OS CAMPOS DE: SUBSIDIARY, SKU, REFER_DATE
						(SELECT DISTINCT SUBSIDIARY, SITE_COMPANY_NAME, SKU, PRICE_LOCAL_TO, REFER_DATE,
						CASE WHEN PRICE_LOCAL_TO IS NOT NULL  THEN 'OK'
						ELSE 'NOK' 
						END AS VALID_PRICE_VAREJO
						FROM OW_LAO.VW_CRAWLING_AP1_ESTORE_DAILY_PRICE
						WHERE SITE_COMPANY_NAME NOT LIKE '%SAMSUNG%') N     
-- 12 VALIDAR SE O PRICE_LOCAL_TO PARA PRODUTOS DIFERENTE DE SAMSUNG É VALIDO E FAZ UM FULL OUTER JOIN CONSIDERANDO OS CAMPOS DE: SUBSIDIARY, SKU, REFER_DATE
					ON (UPPER(TRIM(M.SUBSIDIARY)) = UPPER(TRIM(N.SUBSIDIARY)) AND UPPER(TRIM(M.SKU)) = UPPER(TRIM(N.SKU)) AND M.REFER_DATE = N.REFER_DATE)
					ORDER BY COALESCE(M.REFER_DATE,N.REFER_DATE) DESC, COALESCE(M.SUBSIDIARY,N.SUBSIDIARY), COALESCE(M.SKU,N.SKU) ASC,ROW_NUM ASC 
) AS O
-- 13 CASE ENTRE VALID_PRICE_SAMSUNG E VALID_PRICE_VAREJO E ROW_NUM COMO UM CONTADOR PARA OS RETAILS DIFERENTES
LEFT JOIN
-- 17 CONTADOR DE MAX RETAIL POR SKU, SUB, DATA
				(
				SELECT COALESCE(SUBSIDIARY,SUBSIDIARY_2) AS SUB_TO_JOIN ,COALESCE(SKU,SKU_2) AS SKU_TO_JOIN,COALESCE(REFER_DATE,DATE_2) 
				AS DATE_TO_JOIN,
				MAX(ROW_NUM) AS MAX_TO_JOIN
				
				FROM   
				(
-- 16 CASE ENTRE VALID_PRICE_SAMSUNG E VALID_PRICE_VAREJO E ROW_NUM COMO UM CONTADOR PARA OS RETAILS DIFERENTES
					SELECT DISTINCT A.SUBSIDIARY,  A.SKU,  A.REFER_DATE, 
					B.SUBSIDIARY AS SUBSIDIARY_2,  B.SKU AS SKU_2,  B.REFER_DATE AS DATE_2,
					A.VALID_PRICE_SAMSUNG,B.VALID_PRICE_VAREJO,
					CASE 
					WHEN A.VALID_PRICE_SAMSUNG = 'OK' AND B.VALID_PRICE_VAREJO = 'OK' THEN 'OK'
					WHEN (A.VALID_PRICE_SAMSUNG = 'NOK' OR A.VALID_PRICE_SAMSUNG IS NULL)
					AND (B.VALID_PRICE_VAREJO = 'NOK' OR B.VALID_PRICE_VAREJO IS NULL) THEN 'NOK AMBOS'
					WHEN A.VALID_PRICE_SAMSUNG = 'OK' AND (B.VALID_PRICE_VAREJO = 'NOK' OR B.VALID_PRICE_VAREJO IS NULL) THEN 'NOK VAREJO'
					WHEN B.VALID_PRICE_VAREJO = 'OK' AND (A.VALID_PRICE_SAMSUNG = 'NOK' OR A.VALID_PRICE_SAMSUNG IS NULL) THEN 'NOK SAMSUNG'
					END VALID_FINAL
					       
					, ROW_NUMBER() OVER (PARTITION BY COALESCE(A.SUBSIDIARY,B.SUBSIDIARY), COALESCE(A.SKU,B.SKU), COALESCE(A.REFER_DATE,B.REFER_DATE)
					ORDER BY COALESCE(A.REFER_DATE,B.REFER_DATE) DESC, COALESCE(A.SUBSIDIARY,B.SUBSIDIARY), COALESCE(A.SKU,B.SKU) ASC) as ROW_NUM
					       
					
					FROM 
-- 14 VALIDAR SE O PRICE_LOCAL_TO PARA PRODUTOS SAMSUNG É VALIDO
						(SELECT DISTINCT SUBSIDIARY, SITE_COMPANY_NAME, SKU, PRICE_LOCAL_TO, REFER_DATE,
						CASE WHEN PRICE_LOCAL_TO IS NOT NULL  THEN 'OK'
						ELSE 'NOK' 
						END AS VALID_PRICE_SAMSUNG
						
						FROM OW_LAO.VW_CRAWLING_AP1_ESTORE_DAILY_PRICE
						WHERE SITE_COMPANY_NAME LIKE '%SAMSUNG%') A
-- 14 VALIDAR SE O PRICE_LOCAL_TO PARA PRODUTOS SAMSUNG É VALIDO
FULL OUTER JOIN
-- 15 VALIDAR SE O PRICE_LOCAL_TO PARA PRODUTOS DIFERENTE DE SAMSUNG É VALIDO E FAZ UM FULL OUTER JOIN CONSIDERANDO OS CAMPOS DE: SUBSIDIARY, SKU, REFER_DATE
						(SELECT DISTINCT SUBSIDIARY, SITE_COMPANY_NAME, SKU, PRICE_LOCAL_TO, REFER_DATE,
						CASE WHEN PRICE_LOCAL_TO IS NOT NULL  THEN 'OK'
						ELSE 'NOK' END AS VALID_PRICE_VAREJO
						
						FROM OW_LAO.VW_CRAWLING_AP1_ESTORE_DAILY_PRICE
						WHERE SITE_COMPANY_NAME NOT LIKE '%SAMSUNG%') B
-- 15 VALIDAR SE O PRICE_LOCAL_TO PARA PRODUTOS DIFERENTE DE SAMSUNG É VALIDO E FAZ UM FULL OUTER JOIN CONSIDERANDO OS CAMPOS DE: SUBSIDIARY, SKU, REFER_DATE						
					ON (UPPER(TRIM(A.SUBSIDIARY)) = UPPER(TRIM(B.SUBSIDIARY))
					AND UPPER(TRIM(A.SKU)) = UPPER(TRIM(B.SKU))
					AND A.REFER_DATE = B.REFER_DATE)
					ORDER BY COALESCE(A.REFER_DATE,B.REFER_DATE) DESC, COALESCE(A.SUBSIDIARY,B.SUBSIDIARY), COALESCE(A.SKU,B.SKU) ASC,ROW_NUM ASC
					) AS C 
-- 16 CASE ENTRE VALID_PRICE_SAMSUNG E VALID_PRICE_VAREJO E ROW_NUM COMO UM CONTADOR PARA OS RETAILS DIFERENTES
					GROUP BY COALESCE(SUBSIDIARY,SUBSIDIARY_2),COALESCE(SKU,SKU_2),COALESCE(REFER_DATE,DATE_2)
				) AS D
-- 17 CONTADOR DE MAX RETAIL POR SKU, SUB, DATA
-- 18 JOIN ENTRE O PROCESSO 13 E O PROCESSO 17.		
				ON 
				(COALESCE(O.SUBSIDIARY,O.SUBSIDIARY_2) = D.SUB_TO_JOIN)
				AND (COALESCE(O.SKU,O.SKU_2) = D.SKU_TO_JOIN)
				AND (COALESCE(O.REFER_DATE,O.DATE_2) = D.DATE_TO_JOIN)
				ORDER BY COALESCE(O.REFER_DATE,O.DATE_2) DESC, 
				              COALESCE(O.SUBSIDIARY,O.SUBSIDIARY_2), 
				              COALESCE(O.SKU,O.SKU_2) ASC,
				             O.ROW_NUM ASC  
-- 18 JOIN ENTRE O PROCESSO 13 E O PROCESSO 17.  
-- 19 CRIANDO CAMPO VALID A PARTIR DOS CAMPOS O(ROW_NUM E VALID_FINAL) E D(MAX_TO_JOIN)	           
				) J 
LEFT JOIN 
-- 10 SELECIONA SUB, SKU, REFER_DATE E VALID ONDE O VALID NÃO É NULO.
		(	
		SELECT DISTINCT COALESCE(SUBSIDIARY,SUBSIDIARY_2) AS SUB , 
		COALESCE(SKU,SKU_2) AS SKU,
		COALESCE(REFER_DATE,DATE_2) AS REFER_DATE,
		VALID
		
		
		
		
		
		FROM (
-- 9 CRIANDO CAMPO VALID A PARTIR DOS CAMPOS O(ROW_NUM E VALID_FINAL) E D(MAX_TO_JOIN)
				SELECT DISTINCT O.SUBSIDIARY, 
				          O.SKU, 
				          O.REFER_DATE, 
				          O.SUBSIDIARY_2, 
				          O.SKU_2, 
				          O.DATE_2, 
				          O.VALID_PRICE_SAMSUNG, 
				          O.VALID_PRICE_VAREJO, 
				          O.VALID_FINAL, 
				          O.ROW_NUM,
				--        D.SUB_TO_JOIN, 
				--        D.SKU_TO_JOIN, 
				--        D.DATE_TO_JOIN, 
				          D.MAX_TO_JOIN,
				CASE 
				WHEN D.MAX_TO_JOIN = 1 THEN O.VALID_FINAL 
				WHEN O.VALID_PRICE_SAMSUNG IS NULL OR O.VALID_PRICE_SAMSUNG = 'NOK' THEN 'NOK SAMSUNG'
				WHEN D.MAX_TO_JOIN = 2 AND (ROW_NUM = 1 OR ROW_NUM = 2) AND O.VALID_FINAL IN ('OK') THEN 'OK' -- VALIDAR
				--WHEN D.MAX_TO_JOIN = 2 AND (O.VALID_PRICE_VAREJO = 'NOK') THEN 'NOK'
				WHEN D.MAX_TO_JOIN = 3 AND (ROW_NUM = 1 OR ROW_NUM = 2 OR ROW_NUM = 3) AND O.VALID_FINAL IN ('OK') THEN 'OK' -- VALIDAR
				
				ELSE NULL END AS VALID          
				         
				FROM
				(
-- 3 CASE ENTRE VALID_PRICE_SAMSUNG E VALID_PRICE_VAREJO E ROW_NUM COMO UM CONTADOR PARA OS RETAILS DIFERENTES
					SELECT DISTINCT M.SUBSIDIARY, M.SKU, M.REFER_DATE, 
					N.SUBSIDIARY AS SUBSIDIARY_2, N.SKU AS SKU_2, N.REFER_DATE AS DATE_2,
					M.VALID_PRICE_SAMSUNG,N.VALID_PRICE_VAREJO,
					
					CASE 
					WHEN M.VALID_PRICE_SAMSUNG = 'OK' AND N.VALID_PRICE_VAREJO = 'OK' THEN 'OK'
					WHEN (M.VALID_PRICE_SAMSUNG = 'NOK' OR M.VALID_PRICE_SAMSUNG IS NULL)
					AND (N.VALID_PRICE_VAREJO = 'NOK' OR N.VALID_PRICE_VAREJO IS NULL) THEN 'NOK AMBOS'
					WHEN M.VALID_PRICE_SAMSUNG = 'OK' AND (N.VALID_PRICE_VAREJO = 'NOK' OR N.VALID_PRICE_VAREJO IS NULL) THEN 'NOK VAREJO'
					WHEN N.VALID_PRICE_VAREJO = 'OK' AND (M.VALID_PRICE_SAMSUNG = 'NOK' OR M.VALID_PRICE_SAMSUNG IS NULL) THEN 'NOK SAMSUNG'
					END VALID_FINAL
					       
					, ROW_NUMBER() OVER (PARTITION BY COALESCE(M.SUBSIDIARY,N.SUBSIDIARY), COALESCE(M.SKU,N.SKU), COALESCE(M.REFER_DATE,N.REFER_DATE)
					ORDER BY COALESCE(M.REFER_DATE,N.REFER_DATE) DESC, COALESCE(M.SUBSIDIARY,N.SUBSIDIARY), COALESCE(M.SKU,N.SKU) ASC) as ROW_NUM
					       
					
					FROM 
-- 1 VALIDAR SE O PRICE_LOCAL_TO PARA PRODUTOS SAMSUNG É VALIDO
						(SELECT DISTINCT SUBSIDIARY, SITE_COMPANY_NAME, SKU, PRICE_LOCAL_TO, REFER_DATE,
						CASE WHEN PRICE_LOCAL_TO IS NOT NULL  THEN 'OK'
						ELSE 'NOK' 
						END AS VALID_PRICE_SAMSUNG
						FROM OW_LAO.VW_CRAWLING_AP1_ESTORE_DAILY_PRICE
						WHERE SITE_COMPANY_NAME LIKE '%SAMSUNG%') M
-- 1 VALIDAR SE O PRICE_LOCAL_TO PARA PRODUTOS SAMSUNG É VALIDO
						
FULL OUTER JOIN
-- 2 VALIDAR SE O PRICE_LOCAL_TO PARA PRODUTOS DIFERENTE DE SAMSUNG É VALIDO E FAZ UM FULL OUTER JOIN CONSIDERANDO OS CAMPOS DE: SUBSIDIARY, SKU, REFER_DATE
						(SELECT DISTINCT SUBSIDIARY, SITE_COMPANY_NAME, SKU, PRICE_LOCAL_TO, REFER_DATE,
						CASE WHEN PRICE_LOCAL_TO IS NOT NULL  THEN 'OK'
						ELSE 'NOK' 
						END AS VALID_PRICE_VAREJO
						FROM OW_LAO.VW_CRAWLING_AP1_ESTORE_DAILY_PRICE
						WHERE SITE_COMPANY_NAME NOT LIKE '%SAMSUNG%') N     
						
						         
						ON (UPPER(TRIM(M.SUBSIDIARY)) = UPPER(TRIM(N.SUBSIDIARY)) AND UPPER(TRIM(M.SKU)) = UPPER(TRIM(N.SKU)) AND M.REFER_DATE = N.REFER_DATE)
						ORDER BY COALESCE(M.REFER_DATE,N.REFER_DATE) DESC, COALESCE(M.SUBSIDIARY,N.SUBSIDIARY), COALESCE(M.SKU,N.SKU) ASC,ROW_NUM ASC
-- 2 VALIDAR SE O PRICE_LOCAL_TO PARA PRODUTOS DIFERENTE DE SAMSUNG É VALIDO E FAZ UM FULL OUTER JOIN CONSIDERANDO OS CAMPOS DE: SUBSIDIARY, SKU, REFER_DATE
					) AS O
-- 3 CASE ENTRE VALID_PRICE_SAMSUNG E VALID_PRICE_VAREJO E ROW_NUM COMO UM CONTADOR PARA OS RETAILS DIFERENTES
LEFT JOIN
-- 7 CONTADOR DE MAX RETAIL POR SKU, SUB, DATA
				(
				SELECT COALESCE(SUBSIDIARY,SUBSIDIARY_2) AS SUB_TO_JOIN ,COALESCE(SKU,SKU_2) AS SKU_TO_JOIN,COALESCE(REFER_DATE,DATE_2) 
				AS DATE_TO_JOIN,
				MAX(ROW_NUM) AS MAX_TO_JOIN
				
				FROM   
				(
-- 6 CASE ENTRE VALID_PRICE_SAMSUNG E VALID_PRICE_VAREJO E ROW_NUM COMO UM CONTADOR PARA OS RETAILS DIFERENTES
					SELECT DISTINCT A.SUBSIDIARY,  A.SKU,  A.REFER_DATE, 
					B.SUBSIDIARY AS SUBSIDIARY_2,  B.SKU AS SKU_2,  B.REFER_DATE AS DATE_2,
					A.VALID_PRICE_SAMSUNG,B.VALID_PRICE_VAREJO,
					CASE 
					WHEN A.VALID_PRICE_SAMSUNG = 'OK' AND B.VALID_PRICE_VAREJO = 'OK' THEN 'OK'
					WHEN (A.VALID_PRICE_SAMSUNG = 'NOK' OR A.VALID_PRICE_SAMSUNG IS NULL)
					AND (B.VALID_PRICE_VAREJO = 'NOK' OR B.VALID_PRICE_VAREJO IS NULL) THEN 'NOK AMBOS'
					WHEN A.VALID_PRICE_SAMSUNG = 'OK' AND (B.VALID_PRICE_VAREJO = 'NOK' OR B.VALID_PRICE_VAREJO IS NULL) THEN 'NOK VAREJO'
					WHEN B.VALID_PRICE_VAREJO = 'OK' AND (A.VALID_PRICE_SAMSUNG = 'NOK' OR A.VALID_PRICE_SAMSUNG IS NULL) THEN 'NOK SAMSUNG'
					END VALID_FINAL
					       
					, ROW_NUMBER() OVER (PARTITION BY COALESCE(A.SUBSIDIARY,B.SUBSIDIARY), COALESCE(A.SKU,B.SKU), COALESCE(A.REFER_DATE,B.REFER_DATE)
					ORDER BY COALESCE(A.REFER_DATE,B.REFER_DATE) DESC, COALESCE(A.SUBSIDIARY,B.SUBSIDIARY), COALESCE(A.SKU,B.SKU) ASC) as ROW_NUM
					       
					
					FROM 
-- 4 VALIDAR SE O PRICE_LOCAL_TO PARA PRODUTOS SAMSUNG É VALIDO
						(SELECT DISTINCT SUBSIDIARY, SITE_COMPANY_NAME, SKU, PRICE_LOCAL_TO, REFER_DATE,
						CASE WHEN PRICE_LOCAL_TO IS NOT NULL  THEN 'OK'
						ELSE 'NOK' 
						END AS VALID_PRICE_SAMSUNG
						
						FROM OW_LAO.VW_CRAWLING_AP1_ESTORE_DAILY_PRICE
						WHERE SITE_COMPANY_NAME LIKE '%SAMSUNG%') A
-- 4 VALIDAR SE O PRICE_LOCAL_TO PARA PRODUTOS SAMSUNG É VALIDO
					FULL OUTER JOIN
-- 5 VALIDAR SE O PRICE_LOCAL_TO PARA PRODUTOS DIFERENTE DE SAMSUNG É VALIDO E FAZ UM FULL OUTER JOIN CONSIDERANDO OS CAMPOS DE: SUBSIDIARY, SKU, REFER_DATE
						(SELECT DISTINCT SUBSIDIARY, SITE_COMPANY_NAME, SKU, PRICE_LOCAL_TO, REFER_DATE,
						CASE WHEN PRICE_LOCAL_TO IS NOT NULL  THEN 'OK'
						ELSE 'NOK' END AS VALID_PRICE_VAREJO
						
						FROM OW_LAO.VW_CRAWLING_AP1_ESTORE_DAILY_PRICE
						WHERE SITE_COMPANY_NAME NOT LIKE '%SAMSUNG%') B   
-- 5 VALIDAR SE O PRICE_LOCAL_TO PARA PRODUTOS DIFERENTE DE SAMSUNG É VALIDO E FAZ UM FULL OUTER JOIN CONSIDERANDO OS CAMPOS DE: SUBSIDIARY, SKU, REFER_DATE
					ON (UPPER(TRIM(A.SUBSIDIARY)) = UPPER(TRIM(B.SUBSIDIARY))
					AND UPPER(TRIM(A.SKU)) = UPPER(TRIM(B.SKU))
					AND A.REFER_DATE = B.REFER_DATE)
					ORDER BY COALESCE(A.REFER_DATE,B.REFER_DATE) DESC, COALESCE(A.SUBSIDIARY,B.SUBSIDIARY), COALESCE(A.SKU,B.SKU) ASC,ROW_NUM ASC
					) AS C 			
-- 6 CASE ENTRE VALID_PRICE_SAMSUNG E VALID_PRICE_VAREJO E ROW_NUM COMO UM CONTADOR PARA OS RETAILS DIFERENTES
				GROUP BY COALESCE(SUBSIDIARY,SUBSIDIARY_2),COALESCE(SKU,SKU_2),COALESCE(REFER_DATE,DATE_2)
				) AS D
-- 7 CONTADOR DE MAX RETAIL POR SKU, SUB, DATA
				
-- 8 JOIN ENTRE O PROCESSO 3 E O PROCESSO 7.
			ON 
			(COALESCE(O.SUBSIDIARY,O.SUBSIDIARY_2) = D.SUB_TO_JOIN)
			AND (COALESCE(O.SKU,O.SKU_2) = D.SKU_TO_JOIN)
			AND (COALESCE(O.REFER_DATE,O.DATE_2) = D.DATE_TO_JOIN)
			ORDER BY COALESCE(O.REFER_DATE,O.DATE_2) DESC, 
			              COALESCE(O.SUBSIDIARY,O.SUBSIDIARY_2), 
			              COALESCE(O.SKU,O.SKU_2) ASC,
			             O.ROW_NUM ASC  
-- 8 JOIN ENTRE O PROCESSO 3 E O PROCESSO 7.		
-- 9 CRIANDO CAMPO VALID A PARTIR DOS CAMPOS O(ROW_NUM E VALID_FINAL) E D(MAX_TO_JOIN)	             
				)		
				WHERE VALID IS NOT NULL) K 
-- 10 SELECIONA SUB, SKU, REFER_DATE E VALID ONDE O VALID NÃO É NULO.
		ON ((COALESCE(J.SUBSIDIARY,J.SUBSIDIARY_2) = K.SUB) AND (COALESCE(J.SKU,J.SKU_2) = K.SKU) AND (COALESCE(J.REFER_DATE,J.DATE_2) = K.REFER_DATE))
		WHERE J.VALID IS NULL
UNION ALL 
SELECT DISTINCT  * FROM 
(
-- 29 CRIANDO CAMPO VALID A PARTIR DOS CAMPOS O(ROW_NUM E VALID_FINAL) E D(MAX_TO_JOIN)	
			SELECT DISTINCT O.SUBSIDIARY, 
			          O.SKU, 
			          O.REFER_DATE, 
			          O.SUBSIDIARY_2, 
			          O.SKU_2, 
			          O.DATE_2, 
			          O.VALID_PRICE_SAMSUNG, 
			          O.VALID_PRICE_VAREJO, 
			          O.VALID_FINAL, 
			          O.ROW_NUM,
			--        D.SUB_TO_JOIN, 
			--        D.SKU_TO_JOIN, 
			--        D.DATE_TO_JOIN, 
			          D.MAX_TO_JOIN,
			CASE 
			WHEN D.MAX_TO_JOIN = 1 THEN O.VALID_FINAL 
			WHEN O.VALID_PRICE_SAMSUNG IS NULL OR O.VALID_PRICE_SAMSUNG = 'NOK' THEN 'NOK SAMSUNG'
			WHEN D.MAX_TO_JOIN = 2 AND (ROW_NUM = 1 OR ROW_NUM = 2) AND O.VALID_FINAL IN ('OK') THEN 'OK' 
			--WHEN D.MAX_TO_JOIN = 2 AND (O.VALID_PRICE_VAREJO = 'NOK') THEN 'NOK'
			WHEN D.MAX_TO_JOIN = 3 AND (ROW_NUM = 1 OR ROW_NUM = 2 OR ROW_NUM = 3) AND O.VALID_FINAL IN ('OK') THEN 'OK' 
			
			ELSE NULL END AS VALID          
			         
			FROM
-- 23 CASE ENTRE VALID_PRICE_SAMSUNG E VALID_PRICE_VAREJO E ROW_NUM COMO UM CONTADOR PARA OS RETAILS DIFERENTES         
					(SELECT DISTINCT M.SUBSIDIARY, M.SKU, M.REFER_DATE, 
					N.SUBSIDIARY AS SUBSIDIARY_2, N.SKU AS SKU_2, N.REFER_DATE AS DATE_2,
					M.VALID_PRICE_SAMSUNG,N.VALID_PRICE_VAREJO,
					
					CASE 
					WHEN M.VALID_PRICE_SAMSUNG = 'OK' AND N.VALID_PRICE_VAREJO = 'OK' THEN 'OK'
					WHEN (M.VALID_PRICE_SAMSUNG = 'NOK' OR M.VALID_PRICE_SAMSUNG IS NULL)
					AND (N.VALID_PRICE_VAREJO = 'NOK' OR N.VALID_PRICE_VAREJO IS NULL) THEN 'NOK AMBOS'
					WHEN M.VALID_PRICE_SAMSUNG = 'OK' AND (N.VALID_PRICE_VAREJO = 'NOK' OR N.VALID_PRICE_VAREJO IS NULL) THEN 'NOK VAREJO'
					WHEN N.VALID_PRICE_VAREJO = 'OK' AND (M.VALID_PRICE_SAMSUNG = 'NOK' OR M.VALID_PRICE_SAMSUNG IS NULL) THEN 'NOK SAMSUNG'
					END VALID_FINAL
					       
					, ROW_NUMBER() OVER (PARTITION BY COALESCE(M.SUBSIDIARY,N.SUBSIDIARY), COALESCE(M.SKU,N.SKU), COALESCE(M.REFER_DATE,N.REFER_DATE)
					ORDER BY COALESCE(M.REFER_DATE,N.REFER_DATE) DESC, COALESCE(M.SUBSIDIARY,N.SUBSIDIARY), COALESCE(M.SKU,N.SKU) ASC) as ROW_NUM
					       
					FROM 
-- 21 VALIDAR SE O PRICE_LOCAL_TO PARA PRODUTOS SAMSUNG É VALIDO
						(SELECT DISTINCT SUBSIDIARY, SITE_COMPANY_NAME, SKU, PRICE_LOCAL_TO, REFER_DATE,
						CASE WHEN PRICE_LOCAL_TO IS NOT NULL  THEN 'OK'
						ELSE 'NOK' 
						END AS VALID_PRICE_SAMSUNG
						FROM OW_LAO.VW_CRAWLING_AP1_ESTORE_DAILY_PRICE
						WHERE SITE_COMPANY_NAME LIKE '%SAMSUNG%') M
-- 21 VALIDAR SE O PRICE_LOCAL_TO PARA PRODUTOS SAMSUNG É VALIDO
FULL OUTER JOIN
-- 22 VALIDAR SE O PRICE_LOCAL_TO PARA PRODUTOS DIFERENTE DE SAMSUNG É VALIDO E FAZ UM FULL OUTER JOIN CONSIDERANDO OS CAMPOS DE: SUBSIDIARY, SKU, REFER_DATE
						(SELECT DISTINCT SUBSIDIARY, SITE_COMPANY_NAME, SKU, PRICE_LOCAL_TO, REFER_DATE,
						CASE WHEN PRICE_LOCAL_TO IS NOT NULL  THEN 'OK'
						ELSE 'NOK' 
						END AS VALID_PRICE_VAREJO
						FROM OW_LAO.VW_CRAWLING_AP1_ESTORE_DAILY_PRICE
						WHERE SITE_COMPANY_NAME NOT LIKE '%SAMSUNG%') N
-- 22 VALIDAR SE O PRICE_LOCAL_TO PARA PRODUTOS DIFERENTE DE SAMSUNG É VALIDO E FAZ UM FULL OUTER JOIN CONSIDERANDO OS CAMPOS DE: SUBSIDIARY, SKU, REFER_DATE
					ON (UPPER(TRIM(M.SUBSIDIARY)) = UPPER(TRIM(N.SUBSIDIARY)) AND UPPER(TRIM(M.SKU)) = UPPER(TRIM(N.SKU)) AND M.REFER_DATE = N.REFER_DATE)
					ORDER BY COALESCE(M.REFER_DATE,N.REFER_DATE) DESC, COALESCE(M.SUBSIDIARY,N.SUBSIDIARY), COALESCE(M.SKU,N.SKU) ASC,ROW_NUM ASC ) AS O
-- 23 CASE ENTRE VALID_PRICE_SAMSUNG E VALID_PRICE_VAREJO E ROW_NUM COMO UM CONTADOR PARA OS RETAILS DIFERENTES   
LEFT JOIN
-- 27 CONTADOR DE MAX RETAIL POR SKU, SUB, DATA
(
				SELECT COALESCE(SUBSIDIARY,SUBSIDIARY_2) AS SUB_TO_JOIN ,COALESCE(SKU,SKU_2) AS SKU_TO_JOIN,COALESCE(REFER_DATE,DATE_2) 
				AS DATE_TO_JOIN,
				MAX(ROW_NUM) AS MAX_TO_JOIN
				
				FROM
				(
-- 26 CASE ENTRE VALID_PRICE_SAMSUNG E VALID_PRICE_VAREJO E ROW_NUM COMO UM CONTADOR PARA OS RETAILS DIFERENTES
				SELECT DISTINCT A.SUBSIDIARY,  A.SKU,  A.REFER_DATE, 
				B.SUBSIDIARY AS SUBSIDIARY_2,  B.SKU AS SKU_2,  B.REFER_DATE AS DATE_2,
				A.VALID_PRICE_SAMSUNG,B.VALID_PRICE_VAREJO,
				CASE 
				WHEN A.VALID_PRICE_SAMSUNG = 'OK' AND B.VALID_PRICE_VAREJO = 'OK' THEN 'OK'
				WHEN (A.VALID_PRICE_SAMSUNG = 'NOK' OR A.VALID_PRICE_SAMSUNG IS NULL)
				AND (B.VALID_PRICE_VAREJO = 'NOK' OR B.VALID_PRICE_VAREJO IS NULL) THEN 'NOK AMBOS'
				WHEN A.VALID_PRICE_SAMSUNG = 'OK' AND (B.VALID_PRICE_VAREJO = 'NOK' OR B.VALID_PRICE_VAREJO IS NULL) THEN 'NOK VAREJO'
				WHEN B.VALID_PRICE_VAREJO = 'OK' AND (A.VALID_PRICE_SAMSUNG = 'NOK' OR A.VALID_PRICE_SAMSUNG IS NULL) THEN 'NOK SAMSUNG'
				END VALID_FINAL
				       
				, ROW_NUMBER() OVER (PARTITION BY COALESCE(A.SUBSIDIARY,B.SUBSIDIARY), COALESCE(A.SKU,B.SKU), COALESCE(A.REFER_DATE,B.REFER_DATE)
				ORDER BY COALESCE(A.REFER_DATE,B.REFER_DATE) DESC, COALESCE(A.SUBSIDIARY,B.SUBSIDIARY), COALESCE(A.SKU,B.SKU) ASC) as ROW_NUM
				       
				
				FROM
-- 24 VALIDAR SE O PRICE_LOCAL_TO PARA PRODUTOS SAMSUNG É VALIDO
					(SELECT DISTINCT SUBSIDIARY, SITE_COMPANY_NAME, SKU, PRICE_LOCAL_TO, REFER_DATE,
					CASE WHEN PRICE_LOCAL_TO IS NOT NULL  THEN 'OK'
					ELSE 'NOK' 
					END AS VALID_PRICE_SAMSUNG
					
					FROM OW_LAO.VW_CRAWLING_AP1_ESTORE_DAILY_PRICE
					WHERE SITE_COMPANY_NAME LIKE '%SAMSUNG%') A
-- 24 VALIDAR SE O PRICE_LOCAL_TO PARA PRODUTOS SAMSUNG É VALIDO
FULL OUTER JOIN
-- 25 VALIDAR SE O PRICE_LOCAL_TO PARA PRODUTOS DIFERENTE DE SAMSUNG É VALIDO E FAZ UM FULL OUTER JOIN CONSIDERANDO OS CAMPOS DE: SUBSIDIARY, SKU, REFER_DATE
					(SELECT DISTINCT SUBSIDIARY, SITE_COMPANY_NAME, SKU, PRICE_LOCAL_TO, REFER_DATE,
					CASE WHEN PRICE_LOCAL_TO IS NOT NULL  THEN 'OK'
					ELSE 'NOK' END AS VALID_PRICE_VAREJO
					FROM OW_LAO.VW_CRAWLING_AP1_ESTORE_DAILY_PRICE
					WHERE SITE_COMPANY_NAME NOT LIKE '%SAMSUNG%') B    
-- 25 VALIDAR SE O PRICE_LOCAL_TO PARA PRODUTOS DIFERENTE DE SAMSUNG É VALIDO E FAZ UM FULL OUTER JOIN CONSIDERANDO OS CAMPOS DE: SUBSIDIARY, SKU, REFER_DATE
				ON (UPPER(TRIM(A.SUBSIDIARY)) = UPPER(TRIM(B.SUBSIDIARY))
				AND UPPER(TRIM(A.SKU)) = UPPER(TRIM(B.SKU))
				AND A.REFER_DATE = B.REFER_DATE)
				ORDER BY COALESCE(A.REFER_DATE,B.REFER_DATE) DESC, COALESCE(A.SUBSIDIARY,B.SUBSIDIARY), COALESCE(A.SKU,B.SKU) ASC,ROW_NUM ASC
-- 26 CASE ENTRE VALID_PRICE_SAMSUNG E VALID_PRICE_VAREJO E ROW_NUM COMO UM CONTADOR PARA OS RETAILS DIFERENTES
				) AS C 
				GROUP BY COALESCE(SUBSIDIARY,SUBSIDIARY_2),COALESCE(SKU,SKU_2),COALESCE(REFER_DATE,DATE_2)
				) AS D
-- 27 CONTADOR DE MAX RETAIL POR SKU, SUB, DATA
-- 28 JOIN ENTRE O PROCESSO 23 E O PROCESSO 27.					
				ON 
				(COALESCE(O.SUBSIDIARY,O.SUBSIDIARY_2) = D.SUB_TO_JOIN)
				AND (COALESCE(O.SKU,O.SKU_2) = D.SKU_TO_JOIN)
				AND (COALESCE(O.REFER_DATE,O.DATE_2) = D.DATE_TO_JOIN)
				ORDER BY COALESCE(O.REFER_DATE,O.DATE_2) DESC, 
				              COALESCE(O.SUBSIDIARY,O.SUBSIDIARY_2), 
				              COALESCE(O.SKU,O.SKU_2) ASC,
				             O.ROW_NUM ASC   
-- 28 JOIN ENTRE O PROCESSO 23 E O PROCESSO 27.		            
-- 29 CRIANDO CAMPO VALID A PARTIR DOS CAMPOS O(ROW_NUM E VALID_FINAL) E D(MAX_TO_JOIN)
			) S WHERE S.VALID IS NOT NULL 
-- 30 UNION ENTRE VALID NULL E VALID NOT NULL			
	)
		ORDER BY COALESCE(REFER_DATE,DATE_2) DESC, 
              COALESCE(SUBSIDIARY,SUBSIDIARY_2), 
              COALESCE(SKU,SKU_2) ASC,            
             ROW_NUM ASC 
-- 31 Script para gerar a tabela auxiliar. Ordenando por REFER_DATE, SUNSIDIARY, SKU,ROW_NUM
);           
-- Trunca a Tabela fato OW_LAO.FT_CRAWLING_AP1_ESTORE_DAILY_PRICE
 TRUNCATE TABLE OW_LAO.FT_CRAWLING_AP1_ESTORE_DAILY_PRICE;
-- Insere dados na tablea fato OW_LAO.FT_CRAWLING_AP1_ESTORE_DAILY_PRICE a partir da View OW_LAO.VW_CRAWLING_AP1_ESTORE_DAILY_PRICE
 INSERT INTO OW_LAO.FT_CRAWLING_AP1_ESTORE_DAILY_PRICE SELECT
	FT.SUBSIDIARY,
	FT.COUNTRY,
	FT.SKU,
	FT.MODEL_DESC,
	FT.SITE_COMPANY_NAME,
	TO_DATE(FT.REFER_DATE,'YYYY-MM-DD') AS REFER_DATE,
	FT.FROM_CURRENCY,
	FT.TO_CURRENCY,
	FT.PRICE_LOCAL_FROM,
	FT.PRICE_LOCAL_TO,
	FT.PRICE_USD_FROM,
	FT.PRICE_USD_TO,
	FT.SITE_URL,
	FT.PRODUCT_DIVISION,
	FT.PRODUCT_CATEGORY,
	FT.PRODUCT_SUB_CATEGORY,
	FT.PRODUCT_FAMILY,
	FT.PRODUCT_SERIES,
	FT.PREMIUM,
	FT.STATUS_SITE,
	TF.VALID 
FROM OW_LAO.VW_CRAWLING_AP1_ESTORE_DAILY_PRICE FT 
LEFT JOIN OW_LAO.TF_CRAWLING_AP1_ESTORE_DAILY_PRICE_AUX TF ON (FT.SUBSIDIARY = COALESCE(TF.SUBSIDIARY,TF.SUBSIDIARY_2) 
	AND FT.SKU = COALESCE(TF.SKU,TF.SKU_2) 
	AND FT.REFER_DATE = COALESCE(TF.REFER_DATE,TF.DATE_2)) 
;
END