
CREATE PROCEDURE OW_LAO.PROC_D2C_NERP_INVENTORY
LANGUAGE SQLSCRIPT as
BEGIN
--Truncate tabela referente as informações de Inventory
TRUNCATE TABLE OW_LAO.FT_D2C_NERP_INVENTORY;
--Cria tabela referente  as informações de Inventory
INSERT INTO OW_LAO.FT_D2C_NERP_INVENTORY
SELECT ONZDASO.COMPANY 
	,DS.SUBSIDIARY 
	,DP."DIVISION" AS DIMPROD_DIVISION
	,DP.PRODUCT_GROUP_1 AS DIMPROD_PRODUCT_GROUP
	,DP.PRODUCT_1 AS DIMPROD_PRODUCT
	,ONZDASO.MATERIAL AS SKU
	,MSL.INV_TYPE 
	,ONZDASO.PLANT 
	,RDGAOH.PLANT_DESC
	,MSL.S_LOC
	,MSL.S_LOC_DESC
	,ONZDASO.ON_HAND  AS "QTY"
	,DC.YYYYWW AS "YEAR_WEEK"
	,DC.YYYYMMDD AS "DATE"
	,NOW() AS "LOAD_DATE"
	
FROM OW_LAO.ODS_NERP_ZRMMJ310410_DISPLAY_AVALIABLE_STOCK_OVERVIEW ONZDASO 
LEFT JOIN OW_MD.DIM_SUBSIDIARY DS ON (ONZDASO.COMPANY = DS.COMPANY_CODE)
LEFT JOIN OW_MD.DIM_PRODUCT DP ON (ONZDASO.MATERIAL = DP.SKU) 
LEFT JOIN OW_MD.MAP_STORAGE_LOCATION MSL ON (ONZDASO.PLANT = MSL.PLANT  AND ONZDASO.STORAGE_LOCATION  = MSL.S_LOC)
LEFT JOIN (SELECT RDGAOH.PLANT,RDGAOH.PLANT_DESC FROM  OW_LAO.RAW_DATA_GSCM_ACTUAL_ON_HAND RDGAOH 
GROUP BY RDGAOH.PLANT,RDGAOH.PLANT_DESC)RDGAOH ON (ONZDASO.PLANT = RDGAOH.PLANT)
LEFT JOIN OW_MD.DIM_CALENDAR DC ON (TO_DATE(SUBSTRING(ONZDASO.FILE_NAME,17,8), 'DDMMYYYY') = DC.YYYYMMDD)
WHERE  DS.COUNTRY_REGION IS NOT NULL
;	
END
