/***********************************************************************************************
CREATED BY : Luciano Mariani
CREATION DATE : 2023-04-25
ALTER DATE : 2023-04-28
VERSION: 1.1
DESCRIPTION: Feeds unified table with KPI 4.4 KPI Sales by channel indicators
	TF_D2C_NERP_SALES_BY_CHANNEL_KPI regarding Sales Order transactions (ZRSDD6A120)
	and Outbound (ZLLEJ50090) by Dimension Product and Dimension Sales Channel.
-- CALL OW_LAO.PROC_D2C_NERP_SALES_BY_CHANNEL;
-- SELECT TOP 1000 * FROM OW_LAO.TF_D2C_NERP_SALES_BY_CHANNEL_KPI;
***********************************************************************************************/
CREATE PROCEDURE OW_LAO.PROC_D2C_NERP_SALES_BY_CHANNEL
LANGUAGE SQLSCRIPT as
BEGIN
	
	-- VERIFICA SE ALGUMA DAS TABELAS USADAS NO PROCESSO ESTÁ VAZIA
	IF(
		(SELECT COUNT('') FROM OW_LAO.ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING) = 0
		OR (SELECT COUNT('') FROM OW_LAO.ODS_NERP_ZLLEJ50090_OUTBOUND_TRACKING) = 0
		OR (SELECT COUNT('') FROM OW_MD.DIM_PRODUCT) = 0
		OR (SELECT COUNT('') FROM OW_MD.DIM_SALES_CHANNEL) = 0
		OR (SELECT COUNT('') FROM OW_MD.DIM_CALENDAR) = 0
		OR (SELECT COUNT('') FROM OW_LAO.FT_AP2_EXCHANGE_RATE) = 0
	)
	THEN
		-- SE ALGUMA ESTIVER VAZIA ENVIA MSG E SAI
		SELECT 'NÃO HÁ REGISTROS EM UMA OU MAIS TABELAS' AS RESULTADO ,CURRENT_DATE AS DATE_NOW FROM dummy;
	ELSE
	
		-- LIMPA TABELA FATO OW_LAO.TF_D2C_NERP_SALES_BY_CHANNEL_KPI
		TRUNCATE TABLE OW_LAO.TF_D2C_NERP_SALES_BY_CHANNEL_KPI;
			 
		 -- INSERE OS DADOS TRATADOS NA TABELA FATO 
		INSERT INTO OW_LAO.TF_D2C_NERP_SALES_BY_CHANNEL_KPI 
		SELECT 
			 SUBSIDIARY
			,CHANNEL
			,SUB_CHANNEL
			,SALES_CHANNEL_ATTR_1
			,SALES_CHANNEL_ATTR_2
			,PDROD_DIVISION
			,PDROD_PRODUCT_GROUP
			,PDROD_PRODUCT
			,PROD_ATTB_1
			,SKU
			,SO_CREATE_ON
			,"1ST_GI_DATE"
			,BILLING_CREATED_ON
			,YYYYWW_SO
			,YYYYWW_GI
			,YYYYWW_IOD
			,YYYYMM_SO
			,YYYYMM_GI
			,YYYYMM_IOD
			,YYYYQQ_SO
			,YYYYQQ_GI
			,YYYYQQ_IOD
			-- MEASURES
			,SUM(QTY_PAYMENT) AS QTY_PAYMENT
			,SUM(QTY_GI) AS QTY_GI
			,SUM(QTY_IOD) AS QTY_IOD
			,SUM(AMOUNT_LOCAL_SO) AS AMOUNT_LOCAL_SO
			,SUM(AMOUNT_LOCAL_NET_VALUE) AS AMOUNT_LOCAL_NET_VALUE
			,SUM(AMOUNT_USD_SO) AS AMOUNT_USD_SO
			,SUM(AMOUNT_USD_NET_VALUE) AS AMOUNT_USD_NET_VALUE
			,CURRENT_DATE AS KPI_LAST_UPDATE
		FROM(
			SELECT
				 CASE WHEN SO.SALES_ORG = '8201' THEN 'SEDA' ELSE 'OTHERS' END AS SUBSIDIARY --	1	Subsidiary
				,CH.CHANNEL --	2 Channel
				,CH.SUB_CHANNEL --	3 Sub Channel
				,CH.SALES_CHANNEL_ATTR_1 --	4 Ch. Attb 1
				,CH.SALES_CHANNEL_ATTR_2 --	5 Ch. Attb 2
				,PD."DIVISION" AS PDROD_DIVISION --	6	Division
				,PD.PRODUCT_GROUP_1 AS PDROD_PRODUCT_GROUP -- 7	Product Group
				,PD.PRODUCT_1 AS PDROD_PRODUCT -- 8	Product
				,PD.ATTB01 AS PROD_ATTB_1 -- Novo campo pedido p/ Erick
				,SO.MATERIAL AS SKU
				,OW_LAO.Add_Hours(SO.SO_CREATE_ON, SO.SO_CREATE_ON_TIME, -12) AS SO_CREATE_ON --	9 Calendar "SO create on"
				,OB."1ST_GI_DATE" -- 10	Calendar "1st GI" date"
				,TO_DATE(OB.BILLING_CREATED_ON) AS BILLING_CREATED_ON -- 11	Calendar "Billing created on"
				/*********** - 12	CALENDARS (YYYYMM) ********/
				,CSO.YYYYWW AS YYYYWW_SO
				,CGI.YYYYWW AS YYYYWW_GI
				,CIOD.YYYYWW AS YYYYWW_IOD
				/*********** - 13	CALENDARS (YYYYMM) ********/
				,CSO.YYYYMM AS YYYYMM_SO
				,CGI.YYYYMM AS YYYYMM_GI 
				,CIOD.YYYYMM AS YYYYMM_IOD 
				/*********** - 14	CALENDARS (YYYYQQ) ********/
				,CSO.YYYYQQ AS YYYYQQ_SO
				,CGI.YYYYQQ AS YYYYQQ_GI 
				,CIOD.YYYYQQ AS YYYYQQ_IOD
				/*********** QTD ************/
				,CAST(SO.ORDER_QTY_BASE AS INTEGER) AS QTY_PAYMENT -- 15 [QTY_SO]
				,CAST(SUBSTR(OB."1ST_GI_QTY", 1, LENGTH(OB."1ST_GI_QTY") - 2) AS INTEGER) AS QTY_GI -- 16 [QTY_GI]
				,CAST(OB.DELIVERY_QTY AS INTEGER) AS QTY_IOD -- 17 QTY_IOD
				/*********** VALUE LOCAL ************/	
				,CAST(REPLACE(SO.SO_NET_VALUE, ',', '') AS DECIMAL(18,2)) AS AMOUNT_LOCAL_SO -- 18 [Amount($Real)_Payment]
				,CAST(REPLACE(OB.NET_VALUE , ',', '') AS DECIMAL(18,2)) AS AMOUNT_LOCAL_NET_VALUE -- 19 [Amount($Real)_GI]
				/*********** VALUE USD ************/	
				,CAST(( REPLACE(SO.SO_NET_VALUE, ',', '')
						/ EX.EXCHANGE_RATE
				)AS DECIMAL(18,2)) AS AMOUNT_USD_SO --  20 AS AMOUNT_USD_PAYMENT_SO -- 21 [Amount($USD)_Payment]
				,CAST(( REPLACE(OB.NET_VALUE , ',', '')
						/ EX.EXCHANGE_RATE
				)AS DECIMAL(18,2)) AS AMOUNT_USD_NET_VALUE --  21 AMOUNT_USD_GI --	22 [Amount($usd)_GI] 
				--******************************************************/
			FROM
				/***** Sales Order (SO) ****/
				OW_LAO.ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING SO
				--OW_SEDA_S.ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING SO
				/***** Outbound (OB) ****/
				LEFT JOIN OW_LAO.ODS_NERP_ZLLEJ50090_OUTBOUND_TRACKING OB 
					ON 	OB.DELIVERY_NO = SO.DELIVERY
						AND OB.MATERIAL = SO.MATERIAL
						AND OB.DELIVERY_ITEM = SO.DELIVERY_ITEM
				
				/***** Vtex Order List (VO) ****/
				LEFT JOIN (				
					SELECT
						 ORDER_ID
						,MAX(SALES_CHANNEL) AS SALES_CHANNEL
					FROM(
						SELECT
							CASE
								WHEN S.CUSTOMER_PO IS NOT NULL THEN
									V.ORDER_ID
								ELSE
									CAST("SEQUENCE" AS VARCHAR(80))
							END AS ORDER_ID
							,CAST(SALES_CHANNEL AS VARCHAR(80)) AS SALES_CHANNEL
						FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_LIST V
							LEFT JOIN OW_LAO.ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING S
								ON V.ORDER_ID = S.CUSTOMER_PO
									AND S.SALES_DOC_TYPE = 'YS10' -- (SOMENTE D2C)
									AND S.SALES_ORG = '8201' -- SEDA
									AND S.SHIPPING_TYPE IN('P3','P4')
					)
					GROUP BY
						 ORDER_ID
				)VO ON VO.ORDER_ID = SO.CUSTOMER_PO
				
				/***** Dimension Sales Channel (CH) ****/
				LEFT JOIN OW_MD.DIM_SALES_CHANNEL CH
					ON VO.SALES_CHANNEL = CH.VTEX_POLICY
	
				/***** Dimension Product (PD) ****/
				LEFT JOIN OW_MD.DIM_PRODUCT PD
					ON SO.MATERIAL = PD.SKU
				
				/***********  Calendars (CL) ********/
				LEFT JOIN OW_MD.DIM_CALENDAR CSO
					ON CSO.YYYYMMDD = TO_DATE(OW_LAO.Add_Hours(SO.SO_CREATE_ON, SO.SO_CREATE_ON_TIME, -12)) -- SO
				LEFT JOIN OW_MD.DIM_CALENDAR CGI
					ON CGI.YYYYMMDD = TO_DATE(OB."1ST_GI_DATE") -- GI
				LEFT JOIN OW_MD.DIM_CALENDAR CIOD
					ON CIOD.YYYYMMDD = TO_DATE(OB.BILLING_CREATED_ON) -- IOD
				
				/*********** EXCHANGE_RATE (EX) ********/
				LEFT JOIN OW_LAO.FT_AP2_EXCHANGE_RATE EX
					ON 	EX.VALID_FROM = TO_DATE(OW_LAO.Add_Hours(SO.SO_CREATE_ON, SO.SO_CREATE_ON_TIME, -12))
						AND EX.TO_CURRENCY = SO.SO_CURR
						AND EX.FROM_CURRENCY = 'USD'
			WHERE
				-- COMMON FILTERS 
				SO.SALES_DOC_TYPE = 'YS10' -- (SOMENTE D2C)
				AND SO.SALES_ORG = '8201' -- SEDA
				AND SO.SHIPPING_TYPE IN('P3','P4')
		)
		GROUP BY
			 SUBSIDIARY
			,CHANNEL
			,SUB_CHANNEL
			,SALES_CHANNEL_ATTR_1
			,SALES_CHANNEL_ATTR_2
			,PDROD_DIVISION
			,PDROD_PRODUCT_GROUP
			,PDROD_PRODUCT
			,PROD_ATTB_1
			,SKU
			,SO_CREATE_ON
			,"1ST_GI_DATE"
			,BILLING_CREATED_ON
			,YYYYWW_SO
			,YYYYWW_GI
			,YYYYWW_IOD
			,YYYYMM_SO
			,YYYYMM_GI
			,YYYYMM_IOD
			,YYYYQQ_SO
			,YYYYQQ_GI
			,YYYYQQ_IOD
		ORDER BY
			 SO_CREATE_ON
			,SUBSIDIARY
			,CHANNEL
			,SUB_CHANNEL
			,SALES_CHANNEL_ATTR_1
			,SALES_CHANNEL_ATTR_2
			,PDROD_DIVISION
			,PDROD_PRODUCT_GROUP
			,PDROD_PRODUCT
			,PROD_ATTB_1
			,SKU;
	
		--MENSAGEM
		SELECT 'TF_D2C_NERP_SALES_BY_CHANNEL_KPI ATUALIZADA COM SUCESSO!' AS RESULTADO ,CURRENT_DATE AS DATE_NOW FROM dummy;
	
	END IF;
END