CREATE PROCEDURE OW_LAO.PROC_D2C_CELLO_NERP_RETURN_OPERATION
LANGUAGE SQLSCRIPT as
BEGIN
--Truncate tabela referente as informações de Return Operation
TRUNCATE TABLE OW_LAO.FT_D2C_CELLO_NERP_RETURN_OPERATION;
--Cria tabela referente  as informações de Return Operation
INSERT INTO OW_LAO.FT_D2C_CELLO_NERP_RETURN_OPERATION(
		SUBSIDIARY
		,DIMPROD_PRODUCT_GROUP
		,DIMPROD_DIVISION
		,DIMPROD_PRODUCT
		,SEDA_BU_ESTORE
		,SEDA_DIVISION_ESTORE
		,SEDA_CATEGORY_ESTORE
		,SEDA_FAMILY_ESTORE
		,SEDA_DESC_ESTORE
		,YEAR_MONTH
		,WEEK
		,R_DO_NO
		,RDO_ORDER_TYPE
		,ORDER_TYPE
		,SOLDTO_NM
		,S_CARRIER_NAME
		,RETURN_QTY
		,SO_CREATED_ON
		,R_DO_CREATED_ON
		,RETURN_IOD_DATE
		,GR_DATE
		,PICK_UP_DATE
		,RETURN_SIT_QTY
		,RETURN_POST_QTY
		,RETURN_PICKUP_QTY
		,SIT_RDO_RIOD
		,SIT_IOD_GR
		,POST_REQUEST_CODE
		,POST_CODE_POST
		,POST_POST_RDO
		,POST_RSO_RDO
		,POST_RDO_RIOD
		,POST_RIOD_RGR
		,PICKUP_REQUEST_RDO
		,PICKUP_RDO_PICKUP
		,PICKUP_RGR_PICKUP
		,PICKUP_RGR_RIOD
		,R_RATE_NUMERADOR
		,R_RATE_SELLED_DEN
		,R_RATE_SIT_DEN
		,SUBREASON_CODE_DESC
		,TOT_RDO
		,TOT_RDO_IOD_GR
		,TOT_DIF
		,LAST_UPDATE
	) 
	SELECT 	 OGRRW.SUBSIDIARY 
		,DP.PRODUCT_GROUP_1 AS DIMPROD_PRODUCT_GROUP
		,DP."DIVISION" AS DIMPROD_DIVISION
		,DP.PRODUCT_1 AS DIMPROD_PRODUCT
	        ,DP.SEDA_BU_ESTORE
	        ,DP.SEDA_DIVISION_ESTORE 
	        ,DP.SEDA_CATEGORY_ESTORE 
	        ,DP.SEDA_FAMILY_ESTORE 
	        ,DP.SEDA_DESC_ESTORE
	        ,OGRRW."MONTH" AS "YEAR_MONTH" --Dados de RETURN_RATIO
	        ,OGRRW."WEEK" 		       --Dados de RETURN_RATIO
	        --,OGRRW.ITEM AS MATERIAL
	        ,OGRRW.R_DELIVERY_DOCUMENT_NO AS R_DO_NO
	        ,CASE WHEN UPPER(VUTCRT.RDO_ORDER_TYPE) LIKE '%STORE_RTN%'
	   		THEN 'Sit'
	   	 WHEN UPPER(VUTCRT.RDO_ORDER_TYPE) LIKE '%CORREIOS%'
	   	 	THEN 'Post'
	   	 WHEN UPPER(VUTCRT.RDO_ORDER_TYPE) LIKE '%COLLECT%'
	   	 	THEN 'Pick-up'
	   	 	ELSE NULL 
	   	END AS RDO_ORDER_TYPE
	        ,VUTCRT.RDO_ORDER_TYPE AS ORDER_TYPE
	        ,OGRRW.SOLD_TOPARTY AS SOLDTO_NM 
	        ,VUTCRT.RDO_S_CARRIER_NAME AS S_CARRIER_NAME
	        ,SUM(CASE WHEN OGRRW.R_DELIVERY_DOCUMENT_NO IS NOT NULL 
	        	THEN OGRRW.QUANTITY
	        	ELSE 0 
	        END) AS RETURN_QTY
	    	,TO_DATE(ONZOT.SO_CREATED_ON) AS SO_CREATED_ON
	        ,TO_DATE(VUTCRT.RDO_INSERT_DATE) AS R_DO_CREATED_ON
	   	,TO_DATE(VUTCRT.RDO_RETURN_IOD_DATE) AS RETURN_IOD_DATE
	   	,TO_DATE(VUTCRT.GR_DATE) AS GR_DATE
	        ,TO_DATE(VUTCRT.RDO_PICK_UP_DATE) AS PICK_UP_DATE
	        ,SUM(CASE WHEN UPPER(VUTCRT.RDO_ORDER_TYPE) LIKE '%STORE_RTN%'
	   		THEN  OGRRW.QUANTITY
	   		ELSE NULL
		END) AS "RETURN_SIT_QTY"
	   	,SUM(CASE WHEN UPPER(VUTCRT.RDO_ORDER_TYPE) LIKE '%CORREIOS%'
	   		THEN  OGRRW.QUANTITY
	   		ELSE NULL
		END) AS "RETURN_POST_QTY"
		,SUM(CASE WHEN UPPER(VUTCRT.RDO_ORDER_TYPE) LIKE '%COLLECT%'AND VUTCRT.RDO_RETURN_IOD_DATE IS NOT NULL
	   		THEN  OGRRW.QUANTITY
	   		ELSE NULL
		END) AS "RETURN_PICKUP_QTY"
	
		,CASE WHEN UPPER(VUTCRT.RDO_ORDER_TYPE) LIKE '%STORE_RTN%'
   			THEN DAYS_BETWEEN(TO_DATE(VUTCRT.RDO_INSERT_DATE),TO_DATE(VUTCRT.RDO_RETURN_IOD_DATE)) 
			ELSE NULL
		END AS "SIT_RDO_RIOD"
		,CASE WHEN UPPER(VUTCRT.RDO_ORDER_TYPE) LIKE '%STORE_RTN%'
	   		THEN DAYS_BETWEEN(TO_DATE(VUTCRT.RDO_RETURN_IOD_DATE),TO_DATE(VUTCRT.GR_DATE)) 
			ELSE NULL
		END AS "SIT_IOD_GR"
		,CAST(NULL AS INT) AS "POST_REQUEST_CODE"
		,CAST(NULL AS INT) AS "POST_CODE_POST"
		,CAST(NULL AS INT) AS "POST_POST_RDO"
		,CASE WHEN UPPER(VUTCRT.RDO_ORDER_TYPE) LIKE '%CORREIOS%'AND UPPER(OGRRW.SOLD_TOPARTY) LIKE '%SEDA%'
	   		THEN  DAYS_BETWEEN(TO_DATE(ONZOT.SO_CREATED_ON),TO_DATE(VUTCRT.RDO_INSERT_DATE)) 
	   		ELSE NULL
		END AS "POST_RSO_RDO"
		,CASE WHEN UPPER(VUTCRT.RDO_ORDER_TYPE) LIKE '%CORREIOS%'AND UPPER(OGRRW.SOLD_TOPARTY) LIKE '%SEDA%'
	   		THEN  DAYS_BETWEEN(TO_DATE(VUTCRT.RDO_INSERT_DATE),TO_DATE(VUTCRT.RDO_RETURN_IOD_DATE)) 
	   		ELSE NULL
		END AS "POST_RDO_RIOD"
		,CASE WHEN UPPER(VUTCRT.RDO_ORDER_TYPE) LIKE '%CORREIOS%'AND UPPER(OGRRW.SOLD_TOPARTY) LIKE '%SEDA%'
	   		THEN DAYS_BETWEEN(TO_DATE(VUTCRT.RDO_RETURN_IOD_DATE),TO_DATE(VUTCRT.GR_DATE)) 
	   		ELSE NULL
		END AS "POST_RIOD_RGR"
		,CAST(NULL AS INT) AS "PICKUP_REQUEST_RDO"
		,CASE WHEN UPPER(VUTCRT.RDO_ORDER_TYPE) LIKE '%COLLECT%'AND UPPER(OGRRW.SOLD_TOPARTY) LIKE '%SEDA%'
	   		THEN DAYS_BETWEEN(TO_DATE(VUTCRT.RDO_INSERT_DATE),TO_DATE(VUTCRT.RDO_PICK_UP_DATE))
	   		ELSE NULL
		END AS "PICKUP_RDO_PICKUP"
		,CASE WHEN UPPER(VUTCRT.RDO_ORDER_TYPE) LIKE '%COLLECT%'AND UPPER(OGRRW.SOLD_TOPARTY) LIKE '%SEDA%'
	   		THEN DAYS_BETWEEN(TO_DATE(VUTCRT.RDO_PICK_UP_DATE),TO_DATE(VUTCRT.GR_DATE))
	   		ELSE NULL
		END AS "PICKUP_RGR_PICKUP"
		,CASE WHEN UPPER(VUTCRT.RDO_ORDER_TYPE) LIKE '%COLLECT%'AND UPPER(OGRRW.SOLD_TOPARTY) LIKE '%SEDA%'
	   		THEN DAYS_BETWEEN(TO_DATE(VUTCRT.GR_DATE), TO_DATE(VUTCRT.RDO_RETURN_IOD_DATE))
	   		ELSE NULL
		END AS "PICKUP_RGR_RIOD"
	        ,SUM(CASE WHEN OGRRW.R_DELIVERY_DOCUMENT_NO IS NOT NULL 
		   THEN ROUND(OGRRW.AMOUNT,2)
		   ELSE 0
		END) AS  R_RATE_NUMERADOR
	 	,SUM(CASE WHEN OGRRW.R_DELIVERY_DOCUMENT_NO IS NULL 
	  		THEN ROUND(OGRRW.AMOUNT,2)
	  		ELSE 0
	    	END) AS  R_RATE_SELLED_DEN
	    	,SUM(CASE WHEN OGRRW.CLASSIFICATION = 'Return SiT'
	  		THEN ROUND(OGRRW.AMOUNT,2) 
	  		ELSE 0
	    	END) AS R_RATE_SIT_DEN
		,OGRRW.SUBREASON_CODE_DESC
		,COUNT(DISTINCT VUTCRT.RDO_NUMBER) AS "TOT_RDO"
		,COUNT(DISTINCT(CASE WHEN VUTCRT.RDO_RETURN_IOD_DATE IS NOT NULL AND VUTCRT.GR_DATE IS NOT NULL  
			THEN VUTCRT.RDO_NUMBER
	        	ELSE NULL
		END)) AS "TOT_RDO_IOD_GR"
		,(COUNT(DISTINCT VUTCRT.RDO_NUMBER)
		-
		COUNT(DISTINCT(CASE WHEN VUTCRT.RDO_RETURN_IOD_DATE IS NOT NULL AND VUTCRT.GR_DATE IS NOT NULL  
			THEN VUTCRT.RDO_NUMBER
		        ELSE NULL
		END))) AS "TOT_DIF"
        	,NULL AS LAST_UPDATE
	FROM  OW_SEDA_S.ODS_GLP_RETURN_RATIO_WEEKLY OGRRW 
	--Estamos fazendo o SELECT DISTINCT PARA REMOVER DUPLICIDADES NA HORA DE RELACIONAR AS BASES
	LEFT JOIN (SELECT DISTINCT VCRT.RDO_NUMBER ,VCRT.MATERIAL_CODE,VCRT.RDO_ORDER_TYPE
					,VCRT.RDO_S_CARRIER_NAME,VCRT.RDO_INSERT_DATE
					,VCRT.RDO_RETURN_IOD_DATE,VCRT.GR_DATE,VCRT.RDO_PICK_UP_DATE
		   FROM OW_SEDA_S.VW_CELLO_RETURN_TRACKING VCRT) AS VUTCRT 
		   ON (OGRRW.R_DELIVERY_DOCUMENT_NO = VUTCRT.RDO_NUMBER AND OGRRW.ITEM = VUTCRT.MATERIAL_CODE)
	LEFT JOIN OW_MD.DIM_PRODUCT DP ON (OGRRW.ITEM = DP.SKU) 
	--Estamos fazendo o SELECT DISTINCT PARA REMOVER DUPLICIDADES NA HORA DE RELACIONAR AS BASES
	LEFT JOIN (SELECT DISTINCT ONZOT1.SO_CREATED_ON,ONZOT1.DELIVERY_NO,ONZOT1.MATERIAL
		   FROM OW_LAO.ODS_NERP_ZLLEJ50090_OUTBOUND_TRACKING ONZOT1) ONZOT 
		   ON (OGRRW.R_DELIVERY_DOCUMENT_NO = ONZOT.DELIVERY_NO AND OGRRW.ITEM = ONZOT.MATERIAL)
	WHERE UPPER(OGRRW.SOLD_TOPARTY)  LIKE '%SEDA%'
	GROUP BY OGRRW.SUBSIDIARY 
		,DP.PRODUCT_GROUP_1
		,DP."DIVISION"
		,DP.PRODUCT_1
	        ,DP.SEDA_BU_ESTORE
	        ,DP.SEDA_DIVISION_ESTORE 
	        ,DP.SEDA_CATEGORY_ESTORE 
	        ,DP.SEDA_FAMILY_ESTORE 
	        ,DP.SEDA_DESC_ESTORE
	        ,OGRRW."MONTH" 		       --Dados de RETURN_RATIO
	        ,OGRRW."WEEK" 		       --Dados de RETURN_RATIO
	        --,OGRRW.ITEM AS MATERIAL
	        ,OGRRW.R_DELIVERY_DOCUMENT_NO
	        ,CASE WHEN UPPER(VUTCRT.RDO_ORDER_TYPE) LIKE '%STORE_RTN%'
	   		THEN 'Sit'
	   	 WHEN UPPER(VUTCRT.RDO_ORDER_TYPE) LIKE '%CORREIOS%'
	   	 	THEN 'Post'
	   	 WHEN UPPER(VUTCRT.RDO_ORDER_TYPE) LIKE '%COLLECT%'
	   	 	THEN 'Pick-up'
	   	 	ELSE NULL 
	   	END 
	        ,VUTCRT.RDO_ORDER_TYPE
	        ,OGRRW.SOLD_TOPARTY
	        ,VUTCRT.RDO_S_CARRIER_NAME
	        /*,(CASE WHEN OGRRW.R_DELIVERY_DOCUMENT_NO IS NOT NULL 
	        	THEN OGRRW.QUANTITY
	        	ELSE 0 
	        END)*/
	    	,TO_DATE(ONZOT.SO_CREATED_ON)
	        ,TO_DATE(VUTCRT.RDO_INSERT_DATE)
	   	,TO_DATE(VUTCRT.RDO_RETURN_IOD_DATE)
	   	,TO_DATE(VUTCRT.GR_DATE)
	        ,TO_DATE(VUTCRT.RDO_PICK_UP_DATE)
	        /*,CASE WHEN UPPER(VUTCRT.RDO_ORDER_TYPE) LIKE '%STORE_RTN%'
	   		THEN  OGRRW.QUANTITY
	   		ELSE NULL
		END*/ 
	   	/*,CASE WHEN UPPER(VUTCRT.RDO_ORDER_TYPE) LIKE '%CORREIOS%'AND UPPER(OGRRW.SOLD_TOPARTY) LIKE '%SEDA%'
	   		THEN  OGRRW.QUANTITY
	   		ELSE NULL
		END*/ 
		/*,CASE WHEN UPPER(VUTCRT.RDO_ORDER_TYPE) LIKE '%COLLECT%'AND UPPER(OGRRW.SOLD_TOPARTY) LIKE '%SEDA%'
	   		THEN  OGRRW.QUANTITY
	   		ELSE NULL
		END*/ 
		,CASE WHEN UPPER(VUTCRT.RDO_ORDER_TYPE) LIKE '%STORE_RTN%'
   			THEN DAYS_BETWEEN(TO_DATE(VUTCRT.RDO_INSERT_DATE),TO_DATE(VUTCRT.RDO_RETURN_IOD_DATE)) 
			ELSE NULL
		END 
		,CASE WHEN UPPER(VUTCRT.RDO_ORDER_TYPE) LIKE '%STORE_RTN%'
	   		THEN DAYS_BETWEEN(TO_DATE(VUTCRT.RDO_RETURN_IOD_DATE),TO_DATE(VUTCRT.GR_DATE)) 
			ELSE NULL
		END
		--,CAST(NULL AS INT) AS "POST_REQUEST_CODE"
		--,CAST(NULL AS INT) AS "POST_CODE_POST"
		--,CAST(NULL AS INT) AS "POST_POST_RDO"
		,CASE WHEN UPPER(VUTCRT.RDO_ORDER_TYPE) LIKE '%CORREIOS%'AND UPPER(OGRRW.SOLD_TOPARTY) LIKE '%SEDA%'
	   		THEN  DAYS_BETWEEN(TO_DATE(ONZOT.SO_CREATED_ON),TO_DATE(VUTCRT.RDO_INSERT_DATE)) 
	   		ELSE NULL
		END
		,CASE WHEN UPPER(VUTCRT.RDO_ORDER_TYPE) LIKE '%CORREIOS%'AND UPPER(OGRRW.SOLD_TOPARTY) LIKE '%SEDA%'
	   		THEN  DAYS_BETWEEN(TO_DATE(VUTCRT.RDO_INSERT_DATE),TO_DATE(VUTCRT.RDO_RETURN_IOD_DATE)) 
	   		ELSE NULL
		END
		,CASE WHEN UPPER(VUTCRT.RDO_ORDER_TYPE) LIKE '%CORREIOS%'AND UPPER(OGRRW.SOLD_TOPARTY) LIKE '%SEDA%'
	   		THEN DAYS_BETWEEN(TO_DATE(VUTCRT.RDO_RETURN_IOD_DATE),TO_DATE(VUTCRT.GR_DATE)) 
	   		ELSE NULL
		END
		--,CAST(NULL AS INT) AS "PICKUP_REQUEST_RDO"
		,CASE WHEN UPPER(VUTCRT.RDO_ORDER_TYPE) LIKE '%COLLECT%'AND UPPER(OGRRW.SOLD_TOPARTY) LIKE '%SEDA%'
	   		THEN DAYS_BETWEEN(TO_DATE(VUTCRT.RDO_INSERT_DATE),TO_DATE(VUTCRT.RDO_PICK_UP_DATE))
	   		ELSE NULL
		END
		,CASE WHEN UPPER(VUTCRT.RDO_ORDER_TYPE) LIKE '%COLLECT%'AND UPPER(OGRRW.SOLD_TOPARTY) LIKE '%SEDA%'
	   		THEN DAYS_BETWEEN(TO_DATE(VUTCRT.RDO_PICK_UP_DATE),TO_DATE(VUTCRT.GR_DATE))
	   		ELSE NULL
		END
		,CASE WHEN UPPER(VUTCRT.RDO_ORDER_TYPE) LIKE '%COLLECT%'AND UPPER(OGRRW.SOLD_TOPARTY) LIKE '%SEDA%'
	   		THEN DAYS_BETWEEN(TO_DATE(VUTCRT.GR_DATE), TO_DATE(VUTCRT.RDO_RETURN_IOD_DATE))
	   		ELSE NULL
		END
	        /*,CASE WHEN OGRRW.R_DELIVERY_DOCUMENT_NO IS NOT NULL 
		   THEN ROUND(OGRRW.AMOUNT,2)
		   ELSE 0
		END*/
	 	/*,CASE WHEN OGRRW.R_DELIVERY_DOCUMENT_NO IS NULL 
	  		THEN ROUND(OGRRW.AMOUNT,2)
	  		ELSE 0
	    	END*/
	    	/*,CASE WHEN OGRRW.CLASSIFICATION = 'Return SiT'
	  		THEN ROUND(OGRRW.AMOUNT,2) 
	  		ELSE 0
	    	END*/
	    	,OGRRW.SUBREASON_CODE_DESC
		
	;		
-- Update para Setar o horário de carga. Obs.: Estou fazendo aqui para não ter probemas com milisegundos
UPDATE OW_LAO.FT_D2C_CELLO_NERP_RETURN_OPERATION
	SET LAST_UPDATE = NOW()
	WHERE LAST_UPDATE IS NULL;
END