/***********************************************************************************************
CREATED BY : Luciano Mariani
CREATION DATE : 2023-08-01
ALTER DATE : 
VERSION: 1.0
-- CALL OW_LAO.PROC_D2C_NERP_SALES_BY_HOUR_KPI;
SELECT TOP 100 * FROM OW_LAO.TF_D2C_NERP_SALES_BY_HOUR_KPI WHERE  "SOURCE"  = 'TGS' AND QTY > 0
***********************************************************************************************/
CREATE PROCEDURE OW_LAO.PROC_D2C_NERP_SALES_BY_HOUR_KPI LANGUAGE SQLSCRIPT
AS
BEGIN
	
	--APAGA TATBELA FATO TF_D2C_NERP_SALES_BY_HOUR_KPI
	-- DROP TABLE OW_LAO.TF_D2C_NERP_SALES_BY_HOUR_KPI;
	
	-- APAGA TUDO EM 90 DIAS
	DELETE FROM OW_LAO.TF_D2C_NERP_SALES_BY_HOUR_KPI
	WHERE DATE_REF >= ADD_DAYS(CURRENT_TIMESTAMP, -60) ;
	-- APAGA TUDO DE TGS (TARGET)
	DELETE FROM OW_LAO.TF_D2C_NERP_SALES_BY_HOUR_KPI
	WHERE SOURCE = 'TGS' ;
		
	-- CRIA NOVA TATBELA FATO TF_D2C_NERP_SALES_BY_HOUR_KPI
	-- CREATE COLUMN TABLE OW_LAO.TF_D2C_NERP_SALES_BY_HOUR_KPI AS (
	 	INSERT INTO OW_LAO.TF_D2C_NERP_SALES_BY_HOUR_KPI
		SELECT 
				"SOURCE"
				,SUBSIDIARY
				,DATE_REF
				,YYYYWW
				,YYYYMM
				,YYYYQQ
				,PO_WEEK_DAY_NUM
				,PO_WEEK_DAY_NAME
				,PO_HOUR
				,CAST(CONCAT(
						CONCAT(DATE_REF, CASE WHEN LENGTH(PO_HOUR) = 2 THEN CONCAT(' ',PO_HOUR)  ELSE CONCAT(' 0',PO_HOUR) END) 
						,':00') AS TIMESTAMP) 
				AS DATE_REF_TIMESTAMP -- 
				,CHANNEL_TYPE
				,SELECTED_SLA
				,PDROD_DIVISION
				,PDROD_PRODUCT_GROUP
				,PDROD_PRODUCT
				,PROD_ATTB_1
				,SEDA_BU_ESTORE
				,SEDA_CATEGORY_ESTORE
				,SEDA_DESC_ESTORE
				,SEDA_DIVISION_ESTORE
				,SEDA_FAMILY_ESTORE
				,STATUS_PO
				,AFFILIATE_CHANNEL
				,AFFILIATE_SUB_CHANNEL
				,AFFILIATE_PARTNER_LEVEL
				,GLOBAL_CHANNEL
				,AUDIENCE_TYPE
				,COUNTRY
				,CURRENCY
				,MODEL_TYPE
				,PLANT
				,PLANT_NAME
				,QTY
				,AMOUNT_LOCAL
				,AMOUNT_USD
				,KPI_LAST_UPDATE	
		FROM(
			SELECT
				"SOURCE"
				,SUBSIDIARY
				,DATE_REF
				,YYYYWW
				,YYYYMM
				,YYYYQQ
				,PO_WEEK_DAY_NUM
				,PO_WEEK_DAY_NAME
				,PO_HOUR
				,CHANNEL_TYPE
				,SELECTED_SLA
				,PDROD_DIVISION
				,PDROD_PRODUCT_GROUP
				,PDROD_PRODUCT
				,PROD_ATTB_1
				,SEDA_BU_ESTORE
				,SEDA_CATEGORY_ESTORE
				,SEDA_DESC_ESTORE
				,SEDA_DIVISION_ESTORE
				,SEDA_FAMILY_ESTORE
				,STATUS_PO
				,AFFILIATE_CHANNEL
				,AFFILIATE_SUB_CHANNEL
				,AFFILIATE_PARTNER_LEVEL
				,GLOBAL_CHANNEL
				,AUDIENCE_TYPE
				,COUNTRY
				,CURRENCY
				,MODEL_TYPE
				,PLANT
				,PLANT_NAME
				,SUM( CAST(QTY AS DECIMAL(18,2)) ) AS QTY
				,SUM(AMOUNT_LOCAL) AS AMOUNT_LOCAL
				,SUM(AMOUNT_USD) AS AMOUNT_USD
				,MAX(CURRENT_TIMESTAMP) AS KPI_LAST_UPDATE --,KPI_LAST_UPDATE
			FROM OW_LAO.TF_D2C_NERP_SALES NS
			WHERE 1=1
				AND (
					("SOURCE" = 'PO' AND STATUS_PO NOT IN('cancel','canceled'))
					OR "SOURCE" IN ('DO','GI','IOD','SO')
				)
				AND DATE_REF >= ADD_DAYS(CURRENT_TIMESTAMP, -60)
			GROUP BY
				"SOURCE"
				,SUBSIDIARY
				,DATE_REF
				,YYYYWW
				,YYYYMM
				,YYYYQQ
				,PO_WEEK_DAY_NUM
				,PO_WEEK_DAY_NAME
				,PO_HOUR
				,CHANNEL_TYPE
				,SELECTED_SLA
				,PDROD_DIVISION
				,PDROD_PRODUCT_GROUP
				,PDROD_PRODUCT
				,PROD_ATTB_1
				,SEDA_BU_ESTORE
				,SEDA_CATEGORY_ESTORE
				,SEDA_DESC_ESTORE
				,SEDA_DIVISION_ESTORE
				,SEDA_FAMILY_ESTORE
				,STATUS_PO
				,AFFILIATE_CHANNEL
				,AFFILIATE_SUB_CHANNEL
				,AFFILIATE_PARTNER_LEVEL
				,GLOBAL_CHANNEL
				,AUDIENCE_TYPE
				,COUNTRY
				,CURRENCY
				,MODEL_TYPE
				,PLANT
				,PLANT_NAME
				
			UNION ALL -- TARGET
			SELECT 
				  'TGS' AS "SOURCE" 
				, 'SEDA' AS SUBSIDIARY -- SB.SUBSIDIARY
				, TGS."DAY" AS DATE_REF		
				, CL.YYYYWW AS YYYYWW
				, CL.YYYYMM AS YYYYMM
				, CL.YYYYQQ AS YYYYQQ
				, WEEKDAY(TGS."DAY") AS "PO_WEEK_DAY_NUM"
				, DAYNAME(TGS."DAY") AS "PO_WEEK_DAY_NAME"
				, TGS."HOUR" AS PO_HOUR
				, NULL AS CHANNEL_TYPE
				, NULL AS SELECTED_SLA
				, NULL AS PDROD_DIVISION
				, NULL AS PDROD_PRODUCT_GROUP
				, NULL AS PDROD_PRODUCT
				, NULL AS PROD_ATTB_1
				, NULL AS SEDA_BU_ESTORE
				, CATEGORY AS SEDA_CATEGORY_ESTORE
				, NULL AS SEDA_DESC_ESTORE
				, TGS.DIVISION AS SEDA_DIVISION_ESTORE
				, NULL AS SEDA_FAMILY_ESTORE
				, NULL AS STATUS_PO
				, TGS.CHANNEL AS AFFILIATE_CHANNEL
				, TGS.SUB_CHANNEL AS AFFILIATE_SUB_CHANNEL
				, NULL AS AFFILIATE_PARTNER_LEVEL
				, NULL AS GLOBAL_CHANNEL
				, NULL AS AUDIENCE_TYPE
				, NULL AS COUNTRY
				, NULL AS CURRENCY
				, NULL AS MODEL_TYPE
				, NULL AS PLANT
				, NULL AS PLANT_NAME
				, SUM( CAST(TGS.QTY_HOUR AS DECIMAL(18,2))) AS QTY
				, SUM( CAST(TGS.SELLOUT_BY_HOUR_AMT AS DECIMAL(18,2))) AS AMOUNT_LOCAL
				, SUM(
						CAST(TGS.SELLOUT_BY_HOUR_AMT AS DECIMAL(18,2)) 
						/ IFNULL( EX.EXCHANGE_RATE, 
												(	SELECT EXCHANGE_RATE
													FROM (
														SELECT EXCHANGE_RATE 
															,RANK() OVER( PARTITION BY TO_CURRENCY ORDER BY VALID_FROM DESC) AS SEQ
														FROM OW_LAO.FT_AP2_EXCHANGE_RATE EX 
														WHERE FROM_CURRENCY = 'USD'
															AND TO_CURRENCY = 'BRL'
													)
													WHERE SEQ = 1
												)
						)
					) AS AMOUNT_USD
				, CURRENT_TIMESTAMP AS KPI_LAST_UPDATE --KPI_LAST_UPDATE
			-- SELECT TOP 10 * --CURRENT_DATE ,ADD_MONTHS(TO_DATE(YEAR(CURRENT_DATE) || '-' || MONTH(CURRENT_DATE) || '-01', 'YYYY-MM-DD'), 1)
			FROM OW_MD. DIM_TARGET_SELLOUT_BY_HOUR TGS
				LEFT JOIN OW_MD.DIM_CALENDAR CL ON CL.YYYYMMDD = TGS."DAY" 
				LEFT JOIN OW_LAO.FT_AP2_EXCHANGE_RATE EX
					ON 	EX.VALID_FROM = TGS."DAY"
						AND EX.TO_CURRENCY = 'BRL'
						AND EX.FROM_CURRENCY = 'USD'
			WHERE TGS."DAY" < ADD_MONTHS(TO_DATE(YEAR(CURRENT_DATE) || '-' || MONTH(CURRENT_DATE) || '-01', 'YYYY-MM-DD'), 1)
			
			GROUP BY
				--    'TGS' AS "SOURCE" 
				--  , 'SEDA' AS SUBSIDIARY -- SB.SUBSIDIARY	
				  TGS."DAY"		
				, CL.YYYYWW --AS YYYYWW
				, CL.YYYYMM --AS YYYYMM
				, CL.YYYYQQ --AS YYYYQQ
				, WEEKDAY(TGS."DAY") --AS "PO_WEEK_DAY_NUM"
				, DAYNAME(TGS."DAY") --AS "PO_WEEK_DAY_NAME"
				, TGS."HOUR" --AS PO_HOUR
				, TGS.CATEGORY
				, TGS.DIVISION --AS SEDA_DIVISION_ESTORE
				, TGS.CHANNEL -- AS AFFILIATE_CHANNEL
				, TGS.SUB_CHANNEL -- AS AFFILIATE_SUB_CHANNEL
		)		
	;			
	--);
	UPDATE OW_LAO.TF_D2C_NERP_SALES_BY_HOUR_KPI SET
		KPI_LAST_UPDATE = CURRENT_TIMESTAMP
	;
END