
CREATE PROCEDURE OW_LAO.PROC_D2C_NERP_ORDER_PENDING_OVERVIEW
 
LANGUAGE SQLSCRIPT as
 
BEGIN
--Truncar Tabela com os dados no nivel granular mais baixo para tratamento de dados 
TRUNCATE TABLE OW_LAO.TF_D2C_NERP_ORDER_PENDING_OVERVIEW_01;
		      
--Inserir os dados no nivel granular mais baixo na tabela de transformação
INSERT INTO OW_LAO.TF_D2C_NERP_ORDER_PENDING_OVERVIEW_01  
SELECT   NULL AS SUBSIDIARY
	,NULL AS DIMPROD_PRODUCT_GROUP
	,NULL AS DIMPROD_DIVISION
	,NULL AS DIMPROD_PRODUCT
	,URVSBSSOL.REF_ID AS MATERIAL
	,MSRBP.MANAUS_SKU_REFERENCE AS MATERIAL_ADJUSTED
	,URVSBSSOL.STATUS
	,URVSBSSOL.ORDER_ID 
	,URVSBSSOL."SEQUENCE"
	,NULL AS SALES_DOCUMENT
	,NULL AS DELIVERY
	,OW_LAO.AFFILIATE_ID_ADJUSTED(OVSBSDESS.ID_STORE, URVSBSSOL.AFFILIATE_ID, URVSBSSOL.SALES_CHANNEL) AS AFFILIATE_ID_ADJUSTED
	,DAC.AFFILIATE_CHANNEL
	,DAC.AFFILIATE_SUB_CHANNEL
	,NULL AS PLANT
	,NULL AS PLANT_NAME
	,NULL AS STOR_LOC
	,NULL AS SPEC_PROCESSING
	,NULL AS S_LOC_DESC
	,TO_DATE(URVSBSSOL.AUTHORIZED_DATE) AS AUTHORIZED_DATE
	,TO_DATE(URVSBSSOL.CREATION_DATE) AS PO_CREATED_ON
	,NULL AS SO_CREATED_ON
	,NULL AS DO_LOCAL_CREATE_ON_D
	,NULL AS "1ST_GI_LOCAL_CREATE"
	,DC.YYYYWW AS YEAR_WEEK
	,DC.YYYYMM AS YEAR_MONTH
	,NULL AS "PO_WITHOUT_SO"
	,NULL AS "SO_WITHOUT_DO"
	,NULL AS "DO_WITHOUT_GI"
	,NULL AS DELIVERY_BLOCK
	,NULL AS REJECT_REASON_1
	,NULL AS LAST_UPDATE
	,NULL AS SALES_ORG
FROM 	 (
		 SELECT DISTINCT  RVSBSSOL.ORDER_ID
		 		, RVSBSSOL.MARKETPLACE_ORDER_ID
				, TO_CHAR("SEQUENCE") AS "SEQUENCE"
				, TO_DATE(RVSBSSOL.CREATION_TIMESTAMP) AS CREATION_DATE
				, RVSBSSOL.STATUS_DESCRIPTION
				, RVSBSSOL.SALES_CHANNEL
				, RVSBSSOL.AUTHORIZED_DATE
				, RVSBSSOL.STATUS
				,CASE WHEN RVSBSSOIC.REF_ID IS NULL 
					THEN RVSBSSOI.REF_ID
					ELSE RVSBSSOIC.REF_ID
				END AS REF_ID 
				,RVSBSSOL.CD_STORE_INFORMATION
				,RVSBSSOL.UTM_SOURCE
				,RVSBSSOL.AFFILIATE_ID
				FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER RVSBSSOL
				LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_ITEM RVSBSSOI 
				ON (RVSBSSOL.ORDER_ID = RVSBSSOI.ORDER_ID)
				LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_ITEM_COMPONENTS RVSBSSOIC  
				ON (RVSBSSOI.ORDER_ID = RVSBSSOIC.ORDER_ID AND RVSBSSOI.SKU_ID = RVSBSSOIC.SKU_ID)
        			WHERE RVSBSSOL.STATUS NOT IN ('canceled','cancel') AND RVSBSSOL.STATUS IS NOT NULL
				AND TO_DATE(RVSBSSOL.CREATION_TIMESTAMP)>='2023.01.01' --DATA de CORTE
	) URVSBSSOL
LEFT JOIN "OW_MD"."MAP_SKU_REFERENCE_BY_PLANT" MSRBP ON (URVSBSSOL.REF_ID = MSRBP.CAJAMAR_SKU_REFERENCE)	
LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SALES_ORDER RVSBSO  /* (SSG BR - ORDER) */ 	
				ON (URVSBSSOL.MARKETPLACE_ORDER_ID = RVSBSO.ORDER_ID)
LEFT JOIN U_PRJ_ECOM.ODS_VTEX_SSG_BR_SHOP_DATA_ENTITIES_STORES_SDS OVSBSDESS 
				ON ((CASE WHEN (CASE
							-- CD_STORE_INFORMATION
				       			WHEN URVSBSSOL.CD_STORE_INFORMATION IS NOT NULL 
								THEN URVSBSSOL.CD_STORE_INFORMATION
								ELSE RVSBSO.CD_STORE_INFORMATION
						  END) IS NOT NULL 
							THEN(CASE
								 -- CD_STORE_INFORMATION 
								 WHEN URVSBSSOL.CD_STORE_INFORMATION IS NOT NULL 
								 	THEN URVSBSSOL.CD_STORE_INFORMATION
									ELSE RVSBSO.CD_STORE_INFORMATION
							     END)
							ELSE(CASE
								  -- UTM_SOURCE
								  WHEN URVSBSSOL.UTM_SOURCE IS NOT NULL 
								  	THEN URVSBSSOL.UTM_SOURCE
									ELSE RVSBSO.UTM_SOURCE
							    END)
					END) = OVSBSDESS.ID_STORE)
LEFT JOIN OW_LAO.DIM_AFFILIATE_CHANNEL DAC ON 
	DAC.AFFILIATE_ID = OW_LAO.AFFILIATE_ID_ADJUSTED(OVSBSDESS.ID_STORE, URVSBSSOL.AFFILIATE_ID, URVSBSSOL.SALES_CHANNEL)		
LEFT JOIN OW_MD.DIM_CALENDAR DC ON (URVSBSSOL.CREATION_DATE = DC.YYYYMMDD)
;
--Truncar Tabela com os dados no nivel granular mais baixo para tratamento de dados 
TRUNCATE TABLE OW_LAO.TF_D2C_NERP_ORDER_PENDING_OVERVIEW_02;
		      
--Inserir os dados no nivel granular mais baixo na tabela de transformação
INSERT INTO OW_LAO.TF_D2C_NERP_ORDER_PENDING_OVERVIEW_02 
SELECT
	 TDNOPO.SUBSIDIARY
	,TDNOPO.DIMPROD_PRODUCT_GROUP
	,TDNOPO.DIMPROD_DIVISION
	,TDNOPO.DIMPROD_PRODUCT
	,TDNOPO.MATERIAL
	,(CASE WHEN TDNOPO.MATERIAL = ONZASOT.MATERIAL
		THEN TDNOPO.MATERIAL
		ELSE TDNOPO.MATERIAL_ADJUSTED
	 END) AS MATERIAL_ADJUSTED
	,TDNOPO.STATUS
	,TDNOPO.ORDER_ID
	,TDNOPO."SEQUENCE"
	,ONZASOT.SALES_DOCUMENT
	,ONZASOT.DELIVERY
	,TDNOPO.AFFILIATE_ID_ADJUSTED
	,TDNOPO.AFFILIATE_CHANNEL
	,TDNOPO.AFFILIATE_SUB_CHANNEL
	,ONZASOT.PLANT
	,TDNOPO.PLANT_NAME
	,ONZASOT.STOR_LOC
	,ONZASOT.SPEC_PROCESSING
	,TDNOPO.S_LOC_DESC
	,TDNOPO.AUTHORIZED_DATE
	,TDNOPO.PO_CREATED_ON
	,TO_DATE(ONZASOT.SO_LOCAL_CREATE_ON_D) AS SO_CREATED_ON
	,ONZASOT.DO_LOCAL_CREATE_ON_D
	,ONZASOT."1ST_GI_LOCAL_CREATE"
	,TDNOPO.YEAR_WEEK
	,TDNOPO.YEAR_MONTH
	,TDNOPO.PO_WITHOUT_SO
	,TDNOPO.SO_WITHOUT_DO
	,TDNOPO.DO_WITHOUT_GI
	,ONZASOT.DELIVERY_BLOCK
	,ONZASOT.REJECT_REASON_1
	,TDNOPO.LAST_UPDATE
	,ONZASOT.SALES_ORG
FROM OW_LAO.TF_D2C_NERP_ORDER_PENDING_OVERVIEW_01 TDNOPO
LEFT JOIN OW_LAO.ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING ONZASOT ON  ((TDNOPO.ORDER_ID =  ONZASOT.CUSTOMER_PO  
									OR TDNOPO."SEQUENCE" =  ONZASOT.CUSTOMER_PO)  
											AND TDNOPO.MATERIAL = ONZASOT.MATERIAL)
WHERE (ONZASOT.ORDER_QTY_BASE>=0 OR ONZASOT.ORDER_QTY_BASE IS NULL)											
;
--Update using Material (MANAUS_SKU_REFERENCE) from TO-FROM
UPDATE OW_LAO.TF_D2C_NERP_ORDER_PENDING_OVERVIEW_02 AS TDNOPO
	SET TDNOPO.SALES_DOCUMENT 	= ONZASOT.SALES_DOCUMENT
	   ,TDNOPO.DELIVERY 		= ONZASOT.DELIVERY
	   ,TDNOPO.PLANT		= ONZASOT.PLANT
	   ,TDNOPO.STOR_LOC 		= ONZASOT.STOR_LOC
	   ,TDNOPO.SPEC_PROCESSING 	= ONZASOT.SPEC_PROCESSING
	   ,TDNOPO.SO_CREATED_ON 	= TO_DATE(ONZASOT.SO_LOCAL_CREATE_ON_D)
	   ,TDNOPO.DO_LOCAL_CREATE_ON_D = ONZASOT.DO_LOCAL_CREATE_ON_D
	   ,TDNOPO."1ST_GI_LOCAL_CREATE" = ONZASOT."1ST_GI_LOCAL_CREATE"
	   ,TDNOPO.DELIVERY_BLOCK 	= ONZASOT.DELIVERY_BLOCK
	   ,TDNOPO.REJECT_REASON_1 	= ONZASOT.REJECT_REASON_1
	   ,TDNOPO.SALES_ORG		= ONZASOT.SALES_ORG
FROM OW_LAO.TF_D2C_NERP_ORDER_PENDING_OVERVIEW_02 AS TDNOPO	   
LEFT JOIN  OW_LAO.ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING ONZASOT ON  ((TDNOPO.ORDER_ID =  ONZASOT.CUSTOMER_PO  
									 OR TDNOPO."SEQUENCE" =  ONZASOT.CUSTOMER_PO)  
											 AND TDNOPO.MATERIAL_ADJUSTED = ONZASOT.MATERIAL)
WHERE TDNOPO.MATERIAL <> TDNOPO.MATERIAL_ADJUSTED AND TDNOPO.MATERIAL_ADJUSTED IS NOT NULL	
	AND (ONZASOT.ORDER_QTY_BASE>=0 OR ONZASOT.ORDER_QTY_BASE IS NULL)
;
--Update flag type pending
UPDATE OW_LAO.TF_D2C_NERP_ORDER_PENDING_OVERVIEW_02 AS TDNOPO
	SET TDNOPO."PO_WITHOUT_SO" = CASE WHEN TDNOPO.SO_CREATED_ON IS NULL 
					THEN 1
					ELSE 0
			      	     END
	   ,TDNOPO."SO_WITHOUT_DO" = CASE WHEN TDNOPO.DO_LOCAL_CREATE_ON_D IS NULL 
	   				   AND TDNOPO.SO_CREATED_ON IS NOT NULL 
	   				   AND TDNOPO."1ST_GI_LOCAL_CREATE" IS NULL
					THEN 1
					ELSE 0
				     END
	  ,TDNOPO."DO_WITHOUT_GI" = CASE WHEN TDNOPO."1ST_GI_LOCAL_CREATE" IS NULL 
	  				  AND TDNOPO.SO_CREATED_ON IS NOT NULL 
	  				  AND TDNOPO.DO_LOCAL_CREATE_ON_D IS NOT NULL
					THEN 1
					ELSE 0
				    END 
WHERE TDNOPO."PO_WITHOUT_SO" IS NULL AND TDNOPO."SO_WITHOUT_DO" IS NULL AND TDNOPO."DO_WITHOUT_GI" IS NULL
;
	
--Truncar Tabela com os dados no nivel granular mais baixo para tratamento de dados 
TRUNCATE TABLE OW_LAO.FT_D2C_NERP_ORDER_PENDING_OVERVIEW;
		      
--Inserir os dados no nivel granular mais baixo na tabela de transformação
INSERT INTO OW_LAO.FT_D2C_NERP_ORDER_PENDING_OVERVIEW  
SELECT   IFNULL(DS.SUBSIDIARY,'SEDA') AS SUBSIDIARY
	,DP.SEDA_CATEGORY_ESTORE AS DIMPROD_PRODUCT_GROUP
	,DP.SEDA_DIVISION_ESTORE AS DIMPROD_DIVISION
	,DP.SEDA_FAMILY_ESTORE AS DIMPROD_PRODUCT
	,TDNOPO.MATERIAL
	,TDNOPO.MATERIAL_ADJUSTED
	,TDNOPO.STATUS
	,TDNOPO.ORDER_ID
	,TDNOPO."SEQUENCE"
	,TDNOPO.SALES_DOCUMENT
	,TDNOPO.DELIVERY
	,TDNOPO.AFFILIATE_ID_ADJUSTED
	,TDNOPO.AFFILIATE_CHANNEL
	,TDNOPO.AFFILIATE_SUB_CHANNEL
	,DP2.PLANT_CODE AS PLANT
	,DP2.PLANT_NAME
	,TDNOPO.STOR_LOC
	,TDNOPO.SPEC_PROCESSING
	,MSL.S_LOC_DESC
	,TDNOPO.AUTHORIZED_DATE
	,TDNOPO.PO_CREATED_ON
	,TDNOPO.SO_CREATED_ON
	,TDNOPO.DO_LOCAL_CREATE_ON_D
	,TDNOPO."1ST_GI_LOCAL_CREATE"
	,TDNOPO.YEAR_WEEK
	,TDNOPO.YEAR_MONTH
	,TDNOPO.PO_WITHOUT_SO
	,TDNOPO.SO_WITHOUT_DO
	,TDNOPO.DO_WITHOUT_GI
	,TDNOPO.DELIVERY_BLOCK
	,TDNOPO.REJECT_REASON_1
	,NOW() LAST_UPDATE
FROM OW_LAO.TF_D2C_NERP_ORDER_PENDING_OVERVIEW_02 TDNOPO
LEFT JOIN OW_MD.DIM_SUBSIDIARY DS ON (TDNOPO.SALES_ORG = DS.SALES_ORG)
LEFT JOIN OW_MD.DIM_PLANT DP2 ON (TDNOPO.PLANT = DP2.PLANT_CODE)
LEFT JOIN OW_MD.MAP_STORAGE_LOCATION MSL ON (TDNOPO.PLANT = MSL.PLANT AND TDNOPO.STOR_LOC = MSL.S_LOC)
LEFT JOIN OW_MD.DIM_PRODUCT DP ON (IFNULL(TDNOPO.MATERIAL_ADJUSTED,TDNOPO.MATERIAL) = DP.SKU)	
;
END