CREATE PROCEDURE OW_LAO.PROC_D2C_NERP_SALES
LANGUAGE SQLSCRIPT AS
BEGIN
		/*****************************************************************	
	-- CASO A DATA DA ULTIMA INGESTION DE VTEX SEJA MAIOR QUE ULTIMO UPDATE DE PO
	IF (SELECT COUNT('') FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER) > 0 -- TEM DADOS DE PO
		AND( (SELECT COUNT('') FROM OW_LAO.TF_D2C_NERP_SALES WHERE SOURCE = 'PO') = 0 -- CASO A TABELA ESTEJA VAZIA
			OR( ( SELECT MAX(UPDATED_AT) AS VTEX_LOAD_DATE FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER) >
				( SELECT MAX(KPI_LAST_UPDATE) AS PO_UPDATED FROM OW_LAO.TF_D2C_NERP_SALES WHERE SOURCE = 'PO')
			)
		)
	THEN
	*****************************************************************/
		/*****************************************************************
		PROCESSA PO VTEX (INCREMENTAL)
		*****************************************************************	
		--CALL OW_LAO.PROC_D2C_PO_SALES;
		CALL OW_LAO.PROC_D2C_PO_VTEX_SALES;
		CALL OW_LAO.PROC_D2C_VTEX_PROMOTION_KPI;
		CALL OW_LAO.PROC_D2C_NERP_SALES_TRADEIN_KPI;
		CALL OW_LAO.PROC_D2C_NERP_SALES_COUPON_KPI;
		CALL OW_LAO.PROC_D2C_VTEX_SELLOUT_PLATFORM_KPI;
	
		/*****************************************************************
		PROCESSA PO HYBRIS (INCREMENTAL)
		*****************************************************************	
		CALL OW_LAO.PROC_D2C_PO_HYBRIS_SALES;
	
		/*****************************************************************
			SO / IOD / GI / DO
		*****************************************************************/	
		/*****************************************************************
			SO E IOD
		*****************************************************************/			
		-- CASO A DATA DA ULTIMA INGESTION SALES ORDER TRACKING SEJA MAIOR QUE A ULTIMA ATUALIZAÇÃO DE SO E IOD
		IF ( (SELECT COUNT('') FROM OW_LAO.TF_D2C_NERP_SALES WHERE "SOURCE" IN('SO','IOD')) = 0 --CASO TABELA ESTEJA LIMPA
			OR((
				  SELECT MAX(LOAD_DATE) AS SALES_ORDER_LOAD_DATE
				  FROM OW_LAO.ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING
				) > 
				( SELECT MAX(KPI_LAST_UPDATE) AS SO_IOD_UPDATED
				  FROM OW_LAO.TF_D2C_NERP_SALES
				  WHERE "SOURCE" IN('SO','IOD')
				)
			)
		) THEN
			
			-- APAGA DADOS DE SO E IOD
			DELETE FROM OW_LAO.TF_D2C_NERP_SALES
			WHERE SOURCE IN('SO','IOD')
				AND DATE_REF >= ADD_DAYS(CURRENT_TIMESTAMP, -15) -- TO_DATE(SO.SO_LOCAL_CREATE_ON_D) >= ADD_DAYS(CURRENT_TIMESTAMP, -10)
			;
			
			-- INSERE DADOS DE SO E IOD
			INSERT INTO OW_LAO.TF_D2C_NERP_SALES("SOURCE", DATE_REF, YYYYWW, YYYYMM, YYYYQQ, PO_CREATION_DATE, SALES_CHANNEL, SUBSIDIARY, CHANNEL, SUB_CHANNEL, SALES_CHANNEL_ATTR_1, SALES_CHANNEL_ATTR_2, AFFILIATE_ID, SKU, PDROD_DIVISION, PDROD_PRODUCT_GROUP, PDROD_PRODUCT, PROD_ATTB_1, SEDA_BU_ESTORE, SEDA_DIVISION_ESTORE, SEDA_CATEGORY_ESTORE, SEDA_FAMILY_ESTORE, SEDA_DESC_ESTORE, QTY, AMOUNT_LOCAL, AMOUNT_USD, PRICE_TO, AMOUNT_DISCOUNT, AMOUNT_SHIPPING, ITEM_NAME, ORDER_ID, MARKETPLACE_ORDER_ID, CUSTOMER_PO, ENVIRONMENT, STORE_ID, NAME_STORE, CHANNEL_TYPE, REFERENCE_CODE_KIT, REFERENCE_CODE, STATUS_PO, AFFILIATE_ID_ADJUSTED, AFFILIATE_CHANNEL, AFFILIATE_SUB_CHANNEL, AFFILIATE_PARTNER_LEVEL, GLOBAL_CHANNEL, BIZ_TYPE, AUDIENCE_TYPE, COUNTRY, CURRENCY, MODEL_TYPE, KPI_LAST_UPDATE)
			SELECT
				 SO.SOURCE
				,SO.DATE_REF
				,CL.YYYYWW AS YYYYWW
				,CL.YYYYMM AS YYYYMM
				,CL.YYYYQQ AS YYYYQQ
				,PO.PO_CREATION_DATE
				-- CHANNEL
				,PO.SALES_CHANNEL
				,TRIM(BA.SUBSIDIARY_2) AS SUBSIDIARY
				,CH.CHANNEL 
				,CH.SUB_CHANNEL 
				,CH.SALES_CHANNEL_ATTR_1 
				,CH.SALES_CHANNEL_ATTR_2
				,PO.AFFILIATE_ID
				-- PRODUCT
				,PD.SKU
				,PD."DIVISION" AS PDROD_DIVISION
				,PD.PRODUCT_GROUP_1 AS PDROD_PRODUCT_GROUP 
				,PD.PRODUCT_1 AS PDROD_PRODUCT 
				,PD.ATTB01 AS PROD_ATTB_1 
				,PD.SEDA_BU_ESTORE
				,PD.SEDA_DIVISION_ESTORE
				,PD.SEDA_CATEGORY_ESTORE
				,PD.SEDA_FAMILY_ESTORE
				,PD.SEDA_DESC_ESTORE
				
				--MEASURES
				,SO.QTY AS QTY
				,SO.AMOUNT_LOCAL AS AMOUNT_LOCAL
				,CAST( (SO.AMOUNT_LOCAL / EX.EXCHANGE_RATE ) AS DECIMAL(18,2) ) AS AMOUNT_USD
				
				-- ****** PO DATA ******* (NULA ENQUANTO SEM LIGAÇÃO COM KITS)
				--,PO.PRICE_FROM
				--,NULL AS PRICE_FROM
				--,PO.PRICE_TO
				,NULL AS PRICE_TO
				--,PO.AMOUNT_DISCOUNT
				,NULL AS AMOUNT_DISCOUNT
				--,PO.AMOUNT_SHIPPING
				,NULL AS AMOUNT_SHIPPING
				--,PO.ITEM_NAME
				,NULL AS ITEM_NAME
				-- **********************
				
				-- ****** PO DATA *******  (INFORMAÇÕES DA ORDER ESTÁ OK "NÃO É KIT")
				,PO.ORDER_ID
				,PO.MARKETPLACE_ORDER_ID
				,SO.CUSTOMER_PO AS CUSTOMER_PO
				,PO.ENVIRONMENT
				,PO.STORE_ID
				,PO.NAME_STORE
				,PO.CHANNEL_TYPE 
	
				--,PO.REFERENCE_CODE_KIT -- ****** PO DATA ******* (NULA ENQUANTO SEM LIGAÇÃO COM KITS)
				,NULL AS REFERENCE_CODE_KIT
				
				,SO.MATERIAL AS REFERENCE_CODE
				,NULL AS STATUS_PO -- PO.STATUS_PO
				
				-- AFFILIATE
				,PO.AFFILIATE_ID_ADJUSTED
				,AF.AFFILIATE_CHANNEL
				,AF.AFFILIATE_SUB_CHANNEL
				,AF.AFFILIATE_PARTNER_LEVEL
				,AF.GLOBAL_CHANNEL
				,AF.BIZ_TYPE
				,AF.AUDIENCE_TYPE
				,BA.COUNTRY
				,BA.CURRENCY
				
				-- PREMIUM MODEL
				,--CASE WHEN PM.MONTH IS NOT NULL THEN
					CASE WHEN PR.MATERIAL IS NOT NULL THEN 'PREMIUM MODEL' ELSE 'NORMAL MODEL' END
				 --ELSE NULL END
				 AS MODEL_TYPE
				
				,CURRENT_TIMESTAMP AS KPI_LAST_UPDATE
			FROM(
				/*****************************************************************
				 SO (SALES ORDER TRACKING {SO_CREATE_ON})
				*****************************************************************/
				SELECT 
					'SO' AS SOURCE
					,TO_DATE(SO.SO_LOCAL_CREATE_ON_D) AS DATE_REF
					,SO.SALES_ORG
					,SO.MATERIAL
					,SO.CUSTOMER_PO
					,CASE WHEN SO.SO_CURR IS NOT NULL THEN SO.SO_CURR ELSE 'BRL' END AS CURRENCY
					,CAST(SO.ORDER_QTY_BASE AS INTEGER) AS QTY
					,CAST(REPLACE(SO.SO_NET_VALUE, ',', '') AS DECIMAL(18,2)) AS AMOUNT_LOCAL
				FROM OW_LAO.ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING SO
				WHERE 1=1
					AND TO_DATE(SO.SO_LOCAL_CREATE_ON_D) >= ADD_DAYS(CURRENT_TIMESTAMP, -15)
					AND (
						SO.SALES_DOC_TYPE = 'YS10' -- (SOMENTE D2C)
						OR SO.SALES_ORG IN ('3A01', '8109', '8101', '8105', '8107') -- SELA
					)
					--AND SO.SALES_ORG = '8201' -- SEDA
					--AND SO.SHIPPING_TYPE IN('P3','P4')
					AND SO.REJECT_REASON IS NULL
					AND SO.REJECT_REASON_1 IS NULL
					AND SO.SO_LOCAL_CREATE_ON_D IS NOT NULL
				/************************************************
				 IOD (SALES ORDER TRACKING {BILLING_DATE})
				************************************************/
				UNION ALL
				SELECT
					'IOD' AS SOURCE
					,TO_DATE(SO.BILLING_DATE) AS DATE_REF
					,SO.SALES_ORG
					,SO.MATERIAL
					,SO.CUSTOMER_PO
					,CASE WHEN SO.SO_CURR IS NOT NULL THEN SO.SO_CURR ELSE 'BRL' END AS CURRENCY
					,CAST(SO.BILLED_QTY_BASE AS INTEGER) AS QTY
					,CAST(REPLACE(SO.BILLING_NET_VALUE, ',', '') AS DECIMAL(18,2)) AS AMOUNT_LOCAL
				FROM OW_LAO.ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING SO
				WHERE 1=1
					AND TO_DATE(SO.BILLING_DATE) >= ADD_DAYS(CURRENT_TIMESTAMP, -15)
					AND ( SO.SALES_DOC_TYPE = 'YS10' -- (SOMENTE D2C)
						OR SO.SALES_ORG IN ('3A01', '8109', '8101', '8105', '8107') -- SELA
					)
					--AND SO.SALES_ORG = '8201' -- SEDA
					--AND SO.SHIPPING_TYPE IN('P3','P4')
					AND SO.REJECT_REASON IS NULL
					AND SO.REJECT_REASON_1 IS NULL
					AND SO.BILLING_DATE IS NOT NULL
					AND YEAR(SO.BILLING_DATE) >= 2023 -- 2022 VEM DA SELLIN_22
				) SO
				LEFT JOIN OW_MD.DIM_PRODUCT PD ON SO.MATERIAL = PD.SKU
				LEFT JOIN OW_MD.DIM_CALENDAR CL ON SO.DATE_REF = CL.YYYYMMDD
				LEFT JOIN OW_LAO.DIM_BUSINESS_AREA BA ON BA.SALES_ORG = SO.SALES_ORG
				LEFT JOIN OW_LAO.FT_AP2_EXCHANGE_RATE EX
					ON 	EX.VALID_FROM = SO.DATE_REF
						AND EX.TO_CURRENCY = SO.CURRENCY
						AND EX.FROM_CURRENCY = 'USD'
				LEFT JOIN( 
						SELECT -- AGRUPA PARA PEGAR SOMENTE INFORMAÇÕES DA ORDER PO (S/ LIGAÇÃO C/ KITS DUPLICA MATERIAL DA SO)
							 CUSTOMER_PO
							,MAX("SELECTED_SLA") AS "SELECTED_SLA"
							,MAX("WAREHOUSE_ID_GROUP") AS "SELECTED_SLA"
							,MAX(AFFILIATE_ID_ADJUSTED) AS AFFILIATE_ID_ADJUSTED
							,MAX(SALES_CHANNEL) AS SALES_CHANNEL
							,MAX(PO_CREATION_DATE) AS PO_CREATION_DATE
							,MAX(AFFILIATE_ID) AS AFFILIATE_ID
							,MAX(ORDER_ID) AS ORDER_ID
							,MAX(MARKETPLACE_ORDER_ID) AS MARKETPLACE_ORDER_ID
							,MAX(ENVIRONMENT) AS ENVIRONMENT
							,MAX(STORE_ID) AS STORE_ID
							,MAX(NAME_STORE) AS NAME_STORE				
							,MAX(CHANNEL_TYPE) AS CHANNEL_TYPE
							,MAX(STATUS_PO) AS STATUS_PO
						FROM OW_LAO.TF_D2C_NERP_SALES
						WHERE SOURCE = 'PO'
						GROUP BY
							CUSTOMER_PO
					)PO ON SO.CUSTOMER_PO = PO.CUSTOMER_PO -- AND SO.MATERIAL = PO.REFERENCE_CODE (AINDA SEM LIGAÇÃO C/ KITS )
				LEFT JOIN OW_MD.DIM_SALES_CHANNEL CH ON PO.SALES_CHANNEL = CH.VTEX_POLICY
				LEFT JOIN OW_LAO.DIM_AFFILIATE_CHANNEL AF ON AF.AFFILIATE_ID = PO.AFFILIATE_ID_ADJUSTED
				LEFT JOIN (SELECT DISTINCT TRIM(ITEM) AS MATERIAL FROM OW_LAO.ODS_GSCM_PREMIUM_MODELS) PR ON PR.MATERIAL = SO.MATERIAL
				;
			
				/************************************************
				 IOD (SELLIN_2022)
				************************************************
					-- INSERE DADOS DE IOD DA SELLIN DE 2022 
				INSERT INTO OW_LAO.TF_D2C_NERP_SALES(
					"SOURCE"
					, DATE_REF
					, YYYYWW
					, YYYYMM
					, YYYYQQ
					, SUBSIDIARY
					, SKU
					, PDROD_DIVISION
					, PDROD_PRODUCT_GROUP
					, PDROD_PRODUCT
					, PROD_ATTB_1
					, SEDA_BU_ESTORE
					, SEDA_DIVISION_ESTORE
					, SEDA_CATEGORY_ESTORE
					, SEDA_FAMILY_ESTORE
					, SEDA_DESC_ESTORE
					, AMOUNT_USD
					, AMOUNT_LOCAL
					, REFERENCE_CODE
					, MODEL_TYPE
					, KPI_LAST_UPDATE)
				SELECT
					  'IOD' AS "SOURCE"
					, SO.DATE_REF
					, CL.YYYYWW AS YYYYWW
					, CL.YYYYMM AS YYYYMM
					, CL.YYYYQQ AS YYYYQQ
					, SO.SUBSIDIARY
					, SO.MATERIAL AS SKU
					, PD."DIVISION" AS PDROD_DIVISION
					, PD.PRODUCT_GROUP_1 AS PDROD_PRODUCT_GROUP 
					, PD.PRODUCT_1 AS PDROD_PRODUCT 
					, PD.ATTB01 AS PROD_ATTB_1 
					, PD.SEDA_BU_ESTORE
					, PD.SEDA_DIVISION_ESTORE
					, PD.SEDA_CATEGORY_ESTORE
					, PD.SEDA_FAMILY_ESTORE
					, PD.SEDA_DESC_ESTORE
					, SO.AMOUNT_USD
					, CAST( (SO.AMOUNT_USD * EX.EXCHANGE_RATE ) AS DECIMAL(18,2) ) AS AMOUNT_LOCAL				
					, PD.SKU
					-- PREMIUM MODEL
					, CASE WHEN PR.MATERIAL IS NOT NULL THEN 'PREMIUM MODEL' ELSE 'NORMAL MODEL' END AS MODEL_TYPE
					, CURRENT_TIMESTAMP AS KPI_LAST_UPDATE
				FROM OW_LAO.ODS_NERP_SELLIN_2022 SO
					LEFT JOIN OW_MD.DIM_PRODUCT PD ON SO.MATERIAL = PD.SKU
					LEFT JOIN OW_MD.DIM_CALENDAR CL ON SO.DATE_REF = CL.YYYYMMDD
					LEFT JOIN (SELECT DISTINCT TRIM(ITEM) AS MATERIAL FROM OW_LAO.ODS_GSCM_PREMIUM_MODELS) PR ON PR.MATERIAL = SO.MATERIAL
					LEFT JOIN OW_LAO.FT_AP2_EXCHANGE_RATE EX
						ON 	EX.VALID_FROM = SO.DATE_REF
							AND EX.TO_CURRENCY = 'BRL'
							AND EX.FROM_CURRENCY = 'USD'
				WHERE YEAR(SO.DATE_REF) = 2022	
				;
			************************************************/
			
		END IF;	
	
		/*****************************************************************
			GI / DO
		*****************************************************************/		
		-- CASO A DATA DA ULTIMA INGESTION NA OUTBOUND SEJA MAIOR QUE A DATA DE PROCESSAMENTO DE GI
		IF ((SELECT COUNT('') FROM OW_LAO.TF_D2C_NERP_SALES WHERE "SOURCE" IN('GI','DO')) = 0	-- TABELA VAZIA
			OR((  SELECT MAX(LOAD_DATE) AS OUTBOUND_LOAD_DATE
				  FROM OW_LAO.ODS_NERP_ZLLEJ50090_OUTBOUND_TRACKING
				) >
				( SELECT MAX(KPI_LAST_UPDATE) AS GI_UPDATED
				  FROM OW_LAO.TF_D2C_NERP_SALES
				  WHERE "SOURCE" IN ('GI','DO')
				)
			)
		) THEN
			
			-- APAGA DADOS DE GI E DO
			DELETE FROM OW_LAO.TF_D2C_NERP_SALES
			WHERE SOURCE IN ('GI','DO')
					AND DATE_REF >= ADD_DAYS(CURRENT_TIMESTAMP, -15)
			;
			
			-- INSERE DADOS DE GI E DO
			INSERT INTO OW_LAO.TF_D2C_NERP_SALES("SOURCE", DATE_REF, YYYYWW, YYYYMM, YYYYQQ, PO_CREATION_DATE , "PO_WEEK_DAY_NUM", "PO_WEEK_DAY_NAME" , "PO_HOUR", SALES_CHANNEL, SUBSIDIARY, CHANNEL, SUB_CHANNEL, SALES_CHANNEL_ATTR_1, SALES_CHANNEL_ATTR_2, AFFILIATE_ID, SKU, PDROD_DIVISION, PDROD_PRODUCT_GROUP, PDROD_PRODUCT, PROD_ATTB_1, SEDA_BU_ESTORE, SEDA_DIVISION_ESTORE, SEDA_CATEGORY_ESTORE, SEDA_FAMILY_ESTORE, SEDA_DESC_ESTORE, QTY, AMOUNT_LOCAL, AMOUNT_USD, PRICE_TO, AMOUNT_DISCOUNT, AMOUNT_SHIPPING, ITEM_NAME, ORDER_ID, MARKETPLACE_ORDER_ID, CUSTOMER_PO, ENVIRONMENT, STORE_ID, NAME_STORE, CHANNEL_TYPE, REFERENCE_CODE_KIT, REFERENCE_CODE, STATUS_PO, AFFILIATE_ID_ADJUSTED, AFFILIATE_CHANNEL, AFFILIATE_SUB_CHANNEL, AFFILIATE_PARTNER_LEVEL, GLOBAL_CHANNEL, BIZ_TYPE, AUDIENCE_TYPE, COUNTRY, CURRENCY, MODEL_TYPE, KPI_LAST_UPDATE, PLANT, PLANT_NAME)
			SELECT
				 SO.SOURCE
				,SO.DATE_REF
				,CL.YYYYWW AS YYYYWW
				,CL.YYYYMM AS YYYYMM
				,CL.YYYYQQ AS YYYYQQ
				,PO.PO_CREATION_DATE
				
				,WEEKDAY(SO.DATE_REF) AS "PO_WEEK_DAY_NUM"
				,DAYNAME(SO.DATE_REF) AS "PO_WEEK_DAY_NAME"
				,EXTRACT_HOUR(SO.TIME_LOCAL) AS "PO_HOUR"
						
				-- CHANNEL
				,PO.SALES_CHANNEL
				,TRIM(BA.SUBSIDIARY_2) AS SUBSIDIARY
				,CH.CHANNEL 
				,CH.SUB_CHANNEL 
				,CH.SALES_CHANNEL_ATTR_1 
				,CH.SALES_CHANNEL_ATTR_2
				,PO.AFFILIATE_ID
				-- PRODUCT
				,PD.SKU
				,PD."DIVISION" AS PDROD_DIVISION
				,PD.PRODUCT_GROUP_1 AS PDROD_PRODUCT_GROUP 
				,PD.PRODUCT_1 AS PDROD_PRODUCT 
				,PD.ATTB01 AS PROD_ATTB_1 
				,PD.SEDA_BU_ESTORE
				,PD.SEDA_DIVISION_ESTORE
				,PD.SEDA_CATEGORY_ESTORE
				,PD.SEDA_FAMILY_ESTORE
				,PD.SEDA_DESC_ESTORE
				
				--MEASURES
				,SO.QTY AS QTY
				,SO.AMOUNT_LOCAL AS AMOUNT_LOCAL
				,CAST( (SO.AMOUNT_LOCAL / EX.EXCHANGE_RATE ) AS DECIMAL(18,2) ) AS AMOUNT_USD
				
				-- ****** PO DATA ******* (NULA ENQUANTO SEM LIGAÇÃO COM KITS)
				--,PO.PRICE_FROM
				--,NULL AS PRICE_FROM
				--,PO.PRICE_TO
				,NULL AS PRICE_TO
				--,PO.AMOUNT_DISCOUNT
				,NULL AS AMOUNT_DISCOUNT
				--,PO.AMOUNT_SHIPPING
				,NULL AS AMOUNT_SHIPPING
				--,PO.ITEM_NAME
				,NULL AS ITEM_NAME
				-- **********************
				
				-- ****** PO DATA *******  (INFORMAÇÕES DA ORDER ESTÁ OK "NÃO É KIT")
				,PO.ORDER_ID
				,PO.MARKETPLACE_ORDER_ID
				,SO.CUSTOMER_PO AS CUSTOMER_PO
				,PO.ENVIRONMENT
				,PO.STORE_ID
				,PO.NAME_STORE
				,PO.CHANNEL_TYPE 
	
				--,PO.REFERENCE_CODE_KIT -- ****** PO DATA ******* (NULA ENQUANTO SEM LIGAÇÃO COM KITS)
				,NULL AS REFERENCE_CODE_KIT
				
				,SO.MATERIAL AS REFERENCE_CODE
				,NULL AS STATUS_PO -- PO.STATUS_PO
				
				-- AFFILIATE
				,PO.AFFILIATE_ID_ADJUSTED
				,AF.AFFILIATE_CHANNEL
				,AF.AFFILIATE_SUB_CHANNEL
				,AF.AFFILIATE_PARTNER_LEVEL
				,AF.GLOBAL_CHANNEL
				,AF.BIZ_TYPE
				,AF.AUDIENCE_TYPE
				,BA.COUNTRY
				,BA.CURRENCY
			
				-- PREMIUM MODEL
				, CASE WHEN PR.MATERIAL IS NOT NULL THEN 'PREMIUM MODEL' ELSE 'NORMAL MODEL' END AS MODEL_TYPE
				
				, CURRENT_TIMESTAMP AS KPI_LAST_UPDATE
				
				, SO.PLANT
				, DP.ORIGIN AS PLANT_NAME
			FROM(
				/************************************************
				 GI (OUTBOUND {1ST_GI_DATE})
				************************************************/
				SELECT
					'GI' AS SOURCE
					,OB."1ST_GI_DATE" AS DATE_REF
					,NULL AS TIME_LOCAL
					,OB.SALES_ORG
					,OB.MATERIAL
					,SO.CUSTOMER_PO
					,OB.PLANT
					,CASE WHEN SO.SO_CURR IS NOT NULL THEN SO.SO_CURR ELSE 'BRL' END AS CURRENCY
					,CAST(SUBSTR(OB."1ST_GI_QTY", 1, LENGTH(OB."1ST_GI_QTY") - 2) AS INTEGER) AS QTY
					,CAST(REPLACE(OB.NET_VALUE, ',', '') AS DECIMAL(18,2)) AS AMOUNT_LOCAL
				FROM OW_LAO.ODS_NERP_ZLLEJ50090_OUTBOUND_TRACKING OB  -- Outbound (OB)
					LEFT JOIN OW_LAO.ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING SO -- Sales Order (SO) 
						ON 	OB.DELIVERY_NO = SO.DELIVERY
							AND OB.MATERIAL = SO.MATERIAL
							AND OB.DELIVERY_ITEM = SO.DELIVERY_ITEM
				WHERE 1=1
					AND OB."1ST_GI_DATE" >= ADD_DAYS(CURRENT_TIMESTAMP, -15)
					AND OB.DO_TYPE = 'ZND1'
					--AND OB.SALES_ORG = '8201' -- SEDA
					--AND OB.SHIPPING_TYPE  IN('P3','P4')
					AND (
							OB.SO_TYPE = 'YS10' -- (SOMENTE D2C)
							OR OB.SALES_ORG IN ('3A01', '8109', '8101', '8105', '8107') -- SELA
						)
					AND OB."1ST_GI_DATE" IS NOT NULL
					
				/************************************************
				 DO (OUTBOUND {DOCUMENT_DATE_LOCAL})
				************************************************/
				UNION ALL
				
				SELECT
					'DO' AS SOURCE
					,OB.DOCUMENT_DATE_LOCAL AS DATE_REF
					,OB.DOCUMENT_TIME_LOCAL AS TIME_LOCAL
					,OB.SALES_ORG
					,OB.MATERIAL
					,SO.CUSTOMER_PO
					,OB.PLANT
					,CASE WHEN SO.SO_CURR IS NOT NULL THEN SO.SO_CURR ELSE 'BRL' END AS CURRENCY
					,CAST(OB."DELIVERY_QTY" AS INTEGER) AS QTY
					--,CAST(SUBSTR(OB."1ST_GI_QTY", 1, LENGTH(OB."1ST_GI_QTY") - 2) AS INTEGER) AS QTY
					,CAST(REPLACE(OB.NET_VALUE, ',', '') AS DECIMAL(18,2)) AS AMOUNT_LOCAL
				FROM OW_LAO.ODS_NERP_ZLLEJ50090_OUTBOUND_TRACKING OB  -- Outbound (OB)
					LEFT JOIN OW_LAO.ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING SO -- Sales Order (SO) 
						ON 	OB.DELIVERY_NO = SO.DELIVERY
							AND OB.MATERIAL = SO.MATERIAL
							AND OB.DELIVERY_ITEM = SO.DELIVERY_ITEM
				WHERE 1=1
					AND OB.DOCUMENT_DATE_LOCAL >= ADD_DAYS(CURRENT_TIMESTAMP, -15)
					AND OB.DO_TYPE = 'ZND1'
					--AND OB.SALES_ORG = '8201' -- SEDA
					--AND OB.SHIPPING_TYPE  IN('P3','P4')
					AND (
							OB.SO_TYPE = 'YS10' -- (SOMENTE D2C)
							OR OB.SALES_ORG IN ('3A01', '8109', '8101', '8105', '8107') -- SELA
						)
					AND OB.DOCUMENT_DATE_LOCAL IS NOT NULL
				) SO
				LEFT JOIN OW_MD.DIM_PLANT DP ON SO.PLANT = DP.PLANT_CODE
				LEFT JOIN OW_MD.DIM_PRODUCT PD ON SO.MATERIAL = PD.SKU
				LEFT JOIN OW_MD.DIM_CALENDAR CL ON SO.DATE_REF = CL.YYYYMMDD
				LEFT JOIN OW_LAO.DIM_BUSINESS_AREA BA ON BA.SALES_ORG = SO.SALES_ORG
				LEFT JOIN OW_LAO.FT_AP2_EXCHANGE_RATE EX
					ON 	EX.VALID_FROM = SO.DATE_REF
						AND EX.TO_CURRENCY = SO.CURRENCY
						AND EX.FROM_CURRENCY = 'USD'
				LEFT JOIN( 
						SELECT -- AGRUPA PARA PEGAR SOMENTE INFORMAÇÕES DA ORDER PO (S/ LIGAÇÃO C/ KITS DUPLICA MATERIAL DA SO)
							 CUSTOMER_PO
							,MAX("SELECTED_SLA") AS "SELECTED_SLA"
							,MAX("WAREHOUSE_ID_GROUP") AS "SELECTED_SLA"
							,MAX(AFFILIATE_ID_ADJUSTED) AS AFFILIATE_ID_ADJUSTED
							,MAX(SALES_CHANNEL) AS SALES_CHANNEL
							,MAX(PO_CREATION_DATE) AS PO_CREATION_DATE
							,MAX(AFFILIATE_ID) AS AFFILIATE_ID
							,MAX(ORDER_ID) AS ORDER_ID
							,MAX(MARKETPLACE_ORDER_ID) AS MARKETPLACE_ORDER_ID
							,MAX(ENVIRONMENT) AS ENVIRONMENT
							,MAX(STORE_ID) AS STORE_ID
							,MAX(NAME_STORE) AS NAME_STORE				
							,MAX(CHANNEL_TYPE) AS CHANNEL_TYPE
							,MAX(STATUS_PO) AS STATUS_PO
						FROM OW_LAO.TF_D2C_NERP_SALES
						WHERE "SOURCE" = 'PO'
						GROUP BY
							CUSTOMER_PO
					)PO ON SO.CUSTOMER_PO = PO.CUSTOMER_PO -- AND SO.MATERIAL = PO.REFERENCE_CODE (AINDA SEM LIGAÇÃO C/ KITS )
				LEFT JOIN OW_MD.DIM_SALES_CHANNEL CH ON PO.SALES_CHANNEL = CH.VTEX_POLICY
				LEFT JOIN OW_LAO.DIM_AFFILIATE_CHANNEL AF ON AF.AFFILIATE_ID = PO.AFFILIATE_ID_ADJUSTED
				LEFT JOIN (SELECT DISTINCT TRIM(ITEM) AS MATERIAL FROM OW_LAO.ODS_GSCM_PREMIUM_MODELS) PR ON PR.MATERIAL = SO.MATERIAL
				;
		END IF;
	
	
		/*****************************************************************
		*  ATUALIZA DIMENSÕES
		*****************************************************************	
		-- PRODUCT
		UPDATE NS SET 
			  PDROD_DIVISION = PD."DIVISION" -- AS PDROD_DIVISION
			, PDROD_PRODUCT_GROUP = PD.PRODUCT_GROUP_1 -- AS PDROD_PRODUCT_GROUP
			, PDROD_PRODUCT = PD.PRODUCT_1 -- AS PDROD_PRODUCT
			, PROD_ATTB_1 = PD.ATTB01 -- AS PROD_ATTB_1
			, SEDA_BU_ESTORE = PD.SEDA_BU_ESTORE -- AS SEDA_BU_ESTORE
			, SEDA_DIVISION_ESTORE = PD.SEDA_DIVISION_ESTORE -- AS SEDA_DIVISION_ESTORE
			, SEDA_CATEGORY_ESTORE = PD.SEDA_CATEGORY_ESTORE -- AS SEDA_CATEGORY_ESTORE
			, SEDA_FAMILY_ESTORE = PD.SEDA_FAMILY_ESTORE -- AS SEDA_FAMILY_ESTORE
			, SEDA_DESC_ESTORE = PD.SEDA_DESC_ESTORE -- AS SEDA_DESC_ESTORE
		FROM OW_LAO.TF_D2C_NERP_SALES NS
			INNER JOIN OW_MD.DIM_PRODUCT PD ON PD.SKU = NS.REFERENCE_CODE
		WHERE (NS.PDROD_DIVISION IS NULL AND NS.SEDA_DIVISION_ESTORE IS NULL)  -- NÃO EXISTIA ANTES
			OR PD."DIVISION" <> NS.PDROD_DIVISION
			OR PD.PRODUCT_GROUP_1 <> NS.PDROD_PRODUCT_GROUP
			OR PD.PRODUCT_1 <> NS.PDROD_PRODUCT
			OR PD.ATTB01 <> NS.PROD_ATTB_1
			OR PD.SEDA_BU_ESTORE <> NS.SEDA_BU_ESTORE
			OR PD.SEDA_DIVISION_ESTORE <> NS.SEDA_DIVISION_ESTORE
			OR PD.SEDA_CATEGORY_ESTORE <> NS.SEDA_CATEGORY_ESTORE
			OR PD.SEDA_FAMILY_ESTORE <> NS.SEDA_FAMILY_ESTORE
			OR PD.SEDA_DESC_ESTORE <> NS.SEDA_DESC_ESTORE
		;
	
		UPDATE NS SET 
			  PDROD_DIVISION = PD."DIVISION" -- AS PDROD_DIVISION
			, PDROD_PRODUCT_GROUP = PD.PRODUCT_GROUP_1 -- AS PDROD_PRODUCT_GROUP
			, PDROD_PRODUCT = PD.PRODUCT_1 -- AS PDROD_PRODUCT
			, PROD_ATTB_1 = PD.ATTB01 -- AS PROD_ATTB_1
			, SEDA_BU_ESTORE = PD.SEDA_BU_ESTORE -- AS SEDA_BU_ESTORE
			, SEDA_DIVISION_ESTORE = PD.SEDA_DIVISION_ESTORE -- AS SEDA_DIVISION_ESTORE
			, SEDA_CATEGORY_ESTORE = PD.SEDA_CATEGORY_ESTORE -- AS SEDA_CATEGORY_ESTORE
			, SEDA_FAMILY_ESTORE = PD.SEDA_FAMILY_ESTORE -- AS SEDA_FAMILY_ESTORE
			, SEDA_DESC_ESTORE = PD.SEDA_DESC_ESTORE -- AS SEDA_DESC_ESTORE
		FROM OW_LAO.TF_D2C_NERP_SALES NS
			INNER JOIN OW_MD.DIM_PRODUCT PD ON PD.SKU = NS.REFERENCE_CODE
		WHERE NS.PDROD_DIVISION IS NULL
			AND PD."DIVISION" IS NOT NULL;	
	
		-- AFFILIATE CHANNEL
		UPDATE NS SET
			  AFFILIATE_CHANNEL = AF.AFFILIATE_CHANNEL -- AS AFFILIATE_CHANNEL
			, AFFILIATE_SUB_CHANNEL = AF.AFFILIATE_SUB_CHANNEL -- AS AFFILIATE_SUB_CHANNEL
			, AFFILIATE_PARTNER_LEVEL = AF.AFFILIATE_PARTNER_LEVEL -- AS AFFILIATE_PARTNER_LEVEL
			, GLOBAL_CHANNEL = AF.GLOBAL_CHANNEL -- AS GLOBAL_CHANNEL
			, BIZ_TYPE = AF.BIZ_TYPE -- AS BIZ_TYPE
			, AUDIENCE_TYPE = AF.AUDIENCE_TYPE -- AS AUDIENCE_TYPE
		FROM OW_LAO.TF_D2C_NERP_SALES NS
			INNER JOIN OW_LAO.DIM_AFFILIATE_CHANNEL AF ON AF.AFFILIATE_ID = NS.AFFILIATE_ID_ADJUSTED
		WHERE (NS.AFFILIATE_CHANNEL IS NULL AND AF.AFFILIATE_CHANNEL IS NOT NULL) -- NÃO EXISTIA ANTES
			OR AF.AFFILIATE_CHANNEL <> NS.AFFILIATE_CHANNEL
			OR AF.AFFILIATE_SUB_CHANNEL <> NS.AFFILIATE_SUB_CHANNEL
			OR AF.AFFILIATE_PARTNER_LEVEL <> NS.AFFILIATE_PARTNER_LEVEL
			OR AF.GLOBAL_CHANNEL <> NS.GLOBAL_CHANNEL
			OR AF.BIZ_TYPE <> NS.BIZ_TYPE
			OR AF.AUDIENCE_TYPE <> NS.AUDIENCE_TYPE
		;
		
		/*****************************************************************
		EXECUTA PROCESSOS KPIs
		*****************************************************************	
		-- EXECUTA PROC PROC_D2C_NERP_WEEKLY_SALES_KPI
		CALL OW_LAO.PROC_D2C_NERP_WEEKLY_SALES_KPI;
		
		-- EXECUTA PROC SALES_BY_HOUR_KPI
		CALL OW_LAO.PROC_D2C_NERP_SALES_BY_HOUR_KPI;
	
		-- EXECUTA PROC O2O_SALES
		CALL OW_LAO.PROC_D2C_VTEX_O2O_SALES_KPI;
	
		-- EXECUTA PROC SALES_REWARDS
		CALL OW_LAO.PROC_D2C_NERP_SALES_REWARDS_KPI;
	
		-- EXECUTA PROC PO VTEX SALES
		CALL OW_LAO.PROC_D2C_PO_VTEX_SALES_KPI;
		--MENSAGEM
		SELECT 'TF_D2C_NERP_SALES ATUALIZADA COM SUCESSO!' AS RESULTADO ,CURRENT_DATE AS DATE_NOW FROM dummy;
		
	ELSE
		--MENSAGEM
		SELECT 'NÃO HÁ REGISTROS PARA ATUALIZAR' AS RESULTADO ,CURRENT_DATE AS DATE_NOW FROM dummy;		
	END IF;
	
			*****************************************************************/	
	
END