/***********************************************************************************************
CREATED BY : Luciano Mariani
CREATION DATE : 2023-08-01
ALTER DATE : 
VERSION: 1.0 (Live comerce) e (Rewards) 
-- CALL OW_LAO.PROC_D2C_NERP_SALES_REWARDS_KPI;
SELECT TOP 100 * FROM OW_LAO.TF_D2C_NERP_SALES_REWARDS_KPI
***********************************************************************************************/
CREATE PROCEDURE OW_LAO.PROC_D2C_NERP_SALES_REWARDS_KPI LANGUAGE SQLSCRIPT
AS
BEGIN
	
	--APAGA TATBELA FATO TF_D2C_NERP_SALES_REWARDS_KPI
	IF EXISTS(
		SELECT TABLE_NAME
		FROM SYS.TABLES
		WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TF_D2C_NERP_SALES_REWARDS_KPI'
	)
	THEN
		DROP TABLE OW_LAO.TF_D2C_NERP_SALES_REWARDS_KPI;
	END IF;
	--CRIA NOVA TATBELA FATO TF_D2C_NERP_SALES_REWARDS_KPI
	CREATE COLUMN TABLE OW_LAO.TF_D2C_NERP_SALES_REWARDS_KPI AS (
			SELECT
				 "SOURCE"
				,DATE_REF
				,YYYYWW
				,YYYYMM
				,YYYYQQ
				,SUBSIDIARY
				--,CHANNEL
				--,SUB_CHANNEL
				--,SALES_CHANNEL_ATTR_1
				--,SALES_CHANNEL_ATTR_2
				,CHANNEL_TYPE
				,SKU
				,PDROD_DIVISION
				,PDROD_PRODUCT_GROUP
				,PDROD_PRODUCT
				,PROD_ATTB_1
				,SEDA_BU_ESTORE
				,SEDA_CATEGORY_ESTORE
				,SEDA_DESC_ESTORE
				,SEDA_DIVISION_ESTORE
				,SEDA_FAMILY_ESTORE
				,STATUS_PO --,CASE WHEN "SOURCE" = 'PO' THEN STATUS_PO ELSE NULL END AS STATUS_PO
				-- AFFILIATE
				,AFFILIATE_CHANNEL
				,AFFILIATE_SUB_CHANNEL
				,AFFILIATE_PARTNER_LEVEL
				,GLOBAL_CHANNEL
				--,BIZ_TYPE
				,AUDIENCE_TYPE
				,COUNTRY
				,CURRENCY
				,MODEL_TYPE
				,LOWER(COUPON) AS COUPON
				,LOWER(CASE
					WHEN 
						UPPER(COUPON) LIKE '%REW%'
						OR UPPER(COUPON) LIKE '%RWD%'
					THEN 'REWARDS'					
					WHEN 
						UPPER(COUPON) LIKE '%LIVE%'
					THEN 'LIVE'
					WHEN 
						UPPER(COUPON) LIKE '%BLUE%'
					THEN 'BLUE'
					WHEN 
						UPPER(COUPON) LIKE '%GALAXYWATCH%'
						OR UPPER(COUPON) LIKE '%GALAXYBUDS%'
						OR UPPER(COUPON) LIKE '%GALAXYTAB%'
						OR UPPER(COUPON) LIKE '%GALAXYBOOK%'
						OR UPPER(COUPON) LIKE '%LPREWARDS%'
					THEN 'REWARDS'
				ELSE 'OTHERS' END) AS "COUPON_FILTER"
				
				,SUM(QTY) AS QTY
				,SUM(AMOUNT_LOCAL) AS AMOUNT_LOCAL
				,SUM(AMOUNT_USD) AS AMOUNT_USD
				,CURRENT_TIMESTAMP AS KPI_LAST_UPDATE --,KPI_LAST_UPDATE
			FROM OW_LAO.TF_D2C_NERP_SALES
			WHERE STATUS_PO IS NULL 
				OR STATUS_PO NOT IN('cancel','canceled')
			GROUP BY
				 "SOURCE"
				,DATE_REF
				,YYYYWW
				,YYYYMM
				,YYYYQQ
				,SUBSIDIARY
				--,CHANNEL
				--,SUB_CHANNEL
				--,SALES_CHANNEL_ATTR_1
				--,SALES_CHANNEL_ATTR_2
				,CHANNEL_TYPE
				,SKU
				,PDROD_DIVISION
				,PDROD_PRODUCT_GROUP
				,PDROD_PRODUCT
				,PROD_ATTB_1
				,SEDA_BU_ESTORE
				,SEDA_CATEGORY_ESTORE
				,SEDA_DESC_ESTORE
				,SEDA_DIVISION_ESTORE
				,SEDA_FAMILY_ESTORE
				,STATUS_PO --CASE WHEN "SOURCE" = 'PO' THEN STATUS_PO ELSE NULL END --AS STATUS_PO
				,AFFILIATE_CHANNEL
				,AFFILIATE_SUB_CHANNEL
				,AFFILIATE_PARTNER_LEVEL
				,GLOBAL_CHANNEL
				--,BIZ_TYPE
				,AUDIENCE_TYPE
				,COUNTRY
				,CURRENCY
				,MODEL_TYPE
				,LOWER(COUPON) -- AS COUPON
				,LOWER(CASE
					WHEN 
						UPPER(COUPON) LIKE '%REW%'
						OR UPPER(COUPON) LIKE '%RWD%'
					THEN 'REWARDS'					
					WHEN 
						UPPER(COUPON) LIKE '%LIVE%'
					THEN 'LIVE'
					WHEN 
						UPPER(COUPON) LIKE '%BLUE%'
					THEN 'BLUE'
					WHEN 
						UPPER(COUPON) LIKE '%GALAXYWATCH%'
						OR UPPER(COUPON) LIKE '%GALAXYBUDS%'
						OR UPPER(COUPON) LIKE '%GALAXYTAB%'
						OR UPPER(COUPON) LIKE '%GALAXYBOOK%'
						OR UPPER(COUPON) LIKE '%LPREWARDS%'
					THEN 'REWARDS'
				ELSE 'OTHERS' END) --AS "COUPON_FILTER"
	);
	UPDATE OW_LAO.TF_D2C_NERP_SALES_REWARDS_KPI SET
		KPI_LAST_UPDATE = (
				SELECT MAX(PO_CREATION_DATE)
				FROM OW_LAO.TF_D2C_NERP_SALES
				WHERE "SOURCE" = 'PO'
					AND SUBSIDIARY = 'SEDA'
			  )
	;
	
END