CREATE PROCEDURE OW_LAO.PROC_D2C_AR_TABLE_WEEK_PT2
LANGUAGE SQLSCRIPT as
BEGIN
--DELETE Records at FT with same Year WEEK in TMP
DELETE FROM OW_LAO.FT_D2C_AR_TABLE_WEEK FT
-- TO REPROCESS THE COMPLETE BASE, CHANGE "=" TO "IN" ON THE LINE BELOW
WHERE FT.YEAR_WEEK_BY_FILENAME IN (SELECT DISTINCT TDATM.YEAR_WEEK_BY_FILENAME 
					FROM OW_LAO.TMP_D2C_AR_TABLE_WEEK TDATM);
--Inserir os dados no nivel granular mais baixo na tabela fato
INSERT INTO OW_LAO.FT_D2C_AR_TABLE_WEEK
SELECT   TDATM.ORDER_ID
	,TDATM."SEQUENCE"
	,TDATM.PO_AMOUNT
	,TDATM.AMT_PO_DISTINCT
	,TDATM.QTY_PO_DISTINCT
	,TDATM.DIMPROD_PRODUCT_GROUP
	,TDATM.DIMPROD_DIVISION
	,TDATM.DIMPROD_PRODUCT
	,TDATM.AFFILIATE_CHANNEL
	,TDATM.AFFILIATE_SUB_CHANNEL
	,TDATM."Key"
	,TDATM."Key2"
	,TDATM.GL_ACCOUNT_KOREAN
	,TDATM.GL_ACCOUNT_ENGLISH	
	,TDATM."System Due date (In/Over)"
	,TDATM."Range"
	,TDATM."Customer Group (eStore/MKP)"
	,TDATM."(+/-) AR"
	,TDATM.CUSTOMER_NAME
	,TDATM.CUSTOMER
	,TDATM.DOCUMENT_TYPE
	,TDATM.POSTING_KEY
	,TDATM.PAYMENT_TERMS
	,TDATM.REFERENCE
	,TDATM.DOCUMENT_DATE
	,TDATM."ASSIGNMENT"
	,TDATM.AMOUNT_IN_LOCAL_CURRENCY
	,TDATM.NET_DUE_DATE
	,TDATM.ARREARS_BY_NET_DUE_DATE
	,TDATM.DOCUMENT_NUMBER
	,TDATM.CLEARING_DOCUMENT
	,TDATM.CLEARING_DATE
	,TDATM."TEXT"
	,TDATM.REASON_CODE
	,TDATM.ENTRY_DATE
	,TDATM."Week Entry"
	,TDATM."G/L_ACCOUNT"
	,TDATM.BILLING_DOCUMENT
	,TDATM.BUSINESS_AREA
	,TDATM.LINE_ITEM
	,TDATM.INVOICE_REFERENCE
	,TDATM."G/L_ACCOUNT_1"
	,TDATM.POSTING_DATE
	,TDATM."Week Posting"
	,TDATM.REFERENCE_KEY_3
	,TDATM.DOCUMENT_HEADER_TEXT
	,TDATM.REFERENCE_KEY_1
	,TDATM.REFERENCE_KEY_2
	,TDATM."YEAR/MONTH"
	,TDATM.USER_NAME
	,TDATM.LOCAL_CURRENCY
	,TDATM.FILE_LOAD_DATE
	,TDATM.YEAR_WEEK_BY_FILENAME
	,TDATM.YEAR_WEEK
	,MTFASC."TYPE ITEM"
	,(CASE WHEN /*MTFASC."TYPE"*/MTFASC."KEY" IS NULL 
		THEN 'Process Delay'
		ELSE MTFASC."TYPE"
	END) AS "TYPE"
	,(CASE WHEN /*MTFASC."1_CATE"*/MTFASC."KEY" IS NULL
		THEN 'Others (In analysis)'
		ELSE MTFASC."1_CATE"
	END) AS "1_CATE"
	,(CASE WHEN /*MTFASC."2_CATE"*/MTFASC."KEY" IS NULL
		THEN 'In analysis (1st and 2nd analysis)'
		ELSE MTFASC."2_CATE"
	END) AS "2_CATE"
	,MTFASC."3_CATE"
	,(CASE WHEN /*MTFASC."REASON TYPE"*/MTFASC."KEY" IS NULL
		THEN 'System (Manual, missing I/F)'
		ELSE MTFASC."REASON TYPE"
	END) AS "REASON TYPE"
	,(CASE WHEN /*MTFASC.PIC*/MTFASC."KEY" IS NULL
		THEN 'OST'
		ELSE MTFASC.PIC
	END) AS PIC
	,MTFASC.REMARK
	,MTFASC."NEXT STEP"
	,MTFASC."SUB. CATEGORY 2"
	,TDATM."System due date (in/Over)&(+/-) AR&Sub. Category 2"
	,TDATM.LOAD_DATE
FROM OW_LAO.TMP_D2C_AR_TABLE_WEEK TDATM
LEFT JOIN OW_MD.MAP_AR_WEEK_TO_FROM_AR_SCM_CLASSIFICATION MTFASC ON (TDATM."Key" = MTFASC."KEY"
	--Alterar quando voltar de férias, pegar arquivo de week
	AND TDATM.YEAR_WEEK_BY_FILENAME = MTFASC.PERIOD)
;
UPDATE OW_LAO.FT_D2C_AR_TABLE_WEEK FDATW
SET FDATW."Customer Group (eStore/MKP)" = MAC.CUSTOMER_NAME_SUMMARY
	,FDATW.CUSTOMER_NAME = MAC.CUSTOMER_NAME_DETAIL
FROM OW_LAO.FT_D2C_AR_TABLE_WEEK FDATW
LEFT JOIN OW_MD.MAP_AR_MONTH_CUSTOMER MAC
ON--WHERE 
(FDATW.CUSTOMER = MAC.CUSTOMER_CODE);
END