/***********************************************************************************************
CREATE BY : Luciano Mariani
CREATION DATE : 2023-07-28
-- CALL OW_LAO.PROC_D2C_VTEX_O2O_SALES_KPI
-- SELECT TOP 1000 * FROM OW_LAO.FT_D2C_VTEX_O2O_SALES_KPI WHERE O2O_TYPE = 'BOPIS'
***********************************************************************************************/
CREATE PROCEDURE OW_LAO.PROC_D2C_VTEX_O2O_SALES_KPI LANGUAGE SQLSCRIPT
AS
BEGIN
	DROP TABLE OW_LAO.FT_D2C_VTEX_O2O_SALES_KPI;
	CREATE COLUMN TABLE OW_LAO.FT_D2C_VTEX_O2O_SALES_KPI AS (
		SELECT 
			  SUBSIDIARY
			 ,DATE_REF AS ORDER_CREATION_DATE
			 ,STATUS_PO AS ORDER_STATUS
			 ,YYYYWW AS YYYYWW
			 ,YYYYMM AS YYYYMM
			 ,PDROD_DIVISION AS DIMPROD_DIVISION
			 ,PDROD_PRODUCT_GROUP AS DIMPROD_PRODUCT_GROUP
			 ,PDROD_PRODUCT AS DIMPROD_PRODUCT
			 ,SEDA_BU_ESTORE AS DIMPROD_SEDA_BU_ESTORE
			 ,SEDA_CATEGORY_ESTORE AS DIMPROD_SEDA_CATEGORY_ESTORE
			 ,SEDA_DESC_ESTORE AS DIMPROD_SEDA_MKT_DESC_ESTORE
			 ,SEDA_DIVISION_ESTORE AS DIMPROD_SEDA_DIVISION_ESTORE
			 ,SEDA_FAMILY_ESTORE AS DIMPROD_SEDA_FAMILY_ESTORE
			 ,CHANNEL_TYPE AS SALES_CHANNEL
			 ,CASE WHEN O2O_TYPE = 'BOPIS' AND UPPER(SELECTED_SLA) LIKE 'CLIQUE RETIRE%' AND UPPER(ADDRESSTYPE) = 'PICKUP' THEN 'BOPIL' ELSE O2O_TYPE END 
			  AS O2O_TYPE
			 ,SELECTED_SLA 
			 ,REFERENCE_CODE
			 ,PRICE_TO AS PRICE_TO
			 ,AMOUNT_LOCAL + AMOUNT_DISCOUNT - AMOUNT_SHIPPING AS AMOUNT_ITEM
			 ,QTY AS UNITS_QUANTITY
			 ,AMOUNT_LOCAL AS AMOUNT_ORDER
			 ,AMOUNT_DISCOUNT AS AMOUNT_DISCOUNT
			 ,AMOUNT_SHIPPING AS SHIPPING_COST
			 ,AMOUNT_USD AS AMOUNT_ORDER_USD
			 
			 /**************************
			 ,TRIM(SUBSTRING_REGEXPR('[^|]+' IN NAME_STORE FROM 1 OCCURRENCE 1)) AS CHANNEL
			 ,TRIM(SUBSTRING_REGEXPR('[^|]+' IN NAME_STORE FROM 1 OCCURRENCE 2)) AS PARTNER
			 ,TRIM(SUBSTRING_REGEXPR('[^|]+' IN NAME_STORE FROM 1 OCCURRENCE 3)) AS STORE_TYPE
			 --,TRIM(SUBSTRING_REGEXPR('[^|]+' IN NAME_STORE FROM 1 OCCURRENCE 4)) AS STORE_NAME
			 ,CASE
				WHEN O2O_TYPE = 'BOPIS' THEN TRIM(SUBSTRING_REGEXPR( '(CSP[a-zA-Z0-9]+)' IN SELECTED_SLA FROM 1 OCCURRENCE 1))
			  	ELSE TRIM(SUBSTRING_REGEXPR('[^|]+' IN NAME_STORE FROM 1 OCCURRENCE 4)) 
		 	  END AS STORE_NAME
		 	 **************************/
			 	
			 ,CASE WHEN O2O_TYPE = 'BOPIS' THEN
			 	CASE 
				 	WHEN (UPPER(SELECTED_SLA) LIKE 'CLIQUE RETIRE%') AND UPPER(ADDRESSTYPE) = 'PICKUP' THEN 'LOCKER' -- BOPIL
			 		WHEN TRIM(SUBSTRING_REGEXPR( '(CSP[a-zA-Z0-9]+)' IN SELECTED_SLA FROM 1 OCCURRENCE 1)) LIKE 'CSP%' THEN 'CSP'
			 	END
			 ELSE
				TRIM(SUBSTRING_REGEXPR('[^|]+' IN NAME_STORE FROM 1 OCCURRENCE 1))
			END AS CHANNEL
			 
			 ,CASE WHEN O2O_TYPE = 'BOPIS' THEN
			 	CASE 
				 	WHEN (UPPER(SELECTED_SLA) LIKE 'CLIQUE RETIRE%') AND UPPER(ADDRESSTYPE) = 'PICKUP' THEN 'Clique Retire' -- BOPIL
			 		--WHEN TRIM(SUBSTRING_REGEXPR( '(CSP[a-zA-Z0-9]+)' IN SELECTED_SLA FROM 1 OCCURRENCE 1)) LIKE 'CSP%' THEN 'CSP'
			 	END
			 ELSE
				TRIM(SUBSTRING_REGEXPR('[^|]+' IN NAME_STORE FROM 1 OCCURRENCE 2)) 
			END AS PARTNER			 
			 
			 ,TRIM(SUBSTRING_REGEXPR('[^|]+' IN NAME_STORE FROM 1 OCCURRENCE 3)) AS STORE_TYPE
			
			 ,CASE
				WHEN O2O_TYPE = 'BOPIS' THEN
					IFNULL(
						 OW_LAO.REPLACE_TEXT(TRIM(SUBSTRING_REGEXPR( '(CSP[a-zA-Z0-9]+)' IN SELECTED_SLA FROM 1 OCCURRENCE 1)),'CSP','',FALSE)
						,CASE WHEN UPPER(SELECTED_SLA) LIKE 'CLIQUE RETIRE%' THEN FRIENDLYNAME END)
			  	ELSE
					TRIM(SUBSTRING_REGEXPR('[^|]+' IN NAME_STORE FROM 1 OCCURRENCE 4)) 
		 	  END AS STORE_NAME
		 	  
			 ,CURRENT_TIMESTAMP AS KPI_LAST_UPDATE --,KPI_LAST_UPDATE
		FROM OW_LAO.TF_D2C_NERP_SALES NS
		WHERE "SOURCE" = 'PO'
			AND STATUS_PO NOT IN('cancel','canceled')
			AND SUBSIDIARY = 'SEDA'
			-- AND O2O_TYPE IS not null
		ORDER BY
			 SUBSIDIARY
			 ,DATE_REF
	);
	UPDATE OW_LAO.FT_D2C_VTEX_O2O_SALES_KPI SET
		KPI_LAST_UPDATE = (
				SELECT MAX(PO_CREATION_DATE)
				FROM OW_LAO.TF_D2C_NERP_SALES
				WHERE "SOURCE" = 'PO'
					AND SUBSIDIARY = 'SEDA'
			  ) --AS KPI_LAST_UPDATE					
	;
END
