
CREATE PROCEDURE OW_LAO.PROC_D2C_CELLO_NERP_RETURN_PENDING
LANGUAGE SQLSCRIPT as
BEGIN
--Truncate tabela referente as informações de Return Pending
TRUNCATE TABLE OW_LAO.FT_D2C_CELLO_NERP_RETURN_PENDING;
--Cria tabela referente  as informações de Return Pending
INSERT INTO OW_LAO.FT_D2C_CELLO_NERP_RETURN_PENDING
SELECT 	DISTINCT 
	'SEDA' AS SUBSIDIARY 
    ,DP.PRODUCT_GROUP_1 AS DIMPROD_PRODUCT_GROUP
	,DP."DIVISION" AS DIMPROD_DIVISION
	,DP.PRODUCT_1 AS DIMPROD_PRODUCT
	,DC.YYYY AS "YEAR"
	,DC.YYYYQQ AS "QUARTER"
	,DC.YYYYMM AS "YEAR_MONTH"
	,DC.YYYYWW AS "WEEK" 
	,CDII.ITEM_CD AS MATERIAL
	,CDI.DELIVERY_NO
	,CDI.DELIVERY_REF_NO
	--UPPER(RIGHT(CDI.ORDER_TYPE,8)) ANTIGO
	,CASE WHEN UPPER(CDI.ORDER_TYPE) LIKE '%STORE_RTN%' AND UPPER(CDI.SOLDTO_NM) LIKE '%SEDA%'
   		THEN 'Sit'
   	 WHEN UPPER(CDI.ORDER_TYPE) LIKE '%CORREIOS%' AND UPPER(CDI.SOLDTO_NM) LIKE '%SEDA%'
   	 	THEN 'Post'
   	 WHEN UPPER(CDI.ORDER_TYPE) LIKE '%COLLECT%' AND UPPER(CDI.SOLDTO_NM) LIKE '%SEDA%'
   	 	THEN 'Pick-up'
   	 	ELSE NULL 
   	END AS RDO_ORDER_TYPE
   	,CDI.ORDER_TYPE
	,CDI.S_CARRIER_NAME
   	,TO_DOUBLE(CASE WHEN CDII.ITEM_QTY = 'null' THEN NULL ELSE CDII.ITEM_QTY END ) AS RETURN_QTY
    	,TO_DATE(ONZDDTIR.R_DO_CREATED_ON) AS R_DO_CREATED_ON
   	,TO_DATE(LEFT(CDI.RETURN_IOD_DATE,8)) AS RETURN_IOD_DATE
    	,(CASE WHEN LENGTH(CDI.GR_DATE)>14 THEN NULL ELSE TO_DATE(LEFT(CDI.GR_DATE,8)) END) AS GR_DATE
	,TO_DATE(CDI.PICK_UP_DATE) AS PICK_UP_DATE
	,CASE WHEN UPPER(CDI.ORDER_TYPE) LIKE '%COLLECT%' AND UPPER(CDI.SOLDTO_NM) LIKE '%SEDA%' --'Pick-up'
		THEN (CASE WHEN (CASE WHEN LENGTH(CDI.GR_DATE)>14 THEN NULL ELSE TO_DATE(LEFT(CDI.GR_DATE,8)) END) IS NULL 
			THEN 'RGR'
		WHEN TO_DATE(CDI.PICK_UP_DATE) IS NULL 
			THEN 'Pick-up'
		WHEN TO_DATE(LEFT(CDI.RETURN_IOD_DATE,8)) IS NULL
			THEN 'RIOD'
		ELSE NULL		
		END)
	WHEN TO_DATE(LEFT(CDI.RETURN_IOD_DATE,8)) IS NULL
		THEN 'RIOD'
	WHEN (CASE WHEN LENGTH(CDI.GR_DATE)>14 THEN NULL ELSE TO_DATE(LEFT(CDI.GR_DATE,8)) END) IS NULL
		THEN 'RGR'
		ELSE NULL 
	END AS PENDING
	
	, CASE WHEN UPPER(CDI.ORDER_TYPE) LIKE '%COLLECT%' AND UPPER(CDI.SOLDTO_NM) LIKE '%SEDA%' AND (CASE WHEN LENGTH(CDI.GR_DATE)>14 
								THEN NULL ELSE TO_DATE(LEFT(CDI.GR_DATE,8)) END) IS NULL 
		THEN DAYS_BETWEEN(TO_DATE(ONZDDTIR.R_DO_CREATED_ON),CURRENT_DATE)
	WHEN UPPER(CDI.ORDER_TYPE) LIKE '%COLLECT%' AND UPPER(CDI.SOLDTO_NM) LIKE '%SEDA%' AND TO_DATE(CDI.PICK_UP_DATE) IS NULL
		THEN DAYS_BETWEEN((CASE WHEN LENGTH(CDI.GR_DATE)>14 THEN NULL ELSE TO_DATE(LEFT(CDI.GR_DATE,8)) END),CURRENT_DATE)
	WHEN UPPER(CDI.ORDER_TYPE) LIKE '%COLLECT%' AND UPPER(CDI.SOLDTO_NM) LIKE '%SEDA%' AND TO_DATE(LEFT(CDI.RETURN_IOD_DATE,8)) IS NULL
		THEN DAYS_BETWEEN(TO_DATE(CDI.PICK_UP_DATE),CURRENT_DATE)
	WHEN TO_DATE(LEFT(CDI.RETURN_IOD_DATE,8)) IS NULL
		THEN DAYS_BETWEEN(TO_DATE(ONZDDTIR.R_DO_CREATED_ON),CURRENT_DATE)
	WHEN (CASE WHEN LENGTH(CDI.GR_DATE)>14 THEN NULL ELSE TO_DATE(LEFT(CDI.GR_DATE,8)) END) IS NULL
		THEN DAYS_BETWEEN(TO_DATE(LEFT(CDI.RETURN_IOD_DATE,8)),CURRENT_DATE)
	ELSE NULL 
	END AS PENDING_DAYS
	/*
	,CASE WHEN TO_DATE(LEFT(CDI.RETURN_IOD_DATE,8)) IS NULL 
		THEN DAYS_BETWEEN(TO_DATE(ONZDDTIR.R_DO_CREATED_ON),CURRENT_DATE)
		ELSE NULL 
	END AS IOD_PENDING	
	, CASE WHEN (CASE WHEN LENGTH(CDI.GR_DATE)>14 THEN NULL ELSE TO_DATE(LEFT(CDI.GR_DATE,8)) END) IS NULL 
		THEN DAYS_BETWEEN(TO_DATE(LEFT(CDI.RETURN_IOD_DATE,8)),CURRENT_DATE)
		ELSE NULL 
	END AS GR_PENDING
	, CASE WHEN UPPER(CDI.ORDER_TYPE) LIKE '%COLLECT%' AND TO_DATE(CDI.PICK_UP_DATE) IS NULL 
		THEN DAYS_BETWEEN(TO_DATE(ONZDDTIR.R_DO_CREATED_ON),CURRENT_DATE)
		ELSE NULL 
	END AS PICK_UP_PENDING
	, CASE WHEN UPPER(CDI.ORDER_TYPE) LIKE '%COLLECT%' AND TO_DATE(LEFT(CDI.RETURN_IOD_DATE,8)) IS NULL 
		THEN DAYS_BETWEEN(TO_DATE(CDI.PICK_UP_DATE),CURRENT_DATE)
		ELSE NULL 
	END AS PICK_UP_IOD_PENDING
	*/
   	,DP2.ORIGIN AS PLANT
	,ONZDDTIR.RECV_PLANT AS PLANT_DESC
	 
	,CDI.SHIPTO_STATE AS REGION 
	,CDI.SHIPTO_CITY AS CITY
	,null AS LAST_UPDATE
	FROM OW_SEDA_S.CELLO_DELIVERY_INBOUND CDI
	LEFT JOIN OW_SEDA_S.CELLO_DELIVERY_INBOUND_ITEM CDII ON (CDI.DELIVERY_NO = CDII.DELIVERY_NO )
	LEFT JOIN OW_LAO.ODS_NERP_ZLLEE50090_DISPLAY_DO_TRACKING_INFO_RETURN ONZDDTIR ON (CDII.DELIVERY_NO = ONZDDTIR.RETURN_DO_NO
        AND CDII.ITEM_CD = ONZDDTIR.MATERIAL AND TO_INT(CDII.ITEM_NO) = TO_INT(TO_DOUBLE(ONZDDTIR.R_DO_ITEM)))
	LEFT JOIN OW_MD.DIM_CALENDAR DC ON (DC.YYYYMMDD = TO_DATE(ONZDDTIR.R_DO_CREATED_ON))
	LEFT JOIN OW_MD.DIM_PRODUCT DP ON (CDII.ITEM_CD = DP.SKU) 	
	LEFT JOIN OW_MD.DIM_PLANT DP2 ON (CDI.PLANT_CD = DP2.PLANT_CODE)
	WHERE TO_DOUBLE(ONZDDTIR.R_D_CH_) IN (30,31)
	AND (CASE WHEN UPPER(CDI.ORDER_TYPE) LIKE '%COLLECT%'  AND UPPER(CDI.SOLDTO_NM) LIKE '%SEDA%'--'Pick-up'
		THEN (CASE WHEN (CASE WHEN LENGTH(CDI.GR_DATE)>14 THEN NULL ELSE TO_DATE(LEFT(CDI.GR_DATE,8)) END) IS NULL 
			THEN 'RGR'
		WHEN TO_DATE(CDI.PICK_UP_DATE) IS NULL 
			THEN 'Pick-up'
		WHEN TO_DATE(LEFT(CDI.RETURN_IOD_DATE,8)) IS NULL
			THEN 'RIOD'
		ELSE NULL		
		END)
	WHEN TO_DATE(LEFT(CDI.RETURN_IOD_DATE,8)) IS NULL
		THEN 'RIOD'
	WHEN (CASE WHEN LENGTH(CDI.GR_DATE)>14 THEN NULL ELSE TO_DATE(LEFT(CDI.GR_DATE,8)) END) IS NULL
		THEN 'RGR'
		ELSE NULL 
	END) IS NOT NULL
	;
-- Update para Setar o horário de carga. Obs.: Estou fazendo aqui para não ter probemas com milisegundos
UPDATE OW_LAO.FT_D2C_CELLO_NERP_RETURN_PENDING
	SET LAST_UPDATE = NOW()
	WHERE LAST_UPDATE IS NULL;
END