CREATE PROCEDURE OW_LAO.PROC_D2C_FT_STOCKOUT
LANGUAGE SQLSCRIPT as
BEGIN 
--D2C_FT_STOCKOUT
TRUNCATE TABLE OW_LAO.FT_STOCKOUT;
INSERT INTO "OW_LAO"."FT_STOCKOUT" 
(
--STOCK OUT--
SELECT 
STOCK.SUBSIDIARY,STOCK.DIVISION,STOCK.OBSERVATION_DATE ,STOCK.STOCK_OUT_REASON ,STOCK.CATEGORY
,STOCK.STATUS , CALENDAR.YYYY, CALENDAR.YYYYMM, CALENDAR.YYYYWW
,dp."DIVISION" AS DIMPROD_DIVISION ,dp."PRODUCT_GROUP_1" AS DIMPROD_PROD_GROUP ,SUM(STOCK.INSTOCK) AS INSTOCK, SUM(STOCK.OUTOFSTOCK) AS OUTOFSTOCK,STOCK.SKU
,CURRENT_TIMESTAMP AS PROCESS_DATE, STOCK.LAST_RPA_DATE
FROM (
--QUANTIDADE SKUs INSTOCK--
select SKU,SUBSIDIARY,DIVISION,OBSERVATION_DATE ,STOCK_OUT_REASON ,CATEGORY,STATUS, RPA_DATE as LAST_RPA_DATE 
,   count(DISTINCT SKU) as "INSTOCK", 0 as "OUTOFSTOCK"
from OW_LAO.ODS_GLOBAL_BI_STOCKOUT
where STATUS = 'InStock'
AND 
  RPA_DATE  IN (
    SELECT   MAX(RPA_DATE)
    FROM     OW_LAO.ODS_GLOBAL_BI_STOCKOUT
    GROUP BY MONTH(RPA_DATE), YEAR(RPA_DATE)
  ) 
group by 
 SKU,SUBSIDIARY,DIVISION,OBSERVATION_DATE ,STOCK_OUT_REASON ,CATEGORY,STATUS, RPA_DATE 
union all
--QUANTIDADE SKUs OUTOFSTOCK--
select  SKU,SUBSIDIARY,DIVISION,OBSERVATION_DATE ,STOCK_OUT_REASON ,CATEGORY,STATUS, RPA_DATE as LAST_RPA_DATE 
, 0 as "INSTOCK", count(DISTINCT SKU) as "OUTOFSTOCK"
from OW_LAO.ODS_GLOBAL_BI_STOCKOUT
where STATUS = 'OutOfStock'
AND 
  RPA_DATE  IN (
    SELECT   MAX(RPA_DATE)
    FROM     OW_LAO.ODS_GLOBAL_BI_STOCKOUT
    GROUP BY MONTH(RPA_DATE), YEAR(RPA_DATE)
  ) 
group by 
  SKU,SUBSIDIARY,DIVISION,OBSERVATION_DATE ,STOCK_OUT_REASON ,CATEGORY,STATUS, RPA_DATE 
) STOCK
LEFT JOIN OW_MD.DIM_CALENDAR CALENDAR on OBSERVATION_DATE=CALENDAR.YYYYMMDD --LEFT JOIN DIM CALENDAR 
LEFT JOIN OW_MD.DIM_PRODUCT dp  ON STOCK.SKU= dp.SKU --LEFT JOIN HIERARQUIA
GROUP BY STOCK.SUBSIDIARY,STOCK.DIVISION,STOCK.OBSERVATION_DATE ,STOCK.STOCK_OUT_REASON ,STOCK.CATEGORY
,STOCK.STATUS, STOCK.LAST_RPA_DATE ,CALENDAR.YYYY, CALENDAR.YYYYMM, CALENDAR.YYYYWW,STOCK.SKU
,dp."DIVISION" ,dp."PRODUCT_GROUP_1"
)
;
END