CREATE PROCEDURE OW_LAO.PROC_LAO_SALES_DEDUCTION_6W_10W
LANGUAGE SQLSCRIPT as
BEGIN
-- Truncate table OW_LAO.TF_LAO_SALES_DEDUCTION_6W_10W_GSCM
TRUNCATE TABLE OW_LAO.TF_LAO_SALES_DEDUCTION_6W_10W_GSCM;
--CREATE TABLE OW_LAO.TF_LAO_SALES_DEDUCTION_6W_10W_GSCM AS (
INSERT INTO OW_LAO.TF_LAO_SALES_DEDUCTION_6W_10W_GSCM
SELECT 
	GSCM.AP2
	,GSCM.AP1
	,GSCM.CHANNEL
	,GSCM.ITEM
	,REPLACE(TO_CHAR(GSCM.DATE_FORMAT), '-', '.') AS "SALES_DATE"
	,GSCM."VALUE"
	,GSCM."SOURCE"
	,GSCM.PRODUCT_GRP
	,GSCM.PRODUCT
	,(CASE WHEN GSCM.PRODUCT_GRP ='MOBILE' AND GSCM.PRODUCT ='HHP' 
			THEN 'SMART' 
	WHEN GSCM.PRODUCT_GRP ='MOBILE' AND GSCM.PRODUCT ='TABLET' 
			THEN 'TABLET'
			ELSE GSCM.PRODUCT_GRP 
	END ) AS TF_GSCM_PRODUCT_GRP
	,(CASE WHEN GSCM.AP2 = 'SELA-P' 
		THEN GSCM.AP1
		ELSE '1'
	END) AS TF_GSCM_AP1	
FROM OW_LAO.ODS_GSCM_CH_PSI_WARNING_SALES_DEDUCTION_DAILY_6W_10W GSCM
	WHERE GSCM.DATE_FORMAT IS NOT NULL 
--)
;
	
-- Truncate table OW_LAO.TF_LAO_SALES_DEDUCTION_DAILY_BIZ_AREA
TRUNCATE TABLE OW_LAO.TF_LAO_SALES_DEDUCTION_DAILY_BIZ_AREA;
--CREATE TABLE OW_LAO.TF_LAO_SALES_DEDUCTION_DAILY_BIZ_AREA AS (
INSERT INTO OW_LAO.TF_LAO_SALES_DEDUCTION_DAILY_BIZ_AREA
SELECT 	BIZ_AREA.COMPANY_CODE AS COMPANY_CODE
	,BIZ_AREA.COMPANY_CODE_NAME
	,BIZ_AREA.AP1
	,BIZ_AREA.BUSINESS_AREA
	,(CASE WHEN BIZ_AREA.COMPANY_CODE_NAME = 'SELA-P' 
		THEN BIZ_AREA.AP1
		ELSE '1'
	END) AS TF_BIZ_AREA_COMPANY_CODE
	
FROM "OW_LAO"."INPUT_MAPPING_BIZ_AREA_SALES_DEDUCTION" BIZ_AREA
WHERE BIZ_AREA.BUSINESS_AREA <> '850C'
--)	
;
-- Truncate table OW_LAO.TF_LAO_SALES_DEDUCTION_DAILY_CORES
TRUNCATE TABLE OW_LAO.TF_LAO_SALES_DEDUCTION_DAILY_CORES;
--CREATE TABLE OW_LAO.TF_LAO_SALES_DEDUCTION_DAILY_CORES AS (
INSERT INTO OW_LAO.TF_LAO_SALES_DEDUCTION_DAILY_CORES
SELECT 	CORES.AP2
	,CORES.AP1
	,CORES.CUSTOMER_CODE AS CHANNEL_CODE
	,CORES.SOLD_TO_PARTY AS "SOLD_TO"
	,CORES.PROD_GROUP 
	,CORES."LEVEL"
	,CORES.CHANNEL
	,CORES.PARENT_CHANNEL
	,CORES."SOURCE"
	,(CASE WHEN CORES.AP2 = 'SELA-P' 
		THEN CORES.AP1
		ELSE '1'
	END) AS TF_CORES_AP1
FROM "OW_LAO"."INPUT_MAP_CORES_SALES_DEDUCTION" CORES
--)	
;
-- Truncate table OW_LAO.FT_LAO_SALES_DEDUCTION_DAILY
TRUNCATE TABLE OW_LAO.FT_LAO_SALES_DEDUCTION_DAILY_6W_10W;
--CREATE TABLE OW_LAO.FT_LAO_SALES_DEDUCTION_DAILY AS (
INSERT INTO OW_LAO.FT_LAO_SALES_DEDUCTION_DAILY_6W_10W
SELECT 
	BIZ_AREA.COMPANY_CODE
	,BIZ_AREA.BUSINESS_AREA
	,GSCM.ITEM
	,GSCM.SALES_DATE
	,DC.YYYYWW AS "YEAR_WEEK"
	,(CASE WHEN CORES."LEVEL" ='2' THEN 'SAMSUNG' ELSE CORES.PARENT_CHANNEL END) AS "CHANNEL_CODE_FROM"
	,CORES.CHANNEL_CODE
	,'CONSUMER' AS CHANNEL_CODE_TO
	,'SO' AS SELL_OUT_FLAG
	,CORES.SOLD_TO
	,GSCM."VALUE"
	,(CASE WHEN CORES.PROD_GROUP <> 'ALL' AND GSCM.AP2 <> 'SELA-P' AND CORES."LEVEL" ='3'
		THEN 'LVL 3, != ALL, NOT SELA'
	WHEN CORES.PROD_GROUP <> 'ALL' AND GSCM.AP2 <> 'SELA-P' AND CORES."LEVEL" ='2'
		THEN 'LVL 2, != ALL, NOT SELA'
	WHEN CORES.PROD_GROUP <> 'ALL' AND GSCM.AP2 = 'SELA-P' AND CORES."LEVEL" ='3'
		THEN 'LVL 3, != ALL, IN SELA'
	WHEN CORES.PROD_GROUP <> 'ALL' AND GSCM.AP2 = 'SELA-P' AND CORES."LEVEL" ='2'
		THEN 'LVL 2, != ALL, IN SELA'
	WHEN CORES.PROD_GROUP = 'ALL' AND GSCM.AP2 <> 'SELA-P' AND CORES."LEVEL" ='3'
		THEN 'LVL 3, = ALL, NOT SELA'
	WHEN CORES.PROD_GROUP = 'ALL' AND GSCM.AP2 <> 'SELA-P' AND CORES."LEVEL" ='2'
		THEN 'LVL 2, = ALL, NOT SELA'
	WHEN CORES.PROD_GROUP = 'ALL' AND GSCM.AP2 = 'SELA-P' AND CORES."LEVEL" ='3'
		THEN 'LVL 3, = ALL, IN SELA'
	WHEN CORES.PROD_GROUP = 'ALL' AND GSCM.AP2 = 'SELA-P' AND CORES."LEVEL" ='2'
		THEN 'LVL 2, = ALL, IN SELA'
		ELSE NULL
	END) AS MAPPED
	,GSCM."SOURCE"
	,CORES.PROD_GROUP
	,CORES."LEVEL" 
	,GSCM.AP2
FROM OW_LAO.TF_LAO_SALES_DEDUCTION_6W_10W_GSCM GSCM 
LEFT JOIN OW_LAO.TF_LAO_SALES_DEDUCTION_DAILY_BIZ_AREA BIZ_AREA ON (GSCM.AP2 = BIZ_AREA.COMPANY_CODE_NAME
								AND GSCM.TF_GSCM_AP1 = BIZ_AREA.TF_BIZ_AREA_COMPANY_CODE )
LEFT JOIN OW_LAO.TF_LAO_SALES_DEDUCTION_DAILY_CORES CORES ON (GSCM.AP2 = CORES.AP2
							  AND GSCM.CHANNEL = CORES.CHANNEL
							  AND GSCM."SOURCE" = CORES."SOURCE"
							  AND GSCM.TF_GSCM_AP1 = CORES.TF_CORES_AP1
							  AND TF_GSCM_PRODUCT_GRP = (CASE WHEN CORES.PROD_GROUP = 'ALL'
							  					THEN TF_GSCM_PRODUCT_GRP
							  					ELSE CORES.PROD_GROUP
							  			    END)
							     )
LEFT JOIN OW_MD.DIM_CALENDAR DC ON (GSCM.SALES_DATE = DC.YYYYMMDD)
WHERE CORES."SOURCE" IS NOT NULL
--)
;
END