CREATE PROCEDURE OW_LAO.PROC_LAO_ODS_GLOBAL_BI_TRAFFIC_DA
LANGUAGE SQLSCRIPT AS
BEGIN
	INSERT INTO "OW_LAO"."ODS_GLOBAL_BI_TRAFFIC_DA" (
	SELECT
	REGION,
SUBSIDIARY,
COUNTRY,
YEAR,
MONTH,
WEEK,
DAY,
CHANNEL_GROUP_1,
CHANNEL_GROUP_2,
"COM_Visit",
SHOPPER_VISIT,
ADD_TO_CART_CURRENT,
CART_PAGE_VISIT_CURRENT,
CHECKOUT_PAGE_CURRENT,
GROSS_ORDER,
NET_ORDERS_CURRENT,
NET_REVENUE,
GROSS_ORDER_CVR,
FILE_NAME,
LOAD_DATE,
RPA_DATE,
DT_CREATION
	  FROM  "OW_LAO"."TF_GLOBAL_BI_TRAFFIC_DA"  tmp
	 WHERE  1=1
	 AND tmp.DAY  NOT IN (SELECT DISTINCT DAY FROM  "OW_LAO"."ODS_GLOBAL_BI_TRAFFIC_DA" A
    WHERE 
    A.DAY = tmp.day 
AND A.SUBSIDIARY = tmp.SUBSIDIARY 
AND  A.COUNTRY = tmp.COUNTRY 
AND  A.YEAR = tmp.YEAR
AND A.MONTH = tmp.MONTH)
    
)
;
	COMMIT;
END;