CREATE PROCEDURE OW_LAO.PROC_INSERT_SALES_CANCELLED_FROM_ODS 
AS 
BEGIN
	
	TRUNCATE TABLE OW_LAO.ODS_EQUALS_SALES_CANCELLED;
	
	INSERT INTO OW_LAO.ODS_EQUALS_SALES_CANCELLED (
"TIPO_CANCELAMENTO" ,
"ID_UNICO_ERP" ,
"ID_UNICO_EQUALS" ,
"ESTABELECIMENTO" ,
"CATEGORIA" ,
"ADQUIRENTE" ,
"BANDEIRA" ,
"TIPO" ,
"PRODUTO" ,
"LOCALIZADOR" ,
"NR_TERMINAL" ,
"LOTE" ,
"LOTE_UNICO" ,
"NR_SEQUENCIA" ,
"NR_REFERENCIA_PEDIDO" ,
"DATA_CAPTURA"  ,
"DATA_VENDA"  ,
"DATA_CANCELAMENTO" ,
"NUMERO_CARTAO" ,
"NSU" ,
"TID" ,
"ORDER_ID" ,
"SEQUENCE" ,
"PARCELA" ,
"QTD_CANCELAMENTO" ,
"VALOR_BRUTO" ,
"VALOR_COMISSAO" ,
"VALOR_LIQUIDO" ,
"VALOR_BRUTO_CANCELAMENTO" ,
"VALOR_LIQUIDO_CANCELAMENTO" ,
"DATA_CONCILIACAO" ,
"MOTIVO_CANCELAMENTO" ,
"ID_UNICO_AJUSTE" 
	)
	
WITH VTEX AS (
SELECT DISTINCT '' TID , ORDER_ID , SEQUENCE FROM OW_LAO.TF_D2C_NERP_SALES
UNION
SELECT DISTINCT TID ,ORDER_ID , SEQUENCE FROM OW_LAO.TF_D2C_PAYMENT_ITAU 
)	
    SELECT DISTINCT
        A.TIPOCANCELAMENTO AS TIPO_CANCELAMENTO,
        A.IDUNICOERP AS ID_UNICO_ERP,
        A.IDUNICOEQUALS AS ID_UNICO_EQUALS,
        A.ESTABELECIMENTO,
        A.CATEGORIADOESTABELECIMENTO AS CATEGORIA,
        A.ADQUIRENTE,
        A.BANDEIRA,
        A.TIPOPRODUTO AS TIPO,
        A.PRODUTO,
        A.LOCALIZADOR,
        A.NRTERMINAL AS NR_TERMINAL,
        A.LOTE,
        A.LOTEUNICO AS LOTE_UNICO,
        A.NRSEQUENCIA AS NR_SEQUENCIA,
        A.NRREFERENCIAPEDIDO AS NR_REFERENCIA_PEDIDO,
        /*TO_VARCHAR(*/TO_DATE(A.DATACAPTURA, 'YYYY-MM-DD')/*, 'DD-MM-YYYY')*/      AS DATA_CAPTURA,
        /*TO_VARCHAR(*/TO_DATE(A.DATAVENDA, 'YYYY-MM-DD')/*, 'DD-MM-YYYY')*/        AS DATA_VENDA,
        /*TO_VARCHAR(*/TO_DATE(A.DATACANCELAMENTO, 'YYYY-MM-DD')/*, 'DD-MM-YYYY')*/ AS DATA_CANCELAMENTO,
        A.NUMEROCARTAO AS NUMERO_CARTAO,
        A.NSU,
        A.TID,
        COALESCE(B.ORDER_ID,C.ORDER_ID,D.ORDER_ID) ORDER_ID,
        COALESCE(B.SEQUENCE,C.SEQUENCE,D.SEQUENCE) SEQUENCE,
        A.PARCELA,
        /*A.QTDCANCELAMENTO*/'1' AS QTD_CANCELAMENTO,
        REPLACE(REPLACE(TO_DECIMAL(A.VALORBRUTO, 10,2),',',''),'.',',')  AS VALOR_BRUTO,
        REPLACE(REPLACE(TO_DECIMAL(A.VALORCOMISSAO, 10,2),',',''),'.',',') AS VALOR_COMISSAO,
        REPLACE(REPLACE(TO_DECIMAL(A.VALORLIQUIDO, 10,2),',',''),'.',',') AS VALOR_LIQUIDO,
       
        --CASE WHEN A.TIPOCANCELAMENTO='Estorno de Chargeback' THEN REPLACE(REPLACE(TO_DECIMAL(A.VALORBRUTOCANCELAMENTO, 10,2),',',''),'.',',')
        --     ELSE '-'||REPLACE(REPLACE(TO_DECIMAL(A.VALORBRUTOCANCELAMENTO, 10,2),',',''),'.',',') END AS VALOR_BRUTO_CANCELAMENTO,
        REPLACE(REPLACE(TO_DECIMAL(A.VALORBRUTOCANCELAMENTO, 10,2),',',''),'.',',')   VALOR_BRUTO_CANCELAMENTO,     
             
        --CASE WHEN A.TIPOCANCELAMENTO='Estorno de Chargeback' THEN REPLACE(REPLACE(TO_DECIMAL(A.VALORLIQUIDOCANCELAMENTO, 10,2),',',''),'.',',')
        --     ELSE '-'||REPLACE(REPLACE(TO_DECIMAL(A.VALORLIQUIDOCANCELAMENTO, 10,2),',',''),'.',',') END AS VALOR_LIQUIDO_CANCELAMENTO,
        REPLACE(REPLACE(TO_DECIMAL(A.VALORLIQUIDOCANCELAMENTO, 10,2),',',''),'.',',')  AS VALOR_LIQUIDO_CANCELAMENTO,
             /*TO_VARCHAR(*/TO_DATE(A.DATACONCILIACAO, 'YYYY-MM-DD')/*, 'DD-MM-YYYY')*/  AS DATA_CONCILIACAO,
        A.MOTIVOCANCELAMENTO   AS MOTIVO_CANCELAMENTO,
        A.IDVENDAAJUSTADA      AS ID_UNICO_AJUSTE
        FROM OW_LAO."TMP_EQUALS_SALES_CANCELLED" A LEFT JOIN VTEX B ON A.NRREFERENCIAPEDIDO = B.SEQUENCE
                                                   LEFT JOIN VTEX C ON A.IDUNICOERP = C.ORDER_ID
                                                   LEFT JOIN VTEX D ON A.TID = D.TID
        WHERE UPPER(A.ADQUIRENTE) IN ('NUPAY','MERCADO PAGO','REDE') ; 
END;