CREATE PROCEDURE OW_LAO.PROC_ODS_HYBRIS_COMBO
 LANGUAGE SQLSCRIPT AS
 BEGIN
	 INSERT INTO  OW_LAO.RAW_HYBRIS_COMBO
	 
	(
	SELECT
A.COUNTRY_CD,
A.ORDER_ID,
A.PRODUCT_NAME,
A.REFERENCE_CODE,
A.PRODUCT_CODE,
A.FILE_NAME,
A.FILE_HYBRIS_DATE,
CURRENT_TIMESTAMP INSERTED_DATE,
CURRENT_TIMESTAMP UPDATED_DATETIME
FROM OW_LAO.TMP_ODS_HYBRIS_COMBO A
WHERE NOT EXISTS (
     SELECT 1
                            FROM OW_LAO.RAW_HYBRIS_COMBO AA
                           WHERE AA.COUNTRY_CD         = A.COUNTRY_CD
                             AND AA.ORDER_ID           = A.ORDER_ID
                             AND AA.REFERENCE_CODE     = A.REFERENCE_CODE
                             AND AA.PRODUCT_CODE       = A.PRODUCT_CODE
                             AND AA.FILE_NAME          = A.FILE_NAME                             
)
)	 
;	 
	 INSERT INTO   OW_LAO.ODS_HYBRIS_COMBO
	 
	(
	SELECT 
	COUNTRY_CD ,
	SUBSIDIARY_ID,
    SUBSIDIARY, 
    ORDER_CODE ,
    ORDER_CREATION_DATE ,
    PRODUCT_CODE ,
    PRODUCT_NAME ,
    REFERENCE_CODE ,
    FILE_NAME_HYBRIS_COMBO ,
    FILE_HYBRIS_DATE_COMBO  ,
    INSERTED_DATE  ,
    UPDATED_DATETIME
	
	FROM (
SELECT DISTINCT 
ROW_NUMBER() OVER (PARTITION BY A.PRODUCT_CODE, LEFT (A.ORDER_CODE,17) 
ORDER BY CAST (A.ORDER_CREATION_DATE AS DATE) DESC ) AS ROW_NUM,
A.COUNTRY_CD,
C.ID     AS SUBSIDIARY_ID,
C.SUBSIDIARY,                                               
LEFT (A.ORDER_CODE,17) AS ORDER_CODE ,
CAST (A.ORDER_CREATION_DATE AS DATE) AS ORDER_CREATION_DATE,
A.PRODUCT_CODE,
B.PRODUCT_NAME,
B.REFERENCE_CODE,
B.FILE_NAME AS FILE_NAME_HYBRIS_COMBO,
B.FILE_HYBRIS_DATE AS FILE_HYBRIS_DATE_COMBO,
B.INSERTED_DATE,
B.UPDATED_DATETIME
FROM OW_LAO.ODS_HYBRIS_SALES  A
JOIN OW_LAO.RAW_HYBRIS_COMBO  B          ON LEFT (A.ORDER_CODE,17)   = LEFT (B.ORDER_ID,17) 
                                        AND A.PRODUCT_CODE           = B.PRODUCT_CODE 
                                        AND A.COUNTRY_CD             = B.COUNTRY_CD
LEFT JOIN U_PRJ_ECOM.DIM_SUBSIDIARY  C  ON LOWER(C.COUNTRY_CODE) =  LOWER(A.COUNTRY_CD)
) A  
 
WHERE NOT EXISTS (
     SELECT 1
                            FROM OW_LAO.ODS_HYBRIS_COMBO AA
                           WHERE AA.COUNTRY_CD         = A.COUNTRY_CD
                             AND AA.ORDER_CODE         = A.ORDER_CODE
                             AND AA.PRODUCT_CODE       = A.PRODUCT_CODE
                          
                          
)
AND ROW_NUM = 1
--AND  ORDER_CODE = 'CL240929-28885933'
)	 
;	 
END