CREATE PROCEDURE OW_LAO.PROC_NERP_ZLLEJ50090_OUTBOUND_TRACKING
 LANGUAGE SQLSCRIPT AS
 BEGIN
	DECLARE CLASSIFICATION_FILE VARCHAR(25);
	
	SELECT DISTINCT 
		(CASE WHEN FILE_NAME LIKE'%SELA%'
					THEN 'SELA'
		  WHEN FILE_NAME NOT LIKE'%SELA%' AND FILE_NAME NOT LIKE '%SEDA_OUTLET%' AND FILE_NAME LIKE '%SEDAD2CVISIB%'
		  			THEN 'SEDAD2CVISIB'
		  WHEN FILE_NAME NOT LIKE'%SELA%' AND FILE_NAME NOT LIKE '%SEDAD2CVISIB%' AND FILE_NAME LIKE '%SEDA_OUTLET%'
		  			THEN 'SEDA_OUTLET'
		  WHEN FILE_NAME NOT LIKE'%SELA%' AND FILE_NAME NOT LIKE '%SEDAD2CVISIB%' AND FILE_NAME NOT LIKE '%SEDA_OUTLET%'
		  			THEN 'OTHERS'
		  END)  INTO CLASSIFICATION_FILE
	FROM OW_LAO.TMP_NERP_ZLLEJ50090_OUTBOUND_TRACKING; 
				
	--Inserir dados no RAW_DATA a partir da tabela TMP
		--Delete dados da tabela RAW_DATA que tenham o mesmo FILE_NAME que o da tabela TMP 
	 DELETE FROM OW_LAO.RAW_DATA_NERP_ZLLEJ50090_OUTBOUND_TRACKING RD
	 WHERE RD.FILE_NAME = (SELECT DISTINCT FILE_NAME FROM OW_LAO.TMP_NERP_ZLLEJ50090_OUTBOUND_TRACKING);
	--Inserir dados na tabela de SALES DEDUCTION
	INSERT INTO OW_LAO.RAW_DATA_NERP_ZLLEJ50090_OUTBOUND_TRACKING
	SELECT * FROM OW_LAO.TMP_NERP_ZLLEJ50090_OUTBOUND_TRACKING;
	
		IF CLASSIFICATION_FILE = 'SELA' THEN 
			
			--SELECT 'VALUE IS SELA' AS RETORNO FROM DUMMY;
		
			DELETE FROM OW_LAO.ODS_NERP_ZLLEJ50090_OUTBOUND_TRACKING 
			WHERE FILE_NAME LIKE'%SELA%'
			AND DOCUMENT_DATE_LOCAL BETWEEN 
				(SELECT MIN(DOCUMENT_DATE_LOCAL) FROM OW_LAO.TMP_NERP_ZLLEJ50090_OUTBOUND_TRACKING WHERE FILE_NAME LIKE'%SELA%')
            AND (SELECT MAX(DOCUMENT_DATE_LOCAL) FROM OW_LAO.TMP_NERP_ZLLEJ50090_OUTBOUND_TRACKING WHERE FILE_NAME LIKE'%SELA%')
			;
		
			INSERT INTO OW_LAO.ODS_NERP_ZLLEJ50090_OUTBOUND_TRACKING 
			SELECT DISTINCT *
			FROM
				(
				SELECT
					MATERIAL || '||' || DELIVERY_ITEM || '||' || DELIVERY_NO AS ID
					, *
				FROM "OW_LAO"."TMP_NERP_ZLLEJ50090_OUTBOUND_TRACKING"
				)
			ORDER BY MATERIAL, DELIVERY_ITEM, DELIVERY_NO
			;
		
		ELSE IF CLASSIFICATION_FILE = 'SEDAD2CVISIB' THEN 
			
			--SELECT 'VALUE IS SEDAD2CVISIB' AS RETORNO FROM	DUMMY;
			
			DELETE FROM OW_LAO.ODS_NERP_ZLLEJ50090_OUTBOUND_TRACKING 
			WHERE FILE_NAME NOT LIKE'%SELA%' AND FILE_NAME NOT LIKE '%SEDA_OUTLET%' AND FILE_NAME LIKE '%SEDAD2CVISIB%'
			AND DOCUMENT_DATE_LOCAL BETWEEN 
				(SELECT MIN(DOCUMENT_DATE_LOCAL) FROM OW_LAO.TMP_NERP_ZLLEJ50090_OUTBOUND_TRACKING WHERE FILE_NAME NOT LIKE'%SELA%' AND FILE_NAME NOT LIKE '%SEDA_OUTLET%' AND FILE_NAME LIKE '%SEDAD2CVISIB%')
            AND (SELECT MAX(DOCUMENT_DATE_LOCAL) FROM OW_LAO.TMP_NERP_ZLLEJ50090_OUTBOUND_TRACKING WHERE FILE_NAME NOT LIKE'%SELA%' AND FILE_NAME NOT LIKE '%SEDA_OUTLET%' AND FILE_NAME LIKE '%SEDAD2CVISIB%')
			;
		
			INSERT INTO OW_LAO.ODS_NERP_ZLLEJ50090_OUTBOUND_TRACKING 
			SELECT DISTINCT *
			FROM
				(
				SELECT
					MATERIAL || '||' || DELIVERY_ITEM || '||' || DELIVERY_NO AS ID
					, *
				FROM "OW_LAO"."TMP_NERP_ZLLEJ50090_OUTBOUND_TRACKING"
				)
			ORDER BY MATERIAL, DELIVERY_ITEM, DELIVERY_NO
			;
		
		ELSE IF CLASSIFICATION_FILE = 'SEDA_OUTLET' THEN 
			
			--SELECT 'VALUE IS SEDA_OUTLET' AS RETORNO FROM DUMMY;
		
			DELETE FROM OW_LAO.ODS_NERP_ZLLEJ50090_OUTBOUND_TRACKING 
			WHERE FILE_NAME NOT LIKE'%SELA%' AND FILE_NAME NOT LIKE '%SEDAD2CVISIB%' AND FILE_NAME LIKE '%SEDA_OUTLET%'
			AND DOCUMENT_DATE_LOCAL BETWEEN 
				(SELECT MIN(DOCUMENT_DATE_LOCAL) FROM OW_LAO.TMP_NERP_ZLLEJ50090_OUTBOUND_TRACKING WHERE FILE_NAME NOT LIKE'%SELA%' AND FILE_NAME NOT LIKE '%SEDAD2CVISIB%' AND FILE_NAME LIKE '%SEDA_OUTLET%')
            AND (SELECT MAX(DOCUMENT_DATE_LOCAL) FROM OW_LAO.TMP_NERP_ZLLEJ50090_OUTBOUND_TRACKING WHERE FILE_NAME NOT LIKE'%SELA%' AND FILE_NAME NOT LIKE '%SEDAD2CVISIB%' AND FILE_NAME LIKE '%SEDA_OUTLET%')
			;
		
			INSERT INTO OW_LAO.ODS_NERP_ZLLEJ50090_OUTBOUND_TRACKING 
			SELECT DISTINCT *
			FROM
				(
				SELECT
					MATERIAL || '||' || DELIVERY_ITEM || '||' || DELIVERY_NO AS ID
					, *
				FROM "OW_LAO"."TMP_NERP_ZLLEJ50090_OUTBOUND_TRACKING"
				)
			ORDER BY MATERIAL, DELIVERY_ITEM, DELIVERY_NO
			;
			
		ELSE IF CLASSIFICATION_FILE = 'OTHERS' THEN 
			
			--SELECT 'VALUE IS OTHERS' AS RETORNO FROM DUMMY;
		
			DELETE FROM OW_LAO.ODS_NERP_ZLLEJ50090_OUTBOUND_TRACKING 
			WHERE FILE_NAME NOT LIKE'%SELA%' AND FILE_NAME NOT LIKE '%SEDAD2CVISIB%' AND FILE_NAME NOT LIKE '%SEDA_OUTLET%'
			AND DOCUMENT_DATE_LOCAL BETWEEN 
				(SELECT MIN(DOCUMENT_DATE_LOCAL) FROM OW_LAO.TMP_NERP_ZLLEJ50090_OUTBOUND_TRACKING WHERE FILE_NAME NOT LIKE'%SELA%' AND FILE_NAME NOT LIKE '%SEDAD2CVISIB%' AND FILE_NAME NOT LIKE '%SEDA_OUTLET%')
            AND (SELECT MAX(DOCUMENT_DATE_LOCAL) FROM OW_LAO.TMP_NERP_ZLLEJ50090_OUTBOUND_TRACKING WHERE FILE_NAME NOT LIKE'%SELA%' AND FILE_NAME NOT LIKE '%SEDAD2CVISIB%' AND FILE_NAME NOT LIKE '%SEDA_OUTLET%')
			;
		
			INSERT INTO OW_LAO.ODS_NERP_ZLLEJ50090_OUTBOUND_TRACKING 
			SELECT DISTINCT *
			FROM
				(
				SELECT
					MATERIAL || '||' || DELIVERY_ITEM || '||' || DELIVERY_NO AS ID
					, *
				FROM "OW_LAO"."TMP_NERP_ZLLEJ50090_OUTBOUND_TRACKING"
				)
			ORDER BY MATERIAL, DELIVERY_ITEM, DELIVERY_NO
			;
				
		END IF;
		END IF;
		END IF;
	END IF;
END;
