--------------------------------------PROCs
------TRAFIC_ALL
------------------PROC_LAO_TF_GLOBAL_BI_TRAFFIC_ALL
CREATE PROCEDURE OW_LAO.PROC_LAO_TF_GLOBAL_BI_TRAFFIC_ALL
LANGUAGE SQLSCRIPT AS
   BEGIN
SELECT  DISTINCT 
A.REGION,
A.SUBSIDIARY,
A.COUNTRY,
A.YEAR,
A.MONTH,
A.WEEK,
A.DAY,
A.CHANNEL_GROUP_1,
A.CHANNEL_GROUP_2,
A.FILE_NAME,
A.RPA_DATE,
MAX(CASE WHEN B.ROW_NUM = 1 THEN A.MEASURE_VALUES   ELSE NULL  END)  AS "COM_Visit",
MAX(CASE WHEN B.ROW_NUM IN (13,12,11,8) THEN A.MEASURE_VALUES   ELSE NULL  END)  AS "Shopper_Visit_Current1" ,  
MAX(CASE WHEN B.ROW_NUM IN (2,19) THEN A.MEASURE_VALUES   ELSE NULL  END)  AS "Add_to_Cart_Current",	
MAX(CASE WHEN B.ROW_NUM IN (3,18) THEN A.MEASURE_VALUES   ELSE NULL  END)  AS "Cart_Page_Visit_Current	",
MAX(CASE WHEN B.ROW_NUM IN (4,17) THEN A.MEASURE_VALUES   ELSE NULL  END)  AS "Checkout_Page_Current",
MAX(CASE WHEN B.ROW_NUM IN (16,10,5,22) THEN ROUND(A.MEASURE_VALUES,0)   ELSE NULL  END)  AS "Gross_Order_Current",
MAX(CASE WHEN B.ROW_NUM IN (15,6,20) THEN ROUND(A.MEASURE_VALUES,0)   ELSE NULL  END)  AS "Net_Orders_Current",
MAX(CASE WHEN B.ROW_NUM IN (14,9,7) THEN A.MEASURE_VALUES   ELSE NULL  END)  AS "Net_Revenue_(Platform)",
MAX(CASE WHEN B.ROW_NUM IN (21) THEN A.MEASURE_VALUES   ELSE NULL  END)  AS "gross_order_cvr",
TO_DATE(TO_NVARCHAR(A."YEAR") || '-' || TO_NVARCHAR(A."MONTH") || '-' || TO_NVARCHAR(A."DAY"), 'YYYY-MM-DD') 
AS DT_CREATION
FROM OW_LAO.TMP_GLOBAL_BI_TRAFFIC_ALL A
LEFT JOIN   OW_LAO.DIM_MEASURE_NAMES_TRAFFIC  B ON B.Measure_Names  = A.Measure_Names  
GROUP BY 
A.REGION,
A.SUBSIDIARY,
A.COUNTRY,
A.YEAR,
A.MONTH,
A.WEEK,
A.DAY,
A.CHANNEL_GROUP_1,
A.CHANNEL_GROUP_2,
A.FILE_NAME,
A.RPA_DATE;
END