CREATE PROCEDURE OW_LAO.PROC_ODS_NUBIMETRICS_SALES_LISTINGS_TOKEN_COLOMBIA
 LANGUAGE SQLSCRIPT AS
 BEGIN
 
      INSERT INTO   OW_LAO.RAW_NUBIMETRICS_LISTINGS_SALES  (
 
 SELECT
 
 CATEGORYID,
CATEGORYLEVEL1,
CATEGORYLEVEL2,
CATEGORYLEVEL3,
CATEGORYLEVEL4,
CATEGORYLEVEL5,
CATEGORYLEVEL6,
CATEGORYLEVEL7,
CATEGORYPATH,
LISTINGTITLE,
SELLERNAME,
SELLERCATEGORY,
'Colombia' AS COUNTRY,
INSERT_DATE,
UPDATE_DATE
 FROM OW_LAO.TMP_RAW_NUBIMETRICS_LISTINGS_SALES_COLOMBIA
)
;
DELETE FROM  OW_LAO.ODS_NUBIMETRICS_LISTINGS_SALES  
WHERE CAST( INSERT_DATE AS DATE) >= ADD_MONTHS(CURRENT_DATE, -2)
AND COUNTRY = 'Colombia'
;
 INSERT INTO   OW_LAO.ODS_NUBIMETRICS_LISTINGS_SALES   (
 
SELECT
 
 CATEGORYID,
CATEGORYLEVEL1,
CATEGORYLEVEL2,
CATEGORYLEVEL3,
CATEGORYLEVEL4,
CATEGORYLEVEL5,
CATEGORYLEVEL6,
CATEGORYLEVEL7,
CATEGORYPATH,
LISTINGTITLE,
SELLERNAME,
SELLERCATEGORY,
COUNTRY,
INSERT_DATE,
UPDATE_DATE
 FROM OW_LAO.RAW_NUBIMETRICS_LISTINGS_SALES
 
WHERE CAST( INSERT_DATE AS DATE) >= ADD_MONTHS(CURRENT_DATE, -2)
AND COUNTRY = 'Colombia'
)
;
END 