CREATE PROCEDURE "OW_LAO"."PROC_ODS_AFTER_SALES_CANCELATION"()
LANGUAGE SQLSCRIPT
AS
BEGIN
    -- Etapa 1: Limpar e preencher tabela de pagamentos VTEX
    EXEC 'TRUNCATE TABLE "OW_LAO"."TB_VTEX_PAYMENTS_CONCAT"';
    
    INSERT INTO "OW_LAO"."TB_VTEX_PAYMENTS_CONCAT"
    SELECT * FROM "OW_LAO"."VW_TMP_VTEX_CONCAT";
    -- Etapa 2: Ajustar EXTERNAL_ORDER_ID nas tabelas de staging
    UPDATE "OW_LAO"."TMP_AFTER_SALES_ORDER_NEW"
    SET "EXTERNAL_ORDER_ID" = SUBSTR("EXTERNAL_ORDER_ID", 5, 1000)
    WHERE SUBSTR("EXTERNAL_ORDER_ID", 4, 1) = '-';
    -- Etapa 3: Sincronizar ORDER_ID_JOIN na tabela de cancelamentos
    UPDATE "OW_LAO"."TMP_AFTER_SALES_CANCELATION_MERGE"
    SET "ORDER_ID_JOIN" = "EXTERNAL_ORDER_ID";
    UPDATE "OW_LAO"."TMP_AFTER_SALES_CANCELATION_MERGE"
    SET "ORDER_ID_JOIN" = SUBSTR("ORDER_ID_JOIN", 5, 1000)
    WHERE SUBSTR("ORDER_ID_JOIN", 4, 1) = '-';
    UPDATE "OW_LAO"."TMP_AFTER_SALES_CANCELATION_MERGE"
    SET "ORDER_ID_JOIN" = SUBSTR("ORDER_ID_JOIN", 5, 1000)
    WHERE SUBSTR("ORDER_ID_JOIN", 4, 1) = '-';
    
    -- Etapa 4: Limpar tabela ODS
    EXEC 'TRUNCATE TABLE "OW_LAO"."ODS_AFTER_SALES_CANCELATION_NEW"';
    -- Etapa 5: Inserir dados transformados na tabela ODS
    INSERT INTO "OW_LAO"."ODS_AFTER_SALES_CANCELATION_NEW"
    SELECT DISTINCT
        A."INSTANCIA",
        A."ID_DATA",
        A."TYPE_DATA",
        A."ORINGIN_DATA",
        A."CREATED_AT",
        A."UPDATED_AT",
        A."ID_COMPENSATIONS",
        REPLACE(REPLACE(A."CURRENT_AMOUNT", '[', ''), ']', '') AS "CURRENT_AMOUNT",
        REPLACE(REPLACE(A."CURRENT_SHIPPING_AMOUNT", '[', ''), ']', '') AS "CURRENT_SHIPPING_AMOUNT",
        REPLACE(REPLACE(A."TOTAL_AMOUNT_COMPENSATIONS", '[', ''), ']', '') AS "TOTAL_AMOUNT_COMPENSATIONS",
        A."ID_CUSTOMER",
        A."FIRST_NAME" || ' ' || A."LAST_NAME" AS "NOME_DO_CONSUMIDOR",
        A."E_MAIL",
        A."ID_ECOMMERCE",
        A."DISPLAY_NAME",
        A."ID_ORDER",
        A."EXTERNAL_ORDER_ID",
        D."SEQUENCE",
        D."ACQUIRER",
        D."PAYMENT_SYSTEM_NAME_ORIGIN" AS "PAYMENT_SYSTEM",
        REPLACE(REPLACE(A."ID_PACKAGES", '[', ''), ']', '') AS "ID_PACKAGES",
        REPLACE(REPLACE(A."TOTAL_SHIPPING_AMOUNT", '[', ''), ']', '') AS "TOTAL_SHIPPING_AMOUNT",
        REPLACE(REPLACE(A."TOTAL_PRODUCTS_AMOUNT", '[', ''), ']', '') AS "TOTAL_PRODUCTS_AMOUNT",
        REPLACE(REPLACE(A."TOTAL_AMOUNT_PACKAGES", '[', ''), ']', '') AS "TOTAL_AMOUNT_PACKAGES",
        A."ID_STATUS",
         CASE WHEN B."STATUS_NAME" = 'compensation_created' THEN 'solicitation_created'
             WHEN B."STATUS_NAME" = 'compensation_paid' THEN 'solicitation_done' 
             WHEN B."STATUS_NAME" = 'compensation_canceled' THEN 'solicitation_canceled'ELSE A."NAME_STATUS" END "STATUS_DA_SOLICITACAO",
         CASE WHEN B."STATUS_NAME" = 'compensation_created' THEN 'criada'
             WHEN B."STATUS_NAME" = 'compensation_paid' THEN 'finalizada' 
             WHEN B."STATUS_NAME" = 'compensation_canceled' THEN 'cancelada'ELSE A."DESCRIPTION_STATUS" END "STATUS_DA_SOLICITACAO2",
        B."ID_DATA" AS "ID_DATA_COMPENSATIONS",
        B."SOLICITATION_ID" AS "SOLICITATION_ID_COMPENSATIONS",
        B."CURRENT_AMOUNT" AS "CURRENT_AMOINT_COMPESANTIONS",
        B."CURRENT_SHIPPING_AMOUNT" AS "CURRENT_SHIPPING_AMOUNT_COMPENSATIONS",
        B."TOTAL_AMOUNT" AS "TOTAL_AMOUNT_COMPENSATIONS",
        B."STATUS_ID" AS "STATUS_ID_COMPENSATIONS",
        CASE WHEN A."NAME_STATUS" = 'solicitation_canceled' THEN 'compensation_canceled' 
             WHEN A."NAME_STATUS" = 'solicitation_done' THEN 'compensation_paid'
             WHEN A."NAME_STATUS" = 'solicitation_created' THEN 'compensation_created' ELSE B."STATUS_NAME" END "STATUS_NAME_COMPENSATIONS",
        CASE WHEN A."DESCRIPTION_STATUS" = 'cancelada' THEN 'cancelada'
             WHEN A."DESCRIPTION_STATUS" = 'finalizada' THEN 'paga' 
             WHEN A."DESCRIPTION_STATUS" = 'criada' THEN 'criada'ELSE B."STATUS_DESCRIPTION" END "STATUS_DESCRIPTION_COMPENSATIONS",
        IFNULL(B."HISTORIES_ID", '') ||
        IFNULL(B."HISTORIES_DATE", '') ||
        IFNULL(B."HISTORIES_COMMENTS", '') ||
        IFNULL(B."HISTORIES_STATUS_ID", '') ||
        IFNULL(B."HISTORIES_STATUS_SERVICE_CODE", '') ||
        IFNULL(B."HISTORIES_STATUS_NAME", '') ||
        IFNULL(B."HISTORIES_STATUS_DESCRIPTION", '') ||
        IFNULL(B."HISTORIES_USER", '') AS "HISTORIES",
        B."ACTIONS_ENABLE_INTEGRATE_PAYMENT",
        C."ID_DATA" AS "ID_DATA_ORDER",
        C."EXTERNAL_ORDER_ID" AS "EXTERNAL_ORDER_ID_ORDER",
        C."ORDERED_AT" AS "ORDERED_AT_ORDER",
        REPLACE(REPLACE(REPLACE(C."TRANSACTIONS_ID", '[', ''), ']', ''), '"', '') AS "TRANSACTIONS_ID",
        REPLACE(REPLACE(REPLACE(C."TRANSACTIONS_MERCHANT_NAME", '[', ''), ']', ''), '"', '') AS "TRANSACTIONS_MERCHANT_NAME",
        REPLACE(REPLACE(REPLACE(C."TRANSACTIONS_PAYMENT_METHOD", '[', ''), ']', ''), '"', '') AS "TRANSACTIONS_PAYMENT_METHOD",
        REPLACE(REPLACE(REPLACE(C."TRANSACTIONS_PAYMENT_DESCRIPTION", '[', ''), ']', ''), '"', '') AS "TRANSACTIONS_PAYMENT_DESCRIPTION",
        REPLACE(REPLACE(REPLACE(C."TRANSACTIONS_PAYMENT_GIFT_CARD_REMD", '[', ''), ']', ''), '"', '') AS "TRANSACTIONS_PAYMENT_GIFT_CARD_REMD",
        REPLACE(REPLACE(REPLACE(C."TRANSACTIONS_ACQUIRER", '[', ''), ']', ''), '"', '') AS "TRANSACTIONS_ACQUIRER",
        REPLACE(REPLACE(REPLACE(C."TRANSACTIONS_NSU", '[', ''), ']', ''), '"', '') AS "TRANSACTIONS_NSU",
        REPLACE(REPLACE(REPLACE(C."TRANSACTIONS_TID", '[', ''), ']', ''), '"', '') AS "TRANSACTIONS_TID",
        REPLACE(REPLACE(REPLACE(C."TRANSACTIONS_TOTAL_AMOUNT", '[', ''), ']', ''), '"', '') AS "TRANSACTIONS_TOTAL_AMOUNT",
        REPLACE(REPLACE(REPLACE(C."TRANSACTIONS_LAST_DIGITS", '[', ''), ']', ''), '"', '') AS "TRANSACTIONS_LAST_DIGITS",
        A."LOAD_DATE"
    FROM 
        "OW_LAO"."TMP_AFTER_SALES_CANCELATION_MERGE" AS A
        LEFT JOIN "OW_LAO"."VIEW_TMP_AFTER_SALES_COMPENSATIONS_NEW" AS B 
            ON TRIM(A."ID_DATA") = TRIM(B."SOLICITATION_ID")
        --LEFT JOIN "OW_LAO"."VIEW_TMP_AFTER_SALES_ORDER_NEW" AS C 
        LEFT JOIN "OW_LAO"."TMP_AFTER_SALES_ORDER_MERGE" AS C     
            ON A."ORDER_ID_JOIN" = CASE WHEN SUBSTR(C."EXTERNAL_ORDER_ID",4,1)='-' THEN 
                                           SUBSTR(C."EXTERNAL_ORDER_ID",5,1000) ELSE C."EXTERNAL_ORDER_ID" END 
        LEFT JOIN "OW_LAO"."TB_VTEX_PAYMENTS_CONCAT" AS D 
            ON CASE 
                WHEN SUBSTR(A."EXTERNAL_ORDER_ID", 1, 4) = 'MZN-' 
                THEN SUBSTR(A."EXTERNAL_ORDER_ID", 5, 1000) 
                ELSE A."ORDER_ID_JOIN" 
               END = D."ORDER_ID";
    -- Confirma a transação
    COMMIT;
END;