CREATE PROCEDURE OW_LAO.PROC_LAO_CRP_CS_VOUCHER_COUPON_UPDATE
LANGUAGE SQLSCRIPT AS
	BEGIN 
		MERGE INTO 
		 	OW_LAO.DIM_LAO_CRP_CS_VOUCHER_COUPON		AS A
		USING 
			OW_LAO.RAW_LAO_CRP_CS_VOUCHER_COUPON 	AS B 
		ON 		A.SUBSIDIARY			= B.SUBSIDIARY
			AND A.VOUCHER_COUPON 		= B.VOUCHER_COUPON
		WHEN MATCHED AND A.ACTIVE = FALSE OR A.ACTIVE IS NULL
		 THEN UPDATE SET
			A.UPDATED_TIMESTAMP		= CURRENT_TIMESTAMP,
			A.ACTIVE 				= TRUE,
			A.REPROCESSING			= TRUE
		 WHEN NOT MATCHED THEN INSERT(
		 	SUBSIDIARY,
		 	VOUCHER_COUPON,
		 	CRP,
		 	ACTIVE,
		 	REPROCESSING
		 )
		 VALUES (
		 	B.SUBSIDIARY,
		 	B.VOUCHER_COUPON,
		 	2,
		 	TRUE,
		 	TRUE
		);
		/*-------------------------------------------------------------------------------------------------*/
		--Delete
		UPDATE
			OW_LAO.DIM_LAO_CRP_CS_VOUCHER_COUPON A	
		SET
			ACTIVE 				= FALSE,
			REPROCESSING 		= FALSE,
			UPDATED_TIMESTAMP 	= CURRENT_TIMESTAMP
		FROM
			OW_LAO.DIM_LAO_CRP_CS_VOUCHER_COUPON A
		WHERE
			NOT EXISTS(
				SELECT 
					1
				FROM
					OW_LAO.RAW_LAO_CRP_CS_VOUCHER_COUPON B
				WHERE 
					A.SUBSIDIARY 			= B.SUBSIDIARY
					AND A.VOUCHER_COUPON  		= B.VOUCHER_COUPON
			)
		AND ACTIVE = TRUE;
	END