CREATE PROCEDURE OW_LAO.PROC_LAO_TF_GLOBAL_BI_TRAFFIC_VD
LANGUAGE SQLSCRIPT AS
   BEGIN
SELECT  DISTINCT 
A.REGION,
A.SUBSIDIARY,
A.COUNTRY,
A.YEAR,
A.MONTH,
A.WEEK,
A.DAY,
A.CHANNEL_GROUP_1,
A.CHANNEL_GROUP_2,
A.FILE_NAME,
A.RPA_DATE,
MAX(CASE WHEN B.ROW_NUM IN (1) THEN A.MEASURE_VALUES   ELSE NULL  END)  AS "COM_Visit",
MAX(CASE WHEN B.ROW_NUM IN (8,11,12,13) THEN A.MEASURE_VALUES   ELSE NULL  END)  AS "Shopper_Visit" ,	
MAX(CASE WHEN B.ROW_NUM IN (19,2) THEN A.MEASURE_VALUES   ELSE NULL  END)  AS "Add_to_Cart_Current",
MAX(CASE WHEN B.ROW_NUM IN (18,3) THEN A.MEASURE_VALUES   ELSE NULL  END)  AS "Cart_Page_Visit_Current	",
MAX(CASE WHEN B.ROW_NUM IN (17,4) THEN A.MEASURE_VALUES   ELSE NULL  END)  AS "Checkout_Page_Current",
MAX(CASE WHEN B.ROW_NUM IN (16,10,5,22,23) THEN ROUND(A.MEASURE_VALUES,0)   ELSE NULL  END)  AS "Gross_Order",
MAX(CASE WHEN B.ROW_NUM IN (6,15,20) THEN ROUND(A.MEASURE_VALUES,0)   ELSE NULL  END)  AS "Net_Orders_Current",
MAX(CASE WHEN B.ROW_NUM IN (7,9,14) THEN A.MEASURE_VALUES   ELSE NULL  END)  AS "Net_Revenue",
MAX(CASE WHEN B.ROW_NUM IN (21,24) THEN A.MEASURE_VALUES   ELSE NULL  END)  AS "gross_order_cvr",
TO_DATE(TO_NVARCHAR(A."YEAR") || '-' || TO_NVARCHAR(A."MONTH") || '-' || TO_NVARCHAR(A."DAY"), 'YYYY-MM-DD') 
AS DT_CREATION
FROM OW_LAO.TMP_GLOBAL_BI_TRAFFIC_VD A
LEFT JOIN  OW_LAO.DIM_MEASURE_NAMES_TRAFFIC  B ON B.Measure_Names  = A.Measure_Names  
GROUP BY 
A.REGION,
A.SUBSIDIARY,
A.COUNTRY,
A.YEAR,
A.MONTH,
A.WEEK,
A.DAY,
A.CHANNEL_GROUP_1,
A.CHANNEL_GROUP_2,
A.FILE_NAME,
A.RPA_DATE;
END;