
CREATE PROCEDURE OW_LAO.PROC_LAO_SALES_DEDUCITON_DAILY_VALIDATION_FOTA_01W_05W
LANGUAGE SQLSCRIPT as
BEGIN
	/*
	 * WEEKDAY(CURRENT_DATE) = 1  -> TERÇA-FEIRA
	 * WEEKDAY(CURRENT_DATE) = 4  -> SEXTA-FEIRA
	*/
	
/**
 Caso o processo apresente erro e rode mais de uma vez em um unico dia.
	Deleta os dados inseridos hoje da tabela 
	"OW_LAO"."ODS_SALES_DEDUCTION_VALIDATION_DAILY_FOTA_01_05W"
**/
 
 DELETE FROM "OW_LAO"."ODS_SALES_DEDUCTION_VALIDATION_DAILY_FOTA_01_05W"
	WHERE TO_DATE(LOAD_DATE) = CURRENT_DATE;
 
-- 		INSERT NA TABELA QUE IRÁ SER USADA PARA VALIDAR.
	/*  
	 *  TABELA VALIDATION: "OW_LAO"."ODS_SALES_DEDUCTION_VALIDATION_DAILY_FOTA_01_05W"
	 * 
	 * 
	 * 
	 * 
	 * */
	
	INSERT INTO "OW_LAO"."ODS_SALES_DEDUCTION_VALIDATION_DAILY_FOTA_01_05W" (WEEK_, COMPANY_CODE, BUSINESS_AREA, QUANTITY, SOURCE_)
SELECT 
    TO_VARCHAR(CURRENT_DATE, 'YYYYWW') AS WEEK_,
    COMPANY_CODE,
    BUSINESS_AREA,
    COUNT(*) AS QUANTITY,
    'FOTA' AS SOURCE_
FROM (
    SELECT 
        COMPANY_CODE, 
        BUSINESS_AREA, 
        ITEM, 
        SALES_DATE, 
        CHANNEL_CODE_FROM,  
        CHANNEL_CODE, 
        CHANNEL_CODE_TO,  
        SUM(VALUE) AS SALES_QTY
    FROM OW_LAO.FT_LAO_SALES_DEDUCTION_DAILY_FOTA -- DADOS FOTA
    WHERE "SOURCE" = 'FOTA'
    AND SALES_DATE IS NOT NULL
    AND COMPANY_CODE IS NOT NULL
    GROUP BY COMPANY_CODE, BUSINESS_AREA, ITEM, SALES_DATE, CHANNEL_CODE_FROM, CHANNEL_CODE, CHANNEL_CODE_TO
) AS SUBQUERY
GROUP BY 
    COMPANY_CODE, 
    BUSINESS_AREA, 
    TO_VARCHAR(CURRENT_DATE, 'YYYYWW'),
    'FOTA';
	
/**
 Caso o processo apresente erro e rode mais de uma vez em um unico dia.
	Deleta os dados inseridos hoje da tabela 
	"OW_LAO"."ODS_SALES_DEDUCTION_CURRENT_WEEK_DATA_FOTA_01_05W"
**/
 
 DELETE FROM "OW_LAO"."ODS_SALES_DEDUCTION_CURRENT_WEEK_DATA_FOTA_01_05W"
	WHERE LOAD_DATE = CURRENT_DATE;
-- 		INSERT NA TABELA CURRENT WEEK
	/*  
	 *  TABELA : "OW_LAO"."ODS_SALES_DEDUCTION_CURRENT_WEEK_DATA_FOTA_01_05W"
	 * 
	 * 
	 * */
INSERT  INTO "OW_LAO"."ODS_SALES_DEDUCTION_CURRENT_WEEK_DATA_FOTA_01_05W" (
            CURRENT_WEEK,
            COMPANY_CODE,
            BUSINESS_AREA,
            CURRENT_QUANTITY,
            SOURCE_,
            LOAD_DATE)
                  SELECT 
            WEEK_ AS CURRENT_WEEK,
            COMPANY_CODE,
            BUSINESS_AREA,
            QUANTITY AS CURRENT_QUANTITY,
            SOURCE_,
            TO_DATE(LOAD_DATE) AS LOAD_DATE
FROM "OW_LAO"."ODS_SALES_DEDUCTION_VALIDATION_DAILY_FOTA_01_05W"
WHERE WEEKDAY(CURRENT_DATE) = WEEKDAY(LOAD_DATE)
AND WEEK_ = TO_VARCHAR(CURRENT_DATE, 'YYYYWW');
/**
 Caso o processo apresente erro e rode mais de uma vez em um unico dia.
	Deleta os dados inseridos hoje da tabela 
	"OW_LAO"."ODS_SALES_DEDUCTION_PREVIOUS_WEEK_DATA_FOTA_01_05W"
**/
DELETE FROM "OW_LAO"."ODS_SALES_DEDUCTION_PREVIOUS_WEEK_DATA_FOTA_01_05W"
WHERE PREVIOUS_WEEK =  
(	CASE WHEN WEEKDAY(CURRENT_DATE) = 1 THEN 
		TO_VARCHAR(ADD_DAYS(CURRENT_DATE,-7), 'YYYYWW')
		 WHEN WEEKDAY(CURRENT_DATE) = 4 THEN 
		TO_VARCHAR(ADD_DAYS(CURRENT_DATE,-3), 'YYYYWW')
END ) 
AND LOAD_DATE =  
(	CASE WHEN WEEKDAY(CURRENT_DATE) = 1 THEN 
			TO_DATE(ADD_DAYS(CURRENT_DATE,-7))
	   	 WHEN WEEKDAY(CURRENT_DATE) = 4 THEN 
			TO_DATE(ADD_DAYS(CURRENT_DATE,-3))
END)
;
-- 		INSERT NA TABELA PREVIOUS WEEK
	/*  
	 *  TABELA : "OW_LAO"."ODS_SALES_DEDUCTION_PREVIOUS_WEEK_DATA_FOTA_01_05W"
	 * 
	 * 
	 * */	
INSERT INTO "OW_LAO"."ODS_SALES_DEDUCTION_PREVIOUS_WEEK_DATA_FOTA_01_05W" (
            PREVIOUS_WEEK ,
            COMPANY_CODE,
            BUSINESS_AREA,
            PREVIOUS_QUANTITY ,
            SOURCE_,
            LOAD_DATE)
                  SELECT 
            WEEK_ AS CURRENT_WEEK,
            COMPANY_CODE,
            BUSINESS_AREA,
            QUANTITY AS CURRENT_QUANTITY,
            SOURCE_,
            TO_DATE(LOAD_DATE) AS LOAD_DATE           
FROM "OW_LAO"."ODS_SALES_DEDUCTION_VALIDATION_DAILY_FOTA_01_05W"
WHERE WEEK_ =  
(	CASE WHEN WEEKDAY(CURRENT_DATE) = 1 THEN 
		TO_VARCHAR(ADD_DAYS(CURRENT_DATE,-7), 'YYYYWW')
		 WHEN WEEKDAY(CURRENT_DATE) = 4 THEN 
		TO_VARCHAR(ADD_DAYS(CURRENT_DATE,-3), 'YYYYWW')
END ) 
AND TO_DATE(LOAD_DATE) =  
(	CASE WHEN WEEKDAY(CURRENT_DATE) = 1 THEN 
			TO_DATE(ADD_DAYS(CURRENT_DATE,-7))
	   	 WHEN WEEKDAY(CURRENT_DATE) = 4 THEN 
			TO_DATE(ADD_DAYS(CURRENT_DATE,-3))
END)
;
/**
 Remover possivel duplicidade do processo de comparação dos dados
 **/
DELETE FROM "OW_LAO"."ODS_LAO_SALES_DEDUCTION_VALIDATION_WEEK_RESULT_FOTA_01_05W"
WHERE CURRENT_LOAD_DATE = CURRENT_DATE; 
-- COMPARAÇÃO SEMANA ATUAL VS SEMANA ANTERIOR 
-- TABELA "OW_LAO"."ODS_LAO_SALES_DEDUCTION_VALIDATION_WEEK_RESULT_FOTA_01_05W"
INSERT INTO "OW_LAO"."ODS_LAO_SALES_DEDUCTION_VALIDATION_WEEK_RESULT_FOTA_01_05W"(
		COMPANY_CODE,
		BUSINESS_AREA,
		SOURCE_,
		CURRENT_WEEK,
		PREVIOUS_WEEK,
		CURRENT_QUANTITY,
		PREVIOUS_QUANTITY,
		QUANTITY_DIFFERENCE,
		PERCENTAGE_DIFFERENCE,
		CURRENT_LOAD_DATE
	)
	SELECT  --DISTINCT 
		CUR.COMPANY_CODE,
		CUR.BUSINESS_AREA,
		CUR.SOURCE_,
		CUR.CURRENT_WEEK,
		PREVIOUS.PREVIOUS_WEEK,
		CUR.CURRENT_QUANTITY,
		PREVIOUS.PREVIOUS_QUANTITY,
		CUR.CURRENT_QUANTITY - PREVIOUS.PREVIOUS_QUANTITY AS QUANTITY_DIFFERENCE,
		CASE 
			WHEN PREVIOUS.PREVIOUS_QUANTITY = 0 THEN 0
			ELSE ROUND((CUR.CURRENT_QUANTITY - PREVIOUS.PREVIOUS_QUANTITY) / PREVIOUS.PREVIOUS_QUANTITY * 100,2)
		END AS PERCENTAGE_DIFFERENCE,
		CUR.LOAD_DATE		
FROM "OW_LAO"."ODS_SALES_DEDUCTION_CURRENT_WEEK_DATA_FOTA_01_05W" CUR
INNER JOIN "OW_LAO"."ODS_SALES_DEDUCTION_PREVIOUS_WEEK_DATA_FOTA_01_05W" PREVIOUS
ON CUR.COMPANY_CODE = PREVIOUS.COMPANY_CODE
AND CUR.BUSINESS_AREA = PREVIOUS.BUSINESS_AREA
AND CUR.SOURCE_ = PREVIOUS.SOURCE_ 
WHERE CUR.LOAD_DATE = CURRENT_DATE
  AND PREVIOUS.PREVIOUS_WEEK =
(	CASE WHEN WEEKDAY(CURRENT_DATE) = 1 THEN 
		TO_VARCHAR(ADD_DAYS(CURRENT_DATE,-7), 'YYYYWW')
		 WHEN WEEKDAY(CURRENT_DATE) = 4 THEN 
		TO_VARCHAR(ADD_DAYS(CURRENT_DATE,-3), 'YYYYWW')
END ) 
  AND PREVIOUS.LOAD_DATE =  
(	CASE WHEN WEEKDAY(CURRENT_DATE) = 1 THEN 
			TO_DATE(ADD_DAYS(CURRENT_DATE,-7))
	   	 WHEN WEEKDAY(CURRENT_DATE) = 4 THEN 
			TO_DATE(ADD_DAYS(CURRENT_DATE,-3))
END)
;
END