CREATE PROCEDURE OW_LAO.PROC_FT_LAO_GOVERNANCE_ORDERS_KPI LANGUAGE SQLSCRIPT
AS
BEGIN
	
DELETE FROM OW_LAO.FT_LAO_GOVERNANCE_ORDERS  
WHERE CAST(PO_DATE AS DATE) BETWEEN ADD_DAYS(CURRENT_DATE, -1) AND CURRENT_DATE
;
INSERT INTO OW_LAO.FT_LAO_GOVERNANCE_ORDERS 
(SELECT * FROM OW_LAO.VIEW_ORDERS_GOVERNANCE_LAO
WHERE CAST(PO_DATE AS DATE) BETWEEN ADD_DAYS(CURRENT_DATE, -1) AND CURRENT_DATE)
;
END 