CREATE PROCEDURE OW_LAO.PROC_FUNNEL_PAYMENTS_MAP(
	IN CONSULTA NVARCHAR(40)
) LANGUAGE SQLSCRIPT AS
BEGIN	
	IF :CONSULTA = 'F_FUNNEL_PAYMENTS' THEN	
	BEGIN
		/*-------------------------------------------------------------------------------------------------*/
		--	
		CREATE LOCAL TEMPORARY TABLE #AUX_TAXES AS (			
			SELECT 
				SUBSIDIARY,
				CURRENCY,
				TAX_VALUE
			FROM 
				OW_LAO.AUX_SALES_CONTROL_TOWER_TABLE_TAXES 	A
			JOIN
				U_PRJ_ECOM.DIM_SUBSIDIARY 					B
			ON	
				A.ID = B.ID 
			ORDER BY 
				SUBSIDIARY_ID			
		);				
		/*-------------------------------------------------------------------------------------------------*/
		--			
		SELECT  
			A.PO_DATE,
			WEEK(A.PO_DATE)					AS PO_WEEK, 
			A.PO_MONTH,
			A.PO_YEAR,
			A.SUBSIDIARY,
			CASE 
				WHEN UPPER(PO_DEVICETYPE) IN('WEBMOBILE', 'WEB') 	THEN 'Website'
				WHEN UPPER(PO_DEVICETYPE) IN('MOBILEAPP') 			THEN 'App'
				ELSE 'Website'
			END AS PO_DEVICETYPE,
			A.CHANNEL,
			CASE 
				WHEN BIZ_TYPE =  'B2C' THEN 'SHOP' 
				ELSE BIZ_TYPE
			END 							AS BIZ_TYPE,
			A.AUDIENCE_TYPE,
			A.FUNNEL_STATUS,
			A.PAY_GATEWAY,
			A.PAY_STORENAME 				AS PO_STORENAME,
			A.PAY_ORDERID,
			A.PAY_STATUS,
			A.PAY_DETAIL,
			A.PAY_GATEWAY_CODE,
			A.PAYMENT_TYPE,
			A.CURRENCY,
			A.POSTORENAME,
			B.GATEWAY,
			C.PAYMENT_MODE,
			D.GATEWAY_CODE,
			CAST(A.PE_AMOUNT 	 AS DECIMAL) 						AS PE_AMOUNT,
			CAST(A.REVENUE_LOCAL AS DECIMAL) 						AS REVENUE_LOCAL,
			A.REVENUE_LOCAL - (A.REVENUE_LOCAL 	* E.TAX_VALUE)  	AS NET_REVENUE_LOCAL,
			A.REVENU_USD 	- (A.REVENU_USD 	* E.TAX_VALUE)		AS NET_REVENUE_USD,			
			CAST(A.REVENU_USD 	 AS DECIMAL) 						AS REVENU_USD,
			CAST(F.EXCHANGE_RATE AS DECIMAL) 						AS EXCHANGE_RATE,
			IFNULL(A.UPDATED_TIMESTAMP,A.INSERT_TIMESTAMP) DT_RANGE
		FROM 
			OW_LAO.ODS_PAYMENT_FUNNEL 		A
		JOIN
			OW_LAO.DIM_PAYMENT_PAY_GATEWAY	B ON UPPER(A.PAY_GATEWAY) = UPPER(B.PAY_GATEWAY)
		JOIN 
			OW_LAO.DIM_PAYMENT_PAYMENT_TYPE	C ON UPPER(A.PAYMENT_TYPE) = UPPER(C.PAYMENT_TYPE) 
		JOIN 
			OW_LAO.DIM_PAYMENT_GATEWAY_CODE D ON UPPER(A.PAY_GATEWAY_CODE) = UPPER(D.PAY_GATEWAY_CODE) 
		JOIN
			#AUX_TAXES						E ON A.SUBSIDIARY = E.SUBSIDIARY AND A.CURRENCY = E.CURRENCY
		JOIN
			OW_LAO.FT_AP2_EXCHANGE_RATE 	F ON ADD_DAYS(CAST(A.PO_DATE AS DATE),-1) = F.VALID_FROM AND LOWER(A.CURRENCY) = LOWER(F.TO_CURRENCY)
		WHERE 
			A.FUNNEL_STATUS IS NOT NULL;
		
		DROP TABLE #AUX_TAXES;
	END;
	ELSEIF :CONSULTA = 'D_CALENDARIO' THEN	
	/*-------------------------------------------------------------------------------------------------*/
	--		
	BEGIN
        SELECT DISTINCT 
            PO_DATE,
            CAST(RIGHT(ISOWEEK(PO_DATE),2) AS integer) AS "Semana"
        FROM 
            OW_LAO.ODS_PAYMENT_FUNNEL A	
        WHERE 
            A.FUNNEL_STATUS IS NOT NULL;
	END;
	ELSE
		SELECT 'Procedimento não declaro' AS CONSULTA FROM DUMMY;		
	END IF;
END;
