CREATE PROCEDURE OW_LAO.PROC_LAO_CRP_CS_STORENAME_UPDATE
LANGUAGE SQLSCRIPT AS
	BEGIN 
		MERGE INTO 
		 	OW_LAO.DIM_LAO_CRP_CS_STORENAME		AS A
		USING 
			OW_LAO.RAW_LAO_CRP_CS_STORENAME 	AS B 
		ON 		A.SUBSIDIARY			= B.SUBSIDIARY
			AND A.STORENAME_CRP 		= B.STORENAME_CRP
		WHEN MATCHED AND A.ACTIVE = FALSE OR A.ACTIVE IS NULL
		 THEN UPDATE SET
			A.UPDATED_TIMESTAMP		= CURRENT_TIMESTAMP,
			A.ACTIVE 				= TRUE,
			A.REPROCESSING			= TRUE
		 WHEN NOT MATCHED THEN INSERT(
		 	SUBSIDIARY,
		 	STORENAME_CRP,
		 	CRP,
		 	ACTIVE,
		 	REPROCESSING
		 )
		 VALUES (
		 	B.SUBSIDIARY,
		 	B.STORENAME_CRP,
		 	1,
		 	TRUE,
		 	TRUE
		);
		/*-------------------------------------------------------------------------------------------------*/
		--Delete
		UPDATE
			OW_LAO.DIM_LAO_CRP_CS_STORENAME A	
		SET
			ACTIVE 				= FALSE,
			REPROCESSING 		= FALSE,
			UPDATED_TIMESTAMP 	= CURRENT_TIMESTAMP
		FROM
			OW_LAO.DIM_LAO_CRP_CS_STORENAME A
		WHERE
			NOT EXISTS(
				SELECT 
					1
				FROM
					OW_LAO.RAW_LAO_CRP_CS_STORENAME B
				WHERE 
					A.SUBSIDIARY 			= B.SUBSIDIARY
					AND A.STORENAME_CRP  		= B.STORENAME_CRP
			)
		AND ACTIVE = TRUE;
	END