CREATE PROCEDURE OW_LAO.PROC_LAO_SALES_DEDUCTION_DAILY_EDI_EXCEPTION
LANGUAGE SQLSCRIPT as
BEGIN
-- Truncate table OW_LAO.TF_LAO_SALES_DEDUCTION_DAILY_GSCM_EXCEPTION
TRUNCATE TABLE OW_LAO.TF_LAO_SALES_DEDUCTION_DAILY_GSCM_EXCEPTION;
--CREATE TABLE OW_LAO.TF_LAO_SALES_DEDUCTION_DAILY_GSCM_EXCEPTION AS (
INSERT INTO OW_LAO.TF_LAO_SALES_DEDUCTION_DAILY_GSCM_EXCEPTION
SELECT 
	UPPER(GSCM.AP2) -- OK NOVA VERSÃO.
	,UPPER(GSCM.AP1) -- OK NOVA VERSÃO
	,UPPER(GSCM.CHANNEL) -- CHANNEL = SOLD-TO NA NOVA VERSÃO.
	,UPPER(GSCM.ITEM) -- OK NOVA VERSÃO.
	,REPLACE(TO_CHAR(GSCM.DATE_FORMAT), '-', '.') AS "SALES_DATE"
	,GSCM."VALUE" 
	,UPPER(GSCM."SOURCE") -- AUTOFILL BY SPLIT FOLDER NAME 
	,UPPER(GSCM.PRODUCT_GRP) -- OK NOVA VERSÃO.
	,UPPER(GSCM.PRODUCT) -- OK NOVA VERSÃO
	,(CASE WHEN UPPER(GSCM.PRODUCT_GRP) ='MOBILE' AND UPPER(GSCM.PRODUCT) ='HHP' 
			THEN 'SMART' 
	WHEN UPPER(GSCM.PRODUCT_GRP) ='MOBILE' AND UPPER(GSCM.PRODUCT) ='TABLET' 
			THEN 'TABLET'
			ELSE UPPER(GSCM.PRODUCT_GRP) 
	END ) AS TF_GSCM_PRODUCT_GRP
	,(CASE WHEN UPPER(GSCM.AP2) = 'SELA-P' 
		THEN UPPER(GSCM.AP1)
		ELSE '1'
	END) AS TF_GSCM_AP1	
	,UPPER(GSCM.FULL_FILE_NAME) AS "GSCM_FULL_FILE_NAME"
	,UPPER(GSCM.LOAD_DATE) AS  "GSCM_LOAD_DATE"
FROM OW_LAO.ODS_GSCM_CH_PSI_WARNING_SALES_DEDUCTION_DAILY_EXCEPTION GSCM
	WHERE GSCM.DATE_FORMAT IS NOT NULL 
--)
;
-- Truncate table OW_LAO.TF_LAO_SALES_DEDUCTION_DAILY_BIZ_AREA
TRUNCATE TABLE OW_LAO.TF_LAO_SALES_DEDUCTION_DAILY_BIZ_AREA;
--CREATE TABLE OW_LAO.TF_LAO_SALES_DEDUCTION_DAILY_BIZ_AREA AS (
INSERT INTO OW_LAO.TF_LAO_SALES_DEDUCTION_DAILY_BIZ_AREA
SELECT 	BIZ_AREA.COMPANY_CODE AS COMPANY_CODE
	,BIZ_AREA.COMPANY_CODE_NAME
	,BIZ_AREA.AP1
	,BIZ_AREA.BUSINESS_AREA
	,(CASE WHEN BIZ_AREA.COMPANY_CODE_NAME = 'SELA-P' 
		THEN BIZ_AREA.AP1
		ELSE '1'
	END) AS TF_BIZ_AREA_COMPANY_CODE
	
FROM "OW_LAO"."INPUT_MAPPING_BIZ_AREA_SALES_DEDUCTION" BIZ_AREA
WHERE BIZ_AREA.BUSINESS_AREA <> '850C'
--)	
;
-- Truncate table OW_LAO.TF_LAO_SALES_DEDUCTION_DAILY_CORES
TRUNCATE TABLE OW_LAO.TF_LAO_SALES_DEDUCTION_DAILY_CORES;
--CREATE TABLE OW_LAO.TF_LAO_SALES_DEDUCTION_DAILY_CORES AS (
INSERT INTO OW_LAO.TF_LAO_SALES_DEDUCTION_DAILY_CORES
SELECT 	UPPER(CORES.AP2)
	,UPPER(CORES.AP1)
	,UPPER(REPLACE(CORES.CUSTOMER_CODE,',0','')) AS CHANNEL_CODE
	,UPPER(CORES.SOLD_TO_PARTY) AS "SOLD_TO"
	,UPPER(CORES.PROD_GROUP)
	,CORES."LEVEL"
	,UPPER(CORES.CHANNEL)
	,UPPER(CORES.PARENT_CHANNEL)
	,UPPER(CORES."SOURCE")
	,(CASE WHEN UPPER(CORES.AP2) = 'SELA-P'
		THEN UPPER(CORES.AP1)
		ELSE '1'
	END) AS TF_CORES_AP1
	,UPPER(CORES.FILE_NAME) AS "MAP_CORES_FILE_NAME"
	,UPPER(CORES.LOAD_DATE) AS "MAP_CORES_LOAD_DATE"
FROM "OW_LAO"."INPUT_MAP_CORES_SALES_DEDUCTION" CORES
--)	
;
-- Truncate table OW_LAO.FT_LAO_SALES_DEDUCTION_DAILY_EXCEPTION
TRUNCATE TABLE OW_LAO.FT_LAO_SALES_DEDUCTION_DAILY_EXCEPTION;
--CREATE TABLE OW_LAO.FT_LAO_SALES_DEDUCTION_DAILY_EXCEPTION AS (
INSERT INTO OW_LAO.FT_LAO_SALES_DEDUCTION_DAILY_EXCEPTION
SELECT 
	BIZ_AREA.COMPANY_CODE
	,BIZ_AREA.BUSINESS_AREA
	,GSCM.ITEM
	,GSCM.SALES_DATE
	,DC.YYYYWW AS "YEAR_WEEK"
	,(CASE WHEN CORES."LEVEL" ='2' THEN 'SAMSUNG' ELSE REPLACE(CORES.PARENT_CHANNEL,',0','') END) AS "CHANNEL_CODE_FROM"
	,CORES.CHANNEL_CODE
	,'CONSUMER' AS CHANNEL_CODE_TO
	,'SO' AS SELL_OUT_FLAG
	,CORES.SOLD_TO
	,GSCM."VALUE"
	,(CASE WHEN CORES.PROD_GROUP <> 'ALL' AND GSCM.AP2 <> 'SELA-P' AND CORES."LEVEL" ='3'
		THEN 'LVL 3, != ALL, NOT SELA'
	WHEN CORES.PROD_GROUP <> 'ALL' AND GSCM.AP2 <> 'SELA-P' AND CORES."LEVEL" ='2'
		THEN 'LVL 2, != ALL, NOT SELA'
	WHEN CORES.PROD_GROUP <> 'ALL' AND GSCM.AP2 = 'SELA-P' AND CORES."LEVEL" ='3'
		THEN 'LVL 3, != ALL, IN SELA'
	WHEN CORES.PROD_GROUP <> 'ALL' AND GSCM.AP2 = 'SELA-P' AND CORES."LEVEL" ='2'
		THEN 'LVL 2, != ALL, IN SELA'
	WHEN CORES.PROD_GROUP = 'ALL' AND GSCM.AP2 <> 'SELA-P' AND CORES."LEVEL" ='3'
		THEN 'LVL 3, = ALL, NOT SELA'
	WHEN CORES.PROD_GROUP = 'ALL' AND GSCM.AP2 <> 'SELA-P' AND CORES."LEVEL" ='2'
		THEN 'LVL 2, = ALL, NOT SELA'
	WHEN CORES.PROD_GROUP = 'ALL' AND GSCM.AP2 = 'SELA-P' AND CORES."LEVEL" ='3'
		THEN 'LVL 3, = ALL, IN SELA'
	WHEN CORES.PROD_GROUP = 'ALL' AND GSCM.AP2 = 'SELA-P' AND CORES."LEVEL" ='2'
		THEN 'LVL 2, = ALL, IN SELA'
		ELSE NULL
	END) AS MAPPED
	,GSCM."SOURCE"
	,CORES.PROD_GROUP
	,CORES."LEVEL" 
	,GSCM.AP2
	,GSCM.GSCM_FULL_FILE_NAME
	,GSCM.GSCM_LOAD_DATE
	,CORES.MAP_CORES_FILE_NAME 
	,CORES.MAP_CORES_LOAD_DATE
	,NOW() AS "PROCESS_LOAD_DATE"
	,DAYNAME(NOW()) AS "DAY_PROCESS_NAME"
	,'EXCEPTION_PROCESS' AS "PROCESS_TYPE"
	,'EDI_EXCEPTION' AS "SOURCE_PROCESS"
FROM OW_LAO.TF_LAO_SALES_DEDUCTION_DAILY_GSCM_EXCEPTION GSCM 
LEFT JOIN OW_LAO.TF_LAO_SALES_DEDUCTION_DAILY_BIZ_AREA BIZ_AREA ON (GSCM.AP2 = BIZ_AREA.COMPANY_CODE_NAME
								AND GSCM.TF_GSCM_AP1 = BIZ_AREA.TF_BIZ_AREA_COMPANY_CODE )
LEFT JOIN OW_LAO.TF_LAO_SALES_DEDUCTION_DAILY_CORES CORES ON (GSCM.AP2 = CORES.AP2
							  AND GSCM.CHANNEL = CORES.CHANNEL
							  AND GSCM."SOURCE" = CORES."SOURCE"
							  AND GSCM.TF_GSCM_AP1 = CORES.TF_CORES_AP1
							  AND TF_GSCM_PRODUCT_GRP = (CASE WHEN CORES.PROD_GROUP = 'ALL'
							  					THEN TF_GSCM_PRODUCT_GRP
							  					ELSE CORES.PROD_GROUP
							  			    END)
							     )
LEFT JOIN OW_MD.DIM_CALENDAR DC ON (GSCM.SALES_DATE = DC.YYYYMMDD)
WHERE CORES."SOURCE" IS NOT NULL
--)
;
-- EM CASO DE RODAR O MESMO PROCESSO 2X NO DIA ELE IRÁ LIMPAR OS DADOS HISTORICOS PARA NÃO DUPLICAR
--DELETE FROM OW_LAO.FT_LAO_SALES_DEDUCTION_HISTORICO 
--WHERE SOURCE_PROCESS = 'EDI_EXCEPTION'
--AND TO_DATE(PROCESS_LOAD_DATE) = CURRENT_DATE;  
DELETE FROM OW_LAO.FT_LAO_SALES_DEDUCTION_HISTORICO 
WHERE SOURCE_PROCESS = 'EDI_EXCEPTION' 
AND (TO_DATE(PROCESS_LOAD_DATE), SOURCE_PROCESS, SOURCE,AP2,COMPANY_CODE ) IN
(SELECT DISTINCT TO_DATE(PROCESS_LOAD_DATE), SOURCE_PROCESS, SOURCE,AP2,COMPANY_CODE 
FROM OW_LAO.FT_LAO_SALES_DEDUCTION_DAILY_EXCEPTION);
-- FAZ O INSERT DOS DADOS SEMANAIS PARA TABELA HISTORICA.
INSERT INTO OW_LAO.FT_LAO_SALES_DEDUCTION_HISTORICO 
SELECT * FROM OW_LAO.FT_LAO_SALES_DEDUCTION_DAILY_EXCEPTION;
END