CREATE PROCEDURE OW_LAO.PROC_LAO_DELIVERY_MODE_DIM_UPDATE
LANGUAGE SQLSCRIPT AS
	BEGIN 
		MERGE INTO 
		 	OW_LAO.DIM_LAO_DELIVERY_MODE_MAPPING_CONTROL_TOWER		AS A
		USING 
			OW_LAO.RAW_LAO_DELIVERY_MODE_MAPPING_CONTROL_TOWER 	AS B 
		ON 		A.SUBSIDIARY			= B.SUBSIDIARY
			AND A.SHIPPING_METHOD 		= B.SHIPPING_METHOD
		WHEN MATCHED AND A.ACTIVE = FALSE OR A.ACTIVE IS NULL
		 THEN UPDATE SET
		 	A.DELIVERY_MODE			= B.DELIVERY_MODE,
			A.UPDATED_TIMESTAMP		= CURRENT_TIMESTAMP,
			A.ACTIVE 				= TRUE,
			A.REPROCESSING			= TRUE
		 WHEN NOT MATCHED THEN INSERT(
		 	SUBSIDIARY,
		 	DELIVERY_MODE,
		 	SHIPPING_METHOD,
		 	INSERTED_TIMESTAMP,
		 	ACTIVE,
		 	REPROCESSING
		 )
		 VALUES (
		 	B.SUBSIDIARY,
		 	B.DELIVERY_MODE,
		 	B.SHIPPING_METHOD,
		 	CURRENT_TIMESTAMP, 
		 	TRUE,
		 	TRUE
		);
		/*-------------------------------------------------------------------------------------------------*/
		--Delete
		UPDATE
			OW_LAO.DIM_LAO_DELIVERY_MODE_MAPPING_CONTROL_TOWER A	
		SET
			ACTIVE 				= FALSE,
			REPROCESSING 		= FALSE,
			UPDATED_TIMESTAMP 	= CURRENT_TIMESTAMP
		FROM
			OW_LAO.DIM_LAO_DELIVERY_MODE_MAPPING_CONTROL_TOWER A
		WHERE
			NOT EXISTS(
				SELECT 
					1
				FROM
					OW_LAO.RAW_LAO_DELIVERY_MODE_MAPPING_CONTROL_TOWER B
				WHERE 
					A.SUBSIDIARY 				= B.SUBSIDIARY
					AND A.SHIPPING_METHOD  		= B.SHIPPING_METHOD
			)
		AND ACTIVE = TRUE;
	END