CREATE PROCEDURE OW_LAO.PROC_ODS_NUBIMETRICS_SALES_LISTINGS_CHILE
 LANGUAGE SQLSCRIPT AS
 BEGIN
 
      INSERT INTO   OW_LAO.RAW_NUBIMETRICS_SALES_LISTINGS  (
SELECT 
CATEGORYID,
CATEGORYLEVEL1,
CATEGORYLEVEL2,
CATEGORYLEVEL3,
CATEGORYLEVEL4,
CATEGORYLEVEL5,
CATEGORYLEVEL6,
CATEGORYLEVEL7,
CATEGORYPATH,
SITE,
LISTINGTITLE,
SELLERNAME,
SELLERCATEGORY,
NONPROFESSIONALSELLER,
PROFESSIONALSELLER,
FINALPRICELOCALCURRENCY,
FINALPRICEUSD,
ORIGINALPRICELOCALCURRENCY,
CURRENCY,
SALESUNITS,
SALESLOCALCURRENCY,
SALESUSD,
EXCHANGERATEUSD,
LISTINGTYPE,
LISTINGPICTURE,
LISTINGLINK,
DEALSTATUS,
NEWITEM,
USEDITEM,
ITEMCONDITION,
CASE WHEN ACCEPTSMERCADOPAGO = 'true' THEN TRUE ELSE false END AS ACCEPTSMERCADOPAGO,
SELLERSTATE,
SELLERCITY,
OFFICIALSTOREID,
OFFICIALSTORENAME,
CASE WHEN OFFERSFREESHIPPING = 'true'  THEN TRUE ELSE false END  AS OFFERSFREESHIPPING,
CASE WHEN OFFERSMERCADOENVIOS = 'true' THEN TRUE ELSE false END AS OFFERSMERCADOENVIOS,
PERIOD,
BRAND,
CANCELLATIONSUNITS,
CANCELLATIONSLOCALCURRENCY,
CANCELLATIONSUSD,
COUNTRY,
SUBSIDIARY_ID,
CONTINUATIONTOKEN,
INSERT_DATE,
UPDATE_DATE
FROM "OW_LAO"."TMP_RAW_NUBIMETRICS_SALES_LISTINGS_CHILE" 
)
;
DELETE FROM OW_LAO.ODS_NUBIMETRICS_SALES_LISTINGS 
WHERE COUNTRY = 'Chile'
AND CAST(PERIOD AS DATE) >= ADD_MONTHS(TO_DATE(TO_VARCHAR(CURRENT_DATE, 'YYYY-MM') || '-01', 'YYYY-MM-DD'), -1)
AND CAST(PERIOD AS DATE) <  ADD_MONTHS(TO_DATE(TO_VARCHAR(CURRENT_DATE, 'YYYY-MM') || '-01', 'YYYY-MM-DD'), 1)
;
 INSERT INTO  OW_LAO.ODS_NUBIMETRICS_SALES_LISTINGS  (
 
 SELECT  
 
 CATEGORYID,
CATEGORYLEVEL1,
CATEGORYLEVEL2,
CATEGORYLEVEL3,
CATEGORYLEVEL4,
CATEGORYLEVEL5,
CATEGORYLEVEL6,
CATEGORYLEVEL7,
CATEGORYPATH,
SITE,
LISTINGTITLE,
SELLERNAME,
SELLERCATEGORY,
NONPROFESSIONALSELLER,
PROFESSIONALSELLER,
FINALPRICELOCALCURRENCY,
FINALPRICEUSD,
ORIGINALPRICELOCALCURRENCY,
CURRENCY,
SALESUNITS,
SALESLOCALCURRENCY,
SALESUSD,
EXCHANGERATEUSD,
LISTINGTYPE,
LISTINGPICTURE,
LISTINGLINK,
DEALSTATUS,
NEWITEM,
USEDITEM,
ITEMCONDITION,
ACCEPTSMERCADOPAGO,
SELLERSTATE,
SELLERCITY,
OFFICIALSTOREID,
OFFICIALSTORENAME,
OFFERSFREESHIPPING,
OFFERSMERCADOENVIOS,
PERIOD,
BRAND,
CANCELLATIONSUNITS,
CANCELLATIONSLOCALCURRENCY,
CANCELLATIONSUSD,
COUNTRY,
SUBSIDIARY_ID ,
CURRENT_TIMESTAMP AS  INSERT_DATE,
CURRENT_TIMESTAMP AS  UPDATE_DATE
 
 FROM OW_LAO.RAW_NUBIMETRICS_SALES_LISTINGS A
WHERE 
  A.COUNTRY = 'Chile'
  AND (A.PERIOD,A.COUNTRY, LEFT (A.INSERT_DATE,13)) IN (
    SELECT DISTINCT  B.PERIOD,B.COUNTRY , max (LEFT (b.INSERT_DATE,13) )  
    FROM OW_LAO.RAW_NUBIMETRICS_SALES_LISTINGS B
    WHERE 
      B.COUNTRY = 'Chile'
   GROUP BY B.PERIOD,B.COUNTRY 
  )
 and not exists(
		                                select 1
		                                  from  OW_LAO.ODS_NUBIMETRICS_SALES_LISTINGS AA
		                                  where aa.PERIOD         = a.PERIOD
                                            and aa.COUNTRY        = a.COUNTRY
                                       
                           )
)
;
END 