/***********************************************************************************************
CREATED BY : Luciano Mariani
CREATION DATE : 2023-05-29
ALTER DATE : 2023-08-10
VERSION: 1.0
-- CALL OW_LAO.PROC_FT_D2C_BIZOVERVIEW;
-- SELECT * FROM OW_LAO.TF_D2C_MEDALLIA_NPS_KPI
-- SELECT * FROM OW_LAO.TF_D2C_GLOBAL_BI_TRAFFIC_KPI
-- SELECT * FROM OW_LAO.TF_D2C_GLOBAL_BI_SALES_KPI
-- SELECT * FROM OW_LAO.TF_D2C_GSCM_AP1_ACCURACY_KPI
***********************************************************************************************/
CREATE PROCEDURE OW_LAO.PROC_FT_D2C_BIZOVERVIEW
LANGUAGE SQLSCRIPT AS
BEGIN
	
	/*********************************************
		ODS_MEDALLIA_EXPRESS_REPORT
		SELECT * FROM OW_LAO.TF_D2C_MEDALLIA_NPS_KPI
	/*********************************************/
	IF EXISTS(
		SELECT TABLE_NAME
		FROM SYS.TABLES
		WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TF_D2C_MEDALLIA_NPS_KPI'
	)
	THEN
		DROP TABLE OW_LAO.TF_D2C_MEDALLIA_NPS_KPI;
	END IF;
	
	--CRIA NOVA TATBELA 
	CREATE COLUMN TABLE OW_LAO.TF_D2C_MEDALLIA_NPS_KPI AS (	
		-- NOVA TABELA EXPRESS
		SELECT
					 MD.SUBSIDIARY
					,TO_DATE(MD.RESPONSE_DATE_LOCAL) AS DATE_REF
					,CL.YYYYWW AS YYYYWW
					,CL.YYYYMM AS YYYYMM
					,CL.YYYYQQ AS YYYYQQ
					,MD.NEW_FACTOR_WITH_BIGGEST_IMPACT_COMBINED AS NPS
					,SUM(CASE WHEN UPPER(TRIM(MD.NPS_SEGMENT)) = 'PROMOTER' THEN 1 ELSE 0 END) AS "PROMOTER"
					,SUM(CASE WHEN UPPER(TRIM(MD.NPS_SEGMENT)) = 'DETRACTOR' THEN 1 ELSE 0 END) AS "DETRACTOR"
					,SUM(CASE WHEN UPPER(TRIM(MD.NPS_SEGMENT)) = 'PASSIVE' THEN 1 ELSE 0 END) AS "PASSIVE"				
					,TARGET.TARGET_NPS/100 AS TARGET	
					
					,CURRENT_TIMESTAMP AS KPI_LAST_UPDATE			
				FROM OW_LAO.ODS_LAO_MEDALLIA_EXPRESS_REPORT MD
					LEFT JOIN OW_MD.DIM_CALENDAR CL 
						ON 1=1
						AND TO_DATE(MD.RESPONSE_DATE_LOCAL) = CL.YYYYMMDD
					LEFT JOIN OW_MD.ODS_MEDALIA_TARGET_NPS AS TARGET
						ON 1=1
						AND MD.SUBSIDIARY = TARGET.SUBSIDIARY 
						AND MD.NEW_FACTOR_WITH_BIGGEST_IMPACT_COMBINED = TARGET.FACTOR_IMPACT 
						AND CL.YYYYWW = CONCAT(CAST(TARGET.YEAR AS VARCHAR),CASE WHEN LENGTH(REPLACE(TARGET.WEEK,'W','')) = 1 THEN CONCAT('0',REPLACE(TARGET.WEEK,'W','')) ELSE REPLACE(TARGET.WEEK,'W','') END) -- Ajuste do ano/week para o formato da tabela para o join
				WHERE 1=1
					AND MD.NEW_FACTOR_WITH_BIGGEST_IMPACT_COMBINED IS NOT NULL
					AND UPPER(SUSPICIOUS_RECORD) = 'NO'
					AND TO_DATE(MD.RESPONSE_DATE_LOCAL) > '2023-08-23'
				GROUP BY
					 MD.SUBSIDIARY
					,TO_DATE(MD.RESPONSE_DATE_LOCAL) --AS DATE_REF
					,CL.YYYYWW --AS YYYYWW
					,CL.YYYYMM --AS YYYYMM
					,CL.YYYYQQ --AS YYYYQQ
					,MD.NEW_FACTOR_WITH_BIGGEST_IMPACT_COMBINED --AS NPS
					,TARGET.TARGET_NPS/100		
				
		UNION ALL
		
		-- ANTIGA TABELA EXPRESS
		SELECT
					 MD.SUBSIDIARY
					,TO_DATE(MD.RESPONSE_DATE_LOCAL) AS DATE_REF
					,CL.YYYYWW AS YYYYWW
					,CL.YYYYMM AS YYYYMM
					,CL.YYYYQQ AS YYYYQQ
					,MD.NEW_FACTOR_WITH_BIGGEST_IMPACT_COMBINED AS NPS
					,SUM(CASE WHEN UPPER(TRIM(MD.NPS_SEGMENT)) = 'PROMOTER' THEN 1 ELSE 0 END) AS "PROMOTER"
					,SUM(CASE WHEN UPPER(TRIM(MD.NPS_SEGMENT)) = 'DETRACTOR' THEN 1 ELSE 0 END) AS "DETRACTOR"
					,SUM(CASE WHEN UPPER(TRIM(MD.NPS_SEGMENT)) = 'PASSIVE' THEN 1 ELSE 0 END) AS "PASSIVE"				
					,TARGET.TARGET_NPS/100 AS TARGET	
					
					,CURRENT_TIMESTAMP AS KPI_LAST_UPDATE			
				FROM OW_LAO.ODS_MEDALLIA_EXPRESS_REPORT MD
					LEFT JOIN OW_MD.DIM_CALENDAR CL 
						ON 1=1
						AND TO_DATE(MD.RESPONSE_DATE_LOCAL) = CL.YYYYMMDD
					LEFT JOIN OW_MD.ODS_MEDALIA_TARGET_NPS AS TARGET
						ON 1=1
						AND MD.SUBSIDIARY = TARGET.SUBSIDIARY 
						AND MD.NEW_FACTOR_WITH_BIGGEST_IMPACT_COMBINED = TARGET.FACTOR_IMPACT 
						AND CL.YYYYWW = CONCAT(CAST(TARGET.YEAR AS VARCHAR),CASE WHEN LENGTH(REPLACE(TARGET.WEEK,'W','')) = 1 THEN CONCAT('0',REPLACE(TARGET.WEEK,'W','')) ELSE REPLACE(TARGET.WEEK,'W','') END) -- Ajuste do ano/week para o formato da tabela para o join
				WHERE 1=1
					AND MD.NEW_FACTOR_WITH_BIGGEST_IMPACT_COMBINED IS NOT NULL
					AND UPPER(SUSPICIOUS_RECORD) = 'NO'
					AND TO_DATE(MD.RESPONSE_DATE_LOCAL) <= '2023-08-23'
				GROUP BY
					 MD.SUBSIDIARY
					,TO_DATE(MD.RESPONSE_DATE_LOCAL) --AS DATE_REF
					,CL.YYYYWW --AS YYYYWW
					,CL.YYYYMM --AS YYYYMM
					,CL.YYYYQQ --AS YYYYQQ
					,MD.NEW_FACTOR_WITH_BIGGEST_IMPACT_COMBINED --AS NPS
					,TARGET.TARGET_NPS/100
	);
	
	/*********************************************
		ODS_GLOBAL_BI_TRAFFIC_ALL
		SELECT * FROM OW_LAO.TF_D2C_GLOBAL_BI_TRAFFIC_KPI
	/*********************************************/
	IF EXISTS(
		SELECT TABLE_NAME
		FROM SYS.TABLES
		WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TF_D2C_GLOBAL_BI_TRAFFIC_KPI'
	)
	THEN
		DROP TABLE OW_LAO.TF_D2C_GLOBAL_BI_TRAFFIC_KPI;
	END IF;
	
	--CRIA NOVA TATBELA 
	CREATE COLUMN TABLE OW_LAO.TF_D2C_GLOBAL_BI_TRAFFIC_KPI AS (	
		SELECT
			GT.SUBSIDIARY
			,TO_DATE(GT."YEAR" ||'-' || GT."MONTH" || '-' || GT."DAY") AS DATE_REF
			,CL.YYYYWW AS YYYYWW
			,CL.YYYYMM AS YYYYMM
			,CL.YYYYQQ AS YYYYQQ
			,GT.CHANNEL_GROUP_1 AS CHANNEL_GROUP
			,SUM( CAST( ".COM_Visit" AS DECIMAL(18,2))) AS SHOPPER_VISIT_QTY
			,SUM(CAST(GT.NET_REVENUE AS DECIMAL(18,2)))AS NET_REVENUE_USD
			,SUM(GT.NET_ORDERS_CURRENT) AS NET_ORDERS_QTY
			,SUM(GT.GROSS_ORDER) AS GROSS_ORDER_QTY
			
			,CURRENT_TIMESTAMP AS KPI_LAST_UPDATE		
		FROM OW_LAO.ODS_GLOBAL_BI_TRAFFIC_ALL GT
			LEFT JOIN OW_MD.DIM_CALENDAR CL ON CL.YYYYMMDD = TO_DATE(GT."YEAR" ||'-' || GT."MONTH" || '-' || GT."DAY")
		WHERE UPPER(GT.CHANNEL_GROUP_1) <> 'TOTAL'
		GROUP BY
			 GT.SUBSIDIARY
			,TO_DATE(GT."YEAR" ||'-' || GT."MONTH" || '-' || GT."DAY") --AS DATE_REF
			,CL.YYYYWW -- AS YYYYWW
			,CL.YYYYMM -- AS YYYYMM
			,CL.YYYYQQ -- AS YYYYQQ
			,GT.CHANNEL_GROUP_1
	);
	
	/*********************************************
		ODS_GLOBAL_BI_SALES
		SELECT * FROM OW_LAO.TF_D2C_GLOBAL_BI_SALES_KPI
	*********************************************/
	IF EXISTS(
		SELECT TABLE_NAME
		FROM SYS.TABLES
		WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TF_D2C_GLOBAL_BI_SALES_KPI'
	)
	THEN
		DROP TABLE OW_LAO.TF_D2C_GLOBAL_BI_SALES_KPI;
	END IF;
	
	--CRIA NOVA TATBELA 
	CREATE COLUMN TABLE OW_LAO.TF_D2C_GLOBAL_BI_SALES_KPI AS (
		SELECT
			 GS.SUBSIDIARY		
			,TO_DATE(GS.ORDER_DATE) AS DATE_REF
			,CL.YYYYWW AS YYYYWW
			,CL.YYYYMM AS YYYYMM
			,CL.YYYYQQ AS YYYYQQ
			,GS.SKU
			,PD."DIVISION" AS PDROD_DIVISION
			,PD.PRODUCT_GROUP_1 AS PDROD_PRODUCT_GROUP 
			,PD.PRODUCT_1 AS PDROD_PRODUCT 
			,PD.ATTB01 AS PROD_ATTB_1 
			,PD.SEDA_BU_ESTORE
			,PD.SEDA_DIVISION_ESTORE
			,PD.SEDA_CATEGORY_ESTORE
			,PD.SEDA_FAMILY_ESTORE
			,PD.SEDA_DESC_ESTORE				
			,GS.BIZ_TYPE -- CASE WHEN GS.BIZ_TYPE IS NOT NULL THEN GS.BIZ_TYPE ELSE 'UnMapped' END AS BIZ_TYPE
			,GS.AUDIENCE_TYPE
			
			,SUM(CAST(GS.TRANSACTION_NET_REVENUE AS DECIMAL(18,2))) AS NET_REVENUE_USD
			,SUM(GS.NET_QUANTITY) AS NET_QTY
			,SUM(CAST(GS.TRANSACTION_GROSS_REVENUE AS DECIMAL(18,2))) AS GROSS_REVENUE_USD
			,SUM(GS.GROSS_ORDERS) AS GROSS_ORDERS_QTY
			,SUM(CASE WHEN UPPER(GS.TRADE_IN_ORDER) = 'TRUE' THEN GS.TRANSACTION_NET_REVENUE END) AS TRADE_IN_NET_AMOUNT
			,SUM(CASE WHEN UPPER(GS.TRADE_IN_ORDER) = 'TRUE' THEN GS.NET_QUANTITY END) AS TRADE_IN_NET_QTY
			,SUM(CASE WHEN UPPER(GS.TRADE_IN_ELIGIBLE) = 'TRUE' THEN GS.TRANSACTION_NET_REVENUE END) AS TRADE_IN_ELIGIBLE_NET_AMOUNT
			,SUM(CASE WHEN UPPER(GS.TRADE_IN_ELIGIBLE) = 'TRUE' THEN GS.NET_QUANTITY END) AS TRADE_IN_ELIGIBLE_NET_QTY
			,SUM(CASE WHEN UPPER(GS.SCPLUS_ORDER) = 'TRUE' THEN GS.TRANSACTION_NET_REVENUE END) AS CARE_PLUS_NET_AMOUNT
			,SUM(CASE WHEN UPPER(GS.SCPLUS_ORDER) = 'TRUE' THEN GS.NET_QUANTITY END) AS CARE_PLUS_NET_QTY
			,CURRENT_TIMESTAMP AS KPI_LAST_UPDATE
		FROM OW_LAO.ODS_GLOBAL_BI_SALES GS
			LEFT JOIN OW_MD.DIM_CALENDAR CL ON TO_DATE(GS.ORDER_DATE) = CL.YYYYMMDD
			LEFT JOIN OW_MD.DIM_PRODUCT PD ON PD.SKU = GS.SKU
		GROUP BY
			 GS.SUBSIDIARY		
			,TO_DATE(GS.ORDER_DATE) --AS DATE_REF
			,CL.YYYYWW --AS YYYYWW
			,CL.YYYYMM --AS YYYYMM
			,CL.YYYYQQ --AS YYYYQQ
			,GS.SKU
			,PD."DIVISION" -- AS PDROD_DIVISION
			,PD.PRODUCT_GROUP_1 -- AS PDROD_PRODUCT_GROUP 
			,PD.PRODUCT_1 -- AS PDROD_PRODUCT 
			,PD.ATTB01 -- AS PROD_ATTB_1 
			,PD.SEDA_BU_ESTORE
			,PD.SEDA_DIVISION_ESTORE
			,PD.SEDA_CATEGORY_ESTORE
			,PD.SEDA_FAMILY_ESTORE
			,PD.SEDA_DESC_ESTORE				
			,GS.BIZ_TYPE -- CASE WHEN GS.BIZ_TYPE IS NOT NULL THEN GS.BIZ_TYPE ELSE 'UnMapped' END --AS BIZ_TYPE
			,GS.AUDIENCE_TYPE
	);
	/*********************************************
		TF_D2C_GLOBAL_BI_CRV_KPI
		SELECT TOP 200 * FROM OW_LAO.TF_D2C_GLOBAL_BI_CRV_KPI
	/*********************************************/
	IF EXISTS(
		SELECT TABLE_NAME
		FROM SYS.TABLES
		WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TF_D2C_GLOBAL_BI_CRV_KPI'
	)
	THEN
		DROP TABLE OW_LAO.TF_D2C_GLOBAL_BI_CRV_KPI;
	END IF;
	
	--CRIA NOVA TATBELA TF_D2C_GLOBAL_BI_CRV_KPI
	CREATE COLUMN TABLE OW_LAO.TF_D2C_GLOBAL_BI_CRV_KPI AS (	
		SELECT 
			 TF.SUBSIDIARY
			,TF.YYYYWW
			,TF.YYYYMM
			,TF.YYYYQQ
			,TF.SHOPPER_VISIT_CURRENT
			,SL.NET_REVENUE_USD
			,SL.NET_QTY
			,SL.GROSS_REVENUE_USD
			,SL.GROSS_ORDERS_QTY
			,SL.TRADE_IN_NET_AMOUNT
			,SL.TRADE_IN_NET_QTY
			,SL.TRADE_IN_ELIGIBLE_NET_AMOUNT
			,SL.TRADE_IN_ELIGIBLE_NET_QTY
			,SL.CARE_PLUS_NET_AMOUNT
			,SL.CARE_PLUS_NET_QTY
			
			,CURRENT_TIMESTAMP AS KPI_LAST_UPDATE
		FROM (
			SELECT
				 SUBSIDIARY
				,CL.YYYYWW AS YYYYWW
				,CL.YYYYMM AS YYYYMM
				,CL.YYYYQQ AS YYYYQQ
				,SUM(CAST(".COM_Visit" AS DECIMAL(18,2))) AS SHOPPER_VISIT_CURRENT
			FROM OW_LAO.ODS_GLOBAL_BI_TRAFFIC_ALL GT
				LEFT JOIN OW_MD.DIM_CALENDAR CL ON CL.YYYYMMDD = TO_DATE(GT."YEAR" ||'-' || GT."MONTH" || '-' || GT."DAY")
			WHERE UPPER(GT.CHANNEL_GROUP_1) <> 'TOTAL'
			GROUP BY
				 SUBSIDIARY
				,CL.YYYYWW
				,CL.YYYYMM
				,CL.YYYYQQ
		) TF
		INNER JOIN(
			SELECT
				 GS.SUBSIDIARY		
				,CL.YYYYWW AS YYYYWW
				,CL.YYYYMM AS YYYYMM
				,CL.YYYYQQ AS YYYYQQ
				,SUM(CAST(GS.TRANSACTION_NET_REVENUE AS DECIMAL(18,2))) AS NET_REVENUE_USD
				,SUM(GS.NET_QUANTITY) AS NET_QTY
				,SUM(CAST(GS.TRANSACTION_GROSS_REVENUE AS DECIMAL(18,2))) AS GROSS_REVENUE_USD
				,SUM(GS.GROSS_ORDERS) AS GROSS_ORDERS_QTY
				,SUM(CASE WHEN UPPER(GS.TRADE_IN_ORDER) = 'TRUE' THEN GS.TRANSACTION_NET_REVENUE END) AS TRADE_IN_NET_AMOUNT
				,SUM(CASE WHEN UPPER(GS.TRADE_IN_ORDER) = 'TRUE' THEN GS.NET_QUANTITY END) AS TRADE_IN_NET_QTY
				,SUM(CASE WHEN UPPER(GS.TRADE_IN_ELIGIBLE) = 'TRUE' THEN GS.TRANSACTION_NET_REVENUE END) AS TRADE_IN_ELIGIBLE_NET_AMOUNT
				,SUM(CASE WHEN UPPER(GS.TRADE_IN_ELIGIBLE) = 'TRUE' THEN GS.NET_QUANTITY END) AS TRADE_IN_ELIGIBLE_NET_QTY
				,SUM(CASE WHEN UPPER(GS.SCPLUS_ORDER) = 'TRUE' THEN GS.TRANSACTION_NET_REVENUE END) AS CARE_PLUS_NET_AMOUNT
				,SUM(CASE WHEN UPPER(GS.SCPLUS_ORDER) = 'TRUE' THEN GS.NET_QUANTITY END) AS CARE_PLUS_NET_QTY
			FROM OW_LAO.ODS_GLOBAL_BI_SALES GS
				LEFT JOIN OW_MD.DIM_CALENDAR CL ON TO_DATE(GS.ORDER_DATE) = CL.YYYYMMDD
			GROUP BY
				 GS.SUBSIDIARY		
				,CL.YYYYWW
				,CL.YYYYMM
				,CL.YYYYQQ
		) SL ON TF.SUBSIDIARY = SL.SUBSIDIARY
				AND TF.YYYYWW = SL.YYYYWW
				AND TF.YYYYMM = SL.YYYYMM
				AND TF.YYYYQQ = SL.YYYYQQ
	);
	
	/*********************************************
		OW_LAO.ODS_GSCM_AP1_ACCURACY	
		SELECT * FROM OW_LAO.TF_D2C_GSCM_AP1_ACCURACY_KPI
	*********************************************/
	IF EXISTS(
		SELECT TABLE_NAME
		FROM SYS.TABLES
		WHERE SCHEMA_NAME = 'OW_LAO' AND TABLE_NAME = 'TF_D2C_GSCM_AP1_ACCURACY_KPI'
	)
	THEN
		DROP TABLE OW_LAO.TF_D2C_GSCM_AP1_ACCURACY_KPI;
	END IF;
	
	--CRIA NOVA TATBELA 
	CREATE COLUMN TABLE OW_LAO.TF_D2C_GSCM_AP1_ACCURACY_KPI AS (
		SELECT --TOP 100
			 A.SALES_SUBSIDIARY AS SUBSIDIARY
			,CL.YYYYMMDD AS DATE_REF
			,CL.YYYYWW
			,CL.YYYYMM
			,CL.YYYYQQ	
			,A.DIVISION -- CASE A.DIVISION WHEN 'MOBILE' THEN 'MOBILE' WHEN 'TV' THEN 'TV' WHEN 'REF' THEN 'REF/WM' WHEN 'WM' THEN 'REF/WM' END AS DIVISION
			,AVG(CAST(A.FA_1_8W AS DECIMAL(18,2))) AS AP1_ACCURACY
		
			,CURRENT_TIMESTAMP AS KPI_LAST_UPDATE
		FROM OW_LAO.ODS_GSCM_AP1_ACCURACY A
			LEFT JOIN (
				SELECT
					 YYYYWW 
					,YYYYMM
					,YYYYQQ
					,MIN(YYYYMMDD) AS YYYYMMDD
				FROM OW_MD.DIM_CALENDAR
				GROUP BY
					 YYYYWW 
					,YYYYMM
					,YYYYQQ
			) CL ON REPLACE(A.YEAR_WEEK,'.','') = CL.YYYYWW
		WHERE 
			UPPER(A.SALES_SUBSIDIARY) NOT IN('LATIN AMERICA','SALES SUBSIDIARY')
			--AND UPPER(A.DIVISION) IN('MOBILE','TV','REF', 'WM')
			AND A.ACCOUNT IN (
				 'ON_E-STORE_D2C'
				,'E-STORE_D2C'
				,'D2C E-STORE'
				,'ESTORE'
				,'E-STORE'
			)	
		GROUP BY
			 A.SALES_SUBSIDIARY -- AS SUBSIDIARY
			,CL.YYYYMMDD -- AS DATE_REF
			,CL.YYYYWW
			,CL.YYYYMM
			,CL.YYYYQQ	
			,A.DIVISION
	);
	/*********************************************
		OW_LAO.ODS_GLOBAL_BI_STOCKOUT	
	
	SELECT	
		 SC.SUBSIDIARY
		,SC.OBSERVATION_DATE AS DATE_REF
		,SC.SKU
		,SC.DIVISION
		,COUNT(CASE WHEN UPPER(SC.STATUS) = 'OUTOFSTOCK' THEN SC.SKU END) AS OUTOFSTOCK
		,COUNT(SC.SKU) AS TOTAL
	FROM OW_LAO.ODS_GLOBAL_BI_STOCKOUT SC
	*********************************************/
END;
