CREATE PROCEDURE OW_LAO.PROC_MONITORING_SALES_CONTROL_TOWER_TABLE_ALERT_ORDERS
-- OW_LAO.PROC_MONITORING_SALES_CONTROL_TOWER_TABLE_ALERT_ORDERS
LANGUAGE SQLSCRIPT AS 
BEGIN 
	
	DROP TABLE OW_LAO.TMP_MONITORING_SALES_CONTROL_TOWER_TABLE_ALERT_HOUR;
	DROP TABLE OW_LAO.TMP_MONITORING_SALES_CONTROL_TOWER_TABLE_ALERT_ORDERS;
CREATE COLUMN TABLE OW_LAO.TMP_MONITORING_SALES_CONTROL_TOWER_TABLE_ALERT_HOUR AS (
SELECT  
  SUBSIDIARY,
  COUNTRY,
  MAX(po_hour) AS last_po_hour,
  MAX(PO_INSERT_DATE) AS Last_Insert_Time,
  CURRENT_TIMESTAMP AS "CURRENT/TIME",
  ROUND(SECONDS_BETWEEN(MAX(PO_INSERT_DATE), CURRENT_TIMESTAMP) / 3600) AS No_Sales_Inserted_Hour 
  
FROM OW_LAO.ODS_SALES_CONTROL_TOWER_TABLE  
WHERE PO_DATE = CURRENT_DATE
AND PO_PLATAFORM_DATASOURCE NOT IN ('ow_lao.ods_orders_visuar','u_prj_ecom.ft_ecom_order','u_prj_ecom.ods_diggit_ecom_orders')
 
GROUP BY 
  SUBSIDIARY,
  COUNTRY 
  
  ORDER BY
  ROUND(SECONDS_BETWEEN(MAX(PO_INSERT_DATE), CURRENT_TIMESTAMP) / 3600)
 
  )
  
  ;
 
 
  
CREATE COLUMN TABLE OW_LAO.TMP_MONITORING_SALES_CONTROL_TOWER_TABLE_ALERT_ORDERS AS (
    
 SELECT 
SUBSIDIARY,
COUNTRY,
last_po_hour,
LAST_INSERT_TIME,
"CURRENT/TIME",
CASE 
	WHEN  COUNTRY = 'Colombia' THEN  2  
	WHEN  COUNTRY = 'Mexico'   THEN  3
    WHEN  COUNTRY = 'Peru'     THEN  2
    WHEN  COUNTRY = 'Chile'    THEN  1
     ELSE  0
END AS TIMEZONE,
NO_SALES_INSERTED_HOUR,
CASE 
	WHEN  NO_SALES_INSERTED_HOUR >= 2 THEN 'NOT OK'
    ELSE 'OK'
END AS STATUS 
FROM OW_LAO.TMP_MONITORING_SALES_CONTROL_TOWER_TABLE_ALERT_HOUR 
ORDER BY 
NO_SALES_INSERTED_HOUR
 ); 
 
 
END
 