CREATE PROCEDURE OW_LAO.PROC_INSERT_SALES_FROM_ODS 
AS 
BEGIN
	
	TRUNCATE TABLE OW_LAO.ODS_EQUALS_SALES;
	
	INSERT INTO OW_LAO.ODS_EQUALS_SALES (
    ID_UNICO_ERP,
    ID_UNICO_EQUALS,
    ADQUIRENTE,
    PRODUTO,
    ADQ_PRODUTO,
    ESTABELECIMENTO,
    CATEGORIA,
    BANDEIRA,
    LOTE,
    NR_TERMINAL,
    MEIO_DE_CAPTURA,
    MODO_DE_ENTRADA,
    DATA,
    DATA_CAPTURA,
    HORA,
    NUMERO_CARTAO,
    NSU,
    TID,
    NR_SEQUENCIA,
    PARCELA,
    QTD_VENDAS,
    VENDAS_LOTE_UNICO,
    NR_REFERENCIA_PEDIDO,
    VALOR_BRUTO,
    VALOR_COMISSAO,
    TAXA,
    TAXA_DO_CONTRATO,
    TARIFA_PRATICADA,
    TARIFA_CONTRATADA,
    VALOR_LIQUIDO,
    VALOR_REJEITADO,
    SITUACAO,
    DATA_SITUACAO,
    CONCILIACAO,
    M_JUSTIFICADA,
    DT_CONCIL_JUSTIF,
    MOV_INTEGRADO,
    ORDER_ID,
    SEQUENCE 
)
WITH VTEX AS (
SELECT DISTINCT '' TID , ORDER_ID , SEQUENCE FROM OW_LAO.TF_D2C_NERP_SALES
UNION
SELECT DISTINCT TID ,ORDER_ID , SEQUENCE FROM OW_LAO.TF_D2C_PAYMENT_ITAU 
)	
SELECT DISTINCT
    A.IDUNICOERP,
    A.IDUNICOEQUALS,
    A.ADQUIRENTE,
    A.PRODUTO,
    A.ADQPRODUTO,
    A.ESTABELECIMENTO,
    A.CATEGORIADOESTABELECIMENTO,
    A.BANDEIRA,
    A.LOTE,
    A.NRTERMINAL,
    A.MEIOCAPTURA,
    A.MODOENTRADA,
    TO_DATE(A.DATA, 'YYYY-MM-DD'),
    TO_DATE(A.DATACAPTURA, 'YYYY-MM-DD'),
    A.HORA,
    A.NUMEROCARTAO,
    A.NSU,
    A.TID,
    A.NRSEQUENCIA,
    A.PARCELA,
    A.QTDVENDAS,
    A.LOTEUNICO,
    A.NRREFERENCIAPEDIDO,
    REPLACE(REPLACE(TO_DECIMAL(A.VALORBRUTO, 10,2),',',''),'.',',') ,
    REPLACE(REPLACE(TO_DECIMAL(A.VALORCOMISSAO, 10,2),',',''),'.',',') ,
    A.TAXA,
    A.TAXACONTRATO,
    A.TARIFAPRATICADA,
    A.TARIFACONTRATADA,
    REPLACE(REPLACE(TO_DECIMAL(A.VALORLIQUIDO, 10,2),',',''),'.',',') ,
    REPLACE(REPLACE(TO_DECIMAL(A.VALORREJEITADO, 10,2),',',''),'.',',') ,
    A.SITUACAO,
    TO_DATE(A.DATASITUACAO, 'YYYY-MM-DD'),
    A.CONCILIACAO,
    A.MJUSTIFICAtiva,
    TO_DATE(A.DATACONCILIACAO, 'YYYY-MM-DD'),
    A.MOVINTEGRADO,
    COALESCE(B.ORDER_ID,C.ORDER_ID,D.ORDER_ID) ORDER_ID,
    COALESCE(B.SEQUENCE,C.SEQUENCE,D.SEQUENCE) SEQUENCE
FROM OW_LAO.TMP_EQUALS_SALES A LEFT JOIN VTEX B ON A.NRREFERENCIAPEDIDO = B.SEQUENCE
                               LEFT JOIN VTEX C ON A.IDUNICOERP = C.ORDER_ID
                               LEFT JOIN VTEX D ON A.TID =D.TID
 WHERE UPPER(A.ADQUIRENTE) IN ('NUPAY','MERCADO PAGO','REDE') ;                               
	
END;