/***********************************************************************************************
CREATED BY : Luciano Mariani
CREATION DATE : 2023-05-22
VERSION: 1.1
DESCRIPTION: Reprocess all files to ods from the older unprocessed raw to table
CALL OW_LAO.PROC_INGESTION_ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING;
SELECT * FROM OW_LAO.ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING;
SELECT MAX(LAST_TIME_PROCESSED) FROM OW_LAO.RAW_DATA_NERP_ZRSDD6A120_SALES_ORDER_TRACKING	
***********************************************************************************************/
CREATE PROCEDURE OW_LAO.PROC_INGESTION_ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING(
	--IN p_Process_all BOOLEAN DEFAULT FALSE
	 p_DATE_INI DATE DEFAULT NULL
	,P_DATE_FIM DATE DEFAULT NULL
)
LANGUAGE SQLSCRIPT as
BEGIN
	
	/****************************************************************************************
	-- REPROCESSAR TODOS OS ARQUIVOS PARA A ODS A PARTIR DA  RAW NÃO PROCESSADA MAIS ANTIGA
	****************************************************************************************/
	DECLARE v_file_name NVARCHAR(4000);
	
	-- CURSOR PASSA POR CADA ARQUIVO
	DECLARE CURSOR c_select FOR
		SELECT 
			 RANKING_PERIOD_START
			,"FILE_NAME" AS F_FILE_NAME
			--,PERIOD_START ,PERIOD_END ,GENERATED_IN ,LAST_TIME_PROCESSED ,RANKING_PERIOD_START ,RANKING_PERIOD_END ,RANKING_LAST_TIME_PROCESSED
		FROM(
			SELECT 
				  "FILE_NAME"
				--,PERIOD_START ,PERIOD_END ,GENERATED_IN ,LAST_TIME_PROCESSED 
				, PROCESSED
				, RANK() OVER (ORDER BY GENERATED_IN, PERIOD_START) AS RANKING_PERIOD_START
				--, RANK() OVER (ORDER BY GENERATED_IN, PERIOD_END) AS RANKING_PERIOD_END
				, RANK() OVER (ORDER BY LAST_TIME_PROCESSED, PERIOD_START) AS RANKING_LAST_TIME_PROCESSED
			FROM( 
				SELECT DISTINCT 
					  "FILE_NAME"
					, REPLACE(SUBSTRING("FILE_NAME",22,10),'.','-') AS PERIOD_START
					--, REPLACE(SUBSTRING("FILE_NAME",33,10),'.','-') AS PERIOD_END
					, CASE WHEN LENGTH("FILE_NAME") > 50 THEN 
						        REPLACE(SUBSTRING("FILE_NAME",44,10),'.','-') || ' ' || REPLACE(SUBSTRING("FILE_NAME",55,5),'.',':')
					 	   ELSE SUBSTRING(LAST_MODIFICATION_FILE,1,16) END AS GENERATED_IN
					, CASE WHEN LAST_TIME_PROCESSED IS NOT NULL THEN LAST_TIME_PROCESSED
						   ELSE CURRENT_TIMESTAMP END AS LAST_TIME_PROCESSED
					, CASE WHEN LAST_TIME_PROCESSED IS NOT NULL THEN 1 ELSE 0 END AS PROCESSED
				FROM OW_LAO.RAW_DATA_NERP_ZRSDD6A120_SALES_ORDER_TRACKING
				WHERE 1=1
					AND LAST_MODIFICATION_FILE BETWEEN IFNULL(:p_DATE_INI, ADD_DAYS(CURRENT_TIMESTAMP, -1)) 
												   AND IFNULL(:P_DATE_FIM, ADD_DAYS(CURRENT_TIMESTAMP, 2))
					--AND LAST_MODIFICATION_FILE < '2024-01-29 15:28:55'	-- ******** RETIRAR LINHA PARA VOLTAR A PROCESSAR ***************************		
			)
		)
		WHERE
			( PROCESSED = 0) -- NÃO PROCESSADOS  (OU)
			OR ( IFNULL(:p_DATE_INI, ADD_DAYS(CURRENT_TIMESTAMP, -1)) <> ADD_DAYS(CURRENT_TIMESTAMP, -1) ) -- PARAMETRO PASSADO
		ORDER BY
			RANKING_PERIOD_START
		;
	FOR cursorRow as c_select DO
	
		-- SETA PROXIMA ARQUIVO
		v_file_name := cursorRow.F_FILE_NAME; -- SELECT :v_file_name AS FILE_ FROM DUMMY;
		
		--*************************************************************************
		-- APAGA "SALES_DOCUMENT" DA ODS QUE ESTÃO NO NA RAW
		-- ************************************************************************
		DELETE
		FROM OW_LAO.ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING
		WHERE "SALES_DOCUMENT" IN(
			SELECT DISTINCT
				"SALES_DOCUMENT"
			FROM OW_LAO.RAW_DATA_NERP_ZRSDD6A120_SALES_ORDER_TRACKING
			WHERE "FILE_NAME" = v_file_name
		);
		
		--*************************************************************************
		-- INSERE NOVOS REGISTROS DO ARQUIVO QUE ESTÃO NA RAW E NÃO ESTÃO NA OSD
		--*************************************************************************
		INSERT INTO OW_LAO.ODS_NERP_ZRSDD6A120_SALES_ORDER_TRACKING(
			 "SALES_DOCUMENT"
			,"SALES_DOCUMENT_ITEM"
			,"SALES_DOC_TYPE"
			,"CUSTOMER_PO"
			,"SOLD_TO_PARTY"
			,"NAME"
			,"MATERIAL"
			,"ITEM_DESCR"
			,"ITEM_DIVISION"
			,"ORDER_QTY_BASE"
			,"BASE_UNIT"
			,"OPEN_QTY_BASE"
			,"SO_NET_PRICE"
			,"SO_NET_VALUE"
			,"COST"
			,"MARGIN_RATE"
			,"SO_CURR"
			,"SO_CREATE_ON"
			,"SO_CREATE_ON_TIME"
			,"FIRST_SC_DATE"
			,"SALES_ORG"
			,"DISTR_CHANNEL"
			,"DIVISION"
			,"PLANT"
			,"STOR_LOC"
			,"ACCOUNT_CODE"
			,"ACCOUNT_NAME"
			,"GC_ID_GSCM"
			,"GC_NAME"
			,"AP1_CODE"
			,"AP1_NAME"
			,"AP2_CODE"
			,"AP2_NAME"
			,"SCM_SITE_ID"
			,"TRANSPORT_ZONE"
			,"DELIVERY"
			,"DELIVERY_ITEM"
			,"DELIVERY_QTY_BASE"
			,"BASE_UNIT_1"
			,"DOCUMENT_DATE"
			,"DO_CREATE_ON"
			,"DO_CREATE_ON_TIME"
			,"SR_NO"
			,"SR_ITEM"
			,"SR_DATE"
			,"SR_TYPE"
			,"SR_TYPE_DESC"
			,"1ST_GI_NO"
			,"1ST_GI_ITEM"
			,"1ST_GI_QTY"
			,"1ST_GI_CREATE_ON"
			,"1ST_GI_CREATE_ON_TIME"
			,"2ND_GI_NO"
			,"2ND_GI_ITEM"
			,"2ND_GI_QTY"
			,"POSTING_DATE"
			,"2ND_GI_CREATE_ON"
			,"2ND_GI_CREATE_ON_TIME"
			,"BILLING_DOC"
			,"BILLING_DOC_ITEM"
			,"BILLED_QTY_BASE"
			,"BILLING_NET_VALUE"
			,"BILLING_CURR"
			,"BILLING_DATE"
			,"BILLING_CREATE_ON"
			,"BILLING_CREATE_ON_TIME"
			,"PARTIAL_DELIVERY_SEQ"
			,"STATUS"
			,"1ST_GI_DATE"
			,"DELIVERY_BLOCK"
			,"ORDER_REASON"
			,"REJECT_REASON"
			,"REJECT_REASON_1"
			,"ORDER_QTY"
			,"CONFIRMED_QTY"
			,"SPEC_PROCESSING"
			,"MAT_AVAIL_DATE"
			,"MATERIAL_GROUP"
			,"SO_LOCAL_CREATE_ON_D"
			,"DO_LOCAL_CREATE_ON_D"
			,"1ST_GI_LOCAL_CREATE"
			,"BILLING_LOCAL_CREATE"
			,"FINAL_SCH_DATE"
			,"SHIPPING_TYPE"
			
            --Alteração solicitada para acréscimo destes 4 campos 05/02/2024 
			,"SO_LOCAL_CREATE_ON_T"
			,"DO_LOCAL_CREATE_ON_T"
			,"1ST_GI_LOCAL_CREATE_TIME"
			,"2ST_GI_LOCAL_CREATE_TIME"			
			
			,"FILE_NAME"
			,"LOAD_DATE"
			,"LAST_MODIFICATION_FILE"
		)
		SELECT
			 RW."SALES_DOCUMENT"
			,RW."ITEM"
			,RW."SALES_DOC_TYPE"
			,RW."CUSTOMER_PO"
			,RW."SOLD_TO_PARTY"
			,RW."NAME"
			,RW."MATERIAL"
			,RW."ITEM_DESCR"
			,RW."ITEM_DIVISION"
			--ORDER_QTY_BASE = REPLACE(ORDER_QTY_BASE, ',', '')
			,ROUND(REPLACE(RW."ORDER_QTY_BASE", ',', '')) AS "ORDER_QTY_BASE"
			,RW."BASE_UNIT"
			,ROUND(REPLACE(RW."OPEN_QTY_BASE", ',', '')) AS "OPEN_QTY_BASE"
			,RW."SO_NET_PRICE"
			,RW."SO_NET_VALUE"
			,RW."COST"
			,RW."MARGIN_RATE"
			,RW."SO_CURR"
			,RW."SO_CREATE_ON"
			,RW."SO_CREATE_ON_TIME"
			,RW."FIRST_SC_DATE"
			,RW."SALES_ORG"
			,RW."DISTR_CHANNEL"
			,RW."DIVISION"
			,RW."PLANT"
			,RW."STOR_LOC"
			,RW."ACCOUNT_CODE"
			,RW."ACCOUNT_NAME"
			,RW."GC_ID_GSCM"
			,RW."GC_NAME"
			,RW."AP1_CODE"
			,RW."AP1_NAME"
			,RW."AP2_CODE"
			,RW."AP2_NAME"
			,RW."SCM_SITE_ID"
			,RW."TRANSPORT_ZONE"
			,RW."DELIVERY"
			,RW."ITEM_1"
			,ROUND(REPLACE(RW."DELIVERY_QTY_BASE", ',', '')) AS "DELIVERY_QTY_BASE"
			,RW."BASE_UNIT_1"
			,RW."DOCUMENT_DATE"
			,RW."DO_CREATE_ON"
			,RW."DO_CREATE_ON_TIME"
			,RW."SR_NO"
			,RW."SR_ITEM"
			,RW."SR_DATE"
			,RW."SR_TYPE"
			,RW."SR_TYPE_DESC"
			,RW."1ST_GI_NO"
			,RW."ITEM_2"
			,ROUND(REPLACE(RW."1ST_GI_QTY", ',', '')) AS "1ST_GI_QTY"
			,RW."1ST_GI_CREATE_ON"
			,RW."1ST_GI_CREATE_ON_TIME"
			,RW."2ND_GI_NO"
			,RW."ITEM_3"
			,ROUND(REPLACE(RW."2ND_GI_QTY", ',', '')) AS "2ND_GI_QTY"
			,RW."POSTING_DATE"
			,RW."2ND_GI_CREATE_ON"
			,RW."2ND_GI_CREATE_ON_TIME"
			,RW."BILLING_DOC"
			,RW."ITEM_4"
			,ROUND(REPLACE(RW."BILLED_QTY_BASE", ',', '')) AS "BILLED_QTY_BASE"
			,RW."BILLING_NET_VALUE"
			,RW."BILLING_CURR"
			,RW."BILLING_DATE"
			,RW."BILLING_CREATE_ON"
			,RW."BILLING_CREATE_ON_TIME"
			,RW."PARTIAL_DELIVERY_SEQ"
			,RW."STATUS"
			,RW."1ST_GI_DATE"
			,RW."DELIVERY_BLOCK"
			,RW."ORDER_REASON"
			,RW."REJECT_REASON"
			,RW."REJECT_REASON_1"
			,ROUND(REPLACE(RW."ORDER_QTY", ',', '')) AS "ORDER_QTY"
			,ROUND(REPLACE(RW."CONFIRMED_QTY", ',', '')) AS "CONFIRMED_QTY"
			,RW."SPEC_PROCESSING"
			,RW."MAT_AVAIL_DATE"
			,RW."MATERIAL_GROUP"
			,RW."SO_LOCAL_CREATE_ON_D"
			,RW."DO_LOCAL_CREATE_ON_D"
			,RW."1ST_GI_LOCAL_CREATE"
			,RW."BILLING_LOCAL_CREATE"
			,RW."FINAL_SCH_DATE"
			,RW."SHIPPING_TYPE"
			
            --Alteração solicitada para acréscimo destes 4 campos 05/02/2024 
			,RW."SO_LOCAL_CREATE_ON_T"
			,RW."DO_LOCAL_CREATE_ON_T"
			,RW."1ST_GI_LOCAL_CREATE_TIME"
			,RW."2ST_GI_LOCAL_CREATE_TIME"			
			
			,RW."FILE_NAME"
			,RW."LOAD_DATE"
			,RW."LAST_MODIFICATION_FILE"
		FROM OW_LAO.RAW_DATA_NERP_ZRSDD6A120_SALES_ORDER_TRACKING RW
		WHERE RW."FILE_NAME" = :v_file_name
			AND RW.LAST_MODIFICATION_FILE = ( -- CASO O RPA GERE MAIS DE 1 ARQUIVO
									SELECT MAX(LAST_MODIFICATION_FILE)
									FROM OW_LAO.RAW_DATA_NERP_ZRSDD6A120_SALES_ORDER_TRACKING
									WHERE "FILE_NAME" = v_file_name
								)
		;	
		
		-- ATUALIZA LAST_TIME_PROCESSED
		UPDATE OW_LAO.RAW_DATA_NERP_ZRSDD6A120_SALES_ORDER_TRACKING SET
			LAST_TIME_PROCESSED = CURRENT_TIMESTAMP
		WHERE "FILE_NAME" = :v_file_name
			AND LAST_MODIFICATION_FILE = ( -- CASO O RPA GERE MAIS DE 1 ARQUIVO
									SELECT MAX(LAST_MODIFICATION_FILE)
									FROM OW_LAO.RAW_DATA_NERP_ZRSDD6A120_SALES_ORDER_TRACKING
									WHERE "FILE_NAME" = :v_file_name
								)
		;
		
		-- APAGA ARQUIVOS DA RAW_DATA COM MAIS DE 90 DIAS
		DELETE FROM OW_LAO.RAW_DATA_NERP_ZRSDD6A120_SALES_ORDER_TRACKING
		WHERE LAST_MODIFICATION_FILE <= ADD_DAYS(CURRENT_TIMESTAMP, -40)
		;
		
		-- APAGA ARQUIVOS DA RAW_DATA COM MAIS DE 90 DIAS
		DELETE FROM OW_LAO.RAW_DATA_NERP_ZLLEJ50090_OUTBOUND_TRACKING
		WHERE LOAD_DATE <= ADD_DAYS(CURRENT_TIMESTAMP, -40)
		;
		
	END FOR;
END;
