/***********************************************************************************************
CREATED BY : Luciano Mariani
CREATION DATE : 2024-02-15
CALL OW_LAO.PROC_INTEGRATION_RAW_VTEX_SALES_COLLECTION;
***********************************************************************************************/
CREATE PROCEDURE OW_LAO.PROC_INTEGRATION_RAW_VTEX_SALES_COLLECTION
(
	--IN p_Process_all BOOLEAN DEFAULT FALSE
	 p_DATE_INI DATE DEFAULT NULL
	,P_DATE_FIM DATE DEFAULT NULL
)
LANGUAGE SQLSCRIPT as
BEGIN
	
	/****************************************************************************************
	-- REPROCESSAR TODOS OS ARQUIVOS PARA A ODS A PARTIR DA  RAW NÃO PROCESSADA MAIS ANTIGA
	****************************************************************************************/
	--DECLARE v_file_name NVARCHAR(4000);
	
	DECLARE V_COUNT INT;
	
	-- CURSOR PASSA POR CADA ARQUIVO
	DECLARE CURSOR c_select FOR
	SELECT *
	FROM(
		SELECT 'BR_SHOP' AS INSTANCIA, 'TMP_RAW_VTEX_SSG_BR_SHOP_DETAIL_HIST_TALEND_PRL_2020' AS "TABLE_", 'RAW_VTEX_SSG_BR_SHOP_SALES_COLLECTION' AS RAW FROM DUMMY
		UNION ALL SELECT 'BR_SHOP' AS INSTANCIA, 'TMP_RAW_VTEX_SSG_BR_SHOP_DETAIL_HIST_TALEND_PRL' AS "TABLE_", 'RAW_VTEX_SSG_BR_SHOP_SALES_COLLECTION' AS RAW FROM DUMMY
		UNION ALL SELECT 'BR_SHOP' AS INSTANCIA, 'TMP_RAW_VTEX_SSG_BR_SHOP_DETAIL_HIST_TALEND_PRL_2022' AS "TABLE_", 'RAW_VTEX_SSG_BR_SHOP_SALES_COLLECTION' AS RAW FROM DUMMY
		UNION ALL SELECT 'BR_SHOP' AS INSTANCIA, 'TMP_RAW_VTEX_SSG_BR_SHOP_DETAIL_HIST_TALEND_PRL_2023' AS "TABLE_", 'RAW_VTEX_SSG_BR_SHOP_SALES_COLLECTION' AS RAW FROM DUMMY
		--UNION ALL SELECT 'BR_SHOP' AS INSTANCIA, 'TMP_RAW_VTEX_SSG_BR_SHOP_DETAIL_HIST_TALEND_PRL_2024' AS "TABLE_", 'RAW_VTEX_SSG_BR_SHOP_SALES_COLLECTION' AS RAW FROM DUMMY
		UNION ALL SELECT 'SSG_BR' AS INSTANCIA, 'TMP_RAW_VTEX_SSG_BR_DETAIL_HIST_TALEND_PRL_2020' AS "TABLE_", 'RAW_VTEX_SSG_BR_SALES_COLLECTION' AS RAW FROM DUMMY
		UNION ALL SELECT 'SSG_BR' AS INSTANCIA, 'TMP_RAW_VTEX_SSG_BR_DETAIL_HIST_TALEND_PRL' AS "TABLE_", 'RAW_VTEX_SSG_BR_SALES_COLLECTION' AS RAW FROM DUMMY
		UNION ALL SELECT 'SSG_BR' AS INSTANCIA, 'TMP_RAW_VTEX_SSG_BR_DETAIL_HIST_TALEND_PRL_2022' AS "TABLE_", 'RAW_VTEX_SSG_BR_SALES_COLLECTION' AS RAW FROM DUMMY
		UNION ALL SELECT 'SSG_BR' AS INSTANCIA, 'TMP_RAW_VTEX_SSG_BR_DETAIL_HIST_TALEND_PRL_2023' AS "TABLE_", 'RAW_VTEX_SSG_BR_SALES_COLLECTION' AS RAW FROM DUMMY
		UNION ALL SELECT 'EPP2' AS INSTANCIA, 'TMP_RAW_VTEX_SSG_EPP2_DETAIL_HIST_TALEND_PRL_2023' AS "TABLE_", 'RAW_VTEX_SSG_BR_EPP2_SALES_COLLECTION' AS RAW FROM DUMMY
	)
	WHERE TABLE_ = 'TMP_RAW_VTEX_SSG_BR_SHOP_DETAIL_HIST_TALEND_PRL'
	;
	
	FOR cursorRow as c_select DO
	
	/********************************
	* 	BR SHOP
	********************************/
		IF (SELECT cursorRow.TABLE_ FROM DUMMY) = 'TMP_RAW_VTEX_SSG_BR_SHOP_DETAIL_HIST_TALEND_PRL_2020' THEN
			--IF (SELECT COUNT ('') FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_SHOP_DETAIL_HIST_TALEND_PRL_2020) > 0 THEN		
			SELECT count('') INTO V_COUNT FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_SHOP_DETAIL_HIST_TALEND_PRL_2020;
			WHILE :V_COUNT > 0 DO
				-- INSERE NA TABELA PRINCIPAL
				INSERT INTO "U_PRJ_ECOM"."RAW_VTEX_SSG_BR_SHOP_SALES_COLLECTION"(
					  ORDER_ID 
					, CREATION_DATE
					, MARKETPLACE_ORDER_ID
					, COLLECTION
					, DT_HORA_CARGA
				)
				SELECT TOP 10000
					  ORDER_ID
					, CAST(JSON_VALUE(JSON_DETAIL_TXT, '$.creationDate') AS timestamp ) AS CREATION_DATE
					, JSON_VALUE(JSON_DETAIL_TXT, '$.marketplaceOrderId') AS MARKETPLACE_ORDER_ID
					, CAST(JSON_DETAIL_TXT AS TEXT) AS COLLECTION
					, CAST(DT_HORA_CARGA AS timestamp ) AS DT_HORA_CARGA
				FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_SHOP_DETAIL_HIST_TALEND_PRL_2020
				WHERE ORDER_ID NOT IN( SELECT ORDER_ID FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_COLLECTION );
				
				-- APAGA DA TABELA AUXILIAR
				DELETE FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_SHOP_DETAIL_HIST_TALEND_PRL_2020
				WHERE ORDER_ID IN( SELECT ORDER_ID FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_COLLECTION );
    		
				SELECT count(*) INTO V_COUNT FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_SHOP_DETAIL_HIST_TALEND_PRL_2020;
			END WHILE;			
			--END IF;
		END IF;
	
		IF (SELECT cursorRow.TABLE_ FROM DUMMY) = 'TMP_RAW_VTEX_SSG_BR_SHOP_DETAIL_HIST_TALEND_PRL' THEN
			--IF (SELECT COUNT ('') FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_SHOP_DETAIL_HIST_TALEND_PRL) > 0 THEN
			SELECT count('') INTO V_COUNT FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_SHOP_DETAIL_HIST_TALEND_PRL;
			WHILE :V_COUNT > 0 DO		
				-- INSERE NA TABELA PRINCIPAL
				INSERT INTO "U_PRJ_ECOM"."RAW_VTEX_SSG_BR_SHOP_SALES_COLLECTION"(
					  ORDER_ID 
					, CREATION_DATE
					, MARKETPLACE_ORDER_ID
					, COLLECTION
					, DT_HORA_CARGA
				)
				SELECT TOP 10000
					  ORDER_ID
					, CAST(JSON_VALUE(JSON_DETAIL_TXT, '$.creationDate') AS timestamp ) AS CREATION_DATE
					, JSON_VALUE(JSON_DETAIL_TXT, '$.marketplaceOrderId') AS MARKETPLACE_ORDER_ID
					, CAST(JSON_DETAIL_TXT AS TEXT) AS COLLECTION
					, CAST(DT_HORA_CARGA AS timestamp ) AS DT_HORA_CARGA
				FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_SHOP_DETAIL_HIST_TALEND_PRL
				WHERE ORDER_ID NOT IN( SELECT ORDER_ID FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_COLLECTION );
				
				-- APAGA DA TABELA AUXILIAR
				DELETE FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_SHOP_DETAIL_HIST_TALEND_PRL
				WHERE ORDER_ID IN( SELECT ORDER_ID FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_COLLECTION );
			
				SELECT count('') INTO V_COUNT FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_SHOP_DETAIL_HIST_TALEND_PRL;
			END WHILE;
			--END IF;
		END IF;
	
		IF (SELECT cursorRow.TABLE_ FROM DUMMY) = 'TMP_RAW_VTEX_SSG_BR_SHOP_DETAIL_HIST_TALEND_PRL_2022' THEN
			--IF (SELECT COUNT ('') FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_SHOP_DETAIL_HIST_TALEND_PRL_2022) > 0 THEN
			SELECT count('') INTO V_COUNT FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_SHOP_DETAIL_HIST_TALEND_PRL_2022;
			WHILE :V_COUNT > 0 DO
				-- INSERE NA TABELA PRINCIPAL
				INSERT INTO "U_PRJ_ECOM"."RAW_VTEX_SSG_BR_SHOP_SALES_COLLECTION"(
					  ORDER_ID 
					, CREATION_DATE
					, MARKETPLACE_ORDER_ID
					, COLLECTION
					, DT_HORA_CARGA
				)
				SELECT TOP 10000
					  ORDER_ID
					, CAST(JSON_VALUE(JSON_DETAIL_TXT, '$.creationDate') AS timestamp ) AS CREATION_DATE
					, JSON_VALUE(JSON_DETAIL_TXT, '$.marketplaceOrderId') AS MARKETPLACE_ORDER_ID
					, CAST(JSON_DETAIL_TXT AS TEXT) AS COLLECTION
					, CAST(DT_HORA_CARGA AS timestamp ) AS DT_HORA_CARGA
				FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_SHOP_DETAIL_HIST_TALEND_PRL_2022
				WHERE ORDER_ID NOT IN( SELECT ORDER_ID FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_COLLECTION );
				
				-- APAGA DA TABELA AUXILIAR
				DELETE FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_SHOP_DETAIL_HIST_TALEND_PRL_2022
				WHERE ORDER_ID IN( SELECT ORDER_ID FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_COLLECTION );
			
				SELECT count('') INTO V_COUNT FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_SHOP_DETAIL_HIST_TALEND_PRL_2022;
			END WHILE;
			--END IF;
		END IF;
	
		IF (SELECT cursorRow.TABLE_ FROM DUMMY) = 'TMP_RAW_VTEX_SSG_BR_SHOP_DETAIL_HIST_TALEND_PRL_2023' THEN
			--IF (SELECT COUNT ('') FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_SHOP_DETAIL_HIST_TALEND_PRL_2023) > 0 THEN
			SELECT count('') INTO V_COUNT FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_SHOP_DETAIL_HIST_TALEND_PRL_2023;
			WHILE :V_COUNT > 0 DO		
				-- INSERE NA TABELA PRINCIPAL
				INSERT INTO "U_PRJ_ECOM"."RAW_VTEX_SSG_BR_SHOP_SALES_COLLECTION"(
					  ORDER_ID 
					, CREATION_DATE
					, MARKETPLACE_ORDER_ID
					, COLLECTION
					, DT_HORA_CARGA
				)
				SELECT TOP 10000
					  ORDER_ID
					, CAST(JSON_VALUE(JSON_DETAIL_TXT, '$.creationDate') AS timestamp ) AS CREATION_DATE
					, JSON_VALUE(JSON_DETAIL_TXT, '$.marketplaceOrderId') AS MARKETPLACE_ORDER_ID
					, CAST(JSON_DETAIL_TXT AS TEXT) AS COLLECTION
					, CAST(DT_HORA_CARGA AS timestamp ) AS DT_HORA_CARGA
				FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_SHOP_DETAIL_HIST_TALEND_PRL_2023
				WHERE ORDER_ID NOT IN( SELECT ORDER_ID FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_COLLECTION );
				
				-- APAGA DA TABELA AUXILIAR
				DELETE FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_SHOP_DETAIL_HIST_TALEND_PRL_2023
				WHERE ORDER_ID IN( SELECT ORDER_ID FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_COLLECTION );
			
				SELECT count('') INTO V_COUNT FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_SHOP_DETAIL_HIST_TALEND_PRL_2023;
			END WHILE;
			--END IF;
		END IF;	
	
	
	/********************************
	* 	SSG_BR
	********************************/
	
		IF (SELECT cursorRow.TABLE_ FROM DUMMY) = 'TMP_RAW_VTEX_SSG_BR_DETAIL_HIST_TALEND_PRL_2020' THEN
			--IF (SELECT COUNT ('') FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_DETAIL_HIST_TALEND_PRL_2020) > 0 THEN
			SELECT count('') INTO V_COUNT FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_DETAIL_HIST_TALEND_PRL_2020;
			WHILE :V_COUNT > 0 DO		
				-- INSERE NA TABELA PRINCIPAL
				INSERT INTO "U_PRJ_ECOM"."RAW_VTEX_SSG_BR_SALES_COLLECTION"(
					  ORDER_ID 
					, CREATION_DATE
					, MARKETPLACE_ORDER_ID
					, COLLECTION
					, DT_HORA_CARGA
				)
				SELECT TOP 10000
					  ORDER_ID
					, CAST(JSON_VALUE(JSON_DETAIL_TXT, '$.creationDate') AS timestamp ) AS CREATION_DATE
					, JSON_VALUE(JSON_DETAIL_TXT, '$.marketplaceOrderId') AS MARKETPLACE_ORDER_ID
					, CAST(JSON_DETAIL_TXT AS TEXT) AS COLLECTION
					, CAST(DT_HORA_CARGA AS timestamp ) AS DT_HORA_CARGA
				FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_DETAIL_HIST_TALEND_PRL_2020
				WHERE ORDER_ID NOT IN( SELECT ORDER_ID FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SALES_COLLECTION );
				
				-- APAGA DA TABELA AUXILIAR
				DELETE FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_DETAIL_HIST_TALEND_PRL_2020
				WHERE ORDER_ID IN( SELECT ORDER_ID FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SALES_COLLECTION );
			
				SELECT count('') INTO V_COUNT FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_DETAIL_HIST_TALEND_PRL_2020;
			END WHILE;
			--END IF;
		END IF;
		
		IF (SELECT cursorRow.TABLE_ FROM DUMMY) = 'TMP_RAW_VTEX_SSG_BR_DETAIL_HIST_TALEND_PRL' THEN
			--IF (SELECT COUNT ('') FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_DETAIL_HIST_TALEND_PRL) > 0 THEN
			SELECT count('') INTO V_COUNT FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_DETAIL_HIST_TALEND_PRL;
			WHILE :V_COUNT > 0 DO
				-- INSERE NA TABELA PRINCIPAL
				INSERT INTO "U_PRJ_ECOM"."RAW_VTEX_SSG_BR_SALES_COLLECTION"(
					  ORDER_ID 
					, CREATION_DATE
					, MARKETPLACE_ORDER_ID
					, COLLECTION
					, DT_HORA_CARGA
				)
				SELECT TOP 10000
					  ORDER_ID
					, CAST(JSON_VALUE(JSON_DETAIL_TXT, '$.creationDate') AS timestamp ) AS CREATION_DATE
					, JSON_VALUE(JSON_DETAIL_TXT, '$.marketplaceOrderId') AS MARKETPLACE_ORDER_ID
					, CAST(JSON_DETAIL_TXT AS TEXT) AS COLLECTION
					, CAST(DT_HORA_CARGA AS timestamp ) AS DT_HORA_CARGA
				FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_DETAIL_HIST_TALEND_PRL
				WHERE ORDER_ID NOT IN( SELECT ORDER_ID FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SALES_COLLECTION );
				
				-- APAGA DA TABELA AUXILIAR
				DELETE FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_DETAIL_HIST_TALEND_PRL
				WHERE ORDER_ID IN( SELECT ORDER_ID FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SALES_COLLECTION );
			
				SELECT count('') INTO V_COUNT FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_DETAIL_HIST_TALEND_PRL;
			END WHILE;
			--END IF;
		END IF;	
		
		IF (SELECT cursorRow.TABLE_ FROM DUMMY) = 'TMP_RAW_VTEX_SSG_BR_DETAIL_HIST_TALEND_PRL_2022' THEN
			--IF (SELECT COUNT ('') FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_DETAIL_HIST_TALEND_PRL_2022) > 0 THEN
			SELECT count('') INTO V_COUNT FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_DETAIL_HIST_TALEND_PRL_2022;
			WHILE :V_COUNT > 0 DO
				-- INSERE NA TABELA PRINCIPAL
				INSERT INTO "U_PRJ_ECOM"."RAW_VTEX_SSG_BR_SALES_COLLECTION"(
					  ORDER_ID 
					, CREATION_DATE
					, MARKETPLACE_ORDER_ID
					, COLLECTION
					, DT_HORA_CARGA
				)
				SELECT TOP 10000
					  ORDER_ID
					, CAST(JSON_VALUE(JSON_DETAIL_TXT, '$.creationDate') AS timestamp ) AS CREATION_DATE
					, JSON_VALUE(JSON_DETAIL_TXT, '$.marketplaceOrderId') AS MARKETPLACE_ORDER_ID
					, CAST(JSON_DETAIL_TXT AS TEXT) AS COLLECTION
					, CAST(DT_HORA_CARGA AS timestamp ) AS DT_HORA_CARGA
				FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_DETAIL_HIST_TALEND_PRL_2022
				WHERE ORDER_ID NOT IN( SELECT ORDER_ID FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SALES_COLLECTION );
				
				-- APAGA DA TABELA AUXILIAR
				DELETE FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_DETAIL_HIST_TALEND_PRL_2022
				WHERE ORDER_ID IN( SELECT ORDER_ID FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SALES_COLLECTION );
			
				SELECT count('') INTO V_COUNT FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_DETAIL_HIST_TALEND_PRL_2022;
			END WHILE;
			--END IF;
		END IF;
		IF (SELECT cursorRow.TABLE_ FROM DUMMY) = 'TMP_RAW_VTEX_SSG_BR_DETAIL_HIST_TALEND_PRL_2023' THEN
			--IF (SELECT COUNT ('') FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_DETAIL_HIST_TALEND_PRL_2023) > 0 THEN
			SELECT count('') INTO V_COUNT FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_DETAIL_HIST_TALEND_PRL_2023;
			WHILE :V_COUNT > 0 DO
				-- INSERE NA TABELA PRINCIPAL
				INSERT INTO "U_PRJ_ECOM"."RAW_VTEX_SSG_BR_SALES_COLLECTION"(
					  ORDER_ID 
					, CREATION_DATE
					, MARKETPLACE_ORDER_ID
					, COLLECTION
					, DT_HORA_CARGA
				)
				SELECT TOP 10000
					  ORDER_ID
					, CAST(JSON_VALUE(JSON_DETAIL_TXT, '$.creationDate') AS timestamp ) AS CREATION_DATE
					, JSON_VALUE(JSON_DETAIL_TXT, '$.marketplaceOrderId') AS MARKETPLACE_ORDER_ID
					, CAST(JSON_DETAIL_TXT AS TEXT) AS COLLECTION
					, CAST(DT_HORA_CARGA AS timestamp ) AS DT_HORA_CARGA
				FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_DETAIL_HIST_TALEND_PRL_2023
				WHERE ORDER_ID NOT IN( SELECT ORDER_ID FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SALES_COLLECTION );
				
				-- APAGA DA TABELA AUXILIAR
				DELETE FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_DETAIL_HIST_TALEND_PRL_2023
				WHERE ORDER_ID IN( SELECT ORDER_ID FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SALES_COLLECTION );
			
				SELECT count('') INTO V_COUNT FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_BR_DETAIL_HIST_TALEND_PRL_2023;
			END WHILE;
			--END IF;
		END IF;	
	
	
	/********************************
	* 	EPP2
	********************************/
	
		IF (SELECT cursorRow.TABLE_ FROM DUMMY) = 'TMP_RAW_VTEX_SSG_EPP2_DETAIL_HIST_TALEND_PRL_2023' THEN
			--IF (SELECT COUNT ('') FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_EPP2_DETAIL_HIST_TALEND_PRL_2023) > 0 THEN
			SELECT count('') INTO V_COUNT FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_EPP2_DETAIL_HIST_TALEND_PRL_2023;
			WHILE :V_COUNT > 0 DO
				-- INSERE NA TABELA PRINCIPAL
				INSERT INTO "U_PRJ_ECOM"."RAW_VTEX_SSG_BR_EPP2_SALES_COLLECTION"(
					  ORDER_ID
					, CREATION_DATE
					, MARKETPLACE_ORDER_ID
					, COLLECTION
					, DT_HORA_CARGA
				)
				SELECT TOP 10000
					  ORDER_ID
					, CAST(JSON_VALUE(JSON_DETAIL_TXT, '$.creationDate') AS timestamp ) AS CREATION_DATE
					, JSON_VALUE(JSON_DETAIL_TXT, '$.marketplaceOrderId') AS MARKETPLACE_ORDER_ID
					, CAST(JSON_DETAIL_TXT AS TEXT) AS COLLECTION
					, CAST(DT_HORA_CARGA AS timestamp ) AS DT_HORA_CARGA
				FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_EPP2_DETAIL_HIST_TALEND_PRL_2023
				WHERE ORDER_ID NOT IN( SELECT ORDER_ID FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_EPP2_SALES_COLLECTION);
				
				-- APAGA DA TABELA AUXILIAR
				DELETE FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_EPP2_DETAIL_HIST_TALEND_PRL_2023
				WHERE ORDER_ID IN( SELECT ORDER_ID FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_EPP2_SALES_COLLECTION);
			
				SELECT count('') INTO V_COUNT FROM U_PRJ_ECOM.TMP_RAW_VTEX_SSG_EPP2_DETAIL_HIST_TALEND_PRL_2023;
			END WHILE;
			--END IF;
		END IF;	
	END FOR;
END