CREATE PROCEDURE OW_MD.PROC_DIM_VTEX_PURCHASE_ORDER_REGION
LANGUAGE SQLSCRIPT as
BEGIN
--Truncate table OW_MD.TF_VTEX_PURCHASE_ORDER_REGION, tabela de Região
TRUNCATE TABLE OW_MD.TF_VTEX_PURCHASE_ORDER_REGION;
--Insert na tabela de temporária de ORDER REGION
INSERT INTO OW_MD.TF_VTEX_PURCHASE_ORDER_REGION
(COUNTRY,STATE,CITY,POSTAL_CODE)
SELECT DISTINCT COUNTRY, STATE, CITY, POSTAL_CODE FROM (
SELECT DISTINCT TRIM("OW_MD"."FUNC_REMOVE_CHARACTER_SPECIAL"(COUNTRY)) as COUNTRY,
CASE WHEN TRIM("OW_MD"."FUNC_REMOVE_CHARACTER_SPECIAL"(STATE)) = 'AMAZONAS'
 THEN 'AM'
 	WHEN TRIM("OW_MD"."FUNC_REMOVE_CHARACTER_SPECIAL"(STATE))  IN ('DISTRITO FEDERAL/BRAZIL', 'DISTRITO FEDERALBRAZIL')
 THEN 'DF'
 	WHEN TRIM("OW_MD"."FUNC_REMOVE_CHARACTER_SPECIAL"(STATE))  = 'SAO PAULO'
 THEN 'SP'
 	WHEN TRIM("OW_MD"."FUNC_REMOVE_CHARACTER_SPECIAL"(STATE))  = 'RIO DE JANEIRO'
 THEN 'RJ'
    WHEN TRIM("OW_MD"."FUNC_REMOVE_CHARACTER_SPECIAL"(STATE))  = 'PERNAMBUCO'
 THEN 'PE'
     WHEN TRIM("OW_MD"."FUNC_REMOVE_CHARACTER_SPECIAL"(STATE))  = 'ALAGOAS'
 THEN 'AL'
 ELSE TRIM("OW_MD"."FUNC_REMOVE_CHARACTER_SPECIAL"(STATE)) 
 END as STATE,
TRIM("OW_MD"."FUNC_REMOVE_CHARACTER_SPECIAL"(CITY)) as CITY,
TRIM("OW_MD"."FUNC_REMOVE_CHARACTER_SPECIAL"(POSTAL_CODE)) as POSTAL_CODE
FROM "U_PRJ_ECOM"."RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_SHIPPING" 
WHERE COUNTRY IS NOT NULL OR STATE IS NOT NULL OR CITY IS NOT NULL
--ORDER BY TRIM(UPPER(COUNTRY)) ASC, TRIM(UPPER(STATE)) ASC, TRIM(UPPER(CITY)) ASC
UNION
SELECT DISTINCT TRIM("OW_MD"."FUNC_REMOVE_CHARACTER_SPECIAL"(COUNTRY))as COUNTRY,
CASE WHEN TRIM("OW_MD"."FUNC_REMOVE_CHARACTER_SPECIAL"(STATE)) = 'AMAZONAS'
 THEN 'AM'
 	WHEN TRIM("OW_MD"."FUNC_REMOVE_CHARACTER_SPECIAL"(STATE))  IN ('DISTRITO FEDERAL/BRAZIL', 'DISTRITO FEDERALBRAZIL')
 THEN 'DF'
 	WHEN TRIM("OW_MD"."FUNC_REMOVE_CHARACTER_SPECIAL"(STATE))  = 'SAO PAULO'
 THEN 'SP'
 	WHEN TRIM("OW_MD"."FUNC_REMOVE_CHARACTER_SPECIAL"(STATE))  = 'RIO DE JANEIRO'
 THEN 'RJ'
    WHEN TRIM("OW_MD"."FUNC_REMOVE_CHARACTER_SPECIAL"(STATE))  = 'PERNAMBUCO'
 THEN 'PE'
     WHEN TRIM("OW_MD"."FUNC_REMOVE_CHARACTER_SPECIAL"(STATE))  = 'ALAGOAS'
 THEN 'AL'
 ELSE TRIM("OW_MD"."FUNC_REMOVE_CHARACTER_SPECIAL"(STATE)) 
 END as STATE,
TRIM("OW_MD"."FUNC_REMOVE_CHARACTER_SPECIAL"(CITY)) as CITY,
TRIM("OW_MD"."FUNC_REMOVE_CHARACTER_SPECIAL"(POSTAL_CODE)) as POSTAL_CODE
FROM "U_PRJ_ECOM"."RAW_VTEX_SSG_BR_SALES_ORDER_SHIPPING" 
WHERE COUNTRY IS NOT NULL OR STATE IS NOT NULL OR CITY IS NOT NULL
--ORDER BY TRIM(UPPER(COUNTRY)) ASC, TRIM(UPPER(STATE)) ASC, TRIM(UPPER(CITY)) ASC;
)
ORDER BY COUNTRY, STATE, CITY, POSTAL_CODE;
--Merge entre a tabela temporária e a Tabela de dimensão de região
MERGE INTO OW_MD.DIM_VTEX_PURCHASE_ORDER_REGION O
USING OW_MD.TF_VTEX_PURCHASE_ORDER_REGION M 
ON O.COUNTRY = M.COUNTRY
AND O.STATE = M.STATE
AND O.CITY = M.CITY
AND O.POSTAL_CODE = M.POSTAL_CODE
 WHEN MATCHED 
 THEN UPDATE 
 SET O.COUNTRY = M.COUNTRY,
     O.STATE = M.STATE,
     O.CITY = M.CITY,
     O.POSTAL_CODE = M.POSTAL_CODE
 WHEN NOT MATCHED 
 THEN INSERT ("COUNTRY","STATE","CITY","POSTAL_CODE") VALUES(M."COUNTRY",M."STATE",M."CITY",M."POSTAL_CODE");
END;