CREATE PROCEDURE OW_MD.PROC_FT_VTEX_SSG_BR_SHOP_INVENTORY
LANGUAGE SQLSCRIPT as
BEGIN
--Truncate table OW_MD.FT_VTEX_SSG_BR_SHOP_INVENTORY, tabela fato de inventory
TRUNCATE TABLE OW_MD.FT_VTEX_SSG_BR_SHOP_INVENTORY; 
--Insert na tabela fato de inventory
INSERT INTO OW_MD.FT_VTEX_SSG_BR_SHOP_INVENTORY 
(QUANTITY,IS_UNLIMITED_QUANTITY,TOTAL_RESERVED_QUANTITY,DISPATCHED_RESERVATIONS_QUANTITY,AVAILABLE_QUANTITY,LOAD_DATE,SUR_KEY_SSG_BR_SHOP_INVENTORY_WAREHOUSE,SUR_KEY_SSG_BR_SHOP_INVENTORY_SKU,SUR_KEY_PRODUCT,SUR_KEY_PRODUCT_GROUP)
SELECT DISTINCT 
RVSBSIWDR.QUANTITY,
RVSBSIWDR.IS_UNLIMITED_QUANTITY,
RVSBSIWDR.TOTAL_RESERVED_QUANTITY,
RVSBSIWDR.DISPATCHED_RESERVATIONS_QUANTITY,
RVSBSIWDR.AVAILABLE_QUANTITY,
RVSBSIWDR.LOAD_DATE,
DVSBSIW.SUR_KEY AS "SUR_KEY_SSG_BR_SHOP_INVENTORY_WAREHOUSE",
DVSBSIS.SUR_KEY AS "SUR_KEY_SSG_BR_SHOP_INVENTORY_SKU",
DP.SUR_KEY_PRODUCT AS "SUR_KEY_PRODUCT",
DPG.SUR_KEY AS "SUR_KEY_PRODUCT_GROUP"
FROM      "U_PRJ_ECOM"."ODS_VTEX_SSG_BR_SHOP_INVENTORY_WITH_DISPATCHED_RESERVATIONS" RVSBSIWDR 
LEFT JOIN "OW_MD"."DIM_VTEX_SSG_BR_SHOP_INVENTORY_WAREHOUSE" DVSBSIW ON (RVSBSIWDR.WAREHOUSE_ID = DVSBSIW.WAREHOUSE_ID)
LEFT JOIN "OW_MD"."DIM_VTEX_SSG_BR_SHOP_INVENTORY_SKU" DVSBSIS ON (RVSBSIWDR.SKU_ID = DVSBSIS.ID)
LEFT JOIN "OW_MD"."DIM_PRODUCT" DP ON (DVSBSIS.REF_ID = DP.SKU)
LEFT JOIN "OW_MD"."DIM_PRODUCT_GROUP" DPG ON (DP.SUR_KEY_PRODUCT = DPG.SUR_KEY)
;
END;