CREATE PROCEDURE OW_MD.PROC_FT_PRODUCT_STATUS
LANGUAGE SQLSCRIPT as
BEGIN
--Truncate table OW_MD.FT_PRODUCT_STATUS, tabela de status de produto
TRUNCATE TABLE OW_MD.FT_PRODUCT_STATUS;
--Insert na tabela de status de produto
INSERT INTO OW_MD.FT_PRODUCT_STATUS 
(IS_PRODUCT_ACTIVE,SUR_KEY_PRODUCT,REFER_DATE)
SELECT DISTINCT TF.IS_PRODUCT_ACTIVE,
				D.SUR_KEY_PRODUCT AS SUR_KEY_PRODUCT,
                TF.LOAD_DATE AS REFER_DATE
FROM  U_PRJ_ECOM.ODS_VTEX_PRODUCT_SKU  TF
LEFT JOIN OW_MD.DIM_PRODUCT  D ON (TF.ALTERNATE_IDS_REF_ID = D.SKU /*AND TF.ALTERNATE_IDS_EAN = DIM.EAN*/ )
WHERE  D.SUR_KEY_PRODUCT IS NOT NULL
ORDER BY D.SUR_KEY_PRODUCT ASC, TF.LOAD_DATE ASC
;
END;