CREATE PROCEDURE OW_MD.PROC_DIM_VTEX_PURCHASE_ORDER_TRADE_IN
LANGUAGE SQLSCRIPT as
BEGIN
/*
Informações de negócio :
 Registro de TradeIn do campo de OBS
 */
--Truncate table OW_MD.TF_VTEX_PURCHASE_ORDER_TRADE_IN, tabela de TradeIn
TRUNCATE TABLE OW_MD.TF_VTEX_PURCHASE_ORDER_TRADE_IN;
--Insert na tabela de temporária de ORDER TRADE IN
INSERT INTO OW_MD.TF_VTEX_PURCHASE_ORDER_TRADE_IN
(IS_TRADE_IN)
 SELECT DISTINCT IS_TRADE_IN FROM (
 SELECT DISTINCT (CASE WHEN OBS IS NULL THEN FALSE 
	 WHEN UPPER(OBS) NOT LIKE '%ISTRADEIN%' THEN FALSE 
	 WHEN UPPER(OBS) NOT LIKE '%''''ISTRADEIN''''||'':''||''''TRUE''''%' THEN TRUE
ELSE FALSE END) AS IS_TRADE_IN
 FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SALES_ORDER
UNION ALL 
SELECT DISTINCT (CASE WHEN OBS IS NULL THEN FALSE 
	 WHEN UPPER(OBS) NOT LIKE '%ISTRADEIN%' THEN FALSE 
	 WHEN UPPER(OBS) NOT LIKE '%''''ISTRADEIN''''||'':''||''''TRUE''''%' THEN TRUE
ELSE FALSE END) AS IS_TRADE_IN
 FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER
 );
--Merge entre a tabela temporária e a Tabela de dimensão de TradeIn
MERGE INTO OW_MD.DIM_VTEX_PURCHASE_ORDER_TRADE_IN O
USING OW_MD.TF_VTEX_PURCHASE_ORDER_TRADE_IN M 
ON O."IS_TRADE_IN" = M."IS_TRADE_IN"
 WHEN MATCHED 
 THEN UPDATE 
 SET O."IS_TRADE_IN" = M."IS_TRADE_IN"
 
 WHEN NOT MATCHED 
 THEN INSERT ("IS_TRADE_IN") VALUES(M."IS_TRADE_IN");
END;