
CREATE PROCEDURE OW_MD.PROC_INGESTION_DIM_PRODUCT_ESTORE LANGUAGE SQLSCRIPT
AS 
BEGIN 
	
	--*****************************
	-- PRODUCT_ESTORE
	-- SELECT TOP 10 * FROM OW_MD.DIM_PRODUCT_ESTORE
	--*****************************
	UPDATE DP SET
		 DP.SEDA_FAMILY_ESTORE = PE.FAMILY
		,DP.SEDA_DIVISION_ESTORE = PE.DIVISION
		,DP.SEDA_DESC_ESTORE = PE.DESCRICAO_COMERCIAL
		,DP.SEDA_CATEGORY_ESTORE = PE.CATEGORY
		,DP.SEDA_BU_ESTORE = PE.BU
		,DP.UP_DTTM = CURRENT_TIMESTAMP
	FROM OW_MD.DIM_PRODUCT DP
		INNER JOIN OW_MD.DIM_PRODUCT_ESTORE PE ON PE.SKU_PRODUTO = DP.SKU
	;
	--*****************************
	-- PRODUCT_ESTORE
	-- SELECT TOP 10 * FROM OW_MD.DIM_PRODUCT_ESTORE
	--*****************************
	INSERT INTO OW_MD.DIM_PRODUCT(
		 SKU
		,SEDA_FAMILY_ESTORE
		,SEDA_DIVISION_ESTORE
		,SEDA_DESC_ESTORE
		,SEDA_CATEGORY_ESTORE
		,SEDA_BU_ESTORE
		,INIT_DTTM
	)
	SELECT 
		 SKU_PRODUTO
		,PE.FAMILY
		,PE.DIVISION
		,PE.DESCRICAO_COMERCIAL
		,PE.CATEGORY
		,PE.BU
		,CURRENT_TIMESTAMP AS INIT_DTTM
	FROM OW_MD.DIM_PRODUCT_ESTORE PE
		LEFT JOIN OW_MD.DIM_PRODUCT DP ON PE.SKU_PRODUTO = DP.SKU
	WHERE DP.SKU IS NULL
	;
	
	-- ATUALIZA TF_D2C_NERP_SALES PRODUCT
	UPDATE NS SET 
		  NS.PDROD_DIVISION = PD."DIVISION" -- AS PDROD_DIVISION
		, NS.PDROD_PRODUCT_GROUP = PD.PRODUCT_GROUP_1 -- AS PDROD_PRODUCT_GROUP
		, NS.PDROD_PRODUCT = PD.PRODUCT_1 -- AS PDROD_PRODUCT
		, NS.PROD_ATTB_1 = PD.ATTB01 -- AS PROD_ATTB_1
		, NS.SEDA_BU_ESTORE = PD.SEDA_BU_ESTORE -- AS SEDA_BU_ESTORE
		, NS.SEDA_DIVISION_ESTORE = PD.SEDA_DIVISION_ESTORE -- AS SEDA_DIVISION_ESTORE
		, NS.SEDA_CATEGORY_ESTORE = PD.SEDA_CATEGORY_ESTORE -- AS SEDA_CATEGORY_ESTORE
		, NS.SEDA_FAMILY_ESTORE = PD.SEDA_FAMILY_ESTORE -- AS SEDA_FAMILY_ESTORE
		, NS.SEDA_DESC_ESTORE = PD.SEDA_DESC_ESTORE -- AS SEDA_DESC_ESTORE
	FROM OW_LAO.TF_D2C_NERP_SALES NS
		INNER JOIN OW_MD.DIM_PRODUCT PD ON PD.SKU = NS.SKU
	WHERE PD.SKU IN (	
			SELECT DISTINCT 
				NS.SKU 
			FROM (
					SELECT DISTINCT
						  SKU
						, IFNULL(PDROD_DIVISION,'') AS PDROD_DIVISION
						, IFNULL(PDROD_PRODUCT_GROUP,'') AS PDROD_PRODUCT_GROUP
						, IFNULL(PDROD_PRODUCT,'') AS PDROD_PRODUCT
						, IFNULL(PROD_ATTB_1,'') AS PROD_ATTB_1
						, IFNULL(SEDA_BU_ESTORE,'') AS SEDA_BU_ESTORE
						, IFNULL(SEDA_DIVISION_ESTORE,'') AS SEDA_DIVISION_ESTORE
						, IFNULL(SEDA_CATEGORY_ESTORE,'') AS SEDA_CATEGORY_ESTORE
						, IFNULL(SEDA_FAMILY_ESTORE,'') AS SEDA_FAMILY_ESTORE
						, IFNULL(SEDA_DESC_ESTORE,'') AS SEDA_DESC_ESTORE	
					FROM OW_LAO.TF_D2C_NERP_SALES
					WHERE SKU IS NOT NULL
				) NS
				INNER JOIN OW_MD.DIM_PRODUCT PD ON PD.SKU = NS.SKU
			WHERE 
				IFNULL(PD."DIVISION",'') <> IFNULL(NS.PDROD_DIVISION,'')
				OR IFNULL(PD.PRODUCT_GROUP_1,'') <> IFNULL(NS.PDROD_PRODUCT_GROUP,'')
				OR IFNULL(PD.PRODUCT_1,'') <> IFNULL(NS.PDROD_PRODUCT,'')
				OR IFNULL(PD.ATTB01,'') <> IFNULL(NS.PROD_ATTB_1,'')
				OR IFNULL(PD.SEDA_BU_ESTORE,'') <> IFNULL(NS.SEDA_BU_ESTORE,'')
				OR IFNULL(PD.SEDA_DIVISION_ESTORE,'') <> IFNULL(NS.SEDA_DIVISION_ESTORE,'')
				OR IFNULL(PD.SEDA_CATEGORY_ESTORE,'') <> IFNULL(NS.SEDA_CATEGORY_ESTORE,'')
				OR IFNULL(PD.SEDA_FAMILY_ESTORE,'') <> IFNULL(NS.SEDA_FAMILY_ESTORE,'')
				OR IFNULL(PD.SEDA_DESC_ESTORE,'') <> IFNULL(NS.SEDA_DESC_ESTORE,'')
		)	
	/****************
	(PD.SEDA_DIVISION_ESTORE IS NOT NULL 
			AND NS.SEDA_DIVISION_ESTORE IS NULL)  -- NÃO EXISTIA ANTES
				OR (
					PD."DIVISION" <> NS.PDROD_DIVISION
					OR PD.PRODUCT_GROUP_1 <> NS.PDROD_PRODUCT_GROUP
					OR PD.PRODUCT_1 <> NS.PDROD_PRODUCT
					OR PD.ATTB01 <> NS.PROD_ATTB_1
					OR PD.SEDA_BU_ESTORE <> NS.SEDA_BU_ESTORE
					OR PD.SEDA_DIVISION_ESTORE <> NS.SEDA_DIVISION_ESTORE
					OR PD.SEDA_CATEGORY_ESTORE <> NS.SEDA_CATEGORY_ESTORE
					OR PD.SEDA_FAMILY_ESTORE <> NS.SEDA_FAMILY_ESTORE
					OR PD.SEDA_DESC_ESTORE <> NS.SEDA_DESC_ESTORE
				)
	****************/
	
	
	
	;
END