CREATE PROCEDURE OW_MD.PROC_FT_VTEX_PURCHASE_ORDER_TRACKING
LANGUAGE SQLSCRIPT as
BEGIN
--Truncate table OW_MD.TF_VTEX_PURCHASE_ORDER_TRACKING_01, tabela de status de produto
TRUNCATE TABLE OW_MD.TF_VTEX_PURCHASE_ORDER_TRACKING_01;
--Insert na tabela de status de ORDER TRACKING
INSERT INTO OW_MD.TF_VTEX_PURCHASE_ORDER_TRACKING_01 
(ORDER_ID,MARKETPLACE_ORDER_ID,IS_CORPORATE,IS_COMPLETED,CREATION_DATE,AUTHORIZED_DATE,INVOICED_DATE,CANCELLATION_DATE,CREATION_TIMESTAMP,CANCEL_REASON,LAST_CHANGE,TOTAL_ITEMS,VALUE,TOTAL_DISCOUNTS,TOTAL_SHIPPING,SUR_KEY_PAYMENT_STATUS,SUR_KEY_AFFILIATE,SUR_KEY_ORDER_STATUS,IS_ALL_DELIVERED,IS_ANY_DELIVERED,SHIPPING_ESTIMATED_DATE_LIST,PAYMENT_APPROVED_DATE,CREATE_DATE,SUR_KEY_ORDER_REGION,"SEQUENCE",SUR_KEY_ORDER_DOMAIN,SUR_KEY_ORDER_TRADE_IN)
SELECT  DISTINCT 
	RVSBSO.ORDER_ID,
	RVSBSO.MARKETPLACE_ORDER_ID, 
	RVSBSO.IS_CORPORATE,
	RVSBSO.IS_COMPLETED,
	RVSBSO.CREATION_DATE,
	RVSBSO.AUTHORIZED_DATE,
	RVSBSO.INVOICED_DATE,
	RVSBSO.CANCELLATION_DATE,
	RVSBSO.CREATION_TIMESTAMP,
	RVSBSO.CANCEL_REASON,
	MAX(RVSBSO.LAST_CHANGE) AS LAST_CHANGE,
	(RVSBSO.TOTAL_ITEMS/100) AS TOTAL_ITEMS,
	(RVSBSO.VALUE/100) AS VALUE,
	(RVSBSO.TOTAL_DISCOUNTS/100) AS TOTAL_DISCOUNTS,
	(RVSBSO.TOTAL_SHIPPING/100) AS TOTAL_SHIPPING,
	DVPS.SUR_KEY AS SUR_KEY_PAYMENT_STATUS,
	DVA.SUR_KEY AS SUR_KEY_AFFILIATE,
	DVAS.SUR_KEY AS SUR_KEY_ORDER_STATUS,
	LIST.IS_ALL_DELIVERED, 
	LIST.IS_ANY_DELIVERED, 
	LIST.SHIPPING_ESTIMATED_DATE AS SHIPPING_ESTIMATED_DATE_LIST,
	LIST.PAYMENT_APPROVED_DATE,
	NOW() AS CREATE_DATE,
	DVPOR.SUR_KEY AS SUR_KEY_ORDER_REGION,
	RVSBSO."SEQUENCE",
	DVPOD.SUR_KEY AS SUR_KEY_ORDER_DOMAIN,
	DVPOTI.SUR_KEY AS SUR_KEY_ORDER_TRADE_IN
FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER RVSBSO 
LEFT JOIN (SELECT ORDER_ID,STATUS FROM (SELECT A.ORDER_ID, A.STATUS, A.LOAD_DATE, ROW_NUMBER() OVER (PARTITION BY A.ORDER_ID ORDER BY A.LOAD_DATE DESC, A.CREATION_DATE DESC) as ROW_NUM
FROM U_PRJ_ECOM.ODS_VTEX_SSG_BR_PAYMENT_STATUS A ) WHERE ROW_NUM =1) OVSBPS  ON (RVSBSO.MARKETPLACE_ORDER_ID = OVSBPS.ORDER_ID) --Tabela utilizada para fazer o relacionamento entre ORDER_ID e trazer dados de status // ESSE  SUBSELECT com row_num é para trazer o status mais recente da order
LEFT JOIN OW_MD.DIM_VTEX_PAYMENT_STATUS dvps ON (OVSBPS.STATUS = DVPS.PAYMENT_STATUS)
LEFT JOIN OW_MD.DIM_VTEX_AFFILIATE DVA ON (RVSBSO.AFFILIATE_ID = DVA.AFFILIATE_ID)
LEFT JOIN OW_MD.DIM_VTEX_ORDER_STATUS DVAS ON (RVSBSO.STATUS = DVAS.STATUS) AND (RVSBSO.STATUS_DESCRIPTION = DVAS.STATUS_DESCRIPTION)
LEFT JOIN (SELECT ORDER_ID, IS_ALL_DELIVERED ,IS_ANY_DELIVERED , SHIPPING_ESTIMATED_DATE, PAYMENT_APPROVED_DATE FROM (SELECT L.ORDER_ID,L.IS_ALL_DELIVERED , L.IS_ANY_DELIVERED ,
L.SHIPPING_ESTIMATED_DATE,L.PAYMENT_APPROVED_DATE ,ROW_NUMBER() OVER (PARTITION BY L.ORDER_ID ORDER BY L.UPDATED_AT DESC, L.CREATION_DATE DESC) as ROW_NUM
FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_LIST L) WHERE ROW_NUM =1) LIST  ON (LIST.ORDER_ID = RVSBSO.ORDER_ID)
LEFT JOIN U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_SHIPPING RVSBSSOS ON (RVSBSO.ORDER_ID = RVSBSSOS.ORDER_ID)
LEFT JOIN OW_MD.DIM_VTEX_PURCHASE_ORDER_REGION DVPOR ON ( TRIM("OW_MD"."FUNC_REMOVE_CHARACTER_SPECIAL"(RVSBSSOS.COUNTRY)) = DVPOR.COUNTRY AND             --TRATAMENTO DE DADOS PARA FAZER O JOIN COM O CAMPO DE ESTADO TRATADO (UTILIZANDO A FUNÇÃO DE TRATAMENTO)
(CASE WHEN TRIM("OW_MD"."FUNC_REMOVE_CHARACTER_SPECIAL"(RVSBSSOS.STATE)) = 'AMAZONAS'
 THEN 'AM'
 	WHEN TRIM("OW_MD"."FUNC_REMOVE_CHARACTER_SPECIAL"(RVSBSSOS.STATE))  IN ('DISTRITO FEDERAL/BRAZIL', 'DISTRITO FEDERALBRAZIL')
 THEN 'DF'
 	WHEN TRIM("OW_MD"."FUNC_REMOVE_CHARACTER_SPECIAL"(RVSBSSOS.STATE))  = 'SAO PAULO'
 THEN 'SP'
 	WHEN TRIM("OW_MD"."FUNC_REMOVE_CHARACTER_SPECIAL"(RVSBSSOS.STATE))  = 'RIO DE JANEIRO'
 THEN 'RJ'
    WHEN TRIM("OW_MD"."FUNC_REMOVE_CHARACTER_SPECIAL"(RVSBSSOS.STATE))  = 'PERNAMBUCO'
 THEN 'PE'
     WHEN TRIM("OW_MD"."FUNC_REMOVE_CHARACTER_SPECIAL"(RVSBSSOS.STATE))  = 'ALAGOAS'
 THEN 'AL'
 ELSE TRIM("OW_MD"."FUNC_REMOVE_CHARACTER_SPECIAL"(RVSBSSOS.STATE)) 
 END ) = DVPOR.STATE  
AND TRIM("OW_MD"."FUNC_REMOVE_CHARACTER_SPECIAL"(RVSBSSOS.CITY)) = DVPOR.CITY
AND TRIM("OW_MD"."FUNC_REMOVE_CHARACTER_SPECIAL"(RVSBSSOS.POSTAL_CODE)) = DVPOR.POSTAL_CODE)
LEFT JOIN OW_MD.DIM_VTEX_PURCHASE_ORDER_DOMAIN DVPOD ON (SUBSTR_AFTER(RVSBSO.EMAIL_DOMAIN,'@') = DVPOD."DOMAIN")
LEFT JOIN OW_MD.DIM_VTEX_PURCHASE_ORDER_TRADE_IN DVPOTI ON ((CASE WHEN RVSBSO.OBS IS NULL THEN NULL 
	 WHEN UPPER(RVSBSO.OBS) NOT LIKE '%ISTRADEIN%' THEN NULL 
	 WHEN UPPER(RVSBSO.OBS) NOT LIKE '%''''ISTRADEIN''''||'':''||''''TRUE''''%' THEN TRUE
ELSE FALSE END) = DVPOTI."IS_TRADE_IN")  --Regra de trade in feita pelo time de negócio 
GROUP BY 
	RVSBSO.ORDER_ID, 
	RVSBSO.MARKETPLACE_ORDER_ID, 
	RVSBSO.IS_CORPORATE,
	RVSBSO.IS_COMPLETED,
	RVSBSO.CREATION_DATE,
	RVSBSO.AUTHORIZED_DATE,
	RVSBSO.INVOICED_DATE,
	RVSBSO.CANCELLATION_DATE,
	RVSBSO.CREATION_TIMESTAMP,
	RVSBSO.CANCEL_REASON,
	RVSBSO.TOTAL_ITEMS,
	RVSBSO."VALUE",
	RVSBSO.TOTAL_DISCOUNTS,
	RVSBSO.TOTAL_SHIPPING,
	DVPS.SUR_KEY,
	DVA.SUR_KEY,
	DVAS.SUR_KEY,
	LIST.IS_ALL_DELIVERED, 
	LIST.IS_ANY_DELIVERED, 
	LIST.SHIPPING_ESTIMATED_DATE,
	LIST.PAYMENT_APPROVED_DATE,
	NOW(),
	DVPOR.SUR_KEY,
	RVSBSO."SEQUENCE",
	DVPOD.SUR_KEY,
	DVPOTI.SUR_KEY
	
;
MERGE INTO OW_MD.FT_VTEX_PURCHASE_ORDER_TRACKING O 
USING OW_MD.TF_VTEX_PURCHASE_ORDER_TRACKING_01 M 
ON O.ORDER_ID = M.ORDER_ID
 WHEN MATCHED 
 THEN UPDATE 
 SET    O.ORDER_ID          	 =	M.ORDER_ID,
 	O.MARKETPLACE_ORDER_ID   =      M.MARKETPLACE_ORDER_ID,
	O.IS_CORPORATE	    	 =	M.IS_CORPORATE,
	O.IS_COMPLETED	    	 =	M.IS_COMPLETED,
	O.CREATION_DATE		 =	M.CREATION_DATE,
	O.AUTHORIZED_DATE	 =	M.AUTHORIZED_DATE,
	O.INVOICED_DATE	    	 =	M.INVOICED_DATE,
	O.CANCELLATION_DATE	 =	M.CANCELLATION_DATE,
	O.CREATION_TIMESTAMP     =	M.CREATION_TIMESTAMP,
	O.CANCEL_REASON		 =	M.CANCEL_REASON,
	O.LAST_CHANGE		 =	M.LAST_CHANGE,
	O.TOTAL_ITEMS		 =	M.TOTAL_ITEMS,
	O."VALUE"		 =	M."VALUE",
	O.TOTAL_DISCOUNTS	 =	M.TOTAL_DISCOUNTS,
	O.TOTAL_SHIPPING	 =	M.TOTAL_SHIPPING,
	O.SUR_KEY_PAYMENT_STATUS =	M.SUR_KEY_PAYMENT_STATUS,
	O.SUR_KEY_AFFILIATE 	 =	M.SUR_KEY_AFFILIATE,
        O.SUR_KEY_ORDER_STATUS	 =	M.SUR_KEY_ORDER_STATUS,
        O.IS_ALL_DELIVERED       =	M.IS_ALL_DELIVERED, 
	O.IS_ANY_DELIVERED       =      M.IS_ANY_DELIVERED, 
	O.SHIPPING_ESTIMATED_DATE_LIST = M.SHIPPING_ESTIMATED_DATE_LIST,
        O.PAYMENT_APPROVED_DATE  =      M.PAYMENT_APPROVED_DATE,
        O."UPDATE_DATE"    	 = 	M."CREATE_DATE",
        O.SUR_KEY_ORDER_REGION = M.SUR_KEY_ORDER_REGION,
        O."SEQUENCE"          =  M."SEQUENCE",
        O.SUR_KEY_ORDER_DOMAIN = M.SUR_KEY_ORDER_DOMAIN,
        O.SUR_KEY_ORDER_TRADE_IN = M.SUR_KEY_ORDER_TRADE_IN
 WHEN NOT MATCHED 
 THEN INSERT ("ORDER_ID",
"MARKETPLACE_ORDER_ID", 
"IS_CORPORATE",		
"IS_COMPLETED",	
"CREATION_DATE",		
"AUTHORIZED_DATE",		
"INVOICED_DATE",
"CANCELLATION_DATE",	
"CREATION_TIMESTAMP",
"CANCEL_REASON",
"LAST_CHANGE",			
"TOTAL_ITEMS",			
"VALUE",				
"TOTAL_DISCOUNTS",		
"TOTAL_SHIPPING",		
"SUR_KEY_PAYMENT_STATUS",
"SUR_KEY_AFFILIATE",
"SUR_KEY_ORDER_STATUS",
"IS_ALL_DELIVERED",
"IS_ANY_DELIVERED",
"SHIPPING_ESTIMATED_DATE_LIST",
"PAYMENT_APPROVED_DATE",
"CREATE_DATE",
"SUR_KEY_ORDER_REGION",
"SEQUENCE",
"SUR_KEY_ORDER_DOMAIN",
"SUR_KEY_ORDER_TRADE_IN") VALUES(M.ORDER_ID,
M.MARKETPLACE_ORDER_ID,
M.IS_CORPORATE,
M.IS_COMPLETED,
M.CREATION_DATE,
M.AUTHORIZED_DATE,
M.INVOICED_DATE,
M.CANCELLATION_DATE,
M.CREATION_TIMESTAMP,
M.CANCEL_REASON,
M.LAST_CHANGE,
M.TOTAL_ITEMS,
M."VALUE",
M.TOTAL_DISCOUNTS,
M.TOTAL_SHIPPING,
M.SUR_KEY_PAYMENT_STATUS,
M.SUR_KEY_AFFILIATE,
M.SUR_KEY_ORDER_STATUS,
M.IS_ALL_DELIVERED,
M.IS_ANY_DELIVERED,
M.SHIPPING_ESTIMATED_DATE_LIST,
M.PAYMENT_APPROVED_DATE,
M."CREATE_DATE",
M.SUR_KEY_ORDER_REGION,
M."SEQUENCE",
M.SUR_KEY_ORDER_DOMAIN,
M.SUR_KEY_ORDER_TRADE_IN);
END;