CREATE PROCEDURE OW_MD.PROC_FT_VTEX_PURCHASE_ORDER_TRACKING_ITEM
LANGUAGE SQLSCRIPT as
BEGIN
--Truncate table OW_MD.FT_VTEX_PURCHASE_ORDER_TRACKING_ITEM, tabela de status de produto
TRUNCATE TABLE OW_MD.FT_VTEX_PURCHASE_ORDER_TRACKING_ITEM; 
--Insert na tabela de status de ORDER TRACKING ITEM
INSERT INTO OW_MD.FT_VTEX_PURCHASE_ORDER_TRACKING_ITEM 
(PRODUCT_ID,QUANTITY,IS_GIFT,COMMERCIAL_CONDITION_ID,PRICE,SELLING_PRICE,LIST_PRICE,MANUAL_PRICE,ITEM_INDEX,DELIVERED_DATE,INVOICE_NUMBER,ISSUANCE_DATE,TRACKING_NUMBER,SHIPPING_ESTIMATE_DATE,DOCK_ID,SUR_KEY_PURCHASE_ORDER_TRACKING,SUR_KEY_PRODUCT,SUR_KEY_PURCHASE_ORDER_WAREHOUSE,SUR_KEY_PURCHASE_ORDER_COURIER)
SELECT 
RVSBSSOI.PRODUCT_ID, 
RVSBSSOI.QUANTITY, 
RVSBSSOI.IS_GIFT,
RVSBSSOI.COMMERCIAL_CONDITION_ID,
RVSBSSOI.PRICE,
RVSBSSOI.SELLING_PRICE,
RVSBSSOI.LIST_PRICE,
RVSBSSOI.MANUAL_PRICE,
RVSBSSOI.ITEM_INDEX,
RVSBSSOP.DELIVERED_DATE,
RVSBSSOP.INVOICE_NUMBER,
RVSBSSOP.ISSUANCE_DATE,
RVSBSSOP.TRACKING_NUMBER,
RVSBSSOS.SHIPPING_ESTIMATE_DATE,
RVSBSSOS.DOCK_ID,
FVPOT.SUR_KEY AS SUR_KEY_PURCHASE_ORDER_TRACKING,
DP.SUR_KEY AS SUR_KEY_PRODUCT,
DVPOW.SUR_KEY AS SUR_KEY_PURCHASE_ORDER_WAREHOUSE,
DVPOC.SUR_KEY AS SUR_KEY_PURCHASE_ORDER_COURIER
FROM 
U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_ITEM RVSBSSOI
/* Union para manter os dados da BR e BRSHOP solicitados pela Leticia 09/12/2022
 (SELECT DISTINCT ORDER_ID, PRODUCT_ID, QUANTITY, IS_GIFT,COMMERCIAL_CONDITION_ID,PRICE,SELLING_PRICE,LIST_PRICE,MANUAL_PRICE,ITEM_INDEX, REF_ID
FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_ITEM
UNION
SELECT DISTINCT ORDER_ID, PRODUCT_ID, QUANTITY, IS_GIFT,COMMERCIAL_CONDITION_ID,PRICE,SELLING_PRICE,LIST_PRICE,MANUAL_PRICE,ITEM_INDEX, REF_ID
FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SALES_ORDER_ITEM) RVSBSSOI
*/
LEFT JOIN  OW_MD.FT_VTEX_PURCHASE_ORDER_TRACKING FVPOT ON (RVSBSSOI.ORDER_ID = FVPOT.ORDER_ID)
LEFT JOIN OW_MD.OLD_DIM_PRODUCT DP  ON (RVSBSSOI.REF_ID = DP.SKU) --DIM_PRODUCT Tabela antiga, alterarada para a tabela OLD_DIM_PRODUCT, proc alterada 14/04/2023
-- Union para manter os dados da BR e BRSHOP solicitados pela Leticia 09/12/2022
LEFT JOIN (SELECT ORDER_ID, ITEM_INDEX, DELIVERED_DATE, INVOICE_NUMBER, ISSUANCE_DATE, TRACKING_NUMBER, MAX(UPDATED_AT), MAX(CREATED_AT) 
		FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_PACKAGE RVSBSSOP1
	   GROUP BY ORDER_ID, ITEM_INDEX, DELIVERED_DATE, INVOICE_NUMBER, ISSUANCE_DATE, TRACKING_NUMBER
UNION 
SELECT ORDER_ID, ITEM_INDEX, DELIVERED_DATE, INVOICE_NUMBER, ISSUANCE_DATE, TRACKING_NUMBER, MAX(UPDATED_AT), MAX(CREATED_AT)
		FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SALES_ORDER_PACKAGE RVSBSSOP2
	   GROUP BY ORDER_ID, ITEM_INDEX, DELIVERED_DATE, INVOICE_NUMBER, ISSUANCE_DATE, TRACKING_NUMBER) RVSBSSOP
ON (RVSBSSOI.ORDER_ID = RVSBSSOP.ORDER_ID  AND RVSBSSOI.ITEM_INDEX = RVSBSSOP.ITEM_INDEX)
--
LEFT JOIN (SELECT ORDER_ID, ITEM_INDEX, SHIPPING_ESTIMATE_DATE, DOCK_ID, MAX(CREATED_AT), MAX(UPDATED_AT) 
		FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_SHIPPING RVSBSSOS1
	   GROUP BY ORDER_ID, ITEM_INDEX, SHIPPING_ESTIMATE_DATE, DOCK_ID ) RVSBSSOS
ON (RVSBSSOI.ORDER_ID = RVSBSSOS.ORDER_ID  AND RVSBSSOI.ITEM_INDEX = RVSBSSOS.ITEM_INDEX)
LEFT JOIN (SELECT * FROM (SELECT DISTINCT ORDER_ID, ITEM_INDEX, WAREHOUSE_ID, COURIER_NAME, COURIER_ID
FROM "U_PRJ_ECOM"."RAW_VTEX_SSG_BR_SALES_ORDER_SHIPPING"
UNION
SELECT DISTINCT ORDER_ID, ITEM_INDEX, WAREHOUSE_ID, COURIER_NAME, COURIER_ID
FROM "U_PRJ_ECOM"."RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_SHIPPING")) USWC  ON (RVSBSSOI.ORDER_ID = USWC.ORDER_ID AND RVSBSSOI.ITEM_INDEX = USWC.ITEM_INDEX) -- union para trazer os dados da dimensão de warehouse e courier 
LEFT JOIN "OW_MD"."DIM_VTEX_PURCHASE_ORDER_WAREHOUSE" DVPOW ON (USWC.WAREHOUSE_ID = DVPOW.WAREHOUSE_ID)
LEFT JOIN "OW_MD"."DIM_VTEX_PURCHASE_ORDER_COURIER"   DVPOC ON (USWC.COURIER_NAME = DVPOC.COURIER_NAME AND USWC.COURIER_ID = DVPOC.COURIER_ID)
  ;
END;