CREATE PROCEDURE OW_MD.PROC_DIM_VTEX_PURCHASE_ORDER_DOMAIN
LANGUAGE SQLSCRIPT as
BEGIN
/*
Informações de negócio :
 Registro dos dominios onde são dos e-mails dos pedidos.
 */
--Truncate table OW_MD.TF_VTEX_PURCHASE_ORDER_DOMAIN, tabela de dominio
TRUNCATE TABLE OW_MD.TF_VTEX_PURCHASE_ORDER_DOMAIN;
--Insert na tabela de temporária de ORDER DOMAIN
INSERT INTO OW_MD.TF_VTEX_PURCHASE_ORDER_DOMAIN
("DOMAIN")
SELECT DISTINCT "DOMAIN" FROM (
/*SELECT DISTINCT SUBSTR_AFTER(EMAIL_DOMAIN,'@') AS "DOMAIN" FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SALES_ORDER
UNION ALL */
SELECT DISTINCT SUBSTR_AFTER(EMAIL_DOMAIN,'@') AS "DOMAIN" FROM U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER
) WHERE "DOMAIN" IS NOT NULL ORDER BY 1 ASC;
--Merge entre a tabela temporária e a Tabela de dimensão de dominio
MERGE INTO OW_MD.DIM_VTEX_PURCHASE_ORDER_DOMAIN O
USING OW_MD.TF_VTEX_PURCHASE_ORDER_DOMAIN M 
ON O."DOMAIN" = M."DOMAIN"
 WHEN MATCHED 
 THEN UPDATE 
 SET O."DOMAIN" = M."DOMAIN"
 
 WHEN NOT MATCHED 
 THEN INSERT ("DOMAIN") VALUES(M."DOMAIN");
END;