CREATE PROCEDURE OW_MD.PROC_DIM_VTEX_SSG_BR_INVENTORY_SKU
LANGUAGE SQLSCRIPT as
BEGIN
--Truncate table OW_MD.TF_VTEX_SSG_BR_INVENTORY_SKU, tabela de SKU
TRUNCATE TABLE OW_MD.TF_VTEX_SSG_BR_INVENTORY_SKU;
--Insert na tabela de temporária de INVENTORY SKU
INSERT INTO OW_MD.TF_VTEX_SSG_BR_INVENTORY_SKU
(ID,PRODUCT_ID,IS_ACTIVE,ACTIVATE_IF_POSSIBLE,NAME,REF_ID,IS_KIT,CREATION_DATE,MANUFACTURER_CODE,COMMERCIAL_CONDITION_ID)
SELECT DISTINCT 
ID,
PRODUCT_ID,
IS_ACTIVE,
ACTIVATE_IF_POSSIBLE,
NAME,
REF_ID,
IS_KIT,
CREATION_DATE,
MANUFACTURER_CODE,
COMMERCIAL_CONDITION_ID
FROM "U_PRJ_ECOM"."ODS_VTEX_SSG_BR_SKU_BY_REF_ID";
--Merge entre a tabela temporária e a Tabela de dimensão de SKU
MERGE INTO OW_MD.DIM_VTEX_SSG_BR_INVENTORY_SKU O
USING OW_MD.TF_VTEX_SSG_BR_INVENTORY_SKU M 
ON O.ID = M.ID
AND O.CREATION_DATE = M.CREATION_DATE 
 WHEN MATCHED 
 THEN UPDATE 
 SET O.ID = M.ID,
 	 O.PRODUCT_ID = M.PRODUCT_ID,
 	 O.IS_ACTIVE = M.IS_ACTIVE,
 	 O.ACTIVATE_IF_POSSIBLE = M.ACTIVATE_IF_POSSIBLE,
 	 O.NAME = M.NAME,
 	 O.REF_ID = M.REF_ID,
 	 O.IS_KIT = M.IS_KIT,
 	 O.CREATION_DATE = M.CREATION_DATE,
 	 O.MANUFACTURER_CODE = M.MANUFACTURER_CODE,
 	 O.COMMERCIAL_CONDITION_ID = M.COMMERCIAL_CONDITION_ID
 
 WHEN NOT MATCHED 
 THEN INSERT ("ID", "PRODUCT_ID", "IS_ACTIVE", "ACTIVATE_IF_POSSIBLE", "NAME", "REF_ID", "IS_KIT", "CREATION_DATE", "MANUFACTURER_CODE", "COMMERCIAL_CONDITION_ID")
  VALUES(M."ID", M."PRODUCT_ID", M."IS_ACTIVE", M."ACTIVATE_IF_POSSIBLE", M."NAME", M."REF_ID", M."IS_KIT", M."CREATION_DATE", M."MANUFACTURER_CODE", M."COMMERCIAL_CONDITION_ID" );
END;