CREATE PROCEDURE OW_MD.PROC_INGESTION_ODS_MP_ESTORE()
	LANGUAGE SQLSCRIPT
	SQL SECURITY INVOKER 
AS 
BEGIN	
DELETE FROM OW_MD.ODS_MP_ESTORE;
INSERT INTO OW_MD.ODS_MP_ESTORE
WITH SEQUENCIAL AS 
(
	SELECT
		  *
		, RANK() OVER(PARTITION BY YEAR, MONTH, MATERIAL ORDER BY LOAD_DATE DESC) AS SEQ	
	FROM OW_MD.RAW_MP_ESTORE	
	WHERE 1=1 
)
SELECT	  
		  YEAR
		, MONTH
		, CALENDAR_YEAR_MONTH
		, VERSION 
		, SUBSIDIARY 
		, CC 
		, COMBINED_B_A 
		, SALES_ORG
		, GBM 
		, NEW_BIZ_HQ_2 
		, GLOBAL_PROD_GRP1_N 
		, GP1 
		, GLOBAL_PROD_GRP2_N 
		, GP2 
		, CHAR_VALUE_01_N 
		, CHAR_VALUE_02_N 
		, CHAR_VALUE_03_N 
		, CHAR_VALUE_04_N 
		, CHAR_VALUE_05_N 
		, CHAR_VALUE_06_N 
		, CHAR_VALUE_12_N 
		, CHAR_VALUE_13_N 
		, CUSTOMER_TYPE 
		, SOLD_TO_PARTY 
		, SOLD_TO_PARTY_NAME 
		, MATERIAL 
		, NET_SALES_QTY 
		, NET_SALES 
		, CHANNEL 
		, PDROD_DIVISION
		, PDROD_PRODUCT_GROUP
		, LOAD_DATE
		, FILE_NAME	
FROM SEQUENCIAL
WHERE 1=1
	AND SEQ = 1;
	
END;
