CREATE PROCEDURE OW_MD.PROC_DIM_VTEX_SSG_BR_SHOP_INVENTORY_WAREHOUSE
LANGUAGE SQLSCRIPT as
BEGIN
--Truncate table OW_MD.TF_VTEX_SSG_BR_SHOP_INVENTORY_WAREHOUSE, tabela de INVENTORY WAREHOUSE
TRUNCATE TABLE OW_MD.TF_VTEX_SSG_BR_SHOP_INVENTORY_WAREHOUSE;
--Insert na tabela de temporária de INVENTORY WAREHOUSE
INSERT INTO OW_MD.TF_VTEX_SSG_BR_SHOP_INVENTORY_WAREHOUSE
(WAREHOUSE_ID,
WAREHOUSE_NAME)
SELECT DISTINCT 
WAREHOUSE_ID,
WAREHOUSE_NAME
FROM "U_PRJ_ECOM"."ODS_VTEX_SSG_BR_SHOP_INVENTORY_BY_SKU"
WHERE WAREHOUSE_ID IS NOT NULL 
ORDER BY WAREHOUSE_ID ASC;
--Merge entre a tabela temporária e a Tabela de dimensão de INVENTORY WAREHOUSE
MERGE INTO OW_MD.DIM_VTEX_SSG_BR_SHOP_INVENTORY_WAREHOUSE O
USING OW_MD.TF_VTEX_SSG_BR_SHOP_INVENTORY_WAREHOUSE M 
ON O.WAREHOUSE_ID = M.WAREHOUSE_ID
 WHEN MATCHED 
 THEN UPDATE 
 SET O.WAREHOUSE_ID = M.WAREHOUSE_ID,
 	 O.WAREHOUSE_NAME = M.WAREHOUSE_NAME
 
 WHEN NOT MATCHED 
 THEN INSERT ("WAREHOUSE_ID", "WAREHOUSE_NAME") VALUES(M."WAREHOUSE_ID", M."WAREHOUSE_NAME");
END;