CREATE PROCEDURE OW_MD.PROC_INGESTION_DIM_PRODUCT_GLOBAL LANGUAGE SQLSCRIPT
AS 
BEGIN 
		
	--*****************************
	-- PRODUCT_GLOBAL
	-- SELECT TOP 10 * FROM OW_MD.DIM_PRODUCT_GLOBAL
	--*****************************
	UPDATE DP SET
		 DP.SKU = GL.SKU
		,DP."ALL" = GL."ALL"
		,DP.DIVISION = GL.DIVISION
		,DP.PRODUCT_GROUP_1 = GL.PRODUCT_GROUP
		,DP.PRODUCT_1 = GL.PRODUCT
		,DP.ATTB01 = GL."ATTRIBUTES"
	FROM OW_MD.DIM_PRODUCT DP
		INNER JOIN OW_MD.DIM_PRODUCT_GLOBAL GL ON GL.SKU = DP.SKU
	WHERE GL.SKU = DP.SKU
	;
		
	--*****************************
	-- PRODUCT_GLOBAL
	-- SELECT TOP 10 * FROM OW_MD.DIM_PRODUCT_GLOBAL
	--*****************************
	INSERT INTO OW_MD.DIM_PRODUCT(
		 SKU
		,"ALL"
		,DIVISION
		,PRODUCT_GROUP_1
		,PRODUCT_1
		,ATTB01
	)
	SELECT 
		 GL.SKU
		,GL."ALL"
		,GL.DIVISION
		,GL.PRODUCT_GROUP
		,GL.PRODUCT
		,GL."ATTRIBUTES" AS ATTB01
	FROM OW_MD.DIM_PRODUCT_GLOBAL GL
		LEFT JOIN OW_MD.DIM_PRODUCT DP ON GL.SKU = DP.SKU
	WHERE DP.SKU IS NULL
	;
	-- ATUALIZA TF_D2C_NERP_SALES PRODUCT
	UPDATE NS SET 
		  PDROD_DIVISION = PD."DIVISION" -- AS PDROD_DIVISION
		, PDROD_PRODUCT_GROUP = PD.PRODUCT_GROUP_1 -- AS PDROD_PRODUCT_GROUP
		, PDROD_PRODUCT = PD.PRODUCT_1 -- AS PDROD_PRODUCT
		, PROD_ATTB_1 = PD.ATTB01 -- AS PROD_ATTB_1
		, SEDA_BU_ESTORE = PD.SEDA_BU_ESTORE -- AS SEDA_BU_ESTORE
		, SEDA_DIVISION_ESTORE = PD.SEDA_DIVISION_ESTORE -- AS SEDA_DIVISION_ESTORE
		, SEDA_CATEGORY_ESTORE = PD.SEDA_CATEGORY_ESTORE -- AS SEDA_CATEGORY_ESTORE
		, SEDA_FAMILY_ESTORE = PD.SEDA_FAMILY_ESTORE -- AS SEDA_FAMILY_ESTORE
		, SEDA_DESC_ESTORE = PD.SEDA_DESC_ESTORE -- AS SEDA_DESC_ESTORE
	FROM OW_LAO.TF_D2C_NERP_SALES NS
		INNER JOIN OW_MD.DIM_PRODUCT PD ON PD.SKU = NS.SKU
	WHERE  (PD.SEDA_DIVISION_ESTORE IS NOT NULL 
			AND NS.SEDA_DIVISION_ESTORE IS NULL)  -- NÃO EXISTIA ANTES
				OR (
					PD."DIVISION" <> NS.PDROD_DIVISION
					OR PD.PRODUCT_GROUP_1 <> NS.PDROD_PRODUCT_GROUP
					OR PD.PRODUCT_1 <> NS.PDROD_PRODUCT
					OR PD.ATTB01 <> NS.PROD_ATTB_1
					OR PD.SEDA_BU_ESTORE <> NS.SEDA_BU_ESTORE
					OR PD.SEDA_DIVISION_ESTORE <> NS.SEDA_DIVISION_ESTORE
					OR PD.SEDA_CATEGORY_ESTORE <> NS.SEDA_CATEGORY_ESTORE
					OR PD.SEDA_FAMILY_ESTORE <> NS.SEDA_FAMILY_ESTORE
					OR PD.SEDA_DESC_ESTORE <> NS.SEDA_DESC_ESTORE
				)
	;
	
END