CREATE PROCEDURE OW_MD.PROC_VTEX_PURCHASE_ORDER_PAYMENT
LANGUAGE SQLSCRIPT as
BEGIN
--Truncate table OW_MD.TF_VTEX_ORDER_PAYMENT_01
TRUNCATE TABLE OW_MD.TF_VTEX_PURCHASE_ORDER_PAYMENT_01; 
--Insert na tabela  OW_MD.TF_VTEX_ORDER_PAYMENT_01
INSERT INTO OW_MD.TF_VTEX_PURCHASE_ORDER_PAYMENT_01 
(SUR_KEY_VTEX_PURCHASE_ORDER_TRACKING,SUR_KEY_VTEX_PAYMENT_GROUP,CREATE_DATE)
SELECT DISTINCT FVPOT.SUR_KEY AS SUR_KEY_VTEX_PURCHASE_ORDER_TRACKING,
 				 DVPG.SUR_KEY AS SUR_KEY_VTEX_PAYMENT_GROUP,
 				 NOW() AS CREATE_DATE
  
 FROM (
SELECT DISTINCT ORDER_ID, (CASE WHEN UPPER(PAYMENT_SYSTEM_NAME)  LIKE '%VALOR ASSUMIDO%' THEN 'Valor Assumido' ELSE PAYMENT_GROUP END) AS PAYMENT_GROUP,
 (CASE WHEN UPPER(PAYMENT_SYSTEM_NAME)  LIKE '%VALOR ASSUMIDO%' THEN 'Valor Assumido' ELSE PAYMENT_SYSTEM_NAME END) AS PAYMENT_SYSTEM_NAME, PAYMENT_SYSTEM FROM 
U_PRJ_ECOM.RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_PAYMENT
--where ORDER_ID = 'SGP-1275500572128-01' --WHERE  ORDER_ID IN ('SSG-1151580127153-01', '1151580127153-01')
UNION
SELECT DISTINCT ORDER_ID, (CASE WHEN UPPER(PAYMENT_SYSTEM_NAME)  LIKE '%VALOR ASSUMIDO%' THEN 'Valor Assumido' ELSE PAYMENT_GROUP END) AS PAYMENT_GROUP, 
(CASE WHEN UPPER(PAYMENT_SYSTEM_NAME)  LIKE '%VALOR ASSUMIDO%' THEN 'Valor Assumido' ELSE PAYMENT_SYSTEM_NAME END) AS PAYMENT_SYSTEM_NAME, PAYMENT_SYSTEM FROM 
U_PRJ_ECOM.RAW_VTEX_SSG_BR_SALES_ORDER_PAYMENT
--where ORDER_ID = 'SGP-1275500572128-01' --WHERE  ORDER_ID IN ('SSG-1151580127153-01', '1151580127153-01')
) SOP 
INNER JOIN OW_MD.FT_VTEX_PURCHASE_ORDER_TRACKING FVPOT ON ( SOP.ORDER_ID = FVPOT.ORDER_ID OR SOP.ORDER_ID = FVPOT.MARKETPLACE_ORDER_ID)
INNER JOIN OW_MD.DIM_VTEX_PAYMENT_GROUP DVPG 
ON (1=1 --AND SOP.PAYMENT_GROUP = DVPG.PAYMENT_GROUP     -- Comentado para considerar os registros da BR_SALES_ORDER_PAYMENT
--AND SOP.PAYMENT_SYSTEM_NAME = DVPG.PAYMENT_SYSTEM_NAME -- Comentado para considerar os registros da BR_SALES_ORDER_PAYMENT
AND SOP.PAYMENT_SYSTEM = DVPG.PAYMENT_SYSTEM)
--WHERE  SOP.PAYMENT_GROUP IS NOT NULL   -- Comentado para considerar os registros da BR_SALES_ORDER_PAYMENT
; 
/* -- FORMA ANTIGA, muitos registros desnecessários
SELECT FVPOT.SUR_KEY AS SUR_KEY_VTEX_PURCHASE_ORDER_TRACKING,
DVPG.SUR_KEY AS SUR_KEY_VTEX_PAYMENT_GROUP,
NOW() AS CREATE_DATE
FROM OW_MD.FT_VTEX_PURCHASE_ORDER_TRACKING FVPOT,
OW_MD.DIM_VTEX_PAYMENT_GROUP DVPG 
;
*/
-- TRUNCAR A TABELA COM VALORES DIFERENTES DE VALOR ASSUMIDO
TRUNCATE TABLE OW_MD.TF_VTEX_PURCHASE_ORDER_PAYMENT_02;
--Insert na tabela  OW_MD.TF_VTEX_ORDER_PAYMENT_02
INSERT INTO OW_MD.TF_VTEX_PURCHASE_ORDER_PAYMENT_02
(SUR_KEY_VTEX_PURCHASE_ORDER_TRACKING, SUR_KEY_VTEX_PAYMENT_GROUP,CREATE_DATE)
SELECT SUR_KEY_VTEX_PURCHASE_ORDER_TRACKING, SUR_KEY_VTEX_PAYMENT_GROUP,CREATE_DATE
FROM OW_MD.TF_VTEX_PURCHASE_ORDER_PAYMENT_01
WHERE SUR_KEY_VTEX_PAYMENT_GROUP != 1;
-- TRUNCAR A TABELA COM VALORES IGUAIS A VALOR ASSUMIDO
TRUNCATE TABLE OW_MD.TF_VTEX_PURCHASE_ORDER_PAYMENT_03;
--Insert na tabela  OW_MD.TF_VTEX_ORDER_PAYMENT_03
INSERT INTO OW_MD.TF_VTEX_PURCHASE_ORDER_PAYMENT_03
(SUR_KEY_VTEX_PURCHASE_ORDER_TRACKING, SUR_KEY_VTEX_PAYMENT_GROUP,CREATE_DATE)
SELECT SUR_KEY_VTEX_PURCHASE_ORDER_TRACKING, SUR_KEY_VTEX_PAYMENT_GROUP,CREATE_DATE 
FROM OW_MD.TF_VTEX_PURCHASE_ORDER_PAYMENT_01
WHERE SUR_KEY_VTEX_PAYMENT_GROUP = 1;
-- TRUNCAR A TABELA DE TRANSFORMAÇÃO FINAL COM O UNION 
TRUNCATE TABLE OW_MD.TF_VTEX_PURCHASE_ORDER_PAYMENT_04;
--Insert na tabela  OW_MD.TF_VTEX_ORDER_PAYMENT_04 (para order que tenha valor assumido e outro tipo de pagamento considerar apenas outro tipo)
INSERT INTO OW_MD.TF_VTEX_PURCHASE_ORDER_PAYMENT_04
(SUR_KEY_VTEX_PURCHASE_ORDER_TRACKING, SUR_KEY_VTEX_PAYMENT_GROUP,CREATE_DATE)
SELECT SUR_KEY_VTEX_PURCHASE_ORDER_TRACKING, SUR_KEY_VTEX_PAYMENT_GROUP,CREATE_DATE FROM 
( 
SELECT SUR_KEY_VTEX_PURCHASE_ORDER_TRACKING, SUR_KEY_VTEX_PAYMENT_GROUP,CREATE_DATE FROM 
OW_MD.TF_VTEX_PURCHASE_ORDER_PAYMENT_02
UNION ALL 
SELECT SUR_KEY_VTEX_PURCHASE_ORDER_TRACKING, SUR_KEY_VTEX_PAYMENT_GROUP,CREATE_DATE FROM 
OW_MD.TF_VTEX_PURCHASE_ORDER_PAYMENT_03 
WHERE SUR_KEY_VTEX_PURCHASE_ORDER_TRACKING NOT IN ( SELECT DISTINCT SUR_KEY_VTEX_PURCHASE_ORDER_TRACKING FROM 
OW_MD.TF_VTEX_PURCHASE_ORDER_PAYMENT_02 )
);
MERGE INTO OW_MD.FT_VTEX_PURCHASE_ORDER_PAYMENT O 
USING OW_MD.TF_VTEX_PURCHASE_ORDER_PAYMENT_04 M 
ON  O.SUR_KEY_VTEX_PURCHASE_ORDER_TRACKING = M.SUR_KEY_VTEX_PURCHASE_ORDER_TRACKING  AND
    O.SUR_KEY_VTEX_PAYMENT_GROUP = M.SUR_KEY_VTEX_PAYMENT_GROUP 
    WHEN MATCHED 
    THEN UPDATE
    SET O.SUR_KEY_VTEX_PURCHASE_ORDER_TRACKING = M.SUR_KEY_VTEX_PURCHASE_ORDER_TRACKING ,
    O.SUR_KEY_VTEX_PAYMENT_GROUP = M.SUR_KEY_VTEX_PAYMENT_GROUP, 
    O.UPDATE_DATE = M.CREATE_DATE
 WHEN NOT MATCHED   
 THEN INSERT (SUR_KEY_VTEX_PURCHASE_ORDER_TRACKING, SUR_KEY_VTEX_PAYMENT_GROUP, CREATE_DATE) VALUES (M.SUR_KEY_VTEX_PURCHASE_ORDER_TRACKING, M.SUR_KEY_VTEX_PAYMENT_GROUP, M.CREATE_DATE)
 ;
END;