CREATE PROCEDURE OW_MD.PROC_DIM_VTEX_PURCHASE_ORDER_WAREHOUSE
LANGUAGE SQLSCRIPT as
BEGIN
--Truncate table OW_MD.TF_VTEX_PURCHASE_ORDER_WAREHOUSE, tabela de armazem
TRUNCATE TABLE OW_MD.TF_VTEX_PURCHASE_ORDER_WAREHOUSE;
--Insert na tabela de temporária de ORDER WAREHOUSE
INSERT INTO OW_MD.TF_VTEX_PURCHASE_ORDER_WAREHOUSE
(WAREHOUSE_ID)
SELECT * FROM (
SELECT DISTINCT 
WAREHOUSE_ID
FROM "U_PRJ_ECOM"."RAW_VTEX_SSG_BR_SALES_ORDER_SHIPPING"
UNION
SELECT DISTINCT 
WAREHOUSE_ID
FROM "U_PRJ_ECOM"."RAW_VTEX_SSG_BR_SHOP_SALES_ORDER_SHIPPING"
)
WHERE WAREHOUSE_ID IS NOT NULL 
ORDER BY WAREHOUSE_ID ASC;
--Merge entre a tabela temporária e a Tabela de dimensão de armazem
MERGE INTO OW_MD.DIM_VTEX_PURCHASE_ORDER_WAREHOUSE O
USING OW_MD.TF_VTEX_PURCHASE_ORDER_WAREHOUSE M 
ON O.WAREHOUSE_ID = M.WAREHOUSE_ID
 WHEN MATCHED 
 THEN UPDATE 
 SET O.WAREHOUSE_ID = M.WAREHOUSE_ID
 
 WHEN NOT MATCHED 
 THEN INSERT ("WAREHOUSE_ID") VALUES(M."WAREHOUSE_ID");
END;