
CREATE PROCEDURE OW_MD.PROC_INGESTION_ODS_MEDALIA_TARGET_NPS
	LANGUAGE SQLSCRIPT
	SQL SECURITY INVOKER 
AS 
BEGIN 
DELETE FROM OW_MD.ODS_MEDALIA_TARGET_NPS;
INSERT INTO OW_MD.ODS_MEDALIA_TARGET_NPS
WITH SEQUENCIAL AS (
SELECT 
	   SUBSIDIARY
  	 , YEAR
	 , WEEK
 	 , FACTOR_IMPACT
	 , TARGET_NPS
	 , LOAD_DATE
	 , FILE_NAME 
	 , RANK() OVER(PARTITION BY SUBSIDIARY, YEAR, WEEK, FACTOR_IMPACT ORDER BY LOAD_DATE DESC) AS SEQ
FROM OW_MD.RAW_MEDALIA_TARGET_NPS		
WHERE 1=1 
ORDER BY SUBSIDIARY, YEAR, WEEK, FACTOR_IMPACT, SEQ 
)
SELECT 
	   SUBSIDIARY
  	 , YEAR
	 , WEEK
 	 , FACTOR_IMPACT
	 , TARGET_NPS
	 , LOAD_DATE 
	 , FILE_NAME
FROM SEQUENCIAL
WHERE 1=1
	AND SEQ = 1;
	
END