CREATE PROCEDURE OW_SEDA_S.PRC_CE_UPDT_SHOPPING_W_BRANDSHOP AS 
--DO
BEGIN 
	
tmp=
SELECT DISTINCT SHOPPING_CENTER_STORE FROM OW_SEDA_S.MAP_CE_STORES mcs WHERE ACCOUNT = 'BRAND SHOP' AND SHOPPING_CENTER_STORE IS NOT NULL;
UPDATE mcs SET
	shopping_with_brand_shop = 
	CASE 
		WHEN mcs.SHOPPING_CENTER_STORE IS NOT NULL THEN 'Yes'
		ELSE 'No'
	END
FROM OW_SEDA_S.MAP_CE_STORES mcs 
LEFT JOIN :tmp tmp ON mcs.SHOPPING_CENTER_STORE = tmp.SHOPPING_CENTER_STORE;
	
END;