CREATE PROCEDURE OW_SEDA_S.PRC_CE_UPDATE_ESES_ON_PIVOT AS 
--DO 
BEGIN 
	
TMP=
SELECT 
	COALESCE(SITE_ID, 'C820_47960950094517_SP') SITE_ID, 
	ITEM, 
	WEEKNUM, 
	SUM(SELL_OUT) sell_out, 
	SUM(COALESCE(INVENTORY, 0)) inventory,
	0 stock_out,
	0 dead_inventory,
	0 dead_sku,
	0 channel_inv,
	0 cust_sales,
	0 booking_confirmed,
	AVG(RRP) RRP,
	NULL estimated_sales_lost,
	0 inv_wo_display
FROM OW_SEDA_S.FT_CE_DAILY_PIVOT fcdp 
WHERE 1=1
	AND LEFT(WEEKNUM, 4) = 2023
	AND ACCOUNT LIKE '%E-SES%'
	AND WEEKNUM <= (SELECT MAX(WEEKNUM) from OW_SEDA_S.FT_CE_PIVOT WHERE INVENTORY > 0)
GROUP BY
	COALESCE(SITE_ID, 'C820_47960950094517_SP'), 
	ITEM, 
	WEEKNUM;
DELETE FROM OW_SEDA_S.FT_CE_PIVOT fcp 
WHERE 1=1
	AND EXISTS (SELECT 1 FROM OW_SEDA_S.MAP_CE_STORES mcs WHERE mcs.SITE_ID = fcp.SITE_ID AND mcs.ACCOUNT IN ('E-STORE'))
	AND EXISTS (SELECT 1 FROM :TMP t WHERE t.WEEKNUM = fcp.WEEKNUM);
INSERT INTO OW_SEDA_S.FT_CE_PIVOT
SELECT * FROM :TMP;
END;