CREATE PROCEDURE OW_SEDA_S.PRC_CE_UPDATE_GFK AS 
BEGIN 
UPDATE OW_SEDA_S.MAP_CE_STORES
SET GFK_REGION =  
	CASE
		WHEN SIGLA_DA_UF_STORE IN ('CE','RN','PB','PE','AL','SE','BA') THEN 'Region 1: NE'
		WHEN SIGLA_DA_UF_STORE IN ('PR','SC','RS') THEN 'Region 6: PR, SC, RS'
		WHEN SIGLA_DA_UF_STORE IN ('GO','DF','MS') THEN 'Region 7'
		WHEN SIGLA_DA_UF_STORE IN ('MT','RO','TO') THEN 'Region 8'
		WHEN SIGLA_DA_UF_STORE IN ('PA','AP','MA','PI') THEN 'Region 9'
		WHEN SIGLA_DA_UF_STORE IN ('AM','AC','RR') THEN 'Region 10'
		WHEN SIGLA_DA_UF_STORE IN ('MG','ES') THEN 'Region 2: I-RJ, MG, ES'
		WHEN SIGLA_DA_UF_STORE IN ('RJ') AND NOME_DA_REGIAO_METROPOLITANA_STORE <> 'RM RIO DE JANEIRO' THEN 'Region 2: I-RJ, MG, ES'
		WHEN NOME_DA_REGIAO_METROPOLITANA_STORE = 'RM RIO DE JANEIRO' THEN 'Region 3: G-RJ'
		WHEN NOME_DA_REGIAO_METROPOLITANA_STORE = 'RM SAO PAULO' THEN 'Region 4: G-SP'
		WHEN SIGLA_DA_UF_STORE IN ('SP') AND NOME_DA_REGIAO_METROPOLITANA_STORE <> 'RM SAO PAULO' THEN 'Region 5: I-SP'
	  END
WHERE 1=1
	AND STORE_TYPE IN ('Mobile','Reg. Stores','Virtual', 'Online', 'SES', 'Carriers')
	AND GFK_REGION IS NULL;
END;