CREATE PROCEDURE OW_SEDA_S.PRC_CE_UPDATE_CHANNEL_READY (WEEKNUM_REF INT, CHANNEL_REF VARCHAR(45)) AS 
--DO 
BEGIN
	
TMP_FILTER=
SELECT 
	WEEKNUM, MAX(SELL_OUT_DATE) LAST_DAY_OF_WEEK
FROM OW_SEDA_S.FT_CE_DAILY_PIVOT
WHERE 1=1
	AND WEEKNUM = WEEKNUM_REF
	AND INVENTORY > 0 
GROUP BY WEEKNUM;
	
TMP_AUX=
SELECT
	fcdp.*
	, tf.LAST_DAY_OF_WEEK,
	CASE 
		WHEN tf.LAST_DAY_OF_WEEK = fcdp.SELL_OUT_DATE THEN INVENTORY 
		ELSE 0
	END LAST_DAY_INVENTORY
FROM OW_SEDA_S.FT_CE_DAILY_PIVOT fcdp 
INNER JOIN OW_SEDA_S.MAP_CE_STORES mcs ON mcs.SITE_ID = fcdp.SITE_ID 
INNER JOIN OW_SEDA_S.MAP_CE_PRODUCTS mcp ON mcp.ITEM = fcdp.ITEM 
INNER JOIN :TMP_FILTER tf ON fcdp.WEEKNUM = tf.WEEKNUM
WHERE 1=1
	AND mcs.CHANNEL = CHANNEL_REF;
	
TMP_COMPLETE=
SELECT
	'Sell Out' AS "PARAMETER",
	WEEKNUM,
	SITE_ID,
	ITEM,
	SUM(SELL_OUT) AS "DATA",
	'FT_CE_DAILY_PIVOT' AS REPORT,
	CURRENT_DATE
FROM :TMP_AUX
GROUP BY 
	WEEKNUM,
	SITE_ID,
	ITEM
HAVING SUM(SELL_OUT) <> 0
UNION ALL 
SELECT
	'Inventory' AS "PARAMETER",
	WEEKNUM,
	SITE_ID,
	ITEM,
	SUM(LAST_DAY_INVENTORY) AS "DATA",
	'FT_CE_DAILY_PIVOT' AS REPORT,
	CURRENT_DATE
FROM :TMP_AUX
GROUP BY 
	WEEKNUM,
	SITE_ID,
	ITEM
HAVING SUM(LAST_DAY_INVENTORY) <> 0;
DELETE FROM OW_SEDA_S.FT_CE_READY fcp 
WHERE 1=1
	AND EXISTS (SELECT 1 FROM OW_SEDA_S.MAP_CE_STORES mcp WHERE fcp.SITE_ID = mcp.SITE_ID AND mcp.CHANNEL = CHANNEL_REF)
	AND fcp.WEEKNUM = WEEKNUM_REF;
INSERT INTO OW_SEDA_S.FT_CE_READY
SELECT * FROM :TMP_COMPLETE;
END;