CREATE PROCEDURE OW_SEDA_S.PRC_CE_STORE_EDI AS 
--DO
BEGIN 
DELETE FROM OW_SEDA_S.ODS_CE_STORE_EDI WHERE LEFT(WEEKNUM, 4) = 2023;
	
INSERT INTO OW_SEDA_S.ODS_CE_STORE_EDI
SELECT SITE_ID, ITEM, WEEKNUM, "Sell Out" SELL_OUT, INVENTORY, "Channel Inv." CHANNEL_INVENTORY, "Cust. Sales" CUSTOMER_SALES FROM OW_SEDA_S.FT_CE_PIVOT fcp 
WHERE 1=1
	AND LEFT(WEEKNUM, 4) >= 2023
	AND WEEKNUM <= (SELECT MAX(WEEKNUM) from OW_SEDA_S.FT_CE_PIVOT WHERE INVENTORY > 0);
END;