CREATE PROCEDURE OW_SEDA_S.PRC_CE_AMAZON_PRIME_DAY AS 
--DO 
BEGIN 
	
TMP=
SELECT * FROM (
	SELECT 
		fcst.*,
		t.TIMESTAMP_REF,
		t.FCST_PERIOD_CONSIDERED,
		t.NUMBER_OF_FCST_PERIOD_CONSIDERED,
		CASE 
			WHEN WEEKNUM = 202328 AND TO_DATE(TIMESTAMP_REF) = '2023-07-11' THEN ROUND(fcst.SELL_OUT_FCST_1 * FCST_PERIOD_CONSIDERED / NUMBER_OF_FCST_PERIOD_CONSIDERED, 0)
			WHEN WEEKNUM = 202328 AND TO_DATE(TIMESTAMP_REF) = '2023-07-12' THEN ROUND(fcst.SELL_OUT_FCST_2 * FCST_PERIOD_CONSIDERED / NUMBER_OF_FCST_PERIOD_CONSIDERED, 0)
			WHEN WEEKNUM = 202328 AND TO_DATE(TIMESTAMP_REF) = '2023-07-13' THEN ROUND(fcst.SELL_OUT_FCST_3 * FCST_PERIOD_CONSIDERED / NUMBER_OF_FCST_PERIOD_CONSIDERED, 0)
			WHEN WEEKNUM = 202328 AND TO_DATE(TIMESTAMP_REF) = '2023-07-14' THEN ROUND(fcst.SELL_OUT_FCST_4 * FCST_PERIOD_CONSIDERED / NUMBER_OF_FCST_PERIOD_CONSIDERED, 0)
			WHEN WEEKNUM = 202328 AND TO_DATE(TIMESTAMP_REF) = '2023-07-15' THEN ROUND(fcst.SELL_OUT_FCST_5 * FCST_PERIOD_CONSIDERED / NUMBER_OF_FCST_PERIOD_CONSIDERED, 0)
			WHEN WEEKNUM = 202328 AND TO_DATE(TIMESTAMP_REF) = '2023-07-16' THEN ROUND(fcst.SELL_OUT_FCST_6 * FCST_PERIOD_CONSIDERED / NUMBER_OF_FCST_PERIOD_CONSIDERED, 0)
			WHEN WEEKNUM = 202341 AND TO_DATE(TIMESTAMP_REF) = '2023-10-10' THEN ROUND(fcst.SELL_OUT_FCST_1 * FCST_PERIOD_CONSIDERED / NUMBER_OF_FCST_PERIOD_CONSIDERED, 0)
			WHEN WEEKNUM = 202341 AND TO_DATE(TIMESTAMP_REF) = '2023-10-11' THEN ROUND(fcst.SELL_OUT_FCST_2 * FCST_PERIOD_CONSIDERED / NUMBER_OF_FCST_PERIOD_CONSIDERED, 0)
			WHEN WEEKNUM = 202341 AND TO_DATE(TIMESTAMP_REF) = '2023-10-12' THEN ROUND(fcst.SELL_OUT_FCST_3 * FCST_PERIOD_CONSIDERED / NUMBER_OF_FCST_PERIOD_CONSIDERED, 0)
			WHEN WEEKNUM = 202341 AND TO_DATE(TIMESTAMP_REF) = '2023-10-13' THEN ROUND(fcst.SELL_OUT_FCST_4 * FCST_PERIOD_CONSIDERED / NUMBER_OF_FCST_PERIOD_CONSIDERED, 0)
			WHEN WEEKNUM = 202341 AND TO_DATE(TIMESTAMP_REF) = '2023-10-14' THEN ROUND(fcst.SELL_OUT_FCST_5 * FCST_PERIOD_CONSIDERED / NUMBER_OF_FCST_PERIOD_CONSIDERED, 0)
			WHEN WEEKNUM = 202341 AND TO_DATE(TIMESTAMP_REF) = '2023-10-15' THEN ROUND(fcst.SELL_OUT_FCST_6 * FCST_PERIOD_CONSIDERED / NUMBER_OF_FCST_PERIOD_CONSIDERED, 0)
		END FCST_BY_HOUR
	FROM OW_SEDA_S.ODS_CE_AMAZON_SELL_OUT_FCST fcst
	CROSS JOIN (
	SELECT 
		*,
		CASE 
			WHEN HOUR(TIMESTAMP_REF) BETWEEN 10 AND 22 THEN 1.3
			ELSE 0.65
		END FCST_PERIOD_CONSIDERED,
		COUNT(
		CASE 
			WHEN HOUR(TIMESTAMP_REF) BETWEEN 10 AND 22 THEN 1.3
			ELSE 0.65
		END
		) OVER (PARTITION BY TO_DATE(TIMESTAMP_REF)) NUMBER_OF_FCST_PERIOD_CONSIDERED
	FROM (
		SELECT
			 GENERATED_PERIOD_START as ID,
			 ADD_SECONDS (TO_TIMESTAMP ('2023-07-06 00:00:00'), 60*30*GENERATED_PERIOD_START) TIMESTAMP_REF
		FROM SERIES_GENERATE_INTEGER(1,0,10001) 
		WHERE 1=1 
			AND TO_DATE(ADD_SECONDS (TO_TIMESTAMP ('2023-07-06 00:00:00'), 60*30*GENERATED_PERIOD_START)) IN ('2023-07-11', '2023-07-12', '2023-07-13', '2023-07-14', '2023-07-15', '2023-07-16', '2023-10-10', '2023-10-11', '2023-10-12', '2023-10-13', '2023-10-14', '2023-10-15'))
	) t
	WHERE 1=1
		--AND fcst.ITEM = 'UN60BU8000GXZD'
) WHERE FCST_BY_HOUR IS NOT NULL
	;
TMP_AUX=
SELECT
	fcas.ASIN,
	fcas.ITEM,
	fcas.NET_OPS,
	fcas.NET_UNITS,
	ADD_SECONDS(fcas.REPORT_DATE, - 3 * 60 * 60) REPORT_DATE,
	fcas.FILE_NAME,
	fcas.LOAD_DATE,
	CASE 
		WHEN SUM(t.FCST_BY_HOUR) IS NULL AND fcas.NET_UNITS >= 0 THEN NET_UNITS 
		WHEN SUM(t.FCST_BY_HOUR) IS NULL AND fcas.NET_UNITS < 0 THEN 0 
		ELSE SUM(t.FCST_BY_HOUR)
	END FCST_BY_HOUR,
	DENSE_RANK() OVER (PARTITION BY fcas.ITEM ORDER BY REPORT_DATE DESC) MOST_RECENT_INFO
FROM OW_SEDA_S.FT_CE_AMAZON_SELL_OUT fcas
INNER JOIN OW_SEDA_S.VW_CE_CALENDAR vcc ON TO_DATE(fcas.REPORT_DATE) = TO_DATE(vcc."DATE")
LEFT JOIN :TMP t ON 1=1
		AND fcas.ITEM = t.ITEM
		AND vcc.YEARWEEK = t.WEEKNUM
		AND fcas.REPORT_DATE >= t.TIMESTAMP_REF
GROUP BY 
	fcas.ASIN,
	fcas.NET_OPS,
	fcas.NET_UNITS,
	fcas.REPORT_DATE,
	fcas.FILE_NAME,
	fcas.ITEM,
	fcas.LOAD_DATE;
TRUNCATE TABLE OW_SEDA_S.FT_CE_AMAZON_PRIME_DAY;
INSERT INTO OW_SEDA_S.FT_CE_AMAZON_PRIME_DAY
SELECT 
	ta.*,
	COALESCE(inv.ESTOQUE, 0) INITIAL_INVENTORY,
	CASE 
		WHEN ta.MOST_RECENT_INFO = 1 THEN COALESCE(inv.ESTOQUE, 0) - ta.NET_UNITS
		ELSE 0
	END EST_INVENTORY
FROM :TMP_AUX ta
LEFT JOIN (
	SELECT 
		ASIN,
		ITEM,
		DATA,
		VENDA,
		ESTOQUE
	FROM (
		SELECT 
			*,
			DENSE_RANK() OVER (ORDER BY "DATA" DESC) MOST_RECENT_INVENTORY
		FROM OW_SEDA_S.ODS_CE_AMAZON_INVENTORY
	) WHERE MOST_RECENT_INVENTORY = 1
) inv ON inv.ITEM = ta.ITEM;
END;