CREATE PROCEDURE OW_SEDA_S.PRC_MX_API_OMNITRACKING_FULL(YEAR_REF INT, MONTH_REF INT) AS 
--DO
BEGIN
TMP_FILTER=
SELECT
	PRODUCT_NAME,
	CATEGORY_NAME,
	BRAND_NAME,
	LINK_COLOR,
	DAY_COLLECT,
	HOUR_COLLECT,
	MARKETPLACE_NAME STORE,
	CASE WHEN MARKETPLACE_NAME = PMU_SELLER THEN '-' ELSE PMU_SELLER END MARKET_PLACE,
	SPOT_PRICE,
	FORWARD_PRICE,
	SCREENSHOT_URL,
	URL,
	COLLECTED_SELLER,
	TITLE,
	TYPE_SELLER,
	PRICE_FROM,
	LOAD_DATE
FROM OW_SEDA_S.RAW_SEDA_API_OMNITRACKING rsao
WHERE 1=1
	AND STATUS = 'COLETADO'
	AND TYPE_COLLECT = 'COLETA PADRÃO'
	AND SPOT_PRICE IS NOT NULL
	AND YEAR(DAY_COLLECT) = YEAR_REF
	AND MONTH(DAY_COLLECT) = MONTH_REF
	--AND EXISTS (SELECT 1 FROM OW_SEDA_S.ODS_MX_REFERENCE_PRICE omrp WHERE UPPER(omrp.PRODUCT_NAME) = rsao.PRODUCT_NAME AND omrp.WEEKNUM = (SELECT MAX(WEEKNUM) FROM OW_SEDA_S.ODS_MX_REFERENCE_PRICE))
	--AND PRODUCT_NAME LIKE '%WATCH 6 LTE 40MM%'
	--AND MARKETPLACE_NAME = 'FAST SHOP'
	--AND LINK_COLOR = 'CINZA'
	--AND DAY_COLLECT ='2024-06-03'
	;
TMP_MODE_SPOT=
SELECT 
	*, 
	DENSE_RANK() OVER (PARTITION BY PRODUCT_NAME, BRAND_NAME, LINK_COLOR, DAY_COLLECT, STORE, MARKET_PLACE ORDER BY COUNT_PRICES DESC) FILTER_MODE 
FROM (
	SELECT
		PRODUCT_NAME,
		CATEGORY_NAME,
		BRAND_NAME,
		LINK_COLOR,
		STORE,
		MARKET_PLACE,
		DAY_COLLECT,
		SPOT_PRICE,
		COUNT(1) COUNT_PRICES
	FROM :TMP_FILTER
	WHERE SPOT_PRICE IS NOT NULL
	GROUP BY 
		PRODUCT_NAME,
		CATEGORY_NAME,
		BRAND_NAME,
		LINK_COLOR,
		STORE,
		MARKET_PLACE,
		DAY_COLLECT,
		SPOT_PRICE);
	
TMP_MODE_FORWARD=
SELECT 
	*, 
	DENSE_RANK() OVER (PARTITION BY PRODUCT_NAME, BRAND_NAME, LINK_COLOR, DAY_COLLECT, STORE, MARKET_PLACE ORDER BY COUNT_PRICES DESC) FILTER_MODE 
FROM (
	SELECT
		PRODUCT_NAME,
		CATEGORY_NAME,
		BRAND_NAME,
		LINK_COLOR,
		STORE,
		MARKET_PLACE,
		DAY_COLLECT,
		FORWARD_PRICE,
		COUNT(1) COUNT_PRICES
	FROM :TMP_FILTER
	WHERE FORWARD_PRICE IS NOT NULL
	GROUP BY 
		PRODUCT_NAME,
		CATEGORY_NAME,
		BRAND_NAME,
		LINK_COLOR,
		STORE,
		MARKET_PLACE,
		DAY_COLLECT,
		FORWARD_PRICE);
TMP_RECENT_PRICE=
SELECT
	PRODUCT_NAME,
	CATEGORY_NAME,
	BRAND_NAME,
	LINK_COLOR,
	STORE,
	MARKET_PLACE,
	DAY_COLLECT,
	HOUR_COLLECT,
	SPOT_PRICE,
	FORWARD_PRICE,
	SCREENSHOT_URL,
	URL,
	DENSE_RANK() OVER (PARTITION BY PRODUCT_NAME, BRAND_NAME, LINK_COLOR, DAY_COLLECT, STORE, MARKET_PLACE ORDER BY DAY_COLLECT, HOUR_COLLECT DESC, LENGTH(URL) ASC) FILTER_RECENT
FROM :TMP_FILTER
GROUP BY 
	PRODUCT_NAME,
	CATEGORY_NAME,
	BRAND_NAME,
	LINK_COLOR,
	STORE,
	MARKET_PLACE,
	DAY_COLLECT,
	HOUR_COLLECT,
	SPOT_PRICE,
	FORWARD_PRICE,
	SCREENSHOT_URL,
	URL;
TMP_AUX=
SELECT
	tf.PRODUCT_NAME,
	tf.CATEGORY_NAME,
	tf.BRAND_NAME,
	tf.LINK_COLOR,
	tf.DAY_COLLECT,
	tf.STORE,
	tf.MARKET_PLACE,
	AVG(tf.SPOT_PRICE) AVG_SPOT_PRICE,
	MIN(tf.SPOT_PRICE) MIN_SPOT_PRICE,
	MAX(tf.SPOT_PRICE) MAX_SPOT_PRICE,
	AVG(tf.FORWARD_PRICE) AVG_FORWARD_PRICE,
	MIN(tf.FORWARD_PRICE) MIN_FORWARD_PRICE,
	MAX(tf.FORWARD_PRICE) MAX_FORWARD_PRICE,
	tf.COLLECTED_SELLER,
	tf.TITLE,
	tf.TYPE_SELLER,
	MAX(tf.PRICE_FROM) PRICE_FROM,
	MAX(tf.LOAD_DATE) LOAD_DATE
FROM :TMP_FILTER tf
GROUP BY
	tf.PRODUCT_NAME,
	tf.CATEGORY_NAME,
	tf.BRAND_NAME,
	tf.LINK_COLOR,
	tf.DAY_COLLECT,
	tf.STORE,
	tf.MARKET_PLACE,
	tf.COLLECTED_SELLER,
	tf.TITLE,
	tf.TYPE_SELLER;
TMP_COMPLETE=
SELECT 
	tf.PRODUCT_NAME,
	tf.CATEGORY_NAME,
	tf.BRAND_NAME,
	tf.LINK_COLOR,
	tf.DAY_COLLECT,
	tf.STORE,
	tf.MARKET_PLACE,
	tf.AVG_SPOT_PRICE,
	tf.MIN_SPOT_PRICE,
	tf.MAX_SPOT_PRICE,
	tms.SPOT_PRICE MODE_SPOT_PRICE,
	trp.SPOT_PRICE RECENT_SPOT_PRICE,
	tf.AVG_FORWARD_PRICE,
	tf.MIN_FORWARD_PRICE,
	tf.MAX_FORWARD_PRICE,
	tmf.FORWARD_PRICE MODE_FORWARD_PRICE,
	trp.FORWARD_PRICE RECENT_FORWARD_PRICE,
	tf.COLLECTED_SELLER,
	tf.TITLE,
	tf.TYPE_SELLER,
	tf.PRICE_FROM,
	omrp.REFERENCE_PRICE_SPOT,
	omrp.REFERENCE_PRICE_INSTALLMENT,
	trp.SCREENSHOT_URL,
	trp.URL,
	tf.LOAD_DATE,
	vcc.YEARWEEK WEEKNUM
FROM :TMP_AUX tf
INNER JOIN (SELECT * FROM :TMP_MODE_SPOT WHERE FILTER_MODE = 1) tms
ON 1=1
	AND tf.PRODUCT_NAME = tms.PRODUCT_NAME
	AND tf.CATEGORY_NAME = tms.CATEGORY_NAME
	AND tf.BRAND_NAME = tms.BRAND_NAME
	AND tf.LINK_COLOR = tms.LINK_COLOR
	AND tf.DAY_COLLECT = tms.DAY_COLLECT
	AND tf.STORE = tms.STORE
	AND tf.MARKET_PLACE = tms.MARKET_PLACE
INNER JOIN (SELECT * FROM :TMP_RECENT_PRICE WHERE FILTER_RECENT = 1) trp
ON 1=1
	AND tf.PRODUCT_NAME = trp.PRODUCT_NAME
	AND tf.CATEGORY_NAME = trp.CATEGORY_NAME
	AND tf.BRAND_NAME = trp.BRAND_NAME
	AND tf.LINK_COLOR = trp.LINK_COLOR
	AND tf.DAY_COLLECT = trp.DAY_COLLECT
	AND tf.STORE = trp.STORE
	AND tf.MARKET_PLACE = trp.MARKET_PLACE
LEFT JOIN (SELECT * FROM :TMP_MODE_FORWARD WHERE FILTER_MODE = 1) tmf
ON 1=1
	AND tf.PRODUCT_NAME = tmf.PRODUCT_NAME
	AND tf.CATEGORY_NAME = tmf.CATEGORY_NAME
	AND tf.BRAND_NAME = tmf.BRAND_NAME
	AND tf.LINK_COLOR = tmf.LINK_COLOR
	AND tf.DAY_COLLECT = tmf.DAY_COLLECT
	AND tf.STORE = tmf.STORE
	AND tf.MARKET_PLACE = tmf.MARKET_PLACE
INNER JOIN OW_SEDA_S.VW_CE_CALENDAR vcc ON vcc."DATE" = tf.DAY_COLLECT
LEFT JOIN OW_SEDA_S.ODS_MX_REFERENCE_PRICE omrp ON tf.PRODUCT_NAME = UPPER(omrp.PRODUCT_NAME) AND vcc.YEARWEEK = omrp.WEEKNUM;
DELETE FROM OW_SEDA_S.FT_MX_API_OMNITRACKING_FULL fmx
WHERE EXISTS (SELECT 1 FROM :TMP_COMPLETE tc WHERE fmx.DAY_COLLECT = tc.DAY_COLLECT);
INSERT INTO OW_SEDA_S.FT_MX_API_OMNITRACKING_FULL
SELECT
	PRODUCT_NAME,
	CATEGORY_NAME,
	BRAND_NAME,
	LINK_COLOR,
	DAY_COLLECT,
	STORE,
	MARKET_PLACE,
	'Spot' AS PRICE_TYPE,
	AVG_SPOT_PRICE AS AVG_PRICE,
	MIN_SPOT_PRICE AS MIN_PRICE,
	MAX_SPOT_PRICE AS MAX_PRICE,
	MODE_SPOT_PRICE AS MODE_PRICE,
	RECENT_SPOT_PRICE AS RECENT_PRICE,
	COLLECTED_SELLER,
	TITLE,
	TYPE_SELLER,
	PRICE_FROM,
	REFERENCE_PRICE_SPOT REFERENCE_PRICE,
	SCREENSHOT_URL,
	URL,
	LOAD_DATE,
	WEEKNUM
FROM :TMP_COMPLETE
WHERE AVG_SPOT_PRICE IS NOT NULL
UNION ALL 
SELECT
	PRODUCT_NAME,
	CATEGORY_NAME,
	BRAND_NAME,
	LINK_COLOR,
	DAY_COLLECT,
	STORE,
	MARKET_PLACE,
	'Installment' AS PRICE_TYPE,
	AVG_FORWARD_PRICE AS AVG_PRICE,
	MIN_FORWARD_PRICE AS MIN_PRICE,
	MAX_FORWARD_PRICE AS MAX_PRICE,
	MODE_FORWARD_PRICE AS MODE_PRICE,
	RECENT_FORWARD_PRICE AS RECENT_PRICE,
	COLLECTED_SELLER,
	TITLE,
	TYPE_SELLER,
	PRICE_FROM,
	REFERENCE_PRICE_INSTALLMENT REFERENCE_PRICE,
	SCREENSHOT_URL,
	URL,
	LOAD_DATE,
	WEEKNUM
FROM :TMP_COMPLETE
WHERE AVG_FORWARD_PRICE IS NOT NULL;
END;
