CREATE PROCEDURE OW_SEDA_S.PRC_CE_BF_PRECO_SISTEMA (IN NUMBER_OF_DAYS INT) AS
BEGIN
	
TMP_AUX =
SELECT * FROM OW_SEDA_S.ODS_CE_WEBPRICE_API WHERE INPUT_DATE BETWEEN ADD_DAYS(CURRENT_DATE, -1 * NUMBER_OF_DAYS) AND ADD_DAYS(CURRENT_DATE, 1);
	
TRUNCATE TABLE OW_SEDA_S.TMP_CE_BF_PRICE_AGGREGATIONS;
INSERT INTO OW_SEDA_S.TMP_CE_BF_PRICE_AGGREGATIONS
SELECT
	mcs.CHANNEL,
	"EXECUTION DATE" DATE_COLLECTED,
	fcps.ITEM,
	MIN(COALESCE("SPOT PRICE",0.0)) MIN_PRICE,
	MAX(COALESCE("SPOT PRICE",0.0)) MAX_PRICE,
	MAX(mode.PRICE_MODE) MODE_PRICE,
	MAX(mode.COUNT_MODE_PRICES) COUNT_MODE_PRICES, 
	COUNT(fcps."SITE ID") STORES_VISITED,
	COUNT(DISTINCT fcps."SITE ID", fcps.ITEM) COLLECTED_PRICES,
	'Preço Tag' REPORT_TYPE
FROM OW_SEDA_S.FT_CE_PRICE_STORE fcps 
INNER JOIN OW_SEDA_S.MAP_CE_STORES mcs ON mcs.SITE_ID = fcps."SITE ID" 
INNER JOIN (
--#Faz o Calculo da Moda
	SELECT 
		*
	FROM (
		SELECT
			*,
			ROW_NUMBER() OVER (PARTITION BY CHANNEL, ITEM, DATE_COLLECTED ORDER BY CHANNEL, ITEM, DATE_COLLECTED, COUNT_MODE_PRICES DESC, PRICE_MODE ASC) ROW_NUM
		FROM (
			SELECT
				mcs.CHANNEL,
				ITEM,
				"EXECUTION DATE" DATE_COLLECTED,
				COALESCE("SPOT PRICE",0.0) PRICE_MODE,
				COUNT(*) COUNT_MODE_PRICES
			FROM OW_SEDA_S.FT_CE_PRICE_STORE fcps 
			INNER JOIN OW_SEDA_S.MAP_CE_STORES mcs ON mcs.SITE_ID = fcps."SITE ID" 
			WHERE 1=1
				AND COALESCE("SPOT PRICE",0.0) > 0
				AND CATEGORY = 'CTV'
			GROUP BY 
				mcs.CHANNEL,
				ITEM,
				"EXECUTION DATE",
				"SPOT PRICE")
		)
	WHERE 1=1
		AND ROW_NUM = 1
) mode 
	ON 1=1
		AND mode.CHANNEL = mcs.CHANNEL
		AND mode.ITEM = fcps.ITEM 
		AND mode.DATE_COLLECTED = fcps."EXECUTION DATE" 
WHERE 1=1
	AND "EXECUTION DATE" BETWEEN ADD_DAYS(CURRENT_DATE, -1 * NUMBER_OF_DAYS) AND CURRENT_DATE 
	AND CATEGORY = 'CTV'
	AND fcps."SPOT PRICE" NOT LIKE '%ETIQUETA%'
GROUP BY 
	mcs.CHANNEL,
	"EXECUTION DATE",
	fcps.ITEM
UNION ALL 
	
SELECT
	UPPER(wb.STORE_NAME) CHANNEL,
	TO_DATE(wb.INPUT_DATE) DATE_COLLECTED,
	wb.ITEM,
	MIN(wb.PRECO_A_VISTA) MIN_PRICE_COLLECTED,
	MAX(wb.PRECO_A_VISTA) MAX_PRICE_COLLECTED,
	MAX(moda.MODA_PRECO_A_VISTA) MODE_PRICE_COLLECTED,
	MAX(COUNT_MODE_PRICES) COUNT_MODE_PRICES,
	1 STORES_VISITED,
	COUNT(DISTINCT wb.ITEM, wb.STORE_NAME, wb.INPUT_DATE) COLLECTED_PRICES,
	'Preço Online' REPORT_TYPE
FROM :TMP_AUX wb
INNER JOIN OW_SEDA_S.MAP_CE_PRODUCTS mcp ON mcp.ITEM = wb.ITEM 
LEFT JOIN 
(
SELECT ITEM, STORE_NAME, MARKETPLACE_NAME, INPUT_DATE, avg(PRECO_A_VISTA) MODA_PRECO_A_VISTA, MAX(COUNT_MODE_PRICES) COUNT_MODE_PRICES FROM (
	SELECT 
		ITEM, 
		STORE_NAME STORE_NAME, 
		MARKETPLACE_NAME MARKETPLACE_NAME, 
		to_date(INPUT_DATE) INPUT_DATE, 
		PRECO_A_VISTA, 
		COUNT(DISTINCT ITEM, STORE_NAME, MARKETPLACE_NAME, INPUT_DATE) COUNT_MODE_PRICES, 
		ROW_NUMBER() OVER (PARTITION BY ITEM, STORE_NAME, MARKETPLACE_NAME, to_date(INPUT_DATE) ORDER BY COUNT(*) DESC) ROW_NUM
	FROM :TMP_AUX ocwa 
	WHERE 1=1
		--AND ITEM = '32LM625B'
		--AND STORE_NAME = 'Americanas'
		--AND MARKETPLACE_NAME = 'Fast Shop'
	GROUP BY ITEM, STORE_NAME, MARKETPLACE_NAME, to_date(INPUT_DATE), PRECO_A_VISTA)
WHERE row_num = 1
GROUP BY ITEM, STORE_NAME, MARKETPLACE_NAME, INPUT_DATE
) moda
ON 1=1
	AND wb.ITEM = moda.ITEM
	AND wb.STORE_NAME = moda.STORE_NAME
	AND COALESCE(wb.MARKETPLACE_NAME,'-') = COALESCE(moda.MARKETPLACE_NAME,'-')
	AND to_date(wb.INPUT_DATE) = moda.INPUT_DATE
LEFT JOIN 
(
	SELECT 
		ITEM, 
		STORE_NAME STORE_NAME, 
		MARKETPLACE_NAME MARKETPLACE_NAME, 
		to_date(INPUT_DATE) INPUT_DATE, 
		PRECO_A_VISTA,
		INPUT_DATE LOAD_DATE
	FROM :TMP_AUX ocwa 
	WHERE SERIES_ROUND(INPUT_DATE, 'INTERVAL 10 MINUTE') IN (
						SELECT MAX_INPUT_DATE FROM (
							SELECT 
								to_date(INPUT_DATE), 
								SERIES_ROUND(MAX(INPUT_DATE), 'INTERVAL 10 MINUTE') MAX_INPUT_DATE
							FROM :TMP_AUX
							GROUP BY
								to_date(INPUT_DATE)
							)
						)
) recent
ON 1=1
	AND wb.ITEM = recent.ITEM
	AND wb.STORE_NAME = recent.STORE_NAME
	AND COALESCE(wb.MARKETPLACE_NAME,'-') = COALESCE(recent.MARKETPLACE_NAME,'-')
	AND to_date(wb.INPUT_DATE) = recent.INPUT_DATE
WHERE 1=1
	AND wb.MARKETPLACE_NAME IS NULL 
	AND mcp.CATEGORY_ITEM = 'TV'
	--AND wb.ITEM = '43P615'
GROUP BY mcp.BRAND_ITEM, wb.STORE_NAME, wb.MARKETPLACE_NAME, wb.ITEM, TO_DATE(wb.INPUT_DATE);
END;