CREATE PROCEDURE OW_SEDA_S.CONN_TO_SEDA(WEEKNUM INT) AS 
BEGIN
DELETE FROM OW_SEDA_S.EDI_DATA_RAW 
WHERE WEEK = WEEKNUM;
INSERT INTO OW_SEDA_S.EDI_DATA_RAW
SELECT * FROM CONN_SEDA_S_CE.EDI_DATA_RAW_TESTE edrt 
WHERE WEEK = WEEKNUM;
END;