CREATE PROCEDURE OW_SEDA_S.PRC_CE_UPDATE_IBGE_INFO(IN SITE_ID_REF VARCHAR(50)) AS 
BEGIN
UPDATE mcs SET 
mcs.COD_IBGE_GRANDES_REGIOES_STORE = "COD IBGE GRANDE REGIAO",
mcs.NOME_DA_GRANDE_REGIAO_STORE = "NOME DA GRANDE REGIAO",
mcs.COD_IBGE_UF_STORE = "COD IBGE UF",
mcs.SIGLA_DA_UF_STORE = "SIGLA DA UF",
mcs.NOME_DA_UF_STORE = "NOME DA UF",
mcs.COD_IBGE_MESORREGIAO_STORE = "COD IBGE MESORREGIAO",
mcs.NOME_DA_MESORREGIAO_STORE = "NOME DA MESORREGIAO",
mcs.COD_IBGE_MICRORREGIAO_STORE = "COD IBGE MICRORREGIAO",
mcs.NOME_DA_MICRORREGIAO_STORE = "NOME DA MICRORREGIAO",
mcs.COD_IBGE_REGIAO_METROPOLITANA_STORE = "COD IBGE REGIAO METROPOLITANA",
mcs.NOME_DA_REGIAO_METROPOLITANA_STORE = "NOME DA REGIAO METROPOLITANA",
mcs.COD_IBGE_MUNICIPIO_STORE = "COD IBGE MUNICIPIO",
mcs.NOME_DO_MUNICIPIO_STORE = "NOME DO MUNICIPIO",
mcs.COD_IBGE_DISTRITO_STORE = "COD IBGE DISTRITO",
mcs.NOME_DO_DISTRITO_STORE = "NOME DO DISTRITO",
mcs.COD_IBGE_SUBDISTRITO_STORE = "COD IBGE SUBDISTRITO",
mcs.NOME_DO_SUBDISTRITO_STORE = "NOME DO SUBDISTRITO",
mcs.COD_IBGE_BAIRRO_STORE = "COD IBGE BAIRRO"
FROM OW_SEDA_S.MAP_CE_STORES mcs
INNER JOIN OW_SEDA_S.MAP_CE_SETOR_CENSITARIO_2010 msc ON msc."COD IBGE SETOR CENSITARIO" = mcs.COD_IBGE_SETOR_CENSITARIO_STORE 
WHERE 1=1
	AND mcs.SITE_ID = SITE_ID_REF;
END